### ISSUE TITLE
Window/Application Capture for Emulators freezes randomly

### ISSUE THREAD

**Issue by Chromagram** [obsproject/obs-studio#7697] opened 2022-11-01 04:07 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/v5SADwxV9lgtaubO

### Expected Behavior

Application or Window Capture for the emulator should run continuously with no issues. It is one take if the app itself stopped functioning or crashed entirely, but the app itself continues to work fine, and without any notices from OBS itself, when I peek over sometimes at the live feed during stream, the captures have frozen and they don't work.

### Current Behavior

Right now, the capture will work with no issues for an unspecified amount of time. For no discernible reason, here and there, the application/window capture for the emulator will be frozen. When this happens, the video is stuck in OBS and the audio is completely missing. The problem is, OBS doesn't prompt any issues when this happens, so the stream keeps going, and I keep playing my game in my main window and only realize what happens if someone points it out to me in chat.

To note, I initially thought it was the emulator I was using, melonDS. I fiddled with the window, video and audio settings, and nothing helped. So I quit stream, and for my next test stream, I used OpenEmu instead. Same issues.

### Steps to Reproduce

1. Start a stream in OBS.
2. Run either an Application or Window Capture for the emulator, either melonDS or OpenEmu. Honestly, any game emulator as a whole you could try, I just haven't tested that far yet because each failed test ruins my stream experience for people.
3. Run the stream for a maximum of 30 minutes, actually playing the game as you go. At random intervals, OBS's capture of the emulator(s) will freeze that one source.
...

### Anything else we should know?

1. The issue is strictly within OBS. Even when the capture source(s) freeze/break down, the actual emulator itself still runs 100% like normal, and OBS also continues all of its other functions like normal. The result ultimately is that some random points, viewers are enjoying the game footage, and then all of a sudden, audio dies and the video freezes.

2. There is no discernible cause or timing of this error. I have had it go for about half an hour without freezing, and sometimes I have had it go only a minute or two.

3. The only way to fix this that I've found (minus killing the app you're capturing entirely of course), is to open the settings panel of the problem source, switch the app or window capture to another option, then switch back to the original one. That resets the issue until the next instance it happens.

4. On a similar vein, I have noticed that if even if you leave the app or window you want captured open, at some point if you leave the OBS window, do some other work, and return, the capture source will be frozen as well unless you do the little swap trick mentioned in the previous point. There seems to be some sort of unspecified timeout sequence OBS hits at some trigger, causing whatever you're capturing to freeze and require a refresh. Back when I used OBS on Windows, I had days where I left the apps and computer on all night (once even accidentally leaving on while on a weeklong trip), and whenever I return, the apps are still being appropriately captured and active, no refresh or fiddling required.

**Comment by HiroiSekai** [comment] 2022-11-06 05:11
Any potential ideas on what this could be or a temporary workaround? It's literally stunting my ability to stream.

**Comment by Fenrirthviti** [comment] 2022-11-06 06:08
This is likely a dupe of https://github.com/obsproject/obs-studio/issues/7663, more info on what is probably going on can be found there. Does not look to be a simple or easy fix.

**Comment by HiroiSekai** [comment] 2022-11-06 09:32
Thanks.

Man, what a rollercoaster. I really love OBS on the Mac as a stability standpoint because I literally never ever ever drop a single frame on it (while the Windows version does whatever the heck it wants, dropping frames, resetting all my settings on updates, etc.), but it's been a massive window juggling maneuver even getting OBS Mac to see the screen captures, but if nothing can be captured before freezing, it's basically unusable for me as a streamer.

I guess I just keep hopelessly wishing that the Mac version can use captures with ease like Windows, but without all the BS of...Windows. A lot of it is Mac restrictions for sure, sadly.

**Comment by gxalpha** [comment] 2022-11-29 18:05
Duplicate of #7663.

**Closed by gxalpha** 2022-11-29 18:05 UTC
