### ISSUE TITLE
Replay functionality doesn't work with FFmpeg custom output

### ISSUE THREAD

**Issue by EntityinArray** [obsproject/obs-studio#5506] opened 2021-11-09 17:26 UTC
### Operating System Info

Windows 10 x64 21H1

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/05JrF7pfpXqBhvAh

### Expected Behavior

Expected replay functionality to be available when using "Custom Output (FFmpeg)" type in Output settings under Recording tab.

### Current Behavior

When using "Custom Output (FFmpeg)" Replay functionality is not working, "Start Replay" button is not present and "Maximum Replay Time" option in Settings > Output > Replay Buffer tab disappears.

### Steps to Reproduce

1. Go to File > Settings > Output
2. Switch Output Mode to Advanced
3. Go to Recording tab and set Type to Custom Output (FFmpeg)
4. Go to Replay Buffer tab and tick the Enable Replay Buffer checkbox
5. Observe that Start Replay button is not present

### Anything else we should know?

Thank you for developing and supporting this amazing piece of software!

**Comment by RytoEX** [comment] 2021-11-09 17:32
Closing as a duplicate of #4948.

It is intentional that Replay Buffer does not work with Custom FFmpeg output.

**Closed by RytoEX** 2021-11-09 17:32 UTC
