### ISSUE TITLE
OBS Studio captures the cursor when it is hidden in Wayland

### ISSUE THREAD

**Issue by evertvorster** [obsproject/obs-studio#8359] opened 2023-02-27 15:39 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

I don't see a help menu?

### Expected Behavior

I would expect that OBS studio captures what is on the screen. 
When DOSBox-x goes fullscreen, it hides the cursor from the user.

### Current Behavior

Visually, when I tell DOSBox-x to go fullscreen, the cursor disappears, but it is captured in its last position by OBS Studio. When I move the mouse, the position is not updated.

### Steps to Reproduce

1. Run Wayland Session
2. Start recording on OBS Studio
3. Run DOSBox-x in fullscreen mode

### Anything else we should know?

On X11, this works as expected, but not so much on Wayland. I also am seeing way more artifacts in the recorded video than what I am seeing on screen, like I know for a fact that a surface was drawn, and am looking at it, but when I check the recorded video, it just shows black. 

Dosbox-x is rendering to OpenGL texture
Laptop I am using this on is the all AMD Lenovo Thinkpad E15 Gen2 (AMD Ryzen 7 CPU, AMD Renoir GPU)

Short recording showing the captured cursor:

https://user-images.githubusercontent.com/12045269/221603539-4e667f54-d38c-443e-8819-597965357e83.mp4

**Comment by tytan652** [comment] 2023-02-27 15:44
PipeWire capture has an option to show the cursor or not.

Note: If you still experience the issue even with "show cursor" disable, fill the template before answering.

**Comment by evertvorster** [comment] 2023-02-27 15:46
I want the cursor to be captured when it's visible on the screen. 

When something goes full screen, and hides the cursor, then I don't want the cursor to be captured.

**Comment by tytan652** [comment] 2023-02-27 15:49
Then you should go to DOSBox-x issue tracker first. This look more related to DOSBox-x than OBS.

**Comment by evertvorster** [comment] 2023-02-27 16:17
I struggle to see how OBS studio capturing something that is not visible is somebody else's problem. 

As in, the cursor is NOT visible on screen, yet OBS studio is capturing it.

**Comment by tytan652** [comment] 2023-02-27 16:57
This looks an issue of DOSBox-x or even Plasma screencast implementation, not OBS.

**Comment by tytan652** [comment] 2023-02-27 17:27
Duplicate of #4895

**Closed by tytan652** 2023-02-27 17:27 UTC
