### ISSUE TITLE
OBS STINGER STRANSITION FREEZ ( not Smooth at the end) 1 second freezes. then i change scene (youtube video attached)

### ISSUE THREAD

**Issue by Dilzze** [obsproject/obs-studio#9131] opened 2023-06-22 21:34 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/6WalBEwhQNJLWtO6

### Expected Behavior

Can you fix stringer stransition bug?

### Current Behavior

Hi the problem i have is: then i change my stringer at the last frame my stringer freez 1 second. transition not smooth.
I uploaded video: 
https://www.youtube.com/watch?v=QPFmSG7IY_c
At 29.0.2 version was all good. The new versions all bad.

### Steps to Reproduce

Changing scenes to see stinger stransition.

**Comment by Dilzze** [comment] 2023-06-22 21:37
My friend also tried the same problem he have. With version 29.0.2 all good. The new obs version have stringer problem.

**Comment by gxalpha** [comment] 2023-06-22 21:38
The video you linked is private. However this looks like a duplicate of https://github.com/obsproject/obs-studio/issues/8981 at first glance.

**Comment by Dilzze** [comment] 2023-06-23 10:12
Now you can see https://www.youtube.com/watch?v=QPFmSG7IY_c
but yes the same problem! Thank you

**Comment by gxalpha** [comment] 2023-06-23 16:18
Closing as duplicate of #8981.
Current workaround is to add a fully transparent frame to the end of the stinger.

**Closed by gxalpha** 2023-06-23 16:18 UTC
