### ISSUE TITLE
Quad mic resolving channel mapping chaos in OBS Studio

### ISSUE THREAD

**Issue by HaujetZhao** [obsproject/obs-studio#3443] opened 2020-09-09 16:14 UTC
## Platform
Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior & Current Behavior

My laptop has four mic, representing 4 channels. When I use **Audacity** or **Adobe Audition** recording, they only uses the **1st** and **3rd** mic, recording correct stereo audio. 

But when I use **OBS** recording, setting the audio channel to be **Stereo**, the issue comes. The **1st** mic maps the **left channel**, the **3rd** mic maps the **right channel**, but the **2nd** mic maps **both left and right channel**, and the **4th** mic also maps  **both left and right channel**. The 3rd and 4th mic shouldn't have be enabled, but now these 2 are enabled, and ruined the stereo effect. 

Then, I changed the OBS audio channel setting to 4.0, the weird thing comes: The **1st** mic maps the **1st channel**, the **2nd** mic maps the **3rd channel**, but the **3rd** mic maps **2nd channel**, and the **4th** mic also maps  **4th channel**. 

I wish OBS could fix this issue, recording a correct stereo audio on a laptop which has 4 mic. Or, if OBS could provide a **mic map channel** setting, giving more audio control to users, it would be far better. 

![image](https://user-images.githubusercontent.com/19181833/92624662-5a5cd300-f2fa-11ea-91b1-cde10aebc872.png)

![image](https://user-images.githubusercontent.com/19181833/92624686-5fba1d80-f2fa-11ea-99d6-08ede21c6c0c.png)

**Comment by WizardCM** [comment] 2020-09-10 03:50
The first issue would be caused by the native downmixing OBS does. This is more commonly useful in Desktop capture scenarios. For example, my PC has 5.1 surround sound output. OBS downmixes that very cleanly into Stereo so that I can stream. I would not want it to only grab left and right channel. In your case however, downmixing is not preferred. A potential solution here would be a "Don't downmix" toggle.

For the second issue, @pkviet might be able to provide more insight into the current logic, and it's correct in most instances. Could you verify whether the behaviour changes in [OBS 26 RC2](https://github.com/obsproject/obs-studio/releases/tag/26.0.0-rc2)? I agree that a way to manually remap channels would be a good addition.

A current workaround for both issues would be [this plugin](https://obsproject.com/forum/resources/rematrix-filter-plugin.620/), which allows you to remap & disable incoming channels as you want.

**Comment by HaujetZhao** [comment] 2020-09-10 04:42
> A potential solution here would be a "Don't downmix" toggle.

I'm sorry but I couldn't find **Downmix** switch in obs, whether in audio setting, or advanced audio setting, could you point out where I can find this toggle? 

I'll try  OBS 26 RC2 and the remap plugin later. 

![image](https://user-images.githubusercontent.com/19181833/92682442-f02c4880-f362-11ea-81ee-a2e7f8290f09.png)

![image](https://user-images.githubusercontent.com/19181833/92682486-0e924400-f363-11ea-8290-7bad53493435.png)

**Comment by WizardCM** [comment] 2020-09-10 04:44
@HaujetZhao Sorry, maybe I could have worded it better: it is not a feature currently in OBS, but an idea for a future feature that would help solve your issue.

**Comment by HaujetZhao** [comment] 2020-09-10 09:40
@WizardCM The OBS 26 RC2 didn't solve the second issue. The rematric plugin do can remap the 4.0 channels, however the stereo channels issue can't be influenced, the 2nd and 4th mic still both maps to left and right channels, interfereing the stereo effect. 

Right now I can only record the video using 4.0 channel with **rematric plugin** remaping the channels, and then using FFmpeg to extract 1st and 4th channels to regroup a stereo audio. 

Wish OBS Studio could solve the **downmixing** issue, and provide native audio remap options in the future.

**Comment by pkviet** [comment] 2020-09-10 10:36
I wrote the surround sound code in obs.
IMO as to first issue:
- not an obs issue; obs retrieves what the wasapi device tells about number of channels. For some reason it declares 4 channels instead of 2. Check the windows audio settings (run mmsys.cpl). Why it works in audacity, i have no idea. The downmixing is normal on obs side since it's not a stereo input.
Second issue:
- i don't see what's weird. On the contrary it explains your first issue. Your driver device exposes it as a 4 channel input.
- the mapping seems to be correct from what I can tell.

Anyway:
- 1) don't use 4.0 for recording or streaming unless you 're sure people who will listen are equipped for 4.0 audio
- 2) do record in stereo. Now if you know about graphs you could check the pins of your wasapi device. There's probably a driver setting to switch from 4 to 2 mikes. 

I won't try to fix that since I don't have your device and it would require owning it in order to troubleshoot correctly.
You're the first person to report that kind of issue. I doubt there are many people with your issue which frankly is minor in an absolute scale (though for you it's major, i agree).
IMO, if the driver exposes 4 channels, it's a fucked up driver.
On multichannel input devices, the mikes are usually paired.

**Comment by HaujetZhao** [comment] 2020-09-10 13:35
@pkviet 

> obs retrieves what the wasapi device tells about number of channels

I think when obs uses stereo channels and the system gives 4 channels, obs has no idea to handle this situation, so it maps the 2nd and 4th mic channel to both left and right channels (while Audacity or Adobe Audition ignores the 2nd and 4th mic channel). IMO that is what need to be fixed because it's obs made mistake when handling multi-mics to stereo channel. 

I checked the system sound channel thousands of times, the drive is newest, but the mic array only provides 4 channels output and it can't be changed: 
![image](https://user-images.githubusercontent.com/19181833/92735636-25a95400-f3ac-11ea-9a55-ff95ebe8a81a.png)

And when I uses "listen to this device", the system correctly mapped the 1st and 2nd mic to left channel, 3rd and 4th mic to right channel. That means the system provided the right mic order, but it's just obs made a wrong channels remapping order. 
![image](https://user-images.githubusercontent.com/19181833/92737183-7ff6e480-f3ad-11ea-81f5-55b4d1395f89.png)


Yes, the 4 mic laptop is a minor group, I'm also the first time using a quad mic laptop. I'm sorry for having no testing machine. 

But I think if obs could provide a mannual remap and downmix control, it could solve the issues like this in the future. Users can mannually control which mic channel should be remapped to which channel, customizing there audio layout according to the actual situation.

**Comment by pkviet** [comment] 2020-09-10 14:41
Try using my obs-asio plugin. It has better channel support than the wasapi source plugin.
Your problem is NOT easy to fix because we need your device and because the downmix is controlled by swresample library , which uses some default matrixing. The one picked by ffmpeg devs doesn't work you but is reasonable otherwise. We're not going to break use for others for your sole case.
Obs-asio has routing capabilities so it should solve your problem.

**Comment by HaujetZhao** [comment] 2020-09-10 14:56
> Try using my obs-asio plugin. It has better channel support than the wasapi source plugin.
> Your problem is NOT easy to fix because we need your device and because the downmix is controlled by swresample library , which uses some default matrixing. The one picked by ffmpeg devs doesn't work you but is reasonable otherwise. We're not going to break use for others for your sole case.
> Obs-asio has routing capabilities so it should solve your problem.

I'll try asio later. For now, I  now uses FFmpeg to extract stereo channels from 4.0 channels. This is acceptable. By the way, my laptop is **Matebook 14 2020 Ryzen Version**.

**Comment by HaujetZhao** [comment] 2020-09-10 15:57
@pkviet Thank you so much, your **obs-asio** and **ASIO4ALL V2** solved my issue. I can now reroute the mic channels and get full control of the four mic input. In fact my 2nd mic in the obs-asio is **Audio Mic Array input 3**, and the 3rd mic in the obs-asio is **Audio Mic Array input 2**, but it doesn't matter now since I can mannually remap the channels. Again, thank you so much! 

![image](https://user-images.githubusercontent.com/19181833/92758448-4fb94100-f3c1-11ea-8d8a-ce0a0202bd4d.png)

**Comment by Fenrirthviti** [comment] 2020-09-10 18:11
Looks like this is resolved, going to close it out. Thanks pkv!

**Closed by Fenrirthviti** 2020-09-10 18:11 UTC
Labels: Confirmed
