### ISSUE TITLE
WIN10x64 maibenben xiaomai 5. Can`t open capture from display. Only black background

### ISSUE THREAD

**Issue by ruslan051** [obsproject/obs-studio#3080] opened 2020-06-19 15:47 UTC
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenrirthviti** [comment] 2020-06-19 15:55
This sounds like a support request, not a bug report, and you have no properly filled out the template. Closing for now. If you update the template and provide proper replication steps and more information, I will reopen.

**Closed by Fenrirthviti** 2020-06-19 15:55 UTC
