### ISSUE TITLE
no list of sources in the "add source" menu 

### ISSUE THREAD

**Issue by truitot** [obsproject/obs-studio#7656] opened 2022-10-24 16:03 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/B96x4YKrSky2f96S

### Expected Behavior

When OBS is displayed on the monitor, the "add source" menu should be filled with all the available sources.

### Current Behavior

When OBS is displayed on the big monitor, the source list is missing. The sources that would be displayed after i click "add source", are just not there. 
when i click OK button - nothing happens

### Steps to Reproduce

1.Start OBS 28.0.3
2.Click "plus" button to add new source
3.Open the "Add source" menu, and see that 
![ryr](https://user-images.githubusercontent.com/116569339/197572400-a89923f3-5f13-4c1d-af02-ac5c8836831d.jpg)
any sources are missing
...

**Comment by tytan652** [comment] 2022-10-24 16:05
Looks like a duplicate of #7655

**Closed** 2022-10-24 16:05 UTC

**Comment by gxalpha** [comment] 2022-10-24 16:06
@truitot in the future, please go through the [support channels](https://obsproject.com/help) before opening new issues.

**Comment by truitot** [comment] 2022-10-24 16:19
why u close the ticket when the case is not resolve
the problem is not resolved !

**Comment by Mister36MN** [comment] 2022-10-24 16:43
You have already been informed multiple times that this is a basic support issue, not an actual problem in OBS itself, hence why you have been directed to the support resources.
