### ISSUE TITLE
Triple monitor, same unique ID

### ISSUE THREAD

**Issue by mmagdy88** [obsproject/obs-studio#10649] opened 2024-05-07 21:31 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/DxBCp3x8as6vT4pB

### Expected Behavior

When I choose a monitor from the drop down menu, I get what's on that monitor

### Current Behavior

When I choose any of my 3 monitors, it shows only the primary one.

### Steps to Reproduce

1. Try to choose any monitor from the Display drop-down menu
2. All display sources have a unique name of the monitor but they all show the primary monitor only.

### Anything else we should know?

I believe it's something related to the unique ID, it happened after I switched cables in the Graphics Card

Original post:
https://obsproject.com/forum/threads/triple-monitor-same-unique-id.175286/

**Comment by RytoEX** [comment] 2024-05-07 21:42
Possible duplicate of #8181?

Please check this comment and provide the info requested: https://github.com/obsproject/obs-studio/issues/8181#issuecomment-1519167663

**Comment by RytoEX** [comment] 2024-05-07 21:46
Additionally, how are these displays connected to the system?

**Comment by mmagdy88** [comment] 2024-05-07 21:49
@RytoEX Thanks for pointing me to that thread, my issue was this [](https://github.com/obsproject/obs-studio/issues/8181#issuecomment-1567265035)

After I disabled my TV, all working good, thank you.

**Closed** 2024-05-07 21:50 UTC
