### ISSUE TITLE
V4L2 Virtual Camera - Loopback device conflicts

### ISSUE THREAD

**Issue by darrellenns** [obsproject/obs-studio#4037] opened 2021-01-08 16:40 UTC
OBS Virtual Camera seems to always use the first V4L2 loopback device. When running multiple instances of OBS, both instances will use the same loopback device. This results in a flickering/glitching mess on the loopback output. Could we get an option to set which loopback device will be used?

## Platform
Operating system and version: Arch Linux (current)
OBS Studio version: 26.1

## Expected Behavior
When running multiple instances of OBS and VirtualCam, each instance should use a separate loopback device.

## Current Behavior
Multiple VirtualCam instances attempt to use the same loopback devices, resulting in glitching VirtualCam output.

## Steps to Reproduce
1. Run OBS and enable virtual cam output
2. Run a second instance of OBS (obs -m), and enable virtual cam output in this instances as well
3. View output of first v4l2loopback device and observe that it glitches between frames from both OBS instances

**Comment by RytoEX** [comment] 2021-01-08 16:53
Please follow the issue template when opening issues on GitHub.

**Comment by darrellenns** [comment] 2021-01-08 23:02
Appologies - I've updated the original post to use the template

**Comment by kkartaltepe** [comment] 2021-01-25 16:03
Im going to close as a duplicate of #3929 as there is more discussion there about conflicting loopback users.

**Closed by kkartaltepe** 2021-01-25 16:03 UTC
Labels: Linux
