### ISSUE TITLE
Occasional audio cut outs in recording

### ISSUE THREAD

**Issue by HWesterhof** [obsproject/obs-studio#11407] opened 2024-10-16 15:10 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FYwkP1UYyTNUQZbP0

### Expected Behavior

A recording without glitches

### Current Behavior

Glitches in recording. Example here:

https://www.youtube.com/watch?v=8qTKOsS8i4w

**Audio waveform**
![image](https://github.com/user-attachments/assets/d31e0dd9-8c49-4cbb-ae65-15d8705ac82f)

### Steps to Reproduce

I use OBS Studio to record a session, the end product is a video file that I can upload to YouTube.

However, occasionally I notice audio cut outs of a few milliseconds. I've literally spent weeks trying figure out this issue. So far I've only been able to narrow things down. It usually happens within 2 to 5 minutes. Sometimes 10 minutes without issue, sometimes within 30 seconds...

It is only happening in OBS Studio. I've recorded several sessions using Audacity without any problem. 

What I've tried:

- Official Scarlett Focusrite drivers (v3.18.0)
- Legacy Scarlett Focusrite drivers (v3.6.0)
- Windows driver (Scarlett 2i2 USB)

(I fully uninstalled all existing drivers when I switched to another driver)

- I tried all combinations imaginable regarding buffer size (ranging from 64 to 1024), frequencies (44100 Hz,48000 Hz), and formats (24 bit, 16 bit)
- Followed steps regarding DPC latency (https://support.focusrite.com/hc/en-gb/articles/208360865-Troubleshooting-DPC-latency)
- Recording settings to the bare minimum: 1080p, 30 FPS (https://obsproject.com/logs/ULpkJLBjjcFnIl1C)

OBS related attempts:
- Latest release (30.2.3)
- Beta release (31.0.0 Beta 1)
- Tried ASIO plugin (to work with ASIO USB Focusrite in OBS)
- Uninstalled all plugins
- Reproducible with a recording with just one source, being the input of the Focusrite (so zero other stuff going on, black screen)
- Recording locations: Ranging from external USB drive, and tried both my internal SSD's (one SATA, other NVME)
- Tried video/audio encoders
- Tried custom FFMpeg encoder (https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FmMiWXtE69gHeYn2k)
- Log analysis using the standard encoder (https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FYwkP1UYyTNUQZbP0)

### Anything else we should know?

My relevant hardware specifications:
- Scarlett Focusrite 2i2 3rd gen, using the input left and right into OBS as audio
- NVIDIA RTX 4070 Ti
- AMD Ryzen 9 5900X 12 core
- 32 GB RAM

**Comment by RytoEX** [comment] 2024-10-16 15:53
Possibly a duplicate of #4600 ?

**Comment by Penwy** [comment] 2024-10-16 17:41
Might be a stupid question but better safe than sorry : have you checked without the noise gate filter on the focusrite source?
It's there in every log you sent, and most definitively can cause audio to cut out, it's kinda its main function.

**Comment by HWesterhof** [comment] 2024-10-16 18:43
> Possibly a duplicate of #4600 ?

It is indeed... And the suggested workaround (by using the OBS Asynchronous Audio Filter Plugin) works for me. Thank you!

**Comment by Fenrirthviti** [comment] 2024-10-16 18:44
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by HWesterhof** [comment] 2024-10-16 18:45
> Might be a stupid question but better safe than sorry : have you checked without the noise gate filter on the focusrite source? It's there in every log you sent, and most definitively can cause audio to cut out, it's kinda its main function.

Fair comment, I realize I should have done all my tests with that plugin disabled, it was certainly not the cause (it was tuned to only cut out noise lower than -55 dB).

But yeah... @RytoEX pointed me to the root cause, and the workaround works for me.

**Closed by Fenrirthviti** 2024-10-16 18:44 UTC
