### ISSUE TITLE
OBS Studio 28.0.1 Doesnt install 

### ISSUE THREAD

**Issue by Vincent392** [obsproject/obs-studio#7398] opened 2022-09-18 11:04 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1 installer

### OBS Studio Log URL

i dont know how to get to the log url

### Expected Behavior

It to fully install

### Current Behavior

Extracting libcef.dll fails at 41% or 38% extraction it fails with a popup: Extract: Error writing to libcef.dll
![image](https://user-images.githubusercontent.com/90470156/190898422-e3599eed-379d-42fc-8321-77cb2cc1a485.png)
log:
[OBS install log fail.txt](https://github.com/obsproject/obs-studio/files/9593794/OBS.install.log.fail.txt)

### Steps to Reproduce

1.Have a windows 10 PC running 20H2 and a Intel core i5 3rd gen and a geforce 740m and a part borked windows install
2.Install it onto a 3rd drive
3.it should appear
...

### Anything else we should know?

i dont know how it happens but it happens.
Model of Laptop: ASUS K46CB-WX060H notebook i5-3337U 35.6 cm (14") HD Intel® Core™ i5 2 GB DDR3-SDRAM 750 GB HDD NVIDIA® GeForce® GT 740M Windows 8 Black, Stainless steel
My specs: ASUS K46CB-WX060H notebook i5-3337U 35.6 cm (16") I think  HD Intel® Core™ i5 8GB DDR3-SDRAM 1TB HDD with a 450GB SSD NVIDIA® GeForce® GT 740M Windows 8 Black, Stainless steel running Windows 10 20H2

**Comment by MattyFresh68** [comment] 2022-09-18 11:05
OBS28 is only compatible with windows 10 and newer. Either update your OS or use obs 27.2.4

**Comment by Vincent392** [comment] 2022-09-18 11:10
> OBS28 is only compatible with windows 10 and newer. Either update your OS or use obs 27.2.4
Uh im running Windows 10 20H2 i did try windows 7 compatibility mode just in case
ps Windows 7 support would be nice.

**Comment by MattyFresh68** [comment] 2022-09-18 11:11
Windows 7 is dead. Microsoft killed it nearly 3 years ago now. OBS team has no plans to support dead OS

**Comment by Vincent392** [comment] 2022-09-18 11:14
> Windows 7 is dead. Microsoft killed it nearly 3 years ago now. OBS team has no plans to support dead OS
yeah i know that. What about 8x support? yeah 8.1 will be killed of in like 6 months so its kinda pointless but still for those machines that cant run 10 or run it poorly.
also vista and xp support is useless i mean XP is a 21 year old OS.

**Comment by Scrxtchy** [comment] 2022-09-18 11:16
There's a notification centre in the taskbar. While this looks like windows 7, I'm positive the OP has skinned their shell to appear this way. This looks like a support thread though, someone will likely come in and close it regardless, as support is only given over [Forums and Discord](https://obsproject.com/help)

**Comment by MattyFresh68** [comment] 2022-09-18 11:17
> There's a notification centre in the taskbar. While this looks like windows 7, I'm positive the OP has skinned their shell to appear this way. This looks like a support thread though, someone will likely come in and close it regardless, as support is only given over [Forums and Discord](https://obsproject.com/help)

They said they are on windows 8. Windows 8 is a hard pass for obs 28

**Comment by Vincent392** [comment] 2022-09-18 11:17
> There's a notification centre in the taskbar. While this looks like windows 7, I'm positive the OP has skinned their shell to appear this way. This looks like a support thread though, someone will likely come in and close it regardless, as support is only given over [Forums and Discord](https://obsproject.com/help)

yeah its windows 10 20H2. the other one thought it was windows 7.

**Comment by MattyFresh68** [comment] 2022-09-18 11:18
Ok, so it is 10? Yea. Follow the other advice and visit the forums or discord

**Comment by Vincent392** [comment] 2022-09-18 11:18
> > There's a notification centre in the taskbar. While this looks like windows 7, I'm positive the OP has skinned their shell to appear this way. This looks like a support thread though, someone will likely come in and close it regardless, as support is only given over [Forums and Discord](https://obsproject.com/help)
> 
> They said they are on windows 8. Windows 8 is a hard pass for obs 28

i said windows 8x support would be nice like 7 support.

**Comment by WizardCM** [comment] 2022-09-18 11:19
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Vincent392** [comment] 2022-09-18 11:20
> Ok, so it is 10? Yea. Follow the other advice and visit the forums or discord

yeah i don't know why it does not work im going to send the storage free on all the drives.
AND ITS CLOSED.

**Closed by WizardCM** 2022-09-18 11:19 UTC

**Comment by Vincent392** [comment] 2022-09-18 11:21
> This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.
> 
> Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

yeah i think its a installer bug. im going to try install on a windows 10 vm.

**Comment by Scrxtchy** [comment] 2022-09-18 11:22
> i said windows 8x support would be nice like 7 support.

Previous versions of windows have been dropped as of OBS 28, as the migration to qt6 was neccessary to remain in support going forward. qt6 was designed without support for previous operating systems. For the time being, OBS27 will still work on these systems however will not have any official support from team members. Users are free to fork the project to maintain a version of OBS that runs on qt5 with some backported patches, but this will remain a third-party project if it ever comes to life

**Comment by Vincent392** [comment] 2022-09-18 11:25
> > i said windows 8x support would be nice like 7 support.
> 
> Previous versions of windows have been dropped as of OBS 28, as the migration to qt6 was neccessary to remain in support going forward. qt6 was designed without support for previous operating systems. For the time being, OBS27 will still work on these systems however will not have any official support from team members. Users are free to fork the project to maintain a version of OBS that runs on qt5 with some backported patches, but this will remain a third-party project if it ever comes to life

how about OBS 28 light for older OSs? Aka take OBS 27 add the 28 patches that will work and tada a version of OBS that will be for older OSs.

**Comment by Vincent392** [comment] 2022-09-18 11:26
> > i said windows 8x support would be nice like 7 support.
> 
> Previous versions of windows have been dropped as of OBS 28, as the migration to qt6 was neccessary to remain in support going forward. qt6 was designed without support for previous operating systems. For the time being, OBS27 will still work on these systems however will not have any official support from team members. Users are free to fork the project to maintain a version of OBS that runs on qt5 with some backported patches, but this will remain a third-party project if it ever comes to life

also nobody is going to try take the Mac OS Version of OBS and port it to Mac OS 10.6 right?

**Comment by tt2468** [comment] 2022-09-18 12:33
I don't see why we would ever want to release OBS for a 13 year old version of macOS.

**Comment by gxalpha** [comment] 2022-09-18 12:53
> Aka take OBS 27 add the 28 patches that will work and tada a version of OBS that will be for older OSs.

Feel free to make a fork yourself (as you are allowed to by the terms of the GPL) if you think it's that simple to maintain (though beware, it really isn't as simple as you may think).

From the OBS Project side, there is no intention to support such old operating systems (Windows 7/8/8.1 and Mac OS X 10.6 - macOS 10.14). The fact that there are hacks to get it running does not change this situation.
