### ISSUE TITLE
picture slideshow only displays a few pictures and not full directory

### ISSUE THREAD

**Issue by scantsquad** [obsproject/obs-studio#3595] opened 2020-10-10 10:06 UTC
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by scantsquad** [comment] 2020-10-10 10:08
windows 10 64bit, obs 26.0.2, only displays maybe 6-8 pictures in slideshow display. the rest of the pictures do not attempt to load or display

**Comment by WizardCM** [comment] 2020-10-10 10:17
Duplicate of #3366. Next time please fill in the issue template.

**Closed by WizardCM** 2020-10-10 10:17 UTC
