### ISSUE TITLE
[BUG] OBS sometimes crash on exit

### ISSUE THREAD

**Issue by turbostar190** [obsproject/obs-studio#2756] opened 2020-04-19 09:47 UTC
## Platform
Operating system and version: Windows 1909 x64
OBS Studio version: 25.0.4 installed version

## Expected Behavior
I should close OBS without seeing an error popup

## Current Behavior
Sometimes, when I close the app after a live streaming using the red cross, a "Woops, OBS has crashed" popup appear.
Crash log: https://obsproject.com/logs/uuZzWEeEzWgiq9Wz
Session log: https://obsproject.com/logs/NF4-J9o_oKC4bcsc

## Steps to Reproduce
I sometimes saw this problem: 
1. Do a live streaming
2. Stop the live streaming
3. Close OBS using red cross
4. A crash popup will appear

## Additional information
It seems very similar to this comment on the issue https://github.com/obsproject/obs-studio/issues/2290#issuecomment-592082729

**Comment by Fenrirthviti** [comment] 2020-04-26 04:07
We have traced this issue back to a bug in the drag/drop to reorder scenes code.

**Comment by notr1ch** [comment] 2020-05-19 00:55
I think this is caused by the same bug as https://github.com/obsproject/obs-studio/issues/2724.

**Comment by WizardCM** [comment] 2020-08-28 01:51
Closing in favour of #3310 to keep discussion in one place.

**Closed by WizardCM** 2020-08-28 01:51 UTC
Labels: Confirmed, Crash Report
