### ISSUE TITLE
VT h264 Hardware Encoder is unusable on ARM Macs

### ISSUE THREAD

**Issue by AuroraWright** [obsproject/obs-studio#5713] opened 2021-12-29 22:06 UTC
### Operating System Info

macOS 12.0

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/OCx5SYJvErSBnX1w

### Expected Behavior

VT H264 HW Encoder works fine on my 2016 Intel mac. I'd expect it to work the same way on ARM.

### Current Behavior

On my 2021 M1 Max machine and recent git versions (compiled for ARM), using the hardware encoder and 1080p60 input/output eventually (after at least a few minutes) causes high framerate spikes (much higher than those set in the "bitrate" field. This eventually causes an encoder overload which doesn't resolve itself and requires you to stop/restart the recording/stream, and it then works for some more time. It's worth noting that it takes pressing the "stop" button twice for it to happen when the encoder is overloaded. This happens both when recording or streaming. Due to https://github.com/obsproject/obs-studio/issues/4670, it's also impossible to limit the bitrate, hence the HW encoder is hardly usable on ARM macs.

### Steps to Reproduce

1. Activate the HW Encoder on an ARM mac
2. Stream/record for a while
3. The encoder overloads
...

**Comment by Fenrirthviti** [comment] 2021-12-29 22:11
Duplicate of #4670

As far as I know, this is a limitation with VT, not OBS (and has been an issue even outside M1 devices). Discussion regarding issues with the VT encoder should go on #4670

**Closed by Fenrirthviti** 2021-12-29 22:11 UTC
