### ISSUE TITLE
Crash when exit obs

### ISSUE THREAD

**Issue by huoyan1231** [obsproject/obs-studio#8713] opened 2023-04-11 09:07 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

crash

### OBS Studio Crash Log URL

https://obsproject.com/logs/EJPQC1RBvDLOWVZU

### Expected Behavior

exit obs

### Current Behavior

crash

### Steps to Reproduce

1.open obs
2.exit obs
3.crash
...

**Comment by gxalpha** [comment] 2023-04-11 09:34
Please still provide a normal crash log, ideally from the session that crashed. It’s located in %APPDATA%\obs-studio\logs

**Comment by huoyan1231** [comment] 2023-04-11 09:35
[2023-04-11 17-01-25.txt](https://github.com/obsproject/obs-studio/files/11198940/2023-04-11.17-01-25.txt)


> Please still provide a normal crash log, ideally from the session that crashed. It’s located in %APPDATA%\obs-studio\logs

**Comment by RytoEX** [comment] 2023-04-13 19:48
Duplicate of #8300

**Closed by RytoEX** 2023-04-13 19:48 UTC
Labels: Crash Report
