### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by LAISOVECHAT** [obsproject/obs-studio#8255] opened 2023-02-12 19:16 UTC
### Operating System Info

Other

### Other OS

Windows7

### OBS Studio Version

Other

### OBS Studio Version (Other)

Windows

### OBS Studio Log URL

Windows

### OBS Studio Crash Log URL

Windows

### Expected Behavior

Windows

### Current Behavior

Windows

### Steps to Reproduce

1.
2.
3.
...
Windows

### Anything else we should know?

Windows

**Comment by tytan652** [comment] 2023-02-12 19:17
Closing as the issue is empty.

**Comment by gxalpha** [comment] 2023-02-12 19:17
Windows 10 or Windows 11

**Closed** 2023-02-12 19:17 UTC

**Comment by derrod** [comment] 2023-02-12 19:21
Windows

**Comment by Penwy** [comment] 2023-02-12 19:22
Windows?
