### ISSUE TITLE
Auto reconnect on SRT streaming is unstable and can crash OBS when stopping

### ISSUE THREAD

**Issue by biosmatrix123** [obsproject/obs-studio#6523] opened 2022-05-20 13:23 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/TSD307e7egWH153z

### Expected Behavior

- When streaming to a SRT server which doesn't exist, OBS should not report it has connected
- When stopping streaming (If it was not actually connected) it should stop properly and not get stuck on 'Stopping Streaming...' and also another press of the 'Stopping Streaming...' button should not crash OBS

### Current Behavior

If streaming is started to a non existant SRT server (use any IP, e.g. 127.0.01) it will appear to connect - but then will attempt to reconnect automatically - which OBS then thinks actually connects, but then disconnects. Because of this I believe OBS is stuck in a loop and will always see the connection as successful thus not stopping to auto-reconnect after X tries as per settings.

When clicking 'Stop Streaming' OBS will then get stuck trying to stop it and it will never stop - you can then click 'Stop Streaming...' again and OBS will crash.

### Steps to Reproduce

1. Configure to stream to non existant SRT server, e.g. srt://127.0.0.1
2. Start Streaming
3. You will see OBS looping : Connected, Disconnected, Connecting, Disconnected etc
4. Click 'Stop Stop Streaming'.
5. It will not stop streaming and remains on 'Stopping Streaming...'
6. Click 'Stopping Streaming.....'
7. OBS Will then crash - no crash report made

**Comment by pkviet** [comment] 2022-05-20 13:55
Duplicate of issue #5791

**Comment by RytoEX** [comment] 2022-05-20 14:12
Duplicate of #5791.

**Closed** 2022-05-20 14:12 UTC
