### ISSUE TITLE
Python scripts not selectable on macOS with OBS 26.1.0

### ISSUE THREAD

**Issue by garrettreid** [obsproject/obs-studio#3922] opened 2020-12-17 18:49 UTC
## Platform

Operating system and version: macOS Big Sur 11.1
OBS Studio version: 26.1.0
## Expected Behavior
Python scripts should be selectable in the Scripts window.

## Current Behavior
Python scripts cannot be selected in the script window. Lua scripts can.

## Steps to Reproduce

1. Open OBS
2. From the menu bar, select the Tools menu, then Scripts
3. In the Scripts window that appears, click the "+" button in the bottom left to add a script
4. Browse to a directory with a python script in it, or use the default directory (OBS.app/Contents/Resources/data/obs-plugins/frontend-tools/scripts/)
5. Try to click on a Python script to open. (Can't, they're greyed out. Lua scripts are not)

## Additional information

The [Scripting page](https://obsproject.com/docs/scripting.html) references a "Python Settings" tab for Windows, but has no specific macOS directions. I have not seen such a tab, but I may be missing a step somewhere.

**Comment by PatTheMav** [comment] 2020-12-17 18:52
This is by design, we disabled Python scripting support as OBS couldn't be built with newer Python versions present.

https://github.com/obsproject/obs-studio/pull/3689 addresses this and once it's merged, Python support should be restored on macOS.

**Closed** 2020-12-17 18:52 UTC
Labels: By Design / Not a bug, macOS
