### ISSUE TITLE
Display Capture: Capture Cursor doesn't capture bigger mouse cursors in Windows 10 and 11.

### ISSUE THREAD

**Issue by timeslider** [obsproject/obs-studio#6543] opened 2022-05-26 18:51 UTC
### Operating System Info

Windows 11

### Other OS

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/si0_nRrXI4Iw9riG

### Expected Behavior

In Windows 10 or 11, if you set the size of the cursor to be bigger than the default size, OBS should record the video with the bigger size.

### Current Behavior

Instead of recording the actual size, it records the default size.

### Steps to Reproduce

I'm currently using Windows 11 now but this happens in Windows 10 as well but I can't write those steps since I don't have Windows 10 anymore. It's very similar though. 

1. In Windows 11, change your mouse size by searching for mouse pointer size. Increase it to something large so it's noticeable.
2. In OBS, have a Display Capture source and make sure that Capture Cursor is on. 
3. Record a video and wave the mouse around so it shows up in the recording.
4. Stop the recording and play it back.
5. Observe that the mouse size is the default size and not the size you selected.

### Anything else we should know?

There's a work around. For whatever reason, opening the magnifier app forces OBS to record the right size mouse cursor. In fact, it actually records two cursors. For this reason, you have to turn _off_ Capture Cursor and it'll record the larger one as expected. But I'd like it if I didn't have to open up the magnifier. I can do this work around because I work with dual monitors but the work around would force you to record the magnifier app if you had a single monitor and there's no way to minimize the magnifier app so it clutters up the screen.

**Comment by WizardCM** [comment] 2022-05-26 23:16
Duplicate of #2604

**Closed by WizardCM** 2022-05-26 23:16 UTC

**Comment by nowlex515** [comment] 2024-09-22 13:49
I found ScreenHunter 7 can do this job.
