### ISSUE TITLE
vdpau existance causes obs to segfault

### ISSUE THREAD

**Issue by smvoss** [obsproject/obs-studio#8104] opened 2023-01-20 18:32 UTC
### Operating System Info

Linux

### Other OS

Arch Linux

### OBS Studio Version

29.0.0

### OBS Studio Log URL

Could not use builtin log viewer, as the log wasn't my current nor my previous log.

```
16:56:00.892: Using EGL/X11
16:56:00.892: CPU Name: AMD Ryzen 9 5950X 16-Core Processor
16:56:00.892: CPU Speed: 3965.491MHz
16:56:00.892: Physical Cores: 16, Logical Cores: 32
16:56:00.892: Physical Memory: 64198MB Total, 58139MB Free
16:56:00.892: Kernel Version: Linux 6.1.6-arch1-3
16:56:00.892: Distribution: "Arch Linux" Unknown
16:56:00.892: Session Type: x11
16:56:00.892: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
16:56:00.893: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
16:56:00.893: Portable mode: false
16:56:00.907: OBS 29.0.0-27-g447adfbe3-modified (linux)
16:56:00.907: ---------------------------------
16:56:00.907: ---------------------------------
16:56:00.907: audio settings reset:
16:56:00.907: 	samples per sec: 48000
16:56:00.907: 	speakers:        2
16:56:00.907: 	max buffering:   960 milliseconds
16:56:00.907: 	buffering type:  dynamically increasing
16:56:00.908: ---------------------------------
16:56:00.908: Initializing OpenGL...
16:56:00.992: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
16:56:00.992: OpenGL loaded successfully, version 3.3.0 NVIDIA 525.78.01, shading language 3.30 NVIDIA via Cg compiler
16:56:01.005: ---------------------------------
16:56:01.005: video settings reset:
16:56:01.005: 	base resolution:   1920x1080
16:56:01.005: 	output resolution: 1280x720
16:56:01.005: 	downscale filter:  Bicubic
16:56:01.005: 	fps:               30/1
16:56:01.005: 	format:            NV12
16:56:01.005: 	YUV mode:          Rec. 709/Partial
16:56:01.005: NV12 texture support not available
16:56:01.005: P010 texture support not available
16:56:01.005: Audio monitoring device:
16:56:01.005: 	name: Default
16:56:01.005: 	id: default
16:56:01.005: ---------------------------------
16:56:01.012: No AJA devices found, skipping loading AJA UI plugin
16:56:01.012: Failed to initialize module 'aja-output-ui.so'
16:56:01.018: No AJA devices found, skipping loading AJA plugin
16:56:01.018: Failed to initialize module 'aja.so'
16:56:01.023: Failed to load 'en-US' text for module: 'decklink-captions.so'
16:56:01.027: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
16:56:01.032: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:56:01.032: Failed to initialize module 'decklink.so'
16:56:01.130: [pipewire] Available captures:
16:56:01.130: [pipewire]     - Desktop capture
16:56:01.130: [pipewire]     - Window capture
16:56:01.144: v4l2loopback not installed, virtual camera disabled
16:56:01.150: [obs-browser]: Version 2.19.0
16:56:01.150: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
16:56:01.165: NVENC supported
16:56:01.165: LIBVA_DRIVER_NAME variable is set, this could prevent FFmpeg VAAPI from working correctly
```

### Expected Behavior

Launches. Note I could not provide a log because it crashed too early in startup to be able to upload.

### Current Behavior

Crashed immediately with segfault. After noticing it failed around libva I decided to uninstall `libva-vdpau-driver` from my system to see if it fixed it and it did. 

Note, I did unset `LIBVA_DRIVER_NAME` just to see if that would help and it resulted in an identical crash.

### Steps to Reproduce

1. Launch OBS with `libva-vdpau-driver` installed
...
```
» gdb obs
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org 
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in obs)
(gdb) r
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe35ff6c0 (LWP 5122)]
[New Thread 0x7fffe1f6c6c0 (LWP 5123)]
[New Thread 0x7fffe176b6c0 (LWP 5124)]
[New Thread 0x7fffe0e8e6c0 (LWP 5125)]
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: AMD Ryzen 9 5950X 16-Core Processor
info: CPU Speed: 2365.752MHz
info: Physical Cores: 16, Logical Cores: 32
info: Physical Memory: 64198MB Total, 57796MB Free
info: Kernel Version: Linux 6.1.6-arch1-3
info: Distribution: "Arch Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffd39ff6c0 (LWP 5127)]
[New Thread 0x7fffd31fe6c0 (LWP 5128)]
info: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
info: Portable mode: false
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.0-27-g447adfbe3-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffd29fd6c0 (LWP 5129)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 525.78.01, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffd15ff6c0 (LWP 5130)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fffbce156c0 (LWP 5131)]
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
[Detaching after fork from child process 5132]
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
[Detaching after fork from child process 5133]
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
[Detaching after fork from child process 5134]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 5135]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 5136]
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 5137]
[New Thread 0x7fffb7bff6c0 (LWP 5138)]
[Detaching after fork from child process 5139]
[Detaching after fork from child process 5140]
[Detaching after fork from child process 5141]
[Detaching after fork from child process 5142]
[Detaching after fork from child process 5143]
[Detaching after fork from child process 5144]
[Detaching after fork from child process 5145]
[Detaching after fork from child process 5146]
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
[Detaching after fork from child process 5147]
[Detaching after fork from child process 5148]
[Detaching after vfork from child process 5149]
warning: v4l2loopback not installed, virtual camera disabled
[Detaching after fork from child process 5151]
info: [obs-browser]: Version 2.19.0
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
[Detaching after fork from child process 5152]
info: NVENC supported
warning: LIBVA_DRIVER_NAME variable is set, this could prevent FFmpeg VAAPI from working correctly

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff1ab88c4 in XDisplayString () from /usr/lib/libX11.so.6
(gdb) b
Breakpoint 1 at 0x7ffff1ab88c4
(gdb) bt
#0  0x00007ffff1ab88c4 in XDisplayString () at /usr/lib/libX11.so.6
#1  0x00007fffb5ebca1d in __vaDriverInit_1_13 () at /usr/lib/dri/vdpau_drv_video.so
#2  0x00007ffff1bd39c3 in  () at /usr/lib/libva.so.2
#3  0x00007ffff1bd6cd0 in vaInitialize () at /usr/lib/libva.so.2
#4  0x00007fffb5fc06b6 in vaapi_open_device () at /usr//lib/obs-plugins/obs-ffmpeg.so
#5  0x00007fffb5fc0a94 in vaapi_device_h264_supported () at /usr//lib/obs-plugins/obs-ffmpeg.so
#6  0x00007fffb5fc0b69 in vaapi_get_h264_default_device () at /usr//lib/obs-plugins/obs-ffmpeg.so
#7  0x00007fffb5fac564 in obs_module_load () at /usr//lib/obs-plugins/obs-ffmpeg.so
#8  0x00007ffff6557dbe in obs_init_module () at /usr/lib/libobs.so.0
#9  0x00007ffff6559307 in  () at /usr/lib/libobs.so.0
#10 0x00007ffff6558908 in obs_find_modules2 () at /usr/lib/libobs.so.0
#11 0x00007ffff6558fed in obs_load_all_modules2 () at /usr/lib/libobs.so.0
#12 0x00005555556cec4d in  ()
#13 0x0000555555602f5e in  ()
#14 0x00005555555e068c in main ()
```

### Anything else we should know?

My system:

Fully up-to-date arch linux (kernel 6.1.6-arch1-3), nvidia 3080 + 5950x.

**Comment by tytan652** [comment] 2023-01-20 18:46
Duplicate of #8056

**Closed** 2023-01-20 18:46 UTC
