### ISSUE TITLE
Remote media streams not displaying video when using hardware decoding in Media Source

### ISSUE THREAD

**Issue by brynlea** [obsproject/obs-studio#10369] opened 2024-03-13 18:22 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/6LiWnBULTyTYyaSC

### Expected Behavior

Video output of caller PC displaying in preview of listener PC via SRT stream.

### Current Behavior

No display in preview, not even black screen.

### Steps to Reproduce

1. Start OBS as admin on both caller and listener.
2. Set stream output of caller PC to listener address.
3. Add media source on listener, untick local file, input as same address from caller stream.
4. Start streaming on caller PC.

### Anything else we should know?

Everything was working before the latest update, nothing un/installed on either PC since last using OBS. Updated video drivers before bug report.
Logs from caller: https://obsproject.com/logs/aT36horil2AtOrE0

**Comment by pkviet** [comment] 2024-03-13 19:21
We can't confirm your issue.
Two devs have checked independently that streaming from obs to an obs media source works fine.
Your logs suggest a network issue since the stream never connects.
It seems to be therefore a support issue rather than a genuine bug.
I'll close therefore this issue. Feel free to seek help in the support channels of our Discord server if you can't figure out what
was improperly configured on your side.

**Comment by brynlea** [comment] 2024-03-13 19:42
Thank you both for looking into it. Unfortunately no one in the Discord could figure it out. I ended up rolling back to v30.0.2 and it's working again.

**Comment by RytoEX** [comment] 2024-03-13 19:45
We're still investigating. Apparently this only occurs when you have "Use hardware decoding when available" enabled.

**Comment by pkviet** [comment] 2024-03-13 20:24
@brynlea could you retest but disable hardware acceleration in your Media Sources ? It should work. Check also if audio is reaching the Media Source.
From your sender log I incorrectly assumed you never connected. But if we're correct it's a decoding issue for video but not audio so you should get audio at least when hw decoding is enabled. But both video and audio if hw decoding is disabled

**Comment by brynlea** [comment] 2024-03-13 21:26
After turning off hardware acceleration the video does work, and audio works both ways.

**Comment by pkviet** [comment] 2024-03-13 21:28
Thanks for the confirmation. We haven't found a fix yet but the issue is related to our update of ffmpeg deps.

**Comment by pkviet** [comment] 2024-03-15 22:01
The issue is not related to SRT per se.
I reproduced it with RTMP.
I found a fix which is being reviewed.
The bug is due to the fact that several color codec params are not passed correctly.

**Closed** 2024-03-18 18:13 UTC
Labels: Dependency Issue, Confirmed
