### ISSUE TITLE
OBS Studio 26.1.0 crashes when I restart my stream on Twitch

### ISSUE THREAD

**Issue by elgrount** [obsproject/obs-studio#3940] opened 2020-12-19 11:08 UTC
Since I updated OBS Studio to the latest version (26.1.0), OBS crashes each time I restart my stream.
If I start a stream, it does work correctly.
If I stop the stream, restart OBS and start the stream, it's ok.
But if I start a stream, stop the stream and restart the stream, it crashes.

## Platform

Operating system and version: Windows 10 64
OBS Studio version: 26.1.0
Streaming platform: Twitch

## Expected Behavior
OBS should not crash when I restart my stream.
It worked correctly in the previous version (26.0)

## Current Behavior

When I start my stream, it works correctly.
But if I stop and restart my stream, OBS crashes each time.
So if I need to restart my stream, I have to close and reopen OBS instead of stop and start the stream directly.
Here is a log file :
[Crash 2020-12-18 17-54-15.txt](https://github.com/obsproject/obs-studio/files/5719252/Crash.2020-12-18.17-54-15.txt)

## Steps to Reproduce

1. Open OBS
2. Start a stream
3. Stop the stream
4. Restart the stream
5. OBS will crash with a popup "oops OBS crashed....."

## Additional information

I have some plugins installed, but it worked correctly before I installed the latest version.

THANKS 👍

**Comment by WizardCM** [comment] 2020-12-19 11:13
Looks like the crash is caused by a combination of the Stream Deck plugin and the Twitch Soundtrack plugin.

**Comment by WizardCM** [comment] 2020-12-19 11:18
I have verified this does not happen with a clean install of OBS 26.1.0, so I'll close this ticket - however I'll see whether it's something we could get Elgato/Twitch to look into.

**Closed by WizardCM** 2020-12-19 11:18 UTC

**Comment by elgrount** [comment] 2020-12-19 14:14
Thanks
I removed the Twitch soundtrack plugin, and it's still crash.
I will try to remove elgato to check...

**Comment by elgrount** [comment] 2020-12-19 14:30
Removed elgato streamdeck plugin => no effet, still crash
After that, I checked the plugin directory, I found 2 dll of Twitch soundtrack (2 dll in 32/64 bits directory). After deleting them, now it works correctly, no crash anymore.
