### ISSUE TITLE
OBS doesn't use aspect ratio metadata in video files when using vlc video source

### ISSUE THREAD

**Issue by sebi-berlin** [obsproject/obs-studio#3843] opened 2020-12-07 16:26 UTC
## Platform
Operating system and version: Windows 10
OBS Studio version: 26.0.2.

## Expected Behavior
Use aspect ratio of media file's metadata

## Current Behavior
aspect ratios in video files metadata does get ignored. the used aspect ratio gets defined by the resolution

## Steps to Reproduce
1. use any videofile
2. change the aspect ratio by e.g. mkvtoolnix to anything else that's not the resolution
3. play it in VLC standalone w/o OBS -> ar gets respected
4. play it in VLC built in -> ar gets ignored

## Additional information
I'm using OBS to stream a bunch of video files with different aspect ratios. Some older files e.g. dvd muxes have different aspect ratios than the video file resolution. I need a way to make OBS have an option to use the aspect ratio metadata, that the video files have.

**Comment by energizerfellow** [comment] 2020-12-07 16:37
Sounds like a PAR vs DAR vs SAR issue and how OBS/VLC (doesn't) handle these issues.  Anamorphic widescreen DVD rips would be a good test here.

**Comment by sebi-berlin** [comment] 2020-12-08 11:16
Exactly! Shall I upload something?

**Comment by WizardCM** [comment] 2020-12-09 10:17
Is this a duplicate of #2933?

**Comment by sebi-berlin** [comment] 2020-12-15 15:46
It could be. But at problem #2933 the media source worked for the user. With my files, media source has the same problem as VLC built in. 

Anyone can make a guess if this is fixable? Unfortunately it is super important for my project. :-( 

Here you can find a short sample file: https://we.tl/t-ItdtUJfPkr

**Comment by glowfishDE** [comment] 2021-05-19 13:58
I have the exact same issue. Can we expect a fix soon?

**Comment by mycroftcanner** [comment] 2022-01-31 03:53
I am still experiencing the same issue... and any video I rotate in the Photos app on iOS end up stretched in the vlc video source.

**Comment by mycroftcanner** [comment] 2022-02-03 15:58
Here is a sample file:

https://user-images.githubusercontent.com/55385694/152379135-a6f0b7c8-97d1-487b-8bd5-351907cb7c86.mov

**Closed** 2022-05-07 23:03 UTC
