### ISSUE TITLE
OBS 28.0.1 cannot close the windows of "windows capture" by the button of Cancel

### ISSUE THREAD

**Issue by iesv** [obsproject/obs-studio#7299] opened 2022-09-05 12:37 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Kcu3T4-jljUwdroS

### Expected Behavior

.

### Current Behavior

OBS 28.01 cannot close the windows of "windows capture" by the button of Cancel when windows is none.

### Steps to Reproduce

1. add Window Capture
2. click the button of cancel
3. cannot close the windows
...

**Comment by Fenrirthviti** [comment] 2022-09-06 02:18
I've tested this and I cannot replicate, at least on Windows 11. Any step along the way clicking Cancel works just fine for me.

Might be some missing information here on which exact window or steps are required.

**Comment by iesvme** [comment] 2022-09-06 15:00
https://user-images.githubusercontent.com/16969250/188668849-1301f7e4-a912-41f2-b7be-ed38dc104dba.mp4

**Comment by tuduweb** [comment] 2022-09-07 10:06
I can reproduce this in obs27/obs28 on win10.

**Comment by Fenrirthviti** [comment] 2022-09-08 05:44
Very interesting that there's no window being picked up by default. In my testing, creating a new source will always default to the first window in the dropdown. Possibly some kind of security software blocking OBS from enumerating the window capture options?

If you select an option for "Window" does the cancel button work correctly?

**Comment by RytoEX** [comment] 2022-09-08 13:32
I can reproduce this. It requires that you _only_ have OBS open, and no other applications such that there are no selectable windows enumerated.

**Comment by RytoEX** [comment] 2022-10-22 07:04
I think this is technically a duplicate of #4093, but both have good information on them.

**Closed** 2023-06-07 19:50 UTC
Labels: Confirmed
