### ISSUE TITLE
Only when streaming with AV1-SVT encoder to Youtube, the stream does not restore it self if frames have dropped. other encoders do restore the stream when connection stabilizes

### ISSUE THREAD

**Issue by lieno** [obsproject/obs-studio#10584] opened 2024-04-21 18:31 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/0E2OEckpOnAee6kh

### Expected Behavior

OBS with AV1-SVT encoder selected should continue the stream to YouTube after frames dropped. and connection has stabilized.

### Current Behavior

Only when using the new AV1-SVT this happen, if for example you are streaming, and you upload a big file, saturating your upload speed, the stream naturally will drop frames, but after you stop uploading the big file. the stream will keep permanently dropping frames forever. even though the internet is very stable. I thoroughly tested this with all other encoders except AV1-AOM. they all restore the stream once connection is stabilized
![OBS](https://github.com/obsproject/obs-studio/assets/23524925/39f77667-5faa-4a4e-a697-3176cd3868ef)

### Steps to Reproduce

1.Stream to YouTube with AV1-SVT
2.reproduce by getting it to dropframes: I can do it by saturating my upload speed. like uploading a big file
3.Stop the thing that causes it to dropframes. it will not restore the stream and it will keep dropping frames
...

### Anything else we should know?

I tried the other Youtube servers same issue, but this issue does not exist when using other encoders like x264, NVENC, H264

**Comment by derrod** [comment] 2024-04-21 18:52
Duplicate of #10383

**Closed by derrod** 2024-04-21 18:52 UTC

**Comment by lieno** [comment] 2024-04-21 19:14
@derrodclosed 

> closed this as [not planned]

 if I read #10383 correctly you have contributed a fix for the issue? or has an update already fixed it, because I still see alot of people having the exact issue as its pretty simple to reproduce

**Comment by derrod** [comment] 2024-04-21 19:40
It has been fixed in master, a version that includes the fix has not been released yet.
