### ISSUE TITLE
Apple VT H264 Hardware Encoder not available in Apple Silicon (M1) MacBook Pro

### ISSUE THREAD

**Issue by polamjag** [obsproject/obs-studio#4170] opened 2021-01-31 13:20 UTC
## Platform

Operating system and version: macOS Big Sur version 11.1 (20C69) / MacBook Pro (13-inch, M1, 2020)
OBS Studio version: 26.1.2

## Expected Behavior

- Apple VT H264 Hardware Encoder should appear in video encoder selector dropdown like this:
  - <img width="667" alt="scr 2021-01-31 at 21 31 06" src="https://user-images.githubusercontent.com/685936/106383896-aa544780-640b-11eb-9b82-407d2b9cef75.png">

## Current Behavior

- Apple VT H264 Hardware Encoder won't appear in video encoder selector dropdown:
  - <img width="672" alt="scr 2021-01-31 at 21 31 44" src="https://user-images.githubusercontent.com/685936/106383923-be984480-640b-11eb-8d23-337c9cea5c6f.png">

## Steps to Reproduce

1. Install OBS on Mac computers with Apple Silicon
2. Launch OBS and go to settings (preferences) screen > output section > set "Output Mode" to "Advanced" > "Streaming" tab > select "Encoder" dropdown. No "Apple VT H264 Hardware Encoder" option in the dropdown

## Additional information

I'm not aware of this problem is reproduced in every Macs with Apple Silicon -- because I only have one MacBook Pro with Apple Silicon. 

I searched around web (incl. issues and OBS forum posts) and Twitter, I found only one possibly relevant Twitter post mentioning both M1 Mac and Hardware Encoder of OBS: https://twitter.com/PB_Undesirables/status/1334933759871889409

### Some investigations

In OBS source code, Apple VT H264 Hardware Encoder is looked up with ID `com.apple.videotoolbox.videoencoder.h264.gva`:

https://github.com/obsproject/obs-studio/blob/9eb32eed18214eb3b292449fe46cd7749db86788/plugins/mac-vth264/encoder.c#L26

I enumerated VideoToolbox encoders in my Mac with Apple Silicon then I found that H.264 hardware encoder is only available with [`EncoderID`](https://developer.apple.com/documentation/videotoolbox/kvtvideoencoderspecification_encoderid) = `com.apple.videotoolbox.videoencoder.ave.avc` (ref. https://gist.github.com/polamjag/3f7c0e52cf792321dde409f98cccf488#file-gistfile1-txt-L68-L76).

I made some modifications around there to check for EncoderID `com.apple.videotoolbox.videoencoder.ave.avc` like below:

https://github.com/obsproject/obs-studio/compare/master...polamjag:apple-vt-hardwareenc-id

This just worked 😌

<img width="1034" alt="scr 2021-01-31 at 20 45 48" src="https://user-images.githubusercontent.com/685936/106384973-20a77880-6411-11eb-8b85-81e0d79838d9.png">

Can I create a pull request at this point?

**Comment by SharkyRawr** [comment] 2021-02-01 01:53
Sadly it does not seem to work on my M1 MacBook Air:
`[VideoToolbox streaming_h264: 'h264']: Error in VTCompressionSessionCreate( kCFAllocatorDefault, enc->width, enc->height, kCMVideoCodecType_H264, encoder_spec, pixbuf_spec, NULL, &sample_encoded_callback, enc->queue, &s): The operation couldn’t be completed. (OSStatus error -12908.)`  
Full log here: https://gist.github.com/SharkyRawr/61a3db69ede9c9d0c402006736012cb3

Apple VT Software encoder continues to work fine though.

I also had to merge https://github.com/obsproject/obs-studio/pull/4105 otherwise it seemed to crash on start though not 100% certain of that.

**Comment by SharkyRawr** [comment] 2021-02-01 02:51
This diff makes the hardware encoder work:

```
diff --git a/plugins/mac-vth264/encoder.c b/plugins/mac-vth264/encoder.c
index 2d4d9bde9..2dd9a7974 100644
--- a/plugins/mac-vth264/encoder.c
+++ b/plugins/mac-vth264/encoder.c
@@ -522,6 +522,11 @@ static void *vt_h264_create_hw(obs_data_t *settings, obs_encoder_t *encoder)
 	return vt_h264_create(settings, encoder, APPLE_H264_ENC_ID_HW);
 }
 
+static void *vt_h264_create_hw_extra(obs_data_t *settings, obs_encoder_t *encoder)
+{
+    return vt_h264_create(settings, encoder, APPLE_H264_ENC_ID_HW_EXTRA);
+}
+
 static void *vt_h264_create_sw(obs_data_t *settings, obs_encoder_t *encoder)
 {
 	return vt_h264_create(settings, encoder, APPLE_H264_ENC_ID_SW);
@@ -1001,7 +1006,8 @@ void register_encoders()
 			   APPLE_H264_ENC_ID_HW_EXTRA) == 0) {
 			info.id = "vt_h264_hw";
 			info.get_name = vt_h264_getname_hw;
-			info.create = vt_h264_create_hw;
+			info.create = strcmp(vt_encoders.array[i].id,
+                                 APPLE_H264_ENC_ID_HW_EXTRA) == 0 ? vt_h264_create_hw_extra : vt_h264_create_hw;
 			obs_register_encoder(&info);
 		} else if (strcmp(vt_encoders.array[i].id,
 				  APPLE_H264_ENC_ID_SW) == 0) {

```

It's a bit hacky but it does encode and does show a picture on receiving stream player.

**Comment by polamjag** [comment] 2021-02-01 14:24
@SharkyRawr 

Thanks for trying out my changes! I guess from your log and extra patch that H.264 hardware encoder is available with both of EncoderID `com.apple.videotoolbox.videoencoder.h264.gva` and `com.apple.videotoolbox.videoencoder.ave.avc` 🤔 

Did you build natively for Apple Silicon? (I've tested my changes under Rosetta 2)

-----

By the way, I found that Apple mentions this topic in https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code#3616876:

> - Encoder IDs in the Video Toolbox framework may differ on arm64 and x86_64 architectures and on different versions of macOS. For example, the value in [`kVTVideoEncoderSpecification_EncoderID`](https://developer.apple.com/documentation/videotoolbox/kvtvideoencoderspecification_encoderid) may differ between architectures.

**Comment by foxgeere** [comment] 2021-02-01 14:50
In case it helps.

- Mac M1 Mac mini 16GB
- Mac OS Big Sur 11.2 RC2
- OBS latest version released

SIMPLE SETTINGS and ADVANCED SETTINGS show different drop down options. None of which are hardware. 

![Screenshot 2021-02-01 at 14 48 23](https://user-images.githubusercontent.com/10975935/106474330-bb00ce00-649c-11eb-858f-7edff3e07061.png)
![Screenshot 2021-02-01 at 14 48 36](https://user-images.githubusercontent.com/10975935/106474335-bb996480-649c-11eb-9d79-00ea03b7ef92.png)

**Comment by SharkyRawr** [comment] 2021-02-01 15:23
Yes I made a fully native arm64 built of OBS. I also made a quick tool to list all VideoToolbox codecs: https://github.com/SharkyRawr/videotoolbox-list
Compiling and running it with `-arch arm64` and `-arch x86_64` revealed no differences on my MBA M1 Big Sur 11.1:

```
[...]
Name: Apple H.264 (HW)
Display Name: Apple H.264 (HW)
Id: com.apple.videotoolbox.videoencoder.ave.avc
=========================
Name: Apple H.264 (SW)
Display Name: Apple H.264 (SW)
Id: com.apple.videotoolbox.videoencoder.h264
[...]
```

I'm missing the `.gva` suffix on the software encoder. Which is why it failed when attempting to run `VTCompressionSessionCreate` on a non-existent codec id. Added the `vt_h264_create_hw_extra` function to create the session with the proper id which the logs reflect:

```
04:21:20.039: [VideoToolbox streaming_h264: 'h264']: session created with hardware encoding
04:21:20.063: [VideoToolbox streaming_h264: 'h264']: settings:
04:21:20.063: 	vt_encoder_id          com.apple.videotoolbox.videoencoder.ave.avc
04:21:20.063: 	bitrate:               3500 (kbps)
04:21:20.063: 	fps_num:               30
04:21:20.063: 	fps_den:               1
04:21:20.063: 	width:                 1440
04:21:20.063: 	height:                900
04:21:20.063: 	keyint:                0 (s)
04:21:20.063: 	limit_bitrate:         off
04:21:20.063: 	rc_max_bitrate:        2500 (kbps)
04:21:20.063: 	rc_max_bitrate_window: 1.500000 (s)
04:21:20.063: 	hw_enc:                on
04:21:20.063: 	profile:               main
```

**Comment by foxgeere** [comment] 2021-02-01 15:28
Wow, you mean we may not be a million miles away from an ARM version? Thank you for all the work and effort you are contributing. Not sure how I can be helpful but I have a Mac mini M1 so if there is anything I can test that helps let me know.

**Comment by RustySly** [comment] 2021-02-02 03:47
First of all, thanks! I have a MacBook Air M1 16GB and Hardware Encoding unlocks successfully with the modified encoder.c file but with a caveat; when you chose to limit the bitrate and enter a max bitrate, if you try to record, it does not stop the first time you press the button but the second time and if you try to stream, it fails to send data completely.

![image](https://user-images.githubusercontent.com/61377822/106549501-29d43a80-6522-11eb-9a05-f4563548ee56.png)

**Comment by ImBada** [comment] 2021-02-05 01:44
> First of all, thanks! I have a MacBook Air M1 16GB and Hardware Encoding unlocks successfully with the modified encoder.c file but with a caveat; when you chose to limit the bitrate and enter a max bitrate, if you try to record, it does not stop the first time you press the button but the second time and if you try to stream, it fails to send data completely.
> 
> ![image](https://user-images.githubusercontent.com/61377822/106549501-29d43a80-6522-11eb-9a05-f4563548ee56.png)

![스크린샷 2021-02-05 오전 10 42 13](https://user-images.githubusercontent.com/25735451/106978141-fc47f500-679e-11eb-808e-41db6dc2f935.png)
I've tested your build and It seems it's not a video issue. It's an audio issue with the VT Hardware encoder.

**Comment by vangdfang** [comment] 2021-02-09 22:05
If you’re missing audio, please see some of my comments on #4105 – it’s likely that the reason you’re missing the audio is because OBS doesn’t see the audio and video streams as “synced”.  The patch there addresses it.

**Comment by timrosede** [comment] 2021-02-13 20:52
Thanks for your work, unfortunately I don't have much experience with C++ so I need your help. I can't get the branch "bugfix-applesilicon" to compile.

I think I am missing the "obsdeps" in ARM64 architecture, but how can I get or create them? I would like to help but need some initial help.

**Comment by iRonJ** [comment] 2021-02-18 05:16
> Yes I made a fully native arm64 built of OBS. I also made a quick tool to list all VideoToolbox codecs: https://github.com/SharkyRawr/videotoolbox-list
> Compiling and running it with `-arch arm64` and `-arch x86_64` revealed no differences on my MBA M1 Big Sur 11.1:
> 
> ```
> [...]
> Name: Apple H.264 (HW)
> Display Name: Apple H.264 (HW)
> Id: com.apple.videotoolbox.videoencoder.ave.avc
> =========================
> Name: Apple H.264 (SW)
> Display Name: Apple H.264 (SW)
> Id: com.apple.videotoolbox.videoencoder.h264
> [...]
> ```
> 
> I'm missing the `.gva` suffix on the software encoder. Which is why it failed when attempting to run `VTCompressionSessionCreate` on a non-existent codec id. Added the `vt_h264_create_hw_extra` function to create the session with the proper id which the logs reflect:
> 
> ```
> 04:21:20.039: [VideoToolbox streaming_h264: 'h264']: session created with hardware encoding
> 04:21:20.063: [VideoToolbox streaming_h264: 'h264']: settings:
> 04:21:20.063: 	vt_encoder_id          com.apple.videotoolbox.videoencoder.ave.avc
> 04:21:20.063: 	bitrate:               3500 (kbps)
> 04:21:20.063: 	fps_num:               30
> 04:21:20.063: 	fps_den:               1
> 04:21:20.063: 	width:                 1440
> 04:21:20.063: 	height:                900
> 04:21:20.063: 	keyint:                0 (s)
> 04:21:20.063: 	limit_bitrate:         off
> 04:21:20.063: 	rc_max_bitrate:        2500 (kbps)
> 04:21:20.063: 	rc_max_bitrate_window: 1.500000 (s)
> 04:21:20.063: 	hw_enc:                on
> 04:21:20.063: 	profile:               main
> ```

just curious how you get it to build for M1? I can get it to build after swapping out the x86 libs for arm libs, but I'm getting a mach-o binary error trying to run the app after it builds.

**Comment by vangdfang** [comment] 2021-02-18 05:38
> just curious how you get it to build for M1? I can get it to build after swapping out the x86 libs for arm libs, but I'm getting a mach-o binary error trying to run the app after it builds.

In short, yes, exactly this.  I basically followed the steps for building obsdeps, but with ARM libs (and you can stitch the two together to form Universal binaries, too).  The error you’re getting is almost certainly caused by the `-pagezero_size` and `-image_base` linker arguments. (As noted over in #4105, a newer LuaJIT will resolve the need for this on Intel, but with the current version in obsdeps, omitting these will break LuaJIT on Intel, but not for ARM.)

**Comment by MrBenFTW** [comment] 2021-02-22 11:31
> > just curious how you get it to build for M1? I can get it to build after swapping out the x86 libs for arm libs, but I'm getting a mach-o binary error trying to run the app after it builds.
> 
> In short, yes, exactly this. I basically followed the steps for building obsdeps, but with ARM libs (and you can stitch the two together to form Universal binaries, too). The error you’re getting is almost certainly caused by the `-pagezero_size` and `-image_base` linker arguments. (As noted over in #4105, a newer LuaJIT will resolve the need for this on Intel, but with the current version in obsdeps, omitting these will break LuaJIT on Intel, but not for ARM.)

Just saw this, where do I specify the Arm libs? in the `full-build-macos.sh` file? I opened an issue here #4266

**Comment by vangdfang** [comment] 2021-03-01 07:55
FYI, #4105 landed this evening, so I believe the issue is at least partially resolved -- or will be when an ARM64-native build of OBS's dependencies are complete, and OBS itself can build as a native binary. (BTW, thanks @polamjag for the callout to the Video Toolbox porting guide specifically -- while I chose a different path, I wouldn't have known about the issue had you and @SharkyRawr tagged my PR!)

**Comment by tomlube** [comment] 2021-03-13 21:13
Anyone want to post their m1 build? haha

**Comment by MrBenFTW** [comment] 2021-03-13 22:04
> Anyone want to post their m1 build? haha

Also want this. I can't figure out how to build it for arm myself manually

**Comment by SharkyRawr** [comment] 2021-03-13 22:29
> > Anyone want to post their m1 build? haha
> 
> Also want this. I can't figure out how to build it for arm myself manually

I made one, just using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

**Comment by MrBenFTW** [comment] 2021-03-13 23:11
> I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

Did you test it? I can't open it
<img width="372" alt="Screenshot 2021-03-13 at 23 09 46" src="https://user-images.githubusercontent.com/27426792/111052236-361cb300-8451-11eb-867f-ab16da50db5b.png">

Running the binary returns this:

```
benmitchell@Scylla ~ % /Applications/OBS.app/Contents/MacOS/OBS 
dyld: Library not loaded: /opt/homebrew/opt/qt@5/lib/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
  Reason: image not found
zsh: abort      /Applications/OBS.app/Contents/MacOS/OBS
```

I tried installing `QtSvg` with brew but it wasn't found

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "qtsvg".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by tomlube** [comment] 2021-03-13 23:41
Yeah same issue here. Tried installing QT through homebrew but same issue, surprisingly enough.

**Comment by tomlube** [comment] 2021-03-14 00:12
Also, rather confusingly, https://cdn.discordapp.com/attachments/680539133478699044/820449177099698187/unknown.png

**Comment by SharkyRawr** [comment] 2021-03-14 09:33
> > I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> > https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip
> 
> Did you test it? I can't open it

I'm not in the apple dev program so it's not signed and macOS freaks out, you can rightlick the Dmg and choose open and then a dialog will ask you if you want to open it anyways. Do the same with the .app bundle and it should work.

**Comment by MrBenFTW** [comment] 2021-03-14 14:32
> I'm not in the apple dev program so it's not signed and macOS freaks out, you can rightlick the Dmg and choose open and then a dialog will ask you if you want to open it anyways. Do the same with the .app bundle and it should work.

That doesn't seem to be the issue, I've resigned it already. The app is missing a library:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 30E6CA21-D5E6-36F7-8CF2-AABA2D292564
Library not loaded: /opt/homebrew/*/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
  Reason: image not found

```

**Comment by RustySly** [comment] 2021-03-15 00:04
at first, i tried to change the needed files' location by editing the obs executable with hexedit and made it all the way through to the qtmacextras framework but i realized that the qt@6 does not have that framework. so, it occurred to me that the app requests specifically the qt@5 (that has the qtmacextras framework), after installing that version obs worked just fine :)

qt@5: https://formulae.brew.sh/formula/qt@5

**Comment by tomlube** [comment] 2021-03-15 00:17
> at first, i tried to change the needed files' location by editing the obs executable with hexedit and made it all the way through to the qtmacextras framework but i realized that the qt@6 does not have that framework. so, it occurred to me that the app requests specifically the qt@5 (that has the qtmacextras framework), after installing that version obs worked just fine :)
> 
> qt@5: https://formulae.brew.sh/formula/qt@5

thanks, mine now fails because it's missing libavcodec now >.<

**Comment by fknorn** [comment] 2021-03-16 06:48
> https://github.com/obsproject/obs-studio/issues/4170?_pjax=%23js-repo-pjax-container#issuecomment-798795640

Thank you, this worked for me, together with

`brew install ffmpeg` and `brew install qt@5`

However, the Virtual Camera is not working using that constellation. I know this is an [issue that others have experienced too](https://obsproject.com/forum/threads/fyi-macos-virtual-cam-on-obs-26-1.135468/), but that thread seems to have stalled an I'm wondering what the current situation is?

Has anyone of you now got OBS running on Apple Silicon, with **working hardware encoding** and **working virtual camera** in apps other than Zoom? Cheers!

**Comment by pixelyunicorn** [comment] 2021-03-17 05:26
> > I'm not in the apple dev program so it's not signed and macOS freaks out, you can rightlick the Dmg and choose open and then a dialog will ask you if you want to open it anyways. Do the same with the .app bundle and it should work.
> 
> That doesn't seem to be the issue, I've resigned it already. The app is missing a library:
> 
> ```
> Termination Reason:    DYLD, [0x1] Library missing
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   dyld: Using shared cache: 30E6CA21-D5E6-36F7-8CF2-AABA2D292564
> Library not loaded: /opt/homebrew/*/QtSvg.framework/Versions/5/QtSvg
>   Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
>   Reason: image not found
> ```

i am having the same issue, even after using `brew install ffmpeg` and `brew install qt@5`. not sure what else i should do to further debug this.

**Comment by tomlube** [comment] 2021-03-17 13:18
> > > I'm not in the apple dev program so it's not signed and macOS freaks out, you can rightlick the Dmg and choose open and then a dialog will ask you if you want to open it anyways. Do the same with the .app bundle and it should work.
> > 
> > 
> > That doesn't seem to be the issue, I've resigned it already. The app is missing a library:
> > ```
> > Termination Reason:    DYLD, [0x1] Library missing
> > 
> > Application Specific Information:
> > dyld: launch, loading dependent libraries
> > 
> > Dyld Error Message:
> >   dyld: Using shared cache: 30E6CA21-D5E6-36F7-8CF2-AABA2D292564
> > Library not loaded: /opt/homebrew/*/QtSvg.framework/Versions/5/QtSvg
> >   Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
> >   Reason: image not found
> > ```
> 
> i am having the same issue, even after using `brew install ffmpeg` and `brew install qt@5`. not sure what else i should do to further debug this.

If you're still getting that error then you didn't install QT correctly. Have you installed homebrew before?

**Comment by pixelyunicorn** [comment] 2021-03-17 14:42
> If you're still getting that error then you didn't install QT correctly. Have you installed homebrew before?

i use homebrew all the time for development, and i ran `brew reinstall qt@5` a few times to be sure. i still have the same error:

````
dyld: Library not loaded: /opt/homebrew/opt/qt@5/lib/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
  Reason: image not found
fish: Job 1, '/Applications/OBS.app/Contents/…' terminated by signal SIGABRT (Abort)
````

**Comment by tomlube** [comment] 2021-03-17 15:07
QT hasn't installed correctly then, I'm not sure why that is though. Installing qt@5 solved the issue for me. Reboot maybe?

**Comment by MrBenFTW** [comment] 2021-03-17 15:16
> QT hasn't installed correctly then, I'm not sure why that is though. Installing qt@5 solved the issue for me. Reboot maybe?

I also installed QT using home brew and am facing the same issues after a reboot

**Comment by MrBenFTW** [comment] 2021-03-18 10:12
I just built it myself on my x86 build server using the latest source code as of 20 minutes ago and it unlocked the hardware encoder?? 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/27426792/111608980-ba649280-87d1-11eb-9645-d496810bb5ab.png">

**Comment by MrBenFTW** [comment] 2021-03-18 15:56
> > > Anyone want to post their m1 build? haha
> > 
> > 
> > Also want this. I can't figure out how to build it for arm myself manually
> 
> I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

Can you tell me what commands you ran exactly (arguments etc) and also did you have to modify any files?

**Comment by paoloestar** [comment] 2021-03-19 08:25
> > > > Anyone want to post their m1 build? haha
> > > 
> > > 
> > > Also want this. I can't figure out how to build it for arm myself manually
> > 
> > 
> > I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> > https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip
> 
> Can you tell me what commands you ran exactly (arguments etc) and also did you have to modify any files?

Works for me! -thanks for the build. Looks we are not far away from a final m1 native build!

**Comment by polamjag** [comment] 2021-03-19 16:21
https://github.com/obsproject/obs-studio/issues/4170#issuecomment-801797895

This is because the problem is about the logic to look up hardware encoder (4c0bb383885b8f858b7c038c98aa53aed5188a59 in #4105 is about that) but not the binary architecture of OBS

**Comment by rgaufman** [comment] 2021-03-20 12:23
> > > > > Anyone want to post their m1 build? haha
> > > > 
> > > > 
> > > > Also want this. I can't figure out how to build it for arm myself manually
> > > 
> > > 
> > > I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> > > https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip
> > 
> > 
> > Can you tell me what commands you ran exactly (arguments etc) and also did you have to modify any files?
> 
> Works for me! -thanks for the build. Looks we are not far away from a final m1 native build!

When I tried to launch that package, I see:

```
$  /Applications/OBS.app/Contents/MacOS/OBS
dyld: Library not loaded: /opt/homebrew/opt/qt@5/lib/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/OBS.app/Contents/Resources/bin/obs
  Reason: image not found
[1]    7444 abort      /Applications/OBS.app/Contents/MacOS/OBS
```

Any ideas?

**Comment by rgaufman** [comment] 2021-03-20 12:27
I installed this package: https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

But when I press "Start Virtual Camera", I just see this in the logs:

```
info: [mac-virtualcam] [macOS] VirtualCam DAL Plugin not shipped with OBS
```

Is there an M1 native package with the virtualcam plugin? :)

**Comment by ImBada** [comment] 2021-03-20 13:15
> > > Anyone want to post their m1 build? haha
> > 
> > 
> > Also want this. I can't figure out how to build it for arm myself manually
> 
> I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

It works but there's no browser source feature…  any chance?

**Comment by richiepreece** [comment] 2021-03-20 21:59
[Here is arguably a better solution. You simply replace a `.so` file in the original application and it enables hardware encoding. My CPU went from having a core pegged and dropping frames, to basically no effort from the computer at all](https://obsproject.com/forum/threads/%E2%80%9Capple-vt-h264-hardware-encoder-unlocked-for-apple-silicon-m1.138433/)

**Comment by fknorn** [comment] 2021-03-21 12:08
Thank you all. So, being the impatient "expert" I am, I got another step closer. I combined @SharkyRawr's M1 build (Thanks again for that! That one runs native on Apple Silicon and, including the hardware-encoder, but not the Virtual Camera)

> https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

with Virtual Camera plugin from the official release, copying the file `ops-mac-virtualcam.plugin` from the OBS.app > Contents > Resources > data folder to the corresponding location under the M1 build, and voilà, it works (in Zoom at least)! 

And that seems to be native, since all OBS-related processes show "Apple" as architecture in the system's Activity Monitor.

Now, the only thing that's left is getting the virtual camera to show up in more apps, like Skype, not just Zoom...

**Comment by MrBenFTW** [comment] 2021-03-21 12:26
> Now, the only thing that's left is getting the virtual camera to show up in more apps, like Skype, not just Zoom...

Could you post your build?

Also, you might have to unsign some apps for it to show up. 

Discord: `sudo codesign --remove-signature /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(GPU\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Plugin\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Renderer\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper.app`

**Comment by fknorn** [comment] 2021-03-21 17:37
> > Now, the only thing that's left is getting the virtual camera to show up in more apps, like Skype, not just Zoom...
> 
> Could you post your build?
> 
> Also, you might have to unsign some apps for it to show up.
> 
> Discord:
> 
> ```
> sudo codesign --remove-signature /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(GPU\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Plugin\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Renderer\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper.app
> ```

Thanks Ben, the `codesign` call did the trick on the respective files for Skype! I can't post my build since it's not mine — but I already posted the link and described what I did to get the Virtual Camera to work ;-)

**Comment by paoloestar** [comment] 2021-03-21 21:59
> > > Now, the only thing that's left is getting the virtual camera to show up in more apps, like Skype, not just Zoom...
> > 
> > 
> > Could you post your build?
> > Also, you might have to unsign some apps for it to show up.
> > Discord:
> > ```
> > sudo codesign --remove-signature /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(GPU\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Plugin\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper\ \(Renderer\).app /Applications/Discord.app/Contents/Frameworks/Discord\ Helper.app
> > ```
> 
> Thanks Ben, the `codesign` call did the trick on the respective files for Skype! I can't post my build since it's not mine — but I already posted the link and described what I did to get the Virtual Camera to work ;-)

I cannot start jobs due to an error - library missing. 
Dyld Error Message:
  dyld: Using shared cache: 2DD809D8-158E-3CB3-8D50-23543930242E
Library not loaded: /opt/homebrew/*/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Applications/OBS experimental.app/Contents/Resources/bin/obs
  Reason: image not found

any help?

**Comment by WizardCM** [comment] 2021-03-21 22:13
Hi everyone, please keep discussion in this issue specific to the missing encoder, and not for troubleshooting custom builds or modifying signatures of other apps.

**Comment by RustySly** [comment] 2021-03-22 01:19
actually, the issue is not completely resolved yet. now, the apple vt hardware encoder is accessible but if you try to limit the bitrate, you cannot stream or record as expected (i explained it before in this discussion). i built the obs for m1 myself and i can say that the problem is still there for both intel and apple builds.

**Comment by MrBenFTW** [comment] 2021-03-28 13:51
> > > Anyone want to post their m1 build? haha
> > 
> > 
> > Also want this. I can't figure out how to build it for arm myself manually
> 
> I made one, using `brew` to install all the deps and compile with `cmake` and generate the dmg with `cpack`.
> https://github.com/SharkyRawr/m1-builds/raw/main/bin/obs-studio-x64-26.1.2-251-g54892b27d-modified.dmg.zip

Could you let me know the exact commands you used to compile? I can't figure it out. I also tried to make an Xcode project but it said there was some file missing? not sure I am doing it from the right dir

**Comment by RytoEX** [comment] 2021-04-13 06:13
With the merging of #4105, this should be fixed as of OBS Studio 27.0.0-rc1.  As such, I'm going to close this.  If the Apple VT Hardware Encoder is still not available in the latest OBS Studio 27 Release Candidate (currently OBS Studio 27.0.0-rc2), please comment and we can reopen this if necessary.

**Closed by RytoEX** 2021-04-13 06:13 UTC
Labels: macOS

**Comment by mathieunicolas** [comment] 2021-04-19 11:38
Hello, unfortunately, with a MacBook Pro M1 11.2.3 the 27.0.0-rc2 doesn't make Apple VT Hardware Encoder available =(
It's a new fresh install, I don't understand why it doesn't work. I also tried to replace the plugin `mac-vth264` with the one someone uploaded (saw it on (a forum)[https://obsproject.com/forum/threads/“apple-vt-h264-hardware-encoder-unlocked-for-apple-silicon-m1.138433/] ), and it doesn't work either.
Anyone has a clue about how to make hardware encoding working ?

**Comment by DevAndArtist** [comment] 2021-05-06 15:17
Is it incorrect that this patch does not enabled hardware encoder in `Simple` Output Mode? I do have the option with the `advanced` mode, but not with the `simple` one. 🤔

**Comment by rgaufman** [comment] 2021-05-16 18:25
I'm on RC4 and I still only see software and I'm not able to change from simple to advanced, the option is greyed out. I'm on a Macbook Pro M1 - any ideas? 
<img width="1093" alt="Screenshot 2021-05-16 at 19 24 26" src="https://user-images.githubusercontent.com/33842342/118408216-7e886500-b67c-11eb-8875-61f72757c942.png">

Also, is there a native Arm version, or just an Intel/Rosetta version?

**Comment by geerlingguy** [comment] 2021-06-01 21:18
@DevAndArtist - Even with non-M1 macs, the hardware encoder option was always hidden behind the 'advanced' mode tab, because it's use does have some limitations that can cause issues with certain types of streams.

**Comment by paulreimer** [comment] 2021-06-01 22:09
@geerlingguy I curious what those limitations might be (I've been happily using the Hardware Encoder; hopefully I haven't been excluding viewers or presenting a poor experience!)

**Comment by Alvt5** [comment] 2022-03-07 10:01
I only see x264 software encoder option (greyed out)  for 27.2.2 , there is no other option for hardware. I uploaded the modified .so into the plugins dir and also no change to the option.
I am on m1 pro, Monterey with latest ops. Any ideas?

**Comment by koenhendriks** [comment] 2022-05-25 09:31
When enabling the Hardware Encoder under video does it also enable it for the Virtual Camera? Or should it be enabled under streaming.

**Comment by koenhendriks** [comment] 2022-06-03 20:22
So for now on Mac there is no way of hardware encoding virtual cam? Looking at 140% CPU now ☹️

**Comment by gxalpha** [comment] 2022-06-03 21:26
OBS itself doesn't encode the virtualcam output at all. This means that any encoding would be done by whatever app your using the virtualcam in.

**Comment by Dibbyo456** [comment] 2022-09-21 15:51
As of v28.0.1, if I only record (not streams) then should I use Software h264 encoding or Hardware Apple h264?

**Comment by RytoEX** [comment] 2022-09-21 16:02
> As of v28.0.1, if I only record (not streams) then should I use Software h264 encoding or Hardware Apple h264?

Use whatever works best for your needs. Please use our [forums](https://obsproject.com/forum) or [Discord server](https://obsproject.com/discord) for support/usage questions.
