### ISSUE TITLE
Full screen projector on second monitor stays gray after (re-)start of OBS

### ISSUE THREAD

**Issue by LoukKamp** [obsproject/obs-studio#8729] opened 2023-04-13 01:14 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/k6jyU9IBt15FQ3gr

### Expected Behavior

When using a Full-screen Projector on a second monitor connected to the windows machine by HDMI, having the option "Save projectors on exit" enabled, the second monitor should show the projector, even after restarting OBS.

### Current Behavior

When using a Full-screen Projector on a second monitor connected to the windows machine by HDMI, having the option "Save projectors on exit" enabled, the second monitor turns into gray after restarting OBS.

This monitor stays gray, unless:
 - you open a new full screen projector on this second monitor
 - you change the scene collection to anything else and change it back to the one that was selected on startup.

### Steps to Reproduce

1. Start OSB (on the main screen of the Windows desktop (or the secondary screen))
2. Right click the Preview window and open a full screen projector on a secondary monitor
3. Or Enter studio mode
4. Right click the Program window and open a full screen projector on a secondary monitor
5. Load a media file containing an image (photo or video): The projector shows this image
6. Restart OBS
7. The projector on the secondary screen shows a gray image. However, audio does play on this monitor (as expected). 
...

### Anything else we should know?

This issue is first reported by [ikonix360](https://obsproject.com/forum/members/ikonix360.327603/) on mar 12, 2023: 

Ever since the **update at least two updates ago**, when I start OBS the full screen projector is showing nothing so I have to close that window and redo the full screen projector.

So, this issue seems to be introduced about two updates  ago since mar 12, 2023.

**Comment by RytoEX** [comment] 2023-04-13 03:18
Possible duplicate of #5083 ?

**Comment by LoukKamp** [comment] 2023-04-13 14:28
I Partly agree with RytoEX: The original issue was caused by switching from studio mode to normal mode, and in this case it is independent of working in studio mode or not. 

However in later comments, users report also situations like I described in this thread (a new variant of the same issue?).

The workaround with 2 instances of a full projector on the second screen also works for this issue, although I needed 3 instances.

I tested this on V29.1.0-Beta 3 and it is still there. I also tested this on a quite new Windows 11 system (HP) with the same results.

**Comment by RytoEX** [comment] 2023-04-13 18:53
If this is a duplicate of (or the same core issue as) #5083, then this goes back to at least OBS Studio 27.

1. Can you reproduce this with a normal image source, a color source, or no sources at all? 
2. Could you provide a screenshot of this?
3. What does the projector look like if you change the OBS theme? (I want to confirm if "gray" is just the background color of the window and not the actual viewport)
4. Can you reproduce the exact same behavior in OBS Studio 27? What about the latest OBS Studio 26?
5. Are you running just a single instance of OBS?

Initially, I'd wondered if this was strictly related to Intel iGPUs (you have an HD Graphics 620 while the OP on #5083 has an HD Graphics 520 with an NVIDIA 940MX) possibly with older drivers (yours and theirs are outdated), but the last reply on that Issue has an NVIDIA GTX 1070 with fairly modern drivers.

**Comment by LoukKamp** [comment] 2023-04-15 02:47
Thanks for the afford! I'm currently testing this with older versions of (26.02, 27.0.1, and 28.0.3) and this takes some time.
 
 - V26.0.2: Can't test (OBS stops with exception: obs_register_source: Tried to register obs_source_info with size 400 which is more than libobs currently supports (384))
- V27.0.1: Works fine (shows projector screen on second monitor after restart)
- V28.0.3: Gray screen on the second monitor after restart

The source does not seem to make any difference: When you create several different projectors (e.g. the first is the program window, the second is a video source, and the third a color source), the first projector created after restarting OBS will be gray. But what is shown on the monitor depends on the sequence of projectors being created (the last one is shown). 

Another test I did is first creating a projector on the main monitor (0) and after that a projector on the second monitor. Now the first projector on the main monitor will be gray, while the second monitor shows the source of the projector (color, image, or program)... So it is always the first projector created that will show a gray image, independently of the selected monitor.

I can't reproduce this with any other type of projector then the full screen projector.

I've tested with some different skin themes, and yes, you where right: the color of the projector screen on the second monitor changes with the the skin theme: When I select the white theme, the color of the projector screen changes to white. When I change it back to the default theme, it turns back to gray again.

Yes, I run a single instance of OBS at any time.

In the mean while, I start to think this might be a **timing** issue. When you create just one projector on another monitor (not the systems own monitor), this projector will stay gray after restarting OBS, but when you create two projectors on the same screen (like suggested in the workaround), only the first will stay gray, but the second will show all images. Maybe the first projector is started before the screens on the monitor are properly initialized. Maybe a small delay or some extra testing on the status of the software it depends on, might solve this problem.

**Comment by LoukKamp** [comment] 2023-04-15 14:44
Some additional tests:
 - V27.2.4 (last V27 release): Still OK
 - V28.0.0-beta1 (first V28 beta): Gray projector screen

Sadly enough, there are a log of changes and new features introduced between those two releases, so it is hard to find what possibly can cause this change in behavior.

Although one of them attracts my mind: 

- Shortened time to switch themes [WizardCM]

Optimizing the time to change themes might cause the projector windows to open earlier on the screen than before.

**Comment by LoukKamp** [comment] 2023-04-19 22:05
Some additional tests:
 - V27.2.4 (last V27 release): Still OK
 - V28.0.0-beta1 (first V28 beta): Gray projector screen

Sadly enough, there are a lot of changes and new features introduced between those two releases, so it is hard to find what possibly can cause this change in behavior.

Although one of them attracts my mind: 

- Shortened time to switch themes [WizardCM]

Optimizing the time to change themes might cause the projector windows to open earlier on the screen than before.

**Comment by LoukKamp** [comment] 2023-04-19 22:40
In addition to the info provided in the previous posts: I've been testing this on a HP laptop with the following specs:

CPU Name: AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
CPU Speed: 2495MHz
Physical Cores: 4, Logical Cores: 4
Physical Memory: 7645MB Total, 4522MB Free
Windows Version: 10.0 Build 19045 (release: 22H2; revision: 2846; 64-bit)
Running as administrator: false
Windows 10/11 Gaming Features:
Game DVR: On
Game Mode: Probably On (no reg key set)
Sec. Software Status:
 	Microsoft Defender Antivirus: enabled (AV)
 	Windows Firewall: enabled (FW)
 Current Date/Time: 2023-04-17, 22:05:43
 Browser Hardware Acceleration: true
 Hide OBS windows from screen capture: false
 Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
 Portable mode: false
 OBS 29.0.2 (64-bit, windows)

A full spec can be found in [This uploaded log file ](https://obsproject.com/logs/0fnHlT18CeJh8ojv)

On this system, only one full screen projector was opened on the second monitor (connected via HDMI). After restarting OBS, the projector opened with a normal image (no gray screen).

So, two different systems with the same version of OBS and the same content loaded result in different behavior! 

This could be caused by different (video) hardware, but in that case I wonder why it only occurs after starting OBS and it only affects the first full screen projector. So my best guess is still a timing issue (e.g. the projector is opened before the hardware is ready to handle the request.)

**Comment by gxalpha** [comment] 2023-09-11 13:32
Duplicate of #5083

**Closed by gxalpha** 2023-09-11 13:32 UTC

**Comment by prehprehpreh** [comment] 2024-03-23 17:50
This still happens to me when I start OBS. I have to close the projector output and re open it to get it to work

**Comment by RytoEX** [comment] 2024-03-23 19:04
> This still happens to me when I start OBS. I have to close the projector output and re open it to get it to work

Please reply on #5083 instead with answers to [my previously asked questions](https://github.com/obsproject/obs-studio/issues/8729#issuecomment-1507463755):

> If this is a duplicate of (or the same core issue as) #5083, then this goes back to at least OBS Studio 27.
>     1. Can you reproduce this with a normal image source, a color source, or no sources at all?
>     2. Could you provide a screenshot of this?
>     3. What does the projector look like if you change the OBS theme? (I want to confirm if "gray" is just the background color of the window and not the actual viewport)
>     4. Can you reproduce the exact same behavior in OBS Studio 27? What about the latest OBS Studio 26?
>     5. Are you running just a single instance of OBS?
