### ISSUE TITLE
Segmentation fault when click browse image in image plugin and after starting obs want keyring

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#2651] opened 2020-04-05 08:25 UTC
Build from source according obs wiki on my debian bullseye with browser source. There where no errors. When you click browse picture on image plugin properties you have segmentation fault immediately or few seconds later when you try find you picture. And second, when start obs, shows keyring dialog lika in opera. I use command for launch opera: "opera --password-store=basic %U" and there were no dialog. Need fix segmentation fault and disable keyring dialog.

**Comment by WizardCM** [comment] 2020-04-05 08:30
Please don't delete the issue template. It's required.

This is also a duplicate of #2644. For the keyring issue, please raise a separate issue.

**Closed by WizardCM** 2020-04-05 08:30 UTC
