### ISSUE TITLE
Panels have ampersands in title.

### ISSUE THREAD

**Issue by peterc-s** [obsproject/obs-studio#10367] opened 2024-03-13 17:21 UTC
### Operating System Info

Other

### Other OS

Endeavour OS

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.2-4 (installed from AUR)

### OBS Studio Log URL

https://obsproject.com/logs/VwnB12ndUhOMGfWt

### Expected Behavior

All panels to have normal names without & characters.

### Current Behavior

![image](https://github.com/obsproject/obs-studio/assets/66807853/77bb3ed5-ec06-462d-9096-3eb8f8c75249)

### Steps to Reproduce

This was on a fresh install of Endeavour OS so...

1. Installed obs-studio and v4l2loopback through `yay -S v4l2loopback obs-studio`,
2. Opened obs and chose the option to optimise for virtual camera.

**Comment by tytan652** [comment] 2024-03-13 17:22
Duplicate of #10341

**Closed by tytan652** 2024-03-13 17:22 UTC
