### ISSUE TITLE
Video Capture window freezes constantly

### ISSUE THREAD

**Issue by ImaraRavenfire** [obsproject/obs-studio#7812] opened 2022-11-19 16:02 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/6Mv1l3Ax1gV-JTAu

### Expected Behavior

I expected to be able to add my camera as a source, but the second I did, OBS froze entirely and I had to task manager shut it down.

### Current Behavior

I attempted to add my camera as a source, only for it to decide it wasn't going to allow that, freezing the entire program to the point that it had to be manually shut down in the task manager

### Steps to Reproduce

1. Open OBS
2. Add Source > Video Capture Device
3. Alternatively, open the properties on your video capture device
...

### Anything else we should know?

It worked fine in the previous version of OBS and has only started happening since the latest update as well as the latest windows update

**Comment by Fenrirthviti** [comment] 2022-11-19 17:15
Driver Version: 31.0.15.2698

This is a known issue with certain nvidia drivers, including the version you are on. Either rolling back, or removing Unity Virtual Camera (the most common triggering cause), or other non-OBS Virtual Cameras might resolve this, however it's a driver bug and outside our control to fix on our side.

I will leave this open for tracking purposes, as we do have an open line of communication with NVIDIA regarding the issue.

**Comment by AudricSan** [comment] 2023-03-03 09:31
Going back to an older version of nvidia driver indeed solves the problem..

Put an update of Obs at this level would it be planned?Because it can be annoying for some games not to have the latest version of the driver, I find it hard to uninstall the driver each time I want to add a Video capture in Obs to reinstall it afterwards 😅

**Comment by Fenrirthviti** [comment] 2023-03-03 18:13
In the next release of OBS, we are hoping to have merged a new feature to block the offending third-party tool from loading in OBS https://github.com/obsproject/obs-studio/pull/8343. This should help reduce this. It is not a bug with NVIDIA, or with OBS, but rather a third-party virtual camera device (UnityCapture, which is commonly used by vtuber applications and has already been patched in newer versions of those).

**Comment by guiglass** [comment] 2023-03-05 09:04
> In the next release of OBS, we are hoping to have merged a new feature to block the offending third-party tool from loading in OBS #8343. This should help reduce this. It is not a bug with NVIDIA, or with OBS, but rather a third-party virtual camera device (UnityCapture, which is commonly used by vtuber applications and has already been patched in newer versions of those).

My game uses UnityCapture and I am running the latest OBS 29.0.2 (64 bit). When I go to add a new Video Capture Device the entire OBS application still freezes. This happens on all PCs. I don't think the bug is fixed yet.

**Comment by Fenrirthviti** [comment] 2023-03-05 19:07
We haven't shipped any new versions since that post was made, so the workaround on our end isn't in a release version. The issue lies in the UnityCapture piece, not OBS, or NVIDIA drivers. We don't fully understand why certain driver versions cause the issue to happen more frequently, but the correct solution is updating your UnityCapture component to a version that has the fix in it, such as the fork here: https://github.com/DenchiSoft/UnityCapture

We also recommend that if you want to use UnityCapture from your game in OBS, you will need to change the name of the .dll file to something unique once it has been patched, as the default of `unitycapturefilter64bit.dll` will be blocked in the next release.

**Comment by guiglass** [comment] 2023-03-05 20:57
@Fenrirthviti Are you saying there is a way to use UnityCapture with the latest OBS and Nvidia drivers? I just tried downloading the .dlls from the fork you recommended and ran the install.bat script, then I updated OBS and Nvidia drivers to current. I launched OBS and added a new Video Capture Device and OBS still was freezing.

What are the patched files in that fork I am not sure I am updating the correct files or if I am missing something?

**Comment by RytoEX** [comment] 2023-03-05 20:59
> @Fenrirthviti Are you saying there is a way to use UnityCapture with the latest OBS and Nvidia drivers? I just tried downloading the .dlls from the fork you recommended and ran the install.bat script, then I updated OBS and Nvidia drivers to current. I launched OBS and added a new Video Capture Device and OBS still was freezing.
> 
> What are the patched files in that fork? I am not sure I am updating the correct files or am I missing something else?

The DLLs in that repo are not based on current code. You must build it yourself.

**Comment by guiglass** [comment] 2023-03-05 21:22
I downloaded the project and from Source directory I opened UnityCaptureFilter.sln in VS and ran build. But in the build output folder all I see is UnityCaptureFilter32bit.dll but UnityCaptureFilter64bit.dll is not present.

![unity capture build](https://user-images.githubusercontent.com/27627161/222986605-52ad9cbf-8237-4607-937d-f2e3b259cabe.png)

Do I only need to build UnityCaptureFilter.sln or are there additional steps?
Thanks

**Comment by guiglass** [comment] 2023-03-05 21:39
> We also recommend that if you want to use UnityCapture from your game in OBS, you will need to change the name of the .dll file to something unique once it has been patched, as the default of `unitycapturefilter64bit.dll` will be blocked in the next release.

@Fenrirthviti Why is unitycapturefilter64bit.dll being black listed in the next release? I tried changing the names of the .dlls however when I modified the names in install.bat and run it causes Windows Defender to present a dialog stating "SmartScreen prevented an unrecognized app from starting" every time. I can continue to run but now customers will always see unrecognized app warnings when installing DirectShow, is it really necessary to block unitycapturefilter64bit.dll ?

**Comment by Fenrirthviti** [comment] 2023-03-06 01:11
Again, and let me state this clearly, and unambiguously:

The bug that causes this is ultimately in UnityCapture.

This is why we are choosing to block the default .dll file. The alternative is to let OBS continue to freeze, without any feedback or understanding by the user on why this is happening. I can't speak to any issues with your application, but it sounds like you might need to look in to some kind of code signing key to validate the new version.

As it stands, issues with a third-party application aren't relevant to the issue itself, and are more general development questions not related to OBS at this point. Let's please keep this thread on-topic.

**Comment by guiglass** [comment] 2023-03-06 08:15
> . I can't speak to any issues with your application

I downloaded the UnityCapture fork as you suggested, then changed the .dll names as you suggested, this caused Windows Defender to show warning messages when install.bat was executed. And has nothing to do with my or any specific application. This is on subject as I am responding to and following your recommendations.

However it makes absolutely no sense to my why you intend to block a .dll that works perfectly if the user compiles the .dlls themselves. It just is bloody nonsense and makes UnityCapture and OBS less desirable for vtubers.

**Comment by Fenrirthviti** [comment] 2023-03-06 19:44
> I downloaded the UnityCapture fork as you suggested, then changed the .dll names as you suggested, this caused Windows Defender to show warning messages when install.bat was executed. And had nothing to do with my specific application. I thought what I wrote was on-topic as I was responding to and following your recommendations.

Try registering them manually, as the install.bat script is trying to access the system directory, which is likely what Defender is unhappy about. I have not had this issue, so I can't speak to what you are doing differently.

> However it makes no sense to me why it is intended to block a .dll that works perfectly when the .dlls are compiled from the fork you shared. It just makes UnityCapture + OBS way more difficult for vtubers to use. Filename hacks and extra setup steps are only a minor inconvenience; but _trying to stay on-topic_ I don't understand how blocking .dlls to avoid freezing the UI solves the issue?

The .dll *does not work perfectly.* The unpatched .dll is what is causing the freezes in OBS. We have been working closely with other affected vtuber apps, who are all shipping a patched version of this .dll without issues. This is why we are taking steps to protect our users from an unrecoverable state where a third-party .dll is locking up OBS. If you have an alternative solution to fixing the freeze on a system with the bugged .dll file that doesn't involve blocking it, we are certainly open to exploring it.

**Closed** 2023-03-09 19:16 UTC
