### ISSUE TITLE
Unable to game capture when OBS is started after the target not before

### ISSUE THREAD

**Issue by Juesto** [obsproject/obs-studio#4084] opened 2021-01-17 02:58 UTC
I've verified for possible conflicts and it still happens.
I have UAC turned off so there shouldn't be any elevation issues.
error 57 is "parameter incorrect" apparently

## Platform
Operating system and version: 6.1.7601
OBS Studio version: 26.1.1 64-bits windows

## Expected Behavior
game capture should activate successfully

## Current Behavior
no capture happens at all and log shows following error: `is_app GetTokenInformation failed: 0x00000057` then stops capturing, see below

## Steps to Reproduce
1. Start game to capture
2. Start OBS
3. Attempt to capture
4. restart game without closing obs
5. capture works

## Additional information

example log with verbose and unfiltered enabled (which really doesn't make much difference) 

[2021-01-14 15-56-11.txt](https://github.com/obsproject/obs-studio/files/5825486/2021-01-14.15-56-11.txt)

```
15:57:33.051: [game-capture: 'Game Capture'] Activate hotkey pressed
15:57:33.061: is_app GetTokenInformation failed: 0x00000057
15:57:33.061: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:33.063: is_app GetTokenInformation failed: 0x00000057
15:57:33.064: [game-capture: 'Game Capture'] using helper (compatibility hook)
15:57:33.190: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
15:57:34.074: is_app GetTokenInformation failed: 0x00000057
15:57:34.074: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:34.076: is_app GetTokenInformation failed: 0x00000057
15:57:34.076: [game-capture: 'Game Capture'] using helper (compatibility hook)
15:57:35.087: is_app GetTokenInformation failed: 0x00000057
15:57:35.087: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:35.089: is_app GetTokenInformation failed: 0x00000057
15:57:35.089: [game-capture: 'Game Capture'] existing hook found, signaling process: (null)
15:57:35.090: [game-capture: 'Game Capture'] map id: CaptureHook_HookInfo21624
15:57:38.181: [game-capture: 'Game Capture'] capture stopped
```
```
15:58:25.171: [game-capture: 'Game Capture'] Activate hotkey pressed
15:58:25.181: is_app GetTokenInformation failed: 0x00000057
15:58:25.181: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:58:25.183: is_app GetTokenInformation failed: 0x00000057
15:58:25.183: [game-capture: 'Game Capture'] existing hook found, signaling process: Control_DX11.exe
15:58:25.183: [game-capture: 'Game Capture'] map id: CaptureHook_HookInfo21624
15:58:25.194: [game-capture: 'Game Capture'] hook stop signal received
15:58:25.194: [game-capture: 'Game Capture'] capture stopped
15:58:27.018: [game-capture: 'Game Capture'] Deactivate hotkey pressed
```

**Comment by Lucky-fish** [comment] 2021-11-25 15:49
It seems to be the issues on Intel graphic driver. Can also be reproduced on Windows 11 with intel graphic card and unable to capture Celeste after it started with admin permission (using UAC).

**Comment by Juesto** [comment] 2021-11-26 12:19
> It seems to be the issues on Intel graphic driver or something wrong on OBS (just guessing.). Can also be reproduced on Windows 11 with intel graphic card and unable to capture Celeste after it started with admin permission (using UAC). So could you tell me if you are using Intel graphic card?

no, this is on nvidia, turns out RivaTunerStatistcsServer is a conflict.

**Comment by RytoEX** [comment] 2021-11-26 16:03
> > It seems to be the issues on Intel graphic driver or something wrong on OBS (just guessing.). Can also be reproduced on Windows 11 with intel graphic card and unable to capture Celeste after it started with admin permission (using UAC). So could you tell me if you are using Intel graphic card?
> 
> no, this is on nvidia, turns out RivaTunerStatistcsServer is a potential conflict.

Correct.  Per our [Known Conflicts](https://obsproject.com/wiki/Known-Conflicts) list, RivaTuner or RTSS can interfere with Game Capture.  To enable compatibility with OBS in RivaTuner (RTSS, version 7.3.2 and above), enable "Use Microsoft Detours API hooking" in the app's Setup.

![unknown](https://user-images.githubusercontent.com/624931/143606873-2f18ff49-aac9-4b78-ba76-59efe7f387a4.png)

I'll be closing this issue now.

**Closed by RytoEX** 2021-11-26 16:03 UTC

**Comment by Juesto** [comment] 2021-11-28 23:38
What version introduces that?

**Comment by Juesto** [comment] 2021-11-28 23:38
what version introduces said setting? @RytoEX

**Comment by Juesto** [comment] 2021-11-28 23:39
Oddly enough, i have to do specific steps to make it work right with RTSS

**Comment by BLVCK-ANGEL** [comment] 2026-08-05 08:45
I enabled that Api Hooking But in OBS Game Capture not hooking the game
