### ISSUE TITLE
Can't record a sound after switching an audio output device.

### ISSUE THREAD

**Issue by hiljainen** [obsproject/obs-studio#3013] opened 2020-05-31 15:08 UTC
## Platform
Operating system and version: Microsoft Windows [Version 10.0.18362.356]
OBS Studio version: 25.0.8 64 (bit)

## Expected Behavior
I switch default Windows playback device while OBS running, and expect that OBS will switch automatically the audio output capture source.

## Current Behavior
Sound do not recording.

## Steps to Reproduce
1. Make sure you have few audio output devices connected.
2. Set "Default" in Audio Output Capture source and start recording.
3. Click Windows Speaker icon in system tray and switch the audio output device.
4. Stop recording.

Result: only first part of the record has a sound.

**Comment by notr1ch** [comment] 2020-05-31 15:11
Duplicate of https://github.com/obsproject/obs-studio/issues/2316

**Closed by notr1ch** 2020-05-31 15:11 UTC
