### ISSUE TITLE
OBS crashes when writing to V4L device 

### ISSUE THREAD

**Issue by jam3st** [obsproject/obs-studio#3117] opened 2020-07-02 01:40 UTC
## Platform
Operating system and version: Linux 5.7.7 SMP
OBS Studio version: 25.0.8

## Expected Behavior
when using file output for rawvideo, I should have v4l option available. FFmpeg  supports v4l output. When I have the v4l2loopback module loaded, I can write to this device using ffmpeg <rawvideo> <vcodec> v4l2 /dev/video0

## Current Behavior
Option is missing and /dev/video0 is filtered out. If I used the URL option I get a crash.

**Comment by kkartaltepe** [comment] 2020-07-02 15:35
Duplicate of #3031

**Closed by kkartaltepe** 2020-07-02 15:35 UTC
