### ISSUE TITLE
[BUG] Keyring dialog shows up when use obs on Debian bullseye with built-in browser source plugin

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#2706] opened 2020-04-13 13:28 UTC
## Platform Debian Bullseye 5.4.0-4-amd64 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux

Operating system and version:
OBS Studio version: 25.0.4 build from source

## Expected Behavior
 Normal usage browser source

## Current Behavior
When start obs with already added browser source plugin in any scene or you just add browser source plugin to scene (no added before browser source plugins to an any scene) shows keyring dialog lika in opera

## Steps to Reproduce

1.build and install obs-studio 25.0.4 from source with built-in browser source
2.launch obs-studio and add browser source plugin to a scene
3.Kering dialog shows up
4.Press cancel for keyring dialog and close obs-studio
5.Run obs again and keyring dialog shows up
6.Press cancel for keyring dialog and delete all browser source plugins from all scenes
7.launch obs-studio and add browser source plugin to a scene
8. Keyring dialog agaain shows up

## Additional information

After launching opera browser keyring dialog shows up. So for fix this issue with opera i use command for launch opera: "opera --password-store=basic %U" and there were no dialog

**Comment by WizardCM** [comment] 2021-01-19 12:38
Hi there, while I can't reproduce this myself, could you try launching OBS with `--use-mock-keychain` to see if the dialog disappears?

Note that this disables cookie encryption. https://bitbucket.org/chromiumembedded/cef/issues/2692/mac-networkservice-allow-custom-service

**Comment by morten71** [comment] 2022-02-17 11:13
I have always had this exact same issue, after I started using the browser plugin. For me the `--use-mock-keychain` parameter didn't fix the problem.

**Comment by gxalpha** [comment] 2022-09-22 22:18
Closing as this was a problem in Chromium that should should be fixed in the version we're using in OBS 28. Please report back should it still exist in OBS 28.

**Closed by gxalpha** 2022-09-22 22:18 UTC
Labels: Linux

**Comment by ksinas** [comment] 2023-01-31 12:14
I experience the same issue on version 29.0.0 ubuntu version 22.04.1

**Comment by BMaxV** [comment] 2024-06-10 08:03
I think I'm having the same issue. Version 30.1.2

**Comment by moothz** [comment] 2024-09-26 15:14
The problem still persists.

- Ubuntu 24.04.1 LTS
- OBS Studio - 30.2.3

Is there a way to pass `--use-mock-keychain` to the browser source (instead of OBS) to avoid this?
