### ISSUE TITLE
Autoconfiguration wizard behaves incorrectly with High DPI monitors (Windows)

### ISSUE THREAD

**Issue by atericparker** [obsproject/obs-studio#4758] opened 2021-05-25 20:36 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/ytyR84Aa2Mto6c1r

### Expected Behavior

The autoconfiguration wizard should detect the monitor's resolution (3840x2160)

### Current Behavior

<img width="798" alt="obs auto config wizard" src="https://user-images.githubusercontent.com/47646072/119564224-650ea980-bd5d-11eb-88f7-1370685ac9a8.png">
<img width="361" alt="monitor resolution" src="https://user-images.githubusercontent.com/47646072/119564364-8ff8fd80-bd5d-11eb-90d0-3ba261db7d10.png">
The auto configuration wizard is detecting the scaled resolution, not the actual resolution. This is undesirable, because if you enable capture, it captures the actual resolution, requiring either scaling, or capturing only a portion.

### Steps to Reproduce

1. Enable monitor scaling in Windows 10 (set to 150% in my case)
2. Open OBS for the first time or manually select the autoconfiguration wizard.

**Comment by notr1ch** [comment] 2021-05-25 21:47
Duplicate of https://github.com/obsproject/obs-studio/issues/4298

**Closed by notr1ch** 2021-05-25 21:47 UTC
