### ISSUE TITLE
[BUG] wacked out colours, NV12 acting as I420

### ISSUE THREAD

**Issue by psyborg55** [obsproject/obs-studio#2860] opened 2020-05-03 17:35 UTC
FX9830P with RX560 GPU, latest adrenaline driver 20.4.1

## Platform
Win7 x64 latest OBS, downloaded May 2 2020.

## Expected Behavior
Record average quality video of display capture.

## Current Behavior
Recording ends up with messed colours and dialogs of other windows shown randomly on screen.

## Steps to Reproduce
Set the NV12 format since it is the only one working on win7 atm with hw encoder. Start recording. Play the recorded file and witness its completely messed up.

When comparing the application behaviour to the one installed on Win10 it appears, that the actual format used when NV12 selected is I420, as I've been able to reproduce the same lousy quality recording on win10 when using I420 format

**Comment by Fenrirthviti** [comment] 2020-05-03 17:39
Please provide a screenshot showing the difference and a log file. There is not enough information in this report to be actionable.

**Comment by energizerfellow** [comment] 2020-05-03 17:46
Can you also post a text file export of the video file's metadata using Mediainfo?  As mentioned, we also need screenshots of the color issues in question. Information on what player(s) you're using and their respective version(s) would be helpful as well.

**Comment by psyborg55** [comment] 2020-05-03 17:51
couldn't find logs in installation folder or related setting in program settings. using MPC-HC 1.7
here's screenshot:
![obs](https://user-images.githubusercontent.com/15853469/80921588-7f06d400-8d77-11ea-9e5e-d5e42f0f995e.png)

**Comment by energizerfellow** [comment] 2020-05-03 19:27
You can find the OBS logs here, which will also convey the relevant encoder settings:
%APPDATA%\obs-studio\logs

Make sure the log includes both the start and completion of the recording attempts.

Do you have the complete metadata from the video?  The text export from Mediainfo is what I'm looking for, or the complete text from Properties -> Mediainfo in MPC-HC, which is the same thing.

Do you have sample videos uploaded anywhere?

**Comment by psyborg55** [comment] 2020-05-03 23:11
heres the log 
[2020-05-03 22-56-45.txt](https://github.com/obsproject/obs-studio/files/4572231/2020-05-03.22-56-45.txt)
```

Video
ID                             : 256 (0x100)
Menu ID                        : 1 (0x1)
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.2
Format settings, CABAC         : Yes
Format settings, RefFrames     : 4 frames
Format settings, GOP           : M=1, N=60
Codec ID                       : 27
Duration                       : 18 s 450 ms
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate                     : 60.000 FPS
Standard                       : Component
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Color range                    : Limited

Audio
ID                             : 257 (0x101)
Menu ID                        : 1 (0x1)
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format version                 : Version 4
Format profile                 : LC
Muxing mode                    : ADTS
Codec ID                       : 15
Duration                       : 18 s 436 ms
Bit rate mode                  : Variable
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 44.1 kHz
Frame rate                     : 43.066 FPS (1024 SPF)
Compression mode               : Lossy

Menu
ID                             : 4096 (0x1000)
Menu ID                        : 1 (0x1)
Duration                       : 18 s 400 ms
List                           : 256 (0x100) (AVC) / 257 (0x101) (AAC)
Service name                   : Service01
Service provider               : FFmpeg
Service type                   : digital television
```
sample video:
[2020-05-03 22-56-55.zip](https://github.com/obsproject/obs-studio/files/4572232/2020-05-03.22-56-55.zip)

**Comment by Xaymar** [comment] 2020-05-06 10:51
#### Info for Developers picking this up:
There was a problem with D3D11 on Windows 7 that happens with the AMD AMF SDK, though I don't remember exactly what it was - it might have been a crash, or bluescreens, but whatever it was, it was important to fix _now_. [The plugin therefore includes a check if it's windows 8 or later](https://github.com/obsproject/obs-amd-encoder/blob/master/source/api-base.cpp#L104-L122), and if it's not on Windows 8 or newer it falls back to D3D9.

The problem here seems to be that [`video_out_get_info` returns NV12](https://github.com/obsproject/obs-amd-encoder/blob/master/source/enc-h264.cpp#L1277-L1319), but what's actually given is a mess of planes. The last time I've seen this happen OBS was falling back to OpenGL, and I still don't understand what causes it.

**Comment by RytoEX** [comment] 2022-09-22 20:55
As this seems to be Windows 7 specific, and we no longer support Windows 7 as of OBS Studio 28, we're going to close this. If this is reproducible in OBS Studio 28.0.2 or newer on Windows 10, then please comment with an OBS log, and details on steps to reproduce, and we can consider reopening this.

**Closed by RytoEX** 2022-09-22 20:55 UTC
