### ISSUE TITLE
The window border of OBS v28 doesn't follow the system's color theme

### ISSUE THREAD

**Issue by kreaninw** [obsproject/obs-studio#7263] opened 2022-09-02 04:28 UTC
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JFmJCqvyKNuZ0qRV

### Expected Behavior

The window border should follow the system's color scheme.

### Current Behavior

The window border doesn't follow the system's color scheme, as shown in the screenshot below:

![Screenshot from 2022-09-02 00-19-34](https://user-images.githubusercontent.com/1403194/188058916-57c1b1a2-3f41-4c06-8233-21d2c74c87cc.png)

OBS v27 doesn't have this issue.

### Steps to Reproduce

1. Open the app.
2. Change your system's color scheme.
3. See the window border, it won't change with the system's color scheme.
...

### Anything else we should know?

I use the [Flatpak](https://flathub.org/apps/details/com.obsproject.Studio) version.

**Comment by EldritchEevee** [comment] 2022-09-02 04:34
Reproducible on Windows 11.

**Comment by feetstv** [comment] 2022-09-02 04:41
> Reproducible on Windows 11.

This isn't a bug on Windows 11. You set your own titlebar colour settings for all apps in the Settings app; if one isn't set, it's white for light mode and black for dark mode.

**Comment by tytan652** [comment] 2022-09-02 05:27
Not a bug, I see that your are under Wayland and use the Flatpak, you have surely a whole bunch of Flatpak package meant to add Adwaita KStyle and QGnomePlatform which is the cause of your issue.

Because Qt provide normally under Wayland a headerbar that match the color of OBS theme.

**Comment by kreaninw** [comment] 2022-09-02 06:50
@tytan652 

I don't know in details. I updated OBS today, then this issue happens. 

Before the update, I have always used OBS 27 from Flatpak also, and never had this issue.

**Comment by tytan652** [comment] 2022-09-02 07:27
To fix themes on OBS we had to do this #6664 which maybe mess QGnomePlatform.
I think we can add a workaround for Wayland, to use Qt default decoration.

**Comment by tytan652** [comment] 2022-09-02 07:36
I"m not a heavy Wayland user (NVIDIA GPU), I recommend you to report the issue to https://github.com/FedoraQt/QGnomePlatform

You can specify to them that we have this PR merged https://github.com/obsproject/obs-studio/pull/6664 that may trigger the bug and we are not going to revert this since we don't want other style to overlap OBS themes.

**Comment by gxalpha** [comment] 2022-09-02 10:40
Closing per the above [comment](https://github.com/obsproject/obs-studio/issues/7263#issuecomment-1235163946)

**Closed by gxalpha** 2022-09-02 10:40 UTC
