### ISSUE TITLE
"Stopping recording" when recording while Replay Buffer is on

### ISSUE THREAD

**Issue by TarekSalama** [obsproject/obs-studio#8362] opened 2023-02-27 18:45 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/lW5MIzsjTmGOjGds

### Expected Behavior

Be be able to record while Replay Buffer is on

### Current Behavior

OBS is stuck on "Stopping recording" only if Replay Buffer is on

### Steps to Reproduce

1. Turn on Replay Buffer
2. Start recording
3. Stop recording
4. Recording won't save and will get stuck on "Stopping recording"

### Anything else we should know?

This issue has been ongoing with me probably since the last Windows 11 update. I am unsure if this is true or not and I haven't tried un-upgrading.

What I have tried doing so far:
- Updating OBS
- Updating my GPU's driver
- Reinstalling OBS fully after uninstalling and removing all settings
- AMD Adrenaline records fine (clipping + recording)
- I can currently use AMD Adrenaline for recording + OBS for clipping (Replay Buffer) however it's a bummer since OBS is superior in terms of configuring the quality vs file size, file names, HDR mode and OpenGL games when recording full desktop.
- I have also noticed that if when saving recording gets stuck on "Stopping recording", it's also impossible to turn off the Replay Buffer. I would have to kill OBS' task.

**Comment by Fenrirthviti** [comment] 2023-02-27 19:50
In order to investigate further, we probably will need a memory dump of the OBS process while the encoder is hung up like that. Please follow the directions here:

https://obsproject.com/forum/resources/598/

And contact me on our Discord (Fenrir in the userlist, Len#9999) or forums (Fenrir as well) to send the dump so we can take a look. Be careful posting somewhere public, as dump files will contain everything about OBS' process, including potentially sensitive information like stream keys and such.

**Comment by RytoEX** [comment] 2023-02-27 20:15
There is a 5 hour gap between when you start Replay Buffer and when you attempt to Start Recording. Just to confirm, were you actively capturing content the whole time? Did your PC go to sleep or hibernate?

**Comment by TarekSalama** [comment] 2023-02-27 20:45
> In order to investigate further, we probably will need a memory dump of the OBS process while the encoder is hung up like that. Please follow the directions here:
> 
> https://obsproject.com/forum/resources/598/
> 
> And contact me on our Discord (Fenrir in the userlist, Len#9999) or forums (Fenrir as well) to send the dump so we can take a look. Be careful posting somewhere public, as dump files will contain everything about OBS' process, including potentially sensitive information like stream keys and such.

I have sent it over on the forum to you.

**Comment by PatTheMav** [comment] 2023-03-02 03:40
This does sound like a duplicate for a known issue when replay buffer and recordings are both active - both activities deadlock each other, as the thread that signals an end of recording is never spawned because the replay output is active.

**Comment by kallestrop** [comment] 2023-03-11 15:52
I can reproduce this issue on both Windows 10 and Arch Linux with the latest OBS 29.0.2 (on Linux i use obs-studio-amf 29.0.2-2 from AUR repository)

What i figured out is, that this problem only occur when using `AMD HW H.264 (AVC)` or `AMD HW H.265 (HEVC)` encoders.

When using `x264` software encoder, there is no problem using both recording and replay buffer at the same time.

**Comment by gxalpha** [comment] 2023-04-13 21:43
@TarekSalama we made some changes in 29.1 that we think might fix this issue, could you test whether this still happens on the current beta of OBS 29.1?

**Comment by TarekSalama** [comment] 2023-04-13 23:45
Yea it's working well now. Thanks!

**Comment by TarekSalama** [comment] 2023-04-13 23:46
Will the beta notify me of an update once the main app has been updated too?

**Comment by gxalpha** [comment] 2023-04-14 00:31
> Yea it's working well now. Thanks!

Thank you for testing. I will close this issue as fixed then.

> Will the beta app notify me of an update once the main app has been updated too?

Yes, it should. You can decide whether you want only main version updates (stable branch) or both beta and main updates (beta branch) in the settings.

**Closed by gxalpha** 2023-04-14 00:31 UTC
