### ISSUE TITLE
Duplicating a profile wipes it's local storage / cookies / etc.

### ISSUE THREAD

**Issue by Lordmau5** [obsproject/obs-studio#9040] opened 2023-06-07 16:08 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ritmAH18y1g27iIe

### Expected Behavior

- Setup Twitch on your profile (by logging in, not by using the stream key option)
- Duplicate the profile
- Have both profiles be logged in (and also settings preserved from BTTV and FFZ)

### Current Behavior

- Setup Twitch on your profile (by logging in, not by using the stream key option)
- Duplicate the profile
- The new / duplicated profile will have all the local storage / login data, but **the original** one has it wiped / is logged out

### Steps to Reproduce

1. Authenticate with Twitch inside OBS
2. Duplicate the profile
3. Notice the original profile is now logged out and has it's local storage wiped

### Anything else we should know?

I am running OBS in a portable instance, not sure if that might contribute to this issue

**Comment by RytoEX** [comment] 2023-06-07 17:19
Duplicate of #7140

**Comment by RytoEX** [comment] 2023-06-07 17:20
Possibly duplicate of #4020 , but it's unclear in that one if there are two different problems being described.

**Closed by RytoEX** 2023-06-07 17:19 UTC

**Comment by Lordmau5** [comment] 2023-06-07 20:21
Well I still *have* the docks available, same for Twitch itself still being logged in.

It's the info inside the dock (in this case chat) being lost in the original profile, so I don't think it's a 1:1 of the 2 issues mentioned
