### ISSUE TITLE
OBS Still removes the built in camera

### ISSUE THREAD

**Issue by m4d0x** [obsproject/obs-studio#9833] opened 2023-11-09 17:11 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

None

### Expected Behavior

Not to overwrite the default camera.

### Current Behavior

Camera got completely removed from the laptop like a month ago, and i can clearly see within Google its gone to use OBS as its default, i cant find the camera within the computer at all, nor get the drivers for it from MSI making meets nearly impossible to attend at.
The computer thinks OBS is the default camera to be used somehow, i've seen an earlier issue about this tho only concerning MAC users, this is Win 11 and kinda frustrating when never being able to put it on during company meetings.

The earlier issue was archived but couldnt tell if anything of the "delete/re-install" was a suitable fix at all to get the default cam back with the drivers cuz they are non-existing as off now.

### Steps to Reproduce

1. By installing OBS, then use it for a year
2.
3.
...

### Anything else we should know?

Its an MSI Vector GP68HX 12VX, Windows 11, i have not even touched the camera settings cuz theres never been need to.

**Comment by Fenrirthviti** [comment] 2023-11-09 17:19
What application are you testing in? Are you checking the list of available webcams in a piece of software that will allow selection if there are multiple? You can try running the uninstall script (must be run as administrator) which is located (assuming default install location) at:

`C:\Program Files\obs-studio\data\obs-plugins\win-dshow\virtualcam-uninstall.bat`

Please let me know if this helps. We don't have any control over what other applications select as a "default" camera, and often they will just pick the most recently "connected". Windows doesn't have a concept of a default video device, it's per application. You can also try a website like https://webcamtests.com/ to verify if the built-in camera is still available as an option.

**Comment by RytoEX** [comment] 2023-11-09 17:42
Duplicate of #3555 ?

**Closed** 2023-11-09 18:24 UTC
