### ISSUE TITLE
Chromakey not functioning correctly

### ISSUE THREAD

**Issue by Cronoburn** [obsproject/obs-studio#4606] opened 2021-04-27 14:02 UTC
### Operating System Info

Other

### Other OS

Garuda Linux (Arch)

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://pastebin.com/MVHV3vX0

### Expected Behavior

I expect that the chromakey will create an transparent pixels anywhere there is green... 

### Current Behavior

It "sorta" works, however, there is no transparency, it looks as if there was an overlay on top of my background. This was working two days ago as expected. 

### Steps to Reproduce

1.simply apply a chroma key filter
2.
3.
...

### Anything else we should know?

There was an update after this started but it did not fix the issue. Please, I run this software for my business and I'm going to have to do some serious re-tooling, and a session that should only take like 30 minutes could end up taking HOURS if not fixed soon.

**Comment by Xaymar** [comment] 2021-04-27 15:02
I recommend not using Beta/RCs in production. I think this bug should be fixed already, however with the given steps and no before/after images or a test video, it will be difficult to reproduce this behavior if it is not an obvious change.

**Comment by Cronoburn** [comment] 2021-04-27 15:17
*sigh* ok, I installed this using a package manager, I appreciate the reply.. Thank you.

**Comment by Cronoburn** [comment] 2021-04-27 15:26
Just as a follow-up, I don't actually use the live chroma-key in production, I use it to monitor (if the live chroma-key in obs works, then I know that my post-edit chroma-key will function well.) Seems redundant, but it helps me know that the lighting is correct and I won't end up with nasty surprises in the final video. Thanks again for the prompt reply and thanks for an amazing piece of software.

**Comment by Xaymar** [comment] 2021-04-27 15:27
You didn't have to close this, that was not my intention. I'm sure it is intended to be fixed, but it's not likely to reproduce the issue when there's so much information missing. Most likely an example video to test the chroma key on is needed, as everyone's green/red/blue/teal/... screen is differently lit. I personally wasn't able to reproduce it with my green screen (which measures at R11 G235 B42 after cameras mess with it).

**Comment by Cronoburn** [comment] 2021-04-27 15:35
For all I know, it could have been a change in IriunCam, v4l2loopback, or even my OpenGl drivers. and what are the numbers you called out? This is a piece of the puzzle I'm unaware of: "R11 G235 B42" Just color values? I am relatively new to this. I do realestate virtual tours and occasionally do video of the real estate agent narrating the tour. I found OBS and fell in love with it. As for opening the issue, I just wanted someone aware of it. I will see if I can get an image with and without the filter applied.

**Comment by Xaymar** [comment] 2021-04-27 15:48
> and what are the numbers you called out? This is a piece of the puzzle I'm unaware of: "R11 G235 B42" Just color values?

Yes they are color values. My green screen isn't green once the camera recording it is done with messing with reality. Which is why in Release Candidate 1 the greenscreen is broken, but Release Candidate 2 has it working fine again.

**Comment by RytoEX** [comment] 2021-04-27 15:49
As said above, OBS Studio 27.0.0-rc2 is effectively beta software.  If you need stability, use a stable release like OBS Studio 26.1.1.

For what it's worth, the chroma matching should be identical to 26 in RC2. Please provide a sample image, a desired/expected output result image (e.g., from OBS Studio 26.1.1), the undesired/actual result from OBS Studio 27.0.0-rc2 (or a build from the current git tree), and your chroma key filter settings.  I'll reopen this for now.

**Comment by Cronoburn** [comment] 2021-04-27 15:54
![test-02](https://user-images.githubusercontent.com/2997671/116272820-bdf41d80-a770-11eb-81ff-54df3bdd1540.jpeg)
![test](https://user-images.githubusercontent.com/2997671/116272822-be8cb400-a770-11eb-9390-9ac5cfbd58e8.jpeg)
I don't have anything producing the desired output at the moment

**Comment by Xaymar** [comment] 2021-04-27 16:02
Yeah that looks broken.

**Comment by Cronoburn** [comment] 2021-04-27 16:05
I know my screen isn't setup perfect, but it usually functions better than this.. lol

**Comment by Cronoburn** [comment] 2021-04-27 16:08
I'm wondering if its not a problem with the package maintainers for Garuda Linux, it's set at version 27rc2.. Maybe a typo or a glitch on their end?

**Comment by RytoEX** [comment] 2021-04-27 16:21
The default settings for chroma key mostly worked for me out of the box in 270.0.0-rc2 (actual RC2 with no commits after it).  I placed a color source behind the test image.

![image](https://user-images.githubusercontent.com/624931/116274113-5cbc5200-a750-11eb-9675-d33c27cb27b0.png)

Adjusting the similarity to about 440 produces decent results.

![image](https://user-images.githubusercontent.com/624931/116274870-0c91bf80-a751-11eb-86f0-d521a339d715.png)

However, with the current git build, I get this with a chroma key filter with default settings:

![image](https://user-images.githubusercontent.com/624931/116276702-c178ac00-a752-11eb-8f34-66e8ecc86c17.png)

I've pinged the developer most familiar with the chroma key changes for OBS Studio 27.

**Comment by Xaymar** [comment] 2021-04-27 16:24
- 26.1.1: Working
- 27.0.0-rc1: Broken, huge streaks of green everywhere.
- 27.0.0-rc2: Same as 26.1.1 again.
- 27.0.0-rc2-52-gc497342fd: Everything matched turns grey, and there's a weird spot of green where there was nothing before.

**Comment by Cronoburn** [comment] 2021-04-27 16:27
ok, I finally got the version string (if it helps)
OBS Studio - 27.0.0.rc2.r51.g387a2c5f3 (linux)

**Comment by Xaymar** [comment] 2021-04-27 16:29
It appears that the maintainer of your distribution in the package manager of your choice doesn't follow the same release schedule as OBS does and always uploads the latest version from `master`. I'm not sure if that's the recommended way to enjoy OBS, but it did reveal an issue that may have gone under the radar.

**Closed** 2021-04-29 01:09 UTC
Labels: Confirmed
