### ISSUE TITLE
[Linux] OBS hogs memory when streaming/recording

### ISSUE THREAD

**Issue by GabMus** [obsproject/obs-studio#2202] opened 2019-11-26 18:27 UTC
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

## Expected Behavior

Memory usage should be normal

## Current Behavior

After 2 to 9 minutes of streaming/recording obs starts eating more and more memory.

My PC has 16 GB and it eats them all, to the point that my system starts swapping and eventually it freezes completely.

## Steps to Reproduce

1. Install OBS 24.0.3-2 (tested on Arch Linux) either from Arch's repos or from flatpak
2. Set up a couple of simple scenes with webcam and screen recording (not sure if it happens with an empty scene alone)
3. Start recording for 2 to 10 minutes
4. Watch your system hang

## Additional information

Using the x264 encoder, fast setting, 4000kbps, main profile

The same problem **does not** happen on [this appimage of an older version](https://github.com/probonopd/obs-studio/releases/continuous) by probonopd. This leads me to believe that it's a new bug related to one of the versions in between.

A little note: having Appimage versions would make troubleshooting these kind of issues easier. I was lucky enough to find this build and confirm my suspects, but having official ones, and older builds available to download would be a huge advantage.

**Comment by Fenrirthviti** [comment] 2019-11-26 18:30
As we do not maintain any packages other than the official Ubuntu package, can you please build from master and see if the same issue occurs?

**Comment by GabMus** [comment] 2019-11-26 19:06
Just tested, the same problem happens with a fresh build from master ([following this section of the wiki](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#linux-portable-mode-all-distros))

**Comment by kkartaltepe** [comment] 2019-11-26 20:11
Provide a log from when the issue occurred.

I cannot replicate it with master on arch linux. After 9 minutes with multiple scens including one with a v4l2 source memory had not appreciably changed.

If you can find a version where your issue did not appear and you can replicate the issue please locate the bad commit with a git bisect. This looks like a decent guide on how to use it http://webchick.net/node/99 if you are new to git.

**Comment by GabMus** [comment] 2019-11-26 20:48
@kkartaltepe thanks, will do tomorrow. Can you provide your specs? I just had the wild idea that maybe my 5700 XT and/or mesa-git drivers might be the culprit

**Comment by RytoEX** [comment] 2019-11-26 20:51
There is an open MESA bug about a memory leak, though that specifically mentioned not needing to start a stream or recording.
https://obsproject.com/mantis/view.php?id=1452

**Comment by GabMus** [comment] 2019-11-26 20:53
That also wouldn't explain why older versions don't cause any problems, and how is it really related considering I use the CPU encoder?

**Comment by GabMus** [comment] 2019-11-26 21:51
Spot on, the bug you linked is exactly what I'm experiencing. So to summarize:

- Bug is *possibly* in mesa and not in OBS
- [Original bug](https://obsproject.com/mantis/view.php?id=1452) (makes this a duplicate)
- [Related mesa bug](https://gitlab.freedesktop.org/mesa/mesa/issues/1426)

**Comment by yesuu** [comment] 2020-01-26 03:39
> Spot on, the bug you linked is exactly what I'm experiencing. So to summarize:
> 
> * Bug is _possibly_ in mesa and not in OBS
> * [Original bug](https://obsproject.com/mantis/view.php?id=1452) (makes this a duplicate)
> * [Related mesa bug](https://gitlab.freedesktop.org/mesa/mesa/issues/1426)

The mesa bug fixes have been merged into the master. After I use the master mesa, there is no memory leak. Forgot to say, I can reproduce the memory leak problem before.

**Comment by Fenrirthviti** [comment] 2020-04-02 17:15
This has been fixed upstream.

**Closed by Fenrirthviti** 2020-04-02 17:15 UTC
Labels: Dependency Issue, Fix available, Mantis Duplicate
