### ISSUE TITLE
Hang on close when UVC device control panel is open

### ISSUE THREAD

**Issue by lt-royal-shrimp** [obsproject/obs-studio#4362] opened 2021-03-17 23:17 UTC
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: OBS Studio 26.1.1
OBS Log file: https://obsproject.com/logs/GxXMvGScbv7LZ-rI

## Expected Behavior

When closing OBS Studio, and the UVC control panel is open, the control panel closes and OBS Studio closes. 

## Current Behavior

When closing OBS Studio with the UVC control panel open, OBS Studio will hang and task manager says the program has stopped responding. 

## Steps to Reproduce

[Video of bug](https://i.imgur.com/d4mrNxP.mp4)

Steps to reproduce
1. Add a UVC device to OBS Studio
2. Open the properties
3. Click on 'Configure' 
4. Keep the UVC panel open and close the properties page
5. Now close OBS Studio

## Additional information

Should happen with any UVC device

**Comment by Fenrirthviti** [comment] 2021-03-17 23:32
Appears to be a duplicate of https://github.com/obsproject/obs-studio/issues/3977

**Comment by WizardCM** [comment] 2021-03-20 02:24
Duplicate of #3977

**Closed by WizardCM** 2021-03-20 02:24 UTC
Labels: Confirmed, Windows
