### ISSUE TITLE
[Wayland] Crash when refocusing workspace during 1+ hour stream

### ISSUE THREAD

**Issue by Geo25rey** [obsproject/obs-studio#4295] opened 2021-03-03 04:02 UTC
## Platform

Operating system and version:
```shell
uname -a
Linux hostname 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux
```
Qt version:
5.15.2

OBS Studio version:
```shell
obs --version
OBS Studio - 26.1.2.r203.g7f27963ca (linux)
```
OBS Log file: No log file saved

<details> 
  <summary>OBS Coredump:</summary>

                Stack trace of thread 833879:
                #0  0x00007f37fdc8eef5 raise (libc.so.6 + 0x3cef5)
                #1  0x00007f37fdc78862 abort (libc.so.6 + 0x26862)
                #2  0x00007f37fe20e9ac _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x909ac)
                #3  0x00007f37c1dc60fa n/a (libQt5WaylandClient.so.5 + 0x620fa)
                #4  0x00007f37c1dd5465 _ZN15QtWaylandClient15QWaylandDisplay13flushRequestsEv (libQt5WaylandClient.so.5 + 0x71465)
                #5  0x00007f37fe46adc0 n/a (libQt5Core.so.5 + 0x2ecdc0)
                #6  0x00007f37fe48c6ce _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30e6ce)
                #7  0x00007f37fe4323ac _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b43ac)
                #8  0x00007f37fe43a844 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2bc844)
                #9  0x000055829df91a47 main (obs + 0x79a47)
                #10 0x00007f37fdc79b25 __libc_start_main (libc.so.6 + 0x27b25)
                #11 0x000055829df92e2e n/a (obs + 0x7ae2e)

                Stack trace of thread 833923:
                #0  0x00007f37fdd4ba9d syscall (libc.so.6 + 0xf9a9d)
                #1  0x00007f37572d87db n/a (libjack.so.0 + 0x317db)
                #2  0x00007f37572bafa5 n/a (libjack.so.0 + 0x13fa5)
                #3  0x00007f37572ba177 n/a (libjack.so.0 + 0x13177)
                #4  0x00007f37572b9ef8 n/a (libjack.so.0 + 0x12ef8)
                #5  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #6  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #7  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833925:
                #0  0x00007f37fdd4ba9d syscall (libc.so.6 + 0xf9a9d)
                #1  0x00007f37572d87db n/a (libjack.so.0 + 0x317db)
                #2  0x00007f37572bafa5 n/a (libjack.so.0 + 0x13fa5)
                #3  0x00007f37572ba177 n/a (libjack.so.0 + 0x13177)
                #4  0x00007f37572b9ef8 n/a (libjack.so.0 + 0x12ef8)
                #5  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #6  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #7  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833891:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833931:
                #0  0x00007f37fdd4ba9d syscall (libc.so.6 + 0xf9a9d)
                #1  0x00007f37572d87db n/a (libjack.so.0 + 0x317db)
                #2  0x00007f37572bafa5 n/a (libjack.so.0 + 0x13fa5)
                #3  0x00007f37572ba177 n/a (libjack.so.0 + 0x13177)
                #4  0x00007f37572b9ef8 n/a (libjack.so.0 + 0x12ef8)
                #5  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #6  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #7  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833903:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde30b98 __new_sem_wait_slow64.constprop.0 (libpthread.so.0 + 0x11b98)
                #2  0x00007f37fedeb41a n/a (libobs.so.0 + 0x4a41a)
                #3  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #4  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833888:
                #0  0x00007f37fdd4637f __poll (libc.so.6 + 0xf437f)
                #1  0x00007f37fccc4baf n/a (libglib-2.0.so.0 + 0xa7baf)
                #2  0x00007f37fcc6f3b1 g_main_context_iteration (libglib-2.0.so.0 + 0x523b1)
                #3  0x00007f37fe48c691 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30e691)
                #4  0x00007f37fe4323ac _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b43ac)
                #5  0x00007f37fe24ad12 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccd12)
                #6  0x00007f37c1cf5098 n/a (libQt5DBus.so.5 + 0x17098)
                #7  0x00007f37fe24beff n/a (libQt5Core.so.5 + 0xcdeff)
                #8  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #9  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833886:
                #0  0x00007f37fdd5139e epoll_wait (libc.so.6 + 0xff39e)
                #1  0x00007f373532e0bc _ZN4asio6detail13epoll_reactor3runElRNS0_8op_queueINS0_19scheduler_operationEEE (obs-websocket.so + 0x820bc)
                #2  0x00007f373532e708 _ZN4asio6detail9scheduler10do_run_oneERNS0_27conditionally_enabled_mutex11scoped_lockERNS0_21scheduler_thread_infoERKSt10error_code (obs-websocket.so + 0x82708)
                #3  0x00007f373530efe2 n/a (obs-websocket.so + 0x62fe2)
                #4  0x00007f373530f27c n/a (obs-websocket.so + 0x6327c)
                #5  0x00007f3735312ac6 _ZThn16_N12QtConcurrent15RunFunctionTaskIvE3runEv (obs-websocket.so + 0x66ac6)
                #6  0x00007f37fe24f2f2 n/a (libQt5Core.so.5 + 0xd12f2)
                #7  0x00007f37fe24beff n/a (libQt5Core.so.5 + 0xcdeff)
                #8  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #9  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833880:
                #0  0x00007f37fdd4637f __poll (libc.so.6 + 0xf437f)
                #1  0x00007f37fccc4baf n/a (libglib-2.0.so.0 + 0xa7baf)
                #2  0x00007f37fcc6f3b1 g_main_context_iteration (libglib-2.0.so.0 + 0x523b1)
                #3  0x00007f37fcc6f402 n/a (libglib-2.0.so.0 + 0x52402)
                #4  0x00007f37fcc9dfc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833881:
                #0  0x00007f37fdd4637f __poll (libc.so.6 + 0xf437f)
                #1  0x00007f37fccc4baf n/a (libglib-2.0.so.0 + 0xa7baf)
                #2  0x00007f37fcc700d3 g_main_loop_run (libglib-2.0.so.0 + 0x530d3)
                #3  0x00007f37c76c5d18 n/a (libgio-2.0.so.0 + 0x101d18)
                #4  0x00007f37fcc9dfc1 n/a (libglib-2.0.so.0 + 0x80fc1)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833904:
                #0  0x00007f37fdd4637f __poll (libc.so.6 + 0xf437f)
                #1  0x00007f3800f12f46 wl_display_dispatch_queue (libwayland-client.so.0 + 0x7f46)
                #2  0x00007f3800f131e0 wl_display_roundtrip_queue (libwayland-client.so.0 + 0x81e0)
                #3  0x00007f3734125399 n/a (wlrobs.so + 0x8399)
                #4  0x00007f37fee0ce99 obs_source_default_render (libobs.so.0 + 0x6be99)
                #5  0x00007f37fee11b5c obs_source_video_render (libobs.so.0 + 0x70b5c)
                #6  0x00007f37fee47fba n/a (libobs.so.0 + 0xa6fba)
                #7  0x00007f37fee11a20 obs_source_video_render (libobs.so.0 + 0x70a20)
                #8  0x00007f37fee18936 obs_transition_video_render (libobs.so.0 + 0x77936)
                #9  0x00007f37fee11a20 obs_source_video_render (libobs.so.0 + 0x70a20)
                #10 0x00007f37fee44ab5 obs_view_render (libobs.so.0 + 0xa3ab5)
                #11 0x00007f37fee4d50c obs_graphics_thread_loop (libobs.so.0 + 0xac50c)
                #12 0x00007f37fee4e939 obs_graphics_thread (libobs.so.0 + 0xad939)
                #13 0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #14 0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833887:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                #2  0x00007f37fedffa59 os_event_timedwait (libobs.so.0 + 0x5ea59)
                #3  0x00007f37fee355d5 obs_hotkey_thread (libobs.so.0 + 0x945d5)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833892:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833893:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833895:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833897:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833898:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833896:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833905:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde30b98 __new_sem_wait_slow64.constprop.0 (libpthread.so.0 + 0x11b98)
                #2  0x00007f37c031c225 n/a (libobs-scripting.so + 0x6225)
                #3  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #4  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833900:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833902:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833899:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833894:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f379ed1ecec n/a (radeonsi_dri.so + 0x4edcec)
                #3  0x00007f379ed1d4c8 n/a (radeonsi_dri.so + 0x4ec4c8)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833924:
                #0  0x00007f37fde3187c read (libpthread.so.0 + 0x1287c)
                #1  0x00007f37572d7b2f n/a (libjack.so.0 + 0x30b2f)
                #2  0x00007f37572dc73d n/a (libjack.so.0 + 0x3573d)
                #3  0x00007f37572dc572 n/a (libjack.so.0 + 0x35572)
                #4  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833921:
                #0  0x00007f37fde349ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                #1  0x00007f37fde2e260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                #2  0x00007f37572d73c0 n/a (libjack.so.0 + 0x303c0)
                #3  0x00007f37572cb456 n/a (libjack.so.0 + 0x24456)
                #4  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833901:
                #0  0x00007f37fdd19125 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc7125)
                #1  0x00007f37fdd1e357 __nanosleep (libc.so.6 + 0xcc357)
                #2  0x00007f37fdd49379 usleep (libc.so.6 + 0xf7379)
                #3  0x00007f37fedec78a n/a (libobs.so.0 + 0x4b78a)
                #4  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #5  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833922:
                #0  0x00007f37fde3187c read (libpthread.so.0 + 0x1287c)
                #1  0x00007f37572d7b2f n/a (libjack.so.0 + 0x30b2f)
                #2  0x00007f37572dc73d n/a (libjack.so.0 + 0x3573d)
                #3  0x00007f37572dc572 n/a (libjack.so.0 + 0x35572)
                #4  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833928:
                #0  0x00007f37fde3187c read (libpthread.so.0 + 0x1287c)
                #1  0x00007f37572d7b2f n/a (libjack.so.0 + 0x30b2f)
                #2  0x00007f37572dc73d n/a (libjack.so.0 + 0x3573d)
                #3  0x00007f37572dc572 n/a (libjack.so.0 + 0x35572)
                #4  0x00007f37572d68ed n/a (libjack.so.0 + 0x2f8ed)
                #5  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #6  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)

                Stack trace of thread 833920:
                #0  0x00007f37fdd48ad1 __select (libc.so.6 + 0xf6ad1)
                #1  0x00007f376405e45f n/a (linux-v4l2.so + 0x545f)
                #2  0x00007f37fde28299 start_thread (libpthread.so.0 + 0x9299)
                #3  0x00007f37fdd51053 __clone (libc.so.6 + 0xff053)
</details>

## Expected Behavior

OBS to not crash for seemingly no reason.

## Current Behavior

OBS crashes on 1+ hour streams when switching workspaces in swaywm.

## Steps to Reproduce

0. In Sway window manager, open OBS.
1. Using wlrobs, add a wayland screen capture source (scpy).
2. Start streaming for 1+ hours.
3. Switch Sway workspace to a workspace not containing OBS.
4. After 1+ hours, switch back to the workspace containing OBS, and notice as soon as the workspace switch happens the OBS crashes with no log.

**Comment by Geo25rey** [comment] 2021-03-03 04:05
@GeorgesStavracas Any ideas why this might be happenning?

**Comment by Fenrirthviti** [comment] 2021-03-03 04:06
Is this from the flatpak version? If so, support for the flatpak can be found here: https://github.com/flathub/com.obsproject.Studio/issues

**Comment by tkjenll** [comment] 2021-03-03 04:12
ons 3 mars 2021 kl. 05:07 skrev Joel Bethke <notifications@github.com>:

**Comment by kkartaltepe** [comment] 2021-03-03 04:33
I think this is the qt bug where it fails to process wayland messages and crashes once the window is activated again due to the excess of messages? Im not sure ive seen the stacks that were mentioned when this occurs so it may be something different.

**Comment by Geo25rey** [comment] 2021-03-03 13:22
@Fenrirthviti It's compiled from source

**Comment by Geo25rey** [comment] 2021-03-03 13:25
@kkartaltepe It probably is a Qt bug, but I want to leave this opened until the issue is resolved.

**Comment by kkartaltepe** [comment] 2021-03-04 17:12
Well assuming you want the bug to be fixed and not just to have a random open bug against obs. I suggest you follow the steps outlined to confirm whether or not it is the same QT bug and provide the people who can fix it your feedback.

**Comment by Geo25rey** [comment] 2021-03-04 17:19
> Well assuming you want the bug to be fixed and not just to have a random open bug against obs. I suggest you follow the steps outlined to confirm whether or not it is the same QT bug and provide the people who can fix it your feedback.

I was just looking into the Qt source code and I do believe it is the same issue, but, apparently, Qt is no longer FOSS and is commerial-only.

I found [this](https://github.com/strawberrymusicplayer/strawberry/issues/254#issuecomment-778667007) with a patch for Qt, but I don't think it'll every be publicly merged until there is a FOSS fork of Qt.

**Comment by Geo25rey** [comment] 2021-03-04 20:07
If anyone runs into the same issue, I made an [AUR package](https://aur.archlinux.org/packages/qt5-wayland-bugfixport-git) and a [GitHub repo](https://github.com/Geo25rey/qt5-wayland.git) which incorpates the previously mentioned patch and is there for any other Qt5 Wayland-related bug fixes as necessary.

**Comment by kkartaltepe** [comment] 2021-03-04 21:11
I suggest you follow up with Qt's bug on that, since it doesnt matter what version of Qt we use if they never fix the bug. Thanks for the research.

**Comment by GeorgesStavracas** [comment] 2021-04-27 14:08
Looks like [a fix](https://codereview.qt-project.org/c/qt/qtwayland/+/343864) for [QTBUG-81504](https://bugreports.qt.io/browse/QTBUG-81504) landed for Qt 6.2. We might need to poke KDE folks to add it to their 5.15 extra patchset.

**Comment by GeorgesStavracas** [comment] 2021-05-27 23:23
Seems like the proposed fix for [QTBUG-81504](https://bugreports.qt.io/browse/QTBUG-81504) wasn't enough. I can confirm it is still happening.

[I gave it a shot at fixing it](https://bugreports.qt.io/browse/QTBUG-81504?focusedCommentId=568643&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-568643) and I think the proposed fix should be enough, but it needs at least a round of code review. While it doesn't get a review, it would be fantastic if anyone else here could test it and let me know if this crash somehow is still reproducible or not.

I'm not really sure how this fix will propagate to distros; I assume at some point it'll need to reach the KDE Qt patchset? Perhaps @grulja knows?

**Comment by Geo25rey** [comment] 2021-05-28 10:36
@GeorgesStavracas that's very strange. Since the first patch, I haven't experienced the issue. Which desktop environment are you in? It works for me on Sway.

**Comment by progandy** [comment] 2021-05-28 10:45
@Geo25rey: There are different 3 patches:
* patch 1 - the one in your fork (never landed in qt): https://github.com/Geo25rey/qt5-wayland/commit/e3879c175b73a68bdac41b396f4428ebb9437d5b
* patch 2 - the one merged in qt6, very different from patch 1: [93058de8d](https://invent.kde.org/qt/qt/qtwayland/-/commit/93058de8d7e7c2f320c22b3bd898aa06cf5babcd)
* patch 3 **(new)** - [by GeorgesStavracas (very similar to patch 1 with some more changes)](https://bugreports.qt.io/browse/QTBUG-81504?focusedCommentId=568643&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-568643)
So even if "patch 1" fixed it for you, then the official "patch 2" might still have the bug.

**Comment by Geo25rey** [comment] 2021-05-28 11:09
After looking at Patch 2, I believe it theoretically should work, but that assumes that the `isExposed()` is implemented properly.

**Comment by mind-overflow** [comment] 2021-09-14 13:05
Hello, no update on this?

**Comment by RytoEX** [comment] 2021-09-14 20:55
> 
> 
> Hello, no update on this?

The updates would be at Qt's bug tracker or repository.  If you follow the links in the discussion above, you'll see that the patches submitted to Qt have not had any updates in a while, so there has been no update here.

https://bugreports.qt.io/browse/QTBUG-81504?focusedCommentId=568643&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-568643
https://codereview.qt-project.org/c/qt/qtwayland/+/351447
https://codereview.qt-project.org/c/qt/qtwayland/+/351448

@GeorgesStavracas Do you need to follow-up on the QTBUG thread or the codereview threads, or is this just making its way through their process at the moment?

**Comment by GeorgesStavracas** [comment] 2021-09-15 19:24
I don't know what they're waiting for... both patches received +2 and were accepted, but their CI is failing in ways I can't reproduce locally.

**Comment by mind-overflow** [comment] 2021-09-15 20:03
@RytoEX You're absolutely right, it was pretty dumb of me to not look into the main issue first. I'll keep following it there, but it looks kinda stale either way. Isn't there a way to at least implement a temp-fix in obs? We don't have a stable version for Wayland simply because of this bug.

**Comment by GeorgesStavracas** [comment] 2021-09-27 11:23
My patches were merged for Qt6, and KDE folks are already backporting it to 5.15: https://invent.kde.org/qt/qt/qtwayland/-/merge_requests/16

After that, there won't be much else to do here. Please ask your distros to use this patchset.

**Comment by GeorgesStavracas** [comment] 2021-09-27 13:54
Closing since now it's up to distros to ship this patch.

**Closed by GeorgesStavracas** 2021-09-27 13:54 UTC
Labels: Linux, Fix available, Dependency Issue, Confirmed

**Comment by GeorgesStavracas** [comment] 2021-09-28 15:11
Quick update: the KDE patchset now includes these patches, and the KDE 5.15 Flatpak platform is in the process of updating. The Flatpak version OBS Studio will benefit from this fix soon. Again, please ask your distro to update to the latest version of the KDE patchset.

**Comment by abcdw** [comment] 2023-01-18 14:05
Fixed it in guix https://git.savannah.gnu.org/cgit/guix.git/commit/?id=a43c524252.

Kudos to @GeorgesStavracas.
