### ISSUE TITLE
Seg Fault on start

### ISSUE THREAD

**Issue by ChimiChurr0** [obsproject/obs-studio#8616] opened 2023-04-01 20:31 UTC
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

29.0.2

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

Software starts

### Current Behavior

`[linuxbebop@linuxbebop-nitroan51553 ~]$ obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
info: CPU Speed: 3900.256MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 15849MB Total, 5484MB Free
info: Kernel Version: Linux 6.2.9-cannonlake-xanmod1-1
info: Distribution: "Manjaro Linux" Unknown
info: Desktop Environment: XFCE (xfce)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 6.4.3 (runtime), 6.4.3 (compiled)
info: Portable mode: false
info: OBS 29.1.0-beta1-23-g1be1f5163-modified (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
ATTENTION: default value of option mesa_glthread overridden by environment.
info: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 630 (CFL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.0.1, shading language 4.60
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Area
        fps:               30/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] No captures available
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.21.0
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
info: NVENC supported
Segmentation fault (core dumped)
`

### Steps to Reproduce

1.Launch
2.Seg Fault

### Anything else we should know?

Tried both the Package from repo and compiling the git version, both return the same error.
last time I used OBS was in November and it worked as expected.

**Comment by tytan652** [comment] 2023-04-01 20:33
Duplicate of #8056

**Closed by tytan652** 2023-04-01 20:33 UTC

**Comment by ChimiChurr0** [comment] 2023-04-01 20:48
> Duplicate of #8056

Thank You!
