### ISSUE TITLE
Crash when exiting from a full screen application (reproduced on Osu!)

### ISSUE THREAD

**Issue by aliencaocao** [obsproject/obs-studio#5211] opened 2021-08-28 12:03 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/be0GQJ5dmPFbjMqu

### Expected Behavior

Does not crash

### Current Behavior

Crashed when I used windows key or ctrl+esc out of a gaming (Osu!) running in full screen. The crash happens no matter if I start recording or not. The log shows I started recording, but it is 100% reproducible on my machine without recording. Turning off hardware gpu scheduler, game mode and running on admin all does not solve the issue. This only happens with the 27.1 rc-1, it was completely fine in 0.27.0.1

### Steps to Reproduce

1. Open Osu! in full screen mode
2. Open OBS and set a game capture to capture either full screen apps or specific osu window (both leads to crash)
3. Enter osu, then use windows key or ctrl-shift-esc  to minimize the game
obs freezes briefly and crashes

### Anything else we should know?

Running discord in background with overlay off, running MSI afterburner with OSD overlay on in stealth mode. Game is running in D3D11
Log shows an error with D3D11 capure.

**Comment by WizardCM** [comment] 2021-08-28 12:04
Duplicate of #5208

**Closed by WizardCM** 2021-08-28 12:04 UTC
