### ISSUE TITLE
Faded Visuals

### ISSUE THREAD

**Issue by kautif** [obsproject/obs-studio#4636] opened 2021-05-02 16:50 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

![image](https://user-images.githubusercontent.com/22201101/116820733-b5666300-ab33-11eb-8e99-bbf0d8b0d969.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/22201101/116820632-4557dd00-ab33-11eb-95b9-d56e0bceb14b.png)

### Steps to Reproduce

1. Copy bin, data, and obs-plugin directories and contents (OBS-Studio-27.0-rc3-Full-x64.zip)
2. Paste them to overwrite previous OBS studio bin, data, and obs-plugin directories and contents (OBS Studio 26.1.1)
3. Result occurs as shown above but for ALL visual assets whether alert boxes, gifs, videos, etc.
...

### Anything else we should know?

I believe that's it.

**Comment by dodgepong** [comment] 2021-05-02 16:55
All the "faded visuals" you're referring to here are browser sources, caused by the StreamElements plugin, which overwrites the default browser source. Streamelements will need to update their plugin for compatibility with v27.

**Comment by Fenrirthviti** [comment] 2021-05-03 04:01
Closing per above, we do not support OBS with the SE plugin installed due to their replacement of core components with their own versions. Please report this to them.

**Closed by Fenrirthviti** 2021-05-03 04:01 UTC
