### ISSUE TITLE
Illegible modal in Win10 (4k resolution)

### ISSUE THREAD

**Issue by johnrichardrinehart** [obsproject/obs-studio#3512] opened 2020-09-28 23:21 UTC
## Platform
Operating system and version: **Windows 10 Pro r2009**
OBS Studio version: **25.0.8 x86_64 portable binary**

## Expected Behavior

The Settings modal navbar should (IMHO) be adjustable-width.

## Current Behavior

The Settings modal appears as shown below on my 4k monitor. I'm currently on a 15" laptop in landscape mode with 3840 x 2160 "Display resolution" at 250% scale (according to the Control Panel -> System -> Display Scale and Layout.

The modal appears as shown below. The yellow boxed region is fixed width. That's the issue for me. The text is cut off and the navbar (boxed region) is (horizontally) scrollable, but fixed width.

![Settings modal](https://user-images.githubusercontent.com/6321578/94495251-185ed880-01a6-11eb-834e-2ed43d2f2322.png)

## Additional Notes

After adjusting the DPI settings in the binary's properties (right click portable `obs64.exe` binary -> Properties -> Compatibility -> Change high DPI Settings -> check both boxes and set each drop down to "I open this program" then "System (Enhanced)".

Now it looks like the below.

![Settings modal after high DPI settings change](https://user-images.githubusercontent.com/6321578/94495434-9c18c500-01a6-11eb-8e3e-0f26d730f289.png)

**Comment by WizardCM** [comment] 2020-09-28 23:22
Closing as a duplicate of #2634

**Comment by Fenrirthviti** [comment] 2020-09-28 23:22
Effectively a duplicate of https://github.com/obsproject/obs-studio/issues/2634

Closing this one, we are tracking that issue.

**Closed** 2020-09-28 23:22 UTC

**Comment by johnrichardrinehart** [comment] 2020-09-28 23:28
Oh, sorry everyone. I tried searching first. "modal" "Settings" "menu size"....
