### ISSUE TITLE
Video Output Device outputting colors weirdly

### ISSUE THREAD

**Issue by SpencerComputers** [obsproject/obs-studio#7266] opened 2022-09-02 05:46 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/79dN1ZkxYDTv9n3a

### Expected Behavior

Video Capture Device outputs colors correctly.

### Current Behavior

Video Capture Device (Camlink 4K) showing strange colors as seen [here](https://i.imgur.com/MVZV3mH.png).

Upon viewing on Windows built in camera app, everything appears to be normal.

### Steps to Reproduce

1. Turn on Video Device (camera in this case)
2. Connect to Camlink 4K and plug into computer
3. Open OBS Studio and ensure Camlink is added as a Video Output Device

### Anything else we should know?

I tried opening the camera output through Windows camera while writing this, so I could screenshot it to show, but I forgot to close OBS, so the camera output was still in use. Once I did this, OBS' camera feed fixed itself magically, and after a reboot was still fixed up.

Really strange, but it obviously did something.

**Comment by prgmitchell** [comment] 2022-09-02 08:23
This looks to be the same bug reported in #7239

**Comment by SpencerComputers** [comment] 2022-09-02 08:25
> This looks to be the same bug reported in #7239

Thanks, wasn't sure what UVC was and assumed it was some sort of NDI network camera or something. My bad, if this can get merged by somebody then that would be great.

**Comment by RytoEX** [comment] 2022-09-03 00:17
Duplicate of #7239

**Closed by RytoEX** 2022-09-03 00:17 UTC
