### ISSUE TITLE
The dock remains stationary after attempting to move it the first time (next times it's ok)

### ISSUE THREAD

**Issue by SovaProgrammer** [obsproject/obs-studio#3728] opened 2020-11-13 17:29 UTC
## Platform

Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 26.0.2

## Expected Behavior
Dock panel moves immediately after unpinning.

## Current Behavior
Dock panel unpinning but does not move.

## Steps to Reproduce
1. Open OBS Studio.
2. Unpin any the dock and try to move it.

## Additional information
[Video](https://youtu.be/tJsHEFGiKwk)

#3729 
The browser dock does not attach immediately after unpinning (when does not click to dock but only to bring the cursor closer and hover over the attachment point all OK)

## Expected Behavior
Dock panel is docked after undocked.

## Current Behavior
After undocked, the docking station does not insert into the docking station.

## Steps to Reproduce
1. Open OBS Studio.
2. Unpin any the dock and try to dock it.

## Additional information
[Video](https://youtu.be/b7qrIfBXiyU)

#3730
The dock panel can be moved without clicking on it

## Expected Behavior
The dock panel does not move.

## Current Behavior
The dock panel is moving.

## Steps to Reproduce
1. Open OBS Studio.
2. Unpin any the dock and, without clicking on it, move the cursor closer to the heading, and then move slowly.

## Additional information
[Video](https://youtu.be/pOT_HGglgpI)

**Comment by gxalpha** [comment] 2020-11-13 18:50
Am I right to assume that this is the same or similar as #3729 and #3730 ?
If so, could you maybe put the information all into one issue?

**Comment by WizardCM** [comment] 2021-01-17 03:27
Verified on macOS 10.14, however I'm not sure if it's something we have the ability to fix (it could be a limitation of Qt).

**Comment by WizardCM** [comment] 2021-05-10 03:26
I've spent some time over the past few weeks trying to debug/fix this.

For posterity, here are my findings so far:

1. this has been an issue on OBS on macOS since docks were introduced (verified in [OBS v20, released 2017](https://github.com/obsproject/obs-studio/releases/20.0.1))
2. this is limited to the main OBS window. adding a second (simplified) MainWindow and setting it as the parent of the Stats dock does not exhibit the same issue
3. I have tried removing code such as event listeners/handlers & other bits of code from `window-basic-main` and `obs-app` to try and fix the issue, with no luck so far.

I am still in the process of trying to trigger the issue on a second MainWindow by copying code from `window-basic-main.cpp` into my own recreation.

Image of progress so far:
![image](https://user-images.githubusercontent.com/941350/117601855-9ea6b880-b192-11eb-8b6a-df83061c020b.png)

**Comment by RytoEX** [comment] 2021-05-22 02:10
This sounds like [QTBUG-93064](https://bugreports.qt.io/browse/QTBUG-93064).  Though, [QTBUG-90976](https://bugreports.qt.io/browse/QTBUG-90976) and [QTBUG-88993](https://bugreports.qt.io/browse/QTBUG-88993) are also similar in nature. We do set Qt::WA_NativeWindow in a few places:

https://github.com/obsproject/obs-studio/blob/8bcb2c3d42d5e4b801e645b93c6d95625f2859a1/UI/window-basic-main.cpp#L215

https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/UI/qt-display.cpp#L89

https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/UI/window-dock-browser.hpp#L12

We _only_ set `Qt::AA_DontCreateNativeWidgetSiblings` on Wayland, which reportedly should prevent QTBUG-88993.
https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/UI/obs-app.cpp#L1404

**Comment by RytoEX** [comment] 2021-05-22 02:15
@GeorgesStavracas I've been asked to ping you since you've worked on some of the issues with native siblings and widgets.  Thoughts?

**Comment by GeorgesStavracas** [comment] 2021-05-22 14:22
I've made the change to only set `Qt::AA_DontCreateNativeWidgetSiblings` on Wayland because it was causing problems on X11. 

I never tested it on Mac, but AFAIR from the commentary on it, setting this flag on Mac seemed to improve a few things here and there, but cause a regression with browser docks where the white rectangle that indicates hover state when dragging a panel was being drawn behind the browser contents. Is this issue still present? Do the improvements gained from setting this flag on Mac overweight this regression?

**Comment by WizardCM** [comment] 2021-05-23 01:13
> For posterity, here are my findings so far:
> 
> 1. this has been an issue on OBS on macOS since docks were introduced (verified in [OBS v20, released 2017](https://github.com/obsproject/obs-studio/releases/20.0.1))
> 2. this is limited to the main OBS window. adding a second (simplified) MainWindow and setting it as the parent of the Stats dock does not exhibit the same issue
> 3. I have tried removing code such as event listeners/handlers & other bits of code from `window-basic-main` and `obs-app` to try and fix the issue, with no luck so far.
> 
> I am still in the process of trying to trigger the issue on a second MainWindow by copying code from `window-basic-main.cpp` into my own recreation.

After @RytoEX's most recent comments, I spent most of yesterday looking into this further, and here's what I've been able to determine:

1. This does seem related to native widgets/windows
2. I **can** manually trigger this bug on my second MainWindow if I attach any browser docks to it. In this case, this does seem to mean that:
    * browser docks are at least one cause (but not the only cause)
    * additionally, if I then close the browser dock, the issue doesn't disappear until a full OBS restart - this is consistent with the known behavior that if a window is converted to native, it does not revert to being non-native in future
3. We use `winId()` in a few places in the OBS codebase, which also has the potential to convert a window to native, triggering this bug
    * however, as I copied over the preview to my secondary MainWindow, it doesn't seem to be the cause on its own
    * I did add at least one use of winId() to my mainwindow (specifically "disable colour space conversion") but it did not cause the issue to occur
4. I did test enabling the `Qt::AA_DontCreateNativeWidgetSiblings` flag on OBS as a whole, but it **did not** magically fix the issue

Here is a video of me reproducing 1)

https://user-images.githubusercontent.com/941350/119244747-dcee9f80-bbb6-11eb-863a-40b79514ebbe.mp4

This all leads me to believe that some code, somewhere, is causing the OBS main window to become native, which then breaks docking. Theoretically, Qt _could_ fix the bug on their side, however as it's been around since at least 2017 I'm not holding my breath.

Additionally, I did try to fix 1) but was unable to determine exactly which element is triggering the issue. I think the best use of my time for now would be to continue trying to fix 1) specifically before I spend more time trying to track down the main window's issue.

**Comment by GeorgesStavracas** [comment] 2021-05-23 01:27
>This all leads me to believe that some code, somewhere, is causing the OBS main window to become native, which then breaks docking.

Unless Qt differs substantially from other toolkits, all toplevels (windows, dialogs, tooltips) must be native. Any GUI applications have at least one native window.

**Comment by WizardCM** [comment] 2021-05-23 02:06
> Unless Qt differs substantially from other toolkits, all toplevels (windows, dialogs, tooltips) must be native. Any GUI applications have at least one native window.

Which makes this issue all the more confusing, because it's fine in one window and broken in another.

**Comment by WizardCM** [comment] 2022-10-13 23:58
Seems I forgot to mark this as fixed with 88a51dbf977d94431bdb8a2caeff44b7b1658fa4 - which should be available in OBS 28.0.2 and above. Note that this fixes the issue for every dock **except** browser docks.

This fix was made possible by the summary of the issue (and the code) provided in Qt 6.2.0 https://github.com/qt/qtbase/commit/3224c6d7d150164241c13ccf7d47377a39c0a6bb

**Closed by WizardCM** 2022-10-13 23:58 UTC
Labels: macOS, Dependency Issue, Confirmed
