### ISSUE TITLE
Studio mode grouped items problem

### ISSUE THREAD

**Issue by BatuhanOzusta** [obsproject/obs-studio#4108] opened 2021-01-20 09:46 UTC
## Platform

Operating system and version: Windows 10 Pro 64 bit
OBS Studio version: 26.1.1

## Expected Behavior
 When I switch to studio mode, the grouped items slide out.
## Current Behavior
 Grouped items should not slide out when switching to studio mode.
 [2021-01-20 11-58-12.txt](https://github.com/obsproject/obs-studio/files/5841442/2021-01-20.11-58-12.txt)

## Steps to Reproduce

1. Screenshot: https://youtu.be/h14vAfBzQB4
2.
3.
4.

## Additional information
 I may not be able to explain it properly because my English is a bit poor, but it appears in the video.
Grouped items should be reviewed.

**Comment by RytoEX** [comment] 2022-11-02 20:30
Please re-test this in OBS Studio 28.1.1 (or newer) and confirm if this is still an issue. If this is still an issue, please provide a new OBS log. Ideally, please also reproduce this in a minimal scene collection with only a single scene showing the issue, so that it is easier for us to try to identify the cause.

**Comment by Warchamp7** [comment] 2022-11-03 00:20
By default, Studio mode only duplicates the scene, allowing the editing of things like transform and visibility. 

If you would like to ensure that nested scenes and groups do not update live in studio mode, you should enable the `Duplicate sources` option as well.

![image](https://user-images.githubusercontent.com/1554753/199626054-1d87a739-150b-4a8b-80ed-53a31a1de47e.png)

**Comment by gxalpha** [comment] 2023-04-14 10:11
Closing per the above explanation. Please enable "Duplicate Sources" to achieve what you’re looking for.

**Closed by gxalpha** 2023-04-14 10:11 UTC
