### ISSUE TITLE
Replay buffer doesn't work for custom ffmpeg output

### ISSUE THREAD

**Issue by RubenHetKonijn** [obsproject/obs-studio#5224] opened 2021-08-31 06:09 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/rufMExA2muFu_7ew

### Expected Behavior

It should either display it's not supported or give me all the options.

### Current Behavior

It shows a checkbox to enable replay buffer, but the button to start it doesn't appear and there are no other options

### Steps to Reproduce

1. Open Settings
2. Output tab > Recording tab
3. Copy settings
![image](https://user-images.githubusercontent.com/64010592/131450970-286a3f74-a5f8-445d-8ca0-711dcb88b455.png)
4. See bug in replay buffer tab
![image](https://user-images.githubusercontent.com/64010592/131451004-50499213-f7cb-41a5-a60f-e3eae65f0792.png)

**Comment by Fenrirthviti** [comment] 2021-08-31 06:17
Duplicate of #4948

**Closed by Fenrirthviti** 2021-08-31 06:17 UTC
