### ISSUE TITLE
Hotkey with shift occationally acts like another hotkey without shift

### ISSUE THREAD

**Issue by norihiro** [obsproject/obs-studio#5697] opened 2021-12-26 12:26 UTC
### Operating System Info

Other

### Other OS

Fedora 34, also observed on CentOS 8

### OBS Studio Version

Git

### OBS Studio Version (Other)

27.1.3-328-g788dfa860

### OBS Studio Log URL

https://obsproject.com/logs/N5g1jtKz7quQ-KXx

### Expected Behavior

When hit Shift + F6, the program should switch to a scene named `Scene 2`, whose select-scene hotkey is Shift + F6.

### Current Behavior

When hit Shift + F6, the program switches to a scene named `Scene 1`, whose select-scene hotkey is F6 (without shift).

### Steps to Reproduce

1. Create two scenes `Scene 1` and `Scene 2`
2. Assign F6 as the hotkey to switch to the scene `Scene 1`
3. Assign Shift + F6 as the hotkey to switch to the scene `Scene 2`
4. Switch `Scene 2`
5. Restart OBS Studio
6. Hit F6
7. Hit Shift + F6

### Anything else we should know?

At the step 4, if switched to `Scene 1`, the problem does not happen.

**Comment by WizardCM** [comment] 2021-12-26 12:33
This is while OBS is focused?

**Comment by norihiro** [comment] 2021-12-26 12:37
> This is while OBS is focused?

Yes, I didn't change focus of OBS.
Thanks to gxalpha, I figured a PR #5095 fixes the issue.

**Comment by Fenrirthviti** [comment] 2021-12-26 22:50
Duplicate of https://github.com/obsproject/obs-studio/issues/4408

**Closed by Fenrirthviti** 2021-12-26 22:50 UTC
