### ISSUE TITLE
OBS Crashes while having an active Decklink Output 

### ISSUE THREAD

**Issue by TLBCTech** [obsproject/obs-studio#8922] opened 2023-05-18 00:19 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/d9JxkPPZ3bo7ABTw

### OBS Studio Crash Log URL

https://obsproject.com/logs/d9JxkPPZ3bo7ABTw

### Expected Behavior

Expectation is to use DeckLink Output feature to display PC desktop on external monitors in auditorium.

### Current Behavior

Desktop display freezes on external monitors, but not the computer monitors.  when the stop button is clicked, OBS crashes and must be restarted.  This has happened multiple times since the 29.1.1 update was installed.  this issue was not occurring before the update.

### Steps to Reproduce

1. Select the Desktop Scene. Preview displays correctly in the OBS viewer.
2. Click Tools > Decklink Output > Output - click Start; Preview Output - Click Start
3. External displays in auditorium show the desired video image, however, the image on the auditorium screens is now frozen
4. Decklink Output Screen - Click "Stop"under Output.  
5. Decklink Output Screen - Click "Stop" under Preview Output 
6. OBS Crashes.
...

### Anything else we should know?

The DeckLink Output feature was functioning properly Prior to installing the update.  We use it regularly during our church services.

**Comment by gxalpha** [comment] 2023-06-01 19:41
> This has happened multiple times since the 29.1.1 update was installed. this issue was not occurring before the update.

So did this happen on 29.1.0 as well, or was it specifically introduced in the patch release?

**Comment by TLBCTech** [comment] 2023-06-04 14:20
Good Morning!  This did not happen on 29.1.0.  It started with 29.1.1 and has continued with 29.1.2

**Comment by RytoEX** [comment] 2023-06-07 00:20
> Good Morning! This did not happen on 29.1.0. It started with 29.1.1 and has continued with 29.1.2

There's not much changed between 29.1.0 and 29.1.1.
https://github.com/obsproject/obs-studio/compare/29.1.0...29.1.1

**Comment by gxalpha** [comment] 2023-09-11 12:56
@TLBCTech could you reinstall OBS 29.1.0 and check if it still doesn't happen there, and then reinstall OBS 29.1.1 to confirm it still does happen there?

**Comment by RytoEX** [comment] 2023-10-25 13:16
Possibly fixed by #9712.

**Comment by RytoEX** [comment] 2024-04-13 01:50
We're fairly certain that #9697 was a duplicate of this (the crash stacks are the same), and that this was fixed by #9712.

**Closed by RytoEX** 2024-04-13 01:50 UTC
