### ISSUE TITLE
Flickering and glitching when using pipewire + wayland

### ISSUE THREAD

**Issue by kassindornelles** [obsproject/obs-studio#6408] opened 2022-05-01 11:11 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/ozoWunBURbg0CP9c

### Expected Behavior

The preview should be working, also recording renders the same glitches in the preview

### Current Behavior

the preview is flickering and rendering garbage, looks like this:
![image](https://user-images.githubusercontent.com/40970965/166143257-5b118e6c-3f08-4bb4-8314-81f2a5cacab0.png)

### Steps to Reproduce

1. start a GNOME wayland session
2. open OBS and try to capture the screen and/or a window
3. it will start flickering and showing garbage

### Anything else we should know?

I am using the flatpak version of OBS but i also tried the normal OBS package for arch linux and it also is broken
I have pipewire, pipewire-pulse, pipewire-alsa and pipewire-jack installed

no idea if it affects other desktop environments that also support wayland.

**Comment by kassindornelles** [comment] 2022-05-01 13:04
Some other details:

GPU: AMD RX 560 4 GB
FFmpeg is installed, all the gstreamer plugins too
screen resolution is 1366x768 so maybe OBS is going crazy about the resolution?

**Comment by kassindornelles** [comment] 2022-05-01 13:35
changing resolution seems to work

![image](https://user-images.githubusercontent.com/40970965/166148303-2bc263a9-7018-458a-b42f-ed74615e2c0e.png)

**Comment by kkartaltepe** [comment] 2022-05-01 15:46
Looks like a duplicate of #4961

**Closed by kkartaltepe** 2022-05-01 15:46 UTC
