### ISSUE TITLE
[BUG] Changing the visibility of a source in a group makes it being shown on live program directly although sources are duplicated

### ISSUE THREAD

**Issue by chaours** [obsproject/obs-studio#2856] opened 2020-05-02 23:19 UTC
## Platform
Operating system and version: Windows 10 x64 v1909
OBS Studio version: 25.0.8

## Expected Behavior
[On studio mode]
With Duplicate scene checked, when the visibility of a source is changed, the source isn't being displayed or undisplayed on the program before the transition between preview and program is done.
If the source is in a group, the behavior should be the same.

## Current Behavior
If the source is in a group, when changing its visibility, it is updated directly on both preview and program.

## Steps to Reproduce
With studio mode enabled.
1. Create a sources group in a scene.
2. Add a new source inside the group, and make it not visible.
3. Apply the scene preview on live program.
4. Put the same scene in the preview.
5. Make the source in the group visible.
The new state is directly applied on both preview and program live views.

Should the source not be in a group, it's fine : the transition between preview and program is done manually by clicking on transition.

**Comment by WizardCM** [comment] 2020-08-26 00:57
Visibility of a source in a scene is tied to the scene. Visibility of a source in a group is tied to the group.

Therefore, "Duplicate scenes" controls sync of source visibility, and "Duplicate sources" (ie groups) controls sync of grouped source visibility.

This is _technically_ by design, but it's certainly confusing UX. I'm honestly not sure if this is something we can fix with the current internal design of groups.

**Comment by gxalpha** [comment] 2022-09-22 22:22
Closing as this is by technically design and pretty much inherent to the design of groups, as explained above.

**Closed by gxalpha** 2022-09-22 22:22 UTC
Labels: By Design / Not a bug, Confirmed
