### ISSUE TITLE
27.2 OBS crashes when trying to add transition

### ISSUE THREAD

**Issue by MIchael-Kelly7** [obsproject/obs-studio#5845] opened 2022-01-22 12:28 UTC
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

https://obsproject.com/logs/jZ_-w2CcE0bGkS4b

### Expected Behavior

After clicking the transition drop down and clicking Add <transition type> I expect to name the transition then select from a list or file what transition to use.

### Current Behavior

After clicking the drop down for scene transition  > Add: Swipe (or any add) a dialog box pops up to ask me to name the transition. Once I click OK there OBS crashes. I tried to launch from terminal to see if I could spot an error there and checked the log file to see if there was anything there. But I don't see anything in either.

This also happens when right clicking on the source and choosing a show or hide transition beyond cut or fade.

### Steps to Reproduce

1. Click the scene drop down 
2. Click Add: <any of the add options> 
3. Name new transition and click OK
4. OBS crashes

Alternately, right click a scene and go to show transition or hide transition select any transition that would need an Add transition dialog to start.
...

**Comment by exeldro** [comment] 2022-01-22 16:10
This is a known issue of the beta 3 and should be fixed in the upcoming beta release.

**Comment by ogmkp** [comment] 2022-01-23 14:05
> This is a known issue of the beta 3 and should be fixed in the upcoming beta release.

Hi @exeldro , which commit fixes the issue please?

**Comment by ogmkp** [comment] 2022-01-23 14:23
https://github.com/obsproject/obs-studio/issues/5813#issuecomment-1013910166

Found.

**Comment by WizardCM** [comment] 2022-01-24 00:03
Duplicate of #5813

**Closed by WizardCM** 2022-01-24 00:03 UTC
Labels: Fix available, Confirmed
