### ISSUE TITLE
[Crash] OBS crashes when macOS switches into Secure Event Input mode

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#2605] opened 2020-03-30 17:03 UTC
## Platform
Operating system and version: 10.15.3 + 10.15.4
OBS Studio version: 24.0.6

## Expected Behavior
Application should not crash.

## Current Behavior
Application crashes in all states (i.e. recording/not recording, streaming/not streaming) when another application requests macOS enter Secure Event Input mode, typically this would be related to Touch ID and Password prompts in both GUI applications and the Terminal, ex: Chrome, 1Password, Terminal, Keychain, etc...

_Weirdly this doesn't seem to apply to Touch ID in System Preferences in the same way, but does in Password entry?_

## Steps to Reproduce
1. Open OBS
2. Open an application which prompts for a password or Touch ID.
3. Crash instantly or within 5 seconds.

## Related to 
Likely related to, but more abstract/broader remit than #2292

## Additional information
It seems very likely this is related to macOS Secure Event Input as this is also reproducable as follows:

1. Open OBS
2. Open Terminal
3. Click Terminal > Secure Keyboard Entry
4. OBS crashes
5. Reopen OBS
6. OBS crashes
7. Disable Secure Keyboard Entry
8. Reopen OBS
9. OBS does not crash.

Useful Apple Reference:
https://developer.apple.com/library/archive/technotes/tn2150/_index.html

**Comment by WizardCM** [comment] 2020-04-04 00:26
Closing in favour of #2292 as internally it's caused by the same issue.

**Closed by WizardCM** 2020-04-04 00:26 UTC
Labels: macOS
