### ISSUE TITLE
Menu bar not compatible with KDE Plasma's menu bar

### ISSUE THREAD

**Issue by leafpool243** [obsproject/obs-studio#9334] opened 2023-07-29 16:04 UTC
### Operating System Info

Other

### Other OS

Ubuntu (Kubuntu) 23.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/yeOxmCAAYfMjaVr5

### Expected Behavior

Menubar should show up in the global menu:

Example from another application:
![圖片](https://github.com/obsproject/obs-studio/assets/63614345/d1ed0fae-8707-4abc-a30f-590971d94c11)

### Current Behavior

Nothing shows up in the menubar.
![圖片](https://github.com/obsproject/obs-studio/assets/63614345/3c2aa328-587d-444d-ab3a-60814bdcacf5)

### Steps to Reproduce

1. Use KDE's global menu
2. Ensure that the “Application menu daemon” is enabled in Settings->background services (This is required for global menu to work)
3. OBS won’t have the global menu

### Anything else we should know?

If Application menu daemon is disabled, then I can access OBS’s menu bar,
![圖片](https://github.com/obsproject/obs-studio/assets/63614345/11767f16-e6f1-4bcd-8144-f155ab123c41)

But obviously that ruins the global menu bar for other applications as well.

**Comment by derrod** [comment] 2023-07-29 16:10
This appears to be a duplicate of #8361

**Comment by leafpool243** [comment] 2023-07-29 16:17
@derrod Oh, oops! Sorry

**Comment by tytan652** [comment] 2023-07-29 16:20
Duplicate of #8361

**Closed by tytan652** 2023-07-29 16:20 UTC
