### ISSUE TITLE
No audio output to the stream after disconnecting and reconnecting back when using VOD track

### ISSUE THREAD

**Issue by Dzinsham** [obsproject/obs-studio#5572] opened 2021-11-24 20:41 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/KXCavTwWgVUOEGcx

### Expected Behavior

If I have some issues with my ISP or connection and OBS disconnects but manages to reconnect in a 90 seconds window so Twitch VOD hasn't gotten split - everything should be the same as before the connection issues.

### Current Behavior

Right now every time I have a connection issue and OBS disconnects, it manages to reconnect in a couple of seconds. I can see that my audio is fine in the OBS mixer, bot my mic and desktop audio shows, not only in OBS but in Windows too, everything looks and works great, except on the actual stream there is no audio at all. I tried unplugging my mic/audio interface, switching devices in the OBS, in Windows - no help, mixer shows that everything works, but still no audio on my stream. The only thing that fixes that is ending the stream manually in OBS and starting it again.

### Steps to Reproduce

1. I guess have an internet connection issue
2. Wait for OBS to reconnect
3. Speak to the mic or play some music - everything works on my PC but nothing outputs to the stream
4. Stop the stream manually in the OBS, relaunch it - everything works now, but the VOD is split and half of the viewers are gone.

**Comment by Fenrirthviti** [comment] 2021-11-24 20:58
The log file doesn't seem to contain a reconnect event that shows the issue. Can you provide an additional log from a session where the issue occurred?

**Comment by Dzinsham** [comment] 2021-11-24 21:08
> The log file doesn't seem to contain a reconnect event that shows the issue. Can you provide an additional log from a session where the issue occurred?

[2021-11-24_21-28-50.txt](https://github.com/obsproject/obs-studio/files/7598688/2021-11-24_21-28-50.txt)
[2021-11-24_21-28-51.txt](https://github.com/obsproject/obs-studio/files/7598689/2021-11-24_21-28-51.txt)
[2021-11-24_23-07-16.txt](https://github.com/obsproject/obs-studio/files/7598690/2021-11-24_23-07-16.txt)
[2021-11-24_23-14-29.txt](https://github.com/obsproject/obs-studio/files/7598691/2021-11-24_23-14-29.txt)
That's all of the logs from today's even I believe. Some of them maybe useless, in some there are attempts of replugging the audio interface.

**Comment by Fenrirthviti** [comment] 2021-11-24 21:16
Thanks, those logs are helpful. Definitely see something weird going on with your audio devices when a disconnect happens, but I'm not sure there's much we can do on our end, it looks like the device is being disconnected from the system and then reconnected:

```
23:11:25.359: Device 'Динамики (USB AUDIO  CODEC)' invalidated.  Retrying
23:11:25.423: Device 'Линия (USB AUDIO  CODEC)' invalidated.  Retrying
23:11:28.360: [WASAPISource::TryInitialize]:[Динамики (USB AUDIO  CODEC)] Failed to activate client context: 88890004
23:11:28.424: [WASAPISource::TryInitialize]:[Линия (USB AUDIO  CODEC)] Failed to activate client context: 88890004
```

This falls under normal support at this point, so I'm going to go ahead and close this and ask that you shift to our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by Dzinsham** [comment] 2021-11-24 21:26
No, this is me manually unplugging and plugging back the audio interface while the stream was running in hope to fix stuff. There are a couple of forum threads with the same issue over the months with no answers unfortunately.

**Comment by Fenrirthviti** [comment] 2021-11-24 21:37
Ah, understood. I will reopen this then if anyone else has any ideas. I'm completely unsure how a disconnect would be impacting audio and not video, though, so I'm not sure where to go from here.

**Comment by mihawk90** [comment] 2021-11-25 04:00
My suspicion is that this is an issue on Twitch's side.

If I'm reading the log correctly, you are using the Twitch VOD track, correct?

I have had a similar issue a couple of months ago,  and so did another user on the discord.

Basically when the stream disconnects ungracefully, the audio streams both continue to be encoded and sent out, but only the VOD track is picked up by Twitch.
This actually happened fairly recently to me again. But back then and also now I have not been able to reproduce it reliably.

Could you check your Twitch VODs and see if after the reconnect you still have audio there?

The last time this happened to me, I was sending a KILL command (Linux, via KDE system monitor) to OBS to restart it without the VOD splitting, and after the reconnect, there was no audio on stream, but in the VOD.
Even clipping during the stream works there because clips use the VOD track.

**Comment by Dzinsham** [comment] 2021-11-25 14:44
> My suspicion is that this is an issue on Twitch's side.
> 
> If I'm reading the log correctly, you are using the Twitch VOD track, correct?
> 
> I have had a similar issue a couple of months ago, and so did another user on the discord.
> 
> Basically when the stream disconnects ungracefully, the audio streams both continue to be encoded and sent out upon reconnect, but only the VOD track is picked up by Twitch. This actually happened fairly recently to me again. But back then and also now I have not been able to reproduce it reliably.
> 
> Could you check your Twitch VODs and see if after the reconnect you still have audio there?
> 
> The last time this happened to me, I was sending a KILL command (Linux, via KDE system monitor) to OBS to restart it without the VOD splitting, and after the reconnect, there was no audio on stream, but in the VOD. Even clipping during the stream works there because clips use the VOD track. With that same method I was able to reproduce this in the past too, but not reliably. And seeing as OBS is still encoding (and presumably sending out) both audio streams, this gets me to the belief that this is a Twitch issue.
> 
> Unfortunately I can't test with Twitch Soundtrack as I am not on Windows, but I suspect it will only get fixed if it happens there too.

I did use Twitch Soundtrack but i have deleted it months ago! I just checked, there is still Twitch VOD option in the OBS settings for some reason. And yes, you were right, there is a sound in the VOD after the reconnection! I'll try to reinstall Twitch Soundtrack or find a way to clean it out of OBS. Is it possible to kill OBS using Windows without splitting the VOD like you did on Linux?

**Comment by mihawk90** [comment] 2021-11-25 16:17
> And yes, you were right, there is a sound in the VOD after the reconnection!

As suspected then. So... yay(?) for someone having the same issue on Windows. The aforementioned user that had the same issue was on Linux as well so we couldn't rule that out until now.

> I'll try to reinstall Twitch Soundtrack or find a way to clean it out of OBS.

I don't know how Twitch Soundtrack works exactly, is it a plugin? If yes then just uninstalling the plugin is all you need.

> Is it possible to kill OBS using Windows without splitting the VOD like you did on Linux?

There is, but I don't know if the Task Manager can do it. I believe when clicking "End Task" it sends a `TERMINATE` first and only when the application is not responding will it send a `KILL` instead.
Anyway, you can definitely do it via cmd or PowerShell.

cmd:
```
taskkill /IM obs.exe /F
```

PowerShell:
```
Stop-Process -Name "ProcessName" -Force
```

This *may* leave some sub-processes running, so you'll have to check for that manually. I don't know how it would be possible to kill all of them too (haven't used Windows for a while).

**Comment by Dzinsham** [comment] 2021-11-25 20:49
Great to know, thanks! I'll try all of the above if the issue happens again. For now I have disabled twitch vod track option. Will report once it happen!

**Comment by mihawk90** [comment] 2021-11-25 21:22
> For now I have disabled twitch vod track option. Will report once it happen!

I doesn't happen without the Twitch VOD track enabled, that's basically the "fix" for it if the VOD track is not needed.

That's why I'm saying it's probably on Twitch's side since they seem to only pick up the VOD track on reconnect.

**Comment by Fenrirthviti** [comment] 2021-11-26 01:41
Just as a further suggestion for testing purposes, you can validate if the encoder is still outputting audio by making a local recording at the same time as the stream using "Use stream encoder" as the selection. I'd be curious to know if the audio is being output to the file properly, which would more or less confirm that this is an issue on Twitch's side. If it is, we can escalate it to our Twitch contacts for them to look at.

**Comment by Dzinsham** [comment] 2021-11-26 15:39
If this counts - I have always 2 instances of OBS running, one for streaming and the other for recording. There is always audio in the recordings not matter if disconnect/reconnect happens or not. But I could try recording in the same OBS I use for the streaming if the issue happens again.

**Comment by Fenrirthviti** [comment] 2021-11-26 19:24
Yeah, unfortunately if it's a separate instance that's not a useful test. It will need to be from the same instance, and using the "Use stream encoder" option for the recording encoder.

**Comment by mihawk90** [comment] 2021-12-02 09:58
Just happened again today, and I can confirm that the recording had audio on all applicable tracks while the issue was happening live.

OBS stopped uploading (for no apparent reason, but it happens sometimes, no log entries), I killed the process again, restarted OBS, started streaming and audio was missing. Killed the process again, restarted, turned off VOD track, started stream, and it worked again.

**Comment by Dzinsham** [comment] 2021-12-09 19:24
Can confirm too, had a disconnect yesterday but Twitch VOD track was disabled - managed to reconnect in time and had all audio working as it should be.

**Comment by chdxD1** [comment] 2022-01-28 19:44
I've tried to reproduce this today. From an OBS perspective everything is the same but you can easily trigger it by:
1. Enable VOD track
2. Put some recognizable stuff into both tracks (best is two separate audio files, like two different songs). That way you'll be able to check what ends up in the VOD or on the stream.
3. Start stream
4. Kill OBS
5. Start OBS again
6. Start stream again
7. Check if audio is missing in **live stream**, VOD should be there the whole time.
8. Return to step 4

It might not "work" (or not work!) on the first time but I could get it to fail 1 out of 4 tries or so. My suspicion is that twitch has somehow issues on parsing / identifying the audio tracks on a reconnect. 
Also it helps to kill OBS again and restart the stream (still without splitting the VOD!), I could get it to recover most of the times, if not, try the same procedure again.

My suspicion is that twitch fails to recognize the audio track in the RTMP stream somehow, messing up the pipeline on their side. @Fenrirthviti I think it would definitely make sense to raise this to twitch, there are also posts on the OBS forums and on the twitch reddit regarding this.

After discussing this someone mentioned that Twitch Studio is not impacted (I've tried to execute the same steps above with Twitch Studio, I couldn't get it to fail as well), but that might make sense because apparently they are not using RTMP as a transport but rather some HTTPS / TLS based technology.

**Comment by mihawk90** [comment] 2022-02-18 10:22
For reference I was always testing with Source, mainly because I wasn't affiliate at the time and didn't get transcoding often in the first place.

**Comment by mredodos** [comment] 2022-02-24 16:08
is not problem at twitch side. 
i have no audio from all the live (multi streaming), probably something inside obs go wrong

**Comment by mihawk90** [comment] 2022-02-24 17:59
> multi streaming

To which services?
To my knowledge Twitch and YouTube are the only ones even ingesting 2 audio streams.

**Comment by Fenrirthviti** [comment] 2022-02-24 18:23
This is easily proven to be an issue on the Twitch side by making a recording at the same time using the "Same as stream" encoder option. This uses the exact same output to the stream, but sent to the file. The audio is present in the file without issue, it is only on the Twitch side where it fails. There is an extremely remote possibility this is still something on the OBS side, but given this only happens on Twitch when using the VOD feature (which is the only service that supports multi-track ingest right now, YouTube does not), it's likely this is an issue on the Twitch side. We have reached out to them to help investigate, but have so far not received a response or acknowledgement of this issue.

**Comment by mredodos** [comment] 2022-02-25 06:58
> > multi streaming
> 
> To which services? To my knowledge Twitch and YouTube are the only ones even ingesting 2 audio streams.
> 
> Also can you confirm in the log that the audio encoders keep running?

with youtube,facebook and twitch, all via obs.

the problem trigger on all STREAMING not only on twitch. obs receive audio but not send to streaming server something not reconnecting or crashing probably.

**Comment by mihawk90** [comment] 2022-02-25 20:36
When the issue happens can you please try a local recording too (just press Start Recording while the issue is happening live) and confirm whether there is audio in the outputted file.
That'll at least confirm if it's even the same issue.

**Comment by badasafish** [comment] 2022-03-07 21:58
Just tried testing this with an accompanying local recording.

1) Start stream with "Twitch VOD Track" enabled, audio is fine.
2) Force disconnect by disabling Network Adapter.
3) Stream automatically reconnects with zero audio.

Note the accompanying recording had audio in it for the entire time.
Also note the Twitch VOD had the correct audio, i.e. no music for the entire time but mic etc was present as expected both before and after the reconnection.

**Comment by Deadmano** [comment] 2022-03-19 23:21
Just to confirm, as per @badasafish's comment [here](https://github.com/obsproject/obs-studio/issues/5572#issuecomment-1061178804) that this is happening for me as well. The reconnection without audio is a major issue as it means I need to entirely end my stream manually and then start a new one, which causes a split in VODs.

I can also confirm that while the audio is non-existant on reconnection when LIVE, on the VOD page the audio does, in fact, exist! So it is something with the part of reconnecting to the existing stream? How is it that a "manual stop" is fine, but a reconnection ends up in muted audio? And is there no way to correct this even as experimental?

**Comment by mihawk90** [comment] 2022-03-20 05:58
> I need to entirely end my stream manually and then start a new one, which causes a split in VODs.

Not necessarily, you can kill the OBS process (not terminate) and restart it, then try again. That'll often get it to reconnect, but not always.

**Comment by Deadmano** [comment] 2022-03-20 14:20
> > I need to entirely end my stream manually and then start a new one, which causes a split in VODs.
> 
> Not necessarily, you can kill the OBS process (not terminate) and restart it, then try again. That'll often get it to reconnect, but not always.

That's not an option for me as I have a local recording going on at the same time which would be impacted by this.

**Comment by varajune** [comment] 2022-03-20 20:03
Hello, made an account to comment on this issue. Killing the OBS process and restarting does not work for me unless I wait the full 90 seconds for twitch's disconnection protection to end. if I terminate and reconnect via task manager, it still does not push audio through to live (only VOD). I've had to hit "stop streaming" on OBS so that the stream actually ends before I can start it back up with audio.

I've now disabled the disconnection protection and will see if the issue still occurs on my next stream.

**Comment by mihawk90** [comment] 2022-03-21 04:26
> I've now disabled the disconnection protection and will see if the issue still occurs on my next stream.

When you disable this the stream will just end when you disconnect for whatever reason (crash, internet outage, what have you), so there is nothing to reconnect *to*.
This issue is about reconnecting to an exis to ing stream but without the protection there is no existing stream because it just ends on disconnect.

**Comment by varajune** [comment] 2022-03-21 04:30
Would OBS's auto-reconnect not restart the stream? It feels like auto-reconnecting to the protection thing is what is screwing up the audio. Because of this the VOD splits anyway, so if just turning off protection does the same thing I might as well until something gets figured out, instead of having to restart it manually.

As long as protection is on, I won't get audio back until the stream actually stops.

**Comment by mihawk90** [comment] 2022-03-21 06:26
The point is once you disable the protection this issue doesn't apply to you anymore so there's nothing to test.

**Comment by WizardCM** [comment] 2022-03-21 07:18
> The point is once you disable the protection this issue doesn't apply to you anymore so there's nothing to test.
> 
> Of course this fixes the situation for you but in the context of this bug report it doesn't change a thing.

To be clear: If disabling disconnection protection on Twitch's side fixes the issue, then this 100% confirms the issue is on Twitch's side. **However**, I don't believe it has been confirmed that this is caused/related to disconnection protection on Twitch's side - this would be brand new information if that is the case.

My understanding was the issue is caused by the Twitch VoD Track specifically.

**Comment by mredodos** [comment] 2022-03-21 11:06
i repeat is not twitch side. if you stream on facebook or yuotube is the same issue

**Comment by WizardCM** [comment] 2022-03-21 11:44
@mredodos  Could you provide a session log (Help -> Log Files -> Upload Current Log File) after reproducing the issue on a non-Twitch platform?

**Comment by mihawk90** [comment] 2022-03-21 12:52
> To be clear: If disabling disconnection protection on Twitch's side fixes the issue, then this 100% confirms the issue is on Twitch's side. **However**, I don't believe it has been confirmed that this is caused/related to disconnection protection on Twitch's side - this would be brand new information if that is the case.

So if I'm understanding this right what you're saying is that this issue also exists when creating a *new* stream after OBS disconnected at some point?
That would certainly be news to me cause I have not seen that happen and from what I read in this thread there was no mention of this either. This was always talked about in combination with the disconnect protection, even the original report does:

> manages to reconnect in a 90 seconds window so Twitch VOD hasn't gotten split

That window of course being the disconnect protection. I've not heard this with new streams before. And even when I tried to reproduce this in the past and didn't manage to reconnect to the original stream (because the grace period passed), the newly created stream was always fine.

> My understanding was the issue is caused by the Twitch VoD Track specifically

Yes, but it appears to only happen on a reconnect, not on new streams (see above). At least I haven't read a report about new streams (unless I missed something somewhere?).

> combined with auto-reconnect on the OBS side, resulting in a bug on the Twitch side.

I can say with certainty it is not exclusive to auto-reconnects. I had the issue happen when OBS or my PC crashed and I restarted it manually.

**Comment by badasafish** [comment] 2022-04-14 11:40
This is continuing to be a real pain for me and I would love if we could get someone on the dev team to agree to look into this issue.  From my testing and the testing of others this will affect everyone that is using a separate VOD track and experiencing any scenario which triggers the disconnect protection.

Is there anything we can do to provide more information for this problem or help it get more visibility?

Thanks

**Comment by mihawk90** [comment] 2022-04-14 12:10
> I would love if we could get someone on the dev team to agree to look into this issue

@badasafish https://github.com/obsproject/obs-studio/issues/5572#issuecomment-1050135054

They have already reached out, but Twitch being the small startup they are, can take their time.

**Comment by Fenrirthviti** [comment] 2022-04-14 15:57
> This is continuing to be a real pain for me and I would love if we could get someone on the dev team to agree to look into this issue. From my testing and the testing of others this will affect everyone that is using a separate VOD track and experiencing any scenario which triggers the disconnect protection.
> 
> Is there anything we can do to provide more information for this problem or help it get more visibility?
> 
> Thanks

We have already looked in to it, and confirmed the behavior, and reached out to Twitch who have opened an internal case for this. I don't have any kind of ETA for when they will investigate or respond. This issue doesn't appear to be on our end, so there's not really a whole lot we can do, unfortunately.

**Comment by Fenrirthviti** [comment] 2022-04-25 17:27
> Hey everyone, I'm a Twitch engineer working on this issue. Unable to log in here with my Github Enterprise account, but rest assured I'm looking at it. I haven't been able to repro the issue though, so I decided to reach out. I have disconnect protection for both OBS and my Twitch account enabled and I've attempted unplugging and replugging the ethernet adapter to trigger disconnect and reconnect behavior. However, I still hear audio during the live stream upon reconnection. I'll attempt to disable the network adapter as @badasafish suggested to see if this works.

Make sure you have the Twitch VOD track enabled, as it seems to be required for this to manifest. The VOD track will still contain audio if listened to after the fact, but the live stream is where the audio drops out.

**Comment by alinsavix** [comment] 2022-04-25 17:28
> I haven't been able to repro the issue though

When I was testing this, I was able to get like an 80% failure rate by killing OBS with the command someone earlier in the thread suggested (on windows): `taskkill /IM obs.exe /F` ... start stream, execute taskkill, immediately restart OBS, then press the start streaming button. Should be way faster than screwing with network cables and such.

If you can't reproduce within a couple of rounds like that, you may not have your OBS audio config done correctly.

**Comment by badasafish** [comment] 2022-04-26 10:55
> Hey everyone, I'm a Twitch engineer working on this issue. Unable to log in here with my Github Enterprise account, but rest assured I'm looking at it. I haven't been able to repro the issue though, so I decided to reach out. I have disconnect protection for both OBS and my Twitch account enabled and I've attempted unplugging and replugging the ethernet adapter to trigger disconnect and reconnect behavior. However, I still hear audio during the live stream upon reconnection. I'll attempt to disable the network adapter as @badasafish suggested to see if this works.

@tomclavmaster I'm able to reproduce this issue therefore if you want some assistance with this please reach out to me on Discord and I'll be happy to help. @BadAsAFish80 🐟#0275

**Comment by badasafish** [comment] 2022-04-27 19:11
Recently the issue has become even worse, even though the outcome is the same. OBS will reconnect and show that you are streaming but actually this stream goes somewhere other than your actual twitch since you will just be shown as the Disconnect Protection message until the 90s is up and then you are offline. Hopefully @tomclavmaster can reach out to me and we'll help with replicating the issue.

**Comment by mihawk90** [comment] 2022-04-28 02:16
I actually had that happen one time, but I didn't investigate further or tried to reproduce because I thought it was a one-off.

**Comment by tomclavmaster** [comment] 2022-04-28 20:29
@badasafish Turns out I was running into the issue you're describing here. Spoke with the ingestion team and rolled out a fix for the disconnect protection issue you're describing. Thereafter I was able to reproduce the audio drop-off, so I should be good to go for debugging at this point. Thanks for the assistance and I'll reach out on discord if I can't repro again.

**Comment by thatguyjordan** [comment] 2022-05-26 02:27
@tomclavmaster Any updates on time frame of a fix being rolled out for this? Happy to hear you guys are looking into it, it's been an issue for me since vod track was introduced and I always thought it was my setup causing it

**Comment by Deadmano** [comment] 2022-05-27 17:08
Please can we get an ETA on this @tomclavmaster? This is extremely aggrevating as it happens often, and worse yet, if you reconnectthe stream won't be online at all and you have to force end, wait a bit, then start up again. At least give us an option to merge VODs so they don't get split...

**Comment by Alonsowski** [comment] 2022-06-03 17:18
hi, I'm another one having the same issue, at first I thought it was a "only me" issue but then I found this and this is exactly what I've been running into since I started using the VOD audio track. So, any updates on a fix?

**Comment by Fenrirthviti** [comment] 2022-06-03 20:10
Past few comments here have been "when is this going to be fixed" which are not helpful, and send a notification to anyone watching the project or this issue for updates. Please keep comments on topic and be patient for it to be addressed. Asking when it's going to be fixed means someone has to stop what they are doing and take the time to reply, just as I am now, which will just make it take longer.

**Comment by PremiumPanda** [comment] 2022-07-16 13:59
Had to end and restart my stream 5 times last night.  I'm glad to know this isn't just me,  but I'm also aggravated because it's happening. I just made this account and I just want to stay connected to learn how to fix this.

**Comment by EdwinStrempler** [comment] 2022-08-14 04:15
Hi guys we're hoping to get this fix soon.  I have the same problem and it's a pain. 
Greetings everyone.

**Comment by AlbinoDrought** [comment] 2022-09-09 07:10
I'm just a random dude that also wants to fix this, here is my configuration:

- On Twitch, enable VODs and disconnect protection
- On OBS, use simple output and enable "Twitch VOD Track (Uses Track 2)"
- On OBS, create a looping media source ("media source 1") that plays on tracks 1 and 2
- On OBS, create a different looping media source ("media source 2") that plays only on track 1

Here is how to confirm working setup:

- **Make sure your setup works:** perform a quick 1 minute stream
- You should hear "media source 1" and "media source 2" on the stream
- You should only hear "media source 1" in the VOD
- **Make sure your disconnect protection works:** kill OBS (`killall -9 obs`)
- You should see the Twitch disconnect protection screen
- Wait out the 90s for disconnect protection to stop and your stream to end.

Here is how I reproduce and capture the issue:

1. Start a packet capture using Wireshark or a command like `tcpdump -B 8192 -vnpi eth0 -s 0 tcp src port 1935 -w rtmp.pcap`
2. Open OBS and start your stream (`NetStream.Publish.Start: Publishing live_user_[...]`)
3. Cause a disruption in your stream
  - Physically interrupt your network connection, or
  - Virtually interrupt your network connection with something like `tcpkill -i eth0 -1 port 1935`
4. Stop the disruption, wait for stream to reconnect (`NetStream.Publish.Start: Publishing reingest.[...]`)
5. If the stream still has audio, go back to step 3 and try again

You now have a Twitch stream that has video but no audio:
- Stop the stream in OBS
- Stop the packet capture
- Extract the raw media sent by OBS using a tool like [quo/rtmp2flv](https://github.com/quo/rtmp2flv)

The media extracted from my capture has proper video and audio. This means the correct raw media is being sent to Twitch. I agree with some above posters that the issue is likely on Twitch's side due to a combination of reingest + separate VOD track.

If it's true that Twitch Studio is not impacted by this issue, it would be interesting to know if:
- RTMPS does not have this issue, and switching to RTMPS would stop OBS from being impacted
- some difference in RTMP commands sent by Twitch Studio avoids triggering this issue on Twitch's side

Cheers

**Comment by Philaeux** [comment] 2022-10-16 10:47
Hello. I am new to this thread but not new to the issue. My setup produces this bug too: VOD track, disconnect protection, losing sound when reconnecting (but not on VOD/RECORD). From my understanding of the whole tread, it's on Twitch side, either on VOD track or disconnect protection (my bet is on this one). 
I will do more tests without the disconnect protection (I am a small streamer, I can do live tests without this one), and respond if it fixes the issue.

**Comment by Philaeux** [comment] 2022-10-25 22:52
I can confirm after some tests that the Disconnect protection feature is the one inducing the bug. When I disable the feature, I don't have the sound bug anymore.

**Comment by Beeblesnout** [comment] 2022-11-24 22:16
not sure if this is entirely on topic (if not please point me in the right direction) but do we know whats causing the connection issues? my friend is experiencing these disconnects and reconnects with no audio very frequently, however i can still hear her fine on a discord call and her connection does not seem to go down whatsoever.

**Comment by Fenrirthviti** [comment] 2023-02-03 00:09
We have confirmation from Twitch that a fix for this has been deployed on their end, so I'm going to go ahead and close this issue. If this is still happening, please comment with confirmation of reproduction steps and we can revisit.

**Closed by Fenrirthviti** 2023-02-03 00:09 UTC

**Comment by jefflima1** [comment] 2023-02-21 04:33
This problem had been solved, but in the last few days I've been having connection problems, and as soon as I reconnect to the transmission again, there's no audio, just like before, it was solved for a while, but it happened again. I'm using the latest version of OBS

**Comment by Philaeux** [comment] 2023-02-22 13:20
Same feedback from me. Was solved for a while, then came back. Will retry.

**Comment by ulysso** [comment] 2023-02-24 21:10
Same here, having the exact same issue again as always. Use Disconnect Protection and VOD Track together, get a disconnect, and have no audio when coming back before the stream went down completely, but still audio on the VOD just not live. Same exact bug as it always used to be.

**Comment by Fenrirthviti** [comment] 2023-02-25 00:27
We've confirmed that the fix on Twitch's end was rolled back, but no ETA to it being redeployed.

**Comment by RytoEX** [comment] 2023-05-09 21:10
We can confirm that Twitch has globally rolled out a fix for this. Thank you for your patience.
