### ISSUE TITLE
The built-in virtual camera will bring more Pseudo-color

### ISSUE THREAD

**Issue by Danjuanlab** [obsproject/obs-studio#3573] opened 2020-10-08 01:32 UTC
Operating system and version: win10 V1809
OBS Studio version:V26.0.2

I use a x-rite video colorchecker to test the video output effects of the V26 built-in virtual camera and virtual camera plug-in. I found that the built-in virtual camera will show more Pseudo-color at the edges, and the exposure and color saturation will be reduce slightly.

![built-in VC](https://user-images.githubusercontent.com/42509669/95404938-f9500b80-0948-11eb-9f23-d474fe9825d8.PNG)
![built -in zoom](https://user-images.githubusercontent.com/42509669/95404953-00771980-0949-11eb-819d-f8848bc7cb69.PNG)
![原生示波器](https://user-images.githubusercontent.com/42509669/95404975-14bb1680-0949-11eb-945e-801f3f61eb51.PNG)
---------------------------------------------------------------

![plug-in VC](https://user-images.githubusercontent.com/42509669/95404986-1e447e80-0949-11eb-9e7c-fb367c948afb.PNG)
![plug-in VC zoom](https://user-images.githubusercontent.com/42509669/95404994-22709c00-0949-11eb-9925-5e5e57206845.PNG)
![插件示波器](https://user-images.githubusercontent.com/42509669/95405053-4df38680-0949-11eb-89b6-3f710ed8cc30.PNG)

Steps to Reproduce
1.Use the original picture into obs, start the built-in virtual camera.
2.Call the built-in camera in other software and take screenshots of the images in the software.
3.start the  virtual camera plugin.
4.Call the obs virtual camera in the same software and take screenshots of the images in the software.
5.Put these three pictures into DaVinci and compare the loss and difference with an oscilloscope.

[The original image.zip](https://github.com/obsproject/obs-studio/files/5344924/photo.zip)

**Comment by WizardCM** [comment] 2020-10-08 01:33
Please fill in the issue template

**Comment by mufunyo** [comment] 2020-10-08 11:03
The OBS preview is RGB, the virtual camera output is YUV, there is unavoidable loss associated with that conversion. You can minimise the loss by matching the output and input settings in all software involved. You neglected to mention which software you are sending OBS virtual camera output to. You should also double check your OBS output colour settings and ensure they are set to 709 and partial respectively.

**Comment by Fenrirthviti** [comment] 2020-10-09 00:01
Closing as this is not a bug.

**Closed by Fenrirthviti** 2020-10-09 00:01 UTC
