### ISSUE TITLE
No virtual camera on Fedora 40

### ISSUE THREAD

**Issue by Rondosvalle** [obsproject/obs-studio#10931] opened 2024-06-28 21:33 UTC
### Operating System Info

Other

### Other OS

Nobara Linux (Fedora 40)

### OBS Studio Version

30.2.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/K3Vn9bWQG6TrOUBH

### Expected Behavior

Start Virtual Camera button in Controls tab

### Current Behavior

I don't have "Start Virtual Camera" button in Controls tab
![image](https://github.com/obsproject/obs-studio/assets/77638123/d6bcead4-1aa6-474b-a8e8-25ab86d77278)

### Steps to Reproduce

1.  Install and update Nobara Linux to version 40
2. Install obs from the welcome screen

### Anything else we should know?

I also tried to install different versions of obs-studio but the problem persisted.

**Comment by mihawk90** [comment] 2024-06-28 21:37
1. You should not put Fedora in the title when you're not actually on Fedora
2. How to get the option for Virtual Camera is in the [Install Instructions](https://github.com/obsproject/obs-studio/wiki/install-instructions#linux:~:text=For%20virtual%20camera%20support%2C%20you%20need%20the%20v4l2loopback%20kernel%20module%20installed.)
3. This is a support request, not a bug.

**Comment by Rondosvalle** [comment] 2024-06-28 21:50
> 1. This is a support request, not a bug.
> 2. How to get the option for Virtual Camera is described in the [Install Instructions](https://github.com/obsproject/obs-studio/wiki/install-instructions#linux:~:text=For%20virtual%20camera%20support%2C%20you%20need%20the%20v4l2loopback%20kernel%20module%20installed.).
> 3. You should not put Fedora in the title when you're not actually on Fedora. Nobara doesn't use the Fedora package so if after installing `v4l2loopback` you are still not getting the option, the Nobara support channels are likely your best bet.

I apologize for the inaccuracies, thank you

**Comment by mihawk90** [comment] 2024-06-28 21:54
Is it working for you then? Note that after installing the package you might have to wait a couple of minutes and then reboot for OBS to be able to find and load the Kernel module.

**Comment by Rondosvalle** [comment] 2024-06-28 21:55
I've installed the pakage and rebooted the system but it's not working

**Comment by mihawk90** [comment] 2024-06-28 22:03
OK, in that case it's better to drop by our support channels (namely [Discord](https://discord.gg/obsproject) since it's the fastest), as it's more effective in providing support and GitHub issues aren't used for support requests.

**Comment by Rondosvalle** [comment] 2024-06-28 22:06
All right, thank you for helping me!

**Comment by RytoEX** [comment] 2024-06-29 05:16
Closing per above.

**Closed by RytoEX** 2024-06-29 05:16 UTC
