### ISSUE TITLE
Using OBS on dual monitor setups with a vertical one is buggy.

### ISSUE THREAD

**Issue by Boymann** [obsproject/obs-studio#4665] opened 2021-05-07 08:54 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/_MYhluw6wGvKYiIe

### Expected Behavior

The OBS window to fit the vertical monitor. And not resize when clicking a source.

### Current Behavior

When clicking a source the OBS window resizes itself to stretch into the 2nd monitor which is horizontal.

### Steps to Reproduce

1. Open OBS on any screen
2. Pull to the top of a vertical monitor so it resizes itself onto the full monitor
3. Click any source
...

**Comment by WizardCM** [comment] 2021-05-07 08:59
Duplicate of #3476

**Closed by WizardCM** 2021-05-07 08:59 UTC
