### ISSUE TITLE
The border of camera has black area, 640 * 480

### ISSUE THREAD

**Issue by SongAdonis** [obsproject/obs-studio#5345] opened 2021-09-29 09:54 UTC
### Operating System Info

macOS 11.5

### OBS Studio Version

27.1.0

### OBS Studio Log URL

https://obsproject.com/logs/jCLU-FKS_e2Z8FsS

### Expected Behavior

When I set preset of camera  to 640 * 480, The camera rendering area is full，and there is no black area.

### Current Behavior

If I set the preset of camera to 1280 * 720, everything is ok,  but if I set it to 640 * 480, the border of camera will be black. and I 

### Steps to Reproduce

1.add a video capture device source.
2.Set the preset to 1280 * 720 . 
3.After screen appears, change preset to 640 * 480
4.There will be black area in the border of camera

### Anything else we should know?

![image](https://user-images.githubusercontent.com/91406043/135246361-022d457b-3309-4331-94db-0918caad0727.png)
This is a screenshot

**Comment by RytoEX** [comment] 2021-09-29 10:09
This is because the placeholder image for the virtual camera is 1920x1080 pixels (16:9).  Setting your output to 640x480 (4:3) means that the placeholder image will require black bars to fill out the aspect ratio.

Closing this is as this behavior is by design.

**Closed by RytoEX** 2021-09-29 10:09 UTC

**Comment by SongAdonis** [comment] 2021-09-29 10:56
But If I donot choose the virtual camera as device . I choose webcam , the black borders are still  in
@RytoEX 
![image](https://user-images.githubusercontent.com/91406043/135255578-8a9c88c8-2ab8-4c51-870c-33eaa6715b46.png)

**Comment by RytoEX** [comment] 2021-09-29 11:20
Someone more familiar with the mac-avcapture plugin will have to comment, but it looks like the device is transmitting black bars.

@PatTheMav  ?

**Comment by PatTheMav** [comment] 2021-09-29 17:09
I've tried to reproduce the issue but wasn't able to - does this happen with a specific camera or also with the built-in Facetime camera?

In my tests the source resolution and aspect ratio always changed with the selected resolution of the capture source (also switched between 4:3 and 16:9 ratios without any letterboxing appearing). Also when setting a fixed transform the padded areas will be transparent, so that's not it either.

**Comment by SongAdonis** [comment] 2021-09-30 01:34
All cameras both have this problem include Facetime.

Maybe the reason is my FeiShu is running?   FeiShu is a  conferencing software.  but when I kill FuiShu, the black borders are still in. And I try to use another colleague’s computer to capture camera in obs (640 * 480) and it is reproduced. One  will not have problems until the FeiShu is being running..

**Comment by SongAdonis** [comment] 2021-09-30 01:38
Maybe someone can reopen this issue? @PatTheMav @RytoEX

**Comment by Fenrirthviti** [comment] 2021-09-30 20:09
It sounds like this is being caused by third-party software, if it only seems to happen after that software has been run. I would recommend reporting the issue to the FeiShu developers, as we aren't able to replicate on our end without that software installed, but I will defer to Pat if he thinks this might be something we can fix.
