### ISSUE TITLE
Dropped and duplicated frames during recording

### ISSUE THREAD

**Issue by qo4on** [obsproject/obs-studio#7151] opened 2022-08-20 14:04 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/G6qYS2I7IVO09_JV

### Expected Behavior

No dropped frames. No duplicated frames.

### Current Behavior

Dropped and duplicated frames during recording.

### Steps to Reproduce

1. Set the monitor to 1920x1080, 60 fps.
2. Start recording OBS with NVENC at 1920x1080, 60 frames per second.
3. Play the test video using your player, for example mpv.
https://user-images.githubusercontent.com/35609308/185750048-d48263b7-1a26-4d82-8e3a-b00ad3fb49df.mov
4. Stop OBS recording and play recorded video manually frame by frame.
You will clearly see that some frames are missing and some are duplicated.

### Anything else we should know?

This is not a video player issue, many users have confirmed this behavior in OBS discord.

**Comment by Fenrirthviti** [comment] 2022-08-20 16:31
Duplicate of https://github.com/obsproject/obs-studio/issues/6571

**Closed** 2022-08-20 16:31 UTC

**Comment by qo4on** [comment] 2022-08-20 19:10
> Duplicate of #6571

Are you sure that they are talking about the same issue? I can't reproduce it using their Steps to Reproduce from https://github.com/obsproject/obs-studio/issues/6571.
My issue has clear Steps to Reproduce, so everyone can record a video and share it to prove that they have the same problem.
