### ISSUE TITLE
OBS fails to open at all in Manjaro

### ISSUE THREAD

**Issue by grayson676** [obsproject/obs-studio#9014] opened 2023-06-04 05:03 UTC
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2-2(linux)

### OBS Studio Log URL

obs fail to open, no crash log is generated

### OBS Studio Crash Log URL

obs fails to open, no crash log is generated

### Expected Behavior

obs should open

### Current Behavior

obs crashes with segmentation fault

### Steps to Reproduce

1. try opening obs either via CLI or GUI

### Anything else we should know?

the output of obs --verbose is `debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Command Line Arguments: --verbose
info: Using EGL/X11
info: CPU Name: AMD Ryzen 5 5600X 6-Core Processor
info: CPU Speed: 2200.000MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 31978MB Total, 7205MB Free
info: Kernel Version: Linux 6.1.30-1-MANJARO
info: Distribution: "Manjaro Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
debug: found alternate keycode 62 for OBS_KEY_SHIFT which already has keycode 50
debug: found alternate keycode 105 for OBS_KEY_CONTROL which already has keycode 37
debug: found alternate keycode 129 for OBS_KEY_NUMPERIOD which already has keycode 91
debug: found alternate keycode 190 for OBS_KEY_REDO which already has keycode 137
debug: found alternate keycode 208 for OBS_KEY_VK_MEDIA_PLAY_PAUSE which already has keycode 172
debug: found alternate keycode 215 for OBS_KEY_VK_MEDIA_PLAY_PAUSE which already has keycode 172
debug: found alternate keycode 218 for OBS_KEY_PRINT which already has keycode 107
debug: found alternate keycode 231 for OBS_KEY_CANCEL which already has keycode 136
info: Qt Version: 6.5.0 (runtime), 6.4.2 (compiled)
info: Portable mode: false
debug: Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
debug: Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.2-2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
debug: Created EGLDisplay 0x55bfd27d30b0
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 3070/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 530.41.03, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
        base resolution:   1680x1050
        output resolution: 1152x720
        downscale filter:  Bicubic
        fps:               60/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
debug: ---------------------------------
debug: Loading module: decklink-captions.so
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
debug: ---------------------------------
debug: Loading module: decklink-output-ui.so
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
debug: ---------------------------------
debug: Loading module: decklink.so
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
debug: ---------------------------------
debug: Loading module: frontend-tools.so
debug: ---------------------------------
debug: Loading module: image-source.so
debug: ---------------------------------
debug: Loading module: linux-alsa.so
debug: ---------------------------------
debug: Loading module: linux-capture.so
debug: ---------------------------------
debug: Loading module: linux-jack.so
debug: ---------------------------------
debug: Loading module: linux-pipewire.so
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
debug: ---------------------------------
debug: Loading module: linux-pulseaudio.so
debug: ---------------------------------
debug: Loading module: linux-v4l2.so
debug: ---------------------------------
debug: Loading module: obs-ffmpeg.so
info: NVENC supported
debug: VAAPI: Initializing display in vaapi_device_h264_supported
debug: Libva: VA-API version 1.18.0
debug: Libva: Trying to open /usr/lib/dri/nvidia_drv_video.so
debug: Libva: Found init function __vaDriverInit_1_13
[1]    431777 segmentation fault (core dumped)  obs --verbose`

**Comment by Fenrirthviti** [comment] 2023-06-04 07:06
Please provide a gdb backtrace of the crash. OBS only generates its own crash logs on Windows currently.

**Comment by tytan652** [comment] 2023-06-04 07:27
Duplicate of #8056

**Closed by tytan652** 2023-06-04 07:27 UTC
