### ISSUE TITLE
Display capure consistently fails to capture frames [AMD 10-bit]

### ISSUE THREAD

**Issue by Vectrobe** [obsproject/obs-studio#4164] opened 2021-01-30 15:14 UTC
Operating system and version: Windows 10 20H2 19042.746 120.2212.551.0
OBS Studio version: 26.1.1

Display capture currently doesn't work correctly, either with modern AMD drivers, the 5700XT, a 3440x1440 144Hz display, or with the latest public builds of windows, I haven't been able to determine which of the ones it is.

I reported it back at the start of january on the [forums](https://obsproject.com/forum/threads/20h2-blocking-bug-desktop-capture-can-only-capture-the-cursor-and-only-a-single-desktop-frame-or-otherwise-black.136532/); however it was never touched on. The report is as follows;

> Desktop capture can only capture the cursor and only a single desktop frame, or otherwise just a blank frame. Similarly, window capture does not work in auto mode (BitBlt), only WGC works and you must manually set it to that for every window capture. Note also that capture cursor does not function on window capture, at all.
> 
> I've checked the logs with the discord bot, no problems are reported other than a few false-warnings.
> 
> There is however, one trick/hack I've discovered that gets desktop capture to work, and its to have an active window GCI capture just below display capture, and to then hide and unhide desktop capture and it will proceed to capture desktop frames correctly(?). But only so long as you perform this exact hack on every OBS start or when creating a new desktop capture.
> 
> I would hazard a guess that desktop capure is using BitBlit by default, of which nolonger functions in 20H2, thus it doesnt capture frames unless tricked into WGC mode.

I expect https://github.com/obsproject/obs-studio/pull/4140 will fix this. No, this is not a laptop, nor are there multiple GPUs present at this time.

**Comment by energizerfellow** [comment] 2021-01-30 15:25
From the OBS log in the forum post, you're on AMD GPU driver 20.11.3, which appears to have been pulled by AMD (you can find it in a Google search, but no longer shows up if you use AMD's regular driver download workflow).

See if the issue corrects itself if you downgrade to 20.11.2, which is the last WHQL-certified release.

**Comment by Vectrobe** [comment] 2021-01-30 15:28
Its been identical through to 21.1.1, I don't expect 20.11.2 will change it but I'll try anyway.

**Comment by Vectrobe** [comment] 2021-01-30 15:47
nah, not really any improvement, its slightly better at _looking_ like its working, but it very obviously isn't when you move a window around or scroll up and down.

10bpc might also be a factor?

**Comment by energizerfellow** [comment] 2021-01-30 16:37
> 10bpc might also be a factor?

Likely a factor, yes. Try regular 8-bit.

**Comment by WizardCM** [comment] 2021-01-31 03:29
Please fill in the issue template.

**Comment by Vectrobe** [comment] 2021-02-02 11:52
> Please fill in the issue template.

Which part do you need me to re-explain? display capture isn't capturing frames, in admin mode.

> ## Platform
> Operating system and version: Windows 10 20H2 19042.746 120.2212.551.0
> OBS Studio version: 26.1.1
> GPU: RX 5700XT drivers 20.11+ (20.11.2, 20.11.3, 21.1.1 tested, consistent behaviour)
> Display: AOC U34G2G4R3, displayport 1.4, 3440x1440 144Hz 10bpc
> 
> ## Expected Behaviour
> Display capture to capture frames, and at the required framerate
> 
> ## Current Behaviour
> Cursor is captured, display frames are not, or not consistently. Often shows as a black display, or frozen display.
> The cursor hovering over window elements can trigger new frame updates, but not always, and only for that one frame per element.
> Element render misses are mostly avoided when set to fractional FPS, to the display's exact FPS (144/1), but continued capture still does not happen.
> 
> A trick workaround that forces consistent frame capture is to have a window capture source hidden behind the display capture (ie above it in the list), hide the display capture and unhide it. The display capture will then continue to work as it should so long as that window capture is still valid, though it may continue to work afterwards, so long as it isn't hidden.
> 
> ## Steps to Reproduce
> 1. Install OBS
> 2. Run as administrator
> 3. add display capture
> 4. ## Current Behaviour
> 
> ## Additional information
> BitBlt mode on all other capture methods also does not function, in this case not even hover events can trigger new frames. The cursor again however, is still captured in this mode, making for almost identical behaviour.
> 
> It is highly likely https://github.com/obsproject/obs-studio/pull/4140 will fix the issue, as WGC capture works without any issues.

**Comment by Lyamc** [comment] 2021-02-04 07:14
I can confirm this issue. Also running AMD 5700XT

Mouse is always captured at the specified frame rate, but the desktop is not.

https://user-images.githubusercontent.com/10787681/106857824-901da200-6675-11eb-86de-a1ffedbe2d99.mp4

**Comment by Lyamc** [comment] 2021-02-10 22:20
I downgraded OBS 26.1.1 to version 25.0.8 and I still have the same issue.

I also downgraded my AMD drivers to radeon-software-adrenalin-2020-20.11.2-win10-64bit-nov18 but the issue still remains.

Windows updates perhaps? I'm running the latest available: 10.0.19042 Build 19042


Game capture works
Audio capture works
Window capture works
Display capture doesn't work: mouse will update but everything else will rarely update.

For example: scroll or alt-tab without moving the mouse position and the screen contents will never update.
Move the mouse and the screen will update at about 1fps

Windows Build:
![image](https://user-images.githubusercontent.com/10787681/107580169-05740000-6bab-11eb-9fd6-8361f7406794.png)

**Comment by Lyamc** [comment] 2021-02-10 22:24
SOLVED. Perform a factory reset in the AMD control panel and reboot:

![image](https://user-images.githubusercontent.com/10787681/107580576-a06cda00-6bab-11eb-8fdf-97d88df51576.png)

**Comment by Vectrobe** [comment] 2021-02-12 04:57
> 
> SOLVED. Perform a factory reset in the AMD control panel and reboot:
> 

I would have already done that testing through the driver versions, its not a straight "solution".

What display are you using @Lyamc ? 144Hz? freesync? 10bpc? have you checked that all your settings are correct after resetting?

I have freesync disabled on mine, so its running flat 144Hz, however I'm running full 10bpc including in the global game profile, which means the colour buffer is probably at least RGB10A2 or similar, though that of itself wouldn't explain why BitBlit capture is skipping events, where WGC runs perfectly fine.

**Comment by mufunyo** [comment] 2021-02-12 12:02
> I'm running full 10bpc including in the global game profile, which means the colour buffer is probably at least RGB10A2 or similar

FYI, unless you enable HDR mode in Windows, the DWM will always composite in 8bpc.
https://docs.microsoft.com/en-us/windows/win32/direct3darticles/high-dynamic-range
From that doc:
> Prior to advanced color, the DWM restricted windowed apps to output content at only 8 bits per color channel, even if the display supported a higher bit depth.

The only way to render 10bpc on a 10bpc monitor in SDR mode is to render a DXGI context in exclusive fullscreen (or flip fullscreen) with an R10G10A2 swap chain. Even then it's likely display capture will only supply 8bpc to capture applications for compatibility reasons.

**Comment by Lyamc** [comment] 2021-02-12 16:07
My display settings haven't changed:

![image](https://user-images.githubusercontent.com/10787681/107791763-2b171b80-6d09-11eb-9d48-1c48b43096b1.png)

I also tried disabling/renabling different features like virtual super resolution but it had no effect.

**Comment by Vectrobe** [comment] 2021-02-14 09:06
> 
> 
> My display settings haven't changed. 1080p 16:9 YUV444 and 10-bit in AMD control panel. I've been using the same 60Hz monitor before and after.
> 
> I also tried disabling/renabling different features like virtual super resolution but it had no effect.
> 
> Changing the settings to this didn't break OBS either:
> 

What about the 10-bit pixel format under the graphics tab > global graphics > advanced ? this one requires a system reboot to take effect, as it requires the DWM to be fully restarted.

> Even then it's likely display capture will only supply 8bpc to capture applications for compatibility reasons.

This of itself should work just fine, and from the window captures it looks just fine, albeit somewhat dark. Like I mentioned before, it theoretically shouldn't be affecting the capture the way it is (I would expect odd colour corruption _if_ we did), but for the sake of testing configurations that's why I mentioned it.

**Comment by Lyamc** [comment] 2021-02-14 09:09
I’ll rephrase myself: the default after install and reboot was 4:4:4 and 10-bit colour.

I also tried RGB and 12-bit, reboot, and OBS works. Not sure why it stopped working before.

**Comment by Vectrobe** [comment] 2021-02-14 09:12
> 
> 
> I’ll rephrase myself: the default after install and reboot was 4:4:4 and 10-bit colour.
> 
> I also tried RGB and 12-bit, reboot, and OBS works. Not sure why it stopped working before.

the advanced graphics 10-bit pixel format is disabled by default however, is that enabled? its below the anti-aliasing, texture sampling and tessellation mode overrides

**Comment by Lyamc** [comment] 2021-02-15 22:36
Confirmed: when 10-bit support is enabled, OBS has the problem

![image](https://user-images.githubusercontent.com/10787681/107999003-3bdec000-6f9b-11eb-88d7-dc4b459877c5.png)

**Comment by Vectrobe** [comment] 2021-02-16 08:27
well there we go, 10bpc render output support breaks legacy BitBlit for some reason, in a way that it really shouldn't be...

I'm guessing this is a result of a driver override in the DWM, which is resulting in altered render/capture event behaviour, or alternatively something is just failing silently with OBS's capture calls? I haven't exactly had the time or energy to debug the code, let alone build it with https://github.com/obsproject/obs-studio/pull/4140 in place...

Do we have a new release build scheduled?

**Comment by RytoEX** [comment] 2021-02-16 13:03
> well there we go, 10bpc render output support breaks legacy BitBlit for some reason, in a way that it really shouldn't be...
> 
> I'm guessing this is a result of a driver override in the DWM, which is resulting in altered render/capture event behaviour, or alternatively something is just failing silently with OBS's capture calls? I haven't exactly had the time or energy to debug the code, let alone build it with #4140 in place...
> 
> Do we have a new release build scheduled?

@Vectrobe 
Any nightly since #4140 was merged will have that code in it.  Here's the most recent nightly for Windows 64-bit:
https://github.com/obsproject/obs-studio/suites/2045022144/artifacts/41161223

**Comment by Lyamc** [comment] 2021-02-16 16:11
I tested that nightly build: using the new Capture method fixes the issue.

**Comment by Vectrobe** [comment] 2021-02-22 01:35
thanks, using the nightly build and manually switching the display capture method to WGC absolutely fixes the issue, no admin rights required.

I'd suggest we set WGC as the default method for all captures, as I don't see why it shouldn't be. It's the one of the two that's guaranteed to work on all hardware configurations after all. Cant imagine many people running old (unsupported) windows versions would even use OBS anyway...

Are nightly builds supposed to be publicly visible? I'm yet to find anywhere you can get them. Releases has nothing as there's no nightly tag...

**Comment by WizardCM** [comment] 2021-02-22 02:17
> I'd suggest we set WGC as the default method for all captures, as I don't see why it shouldn't be. It's the one of the two that's guaranteed to work on all hardware configurations after all. Cant imagine many people running old (unsupported) windows versions would even use OBS anyway...

For the first release, we're only defaulting to WGC on laptops as it works cross-GPU. There are two remaining issues with WGC: the yellow border (which we'll be able to turn off either in Windows 21H1 or 21H2), and that it disables the hardware cursor (which makes the cursor run at a lower frame rate for the user, making it feel sluggish/laggy).

> Are nightly builds supposed to be publicly visible? I'm yet to find anywhere you can get them. Releases has nothing as there's no nightly tag...

Nightlies can be found by clicking the green check ✔ on commits, or by clicking the Actions tab along the top of the page.

**Comment by Lyamc** [comment] 2021-02-22 02:28
I think it’s fine if the default doesn’t change until those other issues are fixed and some more users test it.

For now, all other capture sources still work regardless of those AMD settings, and if the user has issues they can either change the capture method or they’ll find this thread

**Comment by Vectrobe** [comment] 2021-02-22 15:52
> and that it disables the hardware cursor (which makes the cursor run at a lower frame rate for the user, making it feel sluggish/laggy).

Is this specific to certain games? I haven't seen this occur so far

**Comment by tielqt** [comment] 2021-06-28 13:45
@Vectrobe @Lyamc Kia ora! Has this issue been resolved in public builds and on the latest drivers? If you can test with and without the WGC capture method, that'd be lovely!

**Comment by RytoEX** [comment] 2022-11-02 20:53
As the reporter confirmed that WGC fixes this Issue, we will close this issue.

**Closed by RytoEX** 2022-11-02 20:53 UTC
Labels: Windows, Confirmed
