### ISSUE TITLE
Multiple Media (input) sources are out of sync and delay changes after restarting streams. Cannot use multiple cameras 

### ISSUE THREAD

**Issue by ussah** [obsproject/obs-studio#4301] opened 2021-03-05 12:52 UTC
## Platform
Operating system and version:
Windows 64bit
OBS Studio version:
26.1.1

## Expected Behavior
Multiple video streams are sent with Larix broadcaster using SRT (h.264). 
Video sources are having constant settings and streaming is completed in strong wireless network providing high bandwith and low latency. Video streams are received and shown in sender side set delay (2000ms) . Streams are shooting same high speed occasion such as sport.
 
## Current Behavior
Videos are received and shown but streams are not in sync when using OBS as Media input or VLC input..
When using VLC player both videos are perfectly in sync.

## Steps to Reproduce
1. Setup OBS as SRT streams configurations in Media source or VLC source (SRT caller)
2.Start live streams from Larix cameras (SRT listener)
3.open streams. Delay is inconsistent
4. close & open streams. Delay is inconsistetn and in many cases different than in previous time streams were open.

## Additional information
See  videos showing OBS vs. VL

https://user-images.githubusercontent.com/80106192/110117873-2e5e6e00-7dc2-11eb-8e73-01173f0b2520.mp4

https://user-images.githubusercontent.com/80106192/110117877-2ef70480-7dc2-11eb-83af-05f3fc1bdbe4.MP4

C (version 3.0.12)

**Comment by harfinch** [comment] 2021-06-10 21:24
I've been trying to find a solution to this for a year or so now.  I thought it was a deficiency with SRT.  I never thought to try the SRT feeds outside of OBS.  But you're right, when I play the SRT feeds through ffplay they are in sync - but in OBS they are out of sync.

I'm using Linux OBS version 26.0 - maybe version 27 offers some resolutions to this.

At any rate, I'm just happy to localize the issue with OBS and not SRT and that there is at least one other person having the same issue.

**Comment by harfinch** [comment] 2021-11-02 21:15
I kind of abandoned this idea - but maybe it will become useful for me some where later down the road.  I mention that because I did find a solution, but I really only tested in a simple test environment.  Does it scale?  I really don't know.

Have a look at the GStreamer plugin for OBS.  The post starting at:

https://obsproject.com/forum/threads/receive-srt-stream-within-obs.129698/post-535914

really seemed to help.  Maybe it'll help you.

**Comment by baciucristian** [comment] 2023-01-27 15:12
Any updates? RTSP Camera feed have 2000ms in VLC Media Source and even more on Media Source. GStreamer are not an option, because CPU usage skyrockets when using it.

**Comment by Fenrirthviti** [comment] 2023-01-27 19:42
OBS does not currently provide any kind of sync or latency promises between multiple media sources, even if it's the same source. This is currently expected, as we don't have any kind of timestamp checking implemented, and as far as I am aware, no one has looked in to it. Since this is a feature request for sources to sync, I will close this as working as designed. There are multiple open requests on our [ideas page](https://ideas.obsproject.com/) to request timestamp syncing of various kinds.

**Closed by Fenrirthviti** 2023-01-27 19:42 UTC
