### ISSUE TITLE
Full Screen Recordings Freeze macOS Screen Capture (Display Capture)

### ISSUE THREAD

**Issue by michaelgambold** [obsproject/obs-studio#7368] opened 2022-09-13 11:46 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/_d1-Ofl1J8msZbJg

### Expected Behavior

Recording full screen "Display Capture" should not freeze after a few seconds.

### Current Behavior

When using "macOS Screen Capture" Source recording works as expected until you go full screen. After this the video recording runs for a few seconds then freezes, audio recording continues as expected. This occurs in testing with Chrome + Youtube and Plex (not full screen works correctly but then freezes when going full screen).

What's really interesting is that if you use a "Window Capture" for the Chrome tab and go full screen the recording is black when the window is not "in focus" but when you watch the full screen video it records as expected (doesn't freeze).

The legacy "Display Capture" does freeze and works as expected.

### Steps to Reproduce

1. Add macOS "Display Capture" source
2. Start recording screen
3. Open youtube video in chrome
4. Make video full screen
5. Stop recording
...

**Comment by PatTheMav** [comment] 2022-09-13 15:23
Could you please run `log stream --system | grep "replayd"` in a Terminal while reproducing the issue and upload the output as a txt file on a comment?

**Comment by jcm93** [comment] 2022-09-13 16:55
If this is the same issue I came across and mentioned in discord recently, @gxalpha confirmed it and I think figured out the source of the issue. it was specifically an issue with macOS Screen Capture Display capture on 12.x with any application or window in fullscreen. Window captures weren't affected in my tests, and I don't think application captures were. Behavior changes in 13.

**Comment by michaelgambold** [comment] 2022-09-13 23:49
@PatTheMav Please find requested output attached

[replayd output.txt](https://github.com/obsproject/obs-studio/files/9561489/replayd.output.txt)

**Comment by PatTheMav** [comment] 2022-09-14 11:08
OK, an important detail seems to be that `replayd` reports no issues (frames are supposedly captured just fine) but there are no frame updates arriving in OBS.

I've also replicated a behaviour I found debugging another issue: The recording is updated if the cursor is moved, but _only if the cursor is hidden_. If the cursor is set to be displayed, no movement will update frames.

**Comment by michaelgambold** [comment] 2022-11-09 04:52
After the release of MacOS 13 I tried out the "macOS Screen Capture" source again it does not freeze whilst recording full screen anymore.

**Comment by Knownerd** [comment] 2022-11-12 21:19
For me, it freezes in longer periods, let's say 30 min. The legacy capture doesn't freeze, but it is depreciated and had a delay of nearly 1s.

**Comment by PatTheMav** [comment] 2022-11-22 22:39
We are aware of such issues that are due to a bug in macOS 13.0 - fixes are supposed to come with macOS 13.1, so we have to wait for that update to be released.

**Comment by cboxgo69** [comment] 2022-12-16 13:51
I have livestreams freeze after about 20 minutes using macOS Window Capture.  Is this issue with all macOS Screen Capture types?  Is this issue (Display Capture) fixed with the macOS 13.1 update or is there an OBS update that must be applied as well?

**Comment by gxalpha** [comment] 2022-12-16 13:59
>Is this issue with all macOS Screen Capture types?

I believe the issues where the "macOS Screen Capture" source would randomly freeze apply to all capture types.

>Is this issue (Display Capture) fixed with the macOS 13.1 update or is there an OBS update that must be applied as well?

The random-freezing issues currently known with the source are resolved by updating to macOS 13.1, no OBS update is required. If you run into the problem on macOS 13.1, please let us know.

**Comment by gxalpha** [comment] 2022-12-16 14:03
As for what this issue was originally about, this looks like it was because of our Display Capture workaround on macOS 12.
Because of all the problems, we have removed the "Display Capture" option from the "macOS Screen Capture" source on macOS 12, and recommend either using the old "Display Capture" or updating to macOS 13.

As such, I'm going to close this issue.

If anyone comes across any other problems (freezing, etc) with the macOS Screen Capture source:
- Update macOS to 13.1
- If it still occurs, please open a new bug report (preferably having gone through our support channels first)

**Closed by gxalpha** 2022-12-16 14:03 UTC
Labels: macOS, Confirmed

**Comment by matteolavaggi** [comment] 2023-08-10 18:48
Hi, i've the same problem with OSX 13.4 . Using the Mac OSX Screen Capture result in a screenshoot of the desktop background recorded , audio work as exepcted. The video freeze immediatly, like we try to record an image instead the screen. I'm only able to get a video ouptu using the screen capture from the obsolete menù.

**Comment by gavink97** [comment] 2023-10-01 06:16
I'm experiencing the same issue (Where the video freezes) on Apple Silicon OSX 13.6 using MacOS Screen Capture to capture my display.

Deleting the MacOS Screen Capture Source & creating a new one seemed to solve the issue.

To reproduce the source freezing on the corrupted MacOS Screen Capture simply restart OBS and the source will be frozen.

```
gavinkondrath@Gavins-MacBook-Pro ~ % log stream --system | grep "replayd"
2023-10-01 15:06:53.840529+0900 0x313e8b   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:900
2023-10-01 15:06:53.841295+0900 0x313e8b   Default     0x0                  28860  0    replayd: (SkyLight) server port 0x00003a03, session port 0x00003a03
2023-10-01 15:06:53.841759+0900 0x313e8b   Activity    0x2bd042             28860  0    replayd: (TCC) TCCAccessRequest() IPC
2023-10-01 15:06:53.843630+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPRecordingManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:1139
2023-10-01 15:06:53.843836+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] +[SCCaptureSession fetchShareableContentWithOption:windowID:withCompletionHandler:]:724
2023-10-01 15:06:53.846605+0900 0x31419e   Default     0x0                  28860  0    replayd: (SkyLight) [com.apple.SkyLight:default] New connection 0x99533 main
2023-10-01 15:06:53.857821+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]_block_invoke:907 complete
2023-10-01 15:06:53.895402+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:900
2023-10-01 15:06:53.895564+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPRecordingManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:1139
2023-10-01 15:06:53.895703+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] +[SCCaptureSession fetchShareableContentWithOption:windowID:withCompletionHandler:]:724
2023-10-01 15:06:53.900868+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]_block_invoke:907 complete
2023-10-01 15:06:53.926690+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:900
2023-10-01 15:06:53.926838+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPRecordingManager fetchShareableContentWithOption:windowID:withCompletionHandler:]:1139
2023-10-01 15:06:53.927083+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] +[SCCaptureSession fetchShareableContentWithOption:windowID:withCompletionHandler:]:724
2023-10-01 15:06:53.931722+0900 0x31419e   Default     0x0                  28860  0    replayd:  [INFO] -[RPConnectionManager fetchShareableContentWithOption:windowID:withCompletionHandler:]_block_invoke:907 complete

```

**Comment by Vaytrex** [comment] 2023-10-04 12:10
tested with OBS 30 beta3 still freezing

**Comment by jnpdx** [comment] 2023-11-03 20:39
I've seen some evidence of this issue occurring in 13.6.0 on a separate app I'm working on using SCK. Is it possible that this 13.0 bug has returned?

**Comment by jcm93** [comment] 2023-11-03 22:28
> I've seen some evidence of this issue occurring in 13.6.0 on a separate app I'm working on using SCK. Is it possible that this 13.0 bug has returned?

I haven't seen any evidence of the original issue from this thread reappearing.

That said, if you are working on an app using SCK, I'd suggest verifying that the behavior occurs when run outside the Xcode debugger; I myself have an SCK application that fails to record some fullscreen applications if it is currently being run in the debugger.

**Comment by jnpdx** [comment] 2023-11-03 22:32
Thanks -- it's definitely occurring outside of the Xcode debugger, but it's good to know that it may be more susceptible.

In the event that this issue happens, I assume that frames stop getting delivered to `func stream(_: SCStream, didOutputSampleBuffer sampleBuffer: CMSampleBuffer, of outputType: SCStreamOutputType)` completely, right? It's not just that it erroneously reports frames with `idle` as the status?

**Comment by Merdin** [comment] 2023-11-04 23:34
Just wanted to let you know that my macOS Screen Capture source is also freezing after x minutes of recording.

x = random number.

OBS Studio 29.1.3 (64 bit)
MacBook Pro - M2 Pro (16GB)
macOS Sonoma 14.0

**Comment by PatTheMav** [comment] 2023-11-06 21:35
Please refrain from "I have this issue too" comments on GitHub, especially without any logs or helpful information - they do not contribute to resolving the issue, they will not help maintainers to find the root cause of the issue quicker, they will not change the priority of the issue.

What we need instead are clear steps to _consistently_ (that is: the problem occurs at every attempt) reproduce the issue, because without those the issue cannot be investigated or its root causes either fixed or reported to Apple.

**Comment by quantuminformation** [comment] 2024-01-12 21:19
Im on mac 14, so I shouldn't expect mac screen to capture atm? 

I dont see the old display capture
