### ISSUE TITLE
OBS Crashing

### ISSUE THREAD

**Issue by Fargus5** [obsproject/obs-studio#5214] opened 2021-08-28 19:24 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/GT32D8wt5aDPqbem

### OBS Studio Crash Log URL

https://obsproject.com/logs/pdeyxzaMbIvf74tY

### Expected Behavior

I would like to stream a new game....

### Current Behavior

I normally use obs for streaming with little games (like Minion Master)
I actually started to use OBS with "Final Fantasy 15" and OBS doesn't stop to crash... If I close the game... OBS works correctly.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I have a so bad connection: ADSL

**Comment by Fargus5** [comment] 2021-08-28 19:25
[2021-08-28 21-14-13.txt](https://github.com/obsproject/obs-studio/files/7071357/2021-08-28.21-14-13.txt)
[2021-08-28 20-42-16.txt](https://github.com/obsproject/obs-studio/files/7071358/2021-08-28.20-42-16.txt)
[2021-08-28 20-55-24.txt](https://github.com/obsproject/obs-studio/files/7071359/2021-08-28.20-55-24.txt)
[2021-08-28 21-01-28.txt](https://github.com/obsproject/obs-studio/files/7071360/2021-08-28.21-01-28.txt)
[2021-08-28 21-05-43.txt](https://github.com/obsproject/obs-studio/files/7071361/2021-08-28.21-05-43.txt)
[2021-08-28 21-05-57.txt](https://github.com/obsproject/obs-studio/files/7071362/2021-08-28.21-05-57.txt)
[2021-08-28 21-07-10.txt](https://github.com/obsproject/obs-studio/files/7071363/2021-08-28.21-07-10.txt)
[2021-08-28 21-07-47.txt](https://github.com/obsproject/obs-studio/files/7071364/2021-08-28.21-07-47.txt)
[2021-08-28 21-09-39.txt](https://github.com/obsproject/obs-studio/files/7071365/2021-08-28.21-09-39.txt)

**Comment by Fargus5** [comment] 2021-08-28 19:40
[2021-08-28 21-16-04.txt](https://github.com/obsproject/obs-studio/files/7071382/2021-08-28.21-16-04.txt)

**Comment by RytoEX** [comment] 2021-08-28 22:43
This crash is in libcef, which is from the obs-browser plugin.  Since you are using StreamElement's add-on, which replaces the obs-browser plugin files with an older version of libcef.dll than what we ship with OBS, we cannot accept this bug report.  As such, I'm closing this.  Please report the crash to StreamElements.  If you can reproduce this crash in regular OBS Studio without any plugins, feel free to comment and provide a new crash log and corresponding regular log, and we can reopen this if it looks like a bug in current OBS code.

**Closed by RytoEX** 2021-08-28 22:43 UTC

**Comment by Fargus5** [comment] 2021-08-28 22:44
I would like to unistall streamelements plugin... but I don't know how... could u tell me?

**Comment by RytoEX** [comment] 2021-08-28 22:47
> 
> 
> I would like to unistall streamelements plugin... but I don't know how... could u tell me?

Please seek support in either our support channels on Discord or on our forums, or seek support from StreamElements.

https://obsproject.com/help
