### ISSUE TITLE
Cursor is not displayed

### ISSUE THREAD

**Issue by AlamMancera** [obsproject/obs-studio#7547] opened 2022-10-06 20:44 UTC
### Operating System Info

Windows 11

### Other OS

22H2

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/Er6bo_6ukW796AfS

### Expected Behavior

I want the cursor to be displayed in all my programs. When the cursor changes from a pointer (cursor:default) to a text cursor (cursor:text), I want OBS to record it. 

![image](https://user-images.githubusercontent.com/20695185/194410976-fa6fe2a6-c698-4445-8ed2-dffbf1218382.png)

![image](https://user-images.githubusercontent.com/20695185/194411048-e82bccee-83a8-4985-bc8f-6a6319694662.png)

### Current Behavior

Despite the fact that I have the option to show the cursor activated, it disappears and has a kind of "crash". I have seen what happens when the cursor changes from "default" to "Text". It's very annoying because it failed to teach my students where the cursor is, it happens mostly in programs like Visual Studio, word, etc.

see minute 0:35

https://user-images.githubusercontent.com/20695185/194414568-2eac3d93-2a2d-4468-9e69-e0744bbf2e59.mp4

### Steps to Reproduce

1.Using a program that makes the cursor change from "default" to "text"
![image](https://user-images.githubusercontent.com/20695185/194415022-076ec5d1-309f-4175-8cfa-cfe7d61beffc.png)
![image](https://user-images.githubusercontent.com/20695185/194415046-361c5ebc-af74-4358-a0f0-1322753cf3ff.png)

**Comment by RytoEX** [comment] 2022-10-06 20:52
Duplicate of #3129

As a workaround, use WGC Display Capture ("Windows 10 (1903 and up)").

**Closed by RytoEX** 2022-10-06 20:52 UTC
