### ISSUE TITLE
Decklink plugin broken

### ISSUE THREAD

**Issue by MYI-Liva** [obsproject/obs-studio#9059] opened 2023-06-10 09:24 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F374636015396192257%2F1116378939691106415%2F2023-06-08_16-48-40.txt

### OBS Studio Crash Log URL

https://cdn.discordapp.com/attachments/374636015396192257/1116378658777608312/Crash_2023-06-08_16-48-22.txt

### Expected Behavior

Clicking Start on Decklink Output to work for PGM/PVW respectively. 

### Current Behavior

When starting both, the output hangs and stops working. 

When trying to stop the output, OBS crashes. 
This is easily reproduceable.

Discord #windows-support thread: https://discord.com/channels/348973006581923840/374636015396192257/1116378659104772174

This issue forces me to downgrade to 29.0.2 until the issue is solved

### Steps to Reproduce

1. start Decklink Output Preview
2. start Decklink Output Program
3. 
4.
...

### Anything else we should know?

Decklink Card used: BMD Decklink 8K Pro

Crash log:
Unhandled exception: c0000005
Date/Time: 2023-06-08, 16:48:22
Fault address: 7FFB21432140 (c:\users\production\documents\productions\dpg10\obs\obs-plugins\64bit\decklink-output-ui.dll)
libobs version: 29.1.2 (64-bit)
Windows version: 10.0 build 19044 (release: 21H2; revision: 2965; 64-bit)
CPU: AMD Ryzen 9 5950X 16-Core Processor            

(further crash log to be found in Discord as I don't have the url and currently no access to the affected PC)

**Comment by Fenrirthviti** [comment] 2023-06-10 21:30
Added link to crash log. Probably a duplicate of https://github.com/obsproject/obs-studio/issues/8992

**Comment by MYI-Liva** [comment] 2023-06-10 21:39
> Added link to crash log. Probably a duplicate of #8992

their crash description is quite different from mine. As the playout starts. But the wrong one and instantly freezes (the output, not OBS itself). What I mean by "wrong one", its hard to explain. Basically one of them keeps working (I think its PGM) but the other one gets completly confused.

However, OBS stays functional until I decide to stop the output again, thats the moment it crashes. But with an error message, not like in your described issue case "hard locking".

**Comment by Fenrirthviti** [comment] 2023-06-10 21:40
The crash stack is identical, regardless of how it's triggered.

**Comment by gxalpha** [comment] 2023-06-15 19:35
Duplicate of https://github.com/obsproject/obs-studio/issues/8992

**Closed by gxalpha** 2023-06-15 19:35 UTC
