### ISSUE TITLE
MS Teams App in MAC see only red rectangle / Zoom and Teams in Browser works

### ISSUE THREAD

**Issue by bicmac** [obsproject/obs-studio#8157] opened 2023-01-27 08:07 UTC
### Operating System Info

macOS 13

### Other OS

Intel Based IMAC with MAX OS 13.1

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/3zUB1ZYrkECD65vr

### Expected Behavior

Expected is that I see camera picture in MS Teams App provided by OBS Studio virtual Cam

### Current Behavior

I see only a red rectangle as picture in MS Teams App if I choose OBS Virtual Cam as Camera Source in MS Teams App. 
In Zoom and MS Teams in google Chrome Browser its works. Only Teams App makes Trouble and don't wanna show that Camera Source. I tried also to reinstall the Teams App but no success.
It was working with the version before upgrade.

### Steps to Reproduce

1. Start OBS Studio and start virtual Camera
2. Open MAS Teams App on MAC OS and choose OBS Virtual Cam as source, you see only a red rectangle
3.
...

**Comment by Fenrirthviti** [comment] 2023-01-27 08:15
Duplicate of https://github.com/obsproject/obs-studio/issues/8039

**Closed by Fenrirthviti** 2023-01-27 08:15 UTC

**Comment by bicmac** [comment] 2023-01-27 08:35
@Fenrirthviti thx for closing and refenercing to the existing Bug. But i donbt understand the solution. I'm not so good in using Github and PR versions. So can you maybe explain me how i get my OBS studio running again?

**Comment by gxalpha** [comment] 2023-01-27 08:44
Use OBS 28.1.2 until version 29.0.1 is released
