### ISSUE TITLE
Update from Version 28.1.2 to 29.0.0 Didn't Change Version Number in Windows

### ISSUE THREAD

**Issue by ourichermath** [obsproject/obs-studio#8034] opened 2023-01-10 04:56 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0 non-beta

### OBS Studio Log URL

NA

### Expected Behavior

After updating from within OBS Studio 28.1.2 to 29.0.0, the version number showing in Windows' Settings > Apps > OBS Studio should say 29.0.0 just like it does in the app.  Ditto for running winget upgrade.  Also, this form only offers 29.0.0-beta3 as an option instead of just plain 29.0.0 (which I assume I installed since there's no indication of betaness anywhere).

### Current Behavior

OBS says I've got 29.0.0, but Windows (and winget) say I still have 28.1.2.

### Steps to Reproduce

1. From within OBS, check for updates and tell it to update
2. Check Windows Settings > Apps > OBS Studio and see that the version number hasn't updated
3. Run winget upgrade and see that there's an upgrade from 28.1.2 to 29.0.0 available, even though it's on 29.0.0
...

**Comment by WizardCM** [comment] 2023-01-10 04:59
This is a known issue due to our updater not touching the elements of the registry created by the installer.

I thought we already had a ticket open for this, but I am having trouble finding it.

**Comment by shiina424** [comment] 2023-01-10 05:03
Duplicate of [#2897](https://github.com/obsproject/obs-studio/issues/2897)

**Comment by WizardCM** [comment] 2023-01-10 05:08
Duplicate of #2897

**Closed by WizardCM** 2023-01-10 05:08 UTC
