### ISSUE TITLE
Media Source not playing AV1 recordings correctly

### ISSUE THREAD

**Issue by jenks6797** [obsproject/obs-studio#10876] opened 2024-06-18 15:17 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/H5C5q45ZaS9GNkw6

### Expected Behavior

Recording should play normally inside a Media Source, and also should be able to set the speed.

### Current Behavior

Recording is very choppy inside Media Source, but works normally in VLC Source. Also, the speed setting doesn't do anything.

### Steps to Reproduce

1. Record video in AV1
2. Add video to Media Source
3. Add same video to VLC Source
4. Video should play normally in VLC Source, but choppy in Media Source (and speed settings should not work either)
...

### Anything else we should know?

![Screenshot 2024-06-18 100103](https://github.com/obsproject/obs-studio/assets/165414625/b8e06b1b-e231-49e7-9dfb-e29c0d8efd4c)

**Comment by flaeri** [comment] 2024-06-18 15:20
Could you upload a 10sec sample file that has the problem described?

**Comment by jenks6797** [comment] 2024-06-18 15:26
It's over 10mb, so I can share a Google Drive link if that works. Here's a video showing the issue: https://drive.google.com/file/d/1hU308mk2jmeCx8h5RXHYE_0LjmeS43ac/view?usp=sharing

And here is the video file that is being played in the clip above: https://drive.google.com/file/d/1RgfiJhTlZXATjWdvRfcC8PnUl5QVwER-/view?usp=sharing

**Comment by RytoEX** [comment] 2024-06-18 17:12
All of your Media Sources have hardware decoding enabled. This seems like a duplicate of #10213, where hardware decoding does not work for AV1 encoded files due to how FFmpeg (and our code) handles selecting a capable AV1 decoder.

**Comment by RytoEX** [comment] 2024-06-18 19:48
Upon further consideration, I am going to close this as a duplicate of #10213. The core issue is the same: hardware decoding of AV1 files does not currently work, so the CPU is used to decode them.

**Comment by RytoEX** [comment] 2024-06-18 19:48
Duplicate of #10213

**Closed by RytoEX** 2024-06-18 19:48 UTC
