### ISSUE TITLE
Warzone Voice Chat Not being picked up

### ISSUE THREAD

**Issue by roast247** [obsproject/obs-studio#7187] opened 2022-08-26 00:10 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

obsproject.com

### Expected Behavior

I expect the new window audio capture to pick up audio sources that come through said window

### Current Behavior

No Voice chat audio is coming through

### Steps to Reproduce

1. open warzone
2. join lobby
3. even though you may be able to hear voice chat normally, the window audio capture will NOT pick up the voice chat audio
...

### Anything else we should know?

Fix it

**Comment by RytoEX** [comment] 2022-08-26 02:31
Warzone uses a separate process for voice chat. Thus, selecting the main Warzone process for Application Audio Capture does not capture voice chat, because it is handled by a separate process. For now, we only allow processes with visible windows to be selected. If you require capturing specific audio for processes that do not have visible windows, consider using the [win-capture-audio](https://github.com/bozbez/win-capture-audio) plugin or setting up audio routing.

As this is working as designed, I'm going to close this as not a bug.

**Closed by RytoEX** 2022-08-26 02:31 UTC

**Comment by roast247** [comment] 2022-08-26 02:33
> Warzone uses a separate process for voice chat. Thus, selecting the main Warzone process for Application Audio Capture does not capture voice chat, because it is handled by a separate process. For now, we only allow processes with visible windows to be selected. If you require capturing specific audio for processes that do not have visible windows, consider using the [win-capture-audio](https://github.com/bozbez/win-capture-audio) plugin or setting up audio routing.
> 
> As this is working as designed, I'm going to close this as not a bug.

win-capture-audio does not pick up the audio as well. there is literally a discord regarding the issue with win-capture-audio
