### ISSUE TITLE
"Display Capture" could not show when resizing with undo

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#5856] opened 2022-01-24 08:32 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

null

### OBS Studio Crash Log URL

null

### Expected Behavior

"Display Capture" could show when resizing with undo.

### Current Behavior

"Display Capture" could not show when resizing with undo.

### Steps to Reproduce

1. create a scenes
2. create a source of Display Capture
3. decrease its size
4. undo
5. it won't show

### Anything else we should know?

CPU: AMD Ryzen 5 3600
GPU: AMD Radeon RX 580 2048SP

**Comment by WizardCM** [comment] 2022-01-25 00:06
Please include a log. Is this with or without Studio Mode enabled?

**Comment by iesvme** [comment] 2022-01-25 03:32
https://obsproject.com/logs/pAYI14msVBdzco4m
![gif](https://user-images.githubusercontent.com/16969250/150906064-b877373d-c68d-4aa0-bcc1-c79bb3017210.gif)

**Comment by WizardCM** [comment] 2022-01-25 03:38
Duplicate of #5516

**Closed by WizardCM** 2022-01-25 03:38 UTC
