### ISSUE TITLE
OBS does not work with "FujiFilm X Webcam 2" - Screen stays black (Camera: Fujifilm X-T4)

### ISSUE THREAD

**Issue by k3flo** [obsproject/obs-studio#3777] opened 2020-11-26 12:47 UTC
## Platform
Operating system and version: Windows 10 1909 (Build 18363.1198)
OBS Studio version: OBS 26.0.2 (64-bit, windows)

## Expected Behavior
The Webcamdevice "FUJIFILM X Webcam 2" should be usable as a Video Input Device in OBS like a normal USB Webcam.

## Current Behavior
The "FUJIFILM X Webcam 2" can be selected as video source but the screen stays black.
Log says:
13:34:54.728: User added source 'Videoaufnahmegerät' (dshow_input) to scene 'Szene'
13:34:54.733: Videoaufnahmegerät: DecodeDeviceId failed
13:34:54.733: Videoaufnahmegerät: Video configuration failed

"FUJIFILM X Webcam 2" works correctly with Microsoft Teams, Skype, Zoom, etc.

## Steps to Reproduce
1. Install "FUJIFILM X Webcam 2" software
2. Attach Fujifilm Camera to USB Port
3. Select "FUJIFILM X Webcam 2" as video input source in OBS
4. Screen stays black

## Additional information
Discussion: https://obsproject.com/forum/threads/fujifilm-x-webcam.123272/

Log:
13:34:54.728: User added source 'Videoaufnahmegerät' (dshow_input) to scene 'Szene'
13:34:54.733: Videoaufnahmegerät: DecodeDeviceId failed
13:34:54.733: Videoaufnahmegerät: Video configuration failed
13:34:55.292: ---------------------------------
13:34:55.292: [DShow Device: 'Videoaufnahmegerät'] settings updated: 
13:34:55.292: 	video device: FUJIFILM X Webcam 2
13:34:55.292: 	video path: 
13:34:55.292: 	resolution: 1024x768
13:34:55.292: 	flip: 0
13:34:55.292: 	fps: 20.00 (interval: 500000)
13:34:55.292: 	format: MJPEG
13:35:06.937: ==== Shutting down ==================================================

Is there a way to increase the log level? "DecodeDeviceId failed" doesn't seem to be detailed enough.

**Comment by Owletizia** [comment] 2020-12-07 11:22
I'm experiencing the same issue with my windows computer. It works on mac. I wish it will be solved soon.

**Comment by InanimateCrbnRod** [comment] 2021-01-04 00:20
Same here, its been like this for every fuji camera with OBS and Windows since release. The problem is on OBS's side as it works fine in every other software. please release a fix

**Comment by alinegrc** [comment] 2021-01-14 21:40
Same problem here ... First x webcam 2 didn't recognize my fuji, I fialy solved that. But now obs does't works with it ...

**Comment by InanimateCrbnRod** [comment] 2021-01-15 19:40
Solution I've been using is to window capture Zoom in OBS, remarkably there's no noticeable lag and the quality is pretty great. This also let's me record my solo zoom meeting so when I'm editing my streams I can actually cut to just my face in HD quality and then back to the stream. I also have a very capable system though.

**Comment by k3flo** [comment] 2021-01-20 07:54
The best workaround I found is to use XSplit VCam. After chosing "FUJIFILM X Webcam 2" as video source in VCam, you can select "XSplit VCam" as video source in OBS and your are able to use the Fujifilm camera as webcam nativly without window capturing or other hacks. 
Google "XSplit VCam: Lifetime Subscription" to get this tool with an affordable price.

**Comment by piotr-kubica** [comment] 2021-01-22 12:32
Same goes for Fujifilm X-S10. I remember X-T200 working with OBS on Windows without any problems.

**Comment by raphaelreimann** [comment] 2021-02-01 13:23
I experience the same problem. It would be great if native support for Fujifilm X Webcam 2 would be added to OBS.

**Comment by ViorelMocanu** [comment] 2021-02-02 23:49
Please add support for Fujifilm X Webcam 2 into OBS, my X-T4 would make an amazing webcam and I'd love to use your software to record YouTube videos.

**Comment by piotr-kubica** [comment] 2021-02-04 08:32
Yesterday downloaded OBS version: 26.1.1 (released: January 6th) and Fujifilm X Webcam latest version: 2.1 (released February 3rd 2021) and it works just fine 👍

**Comment by sozodennis01** [comment] 2021-02-04 17:05
Yup! I can confirm with @piotr-kubica that OBS 26.1.1 on Fujifilm X Webcam 2.1 works on Fuji X-T2! Guess it was on Fujifilm to fix something on their end?
![image](https://user-images.githubusercontent.com/50704135/106927691-6baadf80-66e0-11eb-85fe-2737732a4791.png)

**Comment by Fenrirthviti** [comment] 2021-02-04 17:31
I would suspect that was the case, yes. I'll go ahead and close this, but if anyone is still having issues on the 2.1 version of Fujifilm and the latest OBS Studio, please comment and we can re-open.

**Closed by Fenrirthviti** 2021-02-04 17:31 UTC

**Comment by joelmichael** [comment] 2022-03-17 02:33
Am using the latest OBS (v27.2.3) but this does not work with my X100V. Does work with Zoom.

**Comment by PHdeOliveira** [comment] 2022-04-19 18:52
I'm using the latest OBS 24.2.4 and still get a black screen with Fujifilm X Webcam 2 Ver.2.11. Camera is XT-2

**Comment by Fenrirthviti** [comment] 2022-04-19 19:17
OBS 24.x is quite old, and no longer supported, please update to latest (27.2.4), but this is almost certainly going to be an issue on Fujifilm's side.

**Comment by PHdeOliveira** [comment] 2022-04-20 11:50
typo on my part - OBS 27.2.4
