### ISSUE TITLE
Immediate crash upon clicking "Browse" for any file

### ISSUE THREAD

**Issue by thelabcat** [obsproject/obs-studio#10721] opened 2024-05-24 16:39 UTC
### Operating System Info

Other

### Other OS

Fedora 40 x64

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/4bnYCLzFvBkxZAeP

### Expected Behavior

In the properties for an Image or Multimedia source, I click Browse, and am given a file dialog to choose what file I want to be in the source.

### Current Behavior

I click Browse, and OBS crashes.

### Steps to Reproduce

1. Add an Image source to a scene.
2. Leave the name as default.
3. In the configuration dialog, click "Browse"
OBS becomes ded.

### Anything else we should know?

I am using the Flathub version of OBS. The log attached was created in safe mode, but the problem occurs in safe mode and normal mode. I just recently installed the NDI extension, but safe mode disables extensions.

**Comment by derrod** [comment] 2024-05-24 16:44
Yet another duplicate of #10683

**Closed by derrod** 2024-05-24 16:44 UTC

**Comment by thelabcat** [comment] 2024-05-24 21:11
Oh sorry. I tried to search for similar issues but I should have removed the is:open filter. Honestly they should probably not add that by default.
