### ISSUE TITLE
Deinterlacing modes don't work properly

### ISSUE THREAD

**Issue by UsernameBillion** [obsproject/obs-studio#7464] opened 2022-09-25 13:47 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

no log needed..?

### Expected Behavior

Deinterlacing to work

### Current Behavior

I dont know, it just doesnt work properly. I can go through the different modes and sometimes see *something* changing, but it definitely isn't deinterlacing, its just varying levels of janky output. I tried deinterlacing with amarecTV and it works perfectly there, so I dont think the issue is on my end. 

To me it looks like maybe OBS is mistaking where the actual pixel scanlines are and applying the filter wrong This image is with yadif 2x, other modes dont do any better [https://ibb.co/4mDPFrF](url)

### Steps to Reproduce

1. Right click source -> deinterlacing mode

### Anything else we should know?

Specifically I am trying to view PS2 footage through an elgato HD60s, but again it works in amarecTV so I dont see why it can't work in OBS.

**Comment by RytoEX** [comment] 2022-09-27 00:10
Possible duplicate of #6061 or #3402?

**Comment by UsernameBillion** [comment] 2022-09-27 01:12
> Possible duplicate of #6061 or #3402?

Field order and framerate have nothing to do with my issue to my knowledge. I think the deinterlacing options are just generally broken in multiple areas.

**Comment by PatTheMav** [comment] 2022-10-04 19:53
While I understand that it's frustrating if a piece of software doesn't yield expected results, please be more precise in what the issue is, neither "I dont know, it just doesnt work properly" or "varying levels of janky output" allow us to understand the issue, much less investigate it.

Please provide:

* An example file of interlaced video with which the issue is 100% reproducible
* A cross-reference of how the de-interlaced video file _should_ look like according to your own requirements

Going even further, you could look at the code yourself and investigate the possible root cause of the issue and attempt to fix the issue. Even if you're not successful, you could describe your attempts and the insights gained during them, which would also allow other contributors to get to the bottom of the issue quicker.

**Comment by UsernameBillion** [comment] 2022-10-04 20:06
> While I understand that it's frustrating if a piece of software doesn't yield expected results, please be more precise in what the issue is, neither "I dont know, it just doesnt work properly" or "varying levels of janky output" allow us to understand the issue, much less investigate it.
> 
> Please provide:
> 
> * An example file of interlaced video with which the issue is 100% reproducible
> * A cross-reference of how the de-interlaced video file _should_ look like according to your own requirements
> 
> Going even further, you could look at the code yourself and investigate the possible root cause of the issue and attempt to fix the issue. Even if you're not successful, you could describe your attempts and the insights gained during them, which would also allow other contributors to get to the bottom of the issue quicker.

I also get the frustration of some random guy coming and just saying it doesn't work, but the truth is I did look at the .effect files a little but I remember not being able to figure anything out.

As I said, if I had to guess, I'd say that OBS is applying the deinterlace filter on the wrong lines potentially, maybe at a resolution that isnt the real resolution of the source or something, because it looks like it is actually making the deinterlacing lines worse or almost randomly scattered.

If videos help, I'll record some quick samples when I get time - one with deinterlacing off, one with it on, and one from a window capture of amarectv.

**Comment by PatTheMav** [comment] 2022-10-04 20:09
We'd actually need a _source_ video that exhibits the wrong deinterlacing behaviour, that could be an unmodified recording of the input source (retaining full source resolution and interlaced frames), because debugging based on a video is almost impossible if the issue is not considerably easy to pin down.

**Comment by UsernameBillion** [comment] 2022-11-27 01:04
> 

Sorry I took a while, is this good enough? I set the output/canvas to 720x480 30fps so its the same as the source. I spin the camera with no deinterlacing options at first, then I enable yadif 2x top field first and spin again after the pause. You can still see interlacing lines the second time, so something isn't working, but they are notably different in some way, so it is doing *something*.

[Uploading 2022-11-27 00-57-00 - Copy.zip…]()

**Comment by mufunyo** [comment] 2022-11-27 15:30
> 2022-11-27 00-57-00 - Copy.zip

Your source is scaled prior to deinterlacing. Either your capture device is incorrectly configured (incorrect capture resolution) or it is not capable of properly capturing interlaced video.

**Comment by UsernameBillion** [comment] 2022-11-27 16:20
> 

Right. I don't know how I'd fix that, I'm unable to change the resolution in the OBS video capture device properties without it just giving a black screen. 
And its strange that amarectv manages to deinterlace the feed just fine. Even my monitor itself can deinterlace it if I just switch the monitor input. Unfortunately, OBS is the outlier.

But if this truly isn't an issue with OBS somehow, would it be possible to maybe expose the deinterlacing effect resolution options to the user under an advanced tab to counteract issues like this?

**Comment by mufunyo** [comment] 2022-11-27 16:26
> I don't know how I'd fix that, I'm unable to change the resolution in the OBS video capture device properties without it just giving a black screen.

I would recommend going into the OBS support Discord to work out that problem. It could be a pixel format issue or something like that. If it turns out to be a bug in the video capture plugin, you can circle back here with reproduction steps. Right now it looks like the capture driver is scaling the input before it hits OBS, which is blending the interlaced fields together making it impossible to deinterlace properly. Why it would work in Amarec and not OBS is not something I can diagnose from here, so I recommend presenting your problem to a support volunteer on Discord.

**Comment by UsernameBillion** [comment] 2022-11-27 16:51
> 

I didn't have a clue that the video format could change anything other than colors, thank you. I changed to YV12, with bottom field first, and it fixed it. Genuinely no clue how that works. Ill keep all this here incase anyone googles this issue in future.

The only annoyance now is that the resolution wont update automatically, since its bundled in with FPS and color format. Could those options be separated perhaps, or an autoselect: highest/lowest resolution option be added?

![Capture](https://user-images.githubusercontent.com/64720422/204148904-f83e0ba9-b703-45a2-98a8-448c5a29ecbc.PNG)

**Comment by mufunyo** [comment] 2022-11-27 17:16
> The only annoyance now is that the resolution wont update automatically, since its bundled in with FPS and color format. Could those options be separated perhaps, or an autoselect: highest/lowest resolution option be added?

You can submit a feature request to our ideas page: https://ideas.obsproject.com/

Going to close this issue as it seems you have resolved your problem, even if there is a minor annoyance remaining. Glad to see my hunch about pixel formats was correct!

**Closed by mufunyo** 2022-11-27 17:16 UTC
