### ISSUE TITLE
Image Slide Show Source - files in directories are not sorted/ displayed by filename

### ISSUE THREAD

**Issue by verstaerker-583** [obsproject/obs-studio#3619] opened 2020-10-16 16:25 UTC
## Platform

Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 26.0.2

## Expected Behavior

Display pictures sorted by filename.

## Current Behavior

Images added by adding directories are not displayed sorted by name.

## Steps to Reproduce

#!/bin/sh
mkdir test; cd test
wget http://www.markus-mauthe.de/site/assets/files/1046/e1.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e2.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e3.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e4.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e5.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e6.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e7.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e8.jpg
wget http://www.markus-mauthe.de/site/assets/files/1046/e9.jpg
touch -t "200604291400" *.jpg

add test as directory to Image Slide Show

The order I get is:
e8.jpg, e9.jpg, e2.jpg, e3.jpg, e1.jpg, e4.jpg, e5.jpg, e7.jpg, e6.jpg

**Comment by j3n0w** [comment] 2021-03-24 07:54
I have got the same problem / can confirm this.
On 2 different machines running Endeavour OS (Arch based) I can replicate this problem - both with the newest pacman version (obs-studio 26.1.2-2) and with the newest git version from the AUR (obs-studio-git 26.1.2.r186.g01c00cf27-1).
The order of the individual images is random without a pattern (at least I can't find one).
On Windows running version 26.1.1 it is working as intended (3 different machines tested).

**Comment by gxalpha** [comment] 2023-02-04 13:29
There is no code or implication anywhere that the contents would be sorted in any particular order, making this issue is a feature request.
As we don't use GitHub Issues for feature requests, I'm going to close this issue. Please file a feature request at https://ideas.obsproject.com.

**Closed by gxalpha** 2023-02-04 13:29 UTC
