### ISSUE TITLE
Check for updates not working!

### ISSUE THREAD

**Issue by mechamogeo** [obsproject/obs-studio#8124] opened 2023-01-23 02:24 UTC
### Operating System Info

macOS 13

### Other OS

MacBook Pro M1 Ventura 13.1 ARM

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ZPm402aNOEolGeOg

### Expected Behavior

On click at buttons, the check for updates screen need to close and save the response for next obs launch!

### Current Behavior

Clicking in the button has no updating, and the screen is not closed at all

### Steps to Reproduce

1. Open OBS
...

Click in some button at Check for updates screen and see what is going on

### Anything else we should know?

I'm recorded the screen, because the log file doesn't update
https://share.cleanshot.com/KYGsMP6w

**Comment by RytoEX** [comment] 2023-01-23 02:48
Duplicate of #4904

**Closed by RytoEX** 2023-01-23 02:48 UTC
