### ISSUE TITLE
OBS consume all SSD space with logs + 100% CPU core usage because of logging

### ISSUE THREAD

**Issue by t0msk** [obsproject/obs-studio#8397] opened 2023-03-03 13:28 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

Cannot, huge file

### Expected Behavior

It should not spam, or log something like once per 5 seconds (timeout) if it is same issue, but it is logging like every XY milliseconds, like infinite loop.

### Current Behavior

Consuming SSD space with logs in infinite loop (there should be timeout for same logs).

Because of infinite loop of logging I get 100% CPU usage on single CPU core too.

I was recording something and after few hours I got 40 GB log files and my system was running of space on my system drive. So I figured out that OBS is consuming space with logs and when I opened some log file I found that whole log file spammed with:

```
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.318: v4l2-input: /dev/video0: failed to log status
14:19:53.318: v4l2-input: /dev/video0: select timed out
14:19:53.319: v4l2-input: /dev/video0: failed to log status
14:19:53.319: v4l2-input: /dev/video0: select timed out
14:19:53.319: v4l2-input: /dev/video0: failed to log status
14:19:53.319: v4l2-input: /dev/video0: select timed out
14:19:53.319: v4l2-input: /dev/video0: failed to log status
14:19:53.319: v4l2-input: /dev/video0: select timed out
14:19:53.319: v4l2-input: /dev/video0: failed to log status
14:19:53.319: v4l2-input: /dev/video0: select timed out
```

This is beginning of log file if someone is interested:

```
14:19:52.773: Using EGL/X11
14:19:52.774: CPU Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
14:19:52.774: CPU Speed: 3716.279MHz
14:19:52.774: Physical Cores: 4, Logical Cores: 4
14:19:52.774: Physical Memory: 15681MB Total, 2746MB Free
14:19:52.774: Kernel Version: Linux 6.1.10-arch1-1
14:19:52.774: Distribution: "Arch Linux" Unknown
14:19:52.774: Session Type: x11
14:19:52.774: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
14:19:52.775: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
14:19:52.775: Portable mode: false
14:19:52.825: OBS 29.0.2-1 (linux)
14:19:52.825: ---------------------------------
14:19:52.826: ---------------------------------
14:19:52.826: audio settings reset:
14:19:52.826: 	samples per sec: 48000
14:19:52.826: 	speakers:        2
14:19:52.826: 	max buffering:   960 milliseconds
14:19:52.826: 	buffering type:  dynamically increasing
14:19:52.827: ---------------------------------
14:19:52.827: Initializing OpenGL...
14:19:52.880: Loading up OpenGL on adapter Intel Mesa Intel(R) HD Graphics 4600 (HSW GT2)
14:19:52.880: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 22.3.4, shading language 4.60
14:19:52.908: ---------------------------------
14:19:52.908: video settings reset:
14:19:52.908: 	base resolution:   1920x1080
14:19:52.908: 	output resolution: 1920x1080
14:19:52.908: 	downscale filter:  Bilinear
14:19:52.908: 	fps:               30/1
14:19:52.908: 	format:            NV12
14:19:52.908: 	YUV mode:          Rec. 709/Partial
14:19:52.908: NV12 texture support not available
14:19:52.908: P010 texture support not available
14:19:52.912: Audio monitoring device:
14:19:52.912: 	name: Default
14:19:52.912: 	id: default
14:19:52.912: ---------------------------------
14:19:52.919: Failed to load 'en-US' text for module: 'decklink-captions.so'
14:19:52.927: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
14:19:52.934: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:19:52.934: Failed to initialize module 'decklink.so'
14:19:53.089: [pipewire] Available captures:
14:19:53.089: [pipewire]     - Desktop capture
14:19:53.089: [pipewire]     - Window capture
14:19:53.119: NVENC supported
14:19:53.121: VAAPI: API version 1.17
14:19:53.121: FFmpeg VAAPI H264 encoding supported
14:19:53.179: ---------------------------------
14:19:53.179:   Loaded Modules:
14:19:53.180:     text-freetype2.so
14:19:53.180:     rtmp-services.so
14:19:53.180:     obs-x264.so
14:19:53.180:     obs-vst.so
14:19:53.180:     obs-transitions.so
14:19:53.180:     obs-outputs.so
14:19:53.180:     obs-libfdk.so
14:19:53.180:     obs-filters.so
14:19:53.180:     obs-ffmpeg.so
14:19:53.180:     linux-v4l2.so
14:19:53.180:     linux-pulseaudio.so
14:19:53.180:     linux-pipewire.so
14:19:53.180:     linux-jack.so
14:19:53.180:     linux-capture.so
14:19:53.180:     linux-alsa.so
14:19:53.180:     libobs-linuxbrowser.so
14:19:53.180:     image-source.so
14:19:53.180:     frontend-tools.so
14:19:53.180:     decklink-output-ui.so
14:19:53.180:     decklink-captions.so
14:19:53.180: ---------------------------------
14:19:53.180: ==== Startup complete ===============================================
14:19:53.231: All scene data cleared
14:19:53.231: ------------------------------------------------
14:19:53.235: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
14:19:53.235: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
14:19:53.235: pulse-input: Started recording from 'alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_Play__2_000000008582-00.analog-stereo.monitor'
14:19:53.235: [Loaded global audio device]: 'Desktop Audio'
14:19:53.236: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.65) 15.0.0'
14:19:53.236: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
14:19:53.236: pulse-input: Started recording from 'alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_Play__2_000000008582-00.analog-stereo'
14:19:53.236: [Loaded global audio device]: 'Mic/Aux'
14:19:53.245: xshm-input: Geometry 1920x1080 @ 0,0
14:19:53.251: xshm-input: Geometry 1920x1080 @ 0,0
14:19:53.254: [Media Source 'Media Source']: settings:
14:19:53.254: 	input:                   
14:19:53.254: 	input_format:            (null)
14:19:53.254: 	speed:                   100
14:19:53.254: 	is_looping:              no
14:19:53.254: 	is_linear_alpha:         no
14:19:53.254: 	is_hw_decoding:          no
14:19:53.254: 	is_clear_on_media_end:   yes
14:19:53.254: 	restart_on_activate:     yes
14:19:53.254: 	close_when_inactive:     no
14:19:53.254: 	ffmpeg_options:          
14:19:53.280: v4l2-input: Start capture from 
14:19:53.280: v4l2-input: Unable to open device
14:19:53.280: v4l2-input: Initialization failed, errno: No such file or directory
14:19:53.280: xshm-input: Geometry 1920x1080 @ 0,0
14:19:53.284: Failed to open file '/home/tomsk/DSC_2175.JPG': No such file or directory
14:19:53.284: gs_image_file_init_internal: Failed to load file '/home/tomsk/DSC_2175.JPG'
14:19:53.284: [image_source: 'Image'] failed to load texture '/home/tomsk/DSC_2175.JPG'
14:19:53.285: xshm-input: Geometry 1920x1080 @ 0,0
14:19:53.289: v4l2-input: Start capture from /dev/video0
14:19:53.289: v4l2-input: Input: 0
14:19:53.290: v4l2-input: Resolution: 352x288
14:19:53.290: v4l2-input: Pixelformat: BGR3
14:19:53.290: v4l2-input: Linesize: 1056 Bytes
14:19:53.290: v4l2-input: Framerate: -nan fps
14:19:53.290: v4l2-input: /dev/video0: select timeout set to 9223372036854775808 (5x frame periods)
14:19:53.290: PipeWire initialized
14:19:53.291: v4l2-input: Start capture from 
14:19:53.291: v4l2-input: Unable to open device
14:19:53.291: v4l2-input: Initialization failed, errno: No such file or directory
14:19:53.292: xshm-input: Geometry 1920x1080 @ 0,0
14:19:53.295: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: JACK Input Client)
14:19:53.295: 
14:19:53.313: Switched to scene 'Twitch'
14:19:53.317: ------------------------------------------------
14:19:53.317: Loaded scenes:
14:19:53.317: - scene 'Scene':
14:19:53.317:     - source: 'Monitor' (xshm_input)
14:19:53.317:     - source: 'Image' (image_source)
14:19:53.317:     - source: 'Camera' (v4l2_input)
14:19:53.317:     - source: 'Subs' (text_ft2_source_v2)
14:19:53.317:     - source: 'JACK Input Client' (jack_output_capture)
14:19:53.317:     - source: 'Media Source' (ffmpeg_source)
14:19:53.317: - scene 'Zapocet':
14:19:53.317:     - source: 'Screen Capture (XSHM)' (xshm_input)
14:19:53.317:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
14:19:53.317:     - source: 'Screen Capture (PipeWire)' (pipewire-desktop-capture-source)
14:19:53.317:     - source: 'Screen Capture (XSHM) 2' (xshm_input)
14:19:53.317: - scene 'test':
14:19:53.317:     - source: 'Video Capture Device (V4L2) 2' (v4l2_input)
14:19:53.317:     - source: 'Screen Capture (XSHM) 3' (xshm_input)
14:19:53.317: - scene 'Twitch':
14:19:53.317:     - source: 'Screen Capture (XSHM) 4' (xshm_input)
14:19:53.317:     - source: 'cat' (image_source)
14:19:53.317:     - source: 'Follow goal' (linuxbrowser-source)
14:19:53.317: - scene 'Twitch - afk':
14:19:53.317: ------------------------------------------------
```

Here is screenshot of logs:
![image](https://user-images.githubusercontent.com/7276200/222731414-fbe477ff-b804-4b08-9638-73b84f407e27.png)

### Steps to Reproduce

If I start OBS it starts loggining.

**Comment by RytoEX** [comment] 2023-03-03 16:13
Duplicate of #4926

cc @kkartaltepe

**Comment by RytoEX** [comment] 2023-03-03 16:13
Duplicate of #4926

**Closed by RytoEX** 2023-03-03 16:13 UTC

**Comment by t0msk** [comment] 2023-03-03 16:24
> Duplicate of #4926

yes but it is still not fixed after 2 years..

**Comment by RytoEX** [comment] 2023-03-03 16:28
What video capture devices are you using? Are your three vl42_input sources all pointed at different devices?

**Comment by kkartaltepe** [comment] 2023-03-03 16:42
> yes but it is still not fixed after 2 years..

Unfortunately  no one seemed particularly interested in the fix that was proposed or describing their device there. They last described it as a cheap webcam from 15 years ago with broken drivers so there doesnt seem to be much impact of the issue, and those affected can likely upgrade to a webcam from this decade to resolve it and greatly improve their quality at the same time.

I spent some time seeing how other software deals with such broken drivers and have put some comments on the pending PR. But if your drivers are busted and you are using webcams that are older than most processors that could feasibly run OBS it seems like a fairly niche issue. If you really want a fix for special and broken devices you should consider participating in the conversation.
