### ISSUE TITLE
CPU usage increase when Pause and Unpausing recording.

### ISSUE THREAD

**Issue by DarkDuck007** [obsproject/obs-studio#4195] opened 2021-02-06 06:26 UTC
Normal CPU usage when recording is 0.2 to 1% and when I pause and Unpause recording, it shoots up to 15 to 20%
I tried changing the settings, no luck.
It's not the new version, I've experienced this issue for a long time on different versions of OBS Studio.

**Comment by WizardCM** [comment] 2021-02-06 06:26
Duplicate of #3148

**Closed by WizardCM** 2021-02-06 06:26 UTC
