### ISSUE TITLE
TeamViewer: Virtual Camera shows first capture as still frame only

### ISSUE THREAD

**Issue by Sgt-Nukem** [obsproject/obs-studio#4903] opened 2021-06-15 12:35 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/EPHW7pwI0Yzr9kUx

### Expected Behavior

The same as when using OBS Virtual Cam with **Slack, Zoom, Microsoft Teams** (where this works as expected):

A cropped full-motion-video preview of my web cam in their respective options dialogs and when using these apps productively.

### Current Behavior

The preview window in the TeamViewer Extras>Options>Video dialog shows a still image of the first frame it captured when being activated.

Frrom then on it is always showing that first capture as a still image - no full-motion-video whatsoever.

### Steps to Reproduce

1. Start OBS with command line switch '--startvirtualcam'
2. Open TeamViewer, then click on Extras>Options in the menu, then select the Video tab in the dialog and chose "OBS Virtual Camera" as Video source

**Comment by WizardCM** [comment] 2021-06-15 12:46
Unfortunately none of the TeamViewer logs provide any insight into what's going on, so this may be hard to track down. It would not surprise me if this was caused by the same issue as #4243.

**Comment by RytoEX** [comment] 2021-06-15 15:55
Considering TeamViewer is closed source and is the odd one out here, I'd report the issue to them.

**Comment by Fenrirthviti** [comment] 2021-06-16 00:05
Going to close this for now as there isn't a whole lot we can do given TeamViewer is closed source. If their support can provide further details on what we need to look at, we can re-open and investigate further.

**Closed by Fenrirthviti** 2021-06-16 00:05 UTC
Labels: Confirmed, Windows

**Comment by jusmustech** [comment] 2024-12-26 15:38
It is also with VLC
