### ISSUE TITLE
[BUG] ffmpeg nvenc 264&265 b_ref_mode "middle" stalls encode; "disabled" works

### ISSUE THREAD

**Issue by cs9kc** [obsproject/obs-studio#2824] opened 2020-04-28 17:14 UTC
This is a continuation of ticket 2374, found here: https://github.com/obsproject/obs-studio/issues/2374

_Software Versions_
- Operating system and version: Windows 10 Home x64 1909 18363.815
- OBS Studio version: 25.0.4
- NVIDIA Standard driver 445.98 (hotfix for 445.87)
- ffmpeg loads NVENC version 10.0, although the problem was the same on older nvidia drivers that loaded NVENC 9.1

_Expected Behavior_
- When streaming -and- recording locally using both Xaymar's StreamFX and custom ffmpeg output, 
 when "b_ref_mode" is set to "disabled", OBS Studio streams and records properly. 

_Current Behavior_
- When streaming using both Xaymar's StreamFX and custom ffmpeg output with nvenc H264, files stream to Twitch just fine when "b_ref_mode" is set to "middle".  
- When recording locally using both Xaymar's StreamFX and custom ffmpeg output with nvenc H264 and H265, when b_ref_mode is set to "middle", the encode tries to start, but stalls two seconds in.  OBS Studio requires a force close/restart after this happens.

_Steps to Reproduce_
- If using Xaymar's StreamFX w/ffmpeg encoder gui, select "H.264/AVC Nvidia NVENC" or "H.265/HEVC Nvidia NVENC", with lookahead and b-frames set to at least 16 and 3, respectively, files stream and record properly with b_ref_mode set to "disabled", but do not record properly when b_ref_mode is set to "# of b/2" ("middle")
- If using custom ffmpeg output, ensure  rc-lookahead=32 bf=3 b_ref_mode=disabled (or "middle") are included in the arguments passed to the encoder.

Encoder stalls with error: 
[ffmpeg muxer: 'adv_file_output'] Writing file 'P:/OBS/example.mkv'...
[ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for packet data failed
[ffmpeg muxer: 'adv_file_output'] Output of file 'P:/OBS/example.mkv' stopped

_Additional information_
The TL;DR:
This bug is related to an ffmpeg bug discovered almost two years ago, found here:
https://trac.ffmpeg.org/ticket/7303

The devs over at ffmpeg patched in a fix as seen here from the thread above:
https://github.com/FFmpeg/FFmpeg/commit/22844132069ebd2c0b2ac4e7b41c93c33890bfb9

Please see my link to example output and logs from ffmpeg, by "cs9k".

Unfortunately, OBS Studio's muxer still doesn't know what to do with the mismatched dts/pts when recording, so the muxer stalls the encode and obs refuses to stop the recording until force-closed.

I went digging through the OBS code and see where PTS and DTS are looked at, as well where the error "os_process_pipe_write for packet data failed" is thrown for recording output.

https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-mux.c#L394

I am not a programmer, but I hope this may help someone who is workaround the issue until ffmpeg themselves fix the actual issue, instead of bandaid it so it outputs files but still throws over 9000 errors.

**Comment by cs9kc** [comment] 2020-04-28 17:16
[FFMPEG-H264-bframe-ref-mp4-mkv.txt](https://github.com/obsproject/obs-studio/files/4547413/FFMPEG-H264-bframe-ref-mp4-mkv.txt)
[FFMPEG-H265-bframe-ref-mkv.txt](https://github.com/obsproject/obs-studio/files/4547414/FFMPEG-H265-bframe-ref-mkv.txt)
[FFMPEG-H265-bframe-ref-mp4.txt](https://github.com/obsproject/obs-studio/files/4547415/FFMPEG-H265-bframe-ref-mp4.txt)

**Comment by RytoEX** [comment] 2020-04-28 18:13
That FFmpeg commit goes at least as far back as FFmpeg 2.5.  We're currently using FFmpeg 4.2.2.

What happens if you invoke FFmpeg from CLI with the same parameters?

**Comment by cs9kc** [comment] 2020-04-28 18:19
The output that you seek is in the link I posted over on the ffmpeg thread.

ffmpeg used to output unplayable files, but the fix described here allowed for proper output to occur.  ffmpeg still throws errors about DTS/PTS mismatch, but the 'fix' prevents a negative number.

[H264 encode logs.txt](https://github.com/obsproject/obs-studio/files/4547750/H264.encode.logs.txt)

**Comment by RytoEX** [comment] 2020-04-28 18:41
> ffmpeg used to output unplayable files, but the fix described in the ffmpeg thread allowed for proper file output to occur.

But like I said, we're using a version of FFmpeg with the patch you posted.

Rather than reencoding an existing file, I meant invoke FFmpeg to encode AV, like pulling in a webcam and microphone, and using the same parameters as above.  I was wondering if the parameters work in that scenario.

I'll probably need someone else to confirm, but I don't think the mux process actually cares what the PTS/DTS are.  The `os_process_pipe_write` error should not be related to any PTS/DTS mismatch.  I'll ask someone else to weigh in here.

**Comment by Fenrirthviti** [comment] 2020-04-28 18:47
Can you provide a screenshot of the exact settings you're using in custom ffmpeg output mode? I followed your replication steps and it's working perfectly fine for me.

**Comment by RytoEX** [comment] 2020-04-28 18:53
I too attempted to replicate this and recorded a clip just fine.
![image](https://user-images.githubusercontent.com/624931/80525877-e8de4280-895f-11ea-8662-5723d83c25ae.png)

**Comment by Fenrirthviti** [comment] 2020-04-28 18:53
Also, please run this and provide a screenshot of the output:

https://obsproject.com/downloads/OBSDiag.zip

**Comment by cs9kc** [comment] 2020-04-28 19:19
Streaming currently.  I'll run the program at the link and provide output in a little while.

Forgive me if I wasn't clear.  b_ref_mode=disabled works fine, always has

b_ref_mode=middle stalls the recording in OBS Studio.  See my above txt file for the output from ffmpeg itself.

**Comment by Fenrirthviti** [comment] 2020-04-28 19:25
in your replication steps:

`If using custom ffmpeg output, ensure rc-lookahead=32 bf=3 b_ref_mode=disabled (or "middle") are included in the arguments passed to the encoder.`

Please try to make sure you are clear with replication, as it makes validation extremely difficult otherwise. You state that it's happening with the mode set to disabled, and then ask us to dig through an external ticketing system to validate this.

**Comment by cs9kc** [comment] 2020-04-28 19:29
Please forgive me for not breaking the sentence above into two different throughts.  I tried to be thorough and provide as much information as I could from ffmpeg itself as well as OBS.  I'm quite new to this process and absolutely don't want to waste your time.  Thank you for bearing with me.

**Comment by Fenrirthviti** [comment] 2020-04-28 19:31
I was able to replicate *an* error, but not the error being claimed. I get something about audio packets, which makes even less sense:

```14:26:02.930: ==== Recording Start ===============================================
14:26:03.270: receive_audio: Error writing packet: Invalid argument```

However, this is likely because an invalid option is being sent. We don't validate anything in custom ffmpeg output mode, if you select incompatible options, it just fails so this is probably normal. I can't replicate the soft-lock condition.

**Comment by cs9kc** [comment] 2020-04-28 19:34
I see.  I will comment again later this afternoon with output from the link above.  Thank you for your time so far.

**Comment by cs9kc** [comment] 2020-04-28 21:16
I took four recordings using the ffmpeg custom output. 

1. nvenc_h264 with b_ref_mode set to "disabled": pixel_format=yuv420p preset=slow profile=high level=4.2 rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 spatial-aq=1 aq-strength=8 bf=3 b_ref_mode=disabled
![01 - ffmpeg h264_nvenc b_ref_mode disabled settings screenshot](https://user-images.githubusercontent.com/64284066/80538591-9efb5980-896b-11ea-9dc9-86d9df8cd50d.jpg)

2. nvenc_h264 with b_ref_mode set to "middle":: pixel_format=yuv420p preset=slow profile=high level=4.2 rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 spatial-aq=1 aq-strength=8 bf=3 b_ref_mode=middle
![02 - ffmpeg h264_nvenc b_ref_mode middle settings screenshot](https://user-images.githubusercontent.com/64284066/80538603-a4f13a80-896b-11ea-9dcd-c8d2e134f143.jpg)

3. nvenc_hevc with b_ref_mode set to "disabled": pixel_format=yuv420p preset=slow profile=main level=4.1 tier=high rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 spatial_aq=1 aq-strength=8 bf=3 b_ref_mode=disabled
![03 - ffmpeg hevc_nvenc b_ref_mode disabled settings screenshot](https://user-images.githubusercontent.com/64284066/80538618-a9b5ee80-896b-11ea-997f-22c74288daa5.jpg)

4. nvenc_hevc with b_ref_mode set to "middle": pixel_format=yuv420p preset=slow profile=high level=4.2 rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 spatial-aq=1 aq-strength=8 bf=3 b_ref_mode=middle
![04 - ffmpeg hevc_nvenc b_ref_mode middle settings screenshot](https://user-images.githubusercontent.com/64284066/80538631-ad497580-896b-11ea-937d-5b3acd2bf7e1.jpg)

Below is a log from the four recordings, in the order above:
[2020-04-28 15-59-32.txt](https://github.com/obsproject/obs-studio/files/4548454/2020-04-28.15-59-32.txt)

Below is a copy of the output from "OBSDiag"
![image](https://user-images.githubusercontent.com/64284066/80536516-1a5b0c00-8968-11ea-9c08-26991d53f7e3.png)

**Comment by Fenrirthviti** [comment] 2020-04-28 22:46
From the log, it looks like in every single test Xaymar's plugin is superseding our ffmpeg encoder. You'll need to go back to him and report this, not an issue with OBS as I cannot replicate the freeze condition. We properly catch the error and encoding fails. I don't know what causes the error, but it's an internal error stating that the parameters are invalid, and that's coming from FFmpeg itself

`15:59:33.237: encoder 'streaming_h264' (StreamFX-h264_nvenc) created`
`16:00:15.586: encoder 'streaming_h264' (StreamFX-h264_nvenc) created`
`16:00:44.183: encoder 'streaming_h264' (StreamFX-h264_nvenc) created`
`16:01:16.642: encoder 'streaming_h264' (StreamFX-h264_nvenc) created`

**Comment by cs9kc** [comment] 2020-04-28 22:56
In my most recent post I ran tests with the OBS Studio built-in ffmpeg, and using H265/HEVC, it did error out with and error that I feel is related to the issue at large.  

I apologize profusely for my lack of conciseness in the beginning.  My ambition got the better of me, and my delivery was "shotgun" at best.  

Related to your most recent comment, I have no problem going back to Xaymar if his encoder uses its own ffmpeg.   (I was under the impression Xaymar's ffmpeg was simply the script that feeds the built in ffmpeg its settings and arguments.  I'll approach him about that.)

**Comment by cs9kc** [comment] 2020-04-29 16:35
"We properly catch the error and encoding fails. I don't know what causes the error, but it's an internal error stating that the parameters are invalid, and that's coming from FFmpeg itself"

Hello again.  I'm not sure if this statement was in regards to my most recent post, or the one before.  

I would like to see this issue re-opened, as I feel that it isn't strictly limited to ffmpeg itself.  The ffmpeg devs consider the issue 'fixed enough for now' as ffmpeg's output files work/play as expected, despite throwing errors.  

I would love to avoid a "we consider it fixed" < - > "It's not our problem, have them fix it" feedback loop, if at all possible; I would like to use b-frames as references when recording using NVENC's h.265/HEVC encoder.

I provided more concise and (hopefully) repeatable errors in my last post from Tuesday, April 28, using the OBS Studio built-in custom ffmpeg output.  Please let me know if I can provide you with any additional logs or output.

**Comment by Fenrirthviti** [comment] 2020-04-29 17:04
At this point we need to see a reduced test case (please provide ALL the details and double or triple check them) on a base install of OBS Studio with no third party plugins where this issue is replicated before we can address it.

**Comment by cs9kc** [comment] 2020-04-29 17:47
Can do!  Fresh install of 25.0.8, new profile, new scene collection, changed as few settings as possible (bt709, 48khz audio, 1080p60 canvas&output), no addons.  The arguments I chose are ones I would use regularly, and ones likely to be used by others.

*I did try H265 b_ref_mode=middle with rc-lookahead=0, with the same result.

Similar test as before: Four encodes, 264 disabled, 264 middle, 265 disabled, 265 middle.  Logs attached.

[OBS Studio 25.0.8 no addons verbose log.txt](https://github.com/obsproject/obs-studio/files/4553336/OBS.Studio.25.0.8.no.addons.verbose.log.txt)

I watched task manager during all four encodes, and this is the result during the fourth (265 middle).
![Task Manager during H265 b-middle](https://user-images.githubusercontent.com/64284066/80628382-e25ed200-8a16-11ea-88b7-efcc5cd22471.PNG)

1. preset=slow profile=high level=4.2 rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 bf=3 b_ref_mode=disabled
![01-H264_b_ref_mode_disabled](https://user-images.githubusercontent.com/64284066/80628245-b2173380-8a16-11ea-8f5f-4e083b1b682f.jpg)

2. preset=slow profile=high level=4.2 rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 bf=3 b_ref_mode=middle
![02-H264_b_ref_mode_middle](https://user-images.githubusercontent.com/64284066/80628248-b3486080-8a16-11ea-9529-b70da36830c2.jpg)

3. preset=slow profile=main level=4.1 tier=high rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 bf=3 b_ref_mode=disabled
![03-H265_b_ref_mode_disabled](https://user-images.githubusercontent.com/64284066/80628251-b3e0f700-8a16-11ea-82d8-00e6c6cb07df.jpg)

4. preset=slow profile=main level=4.1 tier=high rc=vbr_hq maxrate=13M bufsize=20M rc-lookahead=32 bf=3 b_ref_mode=middle
![04-H265_b_ref_mode_middle](https://user-images.githubusercontent.com/64284066/80628255-b3e0f700-8a16-11ea-8f07-35ec1f2f4f3f.jpg)

**Comment by Fenrirthviti** [comment] 2020-04-29 20:17
Can you please edit the post to explain which ones worked and which ones had issues? If I'm seeing right in the log, only test #4 had an issue? Also, what exactly is happening vs what are you expecting to happen? Again, as far as I can tell the error message being presented here:

```
12:33:45.771: pts (256) < dts (512) in stream 0
12:33:45.771: 
12:33:45.771: receive_audio: Error writing packet: Invalid argument
```

is coming from FFmpeg directly, I don't really think there's a whole lot we can do about it if they supposedly already patched it.

**Comment by Fenrirthviti** [comment] 2020-04-29 20:20
Also, in the future, I don't need to see tests that worked correctly. When I'm asking for a reduced test case I want a single, repeatable issue that we can look in to. Dumping 4 different tests and not even explaining the results makes it *extremely* difficult to parse.

I understand that you are frustrated and you just want this to work, but you're making it very, very difficult to get to the heart of the issue here.

**Comment by cs9kc** [comment] 2020-04-29 20:54
There's no frustration on my end.  I've gone without HEVC-b-frames-as-references for over a year now, and I have no problem continuing on without the feature if this issue can not be remedied.  

I've invoked Clarkson's catch phrase "ambitious but rubbish", I fear.  I'll own it.  I misinterpreted your meaning of 'reduced', thinking you wanted as few variables as possible.  I am used to needing cases of what did _and_ didn't work in both my past and current career fields.  I now know that is not the case with code.

Moving on... Tests 1-3 worked correctly.  Test 4 did not.  

Using the settings from test 4 with the Matroska .mkv container produces a similar error to .mp4.

15:31:17.155: pts (17) < dts (33) in stream 0
15:31:17.155: receive_audio: Error writing packet: Invalid argument
15:31:17.155: Output 'adv_ffmpeg_output': **stopping**

The reason I initially linked to an external ticketing system, is that the error OBS Studio's ffmpeg output is producing, is similar to the error that prompted the ffmpeg ticket itself.

The following is for your reference.  I feel that it is related to the issue at hand, and hope it proves to he helpful in some way:

In comment #3 on the ffmpeg bug tracker page, the developer talks about errors related to the DTS/PTS mismatch.
https://trac.ffmpeg.org/ticket/7303#comment:3

This link from comment #3 shows -where- in the ffmpeg code the change was made:
https://github.com/FFmpeg/FFmpeg/blob/6f2a3958cfac135c60b509a61a4fd39432d8f9a9/fftools/ffmpeg.c#L768

This link from comment #3 shows _what_ in the code was changed.
https://github.com/FFmpeg/FFmpeg/commit/22844132069ebd2c0b2ac4e7b41c93c33890bfb9

**Comment by Fenrirthviti** [comment] 2020-04-29 21:10
Have you tested these exact parameters against FFmpeg directly?

It's all well and good that there's claim this was fixed (or hacked around in this case), but did you validate the issue is NOT present when invoking ffmpeg directly using the *exact* parameters you are trying to use in OBS?

**Comment by pkviet** [comment] 2020-04-29 21:36
Hi,
the "fix" you refer to in FFmpeg CLI (FFmpeg/FFmpeg@2284413) is not something we'll consider in obs imo. Timestamps are sensitive stuff, while your case use is quite marginal in our user population.
And it's not a real fix but a hack.
It's more sensible for us to wait for a real fix in avcodec library.
BTW, where was this pointed out that this commit fixed the issue in FFmpeg CLI ? (where did you find this info)

**Comment by cs9kc** [comment] 2020-04-29 21:55
pkviet and Fenrirthviti, thank you both for looking into the issue.  It's unfortunate that the edits made by the ffmpeg dev are a workaround, rather than a repair.  I do hope they remedy the issue properly at some point in the future.

While I can't fully appreciate the complexity of how all of this works, I can imagine, and I thank yall for giving this issue the time and effort that yall have.  I understand that I am a fringe use case, and am perfectly fine with waiting until ffmpeg applies a true fix to the issue.  

Fenrirthviti, I was done working on this before I saw pkviet's post, so I'll leave it here for you all to look at.  It is the output of ffmpeg 4.2.2 using the exact perimeters I used in OBS Studio.  ffmpeg does still throw an error, but the output isn't broken and encodes using h265 b-frame reference mode encode and play properly.
[ffmpeg_log_h265_b_ref_middle.txt](https://github.com/obsproject/obs-studio/files/4554805/ffmpeg_log_h265_b_ref_middle.txt)

I've got nothing else to add to this ticket; close at your leisure.

Thanks again!

**Comment by pkviet** [comment] 2020-04-29 22:00
i checked in ffmpeg CLI that the workaround is called upon indeed. The best course of action is to wait for ffmpeg devs to fix the issue in avcodec/nvenc so https://trac.ffmpeg.org/ticket/7303.

**Comment by Fenrirthviti** [comment] 2020-04-29 22:19
Thanks for the patience. Going to close this as the issue is not in OBS, and it doesn't make sense for us to implement a workaround for a bug in ffmpeg.

**Closed by Fenrirthviti** 2020-04-29 22:19 UTC

**Comment by ValZapod** [comment] 2020-05-01 04:48
That is most certainly Nvidia driver issue (as raw timestamps are from it). And maybe issue is in ffmpeg's non-file output where guessing does not work.

**Comment by cs9kc** [comment] 2020-05-01 19:40
All,
After clarifying the issue to the ffmpeg developers that the problem is NOT with streaming, but with recording/transcoding locally, I am excited to report that they have applied a fix to libavcodec that resolves the timestamp issue.  

I'll give it a test in the Windows nightlies from Zeranoe in the near future.  I am hopeful that the fix works, and if so, will make it into the next official ffmpeg iteration that is due out soon!  

https://trac.ffmpeg.org/ticket/7303#comment:16

**Comment by ValZapod** [comment] 2020-05-01 19:50
So, Nvidia developer, oromit, fixed it. LOL. Lets reopen https://github.com/obsproject/obs-studio/issues/2374

**Comment by ValZapod** [comment] 2020-06-24 04:38
Guys should we reland https://github.com/obsproject/obs-studio/commit/f27a00d266a380312025fa09878023592d9bb612??
