### ISSUE TITLE
Scroll filter works differently in studio mode

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2501] opened 2020-03-15 06:34 UTC
## Expected Behavior

When the scroll filter is set on a source or scene, when a scene transition occurs, the scroll filter should have identical and predictable behaviour whether or not Studio Mode is enabled.  Scroll filters in the destination scene should reset the scene item's origin to a known default state before starting the scroll.  This should be consistent whether or not Studio Mode is enabled.  

## Current Behavior

When a scroll filter is present on a scene item:

With studio mode disabled:  When a scene transition occurs to the scene with the scroll filter, the scene item the filter is on starts out unscrolled and then starts to scroll as expected and desired.

With studio mode enabled:  With any scene currently showing in Program, and the scene with the scroll filter on it is in the Preview pane, the scroll filter ends up already being active in the Preview window, and when you transition to Program, the scroll filter's current position in the preview window is kept and replaces the Program.  This results in a discrepancy in how scroll filter works during transitions between 2 scenes depending on whether or not studio mode is active and breaks expected behaviour.

https://obsproject.com/logs/hNTdEtq7DIvkz-3U

## Steps to Reproduce

1.  Create a new scene collection with 2 scenes, SCENE A, and SCENE B.
2.  In SCENE A load a static image file to fill the canvas.
3.  In SCENE B load a webcam or a different static image and make it fill the canvas.
4.  Apply a scroll filter to the source webcam or image in SCENE B, and set horizontal speed to +100.
5.  Make sure studio mode is disabled.
6.  Switch to SCENE A and wait a few seconds.
7.  Switch to SCENE B and notice that the item starts out not scrolled and then the scroll starts horizontally scrolling.
8.  Repeat steps 6 and 7 several times and notice how the transition to SCENE B always starts out consistently centered and then the scroll starts.  It never starts out where the scroll has already scrolled it partly off screen when the transition occurs.
9.  Switch to SCENE A, then turn studio mode on and set SCENE B in the preview pane.
10.  Watch the item scrolling in the preview window and when it has scrolled for a bit, say halfway off the screen - press the transition button and the two panes swap and the current state of the scroll showing in the preview window ends up getting sent to the program window instead of the scroll filter resetting back to origin on the item it is applied to, causing an inconsistency in how scroll filter works depending on whether or not Studio Mode is enabled.  I haven't tested this with Multiview but it might be a problem there as well.  (I can test it too if desired).

## Additional information

This problem has occurred with all OBS releases for the last year and a half or so whenever I've tested for it, up to and including the current 25.0 rc6 build.  I first encountered this problem with multi-scene setup I have which I use Advanced Scene Switcher to switch from one scene to the next consecutively.

Some of the scenes have scroll filters on one or more items, and I discovered that if studio mode was disabled then whenever a scene transition occurred whether manually or automated with Advanced Scene Switcher, when a scene containing scroll filters is transitioned to, the item starts out unscrolled and then starts scrolling.  But when I activated Studio Mode in OBS for another purpose and did the exact same thing, when scenes where switched manually or with Advanced Scene Switcher - the state of the scroll filter in the Preview Window ended up preserved and kept when the transition occurred, meaning that my scrolling was off kilter randomly by default every time, and ruining the desired effect.

In order to avoid this problem I have had to disable and avoid using Studio Mode as it introduces this inconsistent and unpredictable behaviour.  I believe the behaviour I describe above as desirable would be what most people expect and should be the default behaviour.

The current behaviour in studio mode might be desired by some people for some use cases too perhaps, such as observing where a scroll is presently at and transitioning when it is where they want it to be visually and preserving it.  If both behaviours are desired then there should perhaps be an extra check box on the Scroll filter as to whether or not the scroll position should be reset on transition or a preserved scroll state kept throughout all transitions.  In that case it should still IMHO be consistent regardless of whether or not Studio Mode (or multiview) are in use though.

I've tried to be as detailed as possible but if I've missed anything or any clarifications etc. are needed please don't hesitate to ask here or on Discord.

Thanks in advance to anyone investigating this issue!  Much appreciated!

**Comment by skeletonbow** [comment] 2020-06-18 09:34
Built OBS successfully tonight first time...  Decided to try to fix this one as I figured it might be an easy fix and I was successful.  Problem is that the filter resets the scroll on _show_, but not on _activate__, so when preview gets transitioned to program, the already in-progress scroll which could be half way through it's scroll sequences gets moved to program.

I fixed it by modifying the callback struct at the end of scroll-filter.c and adding a callback for .activate that calls the same function used for .show:

```
struct obs_source_info scroll_filter = {
	.id = "scroll_filter",
	.type = OBS_SOURCE_TYPE_FILTER,
	.output_flags = OBS_SOURCE_VIDEO,
	.get_name = scroll_filter_get_name,
	.create = scroll_filter_create,
	.destroy = scroll_filter_destroy,
	.update = scroll_filter_update,
	.get_properties = scroll_filter_properties,
	.get_defaults = scroll_filter_defaults,
	.video_tick = scroll_filter_tick,
	.video_render = scroll_filter_render,
	.get_width = scroll_filter_width,
	.get_height = scroll_filter_height,
	.show = scroll_filter_show,
	.activate = scroll_filter_show,
};

```
The updated filter now works properly in both studio mode and normal mode with identical results, and it still scrolls in preview in Studio Mode also.

**Comment by skeletonbow** [comment] 2020-06-18 09:36
It might actually be a better idea to rename the function to scroll_filter_reset_state or something and have .show and .activate both call that instead.

**Comment by WizardCM** [comment] 2020-08-25 10:00
@skeletonbow Would you be willing to submit a PR with your fix and tagging this issue in the commit description?

**Comment by skeletonbow** [comment] 2020-08-29 23:56
My PC died yesterday that has all my dev stuff on it, so it might be a while until I get everything back up and running.  I'll come back to this in the future once everything's sorted out here.

**Comment by PatTheMav** [comment] 2020-12-31 16:46
Ping @skeletonbow - hope you were successful in sorting out your issues with your PC. Would be great if you could find some time to write that PR @WizardCM mentioned.. 😉

**Comment by PatTheMav** [comment] 2022-09-29 12:01
Following up on this myself:

* The root cause is that when a scene is selected in Studio Mode, it's `show` event takes place upon scene selection (which resets the scroll offsets)
* Transitioning to the preview scene does not trigger the `show` callback again, thus no offset reset takes place
* We need to discuss internally whether we want to fix this, as one could argue that you transition to the scene as _visible_ in the preview, which includes the state of animations
* If animations are supposed to be _reset_ on transitions, this would be a new feature
* This reset should probably occur at the start of a transition, to avoid visually jarring "resets" after transition

**Comment by PatTheMav** [comment] 2022-10-05 13:26
I'm closing this issue for now, because IMO it works as intended - when using preview you want the state of the scene as visible in the preview to transfer directly to the program.

If a "reset" of all animations is required, this would be a new feature and should be requested as such.

**Closed by PatTheMav** 2022-10-05 13:26 UTC
