### ISSUE TITLE
Segfault with 27.0.0 rc2 on wayland

### ISSUE THREAD

**Issue by SpeedProg** [obsproject/obs-studio#4605] opened 2021-04-27 14:02 UTC
### Operating System Info

Other

### Other OS

Gentoo

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/ALrXlL-gJi9qLqNY

### Expected Behavior

No sefaulting

### Current Behavior

Segfaults

### Steps to Reproduce

1. Put obs on a screen
2. record a screen with obs using scpy (might not matter if you use an other method)
3. turn of all screen and wait a while
4. come back to a segfaulted obs

### Anything else we should know?

couldn't find a crash log ... but here is the backtrace I get when running it in gdb:
```
#0  0x0000000000000002 in  ()
#1  0x00007ffff0de1e1d in ffi_call_unix64 () at /usr/src/debug/dev-libs/libffi-3.3-r2/libffi-3.3/src/x86/unix64.S:101
#2  0x00007ffff0de136c in ffi_call_int
    (cif=0x7fff7d208f00, fn=0x2, rvalue=<optimized out>, avalue=<optimized out>, closure=<optimized out>)
    at /usr/src/debug/dev-libs/libffi-3.3-r2/libffi-3.3/src/x86/ffi64.c:669
#3  0x00007ffff7fb7452 in wl_closure_invoke (closure=0x7fff480cfd90, flags=1, target=<optimized out>, opcode=1, data=<optimized out>)
    at ../wayland-1.19.0/src/connection.c:1018
#4  0x00007ffff7fb39da in dispatch_event (display=display@entry=0x555556685940, queue=0x555556685a10, queue=<optimized out>)
    at ../wayland-1.19.0/src/wayland-client.c:1452
#5  0x00007ffff7fb50dc in dispatch_queue (queue=0x555556685a10, display=0x555556685940) at ../wayland-1.19.0/src/wayland-client.c:1598
#6  wl_display_dispatch_queue_pending (display=0x555556685940, queue=0x555556685a10) at ../wayland-1.19.0/src/wayland-client.c:1840
#7  0x00007ffff7fb55bf in wl_display_roundtrip_queue (display=0x555556685940, queue=0x555556685a10)
    at ../wayland-1.19.0/src/wayland-client.c:1258
#8  0x00007ffff7fb560c in wl_display_roundtrip (display=<optimized out>) at ../wayland-1.19.0/src/wayland-client.c:1287
#9  0x00007fffc0029718 in render (data=0x555556685880, effect=<optimized out>) at ../wlrobs-v1.0/src/scpy_source.c:260
#10 0x00007ffff5ec3030 in obs_source_default_render (source=source@entry=0x555556681be0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2192
#11 0x00007ffff5ec7b93 in obs_source_main_render (source=0x555556681be0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2206
#12 render_video (source=0x555556681be0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2263
#13 obs_source_video_render (source=0x555556681be0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2283
#14 0x00007ffff5efe18f in render_item (item=0x55555635f0a0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-scene.c:638
#15 scene_video_render (data=<optimized out>, effect=<optimized out>)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-scene.c:732
#16 0x00007ffff5ec7a53 in obs_source_main_render (source=0x55555668bb00)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2208
#17 render_video (source=0x55555668bb00)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2263
#18 obs_source_video_render (source=0x55555668bb00)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2283
#19 0x00007ffff5eced13 in obs_transition_video_render (transition=0x55555657a4e0, callback=0x7fff4f64a410 <fade_callback>)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source-transition.c:793
#20 0x00007ffff5ec7a53 in obs_source_main_render (source=0x55555657a4e0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2208
#21 render_video (source=0x55555657a4e0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2263
#22 obs_source_video_render (source=0x55555657a4e0)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-source.c:2283
#23 0x00007ffff5efad1f in obs_view_render (view=0x555555927ea8)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-view.c:141
#24 0x00007ffff5f04b19 in render_main_texture (video=0x5555559278e8)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-video.c:152
#25 render_video (cur_texture=1, gpu_active=false, raw_active=true, video=0x5555559278e8)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-video.c:488
#26 output_frame (gpu_active=false, raw_active=true)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-video.c:765
#27 obs_graphics_thread_loop (context=context@entry=0x7fff7d209740)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-video.c:977
#28 0x00007ffff5f05f28 in obs_graphics_thread (param=<optimized out>)
    at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/libobs/obs-video.c:1052
#29 0x00007ffff4f6cfde in start_thread (arg=0x7fff7d20a640) at pthread_create.c:463
#30 0x00007ffff4ea242f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
Running sway.

**Comment by GeorgesStavracas** [comment] 2021-04-27 14:02
This is a duplicate of https://github.com/obsproject/obs-studio/issues/4295

**Comment by SpeedProg** [comment] 2021-04-27 14:07
I just want to note that I use a patched version of qt (from the comments which you think this is a duplicate of) and also as long as I don't turn of my monitors the crash never happens even if I switch the workspace away from the one obs is in. Might still be that you are right, but I didn't think so.

**Comment by GeorgesStavracas** [comment] 2021-04-27 15:26
Okay, if this is not the same issue please reopen and let us know

**Comment by SpeedProg** [comment] 2021-04-27 22:07
`Backtrace that this was closed as a duplicated of is for me (when using unpatched qtwayland):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff4dc7536 in __GI_abort () at abort.c:79
#2  0x00007ffff534bdb1 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007fffed09cdf9 in  () at /usr/lib64/libQt5WaylandClient.so.5
#4  0x00007fffed0abf8a in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib64/libQt5WaylandClient.so.5
#5  0x00007ffff5578f20 in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007ffff557c676 in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) () at /usr/lib64/libQt5Core.so.5
#7  0x00007ffff557cdeb in QSocketNotifier::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#8  0x00007ffff60a3193 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff60ac210 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff5543fdf in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#11 0x00007ffff559c2be in  () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff3f2995c in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#13 0x00007ffff3f29bf8 in  () at /usr/lib64/libglib-2.0.so.0
#14 0x00007ffff3f29c8f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#15 0x00007ffff559b9a0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff5542dbb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#17 0x00007ffff554b0bd in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#18 0x00005555555cf352 in run_program (argv=0x7fffffffd9d8, argc=<optimized out>, logFile=...) at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/UI/obs-app.cpp:2087
#19 main(int, char**) (argc=<optimized out>, argv=0x7fffffffd9d8) at /usr/src/debug/media-video/obs-studio-27.0.0_rc2/obs-studio-27.0.0-rc2/UI/obs-app.cpp:2762`
So the backtrace for this segfault is completely different code paths (and does not even use any of the wayland qt) and I still get it even with the new QT patch that was mentioned in the issue this was marked as a duplicated of. I might need to report this issue to wlrobes instead of obs through?

**Comment by GeorgesStavracas** [comment] 2021-04-27 22:53
This is a different backtrace compared to the original one.

**Comment by SpeedProg** [comment] 2021-04-28 09:51
Yes because as mentioned at the start of my last comment, the backtrace is for the bug this was marked as a duplicated of and I only posted it to show that they are completely different.

**Comment by GeorgesStavracas** [comment] 2021-04-29 20:55
Both backtraces crash when flushing messages into the Wayland socket, which is the telltale sign of #4295.

**Comment by RytoEX** [comment] 2022-11-16 20:57
As #4295 has been fixed, please retest in the Flatpak version of OBS Studio 28.1.2 (or newer).

**Comment by RytoEX** [comment] 2024-03-21 17:08
Closing this as there have been no new reports in well over a year and we were reasonably certain that this crash was fixed back then.

**Closed by RytoEX** 2024-03-21 17:08 UTC
Labels: Linux, Dependency Issue
