### ISSUE TITLE
All "Media Source" sources automatically play when OBS is launched (which is quite unpleasant)

### ISSUE THREAD

**Issue by ClearCloud8** [obsproject/obs-studio#9205] opened 2023-07-04 20:37 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Z6ccQ0bb4BMDvyQy

### Expected Behavior

When I open OBS, I do not expect all Media Source video files to automatically play.

### Current Behavior

I have a lot of "Media Source" sources which are pointing at different local video files.... and when I launch OBS, then they all play simultaneously.  It's a lot of audio playing all at once and can be very unpleasant and even startling.  Additionally I see the CPU utilization go up pretty high since many video files are playing at the same time.

### Steps to Reproduce

1. Create 2 or 3 Media Sources which are pointing to different video files, all in the same Scene.
2. Select that Scene so it is active.
3. Quit OBS
4. Re-Launch OBS
5. Observe that all the video files play at the same time... which is very chaotic.
...

**Comment by Penwy** [comment] 2023-07-04 20:43
This is intended behaviour.

If your aim with said media sources is to have them only play when asked so, do the following :
In the properties of the media sources, tick "restart playback when source becomes active"
Hide all the sources
Set whatever automation tool you use to play said media files to unhide then hide them instead of using media controls.

**Comment by ClearCloud8** [comment] 2023-07-04 21:11
Thanks for your response.  The issue I face with that approach is each video can be of different length.  So it's a little tedious to set a timeout for each video based on the video length.  So I have purposefully unticked the option you mentioned... and I used the Play/Stop media control option (which I'm accessing through Elgato Stream Deck).  It works really well to play/show or stop/hide the video -- and even stop it early if I want, by pressing the same button.  And when a video finishes playing then it just disappears on it's own.  And on top of all that.... I just don't understand what use case would desire media sources to auto-play when OBS is launched...  seems like it would be better for everyone if they did not.

**Comment by YorVeX** [comment] 2023-07-05 01:43
> I just don't understand what use case would desire media sources to auto-play when OBS is launched... 

I have a default cam background video loop that always needs to run, also some people have animated panels based on webm video files that should be visible all the time. And while I am programming certain OBS stuff it's really helpful to have my test video loop run right from the start.

So on the contrary I wonder what use case would need to not have them run on startup, because clearly throughout the entirety of OBS all sources work like this: if I want them active, I switch their visibility on, if not, I switch it off. Having it paused from the start would be a broken source to me, because it would show as visible but still do nothing. Then I switch it off, on again, and _then_ it shows something? I'd immediately file a bug report about a source behaving inconsistently like that :-P

**Comment by ClearCloud8** [comment] 2023-07-05 17:54
Hey YorVeX, your use case makes sense! Thanks for sharing it.

Additional details I would like to add (which to me indicates things are **not** working as they should):
- Even with the Media Source visibility toggled off... when you launch OBS, the video files begin to play in the background.
- I see my CPU go up to 25%, whereas it sits at around 6% only after the Media Sources have all stopped.
- I've verified this situation by launching OBS, seeing that my Media Source is not visible....  clicking to make it visible... and observing the video file is already playing something like 15 seconds into the video clip.  (Not from the beginning of the clip.)

So I'm thinking it's really not working as intended....  at the very least, the video should only be Autoplayed when the source is (or becomes) visible.

However, if this somehow IS the intended behavior... then I think users would benefit from a checkbox in the Properties panel, something like:  "Autoplay Video when Visible"  or  "Do not Autoplay"

**Comment by Penwy** [comment] 2023-07-06 12:25
you can use automation tools like advanced-scene-switcher to auto-hide media sources on playback end

**Comment by Fenrirthviti** [comment] 2023-07-06 20:33
Since this is expected, and not a bug, I am going to close this issue as we currently reserve github issues for verified bug reports.

Since this is a feature request, please check out our [ideas page](https://ideas.obsproject.com/)

**Closed by Fenrirthviti** 2023-07-06 20:33 UTC

**Comment by YorVeX** [comment] 2023-07-07 00:02
> * Even with the Media Source visibility toggled off... when you launch OBS, the video files begin to play in the background.
> * I see my CPU go up to 25%, whereas it sits at around 6% only after the Media Sources have all finished playing.
> * I've verified this situation by launching OBS, seeing that my Media Source is not visible....  clicking to make it visible... and observing the video file is already playing something like 15 seconds into the video clip.  (Not from the beginning of the clip.)
> 
> So I'm thinking it's really not working as intended.... at the very least, the video should only be Autoplayed (on launching OBS) when the source is visible/enabled.

All of that is intended behavior, it's exactly what the "Restart playback when source becomes active" option controls. Part of the problem might be that the description doesn't make immediately obvious what it implies. You can only deduct it yourself if you think it through carefully.

When the option is disabled:
* not restarting the video when becoming active means it's on the contrary running all the time in the background
* "running" means it is being decoded, meaning your CPU needs to do decoding work
  * the option for hardware decoding might move some of this to the GPU, but decoding is decoding, it's work, it needs processing, and this inevitably means load somewhere on your machine

Imagine you have a background video in a media source which is a recording of a busy street behind your live cam feed, to make you look like you're in that street. In that background video a shiny yellow taxi has just entered the camera view on the left side. Now you switch to another scene where this background video and your cam is not visible for two seconds, e.g. to show something from your screen, then you switch back. The taxi that had entered the scene on the left side might now be visible just as it moves out of the view on the right side, because it takes a bit longer than two seconds to pass from left to right. But you get the effect of that scene happening live in real time in the background, which you wouldn't if the video was either not continued in the background (the effect would break, because why is that taxi still on the left edge 2 seconds later?) or fully reset (no taxi at all, the whole scene changed).

All of this is only possible for one reason: because the video is not being restarted. But to achieve this, it needs to stay running, _actually running_, regardless of its visibility.

This means that this option is very powerful both about managing the load on your PC and visible effects. And it's fully in your hands how you want it to behave. If you don't want the videos to run in background but only when they are set to visible (or become active through other means, e.g. switching to a scene that contains them), then tick that box, as @Penwy has already advised you to.

**Comment by YorVeX** [comment] 2023-07-07 01:07
> These are some excellent ideas, thank you. I think they could serve as a work-around. Currently I made a kinda lame solution using Stream Deck Multiaction, where it opens OBS, waits 15 seconds, stops all the videos, makes all the videos visible. (I say it's kinda lame, because 15 seconds is just my safe bet... I'm waiting for OBS to be fully loaded so I can execute the rest of the actions. Also, if I ever forget to use the stream deck button to launch OBS... and just launch OBS myself... then I am bombarded with all sorts of chaotic noises playing at the same moment. 😅)

You pretty much describe here the problem with the implementation of what you were requesting with this GH issue. From a source perspective it is either activated or deactivated, it has no means to tell in which context that happens, it cannot tell an activation as part of the OBS startup apart from one at any other point in time. It can only decide whether it just keeps on running the video regardless of becoming active or not (as described in my above answer) or start over with the playback.

To implement what you want you would need to do exactly things like this: remember the OBS startup time somewhere, define how long startup usually takes (obviously different for every user depending on their setup, so there cannot be a general solution) and then treat all activations happening during that time as "startup activation".

Or you would have to rewrite half of OBS to change the event callbacks like "activate" to include an "activated during startup" flag, which apart from breaking the API for pretty much every single existing plugin that show a source or filter (or introducing a separate extra API that would have to be maintained from that point on) it would also mean lots of effort outside of the API, because currently OBS of course doesn't track such a state for sources internally, this would need extra implementations first. All this for a use case that I believe only exists because of some misconceptions about how media sources should be used.

> I did not know Advanced Scene Switcher has an "On OBS Loaded" event hook. That could be a good option to avoid my previously mentioned solution. Even manually adding actions for each source is acceptable I suppose, I just really don't like estimating "about 15 seconds"... which could may or may not always be true. Plus if it works without needing a Stream Deck Multiaction... then it will always work, no matter in what way OBS was launched.
It needs a bit of extra logic, [an example is shown here](https://github.com/WarmUpTill/SceneSwitcher/wiki/Start-other-programs-when-starting-OBS).

> I guess you see why this is an issue already from my previous comment. The videos ARE playing in the background even when the source is hidden (visibility off). I don't have them looping, so they are all just playing through once simultaneously. Some of them up to 30 seconds long. And as mentioned the CPU usage goes up higher than normal. (Just seems like unintended behavior to me... like a bug.)

As I said in my previous answer, it's intended behavior and you should simply set the restart option correctly.
 
> But if I press the same button again.... NOTHING happens. That's because now I'm toggling Visibility off.

That's how a toggle in Stream Deck works. It has only its own toggle state information, if the last button press was an "on" action, then the next has to be an "off" action, it has no way to detect whether the state of what is toggled already reset to "off" by other means outside of its own logic.

But the solution to a limitation in Stream Deck is certainly not that OBS changes half of its code ;-)

Use [this script](https://github.com/exeldro/obs-lua/blob/master/media-hide.lua) by the almighty Exeldro to have media sources auto-hide after they ended their playbacks. Then instead of a toggle in Stream Deck use a source visibility button for the media sources that show the video clips. Unlike a toggle this button will even detect visibility changes from the source in OBS, so it will also indicate whether the clip is currently being played and turn itself back to the "source not visible" indication status afterwards.
