### ISSUE TITLE
Dock Sizes are Reset the next time you open OBS.

### ISSUE THREAD

**Issue by GentlePuppet** [obsproject/obs-studio#2949] opened 2020-05-18 16:29 UTC
## Platform
Operating system and version: Windows 10 Pro 1809
OBS Studio version: 25.0.8

## Expected Behavior
When I manually resize locked Docks in the UI I expect them to be remembered and kept the next time I open OBS.

## Current Behavior
When I manually resize a dock it will be reset the next time I open OBS.

## Steps to Reproduce
Manually Set Sizes
![Manually Set Sizes](https://cdn.discordapp.com/attachments/475505815592108052/711977268146077716/unknown.png)

Close and reopen OBS
![Reset Sizes](https://cdn.discordapp.com/attachments/475505815592108052/711977720065687572/unknown.png)

**Comment by skeletonbow** [comment] 2020-08-31 10:29
I experience this same problem as well, just talked with Matt||Wizard about it.  I've never connected my OBS up to any live streaming service (Twitch/YouTube/etc.) and only use it for primarily local recording and visual effects development, as well as streaming through VirtualCam on Discord voice chat and voice channels occasionally.  The exact same symptoms as described in the original report above occur for me.  Some additional info:

I'm on Windows 10/x64 1909 build fully updated, running OBS 25.0.8.  Reorganizing the panels, OBS remembers that I added/removed/stacked/etc. the panels but once it is closed and restarted, most if not all of the panels have been resized.   I've tried setting it all up both with UI locked and not locked on multiple invocations and the width and specific location of panels is not remembered and restored.

Merely starting OBS up, adjusting the width of a panel and exiting then restarting is enough to reproduce 100% of the time.

**Comment by skeletonbow** [comment] 2020-08-31 10:42
Ok, I did some testing and it appears that every OBS dock has a certain preferred size that it wants to be no smaller than, and if you resize it smaller than that, it will let you up to a minimum size, but when you exit OBS, if the current size of any panel is less than the preferred size it mysteriously seems to want to be no smaller than, when you exit OBS and restart it it will resize all of the panels to be this preferred size, ignoring your resizing wishes.

Potential suggested solution;  Set the minimum sizes of the panels to be the smallest acceptable sizes and allow the user to resize the panels to this size if desired and save and restore them, without enforcing a preferred size smaller than the minimum the user is allowed to resize to.

**Comment by Bidthedog** [comment] 2020-08-31 10:44
> 
> 
> Ok, I did some testing and it appears that every OBS dock has a certain preferred size that it wants to be no smaller than, and if you resize it smaller than that, it will let you up to a minimum size, but when you exit OBS, if the current size of any panel is less than the preferred size it mysteriously seems to want to be no smaller than, when you exit OBS and restart it it will resize all of the panels to be this preferred size, ignoring your resizing wishes.
> 
> Potential suggested solution; Set the minimum sizes of the panels to be the smallest acceptable sizes and allow the user to resize the panels to this size if desired and save and restore them, without enforcing a preferred size smaller than the minimum the user is allowed to resize to.

Also, don't forget the ability to turn docks off - including the ability to turn off ALL docks so only the main capture screen is shown.

**Comment by skeletonbow** [comment] 2020-08-31 11:10
Ok, it seems that only the panels in the bottom dock group below the preview exhibit this behaviour on my system.  If I resize the Scenes pane which is moved to the left of preview, I can shrink it to minimum width and it stays that way over a restart.  If I move it to the bottom dock group and shrink it to the same minimum size, it does not remember it and restores itself to a preferred size larger than I set it to.

Is anyone able to reproduce this on a stock OBS with my repro info?  I do have plugins installed, so my next step would be to set up a pristine install unless someone who has a pristine install can repro it as described, just to help narrow things down further.

**Comment by shleeable** [comment] 2020-09-10 07:30
Same here to make this issue myself.

**Comment by WizardCM** [comment] 2021-01-19 12:55
So based on what others have said, and the code I've looked at, there are two potential theories:

1. When initialising, certain docks have a minimum size that's different to their defined minimum size
2. (this one's my own) dock positions aren't being saved properly, but it's not related to OAuth dock saving

If it's 2, then performing this task sooner during shutdown might help:
https://github.com/obsproject/obs-studio/blob/54207a0d6032e507801c96f69731c3a5a39543da/UI/window-basic-main.cpp#L4294-L4295

If it's 1, we might need to do more specific tests to see if everyone is able to reproduce it the same way. That is, we need to put together reproduction steps using specific built-in docks in a certain layout & window size.

**Comment by BobbyFuzzy** [comment] 2021-01-19 18:04
I have also noticed this issue. Please let me know if I can put together any info for you to help diagnose @WizardCM.

**Comment by BobbyFuzzy** [comment] 2021-01-22 13:12
> * When initialising, certain docks have a minimum size that's different to their defined minimum size

To add to this, I am trying to make docks larger and still experiencing the issue of the size not saving.


> I've done a bit of digging, and it seems that dock settings might only be saved when you have an authenticated Twitch stream

I tested this also with the restream.io profile and noticed that it will save the dock sizes if a profile is linked.

**Comment by mihawk90** [comment] 2021-04-21 12:03
I just now noticed I am having the same issue, I never noticed it before (since I wasn't using Browser docks before, so defaults were fine for me). Can reproduce with 26.1.2 and 27.0.0~rc2, both on Fedora KDE and with an empty profile (i.e. `~/.config/obs-studio` moved out).

**Comment by DemonfangArun** [comment] 2021-11-23 04:00
Going to add a bump here that I am getting this both on opening it as well as if the window gets resized.

27.1.3 (64 bit).

**Comment by SXRWahrheit** [comment] 2021-12-05 18:18
+1 for this issue. I'd like to add that my layout consistently prioritizes the stream preview versus the other dock windows, and re-maximizing the window does not restore the docks to their prior state. It would be fine if I could just load a layout so that once I have it how I like it, I can do that even if it gets messed up.

**Comment by SubhamSatyajeet** [comment] 2021-12-10 04:01
I've also experienced this issue on Wndows 10 20H2. This issue occurs even when OBS is setup simply to record and not stream.

**Comment by KGeetings** [comment] 2022-01-12 04:03
Would just like to say that I've also ran into this issue on two separate computers, and it's easily replicated on my end, using OBS 27.1.3 (64-bit).

**Comment by jiimip** [comment] 2022-01-24 07:34
Got the same issues on 4 different Mac systems and 2 Windows systems, so it's not OS-related.

**Comment by PCHSwS** [comment] 2022-02-12 15:44
I upgraded from 26.1.1 a few days ago to 27.1.3. My docks have been saved with proper size before, since the update everything gets reset back to default every time I launch OBS.

**Comment by AnyMEmdq** [comment] 2022-02-19 18:14
In my case, fully updated to 27.1.3, docks revert to default sizes when I change the size of the window (which in my case is imperative, as it reverts to my main screen every time I reset my PC and I have to manually move it to the secondary monitor). W10 Pro 64 build 19042.1466

**Comment by OldBaldGeek** [comment] 2022-03-31 16:48
I have found a work-around, at least on my two Win10 machines running various versions of OBS (stock 27.2.3, local build based on 27.1.3, local build based on latest source)

I have always run OBS Maximized (not full-screen), and been annoyed by the docks resizing. On a whim, I changed OBS to a resizable window, adjusted that to be as large as possible, and sized the dock items. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.

I then Maximized OBS, and tweaked the dock sizes. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.

Just tried it on full-screen, and it works there as well.

**Comment by Oghenefega** [comment] 2022-05-12 12:23
> I have found a work-around, at least on my two Win10 machines running various versions of OBS (stock 27.2.3, local build based on 27.1.3, local build based on latest source)
> 
> I have always run OBS Maximized (not full-screen), and been annoyed by the docks resizing. On a whim, I changed OBS to a resizable window, adjusted that to be as large as possible, and sized the dock items. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> I then Maximized OBS, and tweaked the dock sizes. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> Just tried it on full-screen, and it works there as well.

Thanks for this amazing work around. Great fix

**Comment by ifohancroft** [comment] 2022-05-22 04:56
> > I have found a work-around, at least on my two Win10 machines running various versions of OBS (stock 27.2.3, local build based on 27.1.3, local build based on latest source)
> > I have always run OBS Maximized (not full-screen), and been annoyed by the docks resizing. On a whim, I changed OBS to a resizable window, adjusted that to be as large as possible, and sized the dock items. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> > I then Maximized OBS, and tweaked the dock sizes. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> > Just tried it on full-screen, and it works there as well.
> 
> Thanks for this amazing work around. Great fix

That worked for me as well. Thanks!

**Comment by RangerX64** [comment] 2022-06-03 22:16
> I have found a work-around, at least on my two Win10 machines running various versions of OBS (stock 27.2.3, local build based on 27.1.3, local build based on latest source)
> 
> I have always run OBS Maximized (not full-screen), and been annoyed by the docks resizing. On a whim, I changed OBS to a resizable window, adjusted that to be as large as possible, and sized the dock items. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> I then Maximized OBS, and tweaked the dock sizes. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> Just tried it on full-screen, and it works there as well.

For those of us who are rather new to OBS Studio, could you please show the actual UI steps one must take to change these specific window settings for the OBS Studio app itself? I have combed through every setting and cannot find any that are specific to doing this for the main OBS window, and all I can find on the internet is how to change the size of the capture windows being used for scenes rather than OBS.

Thank you.

**Comment by mihawk90** [comment] 2022-06-04 13:32
> I have combed through every setting and cannot find any that are specific to doing this for the main OBS window

It's not a setting.

They are talking about just not maximizing the window (i.e. through the maximize button on the title bar) and then just dragging the window size to the edges of your screen instead.

**Comment by playaspec** [comment] 2023-01-22 21:47
> I have found a work-around, at least on my two Win10 machines running various versions of OBS (stock 27.2.3, local build based on 27.1.3, local build based on latest source)
> 
> I have always run OBS Maximized (not full-screen), and been annoyed by the docks resizing. On a whim, I changed OBS to a resizable window, adjusted that to be as large as possible, and sized the dock items. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> I then Maximized OBS, and tweaked the dock sizes. Exit OBS. Start OBS, and WINDOW AND DOCK SIZES ARE RIGHT WHERE I SET THEM.
> 
> Just tried it on full-screen, and it works there as well.

This worked for me as well. Thanks so much!

OBS 29.0.0, built from source.

**Comment by lejifps** [comment] 2023-05-11 04:55
Why tf is that bug even still a thing after ages ?? .. -_- driving someone actually nuts

**Comment by archeruwu** [comment] 2023-05-28 01:56
Can confirm, this STILL happens on the LATEST version of OBS 29, to add on, ever since the release of 28.0, OBS no longer remembers what monitor it was last on and will just open to the default monitor (which mine happens to be 3440x1440 which is VERY large, and messes with the Dock scaling really bad).

**Comment by nospam2k** [comment] 2023-12-28 21:18
Lol, this is interesting. This bug has been around for almost 3 years! The problem is when in full screen, dock widths are not saved. So come out of full screen, enlarge the window to the size of full screen, set the dock sizes, uncheck/recheck Dock Lock, close and reopen and it's saved. Switched to full screen and close enough!

**Comment by WizardCM** [comment] 2023-12-29 01:30
Except it's only 100% reproducible for some people, and often times a fresh installation (where the user backs up & deletes their config) fixes the bug. For most people, the bug does not occur.

**Comment by AlphaTechnicalReal** [comment] 2023-12-30 20:33
I had a friend with this issue after we updated from 28 to 30 and put OBS into portable mode. The solution was just to run OBS as administrator. Give it a shot.

**Comment by belatar** [comment] 2024-04-26 16:44
> Lol, this is interesting. This bug has been around for almost 3 years! The problem is when in full screen, dock widths are not saved. So come out of full screen, enlarge the window to the size of full screen, set the dock sizes, uncheck/recheck Dock Lock, close and reopen and it's saved. Switched to full screen and close enough!

omg, ive been searching for a solution and this did the trick. thanks! drove me nuts having to rearrange my docks everytime i opened it. i wonder what makes this so hard to fix. considering obs does tons of bleeding edge performance critical video and audio stuff this issue sounds like a simple one.
but maybe its one of these "sounds easy, actually is hard" kind of issues.

**Comment by AlphaTechnicalReal** [comment] 2024-04-26 17:46
> If running as admin fixes it, you're likely running OBS from a location that doesn't have proper permissions to save settings to as a normal user, especially if OBS is running in portable mode.
> 
> There's no log files in this entire thread though, so it's hard to say.

You are correct here. Every person I’ve seen with has recently moved the OBS installation or has a folder permission issue. Once OBS is in portable mode you basically always have to run it as admin if not you into all sorts of issues.

I’ll take running it as admin all the time to make sure I have full instance backups of OBS.

**Comment by RytoEX** [comment] 2024-04-26 18:08
> Once OBS is in portable mode you basically always have to run it as admin if not you into all sorts of issues.

If you must run OBS as administrator while in Portable Mode, then that all but confirms that the location OBS is in is write-protected, and your user account itself does not have write permissions there.

Do not run OBS in Portable Mode from protected locations, such as:
* `C:\Program Files`
* `C:\Program Files (x86)`
* `C:\ProgramData`

If you want to run OBS in Portable Mode, extract the zip file somewhere you *do* have write permissions, such as one of these example locations. Make sure you have permission to write files there (you do not get an admin prompt when extracting files):
* Desktop
* `C:\examplefolder`
* `D:\examplefolder`

Otherwise, just run OBS normally (not in Portable Mode), and it will use your user AppData for its user data, and it should work fine.

**Comment by selwynorren** [comment] 2024-07-16 07:55
> > Lol, this is interesting. This bug has been around for almost 3 years! The problem is when in full screen, dock widths are not saved. So come out of full screen, enlarge the window to the size of full screen, set the dock sizes, uncheck/recheck Dock Lock, close and reopen and it's saved. Switched to full screen and close enough!
> 
> omg, ive been searching for a solution and this did the trick. thanks! drove me nuts having to rearrange my docks everytime i opened it. i wonder what makes this so hard to fix. considering obs does tons of bleeding edge performance critical video and audio stuff this issue sounds like a simple one. but maybe its one of these "sounds easy, actually is hard" kind of issues.

So interestingly enough this has been a massive issue for me in Linux as well. This works 100% I always had it maximised and I woudl have to reset width every time I launched OBS. With this workaround it is exactly where I need it to be ever time. Thank you so much!!! Now a permanent fix for maximised would be so helpful.

**Comment by Fenrirthviti** [comment] 2024-10-14 21:25
Since this all seems to be an issue with permissions and not a bug with OBS, I am opting to close this.

If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

**Closed by Fenrirthviti** 2024-10-14 21:25 UTC
Labels: Confirmed
