### ISSUE TITLE
Audio Monitoring doesn't change target output device when the system's default output device changes

### ISSUE THREAD

**Issue by robmonte** [obsproject/obs-studio#8990] opened 2023-05-29 23:27 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/QqitTzbsYyfOTwdP

### Expected Behavior

The audio device that plays back audio monitoring sound should be updated when the system's default device changes. This should be a toggleable setting in the audio settings to allow people to keep using the current behavior they have grown accustomed to.

### Current Behavior

You can see in the logs that OBS detects when both the default input and default output devices changes. However, it does not switch the audio monitoring's output to accommodate for this change, yet the microphone input properly does. 

### Steps to Reproduce

1. Set an input source with audio in OBS
2. Observe the audio monitoring on your current audio device
3. Change the system's default output device
4. Observe the lack of audio in the changed device and that the audio still plays on the first one

**Comment by Fenrirthviti** [comment] 2023-05-29 23:58
Duplicate of https://github.com/obsproject/obs-studio/issues/4463

**Closed by Fenrirthviti** 2023-05-29 23:58 UTC

**Comment by robmonte** [comment] 2023-05-30 01:06
Thanks, I tried searching first but I guess I wasn't using good terms to find the original.

**Comment by Fenrirthviti** [comment] 2023-05-30 01:53
No worries! The underlying problem manifests in a few different ways, so it might not be immediately obvious they're related.
