### ISSUE TITLE
(regression) m3u8 muxer outputs corrupt file

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#3771] opened 2020-11-25 23:23 UTC
## Platform

Operating system and version: Windows 10 2004, Windows 7
OBS Studio version: 26.0.2, also affects 26 RC3, doesn't affect 25.0.8

## Expected Behavior

The m3u8 muxer should split the video into .ts chunks on each keyframe.

## Current Behavior

obs-ffmpeg-mux.exe hangs in the Task manager, doing nothing. A single 256 KB .ts file is written. Trying to stop recording results in stuck "stopping recording...".
## Steps to Reproduce

1. In Settings>Output, change output mode to Advanced, container format to m3u8.
2. Start recording.
3. Stop recording.

**Comment by WizardCM** [comment] 2020-11-25 23:24
This sounds like a duplicate of #3580

**Comment by gxalpha** [comment] 2022-10-19 20:40
Duplicate of https://github.com/obsproject/obs-studio/issues/3580

**Closed by gxalpha** 2022-10-19 20:40 UTC
