### ISSUE TITLE
BlackMagic Decklink Mini 4K won't show video

### ISSUE THREAD

**Issue by brucevw** [obsproject/obs-studio#3408] opened 2020-09-04 20:49 UTC
## Platform

Operating system and version: MacOS Mojave 10.14.6
OBS Studio version: 25.0.8 (64 bit)
Computer: Mac Pro (Mid 2010)
Processor: 2 x 2.8Ghz 6-Core Intel Xeon
Memory: 16 GB 1333 MHz DDR3
Graphics: Radeon RX 570 8GB

## Expected Behavior

I should see a video signal when using BlackMagic Decklink capture device.  It has worked relatively well for a few months and the BlackMagic Express program will show my video signal. 

## Current Behavior

All I'm getting is a black screen.
[2020-09-04 16-26-17.txt](https://github.com/obsproject/obs-studio/files/5176865/2020-09-04.16-26-17.txt)

I'm wondering if it has anything to do with the lines next to time codes 16:19:57.222-.541.  It would appear that the "API compile version 10.11.4" is what you have loaded into your software and "11.6" which shows up on the next line happens to be the latest build of BM Desktop Video Utility.  I tried installing 10.11.4, but it won't operate my BM device.

## Steps to Reproduce

Simply, set up a BlackMagic Decklink Mini 4K with OBS as it's supposed to be and some of the time it won't work.

**Comment by brucevw** [comment] 2020-09-04 21:22
I downgraded to Black Magic Desktop Video Version 11.5.1 (just previous to most recent, 11.6) and it is working now.  I think your API needs updated.

**Comment by Fenrirthviti** [comment] 2020-09-05 00:05
Duplicate of https://github.com/obsproject/obs-studio/issues/3277

**Closed by Fenrirthviti** 2020-09-05 00:05 UTC
