### ISSUE TITLE
Paste filters is clickable after removing source after copy, but doesn't do anything

### ISSUE THREAD

**Issue by adriansuwala** [obsproject/obs-studio#4075] opened 2021-01-15 12:31 UTC
## Platform

Operating system and version: Windows 10 Build 19042, release: 2009, revision: 685
OBS Studio version: 26.1.1

## Expected Behavior

Either filters are pasted or `Paste Filters` is not clickable.

## Current Behavior

`Paste Filters` is clickable, but doesn't do anything.

## Steps to Reproduce

1. Add any source.
2. Add any filters to that source.
3. Add another source (that can have these filters, e.g. both sources can have video filters)
4. Copy filters from the first source.
5. Remove the first source.
6. Right click -> `Paste Filters` on the second source.

**Comment by RytoEX** [comment] 2022-10-22 06:21
I cannot reproduce this on Windows 10 with OBS Studio 28.0.3. Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

**Comment by RytoEX** [comment] 2022-11-02 20:08
Closing per above. If this is still an issue, please comment with updated Steps To Reproduce and a new OBS log, and we can determine if we should reopen this or open a new Issue.

**Closed by RytoEX** 2022-11-02 20:08 UTC
