### ISSUE TITLE
Not running on steam deck (game mode)

### ISSUE THREAD

**Issue by StefanoBalocco** [obsproject/obs-studio#6386] opened 2022-04-28 06:23 UTC
### Operating System Info

Other

### Other OS

SteamOS 3.0 (aka Archlinux)

### OBS Studio Version

27.2.4

### OBS Studio Log URL

n/a

### Expected Behavior

App running

### Current Behavior

Installed from flathub 
Running fine from desktop mode
But, when I run it in game mode from steam, it simply doesn’t open the main window.

### Steps to Reproduce

1. Switch to desktop mode
2. Install from flathub
3. Add to steam
4. Switch to game mode
5. Run

**Comment by derrod** [comment] 2022-04-28 14:04
Based on the logs generated by Steam it sounds like Qt itself fails to start within GameScope. Not sure if Qt6 will "just work" there. But usefulness may be limited there anyway, since I don't know if you could even capture other windows from within gamescope.

```
GameAction [AppID 3006573093, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3006573093 -- "/usr/bin/flatpak" run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio\0
Game process added : AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3006573093 -- "/usr/bin/flatpak" run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio", ProcID 20946, IP 0.0.0.0:0
GameAction [AppID 3006573093, ActionID 1] : LaunchApp changed task to Completed with ""

Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Game process removed: AppID 0 "/home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=3006573093 -- "/usr/bin/flatpak" run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio", ProcID 20946 
```

**Comment by kkartaltepe** [comment] 2022-05-14 01:54
Am I reading that correctly that the wayland platform for Qt failed to load? In that case I dont think there is anything we can do about it and you should file a bug against Qt (or steamdeck packaging?).

**Comment by derrod** [comment] 2022-05-14 16:22
Before filing a bug against Qt I'd like to confirm that this issue still exists with Qt6, but I haven't gotten around to it. We're just running the Flatpak here and FWIW I know other Qt 6 Apps (e.g. ProtonUp-Qt) work in this mode.

**Comment by HugLifeTiZ** [comment] 2022-07-11 16:35
> Am I reading that correctly that the wayland platform for Qt failed to load? In that case I dont think there is anything we can do about it and you should file a bug against Qt (or steamdeck packaging?).

Gamescope is a "Wayland compositor" that [doesn't actually support Wayland clients at all.](https://github.com/Plagman/gamescope/issues/164) It only supports X11 clients through XWayland. So OBS Studio needs to run with the xcb backend. I changed the .desktop file to add QT_QPA_PLATFORM=xcb, and that allows OBS Studio to start and go through first-time setup while in game mode.

You can't actually capture anything, though. Gamescope does expose a Pipewire sink, but for some reason, OBS Studio isn't loading up Pipewire support at all. Is Pipewire only enabled for the Wayland backend? Is there any particularly good reason for that?

**Comment by kkartaltepe** [comment] 2022-07-12 00:29
pipewire is only enabled on wayland because it depends on the egl backend. In the next release pipewire will be enabled on x11, or you can test the current master if you can compile yourself.

Thanks for the interesting description of the platform, it sounds like we should close this working as intended.

**Comment by HugLifeTiZ** [comment] 2022-07-12 02:42
Is OBS studio really *intended* to crash though? I feel like there are still things you can do with it even if you can't capture the screen. Not that I can cite any useful examples. Is crashing at start more desirable than not being able to capture anything?

And besides, even once 28 drops and Pipewire is available on X11, if the platform detection behavior remains as-is, it's still going to crash. Gamescope's developers say that they don't advertise xdg-shell, which is what most traditional Wayland compositors provide and most detection mechanisms look for. The question is: is OBS Studio doing incorrect platform detection, or is the specific version of Qt 6 used by Studio?

**Comment by kkartaltepe** [comment] 2022-07-12 03:08
> Is OBS studio really intended to crash though?

If you launch obs in a wayland session that doesnt support wayland, obs fails to start. This is intentional on Qt's part and I see no reason to attempt to work around Qt's correct behavior.

> And besides, even once 28 drops and Pipewire is available on X11, if the platform detection behavior remains as-is, it's still going to crash. Gamescope's developers say that they don't advertise xdg-shell, which is what most traditional Wayland compositors provide and most detection mechanisms look for. The question is: is OBS Studio doing incorrect platform detection, or is the specific version of Qt 6 used by Studio?

This would be a bug report you should raise to Qt if you think it should behave differently. As a side benefit instead of just "fixing" obs it would help all other users of Qt.

**Comment by kkartaltepe** [comment] 2022-07-12 03:17
Reading the other thread it is believed that qt can correctly determine this odd platform, we have an override to fix Qt behavior on gnome that may be interfering with fallback on this platform if Qt actually can perform that fallback. Consider patching out https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L2087 to see if it behaves differently. We can add another check to restrict this to gnome if needed.

**Comment by HugLifeTiZ** [comment] 2022-09-01 17:09
I just tried running OBS Studio 28.0 on the Steam Deck. It still incorrectly detects the platform and immediately crashes unless you use the `QT_QPA_PLATFORM=xcb` environment variable.

The good news is that the PipeWire source is available now that EGL is being used on X11. The bad news is that it doesn't work. When I click on "Select Monitor", regardless of whether I'm in gaming mode or desktop mode, nothing happens. This is also a problem on my main computer running KDE Neon, so this part probably needs a separate issue report.

**Comment by kkartaltepe** [comment] 2022-09-02 02:07
>  just tried running OBS Studio 28.0 on the Steam Deck. It still incorrectly detects the platform and immediately crashes unless you use the QT_QPA_PLATFORM=xcb environment variable.

> >  Consider patching out https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L2087 to see if it behaves differently. We can add another check to restrict this to gnome if needed.

> The good news is that the PipeWire source is available now that EGL is being used on X11. The bad news is that it doesn't work. When I click on "Select Monitor", regardless of whether I'm in gaming mode or desktop mode, nothing happens. This is also a problem on my main computer running KDE Neon, so this part probably needs a separate issue report.

I believe there are no compositors that support pipewire capture (the xdg-desktop-portal capture functionality) on X11, except maybe bleeding edge gnome. Please open a new bug report for that if you can find other programs able to capture via the xdg-desktop-portal protocol on x11.

**Closed** 2022-12-23 13:00 UTC
Labels: Dependency Issue, Confirmed, Other OS (*nix)
