### ISSUE TITLE
OBS Studio crash when copy and paste an element from another scene collection

### ISSUE THREAD

**Issue by angeloruggieridj** [obsproject/obs-studio#11416] opened 2024-10-18 16:51 UTC
### Operating System Info

Other

### Other OS

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/GGKlOLNymPxEMsAu

### Expected Behavior

Copy elements (text or layers) from Scene collection A to Scene collection B

### Current Behavior

When I want to switch from a Scene collection to another OBS Studio crashes sometimes.
If I copy some elements in order to paste them in another scene, when I switch from scene A to scene B, it crashes always.

OBS Studio crashes also in Safe mode, so it's not a third-part plugin problem.
It is not possible to copy and paste layers from/to scene collections and you need to recreate them.

### Steps to Reproduce

1. Create a text layer on scene collection A
2.Adjust it (change dimension, X/Y position)
3. Copy it
4. Switch to scene collection B
5. OBS crashes
...

**Comment by angeloruggieridj** [comment] 2024-10-18 16:55
Launching from Terminal, on crashes:

`info: [obs-scripting]: Unloaded lua script: instant-replay.lua
warning: QObject::startTimer: Timers cannot be started from another thread
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API misuse: modification of a menu's items on a non-main thread when the menu is part of the main menu. Main menu contents may only be modified from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000195868ec0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000019534ecd8 objc_exception_throw + 88
	2   Foundation                          0x0000000196a65588 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x000000019932ae8c -[NSMenu itemArray] + 32
	4   libqcocoa.dylib                     0x00000001041ef078 qt_plugin_instance + 95084
	5   QtWidgets                           0x0000000103a843a8 _ZN5QMenu11actionEventEP12QActionEvent + 1216
	6   QtWidgets                           0x000000010393540c _ZN7QWidget5eventEP6QEvent + 132
	7   QtWidgets                           0x0000000103a82478 _ZN5QMenu5eventEP6QEvent + 1140
	8   QtWidgets                           0x00000001038ecb68 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 272
	9   QtWidgets                           0x00000001038ee4f8 _ZN12QApplication6notifyEP7QObjectP6QEvent + 3280
	10  QtCore                              0x00000001033f0af0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 292
	11  QtGui                               0x0000000102b9ddc8 _ZN7QAction5eventEP6QEvent + 68
	12  QtWidgets                           0x00000001038ecb68 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 272
	13  QtWidgets                           0x00000001038ed9f8 _ZN12QApplication6notifyEP7QObjectP6QEvent + 464
	14  QtCore                              0x00000001033f0af0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 292
	15  QtGui                               0x0000000102b9da34 _ZN14QActionPrivate10setEnabledEbb + 424
	16  OBS                                 0x0000000100d2c424 OBS + 1426468
	17  libobs                              0x0000000102f65178 signal_handler_signal + 236
	18  libobs                              0x0000000102fcf250 obs_source_filter_remove_refless + 316
	19  libobs                              0x0000000102fcf070 obs_source_destroy + 460
	20  libobs                              0x0000000102fcf8e4 obs_source_release + 92
	21  libobs                              0x0000000102fc1580 obs_sceneitem_release + 152
	22  libobs                              0x0000000102fc759c remove_all_items + 244
	23  libobs                              0x0000000102fbfe24 scene_destroy + 20
	24  libobs                              0x0000000102fcf488 obs_source_destroy_defer + 184
	25  libobs                              0x0000000102ffaeec tiny_tubular_task_thread + 184
	26  libsystem_pthread.dylib             0x000000019570f2e4 _pthread_start + 136
	27  libsystem_pthread.dylib             0x000000019570a0fc thread_start + 8
)
zsh: trace trap  /Applications/OBS.app/Contents/MacOS/OBS`

**Comment by PatTheMav** [comment] 2024-10-18 17:15
Please fix the formatting of your post - it should've been obvious to you that this wall of text will not be helpful.

**Comment by angeloruggieridj** [comment] 2024-10-18 17:54
> Please fix the formatting of your post - it should've been obvious to you that this wall of text will not be helpful.

updated.

**Comment by PatTheMav** [comment] 2024-10-18 18:04
Looks like a duplicate of #11116, already fixed by #11165.

**Closed by PatTheMav** 2024-10-18 18:04 UTC

**Comment by angeloruggieridj** [comment] 2024-10-18 18:06
> Looks like a duplicate of #11116, already fixed by #11165.

Thanks. When it will be available as fix?

**Comment by PatTheMav** [comment] 2024-10-18 18:14
Should be included in the current beta of OBS 31.
