### ISSUE TITLE
Multiview window isn't decorated under Wayland

### ISSUE THREAD

**Issue by rmnvgr** [obsproject/obs-studio#4434] opened 2021-04-02 19:30 UTC
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

Git

### OBS Studio Version (Other)

26.1.2-338-g62bc8f905

### OBS Studio Log URL

https://obsproject.com/logs/jZz2LT7S1elozSI4

### Expected Behavior

The multiview window has a titlebar.

### Current Behavior

The multiview window is not decorated, and so cannot be dragged around.

### Steps to Reproduce

1. Open OBS under a Wayland session
2. Open a multiview window (View → Multiview (windowed))

CC @GeorgesStavracas

**Comment by RytoEX** [comment] 2021-04-02 19:56
There are a multitude of unresolved QTBUGs regarding Wayland.  Please check their issue queue to see if this problem exists there.

**Comment by kkartaltepe** [comment] 2022-11-16 21:31
pretty sure this is a dupe of #6283 the multi-view is a projector window iirc.

**Comment by Fenrirthviti** [comment] 2024-10-14 22:46
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

**Closed by Fenrirthviti** 2024-10-14 22:46 UTC
Labels: Linux

**Comment by kkartaltepe** [comment] 2024-10-15 00:54
fyi it is a dupe of https://github.com/obsproject/obs-studio/issues/6283

**Comment by Fenrirthviti** [comment] 2024-10-15 00:55
Duplicate of https://github.com/obsproject/obs-studio/issues/6283
