### ISSUE TITLE
[macOS] Replay buffer hangs on stopping, `interleaved packets` never sent.

### ISSUE THREAD

**Issue by CaptainTeemo** [obsproject/obs-studio#10202] opened 2024-02-05 09:41 UTC
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Sudlj8CVDGdOIFjs

### Expected Behavior

Replay buffer stopped.

### Current Behavior

Replay buffer not stopped.

### Steps to Reproduce

<img width="690" alt="Screenshot 2024-02-05 at 5 36 46 PM" src="https://github.com/obsproject/obs-studio/assets/4487505/e6455861-f8c6-4a77-b33a-2bed746eddbf">

1. set the encoder.
2. start recording.
3. start replay buffer.
4. press hotkey to stop replay buffer for several times.
5. the button is showing `stopping replay buffer` forever.
...

### Anything else we should know?

<img width="1010" alt="Screenshot 2024-02-05 at 5 39 54 PM" src="https://github.com/obsproject/obs-studio/assets/4487505/d0a2d2be-0253-4864-859c-f4bf9f9fe4d4">

As far as I know, the `initialize_interleaved_packets` always return false in when the issue occurs. So the output will never call `deactivate`.

**Comment by PatTheMav** [comment] 2024-02-17 17:19
Duplicate of #7249.

**Closed by PatTheMav** 2024-02-17 17:19 UTC
