### ISSUE TITLE
Screen shifted in diagonal

### ISSUE THREAD

**Issue by antro31** [obsproject/obs-studio#7742] opened 2022-11-09 14:57 UTC
### Operating System Info

macOS 10.15

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/IkLj7yzSb9bxS2di

### Expected Behavior

While previewing the capture, I was expecting to have a smooth image like this. 

<img width="330" alt="Capture d’écran 2022-11-09 à 15 47 53" src="https://user-images.githubusercontent.com/22416813/200863593-202cc040-109a-482e-b1a4-5c0d68c6c85f.png">

### Current Behavior

Hi OBS Support, 

On latest version, I have a weird behavior displaying screen content. 
It looks like there is a small shift on some pixels on the display

(Look at l, e and top of the g in the following capture). There is a kind of pixel shift done.
<img width="429" alt="Capture d’écran 2022-11-09 à 15 52 15" src="https://user-images.githubusercontent.com/22416813/200862905-e4574594-f337-4864-bee2-d9a96e221954.png">

This shift looks to be a screen diagonal from top left to bottom right. 

This does not happen on 28.0.3

### Steps to Reproduce

1. Open preview window from any source on OBS
2. Check what is displayed around diagonal from Top Left to Bottom Right. 
3.
...

**Comment by Fenrirthviti** [comment] 2022-11-09 17:13
Can you confirm if you actually tested with multiple source types? The log file you posted shows that you're only using a capture card. Are you capturing another display with this capture card? Does this also happen with Window or Display capture? If this is only happening with the capture card, it's likely an issue with the card itself.

**Comment by antro31** [comment] 2022-11-09 18:00
I have tested it only with my capture card. 
Why would it be an issue with the capture card since the issue is not present when using OBS 28.0.3 ?

**Comment by antro31** [comment] 2022-11-11 17:14
Hi, 
I did some tests early today. 
I tried to change both the resolution or frequency, no change, issue is still present on 28.1.2, but not on 28.0.3. 
 
I tried to change the capture source with my webcam. No problem with the webcam.
So overall seems to be linked to the capture card (HD 60S+), but why is there this issue with 28.1.2 and not on 28.0.3?

**Comment by spitford** [comment] 2022-12-08 21:40
I'm having the same problem. I've got a GameCube with an HDMI adapter, (GCHD-Mkii), going into an elgato HD60 S+. The problem is present with my Nintendo Switch as well, but harder to see. The problem is present on 28.1.2 as well as 29.0.0 beta 2, (I haven't tried beta 1).

In the pictures below you can see clearly in the top left and bottom right of the first image as well as in the L and O there is some diagonal glitching. The exact same feed going into Elgato GameCapture software at the same time doesn't have the tearing.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/13268688/206571430-a525788d-2393-4843-9bc3-9b3e336acb73.png">

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/13268688/206572244-e6921fe3-dbaf-4cf7-8e50-dc8e80d8ed71.png">

**Comment by ChrKopp** [comment] 2023-01-31 20:57
Can confirm that I have the same problem with OBS 29.0.0 on macOS 13.1. The same capture card and source captured with QuickTime does not have this issue, see screenshots below:
![image](https://user-images.githubusercontent.com/124094758/215880650-39ce1d6b-28bf-4cf2-8401-a6bd8609c464.png)
![image](https://user-images.githubusercontent.com/124094758/215881291-c903f735-10d8-4d9a-ae24-b61fb4379c21.png)

**Comment by Crazy-Ivan** [comment] 2023-02-10 12:25
I Have the same problem with OBS 29.0.2 on mac. Tested on an external DSLR camera and the mac internal one. Every video source has that diagonal glitch.

**Comment by derrod** [comment] 2023-02-10 15:00
@Crazy-Ivan @ChrKopp please provide logs and information on what capture card(s) you're using.

**Comment by RytoEX** [comment] 2023-02-10 15:04
For those who can reproduce this, please:
1. Post a full OBS log file from a session where this occurs.
2. Confirm that the problem _is not present_ in OBS Studio 28.0.3.
3. Give the specific name, make, and model of your video device (capture card or video camera).
4. Verify whether not the issue is present in beta/rc releases for 28.0, 28.1, and 29.0.
5. Verify if the issue is visible in recordings as well as the OBS preview.

There were _very_ few changes for macOS between 28.0 and 28.1, so this is perplexing.

**Comment by spitford** [comment] 2023-02-13 19:41
I can confirm that the last version this was _not_ present in was 27.2.4. I will try to post logs tonight.

> I'm having the same problem. I've got a GameCube with an HDMI adapter, (GCHD-Mkii), going into an elgato HD60 S+. The problem is present with my Nintendo Switch as well, but harder to see. The problem is present on 28.0 Beta as well as 29.0.0 beta 2, (I haven't tried beta 1).
>

**Comment by gxalpha** [comment] 2023-02-13 22:25
As said before, if you see this problem please also confirm that it's not just in the preview but also the recording, and provide the other info requested [above](https://github.com/obsproject/obs-studio/issues/7742#issuecomment-1425932455).

**Comment by staanemer** [comment] 2023-04-04 16:06
Hi, same issue on four different Macs, all behave the same.

1) Log File:
----------------
17:48:47.086: [macOS] Permission for audio device access granted.
17:48:47.098: [macOS] Permission for video device access granted.
17:48:47.110: [macOS] Permission for accessibility granted.
17:48:47.122: [macOS] Permission for screen capture granted.
17:48:47.122: CPU Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
17:48:47.122: CPU Speed: 2660MHz
17:48:47.122: Physical Cores: 6, Logical Cores: 12
17:48:47.122: Physical Memory: 49152MB Total
17:48:47.122: OS Name: macOS
17:48:47.122: OS Version: Version 12.6 (Build 21G115)
17:48:47.122: Rosetta translation used: false
17:48:47.122: Kernel Version: 21.6.0
17:48:47.123: hotkeys-cocoa: Using layout 'com.apple.keylayout.German'
17:48:47.123: Current Date/Time: 2023-04-04, 17:48:47
17:48:47.123: Browser Hardware Acceleration: true
17:48:47.123: Qt Version: 6.4.1 (runtime), 6.4.1 (compiled)
17:48:47.123: Portable mode: false
17:48:47.343: OBS 29.0.2 (mac)
17:48:47.343: ---------------------------------
17:48:47.345: ---------------------------------
17:48:47.345: audio settings reset:
17:48:47.345: 	samples per sec: 48000
17:48:47.345: 	speakers:        2
17:48:47.345: 	max buffering:   960 milliseconds
17:48:47.345: 	buffering type:  dynamically increasing
17:48:47.346: ---------------------------------
17:48:47.346: Initializing OpenGL...
17:48:47.426: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon RX 580 OpenGL Engine
17:48:47.426: OpenGL loaded successfully, version 4.1 ATI-4.8.101, shading language 4.10
17:48:47.959: ---------------------------------
17:48:47.959: video settings reset:
17:48:47.959: 	base resolution:   1920x1080
17:48:47.959: 	output resolution: 1280x720
17:48:47.959: 	downscale filter:  Bicubic
17:48:47.959: 	fps:               60/1
17:48:47.959: 	format:            NV12
17:48:47.959: 	YUV mode:          Rec. 709/Partial
17:48:47.959: NV12 texture support not available
17:48:47.959: P010 texture support not available
17:48:47.960: Audio monitoring device:
17:48:47.960: 	name: Standard
17:48:47.960: 	id: default
17:48:47.960: ---------------------------------
17:48:47.974: No AJA devices found, skipping loading AJA UI plugin
17:48:47.974: Failed to initialize module 'aja-output-ui'
17:48:47.987: No AJA devices found, skipping loading AJA plugin
17:48:47.987: Failed to initialize module 'aja'
17:48:47.990: Failed to load 'en-US' text for module: 'decklink-captions'
17:48:47.993: Failed to load 'en-US' text for module: 'decklink-output-ui'
17:48:48.017: Decklink API Compiled version 11.6
17:48:48.017: Decklink API Installed version 11.7
17:48:48.352: [VideoToolbox encoder]: Adding VideoToolbox encoders
17:48:48.417: [obs-browser]: Version 2.19.0
17:48:48.417: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
17:48:48.459: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
17:48:48.459: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.4.1 | Qt version (run-time): 6.4.1
17:48:48.459: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
17:48:48.468: [obs-websocket] [obs_module_load] Module loaded.
17:48:48.479: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
17:48:48.480: ---------------------------------
17:48:48.480:   Loaded Modules:
17:48:48.480:     vlc-video
17:48:48.480:     text-freetype2
17:48:48.480:     rtmp-services
17:48:48.480:     obs-x264
17:48:48.480:     obs-websocket
17:48:48.480:     obs-vst
17:48:48.480:     obs-transitions
17:48:48.480:     obs-outputs
17:48:48.480:     obs-filters
17:48:48.480:     obs-ffmpeg
17:48:48.480:     obs-browser
17:48:48.480:     mac-virtualcam
17:48:48.480:     mac-videotoolbox
17:48:48.480:     mac-syphon
17:48:48.480:     mac-capture
17:48:48.480:     mac-avcapture
17:48:48.480:     image-source
17:48:48.480:     frontend-tools
17:48:48.480:     decklink
17:48:48.480:     decklink-output-ui
17:48:48.480:     decklink-captions
17:48:48.480:     coreaudio-encoder
17:48:48.480: ---------------------------------
17:48:48.481: ==== Startup complete ===============================================
17:48:48.509: Switched to Preview/Program mode
17:48:48.509: ------------------------------------------------
17:48:48.563: All scene data cleared
17:48:48.563: ------------------------------------------------
17:48:48.829: coreaudio: Device 'BlackHole 16ch' [44100 Hz] initialized
17:48:48.829: [Loaded global audio device]: 'Desktop-Audio'
17:48:48.860: coreaudio: Device 'Built-in Line Input' [44100 Hz] initialized
17:48:48.860: [Loaded global audio device]: 'Mikrofon-/AUX-Audio'
17:48:48.906: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mikrofon-/AUX-Audio)
17:48:48.906: 
17:48:48.989: Videoaufnahmegerät: Selected device 'OBSBOT Tiny 4K Camera'
17:48:48.992: Videoaufnahmegerät: Using preset 1280x720
17:48:49.131: Switched to scene 'Szene'
17:48:49.134: ------------------------------------------------
17:48:49.134: Loaded scenes:
17:48:49.134: - scene 'Szene':
17:48:49.135:     - source: 'Videoaufnahmegerät' (av_capture_input)
17:48:49.135: ------------------------------------------------


2) Confirmed: no issue with 28.0.3 and 27.2.4.
Tested 28.1, 29.0, 29.0.1, 29.0.2

3) All Video Device affected: different USB Webcams, Insanity Pro 4K, Decklink Quad HDMI

4) Beta 29.1 seems not available for Mac

5)Yes, also visible in recordings

This shift isn't visible with 29.0.2 ARM Version.

**Comment by trus0und** [comment] 2023-04-19 05:29
Can confirm I am seeing this issue on Intel but not on ARM as well. macOS 13.3.1 with Elgato HD60S+.

**Comment by VladFreimann** [comment] 2023-04-28 11:24
I can confirm the same happens, but for me only using iPhone 14 Pro Max in Continuity Camera mode. In Zoom and other apps the camera won't have this problem. What are the solutions for this?

**Comment by ChrKopp** [comment] 2023-04-29 08:18
> 1. Right click on the source in the preview and reset transform to start with the unaltered source.
> 2. Double click on the source to open its properties.
> 3. Change "High" to the highest available resolution in the drop down list.
> 4. Click ok.
> 5. Resize the source to fit onto the canvas by dragging it (not via the transform -> fit to screen option)
> 
> Diagonal glitching lines are now gone.

At least for me this procedure does not fix the problem. I've tried different resolution settings after reseting the transformation and the glitch is visible in all of them. Even the source preview in the properties setting is showing the glitch. As already mentioned this is not a hardware problem, captures with QuickTime for example are fine.

**Comment by RytoEX** [comment] 2023-04-30 01:40
The common items in each log reported so far are:
1. Apple Mac system
2. Intel CPU
3. AMD GPU
4. OBS 28.0+ (or OBS 28.1+)

If you are experiencing this issue, please confirm these details:
1. Post a full OBS log file from a session where this issue occurs.
2. Confirm whether the issue is present in OBS Studio 28.0.3 on the affected system(s).
3. Provide the specific name, make, and model of your video device (capture card or video camera).
4. Verify whether not the issue is present in beta/rc releases for 28.0, 28.1, 29.0, and 29.1.
5. Verify if the issue is visible in recordings as well as the OBS preview.

It sounds like this only affects Intel-based Mac systems. What I am mostly curious about now is verifying the oldest version of OBS where this starts occurring.

**Comment by trus0und** [comment] 2023-04-30 05:08
Okay, so super interestingly, running OBS 29.0.2 on my MacPro7,1 with Radeon Pro W5700X does not exhibit this issue. Will continue to dig!

**Comment by trus0und** [comment] 2023-05-01 03:16
Actually, it has happening on my MacPro7,1 (2019) I just couldnt see it in the same spot. 

<img width="88" alt="Screenshot 2023-05-01 at 1 15 18 pm" src="https://user-images.githubusercontent.com/31195494/235396738-796ff641-ecfb-4032-8ec5-f8578d15fb68.png">

Log: https://obsproject.com/logs/rqUaekXiC4ALqIu2

**Comment by VladFreimann** [comment] 2023-05-01 13:48
Well, I tried installing OBS Studio 28.0.3, and now the line is gone!

iMac 2019 
Intel i9
Radeon Pro 570X 4 ГБ

On 29.0.2 the line was visible.

**Comment by RytoEX** [comment] 2023-05-01 17:02
What I'd really like to confirm is:
1. Does this occur in OBS Studio 28.0.1?
2. Does this occur in OBS Studio 28.1.0-beta1?

Specifically those versions. That would narrow down the changes we'd have to check.

**Comment by VladFreimann** [comment] 2023-05-01 18:13
> What I'd really like to confirm is:
> 
> 1. Does this occur in OBS Studio 28.0.1?
> 2. Does this occur in OBS Studio 28.1.0-beta1?
> 
> Specifically those versions. That would narrow down the changes we'd have to check.

1. The line didn't occur in OBS Studio 28.0.1
2. The line occured in OBS Studio 28.1.0-beta1, same line as in 29.0.2

**Comment by spitford** [comment] 2023-05-03 03:58
I did have the line in 28.0.1

> I'm having the same problem. I've got a GameCube with an HDMI adapter, (GCHD-Mkii), going into an elgato HD60 S+. The problem is present with my Nintendo Switch as well, but harder to see. The problem is present on 28.0 Beta as well as 29.0.0 beta 2, (I haven't tried beta 1).
> 
> In the pictures below you can see clearly in the top left and bottom right of the first image as well as in the L and O there is some diagonal glitching. The exact same feed going into Elgato GameCapture software at the same time doesn't have the tearing.
> 
> <img alt="image" width="1158" src="https://user-images.githubusercontent.com/13268688/206571430-a525788d-2393-4843-9bc3-9b3e336acb73.png">
> 
> <img alt="image" width="1632" src="https://user-images.githubusercontent.com/13268688/206572244-e6921fe3-dbaf-4cf7-8e50-dc8e80d8ed71.png">

**Comment by staanemer** [comment] 2023-05-05 12:53
I really cannot follow what is the sense of your doing, bacpiano.

You can clearly read here and also in other threads, that this glitch occurs with different display in different resolutions on every live camera input. Cables doesn't matter, input devices doesn't matter and so on.

Also on Decklink Output the digonal shift appears directly.

**Comment by gxalpha** [comment] 2023-05-05 13:02
As an update here, we were finally able to reproduce the issue on our side. We were able to find where it was introduced, and a fix has been proposed (follow Pull Request #8851 for progress on that).

> I really cannot follow what is the sense of your doing, bacpiano.

@staanemer This type of comment is not appreciated. As of the time of the comment you're referencing, we were still stabbing in the dark about the problem, and any and all data given to us was helpful. Telling people that what they're doing is useless is quite rude. It implies that you're of the opinion that you already had all the data available and that any other comments are wrong, which was not the case.

**Closed** 2023-05-06 23:31 UTC

**Comment by staanemer** [comment] 2023-05-20 19:03
@gxalpha tank you for your confirmation.
