### ISSUE TITLE
Average time to render frames >10 times slower in studio mode than single window (dropping frames)

### ISSUE THREAD

**Issue by gebi** [obsproject/obs-studio#3880] opened 2020-12-14 14:13 UTC
## Platform

Operating system and version:
debian testing (bullseye/sid) `5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux`

OBS Studio version:
ii  obs-studio     26.0.2+dfsg1-1 amd64        recorder and streamer for live video content
ii  v4l2loopback-dkms 0.12.5-1     all          Source for the v4l2loopback driver (DKMS)

## Expected Behavior
It would be nice if studio mode could be a bit faster than currently (wheras it's 10x slower ).
As it's that much slower i expect there to be a bug somewhere thus i opend this issue.

## Current Behavior
Average time to render frame:
 - single window mode: 1.8ms
 - studio mode: 23ms (and dropping frames from time to time)

## Steps to Reproduce
1. i used a simple scene with just my webcam (with crop&greenscreen as filter)
2. then embed this scene in the animation scenes with background images
3. enable v4l2 (video 4 linux loopback)
4. single window mode frame time 1.8ms
5. switch to studio mode >20ms (and dropping frames from time to time)

## Additional information
logitech web C930e

obs config:
 - base resolution 1080p
 - scaled down to 720p

working hw acceleration:
```
% vainfo
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.9.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.4.2 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

**Comment by mufunyo** [comment] 2020-12-14 14:35
As far as I know, performance on Intel HD Graphics is about as good as it's going to get, the hardware is just severely underpowered. There have been countless patches the past two years shaving microseconds off compositing steps, improving performance on Intel slightly each step. But the fact of the matter is that studio mode has two preview panes (preview and program) and Intel just doesn't have the fill rate to keep up. I strongly suggest upgrading to a discrete GPU.

**Comment by energizerfellow** [comment] 2020-12-23 07:49
@gebi What specific Intel CPU model is this? Can you attach an OBS log file?

**Comment by gebi** [comment] 2020-12-23 13:45
I don't think it's about the principle performance and cpu / gpu hardware (and hw acceleration), because

  - i can start OBS 2 times, feed one into another with full 1080p and still have only `1.3ms` render time in both
  - If i activate studio mode on anyone of them, time to render is 10times slower
  - (i'm not sure HW acceleration is even used here, because i don't "stream" but just mirror to loopback video device for video conference use, and as seen in the screenshots it is not related if loopback output is enabled or not)

maybe vsync? or something else blocking each other?
it does not seem to be CPU usage related, the cpu usage is a few % so it must be something blocking each other in studio mode, as 2 separate obs instances don't show that behaviour

# 2x obs **without** studio mode `1.7ms`
![obs_studio_mode_disabled](https://user-images.githubusercontent.com/659/103000983-67f63b80-452c-11eb-8ac9-4b70bb01110b.jpeg)

# 2x obs with studio mode **enabled** `17.6ms`
![obs_studio_mode_enabled](https://user-images.githubusercontent.com/659/103000986-69276880-452c-11eb-8d8a-80727e695316.jpeg)

HW is an `Intel(R) Core(TM) i7-8550U CPU` (4 cores / 8 HT) running at 3GHz in a Lenovo T480.
obs log: https://gist.github.com/gebi/23e2992fce0c12b40e4b6abbfa0355e0

btw... performance of OBS with studio mode is _really_ great, thus i think it is a bug somewhere that in studio mode you get only 1/10 of the speed ;)!

**Comment by admshao** [comment] 2020-12-23 19:33
Hello Michael!

Is it possible for you to run it on latest obs 26.1 and check if still happens.

If so, Would you be able to also try v25?

**Comment by admshao** [comment] 2020-12-23 19:57
I'm using a discrete AMD gpu with:

libva 2.10
Xserver 1.20.10
mesa 20.3.1
llvm 11.0
DRM 3.39
kernel 5.9

non studio mode = 0.3ms render time
Studio modo = 0.9ms render time

I'm inclined to agree with @mufunyo on this one as this might be something stressing your iGPU.

Does it happens on older versions of OBS? 25 or 24?

**Comment by gebi** [comment] 2020-12-24 16:27
yes i can try reproducing it on older and newer versions of obs (i'll have to check how to get obs from outside of debian, maybe it's also something related to their dfsg free version which always gives problems...)

though @admshao did you look at the screenshots? there is IMHO now way it can be cpu or gpu related when there is no slowdown with two separate obs studios running with the same workload and it's not doing worse when both of them are running in studio mode.

**Comment by energizerfellow** [comment] 2020-12-24 18:26
On a possibly related note, I've seen some rumblings about macOS having a similar level of performance degradation for Studio vs non-Studio modes.

**Comment by dodgepong** [comment] 2020-12-24 19:49
The Mac studio mode performance issue disappeared after we upgraded to 5.14 on Mac for v25.

**Comment by admshao** [comment] 2020-12-24 23:00
Definitely not Qt related.

My thinking still aligns with @mufunyo with some bottleneck triggering by either some lib version or obs graphics code.

To the why we cannot discard the fact you are applying many filters which run shaders, you also do rescale output, grab webcam feed and then the studio mode that may put the final straw to hit a possible bottleneck.

If a libobs "issue" downgrading to obs 25 or 24 might  stop this behavior and probably indicate libobs changes (possibly?) Needed.

If a hardware/libs issue. Upgrading the libs or changing the scene might expode it.

Btw, would this happen to you on a blank new scene? Did you already tried increasing one source per time and one filter at a time to see what triggers the render time? This might give a good hint at where the problem might be on your system.

**Comment by gebi** [comment] 2020-12-28 11:46
ok let's go through the list :)

- in the meantime i got an obs-studio update from debian to 26.1, no change in behaviour

- just the raw video without any filters or any rescaling shows the same issues (1.2ms vs >11ms)

- while fiddling with filters i found a strange behaviour, chroma key is by far the slowest BUT it makes a frame rendering time difference of about 6ms in studio mode alone (disabled vs. enabled of only the chroma key filter), in non studio mode the chroma key filter makes only a difference of 0.5ms in rendering time.

**Comment by kkartaltepe** [comment] 2021-05-22 03:42
I cannot replicate this... Personally I think this is likely a vsync related issue similar to what occurs on Mac. I've triggered the vsync issue on linux with OBS and another window (not with studio mode), but its entirely possible this is the user managing to trigger it with just the two previews in studio mode.

**Comment by dodgepong** [comment] 2021-05-22 12:18
> I think this is likely a vsync related issue similar to what occurs on Mac

For the record, the Mac issue was resolved when we upgraded to Qt 5.14.

**Comment by kkartaltepe** [comment] 2021-05-22 17:04
For whatever its worth qt 5.14 is years away from reaching debian users. But maybe that is why I one contributing factor to me being unable to replicate it as Im using qt 5.15

**Comment by danger89** [comment] 2021-10-21 21:14
I'm using Linux Mint 20.2, I got only 13 FPS using VA-API. This has nothing todo with Qt, but everything with OBS.

**Comment by RytoEX** [comment] 2022-10-14 06:17
Ubuntu 22.04 and 22.10 have Qt 5.15 (5.15.3 and 5.15.6, respectively) and Qt 6 (6.2.4 and 6.3.1, respectively). The PPA version of OBS Studio 28 for Ubuntu 22.04 should be built against Qt 6.2.4 while the Flatpak version should be using Qt 6.3.x. Please retest this in OBS Studio 28.0.3 (or newer) and see if this issue is still present.

**Comment by RytoEX** [comment] 2022-10-15 16:36
I am not seeing this on Ubuntu 22.04 with OBS Studio 28.0.3 (via Flatpak). Average time to render frame for a scene with a few color sources with Color Correction filters and a V4L2 source is 1.6-2.0 ms. Enabling Studio Mode increases that to 2.3-2.8 ms.

**Comment by RytoEX** [comment] 2022-11-16 20:13
I'm going to close this per my above comments. I was not able to reproduce this with modern Qt versions. If you still experience this with OBS Studio 28.1.2 (or newer), please comment and can consider whether to reopen this issue or open a new issue.

**Closed by RytoEX** 2022-11-16 20:13 UTC
Labels: Linux
