### ISSUE TITLE
OBS 25 fails to start after upgrade from 24.0.3

### ISSUE THREAD

**Issue by polskafan** [obsproject/obs-studio#2512] opened 2020-03-17 23:07 UTC
## Expected Behavior
OBS 25 should launch after upgrading.

## Current Behavior
OBS 25 crashes on launch after upgrading. It works again after downgrading.

## Steps to Reproduce
Upgrading from OBS 24.0.3 to OBS 25.

A log of the crash can be found [here](https://pastebin.com/FGYc1FMX).

**Comment by WizardCM** [comment] 2020-03-17 23:09
Could you post a standard log from v25 or v24 as well?

1. Press win+r to open the Run dialog
2. Paste the following into the box and hit OK: %APPDATA%\obs-studio\logs
3. Then find the desired log file (usually the latest) and drag/drop it into a comment

**Comment by polskafan** [comment] 2020-03-17 23:12
Sure.

OBS 24.0.3: https://pastebin.com/sdi0wzTZ
OBS 25: https://pastebin.com/wJhUUx5G

**Comment by tielqt** [comment] 2020-03-18 06:50
@polskafan Did you at any point previously install StreamElements' plugin (otherwise known as OBS Live)?

**Comment by WizardCM** [comment] 2020-03-18 06:59
This crash is caused by using a browser source in "local file" mode pointed to a network share without a drive letter. This'll be fixed in an upcoming patch. https://github.com/obsproject/obs-browser/pull/207

**Comment by polskafan** [comment] 2020-03-18 11:29
Removing the source and then upgrading allowed me to start up OBS 25 just fine. Thanks!

**Comment by WizardCM** [comment] 2020-03-20 04:39
Fixed in 25.0.1.

**Closed by WizardCM** 2020-03-20 04:39 UTC
