### ISSUE TITLE
Update wiki/readme related to deb installation

### ISSUE THREAD

**Issue by NakosCeo** [obsproject/obs-studio#11420] opened 2024-10-19 19:35 UTC
### Operating System Info

Ubuntu 24.04

### OBS Studio Version

30.2.3

### OBS Studio Log URL

n/a

### Expected Behavior

The obs wiki should list instructions on how to install using the .deb files in the Releases page:

[Latest Release](https://github.com/obsproject/obs-studio/releases/tag/30.2.3)

Here there are offered 2 deb files for Ubuntu 24.04 (Noble):

1. `obs-studio_30.2.3-0obsproject1.noble_amd64.deb`
2. 'OBS-Studio-30.2.3-Ubuntu-24.04-x86_64.deb'

Both of these target ubuntu noble (24.04) but have different sizes, and unpacking them and reading their control files, it seems they have different requirements as well.

The first i understand is the one the official PPA offers (the one with obsproject in its name), but i cannot find any information on the second one.

It should be made clear, how these two versions differ (different requirements in control file), and which one should someone install on (Ubuntu Noble) if they have not the ability to add the PPA repository and install from there.

### Current Behavior

Two deb files for ubuntu noble, and no relevant information in wiki or Readme.md

### Steps to Reproduce

1. Navigate to [Latest Release](https://github.com/obsproject/obs-studio/releases/tag/30.2.3)
2. Find 2 deb files for Ubuntu 24.04 (Noble)
3. No explanation in wiki or readme

**Comment by tytan652** [comment] 2024-10-19 19:36
Duplicate of #11419

**Closed by tytan652** 2024-10-19 19:36 UTC

**Comment by NakosCeo** [comment] 2024-10-19 19:38
> Duplicate of #11419

Removed Duplicate.

How can i add information to the wiki, if i don't know the differences, and there is no info about it anywhere online?

If a dev could explain what's the difference between the two versions, i volunteer to document it in the wiki.

**Comment by kkartaltepe** [comment] 2024-10-19 19:43
No neither of these are official if you want our official instructions see https://obsproject.com/download#linux

**Comment by NakosCeo** [comment] 2024-10-19 19:49
> No neither of these are official if you want our official instructions see https://obsproject.com/download#linux

Actually 'obs-studio_30.2.3-0obsproject1.noble_amd64.deb' this version is the one the official PPA uses:

[Official PPA Deb amd64 Noble](https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/obs-studio_30.2.3-0obsproject1~noble_amd64.deb)

The sha512 hashes are identical.
