### ISSUE TITLE
Browser Source Overlay Color Incorrect

### ISSUE THREAD

**Issue by adbakke** [obsproject/obs-studio#4642] opened 2021-05-03 16:08 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://obsproject.com/logs/4_fXcsc8VQr98rE8

### Expected Behavior

Color from Browser source should be the same with an image on browser source vs local image source from the same image.

### Current Behavior

Color is off on both hue, brightness.

See screenshot for image example contrast. Version of image on top is Image Source directly imported, version of image on the bottom is from browser source using same image.

![obs-issue](https://user-images.githubusercontent.com/5157757/116901475-fa5bc980-ac07-11eb-889a-369a4e1da050.png)

### Steps to Reproduce

1. Create StreamElements Overlay
2. Import StreamElements overlay as Browser Source using provided URL from StreamElements.
3. Import same image as Image source into OBS Studio
4. Compare differences in color hue, brightness, et cetera

**Comment by dodgepong** [comment] 2021-05-03 16:13
Can you try with the win64 build [here](https://github.com/obsproject/obs-studio/actions/runs/806195387) and see if you have the same issue?

**Comment by derrod** [comment] 2021-05-03 17:18
Duplicate of #4636, results from SE replacing our browser source with their own version that does not have sRGB support.

The latest builds as linked by @dodgepong have a workaround that should make older source plugins render correctly again.

**Comment by adbakke** [comment] 2021-05-03 19:38
> Can you try with the win64 build [here](https://github.com/obsproject/obs-studio/actions/runs/806195387) and see if you have the same issue?

This does actually fix it, thank you.

**Comment by dodgepong** [comment] 2021-05-03 19:40
Thanks for the confirmation!

**Closed by dodgepong** 2021-05-03 19:40 UTC
