### ISSUE TITLE
Replay buffer prefix folder issues

### ISSUE THREAD

**Issue by Senor-bruh** [obsproject/obs-studio#10449] opened 2024-03-28 11:37 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/ZfPIKD2s40M8OuJ1

### Expected Behavior

My replays to be saved in the prefix folder without spaces in front of the names 

### Current Behavior

spaces in front of replay file names.

### Steps to Reproduce

having \Replays\ on replay buffer filename prefix

### Anything else we should know?

[ffmpeg muxer: 'simple_file_output'] Writing file 'C:/Users/808xl/Pictures/Screenshots (ShareX)/Screenshot 2024-03-28 054249.mp4 - normal recording

[ffmpeg muxer: 'Replay Buffer'] Wrote replay buffer to 'C:/Users/808xl/Pictures/Screenshots (ShareX)//Replays/ Screenshot 2024-03-28 020243.mp4 - replay clip

RecRBPrefix=\\Replays\\ - what it looks like in the basic.ini settings file

**Comment by RytoEX** [comment] 2024-03-28 20:51
Duplicate of #4861

**Closed by RytoEX** 2024-03-28 20:51 UTC
