### ISSUE TITLE
Speech synthesis not captured from browser source when "Control audio via OBS" checked

### ISSUE THREAD

**Issue by Morthy** [obsproject/obs-studio#8436] opened 2023-03-09 21:51 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/p63rBKkiKs70mO3y

### Expected Behavior

When using the speechSynthesis HTML5 API, the resulting audio should be captured when "Control audio via OBS" is checked.

### Current Behavior

No sound is captured. Audio is only captured if the browser source audio is not controlled via OBS.

### Steps to Reproduce

1. Create a sample HTML file:

`<html>
<body>
	<script>
		let utterance = new SpeechSynthesisUtterance("Hello world!");
		speechSynthesis.speak(utterance);
	</script>
</body>
</html>`

2. Add the browser source and observe that you hear "Hello world" on every refresh.
3. Change the browser source to "Control audio via OBS" and observe no audio on refresh.

### Anything else we should know?

Not sure if this is an issue with OBS or CEF.

**Comment by derrod** [comment] 2023-03-09 21:52
Duplicate of #8424

**Closed by derrod** 2023-03-09 21:52 UTC
