### ISSUE TITLE
[28.0.0-beta1] OBS crashes when pressing Stop Recording when using AMD AMF

### ISSUE THREAD

**Issue by gutko** [obsproject/obs-studio#6998] opened 2022-08-08 19:14 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://pastebin.com/c4D89KYz

### Expected Behavior

recording stops correctly

### Current Behavior

obs crash with infinite "stopping recording" on stop recording button, process has to be terminated form task manager

### Steps to Reproduce

1.start recording
2.let it run for a while
3.press stop

### Anything else we should know?
rx580 polaris
AMD driver used 22.5.1
game - stalker anomaly mod 1.5.2 in dx11 mode https://www.moddb.com/mods/stalker-anomaly/downloads
log is incomplete because of crash

**Comment by flaeri** [comment] 2022-08-14 15:26
duplicate of https://github.com/obsproject/obs-studio/issues/7047. Merging might be a good idea, so we can keep all data in one place.

**Comment by RytoEX** [comment] 2022-08-15 18:19
Duplicate of #7047

**Closed by RytoEX** 2022-08-15 18:19 UTC
