### ISSUE TITLE
OBS forgets dock heights in Studio Mode on portrait-oriented monitors

### ISSUE THREAD

**Issue by HeyyItsBran** [obsproject/obs-studio#4880] opened 2021-06-12 09:20 UTC
### Operating System Info

Other

### Other OS

Linux Mint 20.1 Cinnamon

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/oKj0okHq4ob0HuaF

### Expected Behavior

When launched on the same monitor it was closed on, OBS should retain heights for all docks
![image](https://user-images.githubusercontent.com/35010179/121771421-2e130300-cb67-11eb-818b-2e881be924aa.png)

### Current Behavior

When launched all docks are set to their minimum height and the preview/program areas are elongated
![image](https://user-images.githubusercontent.com/35010179/121771393-03c14580-cb67-11eb-93fd-0018551665f9.png)

### Steps to Reproduce

1. Move OBS to a portrait monitor
2. Arrange docks as needed
3. File > Exit
4. Re-launch OBS

**Comment by WizardCM** [comment] 2021-06-12 09:25
Duplicate of #2949

**Closed by WizardCM** 2021-06-12 09:25 UTC

**Comment by HeyyItsBran** [comment] 2021-06-12 09:27
> Duplicate of #2949

Sorry didn't spot that one, my Google-Fu is failing me!
