### ISSUE TITLE
26.1 fails to start on MacOS 10.13.6

### ISSUE THREAD

**Issue by LiamK** [obsproject/obs-studio#3956] opened 2020-12-21 23:41 UTC
## Platform
Operating system and version: MacOS 10.13.6
OBS Studio version: 26.1

## Expected Behavior
OBS starts

## Current Behavior
Obs crashes:
**Symbol not found: ____chkstk_darwin**

## Steps to Reproduce
1. Install OBS 26.1 on Macbook Pro (a. from within program, or b) separately using image downloaded from web site)
2. Double-click on program icon
3. After a couple seconds MacOS displays error message saying OBS Studio failed to start.

## Additional information
I reverted to 26.0.2 and it works fine.
Sorry, I don't have the full crash report.

**Comment by WizardCM** [comment] 2020-12-21 23:44
Duplicate of #3887

**Closed by WizardCM** 2020-12-21 23:44 UTC
