### ISSUE TITLE
Media Sources only show/hide once if transitions are enabled

### ISSUE THREAD

**Issue by 40wattrange** [obsproject/obs-studio#4883] opened 2021-06-12 15:37 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Version (Other)

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/nx3jDlNk9uMsgLY9

### Expected Behavior

For window capture to be updated live

### Current Behavior

Window capture is frozen until you hide/show the source - be it a nested scene or the raw scene itself.

### Steps to Reproduce

1. Switch to scene
2. Window captures are frozen
3. Hide source
4. Show source
5. Window capture now behaves as expected.
...

**Comment by RytoEX** [comment] 2021-06-12 16:07
Works fine for me here.  What are you trying to Window Capture?  What source in your scene was frozen?  Was the window you were capturing visible, or minimized?

**Comment by Fenrirthviti** [comment] 2021-06-13 02:53
Probably related to #4878?

**Comment by Lt23live** [comment] 2022-01-31 16:46
This is still an issue. Has anyone solved it?

**Comment by Fenrirthviti** [comment] 2022-02-02 02:12
Can you provide any more information, such as the questions RytoEX asked in the earlier comment?

**Comment by 40wattrange** [comment] 2022-02-02 16:58
I found that the issue is not just limited to window capture - but a lot of things that have show/hide transitions. 

In the following you video you will see the issue:

Transition set to none: Show/Hide as much as you want.
Transition set: show/hide once, never again until you set the transition back to none
Transition set back to none: Show/Hide as much as you want
Transition set back to fade and account for the fade time being less than the video clip time: Only show once

https://www.youtube.com/watch?v=GIEryqtKQG4

**Comment by Fenrirthviti** [comment] 2022-02-02 17:18
Given this new information, this is a duplicate of #5291

This technically came first, but going to close this in favor of the other report as it contains more information and better reproduction steps.

**Closed by Fenrirthviti** 2022-02-02 17:18 UTC
