### ISSUE TITLE
[28 beta2] AMF encoder produces non usable mp4 file

### ISSUE THREAD

**Issue by gutko** [obsproject/obs-studio#7039] opened 2022-08-11 19:31 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://pastebin.com/9nNv2qzu

### Expected Behavior

recorded mp4 file is usable and viewable in VLC

### Current Behavior

recorded mp4 file cant be opened in VLC - not playing at all
windows movies&tv app plays only audio with black screen
shotcut video editor says when trying to drop this file on a video track: not adding non-seekable file
recorded file seems to contain some material as its 4GB for 27 min duration
not able to post the file itself due to bad connection

paste from media info
General
Complete name                            : E:\OBS\2022-08-11_20-35-48.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 3.92 GiB
Duration                                 : 26 min 56 s
Overall bit rate                         : 20.8 Mb/s
Writing application                      : Lavf59.16.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 26 min 56 s
Bit rate                                 : 20.6 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.166
Stream size                              : 3.88 GiB (99%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 26 min 56 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 37.0 MiB (1%)
Title                                    : simple_aac_recording
Default                                  : Yes
Alternate group                          : 1

### Steps to Reproduce

this one seems to be random-ish but
1. start recording
2. stop recording
3. file is corrupt

### Anything else we should know?
rx580 polaris
driver 22.7.1
game - dying light 1 steam
also happened on driver 22.5.1 with 28-beta1 running as admin with different game

**Comment by flaeri** [comment] 2022-08-11 19:47
Cannot reproduce the issue on a 4500u, driver 22.5.1. There are some confusing aspects to the media info you showed.

I experienced some odd issues on the latest driver in so far as the encoder goes, and if it's not too much trouble, could you try downgrading to 22.5.1 and see if things improve?

By the way, I assume this happens on every recording? Or just once in a while?

**Comment by RytoEX** [comment] 2022-08-11 20:06
I am unable to reproduce this on an AMD Radeon RX 6600M running driver 22.5.1. Recordings look fine in VLC.

**Comment by gutko** [comment] 2022-08-11 20:15
as I said it happened before on 22.5.1 with different game - stalker anomaly mod
maybe its related to polaris, 4500u is vega, 6600m is navi, will downgrade to 22.5.1 and run some tests
it seemed randomish on 22.5.1 and beta1

**Comment by RytoEX** [comment] 2022-08-11 20:48
Please try the stable AMD driver 22.5.1 and OBS Studio Beta 2 or newer.

**Comment by gutko** [comment] 2022-08-11 21:11
> Please try the stable AMD driver 22.5.1 and OBS Studio Beta 2 or newer.

I will

**Comment by gutko** [comment] 2022-08-11 23:09
Ok I think I have more info to share now
This seems to be related to alt-tabbing when obs is already running and game was started
1. start obs
2. start game
3. alt-tab (ctrl+esc combination may be required) to check obs window if it captures game
4. alt-tab back to game
5. start recording
6. play a while
7. stop recording
8. file is corrupt

it was not a case with v27
driver 22.5.1 this time
game - dying light 1 steam

log https://pastebin.com/DxTCWFgh

Media Info

General
Complete name                            : E:\OBS\2022-08-12_00-44-22.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 2.75 GiB
Duration                                 : 8 min 3 s
Overall bit rate                         : 48.9 Mb/s
Writing application                      : Lavf59.16.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 8 min 3 s
Bit rate                                 : 48.7 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.391
Stream size                              : 2.74 GiB (100%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 8 min 3 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 11.1 MiB (0%)
Title                                    : simple_aac_recording
Default                                  : Yes
Alternate group                          : 1

**Comment by RytoEX** [comment] 2022-08-12 00:15
Could you please provide a sample video file that is corrupted?

**Comment by gutko** [comment] 2022-08-12 00:36
> Could you please provide a sample video file that is corrupted?

will try to capture something very small to push trough very limited mobile connection later
meanwhile heres is ffprobe of last 2,75GB file

E:\OBS>ffprobe -i 2022-08-12_00-44-22.mp4
ffprobe version 5.1-full_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001890232e200] stream 0, missing mandatory atoms, broken header
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001890232e200] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none(tv, bt709), 1920x1080): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2022-08-12_00-44-22.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:08:03.24, start: 0.000000, bitrate: 48871 kb/s
  Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), none(tv, bt709), 1920x1080, 60 fps, 90k tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]

**Comment by flaeri** [comment] 2022-08-14 16:04
I highly suspect this is going to end up being a duplicate of https://github.com/obsproject/obs-studio/issues/7047.

If you wouldn't mind trying to confirm (can you make it happen without game capture)?

Does the workaround solve the issue (use settings > output > rescale (different resolution than output(scaled)))

**Comment by gutko** [comment] 2022-08-15 13:29
> I highly suspect this is going to end up being a duplicate of #7047.
> 
> If you wouldn't mind trying to confirm (can you make it happen without game capture)?
> 
> Does the workaround solve the issue (use settings > output > rescale (different resolution than output(scaled)))
did you mean this is a workaround?
![Screenshot 2022-08-15 132740](https://user-images.githubusercontent.com/1101181/184644276-30225446-b0b1-4c18-993c-24bb63419cfe.jpg)

**Comment by flaeri** [comment] 2022-08-15 17:48
Only the action in the 2nd screenshot. Output > recording > rescale output. 

The resolution needs to be different from screenshot one (set that back to 1920x1080)

**Comment by jp9000** [comment] 2022-08-22 19:38
May be fixed now that #7047 is fixed

**Comment by Johl7** [comment] 2022-08-24 15:11
Ive done some testings today, on short recordings its mostly always fine... but around 5 min+ it will at most times result in a non usable mp4(only audio)

**Comment by gutko** [comment] 2022-08-24 18:13
> May be fixed now that #7047 is fixed
Waiting for rc2 to run some tests

**Comment by flaeri** [comment] 2022-08-24 22:11
rc1: repro once, after 7 tries x 10min

0e7f69ee3 (after latest changes to muxer and AMF): repro once, after 3 tries x 10min

It's a pain to reproduce, but it would seem it is unlikely its related to https://github.com/obsproject/obs-studio/issues/7047 :(

**Comment by gutko** [comment] 2022-08-25 16:39
reproduced on rc2 on 1st try

log+ffprobe https://pastebin.com/WKUQWQxU

**Comment by Ja-boop** [comment] 2022-08-26 03:24
Hello, this still happens to me, with rc2

**Comment by gutko** [comment] 2022-08-26 12:40
after last repro I switched to mkv and It went ok. not sure if because change of format or randomness of the issue

**Comment by flaeri** [comment] 2022-08-30 17:42
After the latest modifications to the AMD encoder (07df6548fdb88e093eb0901106a882ad73ad9848), I am no longer able to reproduce this issue. Over 2 hours, and some 14+ 10min+ attempts.

**Comment by Johl7** [comment] 2022-08-30 18:39
> After the latest modifications to the AMD encoder ([07df654](https://github.com/obsproject/obs-studio/commit/07df6548fdb88e093eb0901106a882ad73ad9848)), I am no longer able to reproduce this issue. Over 2 hours, and some 14+ 10min+ attempts.

Some days ago i also ran some tests with multiple settings and doin 10min+ recs... could not repro the issue, allthou at first when i first download the lag related build i managed to repro, but since rebooting the system i couldnt repro anymore.

**Comment by RytoEX** [comment] 2022-08-31 03:00
Based on internal tests and user reports, we're going to consider this Issue fixed by https://github.com/obsproject/obs-studio/commit/07df6548fdb88e093eb0901106a882ad73ad9848.

**Closed by RytoEX** 2022-08-31 03:00 UTC
