### ISSUE TITLE
Apple M1 VT Hardware Encoder (audio) fails Facebook stream with "Limit bitrate" enabled

### ISSUE THREAD

**Issue by kellemar** [obsproject/obs-studio#4670] opened 2021-05-08 07:02 UTC
### Operating System Info

macOS 11.3

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://gist.github.com/kellemar/64412d39920a76b059b5d8cb424f5022

### Expected Behavior

On Macbook Pro 13" Apple Silicon:

When VT Hardware Encoder is selected, and "Start Streaming" is clicked, OBS should connect to Facebook Live successfully.

### Current Behavior

No connection is made. However, x264 and VT Software Encoder works.

### Steps to Reproduce

1. In settings -> Output, select VT Hardware Encoder under the Advanced tab.
2.Leave settings as default.
3. Exit settings screen, and click on Start Streaming.

**Comment by WizardCM** [comment] 2021-05-08 07:05
What do you mean by "no connection is made"? Does an error appear? Did you wait longer than the 10 second test streram in your log?

**Comment by kellemar** [comment] 2021-05-16 11:32
Actually, this also happened with "Limit Bitrate" unchecked. Anyway I found the problem had to do with DIsabling B-frames.

With B-frames disabled, I wouldn't see anything on the stream, even though the Stream Health shows some data being sent. Enabling B-frames fixed the issue.

This issue doesn't occur on VT Software and x264 encoding.

**Comment by RytoEX** [comment] 2021-05-16 14:17
> 
> 
> Actually, this also happened with "Limit Bitrate" unchecked. Anyway I found the problem had to do with DIsabling B-frames.
> 
> With B-frames disabled, I wouldn't see anything on the stream, even though the Stream Health shows some data being sent. Enabling B-frames fixed the issue.
> 
> This issue doesn't occur on VT Software and x264 encoding.

If it's related to b-frames, these are the only places that option is used, for anyone's reference:
https://github.com/obsproject/obs-studio/blob/6a9f25c8ea1b244b4a439667be33f4a5cc6cdf4b/plugins/mac-vth264/encoder.c#L319-L321
https://github.com/obsproject/obs-studio/blob/6a9f25c8ea1b244b4a439667be33f4a5cc6cdf4b/plugins/mac-vth264/encoder.c#L671-L673

**Comment by LPFchan** [comment] 2021-06-27 05:26
Does this issue have to do with why VT Hardware Encoder can't limit the bitrate at all? 

No matter what I set the target & limit bitrate to, VT Hardware Encoder would immediately burst up to 100~350Mbps and overload itself after a while. (I'm a feed from my mirrorless camera with Cam Link in 4K)

**Comment by AuroraWright** [comment] 2021-12-29 21:55
For what it's worth this also applies to recording instead of streaming. "Limit bitrate" produces an empty file. Also, not being able to limit bitrate eventually makes the bitrate spike very high and the encoder overloads (even on a M1 Max machine), making it pointless for anything but very short streams/recordings.

**Comment by AuroraWright** [comment] 2022-01-03 04:05
Apparently, "limit bitrate" is actually somewhat working but after 5 or so seconds of encoding (between 5 and 6 seconds as far as I can tell) the OBS output blackscreens (and, in case of local recordings, saves an empty file after stopping). I've managed to get a couple clips by stopping the recording just before it would hang with several bitrate limits and the file size matched the limit I set.

**Comment by LPFchan** [comment] 2022-01-03 11:55
https://www.reddit.com/r/MacOS/comments/nfn98o/comment/h37uqhe/

Hey, a while ago I've asked the same question to one of the dev who complied native arm64 OBS and here's what he had to say. Thought it might be helpful to you:

> It is because of how the M1 handles CPU clock Cycles.
> It is one of the reasons OBS is not yet out officially for M1 yet. They are waiting for the next version of QT to be released.

**Comment by WizardCM** [comment] 2022-01-03 12:43
Qt and the VT encoder are unrelated.

**Comment by hardy-yan** [comment] 2022-01-17 12:10
Hey guys, I have found another problem on the M1's Hardware Encoder.

If the FPS in OBS is set to fractional FPS, like 29.97 / 59.94, the encoder bitrate will gone wrong that make the Kbps inside OBS behaves like Mbps, makes me think it somehow got multiplied by 1000 by two times for bps. All integer FPS seems to work fine for me.

I have tried to set it to 50 Kbps and it turns out a 50 Mbps stream, and I have the GStreamer Plugin that could use the hardware encoder with more settings, I tried to set the bitrate to 4 (bitrate=4) in extra encoder options, and it worked out a 4000 Kbps stream.

Somehow I believe that's something wrong on Apple / MacOS side, but I am not techie enough to properly talk about the issue.

**Comment by AuroraWright** [comment] 2022-01-17 12:12
macOS is fine, ffmpeg can use HW encoding without issues

**Comment by RytoEX** [comment] 2022-01-18 02:31
> Hey guys, I have found another problem on the M1's Hardware Encoder.
> 
> If the FPS in OBS is set to fractional FPS, like 29.97 / 59.94, the encoder bitrate will gone wrong that make the Kbps inside OBS behaves like Mbps, makes me think it somehow got multiplied by 1000 by two times for bps. All integer FPS seems to work fine for me.
> 
> I have tried to set it to 50 Kbps and it turns out a 50 Mbps stream, and I have the GStreamer Plugin that could use the hardware encoder with more settings, I tried to set the bitrate to 4 (bitrate=4) in extra encoder options, and it worked out a 4000 Kbps stream.
> 
> ~Somehow I believe that's something wrong on Apple / MacOS side, but I am not techie enough to properly talk about the issue.~

That sounds distinctly separate from this Issue.  Please open a new Issue so that can be tracked separately.  Please include detailed steps-to-reproduce and an OBS log from an affected session.  If possible, please reproduce this in a vanilla OBS installation with no third party plugins.  We may ask for a sample media file and/or how you determined the output file's bitrate, so you may wish to include those in advance, if possible.

**Comment by RytoEX** [comment] 2022-01-19 05:22
@kellemar Now that #5809 is merged, I encourage you to try one our recent automatic CI builds to see if it resolves your issue.

Here is the link to the build for that change:
https://github.com/obsproject/obs-studio/suites/4972408406/artifacts/144997675

**Comment by Shirk** [comment] 2022-01-26 12:52
> @kellemar Now that #5809 is merged, I encourage you to try one our recent automatic CI builds to see if it resolves your issue.
> 
> Here is the link to the build for that change: https://github.com/obsproject/obs-studio/suites/4972408406/artifacts/144997675

Testing with a native M1 arm64 build from the current trunk this PR absolutely fixed the issue for streaming with 'limit bitrate' enabled. Previously streaming to Twitch (1080p@60, 6000kbit limit) would create 0kbit streams on Twitch's end. Now it's working fine and respecting the bitrate limit:
![image](https://user-images.githubusercontent.com/304352/151166033-5ebdb02c-7e3e-46c7-8b21-46847f8f9915.png)

(ignore the 0fps, it was a bandwidth test stream)

I can't reproduce the severe frame drop / log that was mentioned here or in the PR personally - but then again I'm running a native arm64 build and not on Rosetta so that might affect things. The only frame drop I got was 0.01% from Render lag and that's down to my overlay.

**Comment by AuroraWright** [comment] 2022-01-26 13:10
@Shirk I get the framedrops with a native arm64 build (M1 Max/macOS 12.1) with 1080p60 output (and any bitrate) so that's interesting, maybe it also depends on the SoC then. Could you post all your VT settings?
Anyway as I noted in issue https://github.com/obsproject/obs-studio/issues/5840 this seems to be due to the RealTime property which slows down the encoder a lot (I noticed the same thing happening with ffmpeg actually) and delays stay generally minimal without it in my experience, or minimal enough that OBS handles them. Quality is also (seemingly) higher without it, so I'll try to make it selectable and make a PR.

**Comment by Shirk** [comment] 2022-01-26 13:14
Sure - this are my settings:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/304352/151169140-39dcb1a4-f0e4-4217-bd50-eb7921ecda98.png">

I could probably remove the "Rescale Output" by now as it's a rescale from 1080p _to_ 1080p which is pointless.

**Comment by AuroraWright** [comment] 2022-01-26 13:28
Tried replicating your settings (also have 1920x1080 60fps set as canvas size) and can confirm, no dice as long as RealTime is set.

**Comment by Shirk** [comment] 2022-01-26 13:33
Very interesting, I've looked at the other Issue and I'm going to and disable the realtime flag in my local sources as mentioned there and see if it makes any difference for me (given I didn't experience your issue so far).

**Comment by RytoEX** [comment] 2022-01-28 12:08
> I could probably remove the "Rescale Output"

"Rescale Output" forces the encoder to rescale the output post-compositing and pre-encode, which I believe is done on CPU.  I don't know if there's a check to attempt to avoid said rescaling if the resolutions (base->scale) are the same.  Generally speaking, we recommend turning it off if you don't need it.

When posting settings, or when confirming an issue, please post an OBS log.  It will show the settings in there.

Please also note my observations [[1](https://github.com/obsproject/obs-studio/pull/5809#issuecomment-1015507665), [2](https://github.com/obsproject/obs-studio/pull/5809#issuecomment-1016095880)] about the changes in PR #5840 and how they may or may not related to the "Use B-Frames" setting as well as [this Issue Reporter's observations](https://github.com/obsproject/obs-studio/issues/4670#issuecomment-841804623) about the setting.  I'm still not convinced this is just one or the other causing these issues to surface, and I think we're diverging into several separate, but contributing, factors.

**Comment by RytoEX** [comment] 2022-07-24 15:12
I'm fairly certain that the original issue reported has been fixed, per the above comments. If there are other, distinct issues with the VT Hardware Encoder, please open those as new Issues. If the original Issue as described in the first post is observed again, please feel free to comment here, and we can reopen this Issue if need be.

**Closed by RytoEX** 2022-07-24 15:12 UTC
Labels: macOS, Confirmed
