### ISSUE TITLE
Pasting multiple sources puts the bottom source at the top of the pasted sources

### ISSUE THREAD

**Issue by Warchamp7** [obsproject/obs-studio#7685] opened 2022-10-29 16:25 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

N/A

### Expected Behavior

The copied sources are pasted in the same order they were in when copied

### Current Behavior

The bottom most source in the list of copied sources is placed at the top of the pasted sources

### Steps to Reproduce

1. Create three sources named 1, 2 and 3 top to bottom
2. Copy all three sources

![image](https://user-images.githubusercontent.com/1554753/198842337-1d0896c5-b90e-4338-bb0c-3514a4c3b470.png)

3. Paste all three sources

Result: 3 is at the top of the list, followed by 1 and then 2 in proper order.
![image](https://user-images.githubusercontent.com/1554753/198842363-f4e1cb07-c6e3-4258-97ea-bc796edb5203.png)

Happens with any number of sources. All sources in the correct order except the bottom one, which is placed at the top

![image](https://user-images.githubusercontent.com/1554753/198842444-ffb4eace-8d39-42fb-ac92-4c09e1613f3e.png)
![image](https://user-images.githubusercontent.com/1554753/198842466-fb3b332b-7ae8-4514-87b7-58b66cf6c232.png)

**Comment by tuduweb** [comment] 2022-10-30 10:45
from qt doc https://doc.qt.io/qt-6/qitemselectionmodel.html#selectedIndexes
The `QItemSelectionModel::selectedIndexes()` results is not sorted.

This cause unexpected behavior.
So I think this result should be sorted manually to make sure the order is correct.

**Comment by PatTheMav** [comment] 2022-11-02 11:53
Duplicate of #4016 - see my comment about it: https://github.com/obsproject/obs-studio/issues/4016#issuecomment-1292290832

It works as expected given our implementation - if we want to retain an internal logical order, we’d have to implement code for that and retain that information in the data sent/retrieved via the clipboard.

**Comment by tuduweb** [comment] 2022-11-03 16:56
@PatTheMav I just edit my PR #7687 , could you please review it again, thx!

**Closed** 2023-02-15 22:09 UTC
