### ISSUE TITLE
[Flatpak] Opening the file browser crashes OBS on Manjaro

### ISSUE THREAD

**Issue by SarenDev** [obsproject/obs-studio#10702] opened 2024-05-20 16:45 UTC
### Operating System Info

Other

### Other OS

Manjaro Linux, 6.9.0-1

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/JkfskKZ2Onvi7fkT

### OBS Studio Crash Log URL

Not generated

### Expected Behavior

Opening the file browser for a selection, like picking a recording path or selecting media to import, should show the file picker and allow selection.

### Current Behavior

Opening the file browser briefly hangs OBS, then exits with a SIGSEGV. This occurs with any instance of the file picker.

### Steps to Reproduce

1. Open the "Profile" menu in the menu bar
2. Select "Import" or "Export"
3. Experience a short freeze, followed by a SIGSEGV

### Anything else we should know?

The system is running KDE 6.0.4

Debugging the Flatpak with the built-in GDB reveals a segfault occurring in /usr/lib/x86_64-linux-gnu/libQt6Core.so.6. The full error is:

```text
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff33b1ae2 in QMetaType::convert(QMetaType, void const*, QMetaType, void*) ()
   from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
```
A stack trace is attached, though it appears to contain a lot of duplicates:

[gdb-trace.tar.gz](https://github.com/obsproject/obs-studio/files/15379526/gdb-trace.tar.gz)

I also tested the Flatpak on Fedora 40 with the same version of KDE, and the issue did not occur there.

**Comment by derrod** [comment] 2024-05-20 16:48
Duplicate of #10683

**Closed by derrod** 2024-05-20 16:48 UTC
