### ISSUE TITLE
[BUG] cmake doesn't define variables for libobs-frontend-api.so and other libraries except for libobs.so

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2660] opened 2020-04-05 21:00 UTC
## Platform
Operating system and version: FreeBSD 12.1 (but this is not a FreeBSD problem)
OBS Studio version: 25.0.3

## Expected Behavior
Install cmake files that detect ```libobs-frontend-api.so``` (and other libraries).

## Current Behavior
```lib/cmake/LibObs/LibObsConfig.cmake``` allows to use ```libobs.so``` by using ``` ${LIBOBS_LIBRARIES}``` but there are no equivalents for ```libobs-frontend-api.so``` and other libraries installed by OBS Studio.

**Comment by Xaymar** [comment] 2020-04-05 21:02
Duplicate of #2625. Two different PRs are available to fix, one adds .cmake and .pc files, the other doesn't. See #2635 (headers only) and #2650 (headers + cmake + pc).

**Comment by Fenrirthviti** [comment] 2020-04-26 06:07
Closing as dupe of #2625. Please provide any additional updates on that PR.

**Closed by Fenrirthviti** 2020-04-26 06:07 UTC
Labels: Duplicate
