### ISSUE TITLE
Vitrual Cam's Picture Black

### ISSUE THREAD

**Issue by buduan** [obsproject/obs-studio#7171] opened 2022-08-23 06:04 UTC
### Operating System Info

macOS 12

### Other OS

macOS

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/1gKXEuFQvGuGhOa3

### Expected Behavior

Output the OBS's Scene to Meeting App.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/39254250/186082051-a8f772db-ee84-4eef-9f2f-5881d44592c5.png">

### Current Behavior

When I chose _OBS Virtual Cam_ as my camera, the output picture was black.

### Steps to Reproduce

1.Edit Scene
2.Start Virtual cam
3.choose OBS Virtual Cam in Dingtalk
4.Black!
...

### Anything else we should know?

I've tried it on Dingtalk and Telegram.All black

**Comment by Voring** [comment] 2022-09-08 11:10
我今天手贱更新了28版本的obs也是无法正常输出画面，原来好像是25版本的，之前一直正常使用，现在我试试旧版本的吧。

**Comment by PatTheMav** [comment] 2022-09-14 13:13
Possible duplicate of https://github.com/obsproject/obs-studio/issues/7333.

**Closed** 2022-09-21 15:04 UTC
Labels: macOS
