### ISSUE TITLE
OBS does not run smoothly with browser recording

### ISSUE THREAD

**Issue by UnixCro** [obsproject/obs-studio#3948] opened 2020-12-20 18:04 UTC
I use OBS under OSX , everything runs smoothly for me and without any problems be it streaming or recording, as soon as I make a browser recording, it runs unnecessarily and often does not play videos.

Anyone ideas?

**Comment by dodgepong** [comment] 2020-12-20 18:52
What is a browser recording?

Please do not delete the issue template. It's important that you fill it out.

**Comment by UnixCro** [comment] 2020-12-21 09:42
Hi, thanks for your reply,

I mean with browser recording, a recording in OBS where you can enter your URL and OBS is filmed directly from the website.

This service is totally unreliable and hangs up all the time. It doesn't matter which graphics setting I set ...

Everything is going fine except for the website recording.

I look forward to your answer

**Comment by WizardCM** [comment] 2020-12-21 09:45
Duplicate of https://github.com/obsproject/obs-browser/issues/209

**Closed by WizardCM** 2020-12-21 09:45 UTC

**Comment by UnixCro** [comment] 2020-12-21 14:22
Many thanks WizardCM!
