### ISSUE TITLE
SIGSEGV on running obs

### ISSUE THREAD

**Issue by Jark5455** [obsproject/obs-studio#8204] opened 2023-02-03 17:42 UTC
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

29.0.1

### OBS Studio Log URL

unable to access

### OBS Studio Crash Log URL

unable to access

### Expected Behavior

I expected OBS to open

### Current Behavior

OBS hits a sigsegv error on launch

### Steps to Reproduce

1. Execute the command `obs` in the terminal

### Anything else we should know?

gdb output

```
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Registered pretty printers for UE4 classes
Reading symbols from obs...

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org 
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
(No debugging symbols found in obs)
(gdb) start 
Temporary breakpoint 1 at 0x88e58
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, 0x00005555555dce58 in main ()
(gdb) c
Continuing.
[New Thread 0x7fffe37b06c0 (LWP 6974)]
[New Thread 0x7fffe20536c0 (LWP 7026)]
[New Thread 0x7fffe18526c0 (LWP 7027)]
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: AMD Ryzen 5 3600 6-Core Processor
info: CPU Speed: 3767.894MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 15919MB Total, 3721MB Free
info: Kernel Version: Linux 6.0.5-3-rt14-MANJARO
info: Distribution: "Manjaro Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffe0c9c6c0 (LWP 7174)]
[New Thread 0x7fffcbfff6c0 (LWP 7175)]
info: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
info: Portable mode: false
[New Thread 0x7fffcb7fe6c0 (LWP 7210)]
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.0-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffcaffd6c0 (LWP 7211)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 525.85.05, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffc9aff6c0 (LWP 7351)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fffb78156c0 (LWP 7352)]
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
[Detaching after fork from child process 7353]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 7360]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 7365]
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 7369]
[New Thread 0x7fffb70146c0 (LWP 7401)]
[Detaching after fork from child process 7402]
[Detaching after fork from child process 7403]
[Detaching after fork from child process 7404]
[Detaching after fork from child process 7405]
[Detaching after fork from child process 7406]
info: [pipewire] No captures available
[Detaching after fork from child process 7407]
[Detaching after fork from child process 7408]
[Detaching after vfork from child process 7409]
warning: v4l2loopback not installed, virtual camera disabled
[Detaching after fork from child process 7411]
info: NVENC supported

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
XDisplayString (dpy=0x0) at /usr/src/debug/libx11/libX11-1.8.3/src/Macros.c:119
119	char *XDisplayString(Display *dpy) { return (DisplayString(dpy)); }
(gdb) c
Continuing.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffb70146c0 (LWP 7401) exited]
[Thread 0x7fffc9aff6c0 (LWP 7351) exited]
[Thread 0x7fffcaffd6c0 (LWP 7211) exited]
[Thread 0x7fffcb7fe6c0 (LWP 7210) exited]
[Thread 0x7fffcbfff6c0 (LWP 7175) exited]
[Thread 0x7fffe0c9c6c0 (LWP 7174) exited]
[Thread 0x7fffe18526c0 (LWP 7027) exited]
[Thread 0x7fffe20536c0 (LWP 7026) exited]
[Thread 0x7fffe37b06c0 (LWP 6974) exited]
[Thread 0x7fffe3922100 (LWP 5350) exited]
[Thread 0x7fffb78156c0 (LWP 7352) exited]
[New process 5350]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by tytan652** [comment] 2023-02-03 17:50
Duplicate of #8056

**Closed by tytan652** 2023-02-03 17:50 UTC
