### ISSUE TITLE
Potrait Mode Screen Capturing return blank image on Windows 11

### ISSUE THREAD

**Issue by Kaitoukid93** [obsproject/obs-studio#5434] opened 2021-10-21 12:10 UTC
### Operating System Info

Other

### Other OS

Windows 11

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/YCFgARw-PTO-u2n-

### Expected Behavior

The Rotated picture should have shown despite being cutted in a half, as in Windows 10, I just need to change the Canvas Size to match the Potrait mode (1080*1920)

### Current Behavior

Blank Image
![Screenshot (343)](https://user-images.githubusercontent.com/40384831/138273899-a7aee074-2af7-45b2-aaae-b7034a834d0e.png)

### Steps to Reproduce

1.Open OBS
2.Add Screen Capture Source
3.Change Display Orientation in Windows Settings
4.Go back to OBS and see Blank Image

### Anything else we should know?

Desktop Duplication API return null when trying to Acquire Next Frame in Windows 11, I think so...

**Comment by WizardCM** [comment] 2021-10-21 12:17
Verified on a Surface Book 2, but it's specific to DXGI Display Capture. WGC works fine. Additionally, rotating back to normal makes the display capture reappear.

**Comment by anton19286** [comment] 2021-11-15 04:23
Same on TightVNC https://sourceforge.net/p/vnc-tight/bugs/1567/ and UltraVNC

**Comment by WizardCM** [comment] 2022-05-26 06:47
Looks like Microsoft have released a fix for this in [Windows 11 Build 22000.706](https://blogs.windows.com/windows-insider/2022/05/19/releasing-windows-11-build-22000-706-to-the-release-preview-channel/), which is currently in the Release Preview channel.

As it is confirmed to be an issue on Microsoft's end and should be fixed for users soon, I'm closing this issue. Thanks again for the report!

**Closed by WizardCM** 2022-05-26 06:47 UTC
Labels: Windows, Dependency Issue, Confirmed
