### ISSUE TITLE
Scene json corruption

### ISSUE THREAD

**Issue by bardiir** [obsproject/obs-studio#4002] opened 2021-01-02 21:12 UTC
## Platform
Operating system and version: Mac Mini M1 with BigSur
OBS Studio version: 26.1.0 (Mac)

## Expected Behavior
I should be able to close and reopen OBS when I did no changes to anything.

## Current Behavior
I've got a json configuration that does break when loading it into OBS.
So if I place this (working.json) from the archive into my scenes folder and start OBS it works just fine. Close it down, start it back up and it crashes. So the scenes settings got corrupted just by loading and unloading it.
I'll go deeper into debugging what exactly changed in the json once I find a good tool to diff json content.

## Steps to Reproduce
[Archiv.zip](https://github.com/obsproject/obs-studio/files/5760858/Archiv.zip)
Load working.json into the scenes directory - probably best to also rename it to Twitch.json
Start OBS (working), Close OBS, Start OBS (crash)

## Additional information
I will update if I find any further information. Currently my closest thing to an additional hint is that it is depending on the browser captures - if I Start OBS, remove all browser Inputs, Close OBS, Open it again it will still work. So the process of having the browser Captures there seems to bug OBS out.
I've seen that there are issues with Browser capture on Big Sur anyway, maybe this is related and can provide input towards fixing the underlying issue by comparing what exactly is being loaded between the two json versions because when I load the working one browser captures just work fine, no crashes etc - just hell of a memory leak if there are css animations present.

**Comment by Fenrirthviti** [comment] 2021-01-02 21:21
Can you please also include the crash details?

**Comment by notr1ch** [comment] 2021-01-02 21:23
As you have audio monitoring enabled, this is likely https://github.com/obsproject/obs-studio/issues/3095

**Comment by bardiir** [comment] 2021-01-02 21:29
> Can you please also include the crash details?
[crash.log](https://github.com/obsproject/obs-studio/files/5760893/crash.log)

> As you have audio monitoring enabled, this is likely #3095
Possibly - I was just hoping it might offer some insight what might be happening for that bug and how to maybe work around it for the time being with an example file that corrupts via OBS just loading/unloading.

**Comment by Fenrirthviti** [comment] 2021-01-02 21:32
Crash log confirms it, going to close this one as it should be fixed by next release.

Duplicate of #3095

**Closed by Fenrirthviti** 2021-01-02 21:32 UTC
