### ISSUE TITLE
[OBS Studio 28.0.0 / 28.0.1] Crashing on Intel Macs at startup

### ISSUE THREAD

**Issue by enyineer** [obsproject/obs-studio#7327] opened 2022-09-09 06:55 UTC
### Operating System Info

Other

### Other OS

MacOS 12 + 13 Beta 6

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://pastebin.com/Rti0NmVG

### Expected Behavior

The application should start without crashing.

### Current Behavior

The application crashes on startup with some of our Intel Macs on MacOS 12 and 13. M1 Macs seem to not have this problem. We're running OBS behind corporate proxies which is why I can't upload the OBS Studio Log URL. The crash happens in the "WhatsNewInfoThread" which could be a proxy problem maybe. Some systems do have Extranet proxies configured, some don't.

### Steps to Reproduce

1. Install OBS on Intel Mac
2. Start OBS
3. Crash occurs

### Anything else we should know?

I opened this for our IT department. If any more info is needed I'll ask them to provide such info.

**Comment by WizardCM** [comment] 2022-09-11 00:03
Fixed in 646d47aacb8614c00cd9c5895323c0c5ee4b3c3f

Note: This is caused by the "What's New" dialog failing to fetch either by a firewall or manipulation between OBS and our servers.

**Closed by WizardCM** 2022-09-11 00:03 UTC
Labels: Confirmed
