### ISSUE TITLE
Set Source Color not undoable

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#7367] opened 2022-09-13 02:35 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/SYodXmSUZoLd2yzk

### Expected Behavior

Pressing ctrl-z should undo a source color change. By source color, i mean the color in the Sources Panel.

### Current Behavior

It doesn't get undone, and only the previous action is undone.

### Steps to Reproduce

1. Toggle a source visibility so we can see what is being undone.
2. Set a source color.
3. Press ctrl-z. Only step 1 will be undone and the source color remains intact.
...

**Comment by RytoEX** [comment] 2022-09-13 11:56
I cannot reproduce this. I changed a color source's color, saved the settings by clicking OK in each dialog, and pressed Control+Z and the color was undone exactly as expected.

**Comment by RytoEX** [comment] 2022-09-13 12:11
It has been clarified to me that this is about the highlight colors of sources in the Sources Dock. This is not something Undo-Redo was ever designed to track. Undo-Redo is for tracking changes to sceneitems represented inside the OBS preview.

Closing this as working as intended.

**Closed by RytoEX** 2022-09-13 12:11 UTC
