### ISSUE TITLE
Pipewire camera-portal failed to create session.

### ISSUE THREAD

**Issue by shetozz** [obsproject/obs-studio#10366] opened 2024-03-13 15:39 UTC
### Operating System Info

Other

### Other OS

Fedora 39 workstation eddition

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/hoz27k6zbwRle0mv

### Expected Behavior

Creating a camera source using pipewire should ask for user permission till the user accepts it, then it should remember the choice.

### Current Behavior

It asked for the permission once, AFAIK I guaranteed it the permission to access the webcam, but it's tilling me it failed to create session denied or canceled by user, so I might be wrong and I denied it.
Anyway, it should ask me when I try to add it a second time after denying it access the first time.

### Steps to Reproduce

1. Install the flatpak
2. Start a Wayland session
3. Create a new camera source using pipewire
...

### Anything else we should know?

This terminal output was consistent across multiple trials

```shell
error: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): '[' or '{' expected near end of file
error: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): '[' or '{' expected near end of file
info: User added source 'Video Capture Device (PipeWire) (BETA)' (pipewire-camera-source) to scene 'المشهد 4'
info: [camera-portal] Selected resolution for ''
info: [camera-portal] Selected format for ''
info: [camera-portal] selected camera ''
warning: [camera-portal] Failed to create session, denied or cancelled by user
```

**Comment by kkartaltepe** [comment] 2024-03-13 16:14
> Anyway, it should ask me when I try to add it a second time after denying it access the first time.

This is not something OBS can control, if you find that the portals do not prompt you as expected or prompt you more than you expect you must file a change request to the portal implementation you are using.

Otherwise ill let someone else follow up if this should be closed as a support request. Id recommend you go to our support channels anyway at the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum).

**Comment by shetozz** [comment] 2024-03-13 16:46
I reported it here because the portal functions as expected even with other OBS permissions, so I thought it's fine.

**Comment by GeorgesStavracas** [comment] 2024-03-14 22:34
This is not a bug nor something that OBS Studio can control. OBS Studio requests the Camera portal for permission to use cameras, if the permission was denied, the portal will return that.

**Closed by GeorgesStavracas** 2024-03-14 22:34 UTC
