### ISSUE TITLE
OBS not open

### ISSUE THREAD

**Issue by dennis-rocha** [obsproject/obs-studio#10338] opened 2024-03-06 14:58 UTC
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.1.0-rc1

### OBS Studio Version (Other)

Version: 30.0.1-0obsproject1~jammy

### OBS Studio Log URL

OBS not open. I can't get the URL

### Expected Behavior

I need use OBS Studio.

### Current Behavior

At first I was getting errors and I managed to solve them with tutorials:
> obs: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory
> obs: error while loading shared libraries: libicuuc.so.56: cannot open shared object file: No such file or directory
> obs: error while loading shared libraries: libicudata.so.56: cannot open shared object file: No such file or directory

Now I'm getting this error:
> obs: symbol lookup error: /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6: undefined symbol: _ZN11QLocaleData19bytearrayToLongLongEPKciPb, version Qt_6

### Steps to Reproduce

1. When I try to open it, it won't open.

### Anything else we should know?

On Monday (2024-03-04) I opened it up to do some recording tests. But on Tuesday (2024-03-05) I couldn't open it. I think it may be related to PyQt, which I uninstalled and installed on Tuesday to record lessons for my students.

**Comment by RytoEX** [comment] 2024-03-15 22:33
Qt broke ABI between 6.6.1 and 6.6.2, so anything previously built against 6.6.1 must be rebuilt it against 6.6.2. If it's a package ask the packager to rebuild it.

For future reference, OBS always writes logs to `~/.config/obs-studio/logs` on Linux, and you should be able to open/upload them manually.

**Comment by RytoEX** [comment] 2024-03-15 22:33
Duplicate of #10280

**Closed by RytoEX** 2024-03-15 22:33 UTC
