### ISSUE TITLE
OBS starts with the new "safe mode" prompt after reboot

### ISSUE THREAD

**Issue by achilleasang** [obsproject/obs-studio#9877] opened 2023-11-16 12:48 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/fxexE3Ua8kKr4mvJ

### Expected Behavior

I have OBS always launch at system startup and stay idle until I start recording with a hotkey. Shutting down/rebooting the PC while OBS is running (idle, no stream/recording active) is what I've been doing for a while with no issues before 30.0.0. 

### Current Behavior

After 30.0.0, on reboot OBS displays the "start in safe mode" prompt, which is annoying and needless. 

### Steps to Reproduce

1. Start OBS
2. Reboot PC while OBS is running

### Anything else we should know?

Ideally I think OBS should handle a system shutdown gracefully, but at least an option to disable the safe mode prompt would be a quick solution.

**Comment by tiberium-v** [comment] 2023-11-16 13:05
you can start obs with `--disable-shutdown-check`. See https://obsproject.com/kb/launch-parameters

**Comment by SnowmanDK** [comment] 2023-11-21 12:22
Although "--disable-shutdown-check" works, it should not be needed, when all you do, is shut down the computer normally, and start it up again.
In my opinion this is still a bug, especially since it didn't exist before v30.

**Comment by Valiant-0** [comment] 2023-11-23 15:34
Commenting as I run OBS for the Replay Buffer function on startup and I keep getting this message.

**Comment by remizik** [comment] 2023-11-27 08:43
I also have this issue since a few days/weeks. (Win 11)
Thanks @tiberium-v for the "--disable-shutdown-check" argument.

**Comment by Pingumania** [comment] 2023-11-27 18:32
Two logs where I closed the app manually and one where I just shut down Windows 10.

[close-app_2023-11-27 19-24-54.txt](https://github.com/obsproject/obs-studio/files/13478948/close-app_2023-11-27.19-24-54.txt)
[os-shutdown_2023-11-27 19-13-53.txt](https://github.com/obsproject/obs-studio/files/13478949/os-shutdown_2023-11-27.19-13-53.txt)

**Comment by Mikilio** [comment] 2023-12-16 13:35
Hi there, I run OBS as a systemd service on Linux and on this world it is supposed to exit cleanly on a SIGTERM. However it does not. 

Running 30.0.2

**Comment by Fenrirthviti** [comment] 2023-12-16 18:32
> Hi there, I run OBS as a systemd service on Linux and on this world it is supposed to exit cleanly on a SIGTERM. However it does not.
> 
> Running 30.0.2

OBS is a user application, not a service, and being run this way is not supported. Additionally, the original report here is for Windows, not Linux.

**Comment by Mikilio** [comment] 2023-12-17 14:27
Im not doing anything exotic here. When I toggle the setting in OBS for autostartup it essentially gets started as a systemd service. A "user application" also needs to try and exit gracefully after a SIGTERM as should any executable. Even if it does not it makes no sense to throw a warning at the user for closing it with a SIGTERM.

Do you prefer having a new issue just for Linux? I believe this is solvable cross-plattform.

**Comment by Fenrirthviti** [comment] 2023-12-17 20:51
If it can be reproduced running OBS normally, feel free to submit a report. Windows does not handle process termination the same as Linux, so while "safe mode shows up" might be a commonality the solution/problem is not the same.

As a note, the safe mode works simply by creating a watchdog file that is removed on shutdown. Something is killing the process before the cleanup step can happen is what's causing these triggers. It's very likely that even though these reports are recent, this unclean shutdown has been happening for years; we just now detect it.

**Closed** 2024-01-24 04:01 UTC
