### ISSUE TITLE
WHIP usage forces CBR regardless of rate control settings or "Ignore recommendations"

### ISSUE THREAD

**Issue by trysdyn** [obsproject/obs-studio#9753] opened 2023-10-24 10:20 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/tvOBVacXJqBDBtuz

### Expected Behavior

Configuring VBR or CQP along side WHIP should either actually utilize VBR or CQP, prevent these from being set to begin with, or throw a notification explaining that they cannot work.

### Current Behavior

Attempting to stream via WHIP using VBR or CQP will sliently revert to CBR at encoder start-up time. The only indication this has happened is in the logs.

### Steps to Reproduce

These are the steps I follow verbatim in the session reflected in the uploaded log

1. Create a new profile (mine is named TEST)
2. File->Settings->Stream, change Service to WHIP, no need to configure a server
3. Check "Ignore streaming service setting recommendations" just in case
4. Move to Output, change Output Mode to Advanced
5. Change Rate Control to VBR
6. Okay these changes
7. Record a blank scene for 30 seconds or so
8. Witness in the logs the encoder settings block reports `rate_control: CBR`
9. Inspect the recorded video and witness the constant 2500kbps bitrate; a blank scene should be <100kbps

Now, to pin down WHIP configuration is causing this...

10. Back to Stream, change Service to Custom
11. Begin a second recording
12. Witness in logs the encoder settings block reports `rate_control: VBR`
13. Inspect the recorded video and witness varying bitrate

### Anything else we should know?

As noted: this strikes if you set VBR or CQP. x264 or HVENC h264 are both susceptible.

I've replicated this on a friend's system as part of setting up and testing a private WebRTC backend. Same Windows version, same RC, same replication steps.

If the forced usage of CBR is not a bug, I'd propose a warning when starting stream or saving config that WHIP and VBR don't go together.

For my own use-cases though I'm hoping this is a config-handling bug :)

**Comment by Penwy** [comment] 2023-10-24 10:26
That's standard OBS behaviour, not unique to WHIP.
IF you need to bypass it, select "custom" service in settings > stream.

**Comment by pkviet** [comment] 2023-10-24 11:09
Pinging @Sean-Der on that.

**Comment by Sean-Der** [comment] 2023-10-24 13:46
My assumption is that it is caused by [this](https://github.com/obsproject/obs-studio/blob/master/plugins/obs-webrtc/whip-service.cpp#L36)

I didn't add that code and I don't have in my `reflog` when it was added.

@tt2468 @DDRBoxman Did you add CBR? Any concern with making it so users can override ?

**Comment by RytoEX** [comment] 2023-10-24 18:14
> My assumption is that it is caused by [this](https://github.com/obsproject/obs-studio/blob/master/plugins/obs-webrtc/whip-service.cpp#L36)
> 
> I didn't add that code and I don't have in my `reflog` when it was added.
> 
> @tt2468 @DDRBoxman Did you add CBR? Any concern with making it so users can override ?

Code was part of the initial PR here (by @kc5nra on December 14, 2022):
https://github.com/obsproject/obs-studio/commit/06925ebec53ab12a21cc43de9f27be6466d895ae#diff-1cfaa4ed324cf1ed7fa2d16dacdae6d1d396dbab7c85260db16f863af08ed531R79-R87

Slightly modified here (force pushed by @tt2468 on December 15, 2022):
https://github.com/obsproject/obs-studio/commit/f90b2c73df83a5551d50e739bb931982512a977f

Code was moved from plugins/obs-webrtc/webrtc-service.c to plugins/obs-webrtc/whip-service.c here (force pushed by @kc5nra on December 15, 2022):
https://github.com/obsproject/obs-studio/commit/3c714f83b7a1e73ab1e43b171bc3ea2f10267387#diff-1cfaa4ed324cf1ed7fa2d16dacdae6d1d396dbab7c85260db16f863af08ed531

Code was moved from plugins/obs-webrtc/whip-service.c to plugins/obs-webrtc/whip-service.cpp here (force pushed by @tt2468 on March 8, 2023):
https://github.com/obsproject/obs-studio/compare/62fffc4f65ea28855821e599dfb002fe137c3759..598599ff09eaa20be3833d691c4874bf95085f12#diff-2238f6f0763ee16377b0d2e261bbefdf75d1f372748719bb8ef2d84b1fa1302fL76-L81
https://github.com/obsproject/obs-studio/compare/62fffc4f65ea28855821e599dfb002fe137c3759..598599ff09eaa20be3833d691c4874bf95085f12#diff-a547b9ec99c6534ce9e367002852f6f597997c7d4233c7476ffb2c26afae2479R29-R35

----

As for why this would be applied, OBS applies CBR by default to RTMP-based services entries as CBR is generally preferred by service providers (and the network providers in between, as far as I know). This was likely done to mirror that decision, so it's most likely intentional. While there has been some previous discussion on the subject, this is not something we'll change lightly or quickly.

**Comment by alinsavix** [comment] 2023-10-24 18:42
> As for why this would be applied, OBS applies CBR by default to RTMP-based services entries as CBR is generally preferred by service providers (and the network providers in between, as far as I know). This was likely done to mirror that decision, so it's most likely intentional. While there has been some previous discussion on the subject, this is not something we'll change lightly or quickly.

WHIP isn't RTMP, though, and it's not a service.

Though the reporter's complaint isn't that it defaults to CBR, it's that *it forces CBR even when told to ignore the provider's recommended settings* (even though there's no provider in use). OBS forces CBR and does not give the user any way to change that, which is something that isn't the case for RTMP even when the provider recommends it. This behavior is actually a regression compared to existing RTMP functionality, not a desire for new functionality or a fundamental change.

**Comment by RytoEX** [comment] 2023-10-24 21:12
> > As for why this would be applied, OBS applies CBR by default to RTMP-based services entries as CBR is generally preferred by service providers (and the network providers in between, as far as I know). This was likely done to mirror that decision, so it's most likely intentional. While there has been some previous discussion on the subject, this is not something we'll change lightly or quickly.
> 
> WHIP isn't RTMP, though, and it's not a service.

To provider fuller context to my abbreviated answer, substitute "RTMP-based services" with "streaming outputs" or "streaming services/outputs" in my answer. The use of "RTMP-based services" was used to explain _where_ the code originated (RTMP-based outputs do this already). In the context of OBS code, WHIP is a "WHIP Service" (WHIPService or whip_custom).

Rate Control is not an ignorable recommended setting. Things that can be ignored are those that can be specified in the "recommended" key in `plugins/rtmp-services/data/services.json`:
* keyint
* profile
* bitrate matrix
* max video bitrate
* bframes
* x264opts
* max audio bitrate

See here for these implementations in RTMP-based outputs:
* https://github.com/obsproject/obs-studio/blob/5cf0f06669189196f2c1b28c9ccbd56034538f3d/plugins/rtmp-services/rtmp-common.c#L656-L726

See here for the current services.json schema:
* https://github.com/obsproject/obs-studio/blob/5cf0f06669189196f2c1b28c9ccbd56034538f3d/plugins/rtmp-services/data/schema/service-schema-v5.json#L100-L196

> Though the reporter's complaint isn't that it defaults to CBR, it's that _it forces CBR even when told to ignore the provider's recommended settings_ (even though there's no provider in use). OBS forces CBR and does not give the user any way to change that, which is something that isn't the case for RTMP even when the provider recommends it. This behavior is actually a regression compared to existing RTMP functionality, not a desire for new functionality or a fundamental change.

RTMP has behaved this way in OBS for years, if not forever. Checking "Ignore streaming service setting recommendations" (or its predecessor) does not, and has never as far as I know, allowed overriding CBR. WebRTC/WHIP output has behaved this way since the merged PR was opened. This is not a regression.

**Comment by alinsavix** [comment] 2023-10-24 22:01
See attached log of OBS being more than happy to do a VBR (over RTMP) connection to twitch when overridden. [2023-10-24 14-50-49.txt](https://github.com/obsproject/obs-studio/files/13127777/2023-10-24.14-50-49.txt)

And yes, it's a regression (or at least a bug, but it's probably silly to argue those semantics) if the intent is for it to work exactly like the existing RTMP functionality when, in reality, the existing RTMP functionality does not behave this way (at least according to my log).

If it's intended to exactly match existing functionality, though -- is that to say that *no* streaming protocol is intended to ever support non-CBR? Because if that's the case, changing the setting away from CBR shouldn't even be an *option* in the streaming menu. And if "only CBR" is only an RTMP thing, why is that being arbitrarily forced onto WHIP, when that is in no way a requirement for the protocol (AFAIK) and there's no attached service provider to recommend one way or another?

This feels like an arbitrary limitation that's being swept aside as "RTMP does it too, so it's intentional, it's unlikely we'll change it" when... it really doesn't need to copy the behavior of RTMP and, presumably, there are other streaming protocols that do not have that limitation (because if there was no circumstance where it could be changed, ever, I can't imagine there'd even be an option to change it).

If there isn't a service provider (or protocol requirement) demanding CBR-only, why *wouldn't* it be an option for the user to switch to VBR if it suits their needs?

**Comment by trysdyn** [comment] 2023-10-24 22:32
So from my perspective, it looks like the main issue here is under the definition of what y'all consider a "Service", WHIP isn't one, but is being treated like one to the detriment of configurability. Every other service in the list is actually a *service*, where some maintainer has published a list of ideal streaming conditions you can enforce; WHIP isn't like that.

I see two paths forward here, personally:

1. Allow user configurations to override the hardcoded settings to use CBR. This seems to be getting pushback.
2. Decouple WHIP from the idea of being a service, require providing a URI in the "Custom..." service configuration to do WHIP, add a handler to make OBS understand an HTTP(S) link or similar provided there is a WHIP URL and handle it appropriately.

2 is how raw SRT and RTMP are done currently, so in a way having WHIP as a "Service" deviates from the prior art of how SRT and RTMP are supported.

In any case, the core issue here is at present I am completely incapable of pushing a VBR stream via WHIP, despite my endpoint being capable of handling it. I'll take anything that gets me around that block.

**Comment by Fenrirthviti** [comment] 2023-10-25 03:20
In summary from an off-thread conversation, setting aside precedent and current implementation, this should be possible to change for WHIP. It seems it was likely an oversight that it was set, based on the paradigms that OBS uses for RTMP (which is what is not likely to change at the moment, until services are ready to accept non-CBR content).

While this isn't a bug, and is working as implemented, we welcome a PR to remove the restriction.

**Closed** 2023-10-28 23:15 UTC

**Comment by alinsavix** [comment] 2023-10-28 23:27
Just thought I'd add a quick note -- when I was commenting above about VBR working on RTMP, that *was* actually happening for me (even though it supposedly wasn't possible) -- because I had `ApplyServiceSettings=false` in my profile ini, probably left over from 3 or 4 years ago. That option has since been replaced by `IgnoreRecommended` (which is stricter), but the code still honors `ApplyServiceSettings` even though there's no way to view or (un)set it beyond editing the ini by hand. So I wasn't going insane there, just in case anyone was wondering.
