### ISSUE TITLE
Black screen when recording in nvidia open source driver wayland window

### ISSUE THREAD

**Issue by flowerseacar** [obsproject/obs-studio#10792] opened 2024-06-07 17:40 UTC
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/GcuCPZygx5w4G5tl

### Expected Behavior

Can record in Wayland

### Current Behavior

Recording black screen

### Steps to Reproduce

Under Nvidia's open source driver, Wayland window, Flatpak version of OBS for full screen recording

**Comment by kkartaltepe** [comment] 2024-06-08 00:05
Looks like a dupe of #10409

**Closed by kkartaltepe** 2024-06-08 00:05 UTC

**Comment by kkartaltepe** [comment] 2024-06-09 16:31
As mentioned, please provide a log from your run where you think things are working.
