### ISSUE TITLE
VLC video source greater than 1080p plays back squashed

### ISSUE THREAD

**Issue by jamtasty1** [obsproject/obs-studio#7873] opened 2022-11-28 22:05 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/1dgV5dYCpGL2ldUa

### Expected Behavior

Any media with resolution greater than 1080p when playing back using VLC video source should scale correctly.

### Current Behavior

When playing back media with resolutions above 1080p, VLC video source doesn't read the correct dimensions and plays back squashed.  For example, a 3840x2160 video clip will playback at something like 344x1920. Editing transform settings and trying to adjust to correct dimensions results in pixelated quality on the horizontal resolution. 

### Steps to Reproduce

1. Add media with resolution greater than 1080p to VLC video source
2.
3.
...

**Comment by RytoEX** [comment] 2022-11-28 22:09
Probably a duplicate of either #7763 or #7775. I suspect that the VLC simply struggles to fetch the dimensions of ingested streams, and that this is not new to OBS 28.

**Comment by jamtasty1** [comment] 2022-11-28 22:12
This is when playing back local files, eg. .mp4/.mkv,etc.  This was working fine in OBS 27.

**Comment by flaeri** [comment] 2022-11-28 22:25
I've tested two media files I had lying around. One 2560x1440, and one 3840x2160.

Both played back correctly for me in a VLC source. VLC version 3.0.17.4 Vetinari.

Would it be possible to get a small sample, or a small file that works incorrectly for you, so that I could see if I can reproduce the issue one my end?

**Comment by MattyFresh68** [comment] 2022-11-29 00:00
Looks like their base canvas is 1080p. If a vlc source that's larger resolution is set to fit the canvas, wouldn't that get squished?

**Comment by CoalZombik** [comment] 2022-12-07 11:01
This looks like duplicate of #7667. This problem is caused by unsafe multiplying the width by Sample Aspect Ratio.

**Comment by RytoEX** [comment] 2023-02-15 21:23
Duplicate of #7666

**Closed by RytoEX** 2023-02-15 21:23 UTC
