### ISSUE TITLE
Display capture does not allow to select a different display, when the previously selected one has been disconnected.

### ISSUE THREAD

**Issue by verstaerker-583** [obsproject/obs-studio#4098] opened 2021-01-19 14:30 UTC
## Platform
Operating system and version: macOs Big Sur 11.1
OBS Studio version: 26.1.2

## Expected Behavior
Same behavior as for example video capture: It should always be possible to select a new device, especially when the previously selected one is no longer connected.

## Current Behavior
Display capture source properties just shows "no properties available" and not the dropdown menu required to select a different one, when a previously selected display is no longer connected.

## Steps to Reproduce
Add display capture, select an external display, disconnect the selected display and then try to select a different one. Or just edit the display in the scene json, change "display": = to something not connected.

**Comment by WizardCM** [comment] 2021-01-19 23:37
Duplicate of #4011

**Closed by WizardCM** 2021-01-19 23:37 UTC
