### ISSUE TITLE
OBS don't remember its position. drop menus show in different monitor.

### ISSUE THREAD

**Issue by barsupi** [obsproject/obs-studio#3945] opened 2020-12-20 05:31 UTC
## Version
OBS Studio version: 26.1.0

## Expected Behavior
after close or move the OBS program. the software should remember it's position in the desktop/screen. same for it's drop menus.

## Current Behavior
OBS now always open in the primary monitor. no matter if it was moved and then closed properly.
also  many drop menu do appear floating in the primary monitor if the obs window was moved away from it. 
this didn't happen in v25.x or previous version.

## Steps to Reproduce

1 - open obs
2 - move window to another monitor
3 - open drop any menu: now they float in primary monitor.
--
3 - close OBS & open: it doesn't remember its last position
4 - goes to primary monitor.

## Additional information
- OS win7x64.
- this behavior was not happening in any version before v26
- krita software has this same behavior. it may be some GUI common issue

## Example picture
1
<img width="400px" src="https://i.imgur.com/afKcZNQ.png"/>
2
<img width="400px" src="https://i.imgur.com/vKypxxu.png"/>

**Comment by WizardCM** [comment] 2021-01-05 08:03
Please provide a session log. Help -> Log Files -> Upload Current Log, then post the link.

**Comment by barsupi** [comment] 2021-01-06 08:10
> 
> 
> Please provide a session log. Help -> Log Files -> Upload Current Log, then post the link.

here is it.

https://obsproject.com/logs/2qqugi1kir6GrVCN

**Comment by 1upCAD** [comment] 2021-01-10 23:13
I'm experiencing the exact same issue and would love to see a fix or know what I could do to resolve the issue.

My log file: https://obsproject.com/logs/oV93HoP6hMGFFJeA

**Comment by mgbeers** [comment] 2022-09-10 04:39
I don't know if this issue is still open but i'm experiencing this problem too, only it's not even the primary monitor where the application opens but on my monitor that is #2 of 3 monitors.  This only recently happened.  I uploaded a log file also https://obsproject.com/logs/ULnb6T34LsmVitza

**Comment by RytoEX** [comment] 2022-10-14 05:05
There is more than one issue described in the original post here.

1. OBS now always open in the primary monitor. no matter if it was moved and then closed properly.
2. many drop menu do appear floating in the primary monitor if the obs window was moved away from it.

The second issue _should_ be fixed as of OBS Studio 28. The first issue I'm not sure about, but this is a good hint:

> krita software has this same behavior. it may be some GUI common issue

Krita also uses Qt, the GUI framework that OBS Studio uses. It would be helpful to know the exact last version of OBS Studio that did not have this behavior (e.g., 25.0.8, 26.0-rc1, 26.0-rc2, 26.0.0, or some other version).

**Comment by Fenrirthviti** [comment] 2024-10-14 21:55
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

We have updated Qt several times since this initial report, and this may have been resolved.

**Closed by Fenrirthviti** 2024-10-14 21:55 UTC
