### ISSUE TITLE
Push to talk and push to mute delay cannot be applied

### ISSUE THREAD

**Issue by kawtt** [obsproject/obs-studio#4131] opened 2021-01-24 14:32 UTC
## Platform
Operating system and version: Windows 10 2004
OBS Studio version: 26.1.1

## Expected Behavior
Push to talk and push to mute values should set upon being set and then hitting apply.

## Current Behavior
Push to talk and push to mute values reset to 0ms upon hitting apply.

## Steps to Reproduce
1. Go to settings under audio.
2. Enable push to talk or push to mute and set a delay.
3. Hit apply.

**Comment by Fenrirthviti** [comment] 2021-01-28 15:12
Duplicate of #3467

Closing this as it's the other is older and has more discussion.

**Closed by Fenrirthviti** 2021-01-28 15:12 UTC
