### ISSUE TITLE
Can't capture any screen and windows if run with nvidia

### ISSUE THREAD

**Issue by tarokeitaro** [obsproject/obs-studio#7143] opened 2022-08-20 03:51 UTC
### Operating System Info

Other

### Other OS

Debian GNU/Linux 11 (bullseye)

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://cdn.discordapp.com/attachments/750170769635409920/1010388527118307378/2022-08-20_10-22-52.txt

### Expected Behavior

Obs should run smoothly if running with nvidia.

### Current Behavior

**Obs just shows a black screen on the screen capture and window catcher, and the UI is messed up.**

![image](https://user-images.githubusercontent.com/42670754/185727350-0c657cab-4d44-4969-bd74-578c04782712.png)

### Steps to Reproduce

I'm using Gnome 3.38.5 for DE on my Debian 11

1. Click show applications, then search for OBS Studio
2. Then right click on the mouse, then select Launch using Discrete Graphics Card
![Screenshot from 2022-08-20 10-36-48](https://user-images.githubusercontent.com/42670754/185727514-5283d707-39af-421a-837b-d7deb317f072.png)

### Anything else we should know?

pfetch
```
  _____      keitaro@kurikuri
 /  __ \     os     Debian GNU/Linux 11 (bullseye)
|  /    |    host   GL65 9SFK REV:1.0
|  \___-     kernel 5.10.0-17-amd64
-_           uptime 3h 39m
  --_        pkgs   1926
             memory 4780M / 15841M
```

lspci
```
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:14.3 Network controller: Intel Corporation Wireless-AC 9560 [Jefferson Peak] (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:15.2 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #2 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake Mobile PCH SATA AHCI Controller (rev 10)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #15 (rev f0)
00:1f.0 ISA bridge: Intel Corporation HM470 Chipset LPC/eSPI Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile / Max-Q Refresh] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU106 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU106 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU106 USB Type-C UCSI Controller (rev a1)
02:00.0 Non-Volatile memory controller: Kingston Technology Company, Inc. Device 500c (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. Device 2600 (rev 21)
```

i build my own obs with autoscript for linux in ~/obs-studio/CI/linux

OBS runs normally without nvidia, but I have to use nvidia to maintain the fps while recording the screen.

_sorry if my english is difficult to understand, i use a language translator._

**Comment by kkartaltepe** [comment] 2022-08-20 04:38
I'm assuming you are using prime offloading and this a duplicate of #6984 if you are not let me know.

**Closed by kkartaltepe** 2022-08-20 04:38 UTC
