### ISSUE TITLE
Virtual Camera, Linux, 27.0.0, garbage video, Sony A7RIII

### ISSUE THREAD

**Issue by johansmolinski** [obsproject/obs-studio#4848] opened 2021-06-09 08:59 UTC
### Operating System Info

Ubuntu 20.10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/8uSivZ-uFbarjEPz

### Expected Behavior

After having set up the scenes to look nicely with the camera, when clicking Start Virtual Camera, I expect the preview to stay the same, just providing me with a virtual camera representing the scenes as configured.

### Current Behavior

When clicking Start Virtual Camera, the video stream from my camera is instantly replaced with a garbage image. When clicking Stop Virtual Camera, the video preview is instantly switched back to normal again.

![image](https://user-images.githubusercontent.com/45559525/121323268-f9f1d500-c90f-11eb-8c0f-3c8bec2168bd.png)

This happens when using a Sony A7RIII mirrorless camera with interchangeable lenses. I use gphoto2 to capture the video, piped to ffmpeg to output to /dev/video0, like:

    gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0

Other cameras work fine with OBS and I can use the /dev/video0 output directly as a video device in for instance VLC or Google Meet. Using the OBS Virtual Camera, however, gives the same garbage result as the preview.

### Steps to Reproduce

1. Connect a Sony A7RIII via USB C to the computer
2. Start capturing as `gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0`
3. In OBS, set up a Video Capturing Device, selecting `Dummy video device (0x0000) (platform:v4l2loopback-000)`
4. Verify the preview looks as expected
5. Click Start Virtual Camera
6. Cry
7. Click Stop Virtual Camera to get the preview back to normal.

**Comment by WizardCM** [comment] 2021-06-09 09:04
Duplicate of #3929

**Closed by WizardCM** 2021-06-09 09:04 UTC

**Comment by johansmolinski** [comment] 2021-06-09 09:13
Thank you @WizardCM for finding this related bug. However, I don't think it is a duplicate. The last comment on #3929 seems to be the same issue as mine, but the main issue discussed in the ticket appears different to me.

**Comment by 6ffm70** [comment] 2021-06-15 14:13
I am the author of that currently last comment https://github.com/obsproject/obs-studio/issues/3929#issuecomment-853497569 and I agree with @johansmolinski - these may well be separate issues.

**Comment by johansmolinski** [comment] 2021-06-15 17:40
Actually it is probably the same issue. There is another duplicate issue, #4200, with a suggested solution that did it for me.
