### ISSUE TITLE
VLC Video Source does not Shuffle on scene load

### ISSUE THREAD

**Issue by box293** [obsproject/obs-studio#3597] opened 2020-10-11 02:13 UTC
## Platform
Operating system and version: Windows 10 Pro 1909
OBS Studio version: 26.0.2

## Expected Behavior
VLC Video Source shuffle playlist should shuffle when the scene is loaded (if shuffle checkbox is selected).

## Current Behavior
When I change scenes the playlist is never shuffled, it is always played in the same order. This can be if there is just one item in the playlist that is a directory (that contains many files) or if you have multiple files individually defined. If you edit the VLC Video Source and then click OK without making any changes then the playlist is shuffled at this point in time.

## Steps to Reproduce
1. Create a VLC Video Source
2. Add multiple files to the playlist
3. Make sure the "Shuffle Playlist" checkbox is selected
4. Click OK
5. Change to another scene
6. Change back to the scene with the VLC Video Source
7. Observe the order of the videos played
8. Change to another scene
9. Change back to the scene with the VLC Video Source
10. Observe the order of the videos played, they will be identical and not shuffled

**Comment by BloodyIron** [comment] 2020-10-11 05:35
Yeah my VLC playlists aren't shuffling too. Same version, except on Linux. Sounds like a regression/bug to me.

**Comment by BloodyIron** [comment] 2020-10-11 05:39
Actually to add some more detail, the shuffling only seems to happen when OBS first loads, and no further. I have to reload the program to get it to re-shuffle.

**Comment by RytoEX** [comment] 2020-10-11 06:03
As far as I know, shuffling is performed whenever the VLC source is updated, so if you open its properties window and save it, it should re-shuffle.  Exactly as stated in "current behavior":
> If you edit the VLC Video Source and then click OK without making any changes then the playlist is shuffled at this point in time.

It's been this way since OBS Studio 20.1.0.  Here's the last commit that changed the shuffle behavior:
https://github.com/obsproject/obs-studio/commit/9321b822bfc999416392b4a553f4171e476f8f7a

I don't think this is a bug.  It's operating exactly as designed.  Perhaps there is an argument to be made that it would be a desirable feature for the playlist shuffle _again_ once it has exhausted its items.  However, as far as I know, VLC doesn't re-shuffle its own playlists once it's reached the end, so I don't think this should be default behavior.

**Comment by box293** [comment] 2020-10-11 09:07
Thanks for the response, I've taken the comments on board and have some further discussion points.

I respect from a programming perspective it is working as it was designed when it was coded.

From a users perspective though I see that it does not work as you would expect, from the way it is presented in the interface. The "Shuffle Playlist" checkbox is an option that has no help context to explain specifically how it works. I checked the online documentation a searched for "shuffle" and this yielded no results, so the intended behavior is not clearly communicated to the end user.

So the end user at this point would assume (from my perspective) that when the "Shuffle Playlist" option is checked, every time the source is part of a scene that is made active then the playlist would be shuffled (or when the source is made visible). This is how other sources use settings and are applied when the scene becomes active/visible.

What is the point of a shuffle? Looking at some online dictionaries a common example refers to shuffling a deck of cards, mixing them up. So when you switch to a scene where there is an option to shuffle the objects of a source, you would assume they would be mixed up at that point in time, when the scene becomes active.

I ended up reporting this as an issue because I wanted to switch to a "Quick Break" scene where videos from a folder location were played in random order. Currently this is not possible for me to achieve without manual intervention. To make this happen, I would need to be in Studio Mode, select the scene I am going to transition to, edit the source so the playlist is shuffled, and then transition to the scene. This feels clunky and means you can't simply press a button on a stream deck to switch to a scene and know videos will be played in random order.

If it is deemed that this is actually a feature request, then perhaps an addition option be added which produces this behavior, and is clearly identified like "Shuffle Playlist when source is Visible/Transitioned To" (yes I know it's wordy but I'm sure that can be improved). 

Alternatively, if providing a behavior of shuffling is not inline with how other media players define what a shuffle is, then another term can be used like "Randomise Playlist".

**Comment by Scrxtchy** [comment] 2020-10-11 12:35
> Alternatively, if providing a behavior of shuffling is not inline with how other media players define what a shuffle is, then another term can be used like "Randomise Playlist".

Yeah, I believe this might be the correct kind of term you have been looking for. Take for instance the media player Foobar2000, it has separate options for Randomise and Shuffle. The key difference between the two is that one persists the history of the playlist, and these are generated on application launch (or changing to another shuffle mode), which is much like how the VLC source handles this.
Random however will always just pick a random track that isn't the previous track. However this does create the possibility of playing the 1st track as the 3rd (and 5th etc), but the chance of that happening diminishes with more content added, but it's not impossible still.
I think the adding options for either random or shuffle behaviour into OBS can be argued.
There is a ticked on VLCs track for a Random playlist option, but the website is 504'ing currently so I do not know if this is implemented into their library or not

**Comment by BloodyIron** [comment] 2020-10-11 14:31
Yeah I didn't notice that in the documentation, but when I see "shuffle playlist" as a setting, I expect it to shuffle every time a new video is about to be played, just like every other shuffle feature on the planet. Can we please get this changed?

**Comment by Fenrirthviti** [comment] 2020-10-11 17:08
Closing this issue as it's not a bug. Please post on the Ideas page for tracking of a change request, or feel free to submit a PR as this is a simple translation change.

https://ideas.obsproject.com/

**Closed by Fenrirthviti** 2020-10-11 17:08 UTC

**Comment by box293** [comment] 2020-10-11 22:01
Done https://ideas.obsproject.com/posts/1149/vlc-video-source-does-not-shuffle-on-scene-load

**Comment by Gelmo** [comment] 2020-11-23 09:16
@box293 @BloodyIron Exeldro's new update to Directory Watch Media adds a Refresh hotkey. The Refresh hotkey will re-save the VLC Video Source properties, which will re-shuffle the playlist if you have Shuffle enabled. To do so, install Directory Watch Media - https://obsproject.com/forum/resources/directory-watch-media.801/ - Add that as an Effect Filter to the VLC Video Source (no need to adjust the settings there). Then go to Settings > Hotkeys and create a Hotkey for Refresh, which will be part of the VLC Video Source section. Now, whenever you press that Refresh hotkey, the playlist will be re-shuffled.

**Comment by box293** [comment] 2020-11-23 22:11
@Gelmo thank you for the heads up, I'll check it out.
