### ISSUE TITLE
Studio Mode problem

### ISSUE THREAD

**Issue by BatuhanOzusta** [obsproject/obs-studio#4097] opened 2021-01-19 11:43 UTC
Hello, when I enter studio mode there is a shift in grouped items. Please resolve this error soon.

Problem video: [https://youtu.be/h14vAfBzQB4](url)

**Comment by WizardCM** [comment] 2021-01-19 11:45
Please fill in the issue template.

**Comment by ElectronicWar** [comment] 2021-01-20 09:55
Closed, duplicate of #4108

**Closed by ElectronicWar** 2021-01-20 09:55 UTC
Labels: Incomplete
