### ISSUE TITLE
Min width size is 742px...

### ISSUE THREAD

**Issue by Kroustalo** [obsproject/obs-studio#5483] opened 2021-11-03 17:03 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/MV_eYlnjuvGqa6tL

### Expected Behavior

Can't reduce the window size less than 742px wide while in 27.0.0 I could reduce it to my desired width of 560px (values shown using sizer 4.0).

### Current Behavior

The minimum window width size is fixed at 742px and removing/joining toolbars don't do anything

### Steps to Reproduce

1. Slide the window horizontally and count the min width value

### Anything else we should know?

Didn't test if I can reach a lower value on 27.0.0 and on witch version after that stopped doing it

**Comment by nico-apps** [comment] 2021-11-03 17:07
This seems like it's more of a suggestion than a bug, as OBS does need some space for you to manage it.

**Comment by gxalpha** [comment] 2021-11-03 17:09
Are you sure that you disabled the source toolbar?
If so, you need to remove docks to make it smaller. 
Also, this looks like a support request for me. Try to ask in the Forums or the on Discord Server. https://obsproject.com/help

**Comment by Kroustalo** [comment] 2021-11-03 18:38
Yeah... the "**source toolbar**" is _different_ from the "**sources toolbar**" at the **Docks** 🤦🏼‍♂️ 

Sorry for the inconvience but still, I don't seem to understand the reason to lock the minimum width. There's cleary space for the other docks to shrink when the window gets smaller in both directions
You could just make it taller when it gets smaller and only if the data does not fit in the window.

So, my message falls into the Support/Suggestion category, so you could move it or pass the idea at the forum...

**Comment by gxalpha** [comment] 2021-11-03 18:51
The problem is that when making it smaller, the source toolbar gets too small to work properly, which is why this minimum size was introduced. 
There also is an [open Pull Request](https://github.com/obsproject/obs-studio/pull/5412) currently scheduled for OBS 28 that, if merged, should make it possible again to make OBS smaller without hiding it completely.

**Closed** 2021-11-03 19:03 UTC
