### ISSUE TITLE
OBS SEGFAULT at launch

### ISSUE THREAD

**Issue by ShockedCoder** [obsproject/obs-studio#8465] opened 2023-03-13 16:15 UTC
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

Launch with no problem

### Current Behavior

Segfaulted

### Steps to Reproduce

1. Launch OBS
2. Segmentation fault

### Anything else we should know?

I found #7889 where it was fixed by removing `qt5ct`, but I can't do that since `manjaro-xfce-settings` depends on this.
I don't even know why this suddenly started happening out of nowhere since I had been using OBS without any problems before this.

**Comment by tytan652** [comment] 2023-03-13 16:17
Duplicate of #8056

**Comment by ShockedCoder** [comment] 2023-03-13 16:18
Damn, that was lightspeed.

**Closed by tytan652** 2023-03-13 16:17 UTC
