### ISSUE TITLE
Replay buffer is limited to 512 mb by default

### ISSUE THREAD

**Issue by sneakyjoeru** [obsproject/obs-studio#2516] opened 2020-03-18 11:17 UTC
## Expected Behavior
When using CBR record option replay buffer should not be limited by memory. Max replay size should be determined by time set by a user

## Current Behavior
Current max size is 512 mb by default. It can be adjusted by switching recording to CFV or CQP and changing a drawn field value in replay buffer settings. Changing recording back to CBR preserves the value for replay buffer.

## Steps to Reproduce
1. Enable replay buffer
2. Set bitrate of replay to 150 mbit/s
3. Set duration to 10 minutes
4. Start replay buffer
5. Save replay buffer after 30+ seconds.

## Additional information
First time reported here:
https://obsproject.com/forum/threads/why-is-max-memory-used-option-isnt-available-on-cbr-for-replay-buffer.109878/

**Comment by sneakyjoeru** [comment] 2020-05-31 16:22
It's still relevant on 25.0.8

**Comment by Fenrirthviti** [comment] 2020-05-31 18:22
This report is confusing as to what you're actually reporting. Are you requesting that the 512mb limit be lifted/increased, or that switching to a dynamic bitrate mode and back to CBR isn't working properly? The 512mb limit is not a bug, it's by design. If anything, the fact it can be bypassed is more of a bug.

**Comment by Fenrirthviti** [comment] 2020-05-31 18:28
Disregard I found the mantis report that better explains this issue.

https://obsproject.com/mantis/view.php?id=1557

**Comment by sneakyjoeru** [comment] 2020-05-31 19:41
My request was to stop using memory limit which is enabled but is hidden for some reason. I hope it makes to a fix as it's been a while. :-(

**Comment by shugen002** [comment] 2020-07-02 16:01
I think this limition should be replace by a warning . In my contact , although some user set their max replay time to a ridiculors number , such as 5000 . And for most of game , the time of a round game is about 30 minutes = 1800s . But there are some user have enough memory to cache this replay .
In my opinion, if prediction of memory usage is over current free usage , we need to display a warning when they set this ridiculous number and start replay buffer . And also when user is a very big replay time , suggest them to use record instead.

**Comment by sneakyjoeru** [comment] 2020-07-02 16:05
If user doesn't have enough memory it's their problems, not other users who just want to have a big enough replay buffer to catch interesting moments.

**Comment by shugen002** [comment] 2020-07-03 03:08
Maybe we also need to provide an option to prelocate memory to make sure OBS have enough memory when it need ?

**Comment by notr1ch** [comment] 2020-08-01 16:19
I can't reproduce this. I tried the following:

Recording - CBR, 50000kbps
Replay Buffer - 300 seconds (memory limit left at default 512MB in CRF mode)
Ran OBS for 10 minutes, pressed replay buffer button, got 5 minute long recording that matched the estimated memory usage of 1.7 GB.

**Comment by ryantheleach** [comment] 2020-11-26 18:14
### Problem: 
Replay buffers are being limited to 512mb by default, by an option that remains hidden to users using CBR bitrate.

### Current Behavior
CBR secretly uses a hidden menu option that limits the buffer size to a max memory size by default.
This menu option can be revealed by switching to CQR recording mode, THEN you can adjust max memory size

### Expected Behavior
When using CBR recording, Replay buffer is specified in time. 
Replays saved are the length of the time specified, if buffer is running longer then the time specified.
CBR  should either 
1. ignore the 'hidden' Max Memory field, OR 
2. abide by it, and have it shown on the replay buffer tab.


### Reproduction Steps

Enable replay buffer
Set recording mode to CQR
Set maximum memory to 40mb
Set recording mode to CBR
Set duration to a period that uses (much) more estimated memory then the currently set Maximum Memory option.
Start replay buffer
Save replay buffer after enough time to create a replay larger then 40mb.

### Workaround

Current max size is 512 mb by default. 
It can only be adjusted by switching recording mode to CFV or CQP and changing Maximum Memory in replay buffer settings. Changing recording back to CBR preserves the value for replay buffer.

**Comment by sneakyjoeru** [comment] 2020-11-26 21:21
Another workaround:
%USERPROFILE%\AppData\Roaming\obs-studio\basic\profiles\
edit basic.ini in your profile settings

to block:
[AdvOut]

Add line:
RecRBSize=xxxxx

where xxxxx - max size in megabytes

**Comment by WizardCM** [comment] 2020-12-09 09:38
Just to confirm - this is still an issue in OBS 26.1.0-rc2?

**Comment by Gol-D-Ace** [comment] 2020-12-09 10:56
I personally can no longer reproduce this with rc2 or master.

**Comment by ryantheleach** [comment] 2020-12-09 15:16
From memory, I originally tested on 26.0.2 (as well as each release version before that it was affecting me with).

Preliminary testing with RC 2, with pathological settings, shows that it should be fixed. I'll set my settings back to default, and do a full test as it was originally affecting me.

**Comment by Gol-D-Ace** [comment] 2020-12-09 18:46
Currently I can't reproduce this even with something as old as v23

**Comment by Gol-D-Ace** [comment] 2020-12-11 21:00
Clean profile with master and I can reproduce this again.

**Closed** 2020-12-12 01:47 UTC
Labels: Mantis Duplicate

**Comment by notr1ch** [comment] 2020-12-12 01:48
> Clean settings with master and I can reproduce this again.

Thanks for this tip, the bug is caused by default settings so I was able to easily reproduce and fix.

**Comment by Gol-D-Ace** [comment] 2020-12-12 01:50
Interesting cause.
So it was already addressing it just at the wrong place.

Thanks for fixing.

**Comment by Jamalajackson1** [comment] 2022-04-02 12:31
> My request was to stop using memory limit which is enabled but is hidden for some reason. I hope it makes to a fix as it's been a while. :-( It should be fairly easy to reproduce and see what is wrong based on my description.



> ### Workaround #2:
> %USERPROFILE%\AppData\Roaming\obs-studio\basic\profiles edit basic.ini in your profile settings
> 
> to block: [AdvOut]
> 
> Add line: RecRBSize=xxxxx
> 
> where xxxxx - max size in megabytes

YOU ARE A LEGEND SEARCHED FOR HOURS HOW TO FIX THIS AND THIS WORKED AMAZING <3333

**Comment by ryantheleach** [comment] 2022-04-04 12:19
@Jamalajackson1 It's my understanding that you shouldn't need that workaround if you are using an OBS version published in the last 2 years?

**Comment by Gol-D-Ace** [comment] 2022-04-04 12:24
Yep this was fixed in 26.1.0 except it got somehow broken again.
