### ISSUE TITLE
Blending mode Darken makes transparency solid black

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#6591] opened 2022-06-05 12:40 UTC
### Operating System Info

Other

### Other OS

Any OS

### OBS Studio Version

Git

### OBS Studio Version (Other)

29782cd59

### OBS Studio Log URL

about:blank

### Expected Behavior

Blending mode _Darken_ shouldn't touch transparent areas of the source when the effect applied.

### Current Behavior

When Blending mode _Darken_ applied to the source the transparent areas of the source turns solid black.

1) Image source (PNG image with alpha):
![Blending test](https://user-images.githubusercontent.com/19683044/172048360-ebf33e8b-6c98-46aa-9971-f3428d628851.png)
 _Blending Mode->Darken_ 
2) placed over the solid Color source: #d1d1d1
3) results in the wrong rendering (black color where the transparency was):
![OBS de11632a9 Blending Screenshot](https://user-images.githubusercontent.com/19683044/172049505-243dca2a-e94f-409c-9277-9477a6e6b040.png)

### Steps to Reproduce

1. Add new Color source
2. Add PNG image with transparency as source and place it over the Color source (from p1)
3. Right-click over the image source (from p2) and select _Blending Mode->Darken_

Observe like any transparency of the source (p2) in the preview of OBS turns solid black.

### Anything else we should know?

Developers aware of the issue, it was mentioned in the:
https://github.com/obsproject/obs-studio/pull/5448#issuecomment-968157676
https://obsproject.com/forum/threads/source-blending-modes.148443/#post-542783
Let's hope it will be tracked a bit better now.

Image editors (like GIMP): produces correct picture (the Darken blending applied for the upper layer, here the result is nonlinear):
![Blending Darken expected result](https://user-images.githubusercontent.com/19683044/172050284-2933e1d8-5a49-4926-a13a-0085f68643a4.png)

Note: If you don't have any picture with alpha - use Text (GDI+) source - it has transparency by default.

**Comment by jpark37** [comment] 2022-06-05 20:45
The alpha-correct versions of darken/lighten require an extra draw because they can't be expressed with a standard fixed-function blend. It's doable, but it's not just swapping in the correct the blend enum values.

From https://www.w3.org/TR/SVGCompositing/

Sca: Premultiplied source color component
Sa: Source opacity component
Dca: Premultiplied destination color component
Da: Destination opacity component

Darken
```
Dca' = min(Sca × Da, Dca × Sa) + Sca × (1 - Da) + Dca × (1 - Sa)
Da'  = Sa + Da - Sa × Da 
```

Ligthen
```
Dca' = max(Sca × Da, Dca × Sa) + Sca × (1 - Da) + Dca × (1 - Sa)
Da'  = Sa + Da - Sa × Da 
```

**Comment by Bombe** [comment] 2022-10-15 21:01
It doesn’t only happen with Darken, Normal is also affected by this. I have a scene that contains a browser source with transparent background color (via custom CSS) and in older versions (pre-27, I think) that transparency was applied as expected when the scene was included in other scenes but since 27 (again, I _think_ it was 27) I have to choose blend mode “Screen” to get the same effect.

**Comment by jpark37** [comment] 2022-10-16 07:50
> I have a scene that contains a browser source

This ticket is about a blend mode situation that OBS doesn't fully support. Your issue is likely that OBS had changed alpha blending to be performed linearly, which web browsers do not.

If you are on OBS 28, you can get "web" blending behavior by selecting Blending Method -> SRGB Off from the source context menu. If you need more help, this ticket probably isn't the place for it.

**Comment by RytoEX** [comment] 2023-01-27 20:02
cc @jw0z96 since they implemented the feature.

As far as I understand it, this would require implementing an extra render to texture to make this work as desired, and that work is non-trivial.

**Comment by jw0z96** [comment] 2023-02-04 19:52
I've not given it too much thought, but you'd probably need to re-implement the blending equations in a fragment shader to overcome the limitations of trying to express this functionality with fixed-function blending - which would require an extra draw, and for both the source _and the scene/background_ to be available for texture sampling. The latter would likely require a non-trivial rework of the scene rendering pipeline in order for the previously rendered parts of the background to be rendered to texture.

It looks like render to texture is already enabled for sources using [non-default blending](https://github.com/obsproject/obs-studio/blob/master/libobs/obs-scene.c#L544), but I'm not sure how you'd achieve the same for the scene/background.

cc @jpark37 In case they have any suggestions for how this could be achieved

**Comment by jpark37** [comment] 2023-02-04 20:42
It's pretty much what you would think. Need to modify obs-scene.c and friends to do the extra draw with a custom shader, perhaps modifying default.effect to add a new technique, and tweaking the blend state. It's more work than I want to bite off to implement and regression test for a feature that I'm not personally interested in on a project that's just a hobby for me.

**Comment by RytoEX** [comment] 2023-02-06 18:00
> I've not given it too much thought, but you'd probably need to re-implement the blending equations in a fragment shader to overcome the limitations of trying to express this functionality with fixed-function blending - which would require an extra draw, and for both the source _and the scene/background_ to be available for texture sampling. The latter would likely require a non-trivial rework of the scene rendering pipeline in order for the previously rendered parts of the background to be rendered to texture.
> 
> It looks like render to texture is already enabled for sources using [non-default blending](https://github.com/obsproject/obs-studio/blob/master/libobs/obs-scene.c#L544), but I'm not sure how you'd achieve the same for the scene/background.

It's starting to sound like this is, for better or worse, "working as intended/designed" and that would make this a feature request rather than a bug.

**Comment by jw0z96** [comment] 2023-02-06 19:43
I'd say there's still a bug here, given that users expect behaviour comparable to photoshop etc. when using the 'darken' blending mode on sources with transparency, but it's probably "working as expected".

Implementing blending in the way discussed in this thread makes the implementation of this feature a lot more complex (in comparison to my original PR, which was pretty tiny), and as far as i'm aware would only really benefit a narrow set of use cases.

**Comment by RytoEX** [comment] 2023-02-13 14:12
> it's probably "working as expected" given the limitations of the current implementation.

If it is working as designed/implemented, and I understand that that is the case, then I'm going to close this. It is unfortunate that user expectations, when compared to how this works in web browsers or other software, does not align with the functionality in OBS, but OBS is not a web browser. If someone wants to expand the implementation, they are free to do so and open a Pull Request.

**Closed by RytoEX** 2023-02-13 14:12 UTC
