### ISSUE TITLE
Creating window capture with no windows open makes it ok/cancel button non-functional for closing properties.

### ISSUE THREAD

**Issue by Echo51** [obsproject/obs-studio#4093] opened 2021-01-18 13:32 UTC
## Platform
Operating system and version: win 10 20h2
OBS Studio version: 26.1.1

## Expected Behavior
Be able to atleast cancel out the window capture properties panel

## Current Behavior
Unable to close properties with cancel/ok

## Steps to Reproduce
1. Minimize all currently open windows or close them
2. Create new window capture
3. Window selection box is empty because no windows
4. all drop downs/ok/cancel button are now non-functional, if not close properties and re-open it for the window capture with no windows open still

**Comment by Fenrirthviti** [comment] 2021-01-18 17:47
Tested this a bit, and I was able to replicate, but the behavior is very inconsistent. Half the time I could click the cancel or OK buttons, half the time I could not. In cases where the cancel button did not work, if I just waited 20-30 seconds and tried again, it would work, or if I clicked the cancel button rapidly it would eventually work. Very strange bug, but confirmed.

**Comment by AlexanderBabansky** [comment] 2021-01-19 01:25
Traced problem to **OBSBasicProperties::qt_metacall** _id value is invalid so button click is not handled

**Comment by RytoEX** [comment] 2022-11-02 20:19
Duplicate of #7299

**Closed by RytoEX** 2022-11-02 20:19 UTC
Labels: Confirmed
