### ISSUE TITLE
Building OBS fails

### ISSUE THREAD

**Issue by Martmists-GH** [obsproject/obs-studio#11642] opened 2024-12-18 13:50 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

31.0.0

### OBS Studio Log URL

N/A

### Expected Behavior

OBS tag 31.0.0 compiles successfully

### Current Behavior

```
/tmp/tmp.AQEZ7kCKHH/obs-studio/plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c: In function ‘enc_create’:
/tmp/tmp.AQEZ7kCKHH/obs-studio/plugins/obs-ffmpeg/obs-ffmpeg-audio-encoders.c:239:9: error: ‘sample_fmts’ is deprecated [-Werror=deprecated-declarations]
  239 |         if (enc->codec->sample_fmts) {
      |         ^~
```
```
/tmp/tmp.AQEZ7kCKHH/obs-studio/plugins/obs-ffmpeg/obs-ffmpeg-output.c: In function ‘create_video_stream’:
/tmp/tmp.AQEZ7kCKHH/obs-studio/plugins/obs-ffmpeg/obs-ffmpeg-output.c:184:9: error: ‘pix_fmts’ is deprecated [-Werror=deprecated-declarations]
  184 |         if (data->vcodec->pix_fmts) {
      |         ^~
```

### Steps to Reproduce

1. Follow the build instructions

**Comment by tytan652** [comment] 2024-12-18 13:51
Duplicate of #11491

**Closed by tytan652** 2024-12-18 13:51 UTC
