### ISSUE TITLE
Scripts named "test.py" will not run

### ISSUE THREAD

**Issue by AkBKukU** [obsproject/obs-studio#10061] opened 2024-01-02 15:58 UTC
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

https://obsproject.com/logs/BmvK4l0Fp4GooFTl

### Expected Behavior

Adding a script named `test.py` to the loaded scripts would have it run.

### Current Behavior

Scripts named `test.py` never run.

### Steps to Reproduce

1. Rename included `url-text.py` script to `test.py` (or rename any other valid script)
2. Attempt to load the script
3. No description will be shown on the right and it does not run

### Anything else we should know?

I'm not the only one who has experienced this issue and it seems to be in older versions as well:
https://obsproject.com/forum/threads/trying-to-follow-python-scripting-tutorial-but-new-scripts-do-not-run.165710/

My system has Python 3.10.12 installed

**Comment by RytoEX** [comment] 2024-01-02 16:00
Duplicate of #7370

**Closed by RytoEX** 2024-01-02 16:00 UTC
