### ISSUE TITLE
Browser properties/interact window keeps getting bigger with each opening until it fills 2 monitors

### ISSUE THREAD

**Issue by Glement** [obsproject/obs-studio#8137] opened 2023-01-24 16:02 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ORBEOOhABM4e7609

### Expected Behavior

First ever opening of the window -> Window is opened with some default size.
User can resize the window.
After closing it, size is saved and is not changed upon further openings.

### Current Behavior

First ever opening of the window -> Window is opened with some default size.
User can resize the window.
After closing it, size is saved and is changed upon further openings, making the window bigger, until it fills all the space available.

### Steps to Reproduce

1.Have 2 monitor setup with different resolutions (i have 1080p, 1440p) and windows 11
2.add browser source
3.open and close interact or properties window

**Comment by ssmazzola** [comment] 2023-01-31 23:54
i'm also having this issue and looking for a fix

**Comment by gxalpha** [comment] 2023-02-01 21:25
Duplicate of #7399

**Closed by gxalpha** 2023-02-01 21:25 UTC
