### ISSUE TITLE
Error on Fedora 35 with Wayland: command xset not found

### ISSUE THREAD

**Issue by jacopofar** [obsproject/obs-studio#5609] opened 2021-12-03 15:25 UTC
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/8dRESccT1HXiO3f2

### Expected Behavior

I expected to be able to record until I click to stop

### Current Behavior

After about 11 minutes OBS exits and stops recording, the video is interrupted. This seems to happen only if I'm playing a game full screen, other activities can be recorded for much longer.

### Steps to Reproduce

1. Start recording
2. Switch to a full screen app (in my case it was Portal 2)
3. after some minutes it stops recording and exits

### Anything else we should know?

I'm using Wayland and the screen capture uses Pipewire. It works perfectly both for audio and video except for this issue.

Running OBS from the terminal I got extra information that is not present in the logs above:

```
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/jacopo/Videos/2021-12-03_15-37-55.mkv'...
info: Output format name and long_name: matroska, Matroska
/usr/bin/xdg-screensaver: Zeile 600: xset: Kommando nicht gefunden.
info: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/jacopo/Videos/2021-12-03_15-37-55.mkv' stopped
info: Output 'simple_file_output': stopping
info: Output 'simple_file_output': Total frames output: 910
info: Output 'simple_file_output': Total drawn frames: 949

...
/usr/bin/xdg-screensaver: Zeile 600: xset: Kommando nicht gefunden.
/usr/bin/xdg-screensaver: Zeile 600: xset: Kommando nicht gefunden.
/usr/bin/xdg-screensaver: Zeile 600: xset: Kommando nicht gefunden.
```

it seems it's invoking `/usr/bin/xdg-screensaver` which is a script that at line 600 has this:

`if xset -q | grep 'DPMS is Enabled' > /dev/null 2> /dev/null; then`

but `xset` is not present on my computer, I'm on Wayland (I don't know why xdg-screensaver is).

I don't know the internals of OBS, but it seems it's trying to do something with xdg-screensaver.

**Comment by mihawk90** [comment] 2021-12-03 16:49
When a dependency of a script or binary contained in a package is not present on a system, that's an issue with the package, not whatever software uses it.

```
~% dnf repoquery --provides "/usr/bin/xdg-screensaver"
xdg-utils = 1.1.3-7.fc33
xdg-utils = 1.1.3-9.fc33

[tarulia@localhost]~% dnf info --showduplicates xdg-utils

Available Packages
Name         : xdg-utils
Version      : 1.1.3
Release      : 9.fc33
Architecture : noarch
Size         : 72 k
Source       : xdg-utils-1.1.3-9.fc33.src.rpm
Repository   : updates
Summary      : Basic desktop integration functions
URL          : http://portland.freedesktop.org/
License      : MIT
Description  : The xdg-utils package is a set of simple scripts that provide basic
             : desktop integration functions for any Free Desktop, such as Linux.
             : They are intended to provide a set of defacto standards.
             : This means that:
             : *  Third party software developers can rely on these xdg-utils
             :    for all of their simple integration needs.
             : *  Developers of desktop environments can make sure that their
             :    environments are well supported
             : *  Distribution vendors can provide custom versions of these utilities
             : 
             : The following scripts are provided at this time:
             : * xdg-desktop-icon      Install icons to the desktop
             : * xdg-desktop-menu      Install desktop menu items
             : * xdg-email             Send mail using the user's preferred e-mail composer
             : * xdg-icon-resource     Install icon resources
             : * xdg-mime              Query information about file type handling and
             :                         install descriptions for new file types
             : * xdg-open              Open a file or URL in the user's preferred application
             : * xdg-screensaver       Control the screensaver
             : * xdg-settings          Get various settings from the desktop environment

Name         : xdg-utils
Version      : 1.1.3
Release      : 7.fc33
Architecture : noarch
Size         : 72 k
Source       : xdg-utils-1.1.3-7.fc33.src.rpm
Repository   : fedora
Summary      : Basic desktop integration functions
URL          : http://portland.freedesktop.org/
License      : MIT
Description  : The xdg-utils package is a set of simple scripts that provide basic
             : desktop integration functions for any Free Desktop, such as Linux.
             : They are intended to provide a set of defacto standards.
             : This means that:
             : *  Third party software developers can rely on these xdg-utils
             :    for all of their simple integration needs.
             : *  Developers of desktop environments can make sure that their
             :    environments are well supported
             : *  Distribution vendors can provide custom versions of these utilities
             : 
             : The following scripts are provided at this time:
             : * xdg-desktop-icon      Install icons to the desktop
             : * xdg-desktop-menu      Install desktop menu items
             : * xdg-email             Send mail using the user's preferred e-mail composer
             : * xdg-icon-resource     Install icon resources
             : * xdg-mime              Query information about file type handling and
             :                         install descriptions for new file types
             : * xdg-open              Open a file or URL in the user's preferred application
             : * xdg-screensaver       Control the screensaver
             : * xdg-settings          Get various settings from the desktop environment
```

As you can see, these are Fedora packages, so the correct place to report this is in the RedHat bugtracker:

https://bugzilla.redhat.com

**Comment by jacopofar** [comment] 2021-12-03 16:57
Yes, but isn't it an issue the fact OBS is invoking `xdg-screensaver`` in first place?

**Comment by mihawk90** [comment] 2021-12-03 17:05
That is certainly a question, but whether that is an "issue" or intended is not my ability to judge.

That said, even if it is an issue with OBS, that still leaves it being an issue of `xdg-screensaver` too.
Both can be true at the same time.

**Comment by kkartaltepe** [comment] 2021-12-03 17:05
No thats how its supposed to work. If you find obs closing unexpectedly consider runnin it in gdb to see if there is a crash that you can provide a backtrace for. Otherwise the xset issue is working as intended, your platform just ships broken packages.

**Comment by mihawk90** [comment] 2021-12-03 18:36
I don't know if that was you, but for reference, here's the report on the RedHat Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=2028903

**Comment by jacopofar** [comment] 2021-12-03 20:15
Yep it was me, thanks. The man page of the command says it resets the screensaver, so I am not sure why it is being invoked by OBS, maybe to prevent it from starting but I don't have a screensaver.

**Comment by ilteroi** [comment] 2022-01-19 19:29
xset simply does not work on wayland. by calling it you have an implicit dependency to x11, which is probably a bad idea considering most distros are switching to wayland by default.

**Comment by derrod** [comment] 2022-01-20 04:06
OBS does not call `xset`. It's being called by the `xdg-screensaver` script.

**Closed** 2022-04-01 05:18 UTC
Labels: Linux, Dependency Issue
