### ISSUE TITLE
macOS Screen Capture exhibits a weird black artifacting on some parts of the captured screen

### ISSUE THREAD

**Issue by KianaKaslana638** [obsproject/obs-studio#11106] opened 2024-08-10 03:45 UTC
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/RodXDhTj3MRYz80g

### Expected Behavior

I expect OBS to record my macOS screen cleanly with no artifacts.

### Current Behavior

![Screenshot 2024-08-10 at 11 31 44 AM](https://github.com/user-attachments/assets/8eebdd13-886e-4702-aa49-5cf493128b9f)

[This is how a recording looks like. (click here to watch the sample recording)](https://youtu.be/edPJWFs7bwY)

![Screenshot 2024-08-10 at 11 35 36 AM](https://github.com/user-attachments/assets/44823fed-1d74-4d4d-bf74-35a3f16a70ea)
This also how it looks like inside the OBS. I have no idea to fix this.

### Steps to Reproduce

1. Start OBS
2. Insert "macOS Screen Capture" as a source.
3. Hit record.
4. Check recording.

### Anything else we should know?

I'm currently using a Mac Mini with Apple M2 SoC with 8GB of LPDDR5 RAM. Running on the latest macOS Sonoma 14.6.1.

**Comment by jcm93** [comment] 2024-08-10 05:03
This is probably a duplicate of https://github.com/obsproject/obs-studio/issues/10403, and due to your color correction filter.

**Comment by RytoEX** [comment] 2024-08-10 19:14
Duplicate of #10403

**Closed by RytoEX** 2024-08-10 19:14 UTC
