### ISSUE TITLE
New Mac ProRes Hardware Recorder - Broken Multi-Track Audio in Premier Pro

### ISSUE THREAD

**Issue by FRANKIEonPC** [obsproject/obs-studio#8037] opened 2023-01-10 11:19 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

N/A  -  is not a configuration issue (this is not a noob / idiot post please see below)

### Expected Behavior

Hardware ProRes Recorder with Multi-Track Audio Files in OBS Beta 29 (on MAC), should playback all Audio Tracks in Premiere Pro (on MAC or PC)

### Current Behavior

**I appreciate people here are volunteers, but PLEASE do not dismiss this issue,** Hardware ProRes Multi-Track Audio Recordings (recorded on Mac) ARE BROKEN in Premiere Pro on both Mac and PC. Only the first track of audio plays back

There is only a 3min Video of the Issue here: https://youtu.be/tSkAkDQWEbE
This is not a noob/idiot post, this is really broken. 

PLEASE try these files yourself before closing this thread: https://www.dropbox.com/sh/wsu6ltkqqdusf85/AADVt3O7B6VezLk5OJ_pIDcSa?dl=0

Adobe has been contacted and have said it is likely an OBS flag issue that is causing Premiere Pro to incorrectly parse the files and that their implementation of ProRes is officially Apple licensed and to Apple spec  --  they say this is demonstarted by Premiere Pro ProRes Multi-Track Exports working correctly within Premiere Pro (on both Mac and PC),l which they do.

### Steps to Reproduce

1. Record (on Mac) using Hardware Recorder ProRes File with Multiple Audio Tracks
2. Put the video files into Premiere Pro on either Mac OR PC (beyond version 14.9 of Premiere Pro)
3. Only first audio track will play after 20-30s or after losing focus of Premiere Pro
...

### Anything else we should know?

Issue resubmitted, as incorrectly closed by gxalpha. PLEASE watch the video and try the clips before closing, it is less than 5min of your time and in everybodies interest to make sure ProRes is correctly working in the full release

**Comment by tytan652** [comment] 2023-01-10 11:38
Like I said off-thread, this may happen to be a Premiere Pro issue with how they import (not export).

This should be reported to Adobe first, except if you have a proof (not a video) that they claims that it's not on their side.

**Comment by gxalpha** [comment] 2023-01-10 12:40
Only seeing this after I already answered on #8033, but here's the long version:
1) There's no need to open a second issue, we can reopen the first one if you respond on it properly. I closed that one after I saw "Windows 10" the report info, and a Windows log attached. At that point, there was no need for me to still watch the video, as everything I saw was on a platform where ProRes was unsupported. I'm giving you the benefit of the doubt here and will reopen it for now, but please still provide the rest of the information (see below).
2) Posting a log is not about being a "noob / idiot". If we want to try to replicate the issue and see if there's something to fix, we need to know the exact configuration you're using (including the custom movflags you set etc). Only then can we actually do anything about it.
I'm going to close this as a duplicate of #8033, so that we don't have multiple places where information is. Please post the appropriate log file there, of a session where you create a recording that yielded in a broken file. Also, please adjust the Steps to Reproduce there to what you're actually doing, including the remuxing you're doing in the video but haven't mentioned anywhere else. I have looked at the video, but please don't expect every single contributor who looks at the issue to do so. It's important to have the correct Steps to Reproduce at a glance.

**Closed by gxalpha** 2023-01-10 12:40 UTC
Labels: Incomplete

**Comment by FRANKIEonPC** [comment] 2023-01-11 11:20
I will provide you with the log later when at home, it cannot help you, it is a fresh install of OBS Beta on Mac with ProRes Hardware selected, nothing more.

What will help you is downloading the files above and putting them in PP to see they are an issue. 

Myself and Xaymar (who has been working on ProRes integration since StreamFx started years ago) are likely to know more about ProRes issues than your average user  --  we are trying to help you even if you can't see that currently.

As stated ADOBE has an officially licensed version of ProRes that Apple helped them integrate - **_they have been asked at least 5 times about this by myself and Xaymar_**  and they are pretty certain it is a FLAG issue with OBS exports that stops Premiere Pro parsing them correctly.

As ADOBE have reiterated multiple times (so please don't write "ask Adobe" again, they have been asked): their integration of ProRes was done **_with Apples Assistance (literally)_** hence why PP ProRes multi-track exports work perfectly. Maybe other NLEs don't require certain flags in their implementations, but that doesn't mean you shouldn't be striving to make ProRes as compatible as possible.

Would imagine OBS exports require literally a couple of extra lines added to them to work correctly.  PP ProRes Exports are also done with Apples ProRes Hardware Encoder, so the only difference between their .mov and your .mov is the metadata / flags / header I assume?

I understand you get 1000 noob questions, or at least seems that looking at the Closed Issues, but this is a major bug with the biggest feature of your new version involving your only interframe multi-track codec (and the most popular professional editing format, on one of the most popular by userbase NLEs)  -- it should be important.
