### ISSUE TITLE
AMD AMF using Color Range Full is not accepted by Twitch (Nvidia & x264 works)

### ISSUE THREAD

**Issue by lextra2** [obsproject/obs-studio#7451] opened 2022-09-24 11:54 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/VccJL2SHYwoTYArv

### Expected Behavior

With Color Range set to Full, the video streams color range should be full and not limited.

### Current Behavior

Twitch streams are set to Limited even though Full is used which works for local recordings.

Using `FullRangeColor=true` as an AMF option does not fix this issue.

### Steps to Reproduce

1. Select AMD AMF under Settings > Output > Encoder
2. Select Color Range Full under Settings > Advanced
3. Start streaming
4. The resulting stream will still be "Limited"

### Anything else we should know?

[Color Range Full works just fine for nvidia users](https://i.imgur.com/fB4Iqfh.jpeg)

**Comment by lextra2** [comment] 2022-09-24 14:43
> Trust me, this not specific to AMD and has been an issue dating back to 2018, OBS colour options always been crappy, to the point viewers can't see anything on dark games.

Does not explain why nvidia works just fine. And I think x264 also works (cannot test right now)

**Comment by lextra2** [comment] 2022-09-24 15:13
Oh it was fixed for nvidia recently? I didn't know that. Can you point me to the ID?

And cpu h264 encoding is still the best looking option. Not really a waste of resources if you have enough cores.

**Comment by energizerfellow** [comment] 2022-09-24 17:40
Full-range YUV is very much non-standard for video work and always has been. This goes clear back to the dawn of digital video with BT.601 and Sony D1 in the early 1980s. The engineering reason for having a limited band of valid in-range YUV color values with extra bits of resolution above/below was for overshoot and linearity issues in analog hardware, ADC/DAC, and magnetic media of the era. This is why pro formats like ProRes and SDI behave the way they do. Strictly speaking, full-range quantization isn't even defined in ITU-R BT.601 and still isn't in either BT.709 or BT.2020.

This broadcast-legal limited range (technically 16-235 luma with differential chroma of +/- 112 centered on 128, i.e. 16-240, for 8-bit, along with its 10/12-bit equivalents) continues to this day in everything from Ultra HD Blu-ray to DaVinci Resolve to Twitch. Vegas Pro didn't even add full-range support until something like two years ago, which should be a hint.

As for the big-name public video services, *none* of them officially support the use non-legal full-range quantization that I'm aware of. Only exception to my knowledge is uploading offline VODs to Youtube, which will correct full-range to broadcast-legal standard-range as part of Youtube's transcoding process. This is *only* for VODs, however, as *streaming* is limited-only and will hard clip full to limited range, just like everybody else, including Twitch. A full-into-limited hard clipping will yield issues such as crushed blacks, blown out highlights, and false contrast.

**Comment by flaeri** [comment] 2022-09-24 18:11
Cannot reproduce. When recording with the new AMD encoder, full range seems to be tagged and working fine on my machine.

Can't speak to how twitch/web browsers handle full range, as I don't usually expect that to work. All I can say is that the AMD encoder is capable of doing. See image. The gradient you see is outside of legal range.
![image](https://user-images.githubusercontent.com/50419942/192112611-06a37a78-b575-4edd-9cd2-bef0639ce0b2.png)

**Comment by lextra2** [comment] 2022-09-24 18:55
Yep. All I tried was streaming. Didn't even test local recording, which works fine. So the new issue is, why twitch does not accept full for AMD while Nvidia works fine...

**Comment by energizerfellow** [comment] 2022-09-24 19:05
Your example of full-range "working" on Twitch appears to be a raw, untranscoded stream being played directly in mpv instead of one of Twitch's official clients like the twitch.tv web site. You should see the same issue with NVENC (or any AVC encoder) if you do the stream's playout as indented.

**Comment by lextra2** [comment] 2022-09-24 19:08
> Your example of full-range "working" on Twitch appears to be a raw, untranscoded stream being played directly in mpv instead of one of Twitch's official clients like the twitch.tv web site. You should see the same issue with NVENC (or any AVC encoder) if you do the stream's playout as indented.

Nope. The only reason I even noticed this streamer using full range is because colors looked more full on the native twitch app on my samsung tv. Twitch does not re-encode the stream. I get the same stream with mpv as I do in the app. Only difference is, in browser player or the app player _might_ limited the range, but again, this is NOT the case for the official samsung tv twitch app.

**Comment by lextra2** [comment] 2022-09-24 20:28
[Here is a test with x264 full which is working as intended](https://www.twitch.tv/videos/1600298316) (gamma is srgb as a bonus test)

**Comment by Fenrirthviti** [comment] 2022-09-25 17:40
Twitch doesn't and probably won't ever support full range, as browser support is abysmal for full color range.

This is likely going to be a waste of your time to try and track down and get any kind of answer from Twitch on, I'd recommend just streaming using partial like everyone else. I'd wager NVIDIA *working* is the actual bug here.

As there's nothing really for us to do on the OBS side, all our outputs are correct, I'm going to close this.

**Closed by Fenrirthviti** 2022-09-25 17:40 UTC

**Comment by Fenrirthviti** [comment] 2022-09-26 01:45
"Might work" is a far cry from "supports".

If Twitch has updated any public documentation to state they support full color range, please provide it and we can reopen this and investigate further, but right now this is all expected outcomes as far as I am aware.

**Comment by lextra2** [comment] 2022-09-26 05:24
As proven already, cpu encoder x264 works just fine for Full range, as does Nvidia. Twitch does not alter the videostream at all, neither by re-encoding nor by limiting the range in their videoplayer.

@Fenrirthviti You can view the example x264 clip posted above yourself. Full range is displayed just fine (Firefox & chrome browsers work)

**Comment by lextra2** [comment] 2022-09-26 05:30
To clarify, this issue is an OBS issue, because for some reason the AMD encoder does not send a full range when used for livestreaming.

**Comment by lextra2** [comment] 2022-09-26 18:45
@Kobi-Blade 
Here is the test image you can use. (Add it under OBS sources and livestream it for like 10 seconds. Afterwards check the colors in the VOD. Do blacks below 16 blend into the background for you?)

![Test](https://user-images.githubusercontent.com/20690384/192355606-3278eda6-2cb1-467a-8a52-b258e21bc2e7.PNG)

For me, using I444 didn't change anything. The range is still limited when livestreaming.

> Wrong YUV Color Range (claims increases CPU usage, there was no difference whasoever CPU usage remained at 10% regardless if I use NV12 or I444).

CPU usage went from 0.4% with NV12 to 1.1% with I444 with my Ryzen 3900x. But you're right. That warning message is exaggerating.

**Comment by lextra2** [comment] 2022-09-26 20:07
I'm not sure what to tell you. Recording works for me. And Livestreaming works too (with x264).

**Comment by Fenrirthviti** [comment] 2022-09-27 19:26
Again, *no streaming services actually support full color range*.

just because it might work in some situations *does not mean it's actually supported or expected to work*. If full range is working fine in the recording outputs, then there is nothing for us to investigate or check in to at this time.

If and when streaming services decide to support full color range, we can revisit this if there is still an issue at that time.

If you want to spend your own time digging through the code and see if there is anything wrong or incorrect, and submit a PR to fix it, we can review it at that point, but our team is not going to spend any time on troubleshooting and fixing a fully unsupported setup.

**Comment by Fenrirthviti** [comment] 2022-09-27 22:02
We have confirmed it is not supported with out contacts at Twitch.

**Comment by derrod** [comment] 2022-09-27 23:25
I think this thread has reached the end of its usefulness.

If anybody can actually point out if OBS is not setting some flag somewhere they can open a proper issue for that, or better yet, submit a PR to fix it.
