### ISSUE TITLE
OBS Chroma Key "Pick Screen Color" does not work right.

### ISSUE THREAD

**Issue by modineandrew** [obsproject/obs-studio#4024] opened 2021-01-06 17:00 UTC
## Platform

Operating system and version: Windows 10 version 2004
OBS Studio version: 26.1.0

## Expected Behavior

"Pick Screen Color" in OBS chroma key settings should allow me to pick the color on the screen, not just colors within the color picker as if I had my mouse over the color picker.

## Current Behavior

As of right now, when I choose to pick screen colors, the crosshair in the color picker rectangle moves as I move my mouse around the screen, not at all dependent on what color is beneath my cursor.

## Steps to Reproduce

1. Add a chroma key filter to any source
2. Change the color to "custom" and click "Select color"
3. Click "Pick screen color" and drag your mouse around on the screen. The color will not change to what's beneath your cursor.

## Additional information

None for now. My video below shows what happens.

https://user-images.githubusercontent.com/74428242/103797601-87e23080-4ffd-11eb-9e4e-7e4a2d7bdc90.mp4

**Comment by derrod** [comment] 2021-01-06 18:33
Are you using scaling in Windows? Because it does seem to read colours from the screen, but the position the colour is read from is offset from the actual mouse position. That may be due to the coordinates not being correctly calculated when DPI scaling is being used.

**Comment by WizardCM** [comment] 2021-01-07 06:46
I would second the question from @derrod - however, at 200% I was not able to reproduce this.

**Comment by modineandrew** [comment] 2021-01-07 15:40
I use 125% scaling, because at 100%, my laptop screen is unreadable at any distance.

**Comment by asher-the-thrasher** [comment] 2021-01-12 23:34
this may be its own issue but may be connected, let me know if I should make a new report, happy to .
i would also like to add to this issue that it is also on Mac OS, this same thing happens to me, big sure, 26.1.2 on all of the color pickers, not just the chroma key filter. happens on text source, color source as well, happy to add anything else that you guys would need
and just to add, for mine it will work in the window for the color picker window, just not anywhere else. i included a video below if that helps.

https://user-images.githubusercontent.com/76796294/104387227-ab790f80-5504-11eb-8210-4c8d0ecc2d2a.mp4

**Comment by modineandrew** [comment] 2021-01-16 20:14
I did not realize that it does apply to all color pickers for me, thanks for pointing that out! Since you are having the issue on a different platform, go ahead and make another issue if you haven't already.

**Comment by RytoEX** [comment] 2022-10-22 06:13
My laptop screen is set to 125% scaling, and I cannot reproduce this on Windows 10 or Windows 11 with OBS Studio 28.0.3. Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

**Comment by RytoEX** [comment] 2022-11-02 19:48
Closing per above. If this is still an issue, please comment with updated Steps To Reproduce and a new OBS log, and we can determine if we should reopen this or open a new Issue.

**Closed by RytoEX** 2022-11-02 19:48 UTC

**Comment by DABO5443** [comment] 2023-01-19 13:48
for me it says like "the settings only apply to SDR video", how tf do I get custom collor then?????
