### ISSUE TITLE
Picking Screen Color outside of window 

### ISSUE THREAD

**Issue by asher-the-thrasher** [obsproject/obs-studio#4081] opened 2021-01-17 01:09 UTC
## Platform
The Pick Screen Color option in any color choosing source doesn't register anything outside of the select color window.

Operating system and version: Mac OS Big Sur 11.2 Beta 
OBS Studio version: 26.1.2

## Expected Behavior
 the pick screen color option should work everywhere on the display.

## Current Behavior
 the screen color picker only works in the pick screen color window, no where else on the display which makes it pretty useless. 
 https://obsproject.com/logs/ucaqNtU89dSVC0C1 

## Steps to Reproduce

1. create a new color source
2. press select color
3. press pick screen color
here's a video of it to make it more clear
https://user-images.githubusercontent.com/76796294/104387227-ab790f80-5504-11eb-8210-4c8d0ecc2d2a.mp4

**Comment by WizardCM** [comment] 2021-01-17 01:13
Hmm, I wonder if this is an OS-side limitation? This feels different from #4024.

I definitely can't repro this on Windows.

**Comment by asher-the-thrasher** [comment] 2021-01-17 01:23
yeah, I was suspecting an OS issue with it because its mac, why not.

**Comment by PatTheMav** [comment] 2021-01-22 18:11
Haven't looked into this in-depth, but colour picking by any non-Apple application requires screen recording permission first, as macOS essentially picks the colour of a pixel in a "virtual" screen recording.

**Comment by asher-the-thrasher** [comment] 2021-01-22 18:54
> Haven't looked into this in-depth, but colour picking by any non-Apple application requires screen recording permission first, as macOS essentially picks the colour of a pixel in a "virtual" screen recording.

wouldn't the obs screen recording permissions cover this? I may be wrong though, apple's permissions are wonderful for privacy but suck to have to do for everything

**Comment by tkerby** [comment] 2021-02-07 01:02
Confirmed here in a fresh install. Makes custom chromakey difficult

**Comment by PatTheMav** [comment] 2021-02-25 15:04
Seems like an open (and unfixed) bug in Qt: https://bugreports.qt.io/browse/QTBUG-72548.

The obvious fix would be to use the native colour dialog which also has a colour picker included, but not that one has other (unfixed) bugs: https://bugreports.qt-project.org/browse/QTBUG-34532

**Comment by CodingAlbert** [comment] 2021-03-10 12:42
**I can confirm the problem:**
The Pick Screen Color option in any color choosing source doesn't register anything outside of the select color window.

on

**Platform**

Operating system and version: Mac OS Big Sur 11.2.2
OBS Studio version: 26.0.2

>Seems like an open (and unfixed) bug in Qt...
I see it is a Qt issue. I will look for a external colour picker as a workaround.

**Comment by PatTheMav** [comment] 2021-03-10 21:02
@CodingAlbert macOS has a built-in color meter - just look for "digital color meter" in spotlight or launchpad.

**Comment by CodingAlbert** [comment] 2021-03-12 08:23
Thanks for pointing that out, Patrick! I tested it per your suggestion. It
just needs a bit of setting up to give a hexadecimal text output.


st 10. 3. 2021 v 22:02 odesílatel Patrick Heyer ***@***.***>
napsal:

**Comment by CodeYan01** [comment] 2022-09-07 08:16
This problem still exists with obs 28.0.1, macOS 12.0.1. I hoped that Qt6 would fix this. Maybe this time the native color dialog works better?

**Comment by gxalpha** [comment] 2022-09-07 13:03
There was no indication on [QTBUG-72548](https://bugreports.qt.io/browse/QTBUG-72548) (which is the bug reported here) that this issue would be fixed in Qt 6, so it's hardly surprising that it isn't.

I will however look into the issues with the native color dialog, I could see us switching to that.
I don't think we care about [QTBUG-34532](https://bugreports.qt-project.org/browse/QTBUG-34532) since we're not subclassing QColorDialog, and the comment in the code doesn't seem to be completely true, since other QDialogs don't get closed but instead put behind the main window (which is something we can work around). There's a good chance that behavior changed since 2014, which is when the comment is from (or perhaps the settings window used to be smaller and just got buried completely by the main window making it look like it was closed. There's virtually no way to know now).

**Closed** 2023-02-19 03:10 UTC
Labels: macOS, Dependency Issue, Confirmed
