### ISSUE TITLE
The NVIDIA NVENC H.264 encoder on Variable Bit-rate uses the "Bitrate" setting as the max, rather than the "Max Bitrate" setting

### ISSUE THREAD

**Issue by LikeLakers2** [obsproject/obs-studio#9703] opened 2023-10-13 02:36 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/fahVdOyRDGsee8Ig

### Expected Behavior

The encoder should use the Max Bitrate setting as the max bitrate, while either ignoring the Bitrate setting or using it as a suggested minimum.

### Current Behavior

The encoder uses the Bitrat" setting as the max bitrate, ignoring Max Bitrate.

### Steps to Reproduce

1. Go to the advanced settings in Output -> Recording.
2. Set the Video Encoder to NVIDIA NVENC H.264
3. Set the Rate Control to VBR, set the Bitrate to some number, and the Max Bitrate to some higher number.
4. Record something bitrate-intensive, and notice that the bitrate on the stats window maxes out at the Bitrate set, not the Max Bitrate.

I was able to replicate the problem using ~~the critically acclaimed MMORPG~~ Final Fantasy XIV as my bitrate-intensive application of choice (spinning the camera around should easily max out the bitrate), in two different scenarios:

1. I used 30000 Kbps as my Bitrate, and 50000 Kbps as my Max Bitrate.
2. I used 5000 Kbps as my Bitrate, and 50000 Kbps as my Max Bitrate.

In either scenario, I was given a maximum bitrate around the Bitrate setting, rather than somewhere in-between Bitrate and Max Bitrate as expected.

### Anything else we should know?

The encoder appears to recognize that it can use lower bitrates - for example, if I remove everything from the scene, the bitrate will drop from 30000 Kbps to 44 Kbps.

I am unsure if this occurs in the NVIDIA NVENC HEVC encoder too.

**Comment by kkartaltepe** [comment] 2023-10-13 03:38
This sounds like the intended behavior per the docs https://docs.nvidia.com/video-technologies/video-codec-sdk/11.1/nvenc-video-encoder-api-prog-guide/index.html#rate-control

max is just the absolute max during some unspecified but short period. You should expect to have a stream with the bitrate specified in bitrate on average.

**Comment by LikeLakers2** [comment] 2023-10-13 03:55
That... doesn't make much sense, I'll be honest. But it also sounds like it's something to do with NVIDIA's end, not OBS' end? Am I getting that right?

**Comment by derrod** [comment] 2023-10-13 04:04
Closing as NVENC appears to behave as intended.

**Closed by derrod** 2023-10-13 04:04 UTC

**Comment by LikeLakers2** [comment] 2023-10-13 04:06
@kkartaltepe That... sounds weird. With the two options labeled as "Bitrate" and "Max Bitrate," I don't get the impression that that's how it should work at all. I thought those were supposed to be the minimum and maximum bitrates.

Granted, this is my first time messing with the settings, but it still seemed very odd that it would perform this way. Perhaps if they were labeled "Average Bitrate" and "Max Bitrate" I might've understood? I don't know.
