### ISSUE TITLE
Unable to record with Nvenc AV1 with resolution greater than 4096x1440 on RTX 4070

### ISSUE THREAD

**Issue by tertius1** [obsproject/obs-studio#9431] opened 2023-08-14 14:57 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/UK27ZApqGmxyZbQI

### Expected Behavior

A recording with an output size of 5120x1440 (ultra wide 49" 32:9 monitor) should be recorded properly with the Nvenc AV1 codec on a RTX 4070 GPU.
![Screenshot 2023-08-14 164003](https://github.com/obsproject/obs-studio/assets/26193033/716865a7-2313-452f-802f-5526d0c0ecc6)

### Current Behavior

The video file is 5120x1440, however only the top left 2546x760 pixels are from the output, the rest of the images are black. This defective output is not dependent on the captured content, it's only dependent on Settings→Video→Output (scaled) Resolution.

![2023-08-14 16-33-04 mkv_snapshot_00 00 840](https://github.com/obsproject/obs-studio/assets/26193033/7f7d775a-bde3-4ca0-b207-9c3d5f7f4afa)

### Steps to Reproduce

1. In OBS, create a new profile
2. Simple output mode, change recording video encoder to Hardware (Nvenc AV1); mkv or mp4
3. Settings->Video both resolutions to 5120x1440 
4. Start recording, Stop Recording, check output vide

Notes:
- Nvidia driver 536.99 DCH Game ready driver; the current driver as of this post
- If you change the output resolution to 4096x1440 or lower, the recording is fine. Every resolution above 4096 exhibits the issue
- Recorded content doesn't matter. Can even test with the "Color" source.
- Same resolution (5120x1440) with Nvenc HEVC works fine.
- Same issue in advanced output mode

### Anything else we should know?

ffmpeg.exe is able to recode a proper hevc-encoded 5120x1440 video to av1_nvenc fine with no issue, so it's possible it's an OBS issue.

**Comment by pkviet** [comment] 2023-08-14 16:16
The issue seems related to tiling with nvenc av1.

**Comment by theHamsta** [comment] 2023-08-14 16:26
Could you share the video file produced by NVENC where 3/4 of the screen are black?

**Comment by theHamsta** [comment] 2023-08-14 16:41
Could you also provide us the output of `nvidia-smi` (run it in the Windows console)? I don't out of my head which driver version `31.0.15.3699` is.

**Comment by alinsavix** [comment] 2023-08-14 16:45
I can confirm this bug, following the reproduction instructions provided. I also noticed that the output file does not correctly play back at all -- with MPC-HC, the part of the image that's visible doesn't change at all, and with VLC the image is just black the entire time.

Log at https://obsproject.com/logs/ERjr2UuuR5SlOeG8, which includes a recording in AV1, a recording in h.265, and an attempt (didn't work due to resolution) to record in h.264, in that order. Output video file is attached: https://github.com/obsproject/obs-studio/assets/25068788/b32cbbc9-1091-453e-8a25-6d4cc86392b3

Quick vitals:
  - OBS 29.1.3
  - Windows 11 22H2
  - nvidia driver 536.67 running on a 4090

**Comment by theHamsta** [comment] 2023-08-14 17:05
@tertius1 is this corruption new since you updated the Nvidia driver to the newest version or was the problem there before?

**Comment by tertius1** [comment] 2023-08-14 19:42
This is a demo video. It's 5120x1440, fullscreen white "test" text scrolling over fullscreen red background. It appears as images in mpc-hc, but actually it's scrolling horizontally and vertically. Windows Explorer isn't able to create a video thumbnail for these videos, so I assume the encoded data stream is defective.

https://github.com/obsproject/obs-studio/assets/26193033/ecd03e02-31de-4469-8871-c6a0cd83eb88

@theHamsta I don't know, if the issue started with the current Nvidia driver. This is the first time I wanted to record this resolution with AV1.

**Comment by theHamsta** [comment] 2023-08-15 10:53
I can't reproduce the bug on a configuration with
- old OBS commit (d27cda1fa, november 22)
- Windows 10
- nvidia driver 536.99 running on a RTX 6000 Ada

I'm using https://github.com/RytoEX/obs-studio/blob/872f0353e68191d69bcc4678a2d195144fdcabeb/UI/window-basic-settings.cpp#L1630 to allow to select in the UI resolutions higher than my actual screen resolution (add values smaller than `1.0`).

 I'm currently trying to build OBS with Qt6 (it's building but rejecting Qt6Core.dll at runtime)

**Comment by tertius1** [comment] 2023-08-15 11:28
Wow, I can use 7680x4320 on my system (see opening post) without issue!
I need to set fps to 30 to avoid encoder overload for higher resolutions, but it's creating a valid video.
Other combinations:
- 7680x4320 working
- 7680x2160 working
- 7680x1440 not working
- 7680x1080 not working
- 5120x4320 working
- 5120x2160 working
- 5120x1440 not working
- 5120x1080 not working

**Comment by theHamsta** [comment] 2023-08-15 13:29
> Wow, I can use 7680x4320 on my system (see opening post) without issue! I need to set fps to 30 to avoid encoder overload for higher resolutions, but it's creating a valid video. Other combinations:
> 
>     * 7680x4320 working
> 
>     * 7680x2160 working
> 
>     * 7680x1440 not working
> 
>     * 7680x1080 not working
> 
>     * 5120x4320 working
> 
>     * 5120x2160 working
> 
>     * 5120x1440 not working
> 
>     * 5120x1080 not working
> 
>     * 3840x1440/1080/720/360 working
> 
> 
> May be the issue description needs to be corrected, but I don't know the general idea what's exactly the issue.

How do those resolutions behave with other software (FFmpeg, Handbrake)? Will they also produce broken videos when using NVENC AV1? You should be able to encode videos with your Ada GPU until resolutions of 8k x 8k.

**Comment by theHamsta** [comment] 2023-08-15 14:04
> Wow, I can use 7680x4320 on my system (see opening post) without issue! I need to set fps to 30 to avoid encoder overload for higher resolutions, but it's creating a valid video. Other combinations:
> 
>     * 7680x4320 working
> 
>     * 7680x2160 working
> 
>     * 7680x1440 not working
> 
>     * 7680x1080 not working
> 
>     * 5120x4320 working
> 
>     * 5120x2160 working
> 
>     * 5120x1440 not working
> 
>     * 5120x1080 not working
> 
>     * 3840x1440/1080/720/360 working
> 
> 
> May be the issue description needs to be corrected, but I don't know the general idea what's exactly the issue.

Thank you! I can repro the bug with `7680x1440 `

**Comment by theHamsta** [comment] 2023-08-16 14:34
> @theHamsta As I wrote in my bug report, ffmpeg.exe is able to encode av1_nvenc 5120x1440 fine. So I assume, ffmpeg in general is able to tile correctly and encode with this codec correctly, while obs isn't.

Could you check whether you used exactly the same settings? For me, it only fails in OBS for some settings for `multipass` (e.g. `multipass=qres`, quarter resolution,  advanced encoder settings).

**Comment by theHamsta** [comment] 2023-08-16 14:51
> For me, 5120x1440 fails for two passes (quarter resolution), works fine for the other two (single pass and two passes full resolution).

Thank you! Was the same for me. I hope you can at least use OBS with this resolution in the meantime until ` quarter resolution is fixed`

**Comment by theHamsta** [comment] 2023-10-25 09:10
@tertius1 the problem should be fixed in the 545.XX series of Nvidia drivers (https://www.nvidia.com/de-de/geforce/game-ready-drivers/). Could you check whether the problem has been fixed?

To reproduce the bug in previous drivers `-multipass quarterRes` + AV1 + certain widths > 4096 are needed. The bug can be reproduce also in FFmpeg (Windows, Linux) with something like
```
ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i <random input video>    -filter_complex "scale_cuda=7680:1440" -c:v av1_nvenc  -preset p6 -b:v 250K -tune hq -multipass qres  -y  output.mp4
``` 

@BtbN @galad87 please be aware of this bug and the fix in case some of your users encounter this problem.

**Comment by tertius1** [comment] 2023-10-27 14:13
> @tertius1 the problem should be fixed in the 545.XX series of Nvidia drivers (https://www.nvidia.com/de-de/geforce/game-ready-drivers/). Could you check whether the problem has been fixed?

Yes, I confirm the problem has been fixed. I tested with Nvidia driver 454.92. It's now possible to record with quarter resolution  multipass mode.
I never thought this is a driver issue...
Thanks!

**Comment by Fenrirthviti** [comment] 2023-10-27 17:09
Driver fix has been released, closing.

**Closed by Fenrirthviti** 2023-10-27 17:09 UTC
Labels: Windows
