### ISSUE TITLE
Video Capture Device ignores the "focus" property on start.

### ISSUE THREAD

**Issue by Rextuz** [obsproject/obs-studio#4281] opened 2021-02-26 09:01 UTC
## Platform

Operating system and version: Arch Linux x86_64 Linux 5.11.1-arch1-1
OBS Studio version: 26.1.2-1
OBS Log file: [2021-02-26 11-09-44.txt](https://github.com/obsproject/obs-studio/files/6048474/2021-02-26.11-09-44.txt)

## Expected Behavior

The camera should apply focus set in Video Capture Device properties when OBS studio is started.

## Current Behavior

The camera enables auto focus regardless of the settings in Video Capture Device properties when OBS studio is started.

## Steps to Reproduce

1. Add _**Video Capture Device (V4L2)**_ to a scene
2. Untick _**Focus, Auto**_ and set _**Focus (absolute)**_ value manually in the properties of the added source
3. Restart OBS
4. The focus is no longer applied, but values in the properties are set

### Temporary workaround:

Open the properties and move the _**Focus (absolute)**_ slider back and forth. The focus applies again.

**Comment by Fenrirthviti** [comment] 2021-02-26 17:14
Duplicate of https://github.com/obsproject/obs-studio/issues/3092

**Closed by Fenrirthviti** 2021-02-26 17:14 UTC
Labels: Linux
