### ISSUE TITLE
OBS rtmps streaming to facebook broken 

### ISSUE THREAD

**Issue by jcfrosty** [obsproject/obs-studio#2330] opened 2020-01-19 18:00 UTC
This is the exact issue:
https://obsproject.com/forum/threads/unable-to-live-stream-to-facebook-live-over-rtmps.102849/

Cannot connect to facebook live due to rtmps requirement, but code breaks mbedtls somehow?

## Expected Behavior 
it should connect as mbedtls is installed, everything would work fine if we didn't use encryption (rtmp vs rtmps). Facebook has now disabled the ability use rtmp even through custom server settings.
(after patch)
 [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 128, channels: 2, channel_layout: 3
11:54:04 AM.252: 
11:54:04 AM.253: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmps://rtmp-api.facebook.com:443/rtmp/...
11:54:04 AM.253: ---------------------------------
11:54:04 AM.253: [FFmpeg aac encoder: 'Track1'] bitrate: 128, channels: 2, channel_layout: 3
11:54:04 AM.253: 
11:54:04 AM.257: ==== Recording Start ===============================================
11:54:04 AM.257: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/broadcaster/Videos/Live Stream Recordings/2020-01-19 11-54-04.mkv'...
11:54:04 AM.616: [rtmp stream: 'adv_stream'] Connection to rtmps://rtmp-api.facebook.com:443/rtmp/ successful
11:54:04 AM.617: ==== Streaming Start ===============================================
11:54:35 AM.055: User switched to scene 'Live Web Presenter'

## Current Behavior (before patch)

[rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmps://rtmp-api.facebook.com:443/rtmp/...
10:12:35 AM.130: ---------------------------------
10:12:35 AM.130: [FFmpeg aac encoder: 'Track1'] bitrate: 128, channels: 2, channel_layout: 3
10:12:35 AM.130: 
10:12:35 AM.133: ==== Recording Start ===============================================
10:12:35 AM.133: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/broadcaster/Videos/Live Stream Recordings/2020-01-19 10-12-35.mp4'...
10:12:35 AM.205: RTMP_Connect1, TLS_Connect failed: -0x7680
10:12:35 AM.205: [rtmp stream: 'adv_stream'] Connection to rtmps://rtmp-api.facebook.com:443/rtmp/ failed: -2
10:12:35 AM.205: ==== Streaming Stop ================================================

## Steps to Reproduce
1. attempt a stream to facebook live
2. fail
3. apply patch like in forum link above
4. recompile
5. facebook live stream rtmps works!

## Additional information

https://obsproject.com/forum/threads/unable-to-live-stream-to-facebook-live-over-rtmps.102849/

**Comment by notr1ch** [comment] 2020-01-19 18:08
The patch in that thread disables certificate verification which breaks the security of TLS, so it is not suitable for inclusion in OBS. This is most likely an issue with invalid certificates in your /etc/ssl/certs directory, try this patch instead:

https://github.com/obsproject/obs-studio/commit/4d89123cdc9c47fdf984980b93a70447c1692183.patch

**Comment by kkartaltepe** [comment] 2020-01-24 03:21
Closing this issue as a duplicate of #2350

**Closed by kkartaltepe** 2020-01-24 03:21 UTC

**Comment by jcfrosty** [comment] 2020-01-25 03:39
I've tested the rtmp.patch and it indeed fixes the livestreaming issue!
