### ISSUE TITLE
OBS Crashes at Startup After Installing Davinci Resolve and Persists After Resolve is Uninstalled and OBS Reinstalled

### ISSUE THREAD

**Issue by Atmo-nS** [obsproject/obs-studio#10822] opened 2024-06-10 19:40 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

Can't Get URL Program Crashes INSTANTLY

### Expected Behavior

OBS to start normally.

### Current Behavior

OBS crashes immediately with the following error.

![image](https://github.com/obsproject/obs-studio/assets/172314486/fe2392a1-2843-4079-9080-f10601f5abc9)

### Steps to Reproduce

1. Install OBS Studio 30.2 Beta 1
2. Install Davinci Resolve
3. Try to Start OBS - Instant Crash

### Anything else we should know?

I installed the beta and started it, and it worked fine just like normal and previous version. I wanted to try the new highlight markers and so I installed Davinci Resolve to test them. After the forced reboot after the Resolve install I went to open OBS and it crashed instantly with the above error.

Now even after uninstalling BOTH programs both Resolve and OBS Beta, including preferences and scenes. It still won't open after just installing the OBS Beta again. I managed to get it working again by following directions of another post on here in issues stating updating Microsoft redistributable fixes the insta-crash. However when I rebooted I lost my network adapter functionality and had no internet? Very odd, after rebooting modem/router I got it working and obs was fine after that.

To test the process and what caused the issue I (stupidly/thinking the vredist updating fixed it?) tried to reproduce to see if Resolve caused this somehow? I installed OBS Beta, started up fine. I closed it and installed Resolve again and rebooted. Again just like before now I am stuck with an OBS that will not open without crashing. I can do the vredist update again but will be back at trying to fix my network adapter which took forever.

Attached is my crash log maybe it will narrow down what is going on.
[Crash 2024-06-10 15-31-46.txt](https://github.com/user-attachments/files/15778289/Crash.2024-06-10.15-31-46.txt)

**Comment by RytoEX** [comment] 2024-06-10 19:47
Duplicate of #10799

**Closed by RytoEX** 2024-06-10 19:47 UTC

**Comment by Atmo-nS** [comment] 2024-06-10 20:07
I have the latest Redistributable installed though and it's still crashing at startup.

![image](https://github.com/obsproject/obs-studio/assets/172314486/d8a19511-397d-4fae-b688-f8843518b71d)

**Comment by RytoEX** [comment] 2024-06-10 20:36
> I have the latest Redistributable installed though and it's still crashing at startup.
> 
> ![image](https://private-user-images.githubusercontent.com/172314486/338329434-d8a19511-397d-4fae-b688-f8843518b71d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTA5NTcsIm5iZiI6MTcxODA1MDY1NywicGF0aCI6Ii8xNzIzMTQ0ODYvMzM4MzI5NDM0LWQ4YTE5NTExLTM5N2QtNGZhZS1iNjg4LWY4ODQzNTE4YjcxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMDE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDc3NzlkNDA2YWMwNTFiZTMzOWMwMjFhMTBkNmI3NjM5OGMzOGRjY2VkOGU0MzczMmY0YzI4YWQ3YjZkMTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.77F3EEc2y3TZjipIF4HrDp_HFhHlmP9bCwt5hlZhBDc)
> 
> Edit to add: I actually did the repair option on that Vredist and it fixed my issue. So Davinci Resolve install does break the vredist apparently and it will only work once it has been repaired.

Apparently, some software installers can break the Visual C++ Runtime/Redistributable installation files, but there's nothing we can do about that.
