### ISSUE TITLE
Window Capture flickers on OBS for Mac

### ISSUE THREAD

**Issue by ghost** [obsproject/obs-studio#2361] opened 2020-01-30 11:12 UTC

**Comment by keyboardcowgirl** [comment] 2020-01-30 11:25
As an extra: I hope _someone_ noticed the double return of _the exact same thing_, both before and after the check if the window even exists. That seems to me like it would cause some extra problems too.

**Comment by Palakis** [comment] 2020-01-30 13:16
Keyboardcowgirl, as much as I can understand your frustration with this issue, this does not give you the right to make attacks like this to the development team.

> abundant other unrelated compiling issues from badly optimised code.

I don't believe "badly optimised code" prevents a successful compilation. What compiling issues are you referring to?

> As an extra: I hope someone noticed the double return of the exact same thing, both before and after the check if the window even exists. That seems to me like it would cause some extra problems too.

Looking at the piece of code you're referring to: https://github.com/obsproject/obs-studio/blob/master/plugins/mac-capture/mac-window-capture.m#L35-L45
This is an early return, not a double-return. This early return happens if CGWindowListCreate returns an empty array (meaning the window specified in wc->window.window_id couldn't be found).

**Comment by dodgepong** [comment] 2020-01-30 13:32
Thanks for the report and the leads. I hope we can look into them further to see if there's something useful to be gleaned.

The reality is that we haven't have a Mac expert actively contributing to the project for quite some time now. Suggestions to use Display capture instead aren't out of laziness (we know it's not ideal), but rather out of practicality due to not being aware of a better solution. Don't read the situation as "the devs are lazy", but rather read it as "the devs need help." This is open source, after all. We're happy to help you get things compiled if you want to try your hand at testing or even submitting a PR.

**Comment by keyboardcowgirl** [comment] 2020-01-30 13:39
> I don't believe "badly optimised code" prevents a successful compilation. What compiling issues are you referring to?

Many files need a variety of fixes, which after a few hours of digging into the code and going by compiler panics to figure out what to patch, successfully builds. After the completed build and packaging, OBS still crashes. I'd spend an entire week to get it to run semi-stable, but that's not the focus of this particular report, it's anecdotal to say there's a lot going on and this issue (as well as stock python support, from what I know) needs some extra attention.


> Looking at the piece of code you're referring to: https://github.com/obsproject/obs-studio/blob/master/plugins/mac-capture/mac-window-capture.m#L35-L45
> This is an early return, not a double-return. This early return happens if CGWindowListCreate returns an empty array (meaning the window specified in wc->window.window_id couldn't be found).

By programming logic, I believe `if (arr.count)` returns true only if the array is populated, not by a zero-value, which would inherently be a `false` boolean. This can be cleaned up. I simply don't understand why
```C++
return CGWindowListCreateImage(
	CGRectNull, kCGWindowListOptionIncludingWindow,
	wc->window.window_id, wc->image_option);
```
comes both before _and after_ `if (!find_window(&wc->window, NULL, false))`.

Again, the issue at hand isn't so much that the double return is a problem, but that `CGWindowListCreateImage` is fed a null area, I understand this is likely because checking window sizes on the fly is difficult, but as seen in the other project linked above, this can be done since the function is called each and every frame grab (since this is an image capture, not an actual video of the window).

For proper video of the window, Apple has API code that uses screen capture through AV Foundation, but as is well known, this doesn't seem to have a clear-cut example on how to record **specific windows**, rather than **the whole screen**. I'm not versed enough in Apple's documentation to make heads or tails of what they suggest with this framework.


> The reality is that we haven't have a Mac expert actively contributing to the project for quite some time now. Suggestions to use Display capture instead aren't out of laziness (we know it's not ideal), but rather out of practicality due to not being aware of a better solution. Don't read the situation as "the devs are lazy", but rather read it as "the devs need help." This is open source, after all. We're happy to help you get things compiled if you want to try your hand at testing or even submitting a PR.

I'm not saying the team is _lazy_, but the main reason nobody works on OBS for Mac is because it's both "not a priority" and the majority of people who do stream from a Mac pay for properly reliable industrial solutions. The few Mac streamers out there that use OBS have to use the work-around or simply don't bother with OBS. There's a toxic atmosphere around OBS being DirectX-only and none of the Mac devs that I know are interested in dealing with that.

Helping becomes difficult when you're talking to a wall of ignorance, so it makes sense that few people even try.

**Comment by Palakis** [comment] 2020-01-30 13:43
> By programming logic, I believe if (arr.count) returns true only if the array is populated, not by a zero-value, which would inherently be a false boolean.

Yes, sorry. I read that too quickly. That's the opposite of what I stated in my initial reply. Early return if `arr` has something in it, then fallback strategy with `find_window`.

**Comment by keyboardcowgirl** [comment] 2020-01-30 13:52
> Yes, sorry. I read that too quickly. That's the opposite of what I stated in my initial reply. Early return if `arr` has something in it, then fallback strategy with `find_window`.

And then another fallback with the exact same _as if the array **was** populated_ ?

I completely understand that OBS is in many parts cobbled-together from throwing code at it and seeing what sticks, without post-compile optimisations for a smoother re-compile, because Team OBS simply doesn't have the time and space to create flow plans and breakdowns like an in-house team would.

I honestly want to figure this out with the team, but I have only a very limited idea of how C++ works and my only understanding of it is from OBS code. I'm a 10-years retired interface developer trying her best, no reason to take things so personal because you read between the lines.

**Comment by Palakis** [comment] 2020-01-30 13:53
> Helping becomes difficult when you're talking to a wall of ignorance, so it makes sense that few people even try.

Are you referring to a specific case?

**Comment by mufunyo** [comment] 2020-01-30 13:54
> There's a toxic atmosphere around OBS being DirectX-only and none of the Mac devs that I know are interested in dealing with that.

Can you please elaborate on this? OBS has a GL backend for Linux, and a Metal backend is planned to resolve Apple's deprecation of OpenGL on macOS. Like dodgepong said before, this is not a problem of "toxic atmosphere", "laziness" or "unwillingness", but just a lack of human resources. Please, please step forward if you want to contribute to better Mac support. Don't bottle up frustration and pour it out on a GitHub issue, talk to Jim or any of us on IRC or Discord, we try our best to be very reasonable.

**Comment by keyboardcowgirl** [comment] 2020-01-30 14:00
> Can you please elaborate on this? OBS has a GL backend for Linux, and a Metal backend is planned to resolve Apple's deprecation of OpenGL on macOS.

I worked on the Metal implementation a while back, but my recommendation for compartmentalising DirectX/OpenGL/Metal/Vulkan into their own modules was completely shot down due to "too much effort" and "OBS is DirectX based, be glad we have OpenGL support already". Modules would make a lot more sense since you can have each module use a purpose-built I/O that can then talk to the core OBS code without running any bloating code to support incompatible frameworks in the background.

Bringing out personal confrontations to a public place is not my style, but you did ask.

> Like dodgepong said before, this is not a problem of "toxic atmosphere", "laziness" or "unwillingness", but just a lack of human resources. Please, please step forward if you want to contribute to better Mac support. Don't bottle up frustration and pour it out on a GitHub issue, talk to Jim or any of us on IRC or Discord, we try our best to be very reasonable.

I own neither of those platforms, so I can't reach out anywhere other than here or the, (shockingly pointless) forums where many people complain about the same simple problems ad nauseam.

**Comment by Palakis** [comment] 2020-01-30 14:03
> I'm a 10-years retired interface developer trying her best, no reason to take things so personal because you read between the lines.

We're trying our best to help you too! :smile:
I don't take things personal (I'm not always around this issue board anyways), just trying to make a point about how releasing frustration on contributors and maintainers will not yield useful results.

**Comment by Palakis** [comment] 2020-01-30 14:08
> I worked on the Metal implementation a while back, but my recommendation for compartmentalising DirectX/OpenGL/Metal/Vulkan into their own modules was completely shot down due to "too much effort" and "OBS is DirectX based, be glad we have OpenGL support already". Modules would make a lot more sense since you can have each module use a purpose-built I/O that can then talk to the core OBS code without running any bloating code to support incompatible frameworks in the background.

Separate graphics backends/modules are a thing since the very first versions of OBS Studio. Who did you get that answer from?

**Comment by keyboardcowgirl** [comment] 2020-01-30 14:17
> Separate graphics backends/modules are a thing since the very first versions of OBS Studio. Who did you get that answer from?

> Bringing out personal confrontations to a public place is not my style, but you did ask.

Let's not go there. All I can say is that it was from a few of the core developers. Undoubtedly also the reason your original Metal dev bailed, whose outdated work I had to pick up since it was built for a few OBS versions before I tried.

As for how accurate that statement about modules is: I have my doubts, since when you start digging into the output/rendering side of things, DX and GL are very deeply baked into random code that doesn't necessarily require it. There's no module-based interface for code to interact with, but rather the interactions are scattered along the entire project. Integrating Metal was a nightmare, and I'm glad I quit that project after months of headaches over getting nowhere.

But, again, we're not talking about output here, but _input to OBS_ via the capture system. I'd like to keep this on topic as much as possible to not confuse whoever is trying to read up on all this afterward. Mainly since at the moment nothing is being actually contributed, other than discussion.

**Comment by tielqt** [comment] 2020-01-30 14:46
If you have fixes for those issues you claim to have found, I'm sure we'd welcome them in relevant PRs. I strongly recommend that if you want to help more, you should join our [Discord server](https://discord.gg/obsproject) and post in the #development channel. Accounts on Discord are free, and the server is publicly accessible.

In the meantime, let's refocus: what issues are you currently, actively having with compiling the program? Compile issues are pretty rare across the project, from my understanding.

**Comment by keyboardcowgirl** [comment] 2020-01-30 15:21
> [...] join our [Discord server](https://discord.gg/obsproject) [...] Accounts on Discord are free [...]

> I own neither of those platforms

I don't have, nor use, nor want to use, nor will ever touch Discord, because I disagree with their EULA and Privacy regulations. Don't use software you disagree with, which is why my efforts to improve OBS, so I can help out in making it better and don't have to ditch that too.

> If you have fixes for those issues you claim to have found, I'm sure we'd welcome them in relevant PRs.

The fixes I implemented may not translate to the compile Team OBS uses for their Mac release, because they have a convoluted pre-compiling setup. I compile bare-bones, as in I get all the dependencies through homebrew and then `cmake` and `make package` with no flags. That's how I find all the deprecation warnings and other issues to fix, which mostly just need a few cleanups in the code and the rare rewrite. I had reported many of them back to Team OBS, but even in the latest updates, a lot of those tiny issues are still there — so why report them again, only to get them ignored? Just like my attempts to stay on topic rather than deviate from the capture code.

> In the meantime, let's refocus: what issues are you currently, actively having with compiling the program? Compile issues are pretty rare across the project, from my understanding (though this is also better discussed on Discord, where you can be helped in real-time).

I'm not here to learn how to compile OBS, that part I've managed already. I'm here to help figure out a solution to a problem that's been around for years, and affects every single Mac user.

Despite the fact I know next to nothing about C++, other than what I've gathered passively by understanding front-end and web coding and the overwhelming amount of patch-job OBS code, I still do my best to figure out what is **actually broken**, and report back with fixes on those problems, rather than setting Team OBS on a hunt for things they don't experience issues with, unless I don't understand the problem like in this case. So I can't contribute code if I don't know what the solution is.

**Comment by pkviet** [comment] 2020-01-30 15:28
Consider checking the CI scripts in order to compile OBS-Studio on Mac. It helped me a lot after getting a lot of the issues you seem to have encountered too. The deps can be downloaded from the URL in the scripts; in particular Qt 5.10.1 is not easily available. We're stuck on this version due to several bugs up to 5.12 (not sure of the status with later Qt versions).

**Comment by jp9000** [comment] 2020-01-30 15:30
Keep unnecessarily provocative comments and opinions away from our issue reports please, as all it does is seek to provoke and detract from any actual issue there may be.

For the actual issue, if we are doing something that can be improved with window capture, then I definitely want to know about it.  In the documentation for `CGWindowListCreateImage()`, using `CGRectNull` specifies that it will automatically use the minimum required size to capture the specified windows in the window list, that's all.  Perhaps it's a bit poorly worded in the documentation, but if you have one window in the window list, it will return an image with a rectangle that is equal to the size of that one window, otherwise window capture would not be capturing anything at all.  I don't mind checking to verify if `CGRectNull` contributes to performance issues with window capture, but with a parameter like that, considering it's a four-integer rectangle structure, I feel doubt considering all it should be expected to do internally is just automatically calculate the rectangle for you.  I could of course be wrong, and Apple could be doing something unpleasant when you use `CGRectNull`, but that feels unlikely.  However, again I will test it to be safe, as stranger things have happened.

Additionally, I'd like to point out that in the subsequent mantis issue you link, `Netizen01` that you yourself reference does not state that it has anything to do with `CGRectNull`, but instead states: `I'm guessing it has more to do with threads and shared image buffers`, which to me sounds like a more plausible explanation.  Unfortunately, we haven't heard back from that individual.

The duplicate call you're talking about is just a redundant call.  It's harmless and is very unlikely to have anything to do with the issue.  I've fixed it in f7cf707ea544.  Of course one could argue that maybe it should be
`if (!arr.count || !find_window(&wc->window, NULL, false))` instead of
`if (arr.count && !find_window(&wc->window, NULL, false))`,
but that's not really relevant either as `CGWindowListCreateImage` will return a safe-to-use value in either case.  I'll check to see if changing that around affects anything but I doubt it.

Although you're in the correct area of code, I don't think either of those things are relevant to the performance issue.  However if I'm wrong I'll gladly eat my words so I'll test it out and report back.

As for the Metal topic that came up for some inexplicable reason, we had a Metal implementation submitted three or four years ago.  I initially tried to communicate with the author of the PR, but had no response.  I'm pretty sure based upon the author's profile, the author did not speak English, but regardless no real communication ever occurred.  It was not due to toxicity or anyone considering OBS "DirectX-only", that has never been the case, and I would challenge you to find a single case where anyone representative of OBS claimed it was "DirectX-only".  Anyway that false claim aside, at the time, there were a couple issues with the PR, and the author was not responding.  Apple had not deprecated OpenGL, and I did not think Apple would do such a thing, so I felt it was redundant and wanted to understand the motivation behind it.  Eventually, I closed it because there was no response, and I felt it was an unnecessary change at the time.  OBS does not particularly require multi-threaded rendering because its rendering is very simple, there wouldn't really be any gain out of it.

Later on, Apple deprecated OpenGL, so I reopened the pull request myself.  I still have a copy of it available on my local mac repository but is very out-dated and doesn't work.  Another developer I trust has offered to take up finishing the Metal renderer but he won't be available to do so for some time.  OpenGL still works on mac and probably will for quite a while so it's not a huge deal for the time being.  Additionally, whether we use OpenGL or Metal likely has little relevance to the actual issue report, as window capture on mac is an async source in the first place.  Asynchronous video sources are completely separate from the renderer.

> I failed to test this for OBS on multiple occasions, due to abundant other unrelated compiling issues from badly optimised code

> I completely understand that OBS is in many parts cobbled-together from throwing code at it and seeing what sticks

> There's a toxic atmosphere around OBS being DirectX-only and none of the Mac devs that I know are interested in dealing with that.

> Helping becomes difficult when you're talking to a wall of ignorance, so it makes sense that few people even try.

> was completely shot down due to "too much effort" and "OBS is DirectX based, be glad we have OpenGL support already"

> I can't reach out anywhere other than here or the (shockingly pointless) forums

> overwhelming amount of patch-job OBS code

All these comments and claims are completely unnecessary and detract from the issue.  You make accusations of toxicity, yet clearly contribute it.  I don't want to see any more of this, please.

**Comment by keyboardcowgirl** [comment] 2020-01-30 15:42
Oh, damn. I saw more off-topic nonsense and closed the thing before I saw the last reply.

> Additionally, I'd like to point out that in the subsequent mantis issue you link, `Netizen01` that you yourself reference does not state that it has anything to do with `CGRectNull`, but instead states: `I'm guessing it has more to do with threads and shared image buffers`, which to me sounds like a more plausible explanation. Unfortunately, we haven't heard back from that individual.

I understand that it could be badly documented or unclear, and that my interpretation of the code could be completely wrong, but I can't verify anything because I both don't understand and don't know what to do with anything because I've had zero training or practice in C++ other than poking at OBS.

> All these comments and claims are completely unnecessary and detract from the issue. You make accusations of toxicity, yet clearly contribute it. I don't want to see any more of this, please.

That's just how I talk when I get frustrated, I'll try to cut it out.

**Comment by jp9000** [comment] 2020-01-30 15:52
I reopened it for you.

Also, thank for you the positive response.  Hurtful responses help no one.  A lot of good people have come together to contribute to this project, and despite its flaws and their flaws, it is not merely some cobbled-together thing.  A lot of care and love has gone in to this project and I will defend it -- and defend them -- adamantly.

**Comment by keyboardcowgirl** [comment] 2020-01-30 15:59
> Also, thank for you the positive response. Hurtful responses help no one.

Correct, I got too frustrated with others not knowing what they're on about and pointing at all kinds of directions while I just wanted to know a difference between one thing or the other, and if I was at all correct in my assumption about a dumb null-square being captured.

I wish there were more Mac devs, so that these things could be explained more clearly, but the majority that I know only work in ObjC or Swift, and don't touch C++ or OBS, even when I ask them. They just insult the efforts and move on along.

**Comment by zackees** [comment] 2020-04-02 01:39
Please fix this issue it's the main reason I can't use this program right now!

Also as a quick hack... what about saving the last good frame and if there is a black frame AND the previous frame was not black, use the previous frame once. This would fix 80% of the problem. I know it's not ideal but would really help.

Thanks a lot everyone for a great program!

**Comment by Fenrirthviti** [comment] 2020-04-26 04:40
Is someone able to please summarize this issue as the original post has been deleted? The discussion here makes it difficult to understand what the issue is and how to replicate so that we can start looking in to it. Last I can recall, we did not have replication steps or access to a machine where this was happening on to investigate.

**Comment by Fenrirthviti** [comment] 2020-04-27 01:19
After reading this over and discussion with the team, there doesn't appear to be anything of value in this thread. Going to close it as it's not even clear what the issue is, and there is nothing actionable here. If someone has proper replication steps for this, we would love to see a new issue reported so we can resume investigation. As it stands, we have been unable to replicate this issue.

**Closed by Fenrirthviti** 2020-04-27 01:19 UTC
Labels: Mantis Duplicate, macOS
