### ISSUE TITLE
Browser sources do not render when running more than one instance

### ISSUE THREAD

**Issue by GalvinPython** [obsproject/obs-studio#11635] opened 2024-12-15 20:49 UTC
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/YWCbFWsQkQZhBUFN

### Expected Behavior

When running OBS in a second or more instance, browser sources should be running as usual

### Current Behavior

When opening OBS in one instance, browser sources work fine, however after opening a second instance, the browser sources doesn't get rendered. In my screenshot, the first instance I loaded in the front, and the second instance behind. You can see in the second instance, where the browser should be displayed, nothing gets shown

This works in 30.2.3, but not in 31.0.0

![msedge_yWW3ZWi6Rv](https://github.com/user-attachments/assets/80259e68-c220-40d5-8ad3-f47011ab2523)

### Steps to Reproduce

1. Open 2 OBS instances
2. Add Browser sources to each, can be default
3. See if both appear or not. In this case, only 1 of the 2 work.

### Anything else we should know?

The log I linked above was for the second instance, the first instance for comparison is [here](https://obsproject.com/logs/JRg4iwSisheF1Jdi), if it may be useful

**Comment by RytoEX** [comment] 2024-12-15 20:53
Duplicate of https://github.com/obsproject/obs-browser/issues/465

**Closed by RytoEX** 2024-12-15 20:53 UTC

**Comment by webupdates** [comment] 2025-01-30 19:09
I just want to say that I am getting this error too.  I experience Black on the browser, on the second and subsequent OBS instances.  I really need this this feature so I downgraded to an older version and it works.  However, I need this to work on the latest version.

I am willing to test any fixes if you need people to help on this front.

**Comment by Thiran23** [comment] 2025-01-30 19:57
hi, i managed to fix my issues by making a portable obs version instead of just a normal second instance. This way browser sources show on both obs.

**Comment by Fenrirthviti** [comment] 2025-01-30 20:01
Please use https://github.com/obsproject/obs-browser/issues/465 for tracking updates.

However, we do not need any additional "this is happening to me too" comments, as we already confirmed this is happening. Follow the other issue for updates as we have them, but as far as we know there isn't much we can do.
