### ISSUE TITLE
Black preview screen in Linux Mint

### ISSUE THREAD

**Issue by Marto32** [obsproject/obs-studio#4259] opened 2021-02-19 20:18 UTC
## Platform
Operating system and version: Linux Mint 20.1 Ulyssa
OBS Studio version: OBS 26.1.1

## Expected Behavior
When I add/unhide a source, the preview of what would be recorded shows up in the OBS UI.

## Current Behavior
A black screen appears with no preview available ([screenshot](https://obsproject.com/forum/attachments/screenshot-from-2021-02-17-21-31-51-png.67703/)). Logfile linked [here](https://obsproject.com/logs/Ry_jwwbVHGOHF0w2).

## Steps to Reproduce
1. Install linux mint 20.1
2. Install OBS studio 26.1.1 (via [these instructions](https://obsproject.com/wiki/install-instructions#linux)).
3. Add a source (either window capture / xcomposite or full display capture) with defaults
4. No preview screen.

## Additional information
Recordings *DO* seem to work. This seems to be an issue with the preview screen only. This has also been logged in a few forum posts listed below:
 * [Black preview screen in Linux Mint](https://obsproject.com/forum/threads/black-preview-screen-in-linux-mint.139490/)
 * [Window capture black screen.](https://obsproject.com/forum/threads/window-capture-black-screen.123791/)
 * [Bug report - window capture black screen](https://obsproject.com/forum/threads/solved-window-capture-black-screen.47082/)

**Comment by GeorgesStavracas** [comment] 2021-02-19 20:43
No failure was recorded when creating the texture, however on teardown there's:

```
xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadPixmap
```

**Comment by Marto32** [comment] 2021-02-24 23:16
Could this be an nVidia issue?

**Comment by GeorgesStavracas** [comment] 2021-02-24 23:27
Either an NVidia issue, or an actual issue in the code that is only (or most frequently) triggered by NVidia drivers or hardware. Hard to know :slightly_frowning_face:

**Comment by awarus** [comment] 2021-03-03 14:46
It seems that GLXPixmap isn't valid(due to GLXDrawable isn't a valid pixmap). Also it's maybe a duplicate of  #3862. Guys [there](https://www.reddit.com/r/archlinux/comments/dry5iz/obs_studio_nvidia_mutter_gnome_and_others_black/) give an advice 
`disable "Allow Flipping" in nvidia-settings for opengl` Who knows, maybe it could help you. 
But if it's not - try with different desktop environment/Xorg/OpenGL version

**Comment by edmundlaugasson** [comment] 2021-03-15 23:00
Having same issue with 64-bit Linux Mint 20.1 Cinnamon and OBS 26.1.1. Some windows with XComposite are black (desktop, web browser Brave, etc.), some visible (terminal, Thunderbird, etc.). At the same time desktop with XHSM is working fine.

Having nVidia Quadro M2000M (GM107GLM). _Allow flipping_ is disabled - didn't help. Also that alpha channel Mesa solution option under XComposite settings didn't help.
```
$ inxi -xxxG
Graphics:
  Device-1: NVIDIA GM107GLM [Quadro M2000M] vendor: Lenovo driver: nvidia v: 460.39 
  bus ID: 01:00.0 chip ID: 10de:13b0 
  Display: x11 server: X.Org 1.20.9 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 2560x1440~60Hz 
  OpenGL: renderer: Quadro M2000M/PCIe/SSE2 v: 4.6.0 NVIDIA 460.39 direct render: Yes
```

```
$ nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M2000M       Off  | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P8    N/A /  N/A |    394MiB /  4035MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18890      G   /usr/lib/xorg/Xorg                186MiB |
|    0   N/A  N/A     19251      G   cinnamon                           38MiB |
|    0   N/A  N/A     19655      G   ...gAAAAAAAAA --shared-files       12MiB |
|    0   N/A  N/A     19806      G   ...AAAAAAAAA= --shared-files       14MiB |
|    0   N/A  N/A     19910      G   ...96AB038DB6D131158B746C3CC        3MiB |
|    0   N/A  N/A     20058      G   ...token=1743612660864995289       12MiB |
|    0   N/A  N/A     26848      G   ...AAAAAAAAA= --shared-files      114MiB |
+-----------------------------------------------------------------------------+
```

**Comment by awarus** [comment] 2021-03-16 10:16
> Having same issue with 64-bit Linux Mint 20.1, Cinnamon and OBS 26.1.1. Some windows with XComposite are black (desktop, web browser Brave, Chromium, etc.), some visible (terminal, Thunderbird, System settings, file manager, etc.). At the same time desktop with XHSM is working fine.
> 
> Having nVidia Quadro M2000M (GM107GLM). _Allow flipping_ is disabled - didn't help. Also that alpha channel Mesa solution option under XComposite settings didn't help.
> 
> ```
> $ inxi -xxxG
> Graphics:
>   Device-1: NVIDIA GM107GLM [Quadro M2000M] vendor: Lenovo driver: nvidia v: 460.39 
>   bus ID: 01:00.0 chip ID: 10de:13b0 
>   Display: x11 server: X.Org 1.20.9 driver: nvidia 
>   unloaded: fbdev,modesetting,nouveau,vesa resolution: 2560x1440~60Hz 
>   OpenGL: renderer: Quadro M2000M/PCIe/SSE2 v: 4.6.0 NVIDIA 460.39 direct render: Yes
> ```
> 
> ```
> $ nvidia-smi 
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Quadro M2000M       Off  | 00000000:01:00.0  On |                  N/A |
> | N/A   44C    P8    N/A /  N/A |    394MiB /  4035MiB |      1%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A     18890      G   /usr/lib/xorg/Xorg                186MiB |
> |    0   N/A  N/A     19251      G   cinnamon                           38MiB |
> |    0   N/A  N/A     19655      G   ...gAAAAAAAAA --shared-files       12MiB |
> |    0   N/A  N/A     19806      G   ...AAAAAAAAA= --shared-files       14MiB |
> |    0   N/A  N/A     19910      G   ...96AB038DB6D131158B746C3CC        3MiB |
> |    0   N/A  N/A     20058      G   ...token=1743612660864995289       12MiB |
> |    0   N/A  N/A     26848      G   ...AAAAAAAAA= --shared-files      114MiB |
> +-----------------------------------------------------------------------------+
> ```
Seem's that the problem associated only with NVIDIA drivers and Xcomposite. 
Try to use 
`nvidia-xconfig --composite `
Here's described well:
https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/xcompositeextension.html 

I am almost sure that it's NVIDIA bug, because of this https://www.nvidia.com/download/driverResults.aspx/156182/en-us
`Fixed a bug that could prevent nvidia-xconfig from disabling the X Composite extension on version 1.20 of the X.org X server. `
Maybe your video card is not in this update. Anyway, try to contact Nvidia support for this problem

**Comment by edmundlaugasson** [comment] 2021-03-16 23:22
`nvidia-xconfig --composite` didn't help either :(
At one side, truly the card provider should solve.
Actually also software should support that solution...

**Comment by Marto32** [comment] 2021-03-17 01:01
FYI, I've posted a question in the nVIDIA support forums [here](https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/439689/nvidia-bug-causing-black-screen-in-obs-linux-mint-/). If you're experiencing this issue please +1 it on their forums as well.

**Comment by edmundlaugasson** [comment] 2021-03-26 18:40
I forgot to add, but I also posted it [here](https://forums.developer.nvidia.com/t/nvidia-bug-causing-black-screen-in-obs-studio-linux-mint-20-1-ulyssa/173267/3). Now same problem twice...

**Comment by Marto32** [comment] 2021-03-28 13:56
I never got a meaningful response on my nVIDIA post. Please keep us updated here if they provide any good info. Thanks @edmundlaugasson !

**Comment by edmundlaugasson** [comment] 2021-05-05 16:29
Perhaps is possible to use SimpleScreenRecorder libraries, which is also free and open-source app - https://github.com/MaartenBaert/ssr - usually that app has no issues and is capable capture even 3D apps.

**Comment by arrowgent** [comment] 2021-05-09 20:50
https://forums.developer.nvidia.com/t/nvidia-bug-causing-black-screen-in-obs-studio-linux-mint-20-1-ulyssa/173267/10

this may be concerning your MESA driver version == 1.20.x
if possible you need to test a different version or the older (known working) 1.19.x version of MESA

thats all i can give for help.   this solved my problem = reverting MESA.

**Comment by arrowgent** [comment] 2021-08-10 22:01
i wanted to report some testing and findings here

previously working fine: **Mesa 20.0.8, nvidia 460.x, xorg-xserver 1.19.6-1**
update again to latest: **Mesa 21.1.6, (nvidia 460.x), xorg-xserver 1.20.9-2**

again same issue
however i went through testing...
i tested nvidia-drm.modeset=0 & nvidia-drm.modeset=1
not the issue
you can check modeset with **sudo cat /sys/module/nvidia_drm/parameters/modeset**

i checked my ~/.profile (/etc/envoirnment if global)

because i have nvidia-prime & an optimus laptop i also have set 

> export __NV_PRIME_RENDER_OFFLOAD=1
> export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-0
> export __GLX_VENDOR_LIBRARY_NAME=nvidia
> export __VK_LAYER_NV_optimus=NVIDIA_only


what i found was using export `__NV_PRIME_RENDER_OFFLOAD=1` is causing this issue

disabling this and rebooting we can test this

**__NV_PRIME_RENDER_OFFLOAD=1 glxgears**
then
 **__NV_PRIME_RENDER_OFFLOAD=1 obs**
capture the glxgears window
PROBLEM FOUND.

and again setting `__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-0 glxgears`
you can test this.
SAME PROBLEM


end result:
OBS is not the issue, its a PRIME_RENDER_OFFLOAD issue

**Comment by gxalpha** [comment] 2022-11-13 00:12
GLX is no longer in OBS. As such, this issue should no longer be applicable.

**Closed by gxalpha** 2022-11-13 00:12 UTC
Labels: Linux
