### ISSUE TITLE
Preloading stinger in Memory

### ISSUE THREAD

**Issue by MattyFresh68** [obsproject/obs-studio#8422] opened 2023-03-07 20:37 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

latest nightly

### OBS Studio Log URL

https://obsproject.com/logs/wlXOpN8iHSMYEPVx

### Expected Behavior

When preloading the stinger into memory, I would expect the stinger to properly complete upon transition, however, as seen in the video I will attach, it seems to hang on near last frame, then suddenly changes to next scene.  I tested with both mov and webm versions of this stinger. Same behavior either way. I also closed obs between testing to see if that maybe changed behavior, which it did not. 

### Current Behavior

see above as well as video

### Steps to Reproduce

1. load stinger
2. set stinger properties to preload into memory
3. transition scenes
...
[Matty for Stream.webm](https://user-images.githubusercontent.com/66339760/223546602-68965041-9a29-4ac3-bf15-1f6b8f1bc654.webm)

https://user-images.githubusercontent.com/66339760/223546646-6654b969-eb04-486d-92f8-e7fba1d1f02d.mp4

### Anything else we should know?

Also chatted with sebastian in discord. He can reproduce

**Comment by flaeri** [comment] 2023-03-08 21:50
I can confirm this behavior. I also re-encoded the file to vp9 (again), and it still happens.

If I convert the file to argb pixel format, and use QuickTime RLE encoding, then it works. Absolutely no idea why that would be. I've tested several other vp9 stingers, and they work. However, none of them were as long (duration) as this one. 

Will try to make some longer ones and test.

**Comment by flaeri** [comment] 2023-03-08 22:06
Alright, that was a bit faster than I thought it would be. Its because of the audio. If you take the stinger file provided, and strip away the audio, it plays fine.

If I take the same singer file, and extend the audio for about an extra second, it plays back fine.

Just to confirm, I also did the audio in vorbis instead of opus, and it has the same issue.

**Comment by jp9000** [comment] 2023-03-26 05:52
Closed via 35f037d

**Closed by jp9000** 2023-03-26 05:52 UTC
