### ISSUE TITLE
Covering Fullscreen/Windowed Projector breaks Discord stream

### ISSUE THREAD

**Issue by jsonvillanueva** [obsproject/obs-studio#8941] opened 2023-05-20 17:42 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/4JmXSGNuetDCS9H0

### Expected Behavior

As in versions 27.0.1 and 27.1.3 (before the UI/Qt update), whenever the projector window was partially covered by another window, Discord would continue to show the projected OBS content.

### Current Behavior

When the Windowed/Fullscreen projector is covered, the projector content cuts out and shows the Discord preview stream image:
https://github.com/obsproject/obs-studio/assets/29168469/884dc3cd-41cf-4f1f-bc8b-c79e7a53574f

### Steps to Reproduce

1. Download any version of OBS 28.0 and later, and Discord
2. Launch OBS, create a scene, and open a Fullscreen/Windowed Projector
3. Grab any other windowed application and move it over the Fullscreen/Windowed Projector
4. (optional: make window "Always on Top") This is a small patch for the issue but removes screen real-estate.

### Anything else we should know?

I wouldn't mind the opportunity to work on this bug myself. I typically stream on Discord using OBS and its Windowed Projector and know this is a pretty niche use case. My Discord username is `jsonv#2494`.

**Comment by RytoEX** [comment] 2023-05-20 17:59
Sounds like a duplicate of #7254.

**Closed** 2023-05-20 18:23 UTC
