### ISSUE TITLE
OBS Studio Crashes Upon Entering Settings Menu

### ISSUE THREAD

**Issue by Ryu945** [obsproject/obs-studio#9341] opened 2023-07-30 18:47 UTC
### Operating System Info

Other

### Other OS

Nobara 37 ( Based on Fedora 37 Gnome)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Nn91Yzf5n4JCojgY

### OBS Studio Crash Log URL

https://obsproject.com/logs/Nn91Yzf5n4JCojgY

### Expected Behavior

When clicking on Settings I go into the Settings menu.

### Current Behavior

It freezes up for a second or two and then crashes.

### Steps to Reproduce

1.  Launch application
2.  Click onf File->Settings
3.  Program Crashes
...

### Anything else we should know?

This is the RPM version of OBS Studio.  X11 interface is being used to run the computer.

**Comment by tytan652** [comment] 2023-07-30 19:05
Duplicate of #9158

**Closed by tytan652** 2023-07-30 19:05 UTC

**Comment by Ryu945** [comment] 2023-07-31 20:21
The following fixed it.

Uninstall with:
`sudo dnf remove obs-studio`

Update Keys with:
`sudo dnf update nobara-gpg-keys --nogpgcheck --refresh` 

Install with:
`sudo dnf install obs-studio`
