### ISSUE TITLE
Encoder overload and lag when using B Frames on RX 6700XT

### ISSUE THREAD

**Issue by deepakkajla** [obsproject/obs-studio#7064] opened 2022-08-14 12:42 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/c7K6O82Z0Bg7xLR5

### Expected Behavior

Adrenalin 22.8.1 fresh installed with DDU in safe mode.
Followed the tutorial by EposVox to enable B fames in OBS (https://www.youtube.com/watch?v=DXL8_Adbob4)
Since, B frame input is available in UI now I just used the command line argument: HighMotionQualityBoostEnable=1
Started 1440p60 stream to youtube expecting some improved quality

### Current Behavior

Starting the stream shows stats as 98% frames skipped due to encoding lag
Setting B frames to 0 works fine (0% skipped)
Same experience in Beta 1 with command line arguments: MaxNumRefFrames=4 BReferenceEnable=1 BPicturesPattern=1 MaxConsecutiveBPictures=1 HighMotionQualityBoostEnable=1

### Steps to Reproduce

1. Youtube stream: 1440p60
2. Set any non zero value of B frame (1 in my case)
3. Start stream

**Comment by flaeri** [comment] 2022-08-14 15:30
Could you try downgrading to [22.5.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-1)?
Please try without anything in the custom options box.

If it's still lagging, try to reduce the "quality" to balanced, or even speed.

**Comment by deepakkajla** [comment] 2022-08-15 11:52
> Could you try downgrading to [22.5.1](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-1)? Please try without anything in the custom options box.
> 
> If it's still lagging, try to reduce the "quality" to balanced, or even speed.

Downgraded to 22.5.1 with DDU. Same issue, removed custom commands, dropped quality to balanced and speed. That only resulted in 50% and 25% skipped frames due to encoding lag respectively.

At 1080p60, balanced preset is fine, high still goes into encoding lag.

**Comment by lextra2** [comment] 2022-08-16 15:26
For higher then 1080p you'd want to use h265 anyways.

**Comment by deepakkajla** [comment] 2022-08-16 16:36
> For higher then 1080p you'd want to use h265 anyways.

Just trying to figure out why I can't recreate the settings by EposVox. Resolution is hardly the issue here, enabling B frames and quality settings are making the encoder overload at both 1080p60 and 1440p60

**Comment by lextra2** [comment] 2022-08-16 18:51
> > For higher then 1080p you'd want to use h265 anyways.
> 
> Just trying to figure out why I can't recreate the settings by EposVox. Resolution is hardly the issue here, enabling B frames and quality settings are making the encoder overload at both 1080p60 and 1440p60

Yup. I got that.

**Comment by gutko** [comment] 2022-08-16 21:28
did you try 2 bframes instead of 1? read somwhere 3 causes problems, so maybe also 1 as odd number, just a loose guess

**Comment by deepakkajla** [comment] 2022-08-21 06:33
> did you try 2 bframes instead of 1? read somwhere 3 causes problems, so maybe also 1 as odd number, just a loose guess

Yeah, any non zero b frame input causes encoder lag.

Log for 1 b-frame: https://obsproject.com/logs/i9aOFwPrBabwtx01
Log for 2 b-frame: https://obsproject.com/logs/ytilm6qloPwJJku4
Log for 3 b-frame: https://obsproject.com/logs/bFPNJ9teaJbD8lW0

**Comment by cs9kc** [comment] 2022-08-31 13:18
The commit for the fix is here: https://github.com/obsproject/obs-studio/commit/07df6548fdb88e093eb0901106a882ad73ad9848

Once OBS Studio v28 releases, give 3 B-frames another try and see how it looks.

**Comment by cs9kc** [comment] 2022-08-31 13:18
> Yeah, any non zero b frame input causes encoder lag.

@deepakkajla The commit for the fix is here: https://github.com/obsproject/obs-studio/commit/07df6548fdb88e093eb0901106a882ad73ad9848

Once OBS Studio v28 releases, give 3 B-frames another try and see how it looks.

**Comment by RytoEX** [comment] 2022-08-31 18:07
Fixed by https://github.com/obsproject/obs-studio/commit/07df6548fdb88e093eb0901106a882ad73ad9848

If the issue is not fixed, please comment, and we can reopen.

**Closed by RytoEX** 2022-08-31 18:07 UTC

**Comment by cs9kc** [comment] 2022-09-01 12:38
@flyleaf1988 What exact options are you using in the encoder settings, both in the GUI and in the text entry field?

**Comment by flyleaf1988** [comment] 2022-09-01 13:53
> @flyleaf1988 What exact options are you using in the encoder settings, both in the GUI and in the text entry field?

![grafik](https://user-images.githubusercontent.com/66389489/187931387-835dbbb1-4c6b-42a4-b77f-5678ecab4691.png)

**Comment by flaeri** [comment] 2022-09-01 15:17
Instead of troubleshooting on a closed issue, could we instead perhaps do this in the support channels on the discord?
https://obsproject.com/discord

If you do not want to use discord or prefer the forums, you could do that instead: 
<https://obsproject.com/forum/list/windows-support.32/>

**Comment by flyleaf1988** [comment] 2022-09-01 15:32
> @flyleaf1988 Input "2" in the Keyframe Interval section and let me know how it behaves, please.

Same thing with all B-Frame Settings.



> Instead of troubleshooting on a closed issue, could we instead perhaps do this in the support channels on the discord? https://obsproject.com/discord
> 
> If you do not want to use discord or prefer the forums, you could do that instead: https://obsproject.com/forum/list/windows-support.32/

Sure, will report in Discord tomorrow.

**Comment by lextra2** [comment] 2022-09-03 07:03
For 1440p and higher, use HLS with x265 on YouTube...
