### ISSUE TITLE
WebRTC data channel not connecting in obs-browser

### ISSUE THREAD

**Issue by castles** [obsproject/obs-studio#2946] opened 2020-05-18 02:25 UTC
The WebRTC data channel fails to work in OBS on Mac. Windows works fine. 

## Platform
Operating system and version: OSX Catalina
OBS Studio version: 25.0.8

## Expected Behavior
Data Channel should connect.

## Current Behavior
Nothing happens. Data Channel doesn't connect. No errors are thrown.

## Steps to Reproduce
An easy way to test it is to open up this page in a browser that supports webRTC: https://mdn-samples.mozilla.org/s/webrtc-simple-datachannel/
You should be able to connect, type a message and send and receive.

In OBS if you add a browser with the same address and try to do the same it doesn't work.

## Additional information
No errors show up in the console when using --remote-debugging-port but these logs show up in terminal:

[0516/215229.218359:ERROR:data_channel.cc(44)] Accepting maxRetransmits = -1 for backwards compatibility
[0516/215229.218421:ERROR:data_channel.cc(49)] Accepting maxRetransmitTime = -1 for backwards compatibility

**Comment by Fenrirthviti** [comment] 2020-05-18 02:28
This is a duplicate of https://github.com/obsproject/obs-browser/issues/209 and this has been submitted to the wrong repo. Please follow that issue for updates and to report any additional findings.

**Closed by Fenrirthviti** 2020-05-18 02:28 UTC
