### ISSUE TITLE
OBS Studio 30.2.2 - Twitch Panels BUG

### ISSUE THREAD

**Issue by C74K** [obsproject/obs-studio#11054] opened 2024-07-31 12:48 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/yGjMSeGYnlpXnLle

### Expected Behavior

Saving the position of panels.
Not sending them to the desktop when minimized startup is set.

### Current Behavior

I had the panels arranged in the connected twitch account and turned OBS off.
10 seconds later I run OBS and the panel positions have not been saved.

### Steps to Reproduce

run obs
move panels
exit obs
run obs

https://youtu.be/T7Dk1WqfVbk

**Comment by mihawk90** [comment] 2024-07-31 17:39
> Not sending them to the desktop when minimized startup is set.

That sounds like a duplicate of #8614 then.

**Comment by C74K** [comment] 2024-07-31 20:19
> > Not sending them to the desktop when minimized startup is set.
> 
> That sounds like a duplicate of #8614 then.

no becose without --minimize-to-tray bug exist too.

**Comment by MrMetacomCode** [comment] 2024-08-03 07:25
I'm getting this same issue on 30.2.2 as well. The workaround mentioned [here](https://github.com/obsproject/obs-studio/issues/8614#issuecomment-1501211719) fixed it for me. I just need to have OBS not in full screen before it's launched again and the docks stay where they should be in the minimized window and don't popup separately.

**Comment by RytoEX** [comment] 2024-08-05 23:29
Please note that "fullscreen" and "maximized" are two different window states. Pressing F11 or selecting "View -> Fullscreen Interface" from the OBS menu bar activate fullscreen mode. Selecting the OBS icon and selecting "Maximize" or pressing the maximize button in the window controls in the upper right maximizes the window size.

That said, this all sounds like a duplicate of #8614, which itself sounds like a Qt window geometry bug if the window state is "maximized" on exit.

**Comment by RytoEX** [comment] 2024-08-05 23:29
Duplicate of #8614

**Closed by RytoEX** 2024-08-05 23:29 UTC
