### ISSUE TITLE
OBS Studio records stuttering video with variable FPS

### ISSUE THREAD

**Issue by UAVXP** [obsproject/obs-studio#10467] opened 2024-04-02 00:06 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/J1rQ8ypiGsP7Wsxw

### Expected Behavior

Smooth constant 60 FPS video

### Current Behavior

Choppy, stuttering variable ~15 FPS video

### Steps to Reproduce

1. Launch OBS Studio >=30.1.0
2. Settings -> Video -> all resolutions set to 1920x1080, FPS = 60
3. Settings -> Output:
```
Output Mode: Simple
Recording Quality: High Quality, Medium File Size
Recording Format: Matroska Video (.mkv)
Video Encoder: Hardware (AMD, H.264)
Leave all the other settings on default
```
4. Add Game Capture to the default Scene
5. Capture Specific Window; hl2.exe; all the other settings are default
6. Switch to the game window and start recording
7. Stop recording
8. Check the recorded video and cry a bit

### Anything else we should know?

I have AMD R7 360 GPU.

Haven't tested beta and release candidates. All the versions I tested were:
```
30.1.1: bug appears [(log)](https://obsproject.com/logs/J1rQ8ypiGsP7Wsxw)
30.1.0: bug appears
30.0.2: everything is alright [(log)](https://obsproject.com/logs/9W6OuXVUpX8pe6JN)
```

I also have uploaded video examples:
[OBS Studio 30.1.1 example](https://drive.google.com/file/d/1-xPOzSXD3amSGxxkxLMbhiAH7bFlfeI6/view?usp=drive_link)
[OBS Studio 30.0.2 example](https://drive.google.com/file/d/1y7xazAyZXOq3CCitr8JcpegPfNDyuxQe/view?usp=drive_link)
(better download them instead of watching in browser player)

**Comment by RytoEX** [comment] 2024-04-02 00:08
Duplicate of #10368

**Closed by RytoEX** 2024-04-02 00:08 UTC

**Comment by UAVXP** [comment] 2024-04-02 00:15
Oh, sorry, haven't found this issue for some reason. Thank you for advice!
