### ISSUE TITLE
Firefox crashes with [@ obs-virtualcam-module64.dll | RtlFreeHeap ] 

### ISSUE THREAD

**Issue by Pehrsons** [obsproject/obs-studio#7672] opened 2022-10-27 08:30 UTC
### Operating System Info

Other

### Other OS

Windows

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.*, 28.*

### OBS Studio Log URL

n/a

### Expected Behavior

No crashes

### Current Behavior

In Firefox crash reporting we see [a crash in [@ obs-virtualcam-module64.dll | RtlFreeHeap ]](https://crash-stats.mozilla.org/signature/?signature=obs-virtualcam-module64.dll%20%7C%20RtlFreeHeap#reports).

We think this could be related to issue #4243. Perhaps it is the [remaining issue with switching resolutions](https://github.com/obsproject/obs-studio/issues/4243#issuecomment-1267743950)?

Re the fixes in that issue we do see some crashing of Firefox caused by obs-virtualcam-module64.dll that has ceased in v28, and then we have this one that didn't, we see it in both v27 and v28. There are also some other crash signatures tied to unknown versions of obs-virtualcam-module64.dll. See more details in the [Firefox bug tracker, bug 1707060](https://bugzilla.mozilla.org/show_bug.cgi?id=1707060#c22).

From the stack there isn't much to go on. [Here is a related report](https://crash-stats.mozilla.org/report/index/063964a1-6514-4ed4-aeed-8999b0220610) with a bit more on the stack. It is however older. In all the reports I looked at the VideoCapture thread is idle, and that's the one where the previous unload race crash was happening. In [one report](https://crash-stats.mozilla.org/report/index/b50ecd39-d430-42f1-979c-abb590221022) I saw the name of the crashing thread and it is [the one that calls IMemInputPin::Receive](https://searchfox.org/mozilla-central/rev/2d1097c27f31cb15f7588b043d691cda9710d14b/third_party/libwebrtc/modules/video_capture/windows/sink_filter_ds.cc#746). Another difference from the unload race is that obs-virtualcam-module64.dll is not yet unloaded.

### Steps to Reproduce

Unknown

### Anything else we should know?

The appropriate Firefox bug is probably [bug 1691902](https://bugzilla.mozilla.org/show_bug.cgi?id=1691902).

**Comment by WizardCM** [comment] 2022-10-27 08:44
This crash might be fixed in either https://github.com/obsproject/obs-studio/commit/feda64e9c618ed217a6549f3457960a54ebef207 or https://github.com/obsproject/obs-studio/commit/bcb73cb5994d932c7a902e8585dabb25feeb251f - both of which are available in [28.1.0 RC1](https://github.com/obsproject/obs-studio/releases/tag/28.1.0-rc1), and will ship as part of OBS 28.1.

**Comment by jp9000** [comment] 2022-10-27 10:10
Thank you very much for the report. There was indeed that remaining known crash caused by changing the resolution. We finally figured out how to reproduce it, and it turns out it's caused by changing the resolution *without* recreating the filter, a case I didn't properly account for, and that doesn't happen in most DirectShow programs. It was reproducible by setting obs to a resolution higher than 1080p, turning on the virtual camera, then going to the webcamtests website in firefox and running its tests on the OBS virtual camera.

It's possible there might be a remaining issue if formats change without recreating the filter, but that (hopefully) should be far more rare case than resolution changes. I'll probably have to make some testing changes to properly test and account for that as well at some point.

Regardless, I'm terribly sorry for any trouble. Assuming this is the cause the reports, the fix will be out with 28.1, which will be very soon like @WizardCM said. The second commit he was referring to was unrelated to this and was a bug specific to Discord's desktop software on Windows, and is a workaround to what I heavily suspect to be a bug in their code.

**Comment by gxalpha** [comment] 2022-11-03 18:54
@Pehrsons could you confirm if this is fixed with OBS 28.1?

**Comment by RytoEX** [comment] 2022-12-07 06:07
We think that the crash on resolution change was resolved with commit https://github.com/obsproject/obs-studio/commit/feda64e9c618ed217a6549f3457960a54ebef207, which is available as of OBS Studio 28.1.0. Another fix was committed as https://github.com/obsproject/obs-studio/commit/6693f3928831a69d73ae057405a918559e6d32de (technically a revert, but the original commit caused other breakage when paired with our other fixes), which is available as of OBS Studio 29.0.0 Beta 1 (and Beta 2). I skimmed recent Mozilla crash logs and did not see any crashes with version 29.0.0 of obs-virtualcam-module64.dll. I'll try to circle back around to this periodically to see if any such reports surface. Is there any easy way to search for reports by module version?

**Comment by Pehrsons** [comment] 2022-12-08 07:31
The only thing the super search on crash-stats can help you with regarding modules is for those modules that are on the stack of the crashing thread. See https://crash-stats.mozilla.org/documentation/supersearch/api/#param-modules_in_stack

It won't take the version number though; it will take the debug id. This can also be seen together with the version number on the modules tab of a crash report. _CDAD977C25F142089EF072AC9AB46FB11_ is for 28.1, but I haven't seen any for 29.

So [here are all Firefox crashes](https://crash-stats.mozilla.org/signature/?modules_in_stack=~obs-virtualcam-module64.dll%2Fcdad977c25f142089ef072ac9ab46fb11&product=Firefox&signature=obs-virtualcam-module64.dll%20%7C%20RtlFreeHeap&date=%3E%3D2022-12-01T07%3A21%3A00.000Z&date=%3C2022-12-08T07%3A21%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports) in the last week (dec 1 to dec 8) with obs-virtualcam-module64.dll v28.1 on the crashing stack.

**Comment by RytoEX** [comment] 2024-02-07 18:32
This, or at least the bulk of crashes like this, is (probably) fixed by #10203, so I'm going to optimistically close this as fixed. Should be shipped in OBS Studio 30.1 Beta 2.

**Closed by RytoEX** 2024-02-07 18:32 UTC
