### ISSUE TITLE
Hyprland Flatpak OBS Cuda Error

### ISSUE THREAD

**Issue by Tahinli** [obsproject/obs-studio#11302] opened 2024-09-19 20:16 UTC
### Operating System Info

Other

### Other OS

Fedora 40

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/vwfsSoz5alOQGhjn

### Expected Behavior

Should record

### Current Behavior

It's not recording with hardware acceleration

### Steps to Reproduce

1. Open OBS Flatpak in Hyprland
2. Select One of the Nvidia Acceleration Codec
3. Try to Record
...

### Anything else we should know?

Flatpak version wasn't working. I uninstalled flatpak version and installed via Fedora Fusion repo, it worked then I install flatpak version again, flatpak version's also working now, but I wanted to report anyway so maybe you can fix this in the first place.

Error was: 

init_cuda_ctx: CUDA call "cu->cuInit(0)" failed with CUDA_ERROR_UNKNOWN (999): unknown error

**Comment by pseudovector** [comment] 2024-09-21 19:27
same issue here

**Comment by isaacbatst** [comment] 2024-10-12 16:36
same here on debian

**Comment by derrod** [comment] 2024-10-12 18:26
Duplicate of #11381 (though technically this one was older, but the other one has some solutions/workarounds).

**Closed by derrod** 2024-10-12 18:26 UTC
