### ISSUE TITLE
OBS virtual camera gives a red screen only

### ISSUE THREAD

**Issue by eyeweaver** [obsproject/obs-studio#7438] opened 2022-09-23 01:42 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/mOrfMqhE13vN0jEG

### Expected Behavior

I expect the virtual camera output to match the media sources I added

### Current Behavior

only a blank red screen

### Steps to Reproduce

1.just start the virtual camera
2.
3.
...

**Comment by RytoEX** [comment] 2022-09-23 01:46
Duplicate of #7333

**Closed by RytoEX** 2022-09-23 01:46 UTC
