### ISSUE TITLE
[BUG] BSD and Linux can start multiple obs-studio instances without --multi warning

### ISSUE THREAD

**Issue by walterav1984** [obsproject/obs-studio#3053] opened 2020-06-09 12:38 UTC
## Update:
MacOS part fixed by commit #3558 
Linux part fixed by #3654 

## Platform
Operating system and version:
FreeBSD 12.2 and current
~~Ubuntu mate Linux 20.04 & MacOS High Sierra 10.13.6~~
OBS Studio version:
25.03 & 25.08 & git commit build 05c9ddd

## Running multiple instances of obs-studio
Running multiple instances of obs-studio is actually a feature if used "responsible", however doing this unresponsible is sadly the case for BSD ~~and Linux and MacOS~~ users. Running another obs-studio instance while another is already running is easily done by accidently clicking its icon or running its command a second time which can have serieus affects on the current broadcast session like framedrops, blocking network ports, overwriting files etc besides confusing users with another instances where the capture devices are suddenly all black...

## Expected Behavior
When starting a second(/third/multiple) instance(s) of "obs-studio" while "obs-studio" was already running on BSD ~~and Linux and or MacOS~~, a warning window should pop up like on Microsoft Windows version of obs-studio which prevents the start of the second "obs-studio" instance until allowed explicitly by pressing "Launch Anyway".

## Current Behavior
The current wrong behaviour for BSD ~~and Linux and MacOS~~  is the same behaviour as using the Windows obs studio started with  `obs64.exe --multi` argument, which skips the warning Window. Using the "--multi" argument on BSD ~~and Linux and or MacOS~~ doesn't affect anything. ~~However MacOS is only affected when obs-studio has been started from the terminal since MacOS has its own sanitizing mechanism to prevent GUI apps to be run multiple times!~~

## Steps to Reproduce Ubuntu mate Linux 20.04 
0. open a terminal window
1. `sudo apt install obs-studio #default apt repository version 25.03 also affected`
2. `#run obs from terminal or from menu icon`
3. `#run another obs instance from terminal or from menu icon`
4. now you have two instances of obs-studio without a warning...

## Steps to Reproduce MacOS
1. Install latest OBS-Studio 25.08
2. run obs by clicking the application
3. open a terminal and run obs from the cli
4. `/Applications/OBS.app/Contents/MacOS/obs`
5. now you have two instances of obs-studio without a warning...

## Additional information
This file in the source code is probably the cause and maybe some ifdef unix:
https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1800

**Comment by emaste** [comment] 2020-06-09 18:04
Reproducible also on FreeBSD

**Comment by kkartaltepe** [comment] 2020-06-09 20:30
This is not implemented for non-windows platforms.
ref: https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1802

**Comment by walterav1984** [comment] 2020-06-10 05:48
Although not implemented running `obs -h` does show `--multi` as a argument on these platforms.

**Comment by akamensky** [comment] 2020-09-27 07:30
OBS uses QT for GUI, which allows to implement this easily.

I did implement this before using shared memory where new instance would try to acquire this shared memory and fail, this simultaneously allowed to "ping" original instance of OBS and bring it to front/focus (then secondary instance can exit with status 0).

The source I used for my own implementation is https://stackoverflow.com/questions/5006547/qt-best-practice-for-a-single-instance-app-protection

**Comment by walterav1984** [comment] 2020-10-16 21:58
@jp9000 is this also fixed for BSD and Linux?

**Comment by RytoEX** [comment] 2020-10-16 22:15
#3558 only addressed the macOS portion of this, so regrettably, I think we should reopen this until the Linux/BSD portion has also been dealt with.

**Comment by dodgepong** [comment] 2020-10-30 19:01
Looks like this was auto-closed by merging #3654, but I'm going to re-open since that PR does not fix the issue on BSD.

**Comment by emaste** [comment] 2020-10-30 19:42
Thanks, @khng300 or I should take a look at this. Our pidfile(3) API should be fine for this.

The Linux abstract namespace extension has some elegant properties but this should be good enough.

**Comment by emaste** [comment] 2020-10-30 19:56
FreeBSD version: 12.2 and -CURRENT

**Comment by khng300** [comment] 2020-10-31 16:20
Please check out https://github.com/obsproject/obs-studio/pull/3670 .

**Closed** 2020-11-14 20:04 UTC
Labels: Good first issue, Linux, macOS
