### ISSUE TITLE
Crash when doing quickstart

### ISSUE THREAD

**Issue by cinnamonbubblegum** [obsproject/obs-studio#6620] opened 2022-06-17 08:53 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/08he5byf5V5UIN-r

### OBS Studio Crash Log URL

https://obsproject.com/logs/eNUItWqJkIJZIGbI

### Expected Behavior

No crash

### Current Behavior

Crashed while running bitrate test for chaturbate

### Steps to Reproduce

Didn't crash when running the same thing again 🤷

**Comment by WizardCM** [comment] 2022-06-17 08:55
You have the following third party plugins installed. See if it happens without them installed:


`Lovense_Update.dll`
`lovense-obs-toolset.dll`
`lovense-Ai-camera.dll`

**Comment by Nofew** [comment] 2022-06-17 11:43
Last I heard, Lovense wasn't compatible with 27.2.4. Last working version was 27.1.3. You can find that from the Releases section on Github. You might need to go back to page 2 to see it.

**Comment by Fenrirthviti** [comment] 2022-06-18 04:28
They do shenanigans with shipping a custom version of the browser source that uses some of our built in components, which means it probably hasn't been updated for the new CEF version we use in newer versions. They will need to update their plugin to either stop using those components, or update to our current supported CEF version, but all that said I don't believe that would cause a crash in the video output thread. I could be mistaken, however.

**Comment by Fenrirthviti** [comment] 2023-01-27 20:02
Since this is most likely caused by third party plugins, and there hasn't been a response in some time, closing.

**Closed by Fenrirthviti** 2023-01-27 20:02 UTC
