### ISSUE TITLE
browser source: Crash often while switching URL

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#6104] opened 2022-03-08 02:54 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Version (Other)

using latest OBS and obs-browser

### OBS Studio Log URL

none

### Expected Behavior

no crash after changing URL

### Current Behavior

crash at obs-browser-page.exe often after changing URL

### Steps to Reproduce

1. add browser source
2. open property window, modify URL and click OK
3. repeat step-2, crash happen sometimes

### Anything else we should know?

I am using VS in DEBUG mode. The output window of VS shows:

_0x00007FFE174B4F69 处(位于 obs-browser-page.exe 中)引发的异常: Microsoft C++ 异常: SysferException，位于内存位置 0x000000DC2EB5D610 处。
程序“[13640] obs-browser-page.exe”已退出，返回值为 0 (0x0)。_

**Comment by walker-WSH** [comment] 2022-03-08 02:54
0x00007FFE174B4F69 处(位于 obs-browser-page.exe 中)引发的异常: Microsoft C++ 异常: SysferException，位于内存位置 0x000000DC2EB5D610 处。
程序“[13640] obs-browser-page.exe”已退出，返回值为 0 (0x0)。

**Comment by WizardCM** [comment] 2022-03-08 02:55
Duplicate of #356

**Closed by WizardCM** 2022-03-08 02:55 UTC

**Comment by walker-WSH** [comment] 2022-03-08 03:03
@WizardCM   

Please known that crash will happen even not using haredware acceleration

**Comment by WizardCM** [comment] 2022-03-08 03:10
Please provide your findings on the other ticket.

**Comment by mask2012** [comment] 2022-07-18 07:25
I have the same problem, to reshow it is very simple, just change url A to url B for > 5 times ,you will see a black browser and after that it will keep black whatever you do, unless restart obs.
