### ISSUE TITLE
AMF Encoder HDR metadata missing / no longer detected by youtube after 29.1.0

### ISSUE THREAD

**Issue by lza78** [obsproject/obs-studio#9195] opened 2023-07-02 10:13 UTC
### Operating System Info

Windows 11

### Other OS

-

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Oe5GVY3AUbx0wBCp

### Expected Behavior

After uploading a obs studio recording in youtube,and after youtube done processing it,youtube allows users to watch the video in HDR.
I upload a video by :
i) https://studio.youtube.com/
ii)Upload videos
iii)Select the obs studio recording and adding description 
iv)wait for it to be processed by youtube(which takes several days at most)

### Current Behavior

When I finish uploading a video to youtube as usual,youtube does not says that the video is HDR even after it done processing.

### Steps to Reproduce

1.Use obs studio 29.1.0 and onwards to make a screen recording
2.Upload it to youtube as usual
3.Youtube does not detect/process HDR

### Anything else we should know?

https://obsproject.com/logs/07wiUuIEPUA2GCx8 
This is the log file where I use OBS STUDIO 29.0.2 to upload videos to youtube normally.After processing,youtube automatically shows the video in HDR.
Since OBS studio 29.1.0 and above,HDR videos is no longer detected automatically by youtube after uploading it.
Every settings is the same in both version that I mentioned.The versions are the only difference unless the newer version(29.1.0 and onwards modified some default settings)

**Comment by derrod** [comment] 2023-07-02 11:28
HDR processing takes longer than the SDR versions, and YouTube does not show any inidcation that it's still processing. You'll just have to wait.

**Comment by lza78** [comment] 2023-07-03 09:36
Hi,I am absolutely sure that it is fully processing already. Those videos I recorded using obs studio 29.0.1 and onwards is already uploaded to youtube for 2 months.After I switched back to obs studio 29.0.2,every video I upload only takes at most 3 days for HDR to be available.I even tried uploading a 2 seconds video to youtube (using obs studio 29.1.3),and after that upload a 2 hours worth of video (using obs studio 29.0.2) and yet after that 2 hours video shows HDR,the 2 seconds video does not have HDR still.

**Comment by derrod** [comment] 2023-07-03 09:47
I uploaded a few test clips recorded with 29.1.3 and 29.0.2 to YouTube and all were processed with HDR renditions available after a few hours.

**Comment by lza78** [comment] 2023-07-03 13:12
Should I contact youtube support instead?
Or can you offer me some ways to troubleshoot what's wrong when I upgraded from 29.0.2 to 29.1.3?
Thanks :)

**Comment by flaeri** [comment] 2023-07-03 13:13
> I uploaded a few test clips recorded with 29.1.3 and 29.0.2 to YouTube and all were processed with HDR renditions available after a few hours.

Did you test with AMF? I did 4, mp4+mkv, p010 and i 010. It's been 2 days, and none of the 4 has gotten HDR. The 5th file I uploaded at the same time (known good) got it within the hour.

I couldn't see anything wrong on the surface, all files seem to have the required data, but may need to dig deeper.

**Comment by derrod** [comment] 2023-07-03 14:44
I've only tested NVENC on my end, perhaps if you could provide us with a sample (github should allow uploads of smaller files, so just do a short test recording) we can investigate further.

**Comment by lza78** [comment] 2023-07-03 14:58
Github does not support .mkv files.So I upload the video to weshare instead.
https://we.tl/t-1QEODYnwMr
just in case you want a log file here it is : https://obsproject.com/logs/zDwUDTuGKbnBywjQ

**Comment by derrod** [comment] 2023-07-04 04:38
Not entirely sure what's happening here, but it appears that your files are not tagged correctly, MediaInfo shows BT2020 etc. but ffprobe does not (remuxed):
`Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 2880x1800, 4166 kb/s, 60 fps, 60 tbr, 16k tbn (default)`
It seems the container might have the necessary metadata, but the video stream itself does not.

By manually changing the metadata in the HEVC stream using the `hevc_metadata` bitstream filter this can be fixed like so:
`ffmpeg -i <input> -c copy -bsf:v hevc_metadata=colour_primaries=9:transfer_characteristics=16:matrix_coefficients=9 <output>`

The file will then correctly show up in ffprobe and on YouTube:
`Stream #0:0[0x1](und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 2880x1800, 4166 kb/s, 60 fps, 60 tbr, 16k tbn (default)`

Going to reopen this with some edits to make clear that this is an issue with AMF.

**Comment by lza78** [comment] 2023-07-04 07:18
do I need to change the metadata every time before I upload to youtube or a fix will be included in the next obs studio version?

**Comment by derrod** [comment] 2023-07-05 08:35
We don't know what the issue is yet, so we can't promise a fix to be in the next version.

**Comment by flaeri** [comment] 2023-07-08 09:35
Bisected it to this deps update:
b262eea - CI: Update deps to 2023-03-20 release

Highly suspect its from the ffmpeg 6.0 version bump. Will try to have a look, but can't make any promises. Not that familiar with that part of the code.

**Comment by flaeri** [comment] 2023-08-03 08:04
I can confirm that using the 2023-03-20 deps, but reverting the ffmpeg bump 681fa3dbb will solve the issue.

**Comment by flaeri** [comment] 2023-08-03 12:47
With some help from @pkviet (lifesaver), I believe I've found the offending commit in ffmpeg here: https://github.com/FFmpeg/FFmpeg/commit/8b5d15530127fea54e934043a64653859de07353

Reverting requires reverting fc410ce (changes log type for 8b5d155) and c421000 (changes indentation for 8b5d155), neither of which has any functional change to 8b5d155.

**Comment by Yw0ke** [comment] 2023-08-26 13:00
Hey guys, Is there a simple way to fix this while waiting for an update ?
I've seen the command line above that will fix a file but i cant be bothered to do that for every record i do.
Thanks for reporting this and the work behind finding what cause the issue.

**Comment by lza78** [comment] 2023-11-14 05:45
This issue seems not to be solved in OBS studio 30.0 yet

**Comment by derrod** [comment] 2023-11-14 05:50
This has been determined to not be an OBS issue but a problem on AMD's side, if it's not fixed in the latest driver yet then you'll have to wait a bit longer.

But a good time to close this as we don't have to make any changes on our end.

**Closed by derrod** 2023-11-14 05:50 UTC

**Comment by RytoEX** [comment] 2023-11-16 20:02
> This issue seems not to be solved in OBS studio 30.0 yet

There was a fix for missing VUI information for HDR in the AMD 23.11.1 drivers. With those, OBS will correctly produce HDR video files when using the AMD HW encoders.

**Comment by lza78** [comment] 2023-11-17 07:01
Well I purposely used PRO drivers because using adrenaline version(I forgot to take note since which),OBS studio will keep saying "Encoding overloaded" and the recording produced is laggy.Now I can only hope that the PRO driver won't have the same issue after updating.
