### ISSUE TITLE
OBS 28.0.2 - Virtual Camera broken on MAC

### ISSUE THREAD

**Issue by sissiwup** [obsproject/obs-studio#7460] opened 2022-09-25 09:01 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.2

### OBS Studio Log URL

No Crash

### Expected Behavior

Show video

### Current Behavior

Show screen like obs not started

### Steps to Reproduce

1.Start OBS
2.Start virtual CAM
3.Start Teams, Webex ore something
...

### Anything else we should know?

28.0 did not work either

**Comment by WizardCM** [comment] 2022-09-25 09:07
This report has nowhere near enough information. A log file is required.

**Comment by Fenrirthviti** [comment] 2022-09-25 17:57
Closing as invalid report. If further information can be provided, we can repoen.

**Closed by Fenrirthviti** 2022-09-25 17:57 UTC

**Comment by banad60** [comment] 2022-09-29 08:46
sissiwup is right, the virtual cam is broken! 
and it seems, not only on mac. it also don't want start on ubuntu 22.04 with an OBS 28.0.2

And this is what your log saying:
10:38:40.954: NV12 texture support not available
10:38:40.954: P010 texture support not available
10:38:40.955: Failed to start virtual camera

a not very usefull message, because i see myself that the virtual-cam is not coming up.

**Comment by RytoEX** [comment] 2022-09-29 18:14
> sissiwup is right, the virtual cam is broken! and it seems, not only on mac. it also don't want start on ubuntu 22.04 with an OBS 28.0.2
> 
> And this is what your log saying: 10:38:40.954: NV12 texture support not available 10:38:40.954: P010 texture support not available 10:38:40.955: Failed to start virtual camera
> 
> a not very usefull message, because i see myself that the virtual-cam is not coming up.

The virtual camera implementations are completely separate per platform (Windows, macOS, Linux/*nix). They have nothing to do with each other. If you have a specific bug with detailed Steps To Reproduce that is not already in our [GitHub Issues](https://github.com/obsproject/obs-studio/issues), then feel free to open an Issue.
