### ISSUE TITLE
Replay Buffer should not stop the program from closing.

### ISSUE THREAD

**Issue by djtravz** [obsproject/obs-studio#3921] opened 2020-12-17 16:25 UTC
Whenever I start playing a game, I always start the Replay Buffer so I can easily save my game clips. When I shut down my computer and walk away, it doesn't shut down because OBS prevents it from doing so. I don't think that the Replay Buffer should be a reason to keep OBS open in this case.

## Platform

Operating system and version: Windows 10 18363.1256
OBS Studio version: 26.1.0

## Expected Behavior

I would want OBS to be able to close automatically when shutting down my computer if the Replay Buffer is running.

## Current Behavior

When the Replay Buffer is running and I attempt to close OBS, it gives the warning "OBS is currently active. All streams/recordings will be shut down. Are you sure you wish to exit?". This prevents windows from shutting down.

## Steps to Reproduce

1. Start the Replay Buffer
2. Attempt to close OBS/shut down Windows.

## Additional information

I apologize if this is not the correct place to put this because I didn't feel like this would qualify as a "Feature Request".

**Comment by RytoEX** [comment] 2022-01-27 18:03
Closing this as this behavior is by design and there's an option to suppress the warning as of OBS Studio 27.2.0.  Active outputs, including Replay Buffer, should prevent the application from closing by warning the user.

As of OBS Studio 27.2.0, which is currently in beta, you can disable all such confirmations/warnings on exit by disabling "Show active outputs warning on exit" in Settings > Advanced.

**Closed by RytoEX** 2022-01-27 18:03 UTC
