### ISSUE TITLE
hdr视频录制暂停闪退

### ISSUE THREAD

**Issue by cancundeyingzi** [obsproject/obs-studio#7068] opened 2022-08-14 17:48 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/hLYCF-DEHayI1SYf

### Expected Behavior

不应闪退,暂停录制视频

### Current Behavior

闪退

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/73635883/184548740-6ddc2356-8057-4026-8889-a3fee10f642f.png)
![image](https://user-images.githubusercontent.com/73635883/184548744-4713b80e-0ebb-4d15-b49e-fa303a472d1e.png)
![image](https://user-images.githubusercontent.com/73635883/184548747-57019d0a-9c0b-422d-9f5f-4e9458afbcca.png)
点击开始录制,然后暂停,闪退

**Comment by RytoEX** [comment] 2022-08-16 00:43
If I'm understand correctly, the issue is:
> 1. Start Recording.
> 2. Pause Recording.
> 3. OBS crashes.

If that's the case, then this is most likely fixed by #7040.

**Closed by RytoEX** 2022-08-16 00:43 UTC
