### ISSUE TITLE
plugin failed to load

### ISSUE THREAD

**Issue by kumar007git** [obsproject/obs-studio#7489] opened 2022-09-28 18:40 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

-

### Expected Behavior

OBS studio application starts without any errors

### Current Behavior

OBS studio starts and gives an error message:

The following OBS plugins failed to load:
decklink-output-ui

Please update or remove these plugins.

### Steps to Reproduce

1. Start OBS studio application

### Anything else we should know?

How can I fix this issue either by updating the plugin or removing it?

**Comment by tytan652** [comment] 2022-09-28 18:42
Please provide a log.

**Comment by PatTheMav** [comment] 2022-10-04 19:48
Last call to provide a log.

**Comment by PatTheMav** [comment] 2022-10-10 00:38
Closing this as no log file was provided. It can be reopened if the missing information to analyse/debug the issue is added.

**Closed by PatTheMav** 2022-10-10 00:38 UTC

**Comment by publicmessages** [comment] 2022-10-20 21:36
here is a log file from obs portable (packaged by portable apps) https://obsproject.com/logs/pIFqYBd-sY29vXtj

**Comment by Fenrirthviti** [comment] 2022-10-20 21:44
What do you mean "packaged by portable apps"? It looks like whatever package you're using is shipping incorrect plugin versions. Can you provide a link to what the package you're using is?

**Comment by publicmessages** [comment] 2022-10-20 21:46
yes, sir. the package is from https://portableapps.com/apps/music_video/obs-studio-portable because I don't have admin on this machine.

**Comment by RytoEX** [comment] 2022-10-20 21:46
> here is a log file from obs portable (packaged by portable apps) https://obsproject.com/logs/pIFqYBd-sY29vXtj
> 
> analyzer says plugin is outdated https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FpIFqYBd-sY29vXtj
> 
> it isn't a blocker or critical error. obs works just fine but on startup it shows this annoying message
> 
> ![image](https://user-images.githubusercontent.com/29666942/197064398-eb52862d-632f-48f6-81e4-85cb14aa042f.png)
> 
> thing is I don't use any fancy decklink and I just want to suppress this message.

We do not maintain the package provided by PortableApps. They likely just did not remove the outdated file "decklink-ouput-ui.dll" and "decklink-ouput-ui.pdb" which were replaced with "decklink-output-ui.dll" and "decklink-output-ui.pdb". Report this to them.

**Comment by publicmessages** [comment] 2022-10-20 21:50
> We do not maintain the package provided by PortableApps.

yes, makes sense because I don't see this problem on either fedora or windows with scoop installer. I was just trying to help by providing a log file :)

**Comment by Fenrirthviti** [comment] 2022-11-22 20:27
> reason: when upgrading the portableapps version of OBS, it does NOT overwrite the OLD decklink-output-ui plugin

As a note, we don't manage or maintain anything on portableapps. Our updater handles this update specifically, so using any other kind of updater or plugin manager is not supported by us. Please report it to them.

**Comment by issltd** [comment] 2024-07-26 18:12
This same issue cropped up when upgrading from OBS 2.x to OBS 3. I would have NEVER figured it out.  The error message was that the plugin decklink-ouput-in - NOT deckilnk-output-in.  My brain autocorrected what I saw to output with the 't'.  I moved the 2 files named without the t and now all is well again - allowing me to troubleshoot  upload errors to restream.
