### ISSUE TITLE
OBS Crash on Startup

### ISSUE THREAD

**Issue by dinodigital** [obsproject/obs-studio#7750] opened 2022-11-10 08:08 UTC
### Operating System Info

macOS 13

### Other OS

MacOS Ventura 13.0.1

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://pastebin.com/hxPM2rNj

### OBS Studio Crash Log URL

https://pastebin.com/hxPM2rNj

### Expected Behavior

Not to Crash

### Current Behavior

Crashes when i launch OBS

### Steps to Reproduce

1. Open application
2. Crash
3.
...

**Comment by B-1P** [comment] 2022-11-13 00:42
Same issue here. Console logs show it getting up to loading OpenGl and that's about it.

Tried versions 28.03 through 28.1.2, all have the same behaviour. 

`$ cat 2022-11-12\ 16-38-23.txt 
16:38:23.107: [macOS] Permission for audio device access granted.
16:38:23.113: [macOS] Permission for video device access granted.
16:38:23.120: [macOS] Permission for accessibility granted.
16:38:23.126: [macOS] Permission for screen capture granted.
16:38:24.526: Rosetta translation used: false
16:38:24.527: CPU Name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
16:38:24.527: CPU Speed: 2300MHz
16:38:24.527: Physical Cores: 8, Logical Cores: 16
16:38:24.527: Physical Memory: 16384MB Total
16:38:24.527: OS Name: macOS
16:38:24.529: OS Version: Version 13.0.1 (Build 22A400)
16:38:24.529: Kernel Version: 22.1.0
16:38:24.530: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
16:38:24.531: Current Date/Time: 2022-11-12, 16:38:24
16:38:24.531: Browser Hardware Acceleration: true
16:38:24.531: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
16:38:24.531: Portable mode: false
16:38:24.584: OBS 28.0.3 (mac)
16:38:24.584: ---------------------------------
16:38:24.586: ---------------------------------
16:38:24.586: audio settings reset:
16:38:24.586: 	samples per sec: 48000
16:38:24.586: 	speakers:        2
16:38:24.586: 	max buffering:   960 milliseconds
16:38:24.586: 	buffering type:  dynamically increasing
16:38:24.599: ---------------------------------
16:38:24.599: Initializing OpenGL...`

**Comment by lightumcc** [comment] 2022-11-14 13:16
I've the same problem, it said it was initializing opengl

**Comment by lightumcc** [comment] 2022-11-14 13:20
I've found that this crash often happens after I disconnect my external monitor and can be reproduced by doing the following:
When connecting an external monitor
Move OBS window to external monitor
Close OBS
Disconnect the external monitor
Restart OBS
No response

**Comment by lightumcc** [comment] 2022-11-14 13:21
> I've the same problem, it said it was initializing opengl

Sometimes logs show stuck in ffmpeg option

**Comment by B-1P** [comment] 2022-11-16 07:46
So I was using an external monitor with the screen closed. The external monitor was connected by a display link dock that used display link manager extension to share the screen. I suspect that this extension is the problem because I got it working by disconnecting the external display and killing the display link manger. Starting OBS on the builtin display and doing the initial setup. Once the initial setup was finished, I was able to go back to my external display and continue using OBS (even after restarts). It appears that during first init, OBS tries to set up rendering and detect sources and the indirection of using an extension like display-link causes problems.

Hope this helps.

**Comment by lightumcc** [comment] 2022-11-16 11:16
> 所以我在屏幕关闭的情况下使用外接显示器。外部显示器通过显示链接扩展坞连接，该扩展坞使用显示链接管理器扩展来共享屏幕。我怀疑这个扩展是问题所在，因为我通过断开外部显示器并关闭显示链接管理器来让它工作。在内置显示器上启动 OBS 并进行初始设置。初始设置完成后，我可以返回到我的外部显示器并继续使用 OBS（即使在重启后）。似乎在第一次初始化期间，OBS 尝试设置渲染和检测源，而间接使用显示链接等扩展会导致问题。
> 
> 希望这可以帮助。

I agree with you, I added an external monitor to my video feed, but when I disconnect the external monitor it may cause OBS to crash
Although I'm not quite sure if this is the crux of the problem

**Comment by B-1P** [comment] 2022-11-16 18:10
> 
> This actually resembles an issue that we had reported to us off of GitHub a little while ago. Do you use an on-screen keyboard?

Nope

**Comment by mr-rayeen** [comment] 2022-12-04 16:31
I m using linux and facing same issue

**Comment by dinodigital** [comment] 2023-01-16 14:47
Any news? Still can't use OBS :(

**Comment by lightumcc** [comment] 2023-01-16 14:49
> Any news? Still can't use OBS :(

After I update to macOS 13.2 (22D5038i), this problem solved.
But I'm not sure wheather it will work on your mac

**Comment by RytoEX** [comment] 2023-03-08 20:31
@dinodigital Please re-test in OBS Studio 29.0.2 (or newer) on macOS 13.2 or the latest stable macOS release.

**Comment by dinodigital** [comment] 2023-03-11 15:02
> @dinodigital Please re-test in OBS Studio 29.0.2 (or newer) on macOS 13.2 or the latest stable macOS release. Please also provide a regular OBS log in addition to a crash log.

Nope. Still doesn't work. Here is crash report: https://pastebin.com/dbRDQFgA

**Comment by RytoEX** [comment] 2023-03-11 17:59
Please also provide the regular OBS log. You can find them at `~/Library/Application Support/obs-studio/logs`.

**Comment by dinodigital** [comment] 2023-03-11 19:13
> Please also provide the regular OBS log. You can find them at `~/Library/Application Support/obs-studio/logs`.

There is no folder "obs-studio" in Application Support

**Comment by RytoEX** [comment] 2023-03-11 19:25
There should definitely be one there. Please verify that you checked:
```
~/Library/Application Support/obs-studio/logs
```
or:
```
/Users/<username>/Library/Application Support/obs-studio/logs
```
and not:
```
/Library/Application Support/obs-studio/logs
```

**Comment by dinodigital** [comment] 2023-03-11 19:30
Done - https://pastebin.com/YVLpUWk9

**Comment by dinodigital** [comment] 2023-03-11 19:30
@RytoEX

**Comment by gxalpha** [comment] 2023-03-11 19:37
In your crash log I can see a DAL plugin (some sort of virtual camera), which is very likely the cause of your crashes: `/Library/CoreMediaIO/DAL/RelayCam.plugin`
I don't know what installed it or what it belongs to. Please uninstall it and try again (by moving it to the trash).

**Comment by dinodigital** [comment] 2023-03-11 20:38
> 

@gxalpha you are my hero! I've deleted this plugin and OBS worked and another software that didnt work also worked! Thank you very-very-very much

**Comment by RytoEX** [comment] 2023-03-12 02:56
Closing per above.

**Closed by RytoEX** 2023-03-12 02:56 UTC
