### ISSUE TITLE
Vulkan broken after update to OBS 26

### ISSUE THREAD

**Issue by tafice** [obsproject/obs-studio#3541] opened 2020-10-02 09:01 UTC
Vulkan broken after update to OBS 26

## Platform
Operating system and version: Windows 10 2004 (19041.508)
OBS Studio version: 26.0.0
Graphics Card:  AMD Radeon RX 470
Driver:  Radeon Software 20.8.3 / 20.9.1 / 20.9.2 (also happens on latest driver)

## Expected Behavior
Everything works likes 25.0.8.  All apps/games works.

## Current Behavior
All Vulkan based applications (Wolfenstein games using vulkan API, RPCS3 emulator) crashed or report some error after installing OBS 26
vulkaninfo.exe report: vkCreateDevice failed with ERROR_INITIALIZATION_FAILED

## Steps to Reproduce
1.Install OBS 26.0 (OBS-Studio-26.0-Full-Installer-x64.exe) 
2.Vulkan is broken
3.Reinstall OBS 25.0.8 (OBS-Studio-25.0.8-Full-Installer-x64.exe)
4.Everything works

## Additional information
OBS 25.0.8 works fine

**Comment by tielqt** [comment] 2020-10-02 09:59
Having tested this with No Man's Sky on an RX 5700 XT, I've found no issue with continued capture of games in OBS 26.0, even on a bleeding edge driver from AMD. I would far more strongly suspect issues with graphics driver installation than I would with anything in OBS itself.

Can you try using the AMD Cleanup Utility (or the Factory Install option in the Radeon installer) to remove the drivers entirely, and then reinstall them, and test after that?

**Comment by MEESTER-SUPERMAN** [comment] 2020-10-02 10:52
Can't repro any issues with Vulkan titles on my Vega 56.

Tested both; No Man's Sky and Doom 2016 (vk) and everything was working as usual on OBS 26

**Comment by frabert** [comment] 2020-10-03 11:04
I can reproduce on my RX570, driver version 20.9.2

NMS crashes after installing OBS V26, crash disappears after uninstalling OBS

**Comment by WizardCM** [comment] 2020-10-03 11:14
Updated Repro steps, potentially limited to AMD GPUs:

1. Install [Mirillis Action](https://mirillis.com/en/products/action.html)
2. Install OBS Studio 26
3. Launch a Vulkan game (definitely reported with No Mans Sky, but not the Game Pass version)

Step 1 is 100% required, and it has to be in this order. If you install OBS then Action, the issue doesn't occur.

**Comment by frabert** [comment] 2020-10-03 11:16
I don't have Mirillis Action, so not 100% necessary to repro, but I do have AMD ReLive installed.

**Comment by WizardCM** [comment] 2020-10-03 11:19
@frabert in the Registry, what other layers do you have installed? `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers`

**Comment by frabert** [comment] 2020-10-03 11:23
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers]
"C:\\Program Files\\RenderDoc\\renderdoc.json"=dword:00000000
"C:\\Program Files (x86)\\RivaTuner Statistics Server\\Vulkan\\RTSSVkLayer64.json"=dword:00000000
"D:\\Program Files (x86)\\Steam\\SteamOverlayVulkanLayer64.json"=dword:00000000
"D:\\Program Files (x86)\\Steam\\SteamFossilizeVulkanLayer64.json"=dword:00000000
```

**Comment by WizardCM** [comment] 2020-10-03 11:26
I wonder if it's anything that renders an overlay, so in your case it could be RivaTuner..

**Comment by Gol-D-Ace** [comment] 2020-10-03 13:21
Windows 10 Pro 2004 x64
NVIDIA GeForce GTX 1060 6 GB with driver version 456.55
MSI Afterburner 4.6.2 Beta 3 with RivaTuner Statistics Server 7.2.3
Game: Ashes of the Singularity: Escalation running in Vulkan mode
OBS Studio Version 26.0.0

Initial scenario just having everything installed like you would normally do. Neither OBS nor MSI Afterburner / RivaTuner are started.
Starting the game results in an instant crash and the crash reporter shows up.

Scenario 2
Uninstalling OBS Studio (removing the Vulkan layer) and then trying to start the game makes the crash go away and the game starts normally.
Reinstalling OBS Studio will cause no crashing until the PC gets restarted. (Probably the layer isn't loaded until then.)

Scenario 3
Removing the RivaTuner Vulkan layer in the registry stops crashing as well instantly.
Adding the layer again will cause no crashing even after a PC restart.

Scenario 4
Uninstalling OBS Studio (removing the layer) after the RivaTuner Vulkan layer got added again (Scenario 3) and installing it again (adding the layer) and then restarting the PC results in the game crashing once again.

Conclusion: It seems like OBS Studio and RivaTuner need to be installed in my case to cause the crashing with the game. It's also important in which order the layers/programs got installed. If the RivaTuner Vulkan layer gets installed/added after OBS Studio got installed everything seems to be fine.

**Comment by Gol-D-Ace** [comment] 2020-10-03 21:51
Fix is in the testing https://github.com/obsproject/obs-studio/suites/1284638403/artifacts/19944980 (https://github.com/obsproject/obs-studio/pull/3549)
If you want to try it make sure to delete the files in C:\ProgramData\obs-studio-hook
before starting obs64.exe from bin\64bit

Also please restart your computer once after starting this OBS build and then make sure to start this build again.

Test if you can capture your game and if the crashing stopped.

**Closed** 2020-10-04 05:41 UTC
Labels: Confirmed, Regression, Windows
