### ISSUE TITLE
Matte stinger transition blinks to 'from' scene

### ISSUE THREAD

**Issue by ColdFire21** [obsproject/obs-studio#4564] opened 2021-04-20 17:15 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/C4AggB5lluA_Lw19

### Expected Behavior

When the matte stinger transition ends it should only display the second scene. 

### Current Behavior

When the transition ends the first scene (the one that i came from) blinks and is shown for less then a second and then my new scene is displayed

https://user-images.githubusercontent.com/4633446/115887549-537e6d00-a452-11eb-9f6a-5627f2c4c3b3.mp4

### Steps to Reproduce

1. display a first scene
2.switch scene
3. wait for transition to end
...

### Anything else we should know?

This behavior doesn't happen all the time, it's quite random

**Comment by WizardCM** [comment] 2021-05-13 23:57
As you are using a separate file for the matte, I believe this is potentially expected behaviour. Does the issue also occur if you combine the matte into the original video (either side by side or stacked)?

**Comment by WizardCM** [comment] 2021-05-14 09:14
Additionally, please provide example stinger/matte files to test with.

**Comment by ColdFire21** [comment] 2021-05-14 09:38
I'm using a separate file, and this behavior is quite random even when i'm the exact same transition between the same scenes. (i'll try ti test it with a combined file)

you'll find attached the files i use

[fire-swipe-track-matte.zip](https://github.com/obsproject/obs-studio/files/6477959/fire-swipe-track-matte.zip)

**Comment by WizardCM** [comment] 2021-05-14 10:31
I cannot reproduce the issue with the files provided. Tested 20 times switching between two scenes.

**Comment by DaveKap** [comment] 2021-05-15 00:33
I'm also seeing this issue with the latest OBS beta. I'm using "Same file, side-by-side" for the track matte option (although I'm just using a basic matte) and as soon as the stinger is done playing using the transition preview, it shows scene A for one frame and then jumps to scene B. If I add a fade effect, I can actually see that the transition stays on scene A the entire time, despite my transition point being as early as possible.

It would appear some bug is causing transition point to be completely ignored during transition stingers. Here's a gif of what I'm seeing:
https://i.imgur.com/TXUHsPE.gifv
Note the transition point number is at 5 milliseconds and yet it still waits until the stinger is done to do the transition.

**Comment by WizardCM** [comment] 2021-05-15 00:39
@DaveKap Please provide the file you're having issues with. It looks to me like the matte is incorrectly built.

Additionally, in Track Matte mode, the Transition Point is completely ignored for the video. This is correct behaviour, it's only used for the audio.

**Comment by DaveKap** [comment] 2021-05-15 00:43
Unfortunately, in order to get the alpha exported with the video using DaVinci Resolve, I have to use a format that explodes the file size up to 200MB (According to guides found via Google, I went with the Quicktime format using the GoPro CineForm Codec with Type RGB 16-Bit.) Do you happen to have an alternative file format I should be using or do you not mind a google drive link to a 200MB video file?

**Comment by WizardCM** [comment] 2021-05-15 00:48
No, a plain black on the matte will not work. Black represents the previous scene, white represents the next scene.

**Comment by DaveKap** [comment] 2021-05-15 00:50
Ah! So inverting matte colors should fix it. I just tried that, and it seems to have worked!

**Comment by WizardCM** [comment] 2021-05-20 09:06
Additionally, apparently this can happen with FPS mismatches. So you need to make sure OBS, your stinger, and your matte all have the same FPS.

**Comment by lindenkron** [comment] 2021-05-30 05:12
I thought this was confirmed a bug (was told it was). I'm getting similar issue about 10% of the time I change transition.



https://user-images.githubusercontent.com/6466136/120092815-584fd400-c116-11eb-9f1d-505ad8c4822d.mp4

**Comment by WizardCM** [comment] 2021-05-30 05:52
> I thought this was confirmed a bug (was told it was). I'm getting similar issue about 10% of the time I change transition.

Please provide your stinger/matte file.

**Comment by BchWut** [comment] 2021-06-04 01:38
Hello, please find my issue attached. There appears to be a 'ghosting' artifact between scenes A and B when I use the side-by-side track matte stinger. I've double-checked that my video has completely black matte color on the right. Could it be an OBS issue? v27.0.0 Win10

https://user-images.githubusercontent.com/85324123/120732778-3779eb00-c529-11eb-9e90-eaad8b26503e.mp4


https://user-images.githubusercontent.com/85324123/120732811-4791ca80-c529-11eb-8859-8fd2c01f3ed9.mov

**Comment by ThePieroCV** [comment] 2021-06-07 02:32
I have the same issue. I'm also using Resolve for design and Export on Quicktime RGB 16 bits (.mov) and converted to webm via ffmpeg.

Maybe is an issue from Resolve or ffmpeg.

**Comment by BchWut** [comment] 2021-06-07 03:12
> I have the same issue. I'm also using Resolve for design and Export on Quicktime RGB 16 bits (.mov) and converted to webm via ffmpeg.
> 
> Maybe is an issue from Resolve or ffmpeg.

Check the quote in my first post, you need to change Data Levels checkbox to "Full" in the advanced render settings.

**Comment by CaptainSkiddow** [comment] 2021-06-29 17:50
Hi!
I have the same blinking issue, but i use After Effects for my renders. Does anyone know how to fix this in After Effects?

Much regards,

Rens

**Comment by treier57lol** [comment] 2021-06-29 19:08
Same issue, using Blender and ffmpeg for rendering. I don't believe that four different pieces of software are at fault for this bug, it's still an issue within OBS. The random nature of the bug as shown by @lindenkron is an indication of that, at least that is my theory.

**Comment by lindenkron** [comment] 2021-06-29 19:10
If you believe you have my glitch, please continue the conversation over at https://github.com/obsproject/obs-studio/issues/4886 @treier57lol 

Think this is a different variation of issue.

**Comment by treier57lol** [comment] 2021-06-29 19:25
Thank you! I'll look into it.

**Comment by flaeri** [comment] 2021-09-01 17:13
Pretty sure this is the same as https://github.com/obsproject/obs-studio/issues/4886, correct?
If so, its already been fixed and merged here https://github.com/obsproject/obs-studio/commit/f48795439504acdfcd985e0d43f3f49ed08d3f85. Available in the beta/rc atm.

**Comment by treier57lol** [comment] 2021-09-01 17:59
Yes, f48795439504acdfcd985e0d43f3f49ed08d3f85 should have fixed this.

**Comment by Fenrirthviti** [comment] 2021-09-01 20:48
Closing per above comments.

**Closed by Fenrirthviti** 2021-09-01 20:48 UTC

**Comment by ItZmirks** [comment] 2021-09-13 14:32
can some one help me i am having the same problem that the transition doesnt finish completely and it changes to the next scene although i rendered it through after effects, moreover i checked and my stream matte and transition are all 60 fps. some1 pls help
