### ISSUE TITLE
virtual Camera doesn't start

### ISSUE THREAD

**Issue by baermathias** [obsproject/obs-studio#4547] opened 2021-04-17 11:58 UTC
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/qtFrkBltWUt3SHOV

### Expected Behavior

Start virtual camera

### Current Behavior

The button "Start Virtual Camera" was there after initial installation, but clicking it did nothing and gave an error: 
```
sh: 1: pkexec: not found
```
But its there: `which pkexec` --> `/usr/bin/pkexec`

Then I found another way:
```
sudo apt-get install v4l2loopback-dkms
sudo modprobe v4l2loopback
```
After this change the button switched to "Stop Virtual Camera", when clicking it.
But still I can't see it in no other app like Signal or Teams.
![Screenshot from 2021-04-17 13-51-21](https://user-images.githubusercontent.com/45003352/115112294-27ac4480-9f85-11eb-9512-e965848de4d3.png)

### Steps to Reproduce

1. Install OBS Studio
2. Start it
3. Click Start Virtual Camera

**Comment by RytoEX** [comment] 2021-04-17 12:12
This appears to be the Snap version of OBS Studio installed from the Ubuntu Software Center, which we do not support.  This appears to be a duplicate of #4256, so I'm closing this.

**Closed by RytoEX** 2021-04-17 12:12 UTC

**Comment by baermathias** [comment] 2021-04-17 17:49
I have just uninstalled the snap version and installed obs via ppa, the Virtual Camera is still not shown on Signal or Teams.
https://obsproject.com/logs/J29yaYXtgQTLXx0e
