### ISSUE TITLE
OBS Studio doesn't detect the NVIDIA drivers in Linux Mint 20

### ISSUE THREAD

**Issue by jcmartinez** [obsproject/obs-studio#3893] opened 2020-12-15 11:52 UTC
In Linux Mint 20 with system and drivers up to date, OBS Studio fails to open NVENC codec with error message:

> Failed to open NVENC codec: Unknown error occured
> Please check your video drivers are up to date

## Platform
OBS Studio wa installed as follows:
```
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install obs-studio
```

Operating system and version:
```
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```
OBS Studio version: 26.1.0 (64bit)

## Expected and Current Behavior
In Linux Mint 20, there are 3 ways of running your system's graphics when you have a dedicated GPU:

1. NVIDIA (Performance mode)
2. NVIDIA on-demand
3. Intel (Power saving mode)

1 - I would expect that when running on NVIDIA (Performance mode). OBS Studio would recognize the NVIDIA drivers. However; it opens, but when you try to start a recording it shows the error message:

> Failed to open NVENC codec: Unknown error occured
> Please check your video drivers are up to date

Log file of this case: https://obsproject.com/logs/lKTE8zTLtvMCf-VA

2 - I would expect that when the system is running as NVIDIA on-demand, I should be able to launch OBS Studio by right click the OBS icon and selecting "Run with NVIDIA GPU". However; when I do so, the program doesn't open at all and no error is shown.
Log fie of this case: https://obsproject.com/logs/sIFyAYsR0KB9AYoI

3 -  Finally, when your system is running as Intel (Power saving mode), OBS studio opens but, as expected, NVIDIA isn't available here and OBS Studio runs only if configured to use Software (x264). Which is ok.

## Steps to Reproduce

**CASE: NVIDIA on-demand**
1. Start your system with NVIDIA on-demand
2. Run OBS Studio
3. Click Settings > Output: Streaming Encoder = NVENC | Rcording Encoder = NVENC
4. Click Start Recording. You get the error message quoted above.

**CASE: NVIDIA (Performance mode)**
1. Start your system with NVIDIA (Performance mode)
2. Click Mint's Menu (Start) button > Sound & Video > Right click on OBS Sudio > Click Run with NVIDIA GPU.
3. The program never starts. No error is show.

**Comment by WizardCM** [comment] 2020-12-15 11:55
Which NVIDIA driver do you have installed? I personally recommend the one from their site, rather than from any of the package managers.

**Comment by jcmartinez** [comment] 2020-12-15 14:00
@WizardCM  - Yes, I tried the driver from NVIDIA's website yesterday, but I reverted back to the version from the repository because it made no difference and I thought that it wuld be easier to debug using what comes by default, which what most people would have in their systems.

**Comment by Gol-D-Ace** [comment] 2020-12-15 14:06
OBS did definitely not run on the nvidia gpu in your log and therefore NVENC wasn't available.

`12:54:48 PM.472: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)`

**Comment by jcmartinez** [comment] 2020-12-15 14:18
@Gol-D-Ace - I see that. How do I tell OBS to go for the NVIDIA GPU? Is there a configuration that I'm missing?

**Comment by Gol-D-Ace** [comment] 2020-12-15 14:22
Have you tried using prime?
sudo prime-select nvidia

**Comment by jcmartinez** [comment] 2020-12-23 16:44
@Gol-D-Ace - Thank you for the suggestion. My understanding is that `sudo prime-select nvidia` is the comand line equivalent to using th GUI to select NVIDIA on-demand.

So, basically, this wuld be the **CASE: NVIDIA (Performance mode)** that I described above.

See the first option on this screenshot:

![image](https://user-images.githubusercontent.com/746915/103018993-5de13680-4546-11eb-96a1-1ac3887ef468.png)

**Comment by Gol-D-Ace** [comment] 2020-12-23 16:45
From my understanding yes this should be equal.

**Comment by chepecarlos** [comment] 2021-01-05 19:20
i have similar problems on my linux mint and nvidia 1650 super

**Comment by ltmartin** [comment] 2021-05-16 18:43
I have the same problem on Linux Mint with an NVIDIA GeForce MX330

**Comment by mehulgera** [comment] 2021-06-06 06:57
I am using Linux Mint 20.1 and the problem is still there. I have NVIDIA GeForce 940MX.

**Comment by JhonCordoba** [comment] 2022-05-04 04:18
is there a solution to this problem? i have the same problem.

**Comment by thelabcat** [comment] 2022-05-25 23:59
I am experiencing a similar startup error with the Flathub version after updating my 510 drivers. However, the snap version of OBS works fine.

**Comment by dewitters** [comment] 2022-06-09 07:54
I have the same problem, but was able to solve it by installing OBS through flatpak: https://flathub.org/apps/details/com.obsproject.Studio

**Comment by thelabcat** [comment] 2022-06-09 18:23
After the update to the 515 drivers on the system drivers gui utility thing and flatpak, the problem no longer exists.

**Comment by jcmartinez** [comment] 2022-06-09 20:04
An installation using Flatpack can be quite large.

I continue to see the problem using the other installation suggested on the documentation i.e. ppa:obsproject/obs-studio

**Comment by kkartaltepe** [comment] 2022-10-14 04:53
Closing as many users do not understand nvidia's choice to make driver updates break their running system. Please use our support channels for questions about nvidia failing to load.

**Closed by kkartaltepe** 2022-10-14 04:53 UTC
Labels: Linux
