### ISSUE TITLE
Crash when closing OBS, must kill process in Task Manager

### ISSUE THREAD

**Issue by poolfloat** [obsproject/obs-studio#7719] opened 2022-11-04 22:42 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/ylV-4fgUEjYYZzBx

### OBS Studio Crash Log URL

https://obsproject.com/logs/56gKbH3noFx7SCl9

### Expected Behavior

When clicking X to exit OBS, it should close.

### Current Behavior

Clicking X to exit OBS, it crashes and pops up an error telling me it has crashed. The Yes/No prompts to save a log to the clipboard are non-responsive, I have to use Task Manager to close OBS and clear that popup.

This did not occur until updating from 2.8.0.3 to 2.8.1.1. I run OBS in portable mode, and this has never been a problem before.

### Steps to Reproduce

1. Open OBS
2. Try to close OBS
3. It Crashes
...

### Anything else we should know?

The only plugin I use with OBS is for my Stream Deck.

**Comment by gxalpha** [comment] 2022-11-04 22:43
> The only plugin I use with OBS is for my Stream Deck.

Please try again without that plug-in

**Comment by poolfloat** [comment] 2022-11-04 22:52
Removed the DLLs for Stream Deck, and it still crashes in the same manner.

**Comment by poolfloat** [comment] 2022-11-04 22:54
Also, just restored my copy of 2.8.0.3 that I zipped prior to update, no crashes.

**Comment by Colink02** [comment] 2022-11-05 00:04
I just updated and had the same issue, has something to do with obs-browser.dll as the log says.I deleted it (not recommended) and that cleared up the issue but obviously not ideal. Also I'm on Windows 10 and have it fully installed.

**Comment by gxalpha** [comment] 2022-11-05 00:07
I believe this is the crash fixed in obsproject/obs-browser@2a35b7d. We're working on getting a hotfix out that includes this fix.

**Comment by Colink02** [comment] 2022-11-05 00:11
Ok, cool Thank You! :D

**Comment by WizardCM** [comment] 2022-11-05 00:15
Duplicate of #7707

**Closed by WizardCM** 2022-11-05 00:15 UTC
