### ISSUE TITLE
[DONT CLOSE - MUST BE A BUG] OBS freeze while playing Battlefield 2024 / Elden Ring

### ISSUE THREAD

**Issue by omexlu** [obsproject/obs-studio#6147] opened 2022-03-15 10:56 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/KXWAEMPKFjBEgkAR

### OBS Studio Crash Log URL

https://obsproject.com/logs/Gn-E6ljBxiWyzJGY

### Expected Behavior

- Dont freeze

### Current Behavior

Hello,

OBS freezes while streaming and need to forced to close:
https://obsproject.com/logs/KXWAEMPKFjBEgkAR
https://obsproject.com/logs/Gn-E6ljBxiWyzJGY

This problem occurs with the game battlefield 2024

### Steps to Reproduce

Cant need help!

**Comment by derrod** [comment] 2022-03-15 11:08
Duplicate of #6147

**Closed by derrod** 2022-03-15 11:08 UTC
Labels: Duplicate

**Comment by omexlu** [comment] 2022-03-15 11:10
Yes... and its still somewhere a bug? Its even known? Other games work great and before the last updates it worked to.

**Comment by norihiro** [comment] 2022-03-15 11:47
Does the crash happen if removing 3rd parties' plugins?
I think these DLLs are not from OBS; `StreamDeckPlugin1.dll`, `StreamDeckPlugin.dll`, `logi_obs_plugin_x64.dll`.

**Comment by omexlu** [comment] 2022-03-15 11:59
> Does the crash happen if removing 3rd parties' plugins? I think these DLLs are not from OBS; `StreamDeckPlugin1.dll`, `StreamDeckPlugin.dll`, `logi_obs_plugin_x64.dll`.

StreamDeck* are from StreamDeck and other from Logitech, the weird thing is that all other games works finem just battlefield 2024 and elder ring not.

It not really crashs but the preview freeze and the stream stops transmitting.

**Comment by feetstv** [comment] 2022-03-15 13:12
If you need help and support, you should visit the OBS forums and/or the official OBS community support Discord server.
