### ISSUE TITLE
Scrolling, drop downmenu's and colour pickers among other things don't show in an OBS browser source.

### ISSUE THREAD

**Issue by xNightWulf69** [obsproject/obs-studio#7755] opened 2022-11-10 23:04 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/HVBpFbgWPWv0ndKH

### Expected Behavior

When opening a webpage on an OBS browser source, be able to scroll the page.
When you click on a dropdown menu, the menu to open.
When clicking on a colour picker, the colour picker to open.

### Current Behavior

Can't scroll
dropdown menu's don't open
Colour picker doesn't open.

### Steps to Reproduce

1. Add a browser source which you should be able scroll on, or has dropdown menu's or colour pickers.
2. Try scrolling or opening the dropdown menu/colour picker.
3.
...

**Comment by gxalpha** [comment] 2022-11-10 23:12
Are you using the *Interact* menu when clicking on the browser source?

**Comment by xNightWulf69** [comment] 2022-11-10 23:16
Yes, the dropdown menus still work, but you can't see them.

**Comment by WizardCM** [comment] 2022-11-10 23:18
To enable scrolling, clear out the contents of the Custom CSS box.

For dropdowns and colour pickers, this is a duplicate of https://github.com/obsproject/obs-browser/issues/148

**Closed by WizardCM** 2022-11-10 23:18 UTC
