### ISSUE TITLE
swiching 1 and 2 scenes fast fade duration cuts not showing slowly

### ISSUE THREAD

**Issue by Dilzze** [obsproject/obs-studio#5579] opened 2021-11-25 23:24 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

Im not at ome right now

### Expected Behavior

swiching  scenes fast to 1 and 2 .  fade transition need to load slowly not cut

### Current Behavior

swiching 1 and 2 scenes fast fade duration cuts not showing slowly (just skips fade efect.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

It was a lot of bugs (scenes, sorces. groups.
1 .if you try to copy all scenes, ant paste to ne source all camera donation goal on sceen is set diferent. it supposed to paste the same as i copy..
2. 10 time obs crashed then i try creating new scenes and deleted them at once (group)
3.  if you lock group folder. files not locked. (camera, text) and somethink is not right then you unlock ant try to change position on screen. (camera, text)

**Comment by Fenrirthviti** [comment] 2022-04-30 21:20
Duplicate of #5291

**Closed by Fenrirthviti** 2022-04-30 21:20 UTC
