### ISSUE TITLE
OBS 26.0 Crashes - crashlog attached

### ISSUE THREAD

**Issue by lcalder** [obsproject/obs-studio#3412] opened 2020-09-05 08:41 UTC
## Platform

Operating system and version: Windows 10 64-bit
OBS Studio version:
16:32:47.092: CPU Name: AMD Ryzen Threadripper 3970X 32-Core Processor 
16:32:47.092: CPU Speed: 3700MHz
16:32:47.092: Physical Cores: 32, Logical Cores: 64
16:32:47.092: Physical Memory: 65429MB Total, 53656MB Free
16:32:47.092: Windows Version: 10.0 Build 19041 (release: 2004; revision: 450; 64-bit)
16:32:47.092: Running as administrator: false
16:32:47.092: Aero is Enabled (Aero is always on for windows 8 and above)
16:32:47.092: Windows 10 Gaming Features:
16:32:47.092: 	Game DVR: On
16:32:47.094: Sec. Software Status:
16:32:47.095: 	Microsoft Defender Antivirus: enabled (AV)
16:32:47.095: 	Windows Firewall: enabled (FW)
16:32:47.096: Current Date/Time: 2020-09-04, 16:32:47
16:32:47.096: Browser Hardware Acceleration: true
16:32:47.096: Portable mode: false
16:32:47.776: OBS 26.0.0-rc1 (64-bit, windows)
16:32:47.777: ---------------------------------

## Expected Behavior
 I should be able to record and use replay buffer as I was able to do normally with obs 25.0.8.
## Current Behavior

I was able to stream and I tried using the new virtual cam for zoom instead of the OBS-virtual cam plugin, and was also testing out a the Replay Source by exeldro plugin, and I tried to record and/or enable the replay buffer and sometimes it would complain that it failed and told me to check for latest Nvidia Drivers (which I have). then I would muck about some and sometimes I could get it to record or start the obs replay buffer, but generally it would seem to crash unexpectedly some time after that, but not necessarily immediately.

[Crash 2020-09-04 16-30-57.txt](https://github.com/obsproject/obs-studio/files/5177783/Crash.2020-09-04.16-30-57.txt)
[Crash 2020-09-05 01-29-25.txt](https://github.com/obsproject/obs-studio/files/5177784/Crash.2020-09-05.01-29-25.txt)
[Crash 2020-09-04 15-32-25.txt](https://github.com/obsproject/obs-studio/files/5177785/Crash.2020-09-04.15-32-25.txt)
[2020-09-04 16-38-50.txt](https://github.com/obsproject/obs-studio/files/5177787/2020-09-04.16-38-50.txt)
[2020-09-05 01-29-47.txt](https://github.com/obsproject/obs-studio/files/5177788/2020-09-05.01-29-47.txt)
[2020-09-04 16-32-47.txt](https://github.com/obsproject/obs-studio/files/5177789/2020-09-04.16-32-47.txt)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by RytoEX** [comment] 2020-09-05 08:57
I'm going to close this because this appears in part to be a duplicate of #3372 and it appears the crashes are related to third party plugins.  Please file issues with those plugins.  If you feel that this is in error, please reopen the issue with an explanation as to why it should be reopened, and please update and clarify the initial post.

In the future, please simply put your Operating System information and OBS version the "Platform" section of the issue template and please properly fill out the steps to reproduce.  The "Current Behavior" section as you have filled it out would not have easily allowed us to investigate or attempt to reproduce the issue.

**Closed by RytoEX** 2020-09-05 08:57 UTC
