### ISSUE TITLE
[Linux] Big latency when monitoring auxiliary audio device

### ISSUE THREAD

**Issue by maxdrfr** [obsproject/obs-studio#3525] opened 2020-09-30 09:39 UTC
## Platform

Operating system and version: Linux Ubuntu 20.04
OBS Studio version: tested on 26.0 and 25.0.8

## Expected Behavior

Turning ON monitoring and output and listen no latency.

## Current Behavior

When I turn monitor and output ON in Advanced Audio Properties, the latency is approximately OK at the begining but after 5 minutes, the monitor gives some big latency.
Tested on standard pulseaudio and RT pulseaudio.
If I listen to pulseaudio line-in or mic loopback, theres no latency, never.
No warns or errors in OBS log or system logs.

## Steps to Reproduce

1. In audio mixer, right click on your audio input source and choose Advanced Audio Properties.
2. Select Monitor and Output in Audio Montioring.
3. Wait 5 minutes, sound loopback takes increasing latency permanently.

## Additional information

That's an long time observed issue.
Was present in OBS 19, 22, 23, 24, 25.0.x and latest 26.

**Comment by maxdrash** [comment] 2020-09-30 09:43
To listen pulseaudio loopback on default line-in or mic:
pactl load-module module-loopback latency_msec=1

**Comment by kkartaltepe** [comment] 2020-10-01 01:00
Provide a log, it sounds like you probably have buffer underruns due to attempting to get low latency out of pulseaudio. These might be caught by OBS resulting in us increasing our buffer thinking your device/configuration is correctly outputting data and if we wait we might actually see that lost audio.

Provide logs from pulseaudio running in verbose logging mode. Something like `journalctl --since "1 day ago" --user-unit   pulseaudio` covering the timespan you are running the test with obs.

**Comment by maxdrash** [comment] 2020-10-01 12:39
There is the log:
https://pastebin.com/raw/dEEH6A1q

In pulseaudio log I have just this (when I start listening to pulseaudio loopback input):
oct. 01 14:04:48 PC-M pulseaudio[1235]: Configured latency of 1,00 ms is smaller than minimum latency, using minimum instead
oct. 01 14:04:48 PC-M pulseaudio[1235]: Cannot set requested sink latency of 2,25 ms, adjusting to 2,50 ms
oct. 01 14:04:48 PC-M pulseaudio[1235]: Cannot set requested source latency of 2,25 ms, adjusting to 2,50 ms

I have no latency on listening to pulseaudio loopback.

But I can hear clearly a big difference in monitoring between pulseaudio loopback and OBS loopback.
Aprox 400 ~ 600 ms after 5 minutes and increasing.

**Comment by kkartaltepe** [comment] 2020-10-01 16:11
Please provide the log, not some section you think might be relevant.

**Comment by maxdrash** [comment] 2020-10-01 16:12
There is the full log .......

**Comment by kkartaltepe** [comment] 2020-10-01 16:14
Then you did not run pulseaudio with verbose logging. At least in OBS there is no issues with latency, its outputing the audio with at most 42ms of latency and never added any more.

**Comment by kkartaltepe** [comment] 2020-10-01 16:26
It may also be possible the reverse is happening, your buffers are so low that PA is growing its buffer since OBS is not able to feed it in the 1ms you have configured. But without a usable PA log its hard to say.

**Comment by maxdrash** [comment] 2020-10-01 16:50
There is the log of pulseaudio in debug mode.
https://pastebin.com/raw/7k3aus4Z

You are right, pulseaudio adds latency on sink device for OBS.
What are your recommendations?

**Comment by kkartaltepe** [comment] 2020-10-01 16:57
use a reasonable buffer size for non-realtime applications. 20ms should be plenty for OBS to keep up.

**Comment by kkartaltepe** [comment] 2020-10-01 17:00
Its also possible we dont handle resizing our buffer when notified of increases on the other side. Im not sure precisely how that code works.

**Comment by maxdrash** [comment] 2020-10-01 17:35
I set in daemon.conf:
default-fragments = 2
default-fragment-size-msec = 5

but these parameters are ignored if udev module is not setted to tsched=0

I modified in default.pa
load-module module-udev-detect tsched=0

Better result and no changes are made on latency now.
I stay observating and I will close this ticket if all goes well.

Thank for your help.

**Comment by kkartaltepe** [comment] 2020-10-03 16:17
just a small update but OBS appears to handling the underruns and is extending the latency of the PA buffer. Normally this is the right behavior but its still underrunning even with an enormous buffer. Im not a PA wizard but I assume this is because samples are lost from the monitored device which was configured with a tiny buffer that isnt growing as OBS tries to increase latency.

**Comment by maxdrash** [comment] 2020-10-03 19:24
But with my fixed size of 10 msec and forcing PA to stay at a fixed latency range, I haven't latency anymore (just a little little, that is acceptable at the end of the chain for a software treatment and stills sync with video).
Do you think I can close this issue or do you want to continue investigations ?

**Comment by kkartaltepe** [comment] 2020-10-03 19:54
im fine with leaving it open its probably possible to push the latency on the device being read up when not using PA. Maybe we can add a reasonable max latency as well. I dont think ill investigate much more personally, but maybe someone else will.

**Comment by maxdrash** [comment] 2020-10-03 19:58
If someone needs to comment they can.
And I invite devs to pull a request to improve this project.
I close this ticket.

**Comment by knarrff** [comment] 2020-11-17 19:26
> Its also possible we dont handle resizing our buffer when notified of increases on the other side (which might be why it continues to grow past a reasonable size). Im not sure precisely how that code works.

I found this thread because I have a similar (the same?) problem. I use a null-device to create something for OBS to shove into. Right after creating the device, latency is there, but small. After some time (a few minutes at most), it is a few seconds. Monitoring the latency in the output of "pactl list sinks" shows the "configured latency" increasing in steps up to 2 seconds. However, this is not the whole story.

Suspending/unsuspending the null-device gets rid of the built-up latency in pulseaudio, but there is still latency left. The only way I found so far is to close and re-open OBSstudio. It looks to me like OBS is doing some internal buffering as well, which is increasing, too. Your comment makes me think it might actually adapt to pulseaudio increasing, but does not recognize that is might also decrease.

The other question apart from OBS going back to less latency would be why this is building up in the first place. What would be a good way to debug that?

Finally: should we reopen this issue or open a new one? OBSstudio should, after all, work with the default configuration of major distributions, or at least recognize this being a problem and possibly display a warning.

**Comment by maxdrash** [comment] 2020-11-17 19:32
And after hours of production, I still have the issue, the latency increases after 20 ~ 30 mins on some OBS sessions and not for others ones.
I have to disable monitoring and re-enable again (don't need to close the software) to get a new source for pulse and get no latency again.

**Comment by knarrff** [comment] 2020-11-18 09:18
@maxdrash : what exactly do you mean by "disable monitoring"? I could set the "monitoring device" to "default", but not sure what device that would then be. Or is there another setting to disable monitoring entirely? (I usually set it to the null-device I manually created)

**Comment by maxdrash** [comment] 2020-11-18 12:11
Like I said at the beginning of this issue -> Right click on sources sounds -> Advanced audio properties -> Audio monitoring: Monitor and Output, or, Monitor OFF.

**Comment by knarrff** [comment] 2020-11-18 12:47
> Like I said at the beginning of this issue -> Right click on sources sounds -> Advanced audio properties -> Audio monitoring: Monitor and Output, or, Monitor OFF.

Just tested and can confirm: this also works for me. It's not a solution, but at least I don't have to close/reopen OBSstudio now, so I can do that even while streaming. Thanks!

**Comment by TRPB** [comment] 2020-11-24 09:37
I've been struggling this for weeks and have found a workaround that at least works for me. I was getting ~8 seconds of delay by the end of a 4 hour teaching block which is really annoying. 

I've been using a Virtual speaker/null device to capture the audio and then use module remap to remap it to a microphone for use in browsers.

After trial and error I've worked out that the cause is the the Virtual Speaker. Using a real audio device solves the problem for me. I just enabled my HDMI audio output and set up OBS to monitor to that instead of a virtual speaker, then remapped that to appear as a source. So far I've not had any unreasonable delays. There is about a 0.2s latency but it's consistent and fine for my needs.

**Comment by kerloi** [comment] 2020-11-25 10:38
I’m facing the same problem (increasing monitoring delay). I’m all but an expert on PA and how sound is being played on linux.
I first noticed the progressive lag while I was streaming. After some tests I discovered that not all audio source behave in the same way. As an example I’ve added three audio input (USB webCam, wired jack mic and, phone through wifi). At the begining all audio are synced and time passing they become unsynced with huge delay for some.

- The streaming isn’t affected nor the recording only the monitoring.
- The graphical db meter stays synced all the time (every sources are synced, a clap is a good test)
- I’m using my default audio for loopback, I haven’t configured anything fancy …
- Every input uses the same monitoring channel (obviously)
I can confirm that deactivating the monitoring and re activating it suppresses the delay.

I also had this problem this morning using another laptop and capturing audio through CamLink : The stream is OK but I had delay on monitoring.

I’m using majaro linux and OBS 26.0.2-2 packed with it.

**Comment by maxdrash** [comment] 2020-12-23 14:05
On Debian 10 stable, I note 2 big problems:
1) OBS don't use 48000 Khz as setted.
2) I got 1 sec of latency after 20 minutes of playing a video with the media plugin.

```
14:33:09.852: CPU Name: Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz
14:33:09.852: CPU Speed: 1929.175MHz
14:33:09.852: Physical Cores: 4, Logical Cores: 4
14:33:09.852: Physical Memory: 11474MB Total, 9040MB Free
14:33:09.852: Kernel Version: Linux 4.19.0-13-amd64
14:33:09.852: Distribution: "Debian GNU/Linux" "10"
14:33:09.852: Session Type: x11
14:33:09.853: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
14:33:09.853: Portable mode: false
14:33:09.884: OBS 26.1.0 (linux)
14:33:09.884: ---------------------------------
14:33:09.909: ---------------------------------
14:33:09.909: audio settings reset:
14:33:09.909: 	samples per sec: 48000
14:33:09.909: 	speakers:        2
14:33:09.920: ---------------------------------
14:33:09.920: Initializing OpenGL...
14:33:09.957: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 970/PCIe/SSE2
14:33:09.957: OpenGL loaded successfully, version 3.3.0 NVIDIA 450.80.02, shading language 3.30 NVIDIA via Cg compiler
14:33:09.967: ---------------------------------
14:33:09.967: video settings reset:
14:33:09.967: 	base resolution:   1920x1080
14:33:09.967: 	output resolution: 1920x1080
14:33:09.967: 	downscale filter:  Bilinear
14:33:09.967: 	fps:               50/1
14:33:09.967: 	format:            NV12
14:33:09.967: 	YUV mode:          709/Full
14:33:09.967: NV12 texture support not available
14:33:09.968: Audio monitoring device:
14:33:09.968: 	name: Monitor of M-Audio Fast Track Stéréo numérique (IEC958)
14:33:09.968: 	id: alsa_output.usb-M-Audio_Fast_Track-00.iec958-stereo.monitor
14:33:09.968: ---------------------------------
```

```
Entrée de la destination #0
	Pilote : protocol-native.c
	Module du propriétaire : 10
	Client : 25
	Destination : 0
	Spécification de l'échantillon : s16le 2ch 44100Hz
	Plan des canaux : front-left,front-right
	Format : pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
	Bouchonné : non
	Sourdine : non
	Volume : front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	Latence du tampon : 415328 usec
	Latence de la destination : 531446 usec
	Méthode de rééchantillonnage : n/d
	Propriétés :
		application.name = "OBS"
		application.icon_name = "obs"
		media.role = "production"
		media.name = "Source média"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "32"
		application.process.id = "1412"
		application.process.user = "maxwell"
		application.process.host = "PC"
		application.process.binary = "obs"
		application.language = "fr_FR.UTF-8"
		window.x11.display = ":0"
		application.process.machine_id = "d3d6000edb8c41478db05a8512afc9dd"
		application.process.session_id = "2"
		module-stream-restore.id = "sink-input-by-media-role:production"
```

I can reproduce the issue on all PC with any kind of sound hardware and on Ubuntu 18.04, Ubuntu 20.04.
I don't know how to solve the issue myself but this is a old problem who makes very bad experience.

Otherwise, I did some comparison with other applications (like chromium, vlc) at the same time of OBS and I got 50 ms of latency in sink input playback stream of pulseaudio, this is not a hardware or pulseaudio problem because other apps don't facing this issue in same environment.

**Comment by maxdrfr** [comment] 2021-03-04 21:33
@jp9000 please, do you think a community developer can bring a solution to this issue ? A pulseaudio project member ?

**Comment by christianlupus** [comment] 2021-04-01 15:31
I think I am also affected by this bug. However, I seem to be much more affected than other users: I just stopped it and my instance generates a latency of roughly **20 seconds per minute** or 33%. This is huge.

Please note this happens not always at the same time to me. Internal media sources seem for example unaffected. The strongest effect is generated when using an RTSP stream via the VLC plugin. As [written above](https://github.com/obsproject/obs-studio/issues/3525#issuecomment-733623838) neither stream nor recording seems affected nor any other OBS functionality except for the monitoring.

What I can say additionally is that my monitoring sound is disturbed:
1. It is pitched (towards the lower frequencies), which makes sort of sense when played too slowly. 
2. The sound is interrupted as if it was transmitted only partially (reminds me of a broken MP3 file that stutters).

I am running on Archlinux and had to compile using [obs-studio-browser AUR package](https://aur.archlinux.org/packages/obs-studio-browser/) as the VLC plugin failed with a segfault. If necessary, I can recompile if this makes things easier to debug.

**Comment by EA801** [comment] 2021-04-02 18:42
Hello everyone!
I found a surprisingly simple solution that has removed both the severely increasing lag, and the incorrect pitch.
To troubleshoot this, I did a quick test stream directly on Facebook's Live Producer, and the same issue showed up when I watched the stream on my phone. This led me to the conclusion that the bug is not specific to OBS, but rather pulseaudio's handling of the capture card's audio sample rate.
In my daemon.conf, I changed default-sample-rate to 48000, leaving alternate-sample-rate commented out (it's also 48k by default). I changed a few other things, but this was the line that actually helped.
`default-sample-rate = 48000`
Let me know if this works for any of you.

**Comment by christianlupus** [comment] 2021-04-03 11:47
@EA801 I cannot confirm this workaround. The same issue still persists. I have the feeling it even got a bit worse but I am unsure.

**Comment by maxdrfr** [comment] 2021-04-03 12:27
> So I suspect it is an output problem and _not_ a capture problem.

Exactly, the input works well, it is the output to sink that causes a latency problem.
Setting it to 48000 hz doesn't solve the problem.

**Comment by codesalatdev** [comment] 2021-05-29 13:01
I wonder why this doesn't get much more attention. This issue occurs with stock configurations. It can't be right to have the monitor out of sync that much. For me, keeping the monitor output active for 5 minutes causes ~4 seconds of delay.

**Comment by maxdrfr** [comment] 2021-06-01 07:45
I see an implementation of pipewire but nothing to solve this problem. And I couldn't get pipewire to work.

**Comment by kkartaltepe** [comment] 2021-06-18 03:21
If you have this issue please give #4908 a try and see not only if it fixes this issue, but if you see any new/different issues with it over the kind of time frames the old issue occurred (10s minutes).

**Comment by maxdrfr** [comment] 2021-06-22 22:00
I tried the patch, after 40 minutes of video looping with the media source I have 1.4 seconds of lag. Sorry.

```
Entrée de la destination #4
        Pilote : protocol-native.c
        Module du propriétaire : 8
        Client : 52
        Destination : 0
        Spécification de l'échantillon : s16le 2ch 44100Hz
        Plan des canaux : front-left,front-right
        Format : pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right
\""
        Bouchonné : non
        Sourdine : non
        Volume : front-left: 19660 /  30% / -31,37 dB,   front-right: 19660 /  30% / -31,37 dB
                balance 0,00
        Latence du tampon : 665714 usec
        Latence de la destination : 772777 usec
        Méthode de rééchantillonnage : n/d
        Propriétés :
                application.name = "OBS"
                application.icon_name = "obs"
                media.role = "production"
                media.name = "Source média"
                native-protocol.peer = "UNIX socket client"
                native-protocol.version = "32"
                application.process.id = "7653"
                application.process.user = "mx"
                application.process.host = "mxpc"
                application.process.binary = "obs"
                application.language = "fr_FR.UTF-8"
                window.x11.display = ":0"
                application.process.machine_id = "71355bacad554703991077a5f85089f4"
                application.process.session_id = "2"
                module-stream-restore.id = "sink-input-by-media-role:production"
```

**Comment by kkartaltepe** [comment] 2021-06-22 23:37
Please provide feedback on the PR, and can you attach the log from OBS with the patch where you reach over 1s of latency as well as the logs from your pulseaudio.

**Comment by Creanimo** [comment] 2021-06-23 09:45
Hello everyone, first time ever writing here, so I hope I am doing it right... 😁 

I think I have the same issue, but on Windows 10:

- monitored audio sources are delayed after a while (Mic, VLC Playlist and monitored OBS Ninja browser sources).
- The lag is only on the monitoring, the stream and the recording are fine.
- Restarting the monitoring fixes it temporarily.

I see this issue is tagged Linux, but could there be a similar problem on Windows? Will this be addressed by the fix from the PR?

**Comment by arktronic** [comment] 2021-06-23 13:42
@Creanimo, there is also a related issue for macOS (#3664) and Windows (#4531).

**Comment by adnion** [comment] 2021-06-23 21:21
This is unfortunate. I tried both workarounds https://github.com/obsproject/obs-studio/issues/3525#issuecomment-732776378 and https://github.com/obsproject/obs-studio/issues/3525#issuecomment-812660547 but the latency is increasing constantly.
If there's a workaround that does not use the monitoring functionality in OBS please let me know!

I use droidcam OBS but I can't get audio input out of OBS. A 'start virtual microphone' setting in OBS would be nice.

**Comment by TRPB** [comment] 2021-06-23 23:21
As this issue is ongoing and people are asking for workarounds, I mentioned this before but on Linux at least, if you use a real device as the sink then create a virtual microphone then the latency is not there.

I set my monitor to my internal soundcard (instead of my USB headphones) and then create a virtual microphone from that:

```
pactl load-module module-remap-source source_name=Remap-Source master=alsa_output.pci-0000_08_00.3.iec958-stereo.monitor
```

For me, this works. I set my onboard soundcard as the monitor in OBS then I use the remapped microphone in teams/discord/collaborate/etc.  It also works if I set my monitor to the HDMI speaker of my monitor and turn my monitor volume down.

There is about ~150ms latency but it doesn't grow (and this is fine for my purposes). The latency is in the pulseaudio virtual speaker that is used as the monitor. As soon as a real hardware device is used it works fine, at least for me.

**Comment by maxdrfr** [comment] 2021-06-24 14:21
Whether it is the media source or a microphone input, in all cases they are monitored to pulseaudio's sink-input way from OBS.
The problem is that the sink-input buffer increases the longer a sink-input runs for an input monitored by OBS or the more media is repeated into its sink-input who stills.

For testing, I fixed the hardware latency again like my comment on Oct 2020 https://github.com/obsproject/obs-studio/issues/3525#issuecomment-702288976 :
In daemon.conf :
default-fragments = 2
default-fragment-size-msec = 10

In default.pa : 
load-module module-udev-detect
replaced by
load-module module-udev-detect tsched=0

For the hw sound card i got 10ms of latency without variation (3.6% cpu instead of 0.6, it's cpu consuming).

But, the sink-input from OBS increases about to +20ms -> + 100ms every media loop.
No change on this side.
(you can force the media restart by editing the media source en press enter to replay the media many times in a row)

And looking for obs media sink-input buffer increasing with:
pactl list sink-inputs

I'm looking for a way to flush all sink-inputs buffers from a pulseaudio command while waiting for a fix for OBS.
(By the way, this problem teaches me a lot about pulseaudio)
Do you have any ideas how to flush sink-input buffers with external command from OBS ?

**Comment by maxdrfr** [comment] 2021-06-29 11:04
For the patch #4908, I have 2 results on 2 machines.
The first machine on Debian 10 (pulseaudio 12.2) has a delay due to the buffer as usual.
On another machine on Debian 11 (pulseaudio 14.2) I don't have any delay anymore, the buffer doesn't exceed 20 to 30 ms.

I have installed pulseaudio 14.2 on Debian 10, I still have an increasing latency. The configuration is coming from the packages.
There is probably something with alsa and many other packages. I will upgrade the whole machine to Debian 11 and do a follow-up to this ticket.

**Comment by ewbteewbte** [comment] 2021-06-30 22:49
Hey there, just to say, I always had the same issue, currently on arch, all packages at latest versions. Also had it on Pop!_OS 19.10 a year ago and on 20.04 a couple of months ago. Lag did appear even if I was monitoring real devices thru OBS.

**Comment by maxdrfr** [comment] 2021-07-11 16:14
The patch #4908 is good for me, no lag for hours on Debian 10 but only for input device, no change for medias.

**Comment by ngoonee** [comment] 2021-08-03 15:42
@TRPB thanks for the workaround. The latency at least remains constant, but definitely more crackling this way. Surprisingly this didn't use to happen at all when I was using pretty much an identical setup on a laptop, but it's now giving me seconds of delay with for online classes. Have you tried #4908 and did it help you?

**Comment by TRPB** [comment] 2021-08-03 15:55
I haven't tried that as the hardware monitor workaround has worked fine for me for me since November last year. Strange that it hasn't worked for you, it must either be my hardware configuration or something the audio driver is doing to automatically adjust for it.

**Comment by MechanicallyDev** [comment] 2021-09-16 03:47
I made a python plugin as a workaround for this issue... It just disables and enables the monitoring of an specified device every X seconds. It does this quite fast, so it is barely noticeable.
Currently the plugin is set to WASAPI (windows audio API), but it is easy to replace the input prefix on the code for people using linux (I didn't knew the prefix used for linux audio drivers).

An almost proper fix would be for OBS to monitor the buildup with a watchdog, and after it hits an specified size to completely clear the buffer to get only the most recent audio.

**Closed** 2021-11-04 20:00 UTC
Labels: Linux

**Comment by HEPOSHEIKKI** [comment] 2024-05-16 06:25
> To listen pulseaudio loopback on default line-in or mic: pactl load-module module-loopback latency_msec=1

This is how I learned to not blindly copy paste commands...
