### ISSUE TITLE
upload log file

### ISSUE THREAD

**Issue by kumar007git** [obsproject/obs-studio#7488] opened 2022-09-28 18:38 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

-

### Expected Behavior

Upload current log file - Should have a confirmation message.

### Current Behavior

There is no warning or confirmation message to upload log file.

### Steps to Reproduce

1. From Help menu > Log Files > Upload Current/Last Log File

### Anything else we should know?

There is no warning or confirmation that log file will be uploaded to an external location. How can I delete log file previously uploaded? What is the retention policy of the log files? This is a flagrant issue. I did not consent to uploading and storing information from my PC to an external location. I ask again - how can I delete the log file previously uploaded by OBS studio?

**Comment by tytan652** [comment] 2022-09-28 18:45
This sounds like a feature request, not a bug report. Please use the [ideas page](https://ideas.obsproject.com/) for new feature requests.

**Comment by Fenrirthviti** [comment] 2022-09-28 20:46
While this would technically be a feature request, I want to at least address the questions in this post.

First, if you want a log file deleted, we will need the URL hash of that file to delete it from our servers, as we collect no identifiable information. Please email privacy@obsproject.com and I would be happy to process that request.

Second, we understand that the current system is not ideal, however we take great lengths to scrub any kind of personal or sensitive information from log files. We do recognize that some people might consider things like scene and source names, or file paths, to be sensitive information. If there is anything specific being logged in our logs that you feel shouldn't be logged, please do let us know so that we can look at those specific things.

Lastly, we are working towards a more transparent policy when it comes to these log files. However, and I cannot stress this enough, we take a lot of steps to ensure nothing sensitive is logged in those files, and they are uploaded entirely anonymously. It's very clear that the log files will be uploaded when selecting "Upload Log File" so I am not sure I quite agree with your claim that you didn't consent to upload the log file. Selecting this option is fairly unambiguous what it is doing.

I'm reopening this for tracking, as these are issues that we need to address going forward.

**Comment by kumar007git** [comment] 2022-09-28 21:03
Thanks for your reply. I do appreciate you guys providing this excellent app. no doubt about it. Hoping you will include a confirmation prompt before uploading anything to external servers/locations. That is what I found in nearly every case where user has to say yes/no when sending data to someplace.

**Comment by Fenrirthviti** [comment] 2022-10-13 19:03
Also as a note, this is effectively a duplicate of #3434 (which I see you commented on already) so I'm going to close this one in favor of only having one open issue for tracking this.

**Comment by Fenrirthviti** [comment] 2022-10-13 19:04
Duplicate of #3434

**Closed by Fenrirthviti** 2022-10-13 19:04 UTC
