### ISSUE TITLE
[BUG][v4l2-linux] Pan/Tilt sliders unusuable with Logitech PTZ Pro 2

### ISSUE THREAD

**Issue by forteller** [obsproject/obs-studio#2621] opened 2020-04-02 20:12 UTC
## Platform
Operating system and version: Ubuntu 19.10
OBS Studio version: 25.0.3. Installed trough OBS project PPA.

## Expected Behavior
Drag the pan and tilt sliders to pan and tilt according to how you drag them.

## Current Behavior
- Tilt does not work at all
- When dragging the pan slider some times it pans, some times it does not. Some times it pans a lot, some times a little. Some times it pans in the direction you drag the slider, some times in the opposite direction.

Log: https://obsproject.com/logs/Gr9bMvD7D2LMtCfj
 
## Steps to Reproduce
1. Add the Logitech PTZ Pro 2 as a source and double click it to open the settings
2. Drag the pan and tilt sliders

## Additional information
Thank you!

**Comment by kkartaltepe** [comment] 2020-04-02 22:34
Replicated.

Almost all sliders are useless since the sliders cause the device to reinitialize. The implementation of the plugin needs to be fixed.

**Comment by ioangogo** [comment] 2020-05-23 15:56
I think i may have a a fix for this that i have been working on selectively restarting the stream. it was being caused by an old assumption that the camera stream should be restarted on every property change. So it was restarting the stream every time

**Comment by kkartaltepe** [comment] 2020-09-09 04:37
was resolved in  #2978

**Closed** 2020-09-09 04:37 UTC
Labels: Linux
