### ISSUE TITLE
OBS does not honor GPU preference for rendering; Instability with eGPUS; No GPU selection provided (macOS)

### ISSUE THREAD

**Issue by MisutaaAsriel** [obsproject/obs-studio#6077] opened 2022-03-04 01:17 UTC
## Operating System Info

macOS 12.0

## OBS Studio Version

27.2.0

## Expected Behavior

When `OBS.app` is set to "Prefer External GPU" in _Finder_ settings, OBS, its sub-processes, and the renderer, should all launch on, and prefer use of, an external GPU.

## Current Behavior

When `OBS.app` is set to "Prefer External GPU" in _Finder_ settings, OBS, its sub-processes, and the renderer, all launch on, and prefer use of, the internal GPU. OBS will show up on _both_ GPUs. but frequently will show activity on the iGPU, which for most users is not expected nor preferred.

Additionally, if the internal display is driven via the iGPU, but with the application driven via the eGPU (I.E. an eGPU with no display attached), and "Prefer External GPU" has been set, the OBS render preview will be blank, and toggling it off then on again will cause an OBS hard crash.

## Steps to Reproduce

1. Open Finder, and navigate to `OBS.app`
2. `Get Info` on the `.app` package and select "Prefer External GPU"
    - _**For Internal Display Crash Only**: Disconnect any displays from the eGPU, and wait for macOS to shift over to driving the internal display via the iGPU._
3. Launch OBS
4. Monitor behavior in Activity Monitor

### Workarounds

1. Open Finder, and navigate to `OBS.app`
2. `Get Info` on the `.app` package and select "Prefer External GPU"
3. "View package contents" and navigate to `/Contents/Frameworks`
4. **For each `.app` package, repeat step 2.
5. Open Terminal
6. Run `SafeEjectGPU gpus`
7. Run `SafeEjectGPU gpuids [gpuid] LaunchOnGPU [OBS.app path]
    - Replace `[gpuid]` with the ID for the eGPU from step 6
    - Replace `[OBS.app path]` with the absolute path to `OBS.app`

### Internal Display Workaround
1. Connect a display or "dummy" display dongle to the eGPU
2. Set macOS to "mirror" the display
3. Use a tool, such as RDM, to set the resolution and refresh rate to the internal display (e.g. `1680x1050 @ 60Hz`)

## Notes
Apple provides resources for information on setting the GPU for rendering, however, being a cross-platform app written in C, using OpenGL, it is a bit cryptic on how one would do this in OBS. CEF and other frameworks may also need manually configured.
- https://developer.apple.com/documentation/metal/gpu_selection_in_macos
- https://developer.apple.com/documentation/metal/gpu_selection_in_macos/selecting_device_objects_for_graphics_rendering

Note that Apple provides recommendations for rendering on the second link, but these are **not** to be taken as hard fact, nor as system documentation, but rather as explanations of potential lag due to copying between GPUs. There _are_ cases where these rules will be more favorably broken, and likewise, many places where it is best to stick to them.

Best practice may be to offer a GPU selection drop-down in the settings, as opposed to numerous "Prefer External GPU" checkboxes, as this would, in theory, be the most reliable.

**Comment by gxalpha** [comment] 2022-05-18 23:48
> Would be interested to know if any development is planned in the direction of being able to select GPU options within OBS. I do see multiple choices for the VT Apple Hardware Encoder when my eGPU is connected, however regardless of selection I can see no real activity in Activity Monitor on the eGPU.

- Feel free to test and provide feedback on #5424



Regarding the rest of this issue, as far as I'm aware no one on the OBS team has a Mac with an external GPU to test, reproduce, and fix this issue with (I did have one, but the enclosure broke and now it's just sitting there).

While this doesn't mean it's impossible for this problem to get fixed, it does mean that it's unlikely.
Someone else with an eGPU would have to dig into it and provide a fix; and the fact that ARM Macs don't support eGPUs anymore (and Apple doesn't seem to intend on changing this in the near future) means it might never happen.

**Comment by gxalpha** [comment] 2023-01-04 21:57
As mentioned in https://github.com/obsproject/obs-studio/pull/5424#issuecomment-1274926001 and other places, we consider eGPU's to be unsupported territory on macOS. As such, this issue will unfortunately be a wontfix.

**Closed by gxalpha** 2023-01-04 21:57 UTC
Labels: macOS

**Comment by matthewbrandt** [comment] 2023-01-04 22:05
I read the reasoning that has been given but leaving hundreds (thousands?) of users on MacOS Intel machines with eGPU's wondering which GPU is being used is just, to be frank, shoddy coding. I don't see how adding such a small feature can cause such a large PR in the first place (as a relatively tech-savvy person). I guess I'll just have to accept this decision, as I am not able to contribute to the project with my level of knowledge.

**Comment by MisutaaAsriel** [comment] 2023-01-04 22:37
> I read the reasoning that has been given but leaving hundreds (thousands?) of users on MacOS Intel machines with eGPU's wondering which GPU is being used is just, to be frank, shoddy coding. I don't see how adding such a small feature can cause such a large PR in the first place (as a relatively tech-savvy person). I guess I'll just have to accept this decision, as I am not able to contribute to the project with my level of knowledge.

It's not exactly shoddy coding per se, but rather the way OBS handles GPUs in general and the way they surface them is counter to the way Apple has you query eGPUs and surface them.

OBS is _Encoder Centric_, in that it's showing the _Encoder Name, and referencing the encoder's ID_.

eGPUs however use _generated_ IDs for encoders, and the encoder name is generic, compared to the _GPU_ name.

So it'd require an overhaul of their code just to do this "proper", from my PoV, just to support something Apple themselves consider unsupported now.

On Ventura, a PR for adding hardware encoder names doesn't even work anymore. the encoder names are all blank, so it's a thing where _Apple themselves have ditched this_ so OBS isn't going to waste the effort going forward.

I also want to say the person who was handling eGPU code doesn't have a working eGPU anymore, last I heard? I may be misremembering though.

It's unfortunate, more or less. eGPUs had a lot of possibilities, but developers were so late to the party and information was so misinterpreted that by time support came Apple had moved on.
