### ISSUE TITLE
No system tray icon after updating to v28

### ISSUE THREAD

**Issue by kreaninw** [obsproject/obs-studio#7262] opened 2022-09-02 04:17 UTC
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JFmJCqvyKNuZ0qRV

### Expected Behavior

The system tray icon should show up like in the previous version (27).

### Current Behavior

There's no system tray icon showing up at all. I have [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) installed and enabled.

The behavior of this issue, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/188057521-e7b57a32-3a68-4742-b1ec-7e9a2939945f.mp4

### Steps to Reproduce

1. Open OBS.
2. Make sure the system tray is enabled in OBS's settings.
3. There's no system tray.
...

### Anything else we should know?

This should not be confused with **[issue #6422](https://github.com/obsproject/obs-studio/issues/6422)**, as the tray icon shows up in that issue, but the app icon was missing. This issue, there's no OBS tray showing up at all.

I use the **[Flatpak](https://flathub.org/apps/details/com.obsproject.Studio)** version. This should streamline the issue.

**Comment by tytan652** [comment] 2022-09-02 05:23
I can't reproduce that with the Flatpak, surely more an issue with your installation than a bug.

**Comment by tytan652** [comment] 2022-09-02 05:51
QGnomePlatform Flatpak package is the one blocking the feature under Wayland, once removed the feature is back.

**Comment by kreaninw** [comment] 2022-09-02 06:46
@tytan652 

There are 2 QGnomePlatform Flatpak packages installed in my system, as shown below:

```
QGnomePlatform                  org.kde.PlatformTheme.QGnomePlatform                               5.15-21.08   system
QGnomePlatform                  org.kde.PlatformTheme.QGnomePlatform                               6.3          system
```

Which package should I remove? Thanks.

**Comment by tytan652** [comment] 2022-09-02 06:53
We use Qt6 since 28, so the second.

**Comment by kreaninw** [comment] 2022-09-02 07:10
@tytan652 

Thanks. I can confirm that, after removing QGnomePlatform (Qt6), the tray icon comes back now.

However, I don't know if it's a good idea to remove a runtime from the system, as other apps which use this runtime might not work properly. And second, if I happen to use another Flatpak Qt6 app, this runtime would be downloaded again, thus breaking OBS again. Therefore, I will leave this issue open.

---

For anyone having this issue, as a workaround, please run this in the terminal:

```
flatpak uninstall QGnomePlatform
```

Then, remove this: `runtime/org.kde.PlatformTheme.QGnomePlatform/x86_64/6.3 (system)`.

**Comment by tytan652** [comment] 2022-09-02 07:18
> However, I don't know if it's a good idea to remove a runtime from the system, as other apps which use this runtime might not work properly.

This package is not a hard dependency, just something that is installed if you install an app that use KDE Runtime and GNOME as desktop environment.

It's just theming.

**Comment by tytan652** [comment] 2022-09-02 07:21
This issue is fixed upstream but not released yet.

https://github.com/FedoraQt/QGnomePlatform/issues/89
https://github.com/FedoraQt/QGnomePlatform/commit/6505fb8941f6b96ef2983de9d77a493dc2e37671

**Comment by gxalpha** [comment] 2022-09-02 10:45
Closing as this is not caused by OBS and already fixed upstream.

**Closed by gxalpha** 2022-09-02 10:45 UTC
Labels: Dependency Issue
