### ISSUE TITLE
Multiple audio tracks fail at high frame rates.

### ISSUE THREAD

**Issue by lizardpeter** [obsproject/obs-studio#5763] opened 2022-01-09 00:05 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/i8yceKg6G7evLVtG

### Expected Behavior

The recording should work perfectly.

### Current Behavior

The recording never starts, and when trying to stop it, it reports "Stopping recording..."

### Steps to Reproduce

1. Set FPS to 120 or another high value.
2. Use multiple audio tracks.

**Comment by WizardCM** [comment] 2022-01-09 00:07
Duplicate of #2855

**Closed by WizardCM** 2022-01-09 00:07 UTC
