### ISSUE TITLE
Display Capture source shows a black frame when click on it (DXGI Desktop Duplication)

### ISSUE THREAD

**Issue by COOLIGUAY** [obsproject/obs-studio#4922] opened 2021-06-19 23:14 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/tbal9yOODhimeMKA

### Expected Behavior

The display capture source should display normally when you click on it.

### Current Behavior

The display capture source shows 1 black frame when click on it with capture method is automatic.
By default in my pc is "DXGI Desktop Duplication".

With "Windows 10 (1903 and up" works fine.
I have tested in 26.1.1 and DXGI works fine too.

### Steps to Reproduce

1. Add a Display Capture source
2. Click on the source
3. Click out of the source
4. Repeat clicking on and out

By default the capture method is DXGI and shows 1 black frame when clicking on the source.

https://user-images.githubusercontent.com/55640387/122657254-3d471180-d162-11eb-8673-94bad59ddbad.mp4

**Comment by notr1ch** [comment] 2021-06-19 23:30
Your log shows a large number of third party plugins, do you still see this behavior without them?

**Comment by COOLIGUAY** [comment] 2021-06-19 23:44
The same thing with a clean 27.0.1

https://obsproject.com/logs/n_nTGFU6gIiThBB_

**Comment by WizardCM** [comment] 2021-06-20 00:15
I'm quite sure this is the same bug as #4831 just with a different visual side effect.

**Comment by WizardCM** [comment] 2021-06-20 05:55
Heads up: the workaround for this is to disable the Source Toolbar.

**Comment by flaeri** [comment] 2021-06-20 10:23
source toolbar removed works around the issue in studio mode for me. 

This will also happen if you have display capture in two different scene, and you have them selected (red box), and move between them (not in studio mode). Source toolbar inactive does not impact it.

**Comment by COOLIGUAY** [comment] 2021-06-20 10:33
I can reproduce it too Flaeri.
With method "Windows" works fine but in automatic or DXGI shows the black frame.

With the toolbar disabled the black frame happens when open the source properties.

**Comment by gxalpha** [comment] 2022-11-23 20:30
Duplicate of #4831

**Closed by gxalpha** 2022-11-23 20:30 UTC
Labels: Windows, Confirmed

**Comment by RytoEX** [comment] 2022-11-23 20:33
Just as a note, while these seem to be the same root cause, this issue only occurs with DXGI. It does not occur with WGC.
