### ISSUE TITLE
Error from ffmpeg-mux

### ISSUE THREAD

**Issue by Anivie** [obsproject/obs-studio#11677] opened 2024-12-29 01:57 UTC
### Operating System Info

Other

### Other OS

Fedora 41 on KDE6

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/VIXwoXP0TXOObI9A

### Expected Behavior

Normal operation

### Current Behavior

After I start recording, I will receive an error a few seconds later: `ffmpeg-mux: /usr/bin/obs-ffmpeg-mux: symbol lookup error: /lib64/libobs.so.30: undefined symbol: XLookupString`

### Steps to Reproduce

1. Start record
2.Wait a seconds

**Comment by mihawk90** [comment] 2024-12-29 02:15
Can't reproduce this. Certainly not a problem with OBS itself.

**Comment by derrod** [comment] 2024-12-29 08:32
Duplicate of #11667 and should be fixed by #11668.

**Closed by derrod** 2024-12-29 08:32 UTC
