### ISSUE TITLE
Reconsider doing proper alpha blending

### ISSUE THREAD

**Issue by CryZe** [obsproject/obs-studio#5674] opened 2021-12-19 16:28 UTC
### Operating System Info

Other

### Other OS

All of them

### OBS Studio Version

27.1.3

### OBS Studio Log URL

No

### Expected Behavior

White Text on a white background shouldn't ever yield black pixels.

### Current Behavior

There's lots of black / greyish pixels showing up on semi transparent pixels.

### Steps to Reproduce

1. Create white text
2. Put it above a white background
3. Scale the text up enough to see the grey pixels.
...

### Anything else we should know?

This was the original PR that fixed this: https://github.com/obsproject/obs-studio/pull/1578

It unfortunately got reverted.

![https://camo.githubusercontent.com/b9e65f16f4aa0262f881524cb9478bfe18f4a46da52baaff52aaddabd9a5e0cf/68747470733a2f2f692e696d6775722e636f6d2f5668686b51635a2e706e67](https://camo.githubusercontent.com/b9e65f16f4aa0262f881524cb9478bfe18f4a46da52baaff52aaddabd9a5e0cf/68747470733a2f2f692e696d6775722e636f6d2f5668686b51635a2e706e67)

**Comment by CryZe** [comment] 2021-12-19 16:33
The PR got reverted because people abuse the wrong alpha blending on text as a fake text border. Obligatory xkcd:

![[obligatory xkcd https://imgs.xkcd.com/comics/workflow.png](https://imgs.xkcd.com/comics/workflow.png)](https://imgs.xkcd.com/comics/workflow.png)

I don't mind it being broken on the text as much (though it bothers me every time I see it on someones stream), but game capture is majorly affected by this problem, where it probably shouldn't have been reverted.

**Comment by jpark37** [comment] 2021-12-19 19:12
I noticed you copied the image from your old PR. Are you sure this is still happening? From 27.1.3:
![image](https://user-images.githubusercontent.com/10396506/146687661-82229079-c00a-49f0-b17d-244d811aec9b.png)

**Comment by CryZe** [comment] 2021-12-19 21:45
You did not zoom in / scale it up far enough, it only happens on the transparent pixels.

**Comment by jpark37** [comment] 2021-12-19 22:22
Sorry, I though you meant scale outside OBS, i.e. look closely.

I looked at the text source example, and the problem there is that the source image is in straight alpha, e.g. 1/1/1/0.5 instead of 0.5/0.5/0.5/0.5, so the Default bilinear filtering will not be mathematically correct. You should be able to work around this by enabling a scale filter on the source, which samples the text texture texels 1:1 and writes to a render target with premultiplied alpha, then scales into the canvas filtering with premultiplied colors. Any scale filter will fix the edge darkening, but Bilinear will match Default behavior.

Hopefully the same workaround will work for game capture, but I haven't tested.

Making this work properly for the Default case seems like a drag. For game capture, it would mean running a full screen shader to convert from straight to premultiplied, which we don't want to pay for by default since most games are completely opaque. We could add a toggle, but every checkbox is more complexity.

In theory, LiveSplit could render to a DXGI swapchain with premultiplied colors, and specify DXGI_ALPHA_MODE_PREMULTIPLIED, assuming it works as advertised since I've never tried it.

**Comment by CryZe** [comment] 2021-12-19 22:46
> For game capture, it would mean running a full screen shader to convert from straight to premultiplied, which we don't want to pay for by default since most games are completely opaque.

There already is a checkbox for whether the source is even captured transparently in the first place, so it could just be tied to whether that is active.

**Comment by jpark37** [comment] 2021-12-19 23:34
> There already is a checkbox for whether the source is even captured transparently in the first place, so it could just be tied to whether that is active.

We don't want to pay an extra cost if they don't rescale the image though.

> Also are you sure this has anything to do with bilinear filtering? It seems to happen if it's a 1:1 transform too:

There's the larger issue that OBS blends in linear space, which is what GPU/PNG specs want. Others cheat, e.g. web/GDI, either out of of ignorance or power savings. Ultimately, we chose to be linear-correct going forward. A toggle to blend naively isn't impossible, but it's not just a few lines of code. Significant plumbing would be involved.

> The scale filter does nothing:

You need to set a resolution for that filter to work, but I meant the "Scale Filtering" setting if you right-click on the source itself. Either way should trigger an extra draw that avoids filtering colors with straight alpha though.

**Comment by jpark37** [comment] 2021-12-19 23:52
Also, is this regular LiveSplit? If you can share the splits/layout, I can try debugging that.

**Comment by FiniteSingularity** [comment] 2022-03-09 23:07
I am seeing similar issues with any sources containing alpha channels, including the edges of chroma keyed sources using the OBS Chroma key filter.  Here is an exaggerated example using StreamFX Dynamic mask plugin.  My scene sources are ordered as follows:

1. Source containing image of chalkboard:  This source is filtered with dynamic mask, using the black/white mask shown below (where black is alpha=0, white is alpha=1)
2. Source containing exact same image of chalkboard.

Since I am placing the same image on top of itself (with the top copy masked a bit), I would expect to not see the mask at all- it should just look like the original image.  Instead I am getting a grey halo around the mask as seen below:
![mask-halo](https://user-images.githubusercontent.com/72580859/157552476-9dbbfe83-5129-40b5-bfcb-81e21580fb71.png)

In order to make sure the problem isn't in the dynamic mask plugin, I wrote a simple OBS shader to do exactly what this scene is doing- pick a top source that is masked, and a bottom source that is not, and combine them.  And the result is exactly what I would expect- you cant see the mask at all.  Here is a snippet of the shader code I am using, where `InputA` is the masked source (that has an alpha channel) and `Background` is the background source that we're putting `InputA` over:

```
  float4 pixel = InputA.Sample(maskSamplerA, v_in.uv);
  float3 pixelRGB = float3(pixel[0], pixel[1], pixel[2]);
  float4 bgPixel = Background.Sample(maskSamplerB, v_in.uv);
  float3 bgPixelRGB = float3(maskPixel[0], maskPixel[1], maskPixel[2]);
  float3 outputRGB = pixelRGB + bgPixelRGB * (1.0 - pixel[3]);
```
I've noticed that if the last line of my shader is:
```
float3 outputRGB = pixelRGB * pixel[3] + bgPixelRGB * (1.0 - pixel[3]);
```
I get the exact same result as using OBS to compose everything- the exact same fuzzy halo.

![mask](https://user-images.githubusercontent.com/72580859/157552540-fdbd8d5d-9c2f-419e-8842-d7dfb86b7aa8.png)

**Comment by y19940406** [comment] 2022-03-31 15:53
I've got a similar problem with browser source. I have a website which is transparent. It contains a div with css like this: {color: #000000; background: #ffffff33;} 
I expected it apperanced fully white background when the background is white and a little bit white when the background is black. But is get gray when background is white...
![image](https://user-images.githubusercontent.com/26666233/161097531-099bee80-c99f-4f21-b393-200268a436b5.png)

**Comment by jpark37** [comment] 2022-04-02 06:14
I see three issues here.

- Given that OP has not responded in some time, I guess he can either work around the issues he was having, or he doesn't want to press further.
- The second issue has more text than I want to try to parse repro steps out of.
- The last may be resolved by #6257.

We should probably just close this out. If anyone still has an issue, please file a clean ticket, ideally with clear, minimal repro steps/assets.

**Comment by CryZe** [comment] 2022-04-02 12:40
No, the issue still exists and I still want it fixed. I'll try to create an executable for you to reproduce it.

**Comment by gin3715** [comment] 2022-04-24 18:18
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1, 27.1.3

### Expected Behavior

No black edge around text (27.1.1)

### Current Behavior

OBS produces a black edge around text (since 27.1.3)

### Steps to Reproduce

Load the html page provided below as a browser source. Put a whilte color source below the browser source

Similar issue happed in browser source with transparency.
```example.html
<html>
<body style="background-color: transparent; padding-top: 20px">
<span style="background-color: #fff; border-radius: 30px; padding: 20px">test</span>
</body>
</html>
```
A browser source loads this simple webpage with transparent background, over a white color source. Results shouldn't produce a black edge around the span element.

![black-edge](https://user-images.githubusercontent.com/17375889/164990606-5e9b88b3-e996-4125-ae97-e2f9b269a8fd.png)

PS: The problem wasn't there at 27.1.1

**Comment by Fenrirthviti** [comment] 2022-10-19 20:21
There have a lot of changes in color handling with all the HDR work, is this issue still present?

If it is, please provide as close to exact reproduction steps as possible so that we can test if this is an expectation, if there is a workaround, or is a bug.

**Comment by CryZe** [comment] 2022-10-19 21:15
I just checked and with v28.0.3 the issue still exists:

![https://i.imgur.com/Mq3WCB4.png](https://i.imgur.com/Mq3WCB4.png)

### Steps to Reproduce

1. Create white text
2. Put it above a white background
3. Scale the text up enough to see the grey pixels.
...

Neither the foreground nor the background consist of any other color than white, there's no reason that there should be any darker pixels. This is an alpha blending bug.

**Comment by flaeri** [comment] 2022-10-19 21:40
Could you try to right click the text source > Blending Method > SRGB Off?

**Comment by CryZe** [comment] 2022-10-19 21:50
That somehow solves it?! I really don't think it should've though. That has nothing to do with sRGB and everything with how alpha is blended. HOWEVER the problem still applies to game capture and toggling the blending method does not fix the problem there.

![https://i.imgur.com/06HNjIy.png](https://i.imgur.com/06HNjIy.png)

**Comment by Fenrirthviti** [comment] 2022-10-20 05:28
As the original report is resolved, marking as fixed.

**Closed by Fenrirthviti** 2022-10-20 05:28 UTC

**Comment by CryZe** [comment] 2022-10-20 06:24
No it's not??? Only if you activate some obscure unrelated feature it essentially bugs out even more and happens to start being correct by complete accident. If anything it's even more bugged now and nothing is resolved at all.
