### ISSUE TITLE
An encoder error occurred while recording. (QuickSync)

### ISSUE THREAD

**Issue by backcgo** [obsproject/obs-studio#5571] opened 2021-11-24 17:19 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/dJU5o3VIsuKvsW9m

### Expected Behavior

Recording well

### Current Behavior

Can't record with an error message .

### Steps to Reproduce

1.install OBS 27.1.3 
2.set output mode "simple"
3.set Encoder Hardware(QSV)
4.start Record
5.An encoder error occurred while recording.

### Anything else we should know?

Hello.
I have an issue with **latest version (27.1.3)**
When I use QSV encoder, if I set the output mode 'Simple'
It won't start record with this message "An encoder error occurred while recording"

but If I set the output mode "Advanced" (use QuickSinc H264)
and check "Rescale output" it works well...... but I don't want to use Rescale output"
(**version 27.1.1 also have this issue** but **27.0 is fine** it doesn't have the issue) 

I want to know why latest versions have this issue and an old version 27.0 doesn't have it.
If I use version 27.0 everything is OK but I want to use latest version.

**Comment by Fenrirthviti** [comment] 2021-11-24 18:27
Updated title to reflect the issue more clearly. There are some weird issues with QuickSync and outdated graphics drivers, please ensure that your Intel GPU graphics drivers are fully up to date. Going off the log, it looks like they are quite outdated.

Please try installing: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

**Comment by backcgo** [comment] 2021-11-25 02:28
Thank you for your reply.
I installed the latest graphic driver(30.0.101.1069) but it didn't solve the problem. 
After installed the driver even I checked Rescale output, the error poped out.(this has no longer worked)
I've removed 27.1.3 reinstall 27.0  (27.0 is still OK)
It looks like I have to use 27.0.....

**Comment by RytoEX** [comment] 2022-02-13 04:39
I cannot reproduce this on an Intel HD Graphics 630 (i7-7700HQ, Kaby Lake) with driver 30.0.101.1069 in either OBS Studio 27.1.3 or 27.2.0. Can you please re-test and confirm if this is still an issue? If this is still an issue, please provide an updated OBS session log.

If someone else with an Ice Lake or newer system (not Comet Lake) can try to reproduce this, that would be helpful.

**Comment by backcgo** [comment] 2022-02-13 08:45
I finally found out why my OBS doesn't work correctly.
It's because the program "super display" which is installed for using Galaxy tab as a second monitor. 
I uninstalled the program and OBS worked well. but It's a shame I can't use the OBS lately version. I need to use "super display" program.

**Comment by cRoCx** [comment] 2022-02-13 18:30
I have just encountered the same issue with OBS Studio 27.1.3 on an Asus Zenbook Duo 14, Windows 11, Intel Gen 11 Iris Plus Graphics G7 (i7-1165G7, Tiger Lake). I paused Windows Updates for two weeks. Now, after resuming and installing a single Windows cumulative update, the OBS error message has gone. I wonder why that solved it, since the Intel Graphics driver is the same version, before and after this update.

**Comment by RytoEX** [comment] 2022-02-14 06:41
> I finally found out why my OBS doesn't work correctly. It's because the program "super display" which is installed for using Galaxy tab as a second monitor. I uninstalled the program and OBS worked well. but It's a shame I can't use the OBS lately version with the program. I need to use "super display" program :(

@backcgo
I would recommend filing a report with the authors/publishers of SuperDisplay. I'd guess that it is using up hardware resources that OBS would otherwise need or it is causing some other conflict. Their documentation suggests that you could enable software encoding, but I suspect that may be too much strain on your system resources.


> I have just encountered the same issue with OBS Studio 27.1.3 on an Asus Zenbook Duo 14, Windows 11, Intel Gen 11 Iris Plus Graphics G7 (i7-1165G7, Tiger Lake). I paused Windows Updates for two weeks. Now, after resuming and installing a single Windows cumulative update, the OBS error message has gone. I wonder why that solved it, since the Intel Graphics driver is the same version, before and after this update.

@cRoCx 
If you experience this issue again, please seek assistance via our [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum), and if it's determined that this is indeed a bug, then you can open a new GitHub Issue. For now, it sounds like you're no longer experiencing an issue, and the issue that you were experiencing was not the same as the reporter here.


With all of that, I will be closing this Issue. Thank you for your assistance!

**Closed by RytoEX** 2022-02-14 06:41 UTC
Labels: Windows
