### ISSUE TITLE
Regression: OBS Virtual Camera becomes green channel only

### ISSUE THREAD

**Issue by adammw** [obsproject/obs-studio#7441] opened 2022-09-23 12:23 UTC
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/2cYjUuvHeL9YQcm-

### Expected Behavior

Expected video output to work correctly as previously did

OBS Screenshot
![image](https://user-images.githubusercontent.com/153219/191959006-b737005c-cf10-4824-939f-91cd2366708d.png)

Image Preview (Discord)
![image](https://user-images.githubusercontent.com/153219/191959828-bd089bb5-a64a-49c0-8870-f331c5e658a7.png)

### Current Behavior

Image Preview (Discord)
![image](https://user-images.githubusercontent.com/153219/191959159-868e4fe2-c39b-4e2f-bde6-9fe72039f14f.png)

### Steps to Reproduce

1. Enable Virtual Camera
2. View Virtual Camera in any other application

### Anything else we should know?

Previously working on the same system before OBS 28.0.2 upgrade. Confirmed downgrading to OBS 28.0.1 solves the issue.

**Comment by Fenrirthviti** [comment] 2022-09-23 16:25
Can you validate if this is resolved by switching the color space from Full back to Limited?

While this is an issue and we're looking in to it, unless you know exactly why you should be using Full color space, you should not really be using it.

**Comment by Fenrirthviti** [comment] 2022-09-23 17:21
Duplicate of https://github.com/obsproject/obs-studio/issues/7442

**Comment by Fenrirthviti** [comment] 2022-09-23 17:21
The other issue is more active, please use it for further tracking as it's the same problem.

**Closed by Fenrirthviti** 2022-09-23 17:21 UTC

**Comment by BitClipper** [comment] 2022-09-23 22:52
Switching Color Range from "Full" to "Limited" fixed the issue on my side.
