### ISSUE TITLE
The dock panel can be moved without clicking on it

### ISSUE THREAD

**Issue by SovaProgrammer** [obsproject/obs-studio#3730] opened 2020-11-13 18:13 UTC
## Platform
Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 26.0.2

## Expected Behavior
The dock panel does not move.

## Current Behavior
The dock panel is moving.

## Steps to Reproduce
1. Open OBS Studio.
2. Unpin any the dock and, without clicking on it, move the cursor closer to the heading, and then move slowly.

## Additional information
[Video](https://youtu.be/pOT_HGglgpI)

**Comment by WizardCM** [comment] 2020-11-14 00:21
Please do not create 3 such closely related tickets separately. Closing this in favour of the first ticket.

Duplicate of #3728

**Closed by WizardCM** 2020-11-14 00:21 UTC
