### ISSUE TITLE
Browser Source - <select> dropdown does not work properly and does not show the menu

### ISSUE THREAD

**Issue by Sun3** [obsproject/obs-studio#5498] opened 2021-11-06 14:26 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/vZC9V2dyyqNjMb0l

### Expected Behavior

When you click on the ```<select>``` Dropdown the menu shows below it.

### Current Behavior

When clicking on the ```<select>``` Dropdown combo box a menu should show underneath. Instead, no menu shows up.

If you enable the checkbox 'Enable Browser Source Hardware Acceleration' in OBS-->Settings-->Advanced Tab, then the screen goes black and shows the menu on the upper left side.

### Steps to Reproduce

1. Start recording with the Browser Source
2. Set website URL to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
3. Click on the <select> Dropdown and nothing happens, the menu does not show up
...

### Anything else we should know?

Thank you.

**Comment by nico-apps** [comment] 2021-11-06 14:31
This is a confirmed issue with CEF (the browser client OBS uses.) Our developers are working on including a newer version that fixes this.

**Comment by mihawk90** [comment] 2021-11-06 15:08
obsproject/obs-browser#148 among others.

**Comment by Sun3** [comment] 2021-11-06 15:26
Thanks... I appreciate it.

**Comment by Fenrirthviti** [comment] 2021-11-06 17:12
Duplicate of https://github.com/obsproject/obs-browser/issues/148

Closing.

**Closed by Fenrirthviti** 2021-11-06 17:12 UTC
