### ISSUE TITLE
'Open [VST] Plugin Interface' Button doesn't show up when OBS is installed under 'Applications' but does when installed via Steam

### ISSUE THREAD

**Issue by attaboyBrad** [obsproject/obs-studio#7617] opened 2022-10-19 02:39 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.1.0-beta1

### OBS Studio Version (Other)

Issue occurs with 28.0.3 as well

### OBS Studio Log URL

https://obsproject.com/logs/XJ9aujHkkrsBAX9_

### Expected Behavior

When I add a 'VST 2.x Plug-In' Audio Filter to an audio source and select the plugin, a button labeled 'Open Plug-In Interface' like that pictured below usually appears.
![Screen Shot 2022-10-18 at 18 12 49](https://user-images.githubusercontent.com/4070613/196582592-3f53364b-ea52-4770-8532-59753f907c9f.png)

### Current Behavior

That button now only appears when I install OBS via Steam, and not when I install OBS via a downloaded installer.  The image from 'Expected Behavior' is from a Steam based install.  The image below is from a regular install--note the absence of said button.
![Screen Shot 2022-10-18 at 18 10 59](https://user-images.githubusercontent.com/4070613/196582562-44845ad0-e2ac-4b2e-9f7a-8cca33100baf.png)

### Steps to Reproduce

1. Launch OBS from an install in '/Applications'
2. Add a 'VST 2.x Plug-In' and select a plugin--I use the ones from Izotope Elements Suite. They're installed in '/Library/Audio/Plug-Ins/VST'
3. Look for the 'Open Plug-In Interface' button.
...

### Anything else we should know?

I've reproduced this issue with both 28.0.3 and 28.1 Beta 1.  When installed via Steam, the button shows up just fine for both versions.  When installed via downloaded dmg, the button fails to appear.  When 27.4.2 is installed via dmg the button shows up.

From the logs, I've noticed the following lines (or similar) appear when installed from dmg and don't appear when running a Steam-based version:

18:55:08.948: User selected new VST plugin: '/Library/Audio/Plug-Ins/VST/Neutron 3 Elements.vst'
18:55:08.949: Couldn't get a pointer to plug-in's main()

I've tried resetting all of the permissions settings I could find.  I tried copy/pasting the .vst files to '~/Library/Audio/Plug-Ins/VST'.  I tried uninstalling and re-installing the VST Plugins.  I tried using an empty profile as well as replacing the whole settings folder.  No joy.

**Comment by ArmchairGuru** [comment] 2022-10-19 02:48
I reproduced this behavior on 28.0.3 running windows 10. No 'open plugin interface button' appeared. However on closing that filter dialog window and reopening the filter window, the button appears as expected.
Still odd behavior as it does not appear on the vst filter add.

**Comment by ArmchairGuru** [comment] 2022-10-19 03:13
> I reproduced this behavior on 28.0.3 running windows 10. No 'open plugin interface button' appeared. However on closing that filter dialog window and reopening the filter window, the button appears as expected. Still odd behavior as it does not appear on the vst filter add.

Apologies, forgot to mention, this was also standard install, not steam.

**Comment by RytoEX** [comment] 2022-10-19 04:55
If I had to hazard a guess, the VSTs you are trying to load are compatible with x86_64 (Intel) and not arm64 (Apple Silicon). This is why the "Open Plugin Interface" button shows up in the Steam version (which is x86_64) and not the one installed via dmg (which was probably arm64).

To confirm, you could upload a log file from the Steam version where it works and the manually installed version where it does not.

**Comment by gxalpha** [comment] 2022-10-19 07:07
> I believe I read on the forums somewhere that Settings and Profiles were in a shared location, and that Plugins were separate

Just for your info, this is wrong. OBS plugins are in the same location for Steam installs as they are with normal installs.

**Comment by RytoEX** [comment] 2022-10-19 15:48
As an aside, Steam always launching the x86_64 version seems to have been caused by a bug in our helper script to detect the system architecture. That bug has been fixed (#7620), so launching OBS via Steam should (in upcoming releases) correctly launch the arm64 version on Apple Silicon systems and the x86_64 version on Intel CPU systems. This should resolve the apparent inconsistency between the two versions.

That will, however, not fix VST plugin architecture incompatibility, which I suspect is the other half of this issue. See also:
* #7619
* #7575

The gist being that VSTs for x86_64 will not run in arm64 OBS. If your VSTs are x86_64, you must run the x86_64 (Intel) version of OBS to run those VSTs.

**Closed by RytoEX** 2022-10-19 15:48 UTC

**Comment by attaboyBrad** [comment] 2022-10-19 16:08
Thanks @RytoEX,

Your links above are right-on.  I looked into my plugins and they indeed dropped support for VST2 in a recent update.  
I'll try to figure out how to contribute to the VST3 bounty.

For anybody else that comes along: my current workaround is to implement my plugins in AudioHijack and then to use Loopback (also by Rogue Amoeba) to route the processed audio into OBS as a regular Audio Input source.

**Comment by attaboyBrad** [comment] 2022-10-22 17:42
> > I believe I read on the forums somewhere that Settings and Profiles were in a shared location, and that Plugins were separate
> 
> Just for your info, this is wrong. OBS plugins are in the same location for Steam installs as they are with normal installs. Edit: To clarify, the above applies to macOS only.

Thanks for the clarification.  [Here's where I found the original information (that apparently only applies to windows)](https://obsproject.com/forum/threads/obs-studio-28-1-release-candidate.160580/post-588752) for anybody else that comes down the road.

**Comment by Mikymike453** [comment] 2023-04-30 09:33
Solution: Re-install an older version of OBS (like 27.x) and the actual VST interface will show up again. 

I tried everything : reinstalling VST's, re-installing OBS, resetting everything, deleting the support folders, moving the VST to the support folders of OBS application folder etc. etc. But the problem was not this, there is something wrong in the OBS 28.x updates (at least for my MacBook air Apple M1 system) 

So hopefully re-installing an older version will solve the problem for you.

**Comment by arnespremberg** [comment] 2023-06-06 20:02
> Solution: Re-install an older version of OBS (like 28.x) and the actual VST interface will show up again.
>

To me that sounds not like a solution but more like a workaround where you force OBS to open in Rosetta, instead of ARM native. This may (for now) be the only way to use many VST2 plugins though.

On KVR audio, you'll be able to filter for universal binary plugins, these work natively for me using the newest version of OBS on my M1 Max: https://www.kvraudio.com/plugins/macos-universal-binary-2-plugins/effects
