### ISSUE TITLE
Avermedia Windowed and Fullscreen Projector (Source) has washed out colors on an HDR monitor with HDR disabled

### ISSUE THREAD

**Issue by theacclaimed** [obsproject/obs-studio#8032] opened 2023-01-09 17:24 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/0R76K0MuDdrqNgxA

### Expected Behavior

Projector Source should have the same color mapping as the OBS window. I compared it with Avermedia's RECentral as well as Xsplit and the issue doesn't show up there making it exclusive to the recent OBS build.

### Current Behavior

I use fullscreen projector so I can see the PS5 gameplay without all the OBS stream overlays while streaming. Using the monitor in SDR mode (it's an HDR monitor) causes the Projector Source either windowed or fullscreen to show the colors drastically washed out, as if the brightness has been turned up to the max. This issue was first observed in the 29.0.0 beta but also exists in the public release.
![projector-source-SDR-colors-on-HDR-display](https://user-images.githubusercontent.com/122300531/211367817-3f4d8067-7d13-43ee-9e9d-2dcff9d09c98.JPG)
![correct-colors-with-HDR-enabled](https://user-images.githubusercontent.com/122300531/211367990-d799050b-e401-4f87-b6d9-2abc6efb2b49.JPG)

### Steps to Reproduce

1. Disable HDR on an HDR capable display
2. Select an Avermedia capture card as a video capture device
3. Open Window Projector (Source) or Fullscreen projector source and observe the colors will be washed out on the HDR monitor.
4. Enabling HDR on the monitor makes the colors display correctly
5. Also, if using an SDR monitor the colors display correctly in the Projector (Source) 
![projector-source-SDR-colors-on-HDR-display](https://user-images.githubusercontent.com/122300531/211367817-3f4d8067-7d13-43ee-9e9d-2dcff9d09c98.JPG)
![correct-colors-with-HDR-enabled](https://user-images.githubusercontent.com/122300531/211367990-d799050b-e401-4f87-b6d9-2abc6efb2b49.JPG)

**Comment by rmtracey** [comment] 2023-01-14 22:47
Also noticed this issue. The the capture card itself may not have anything to do with it as I have an Elgato. Doesn't happen on SDR monitors.

Unfortunately I can only add another report of the issue as I no longer have access to an HDR monitor, so I can't do any further testing.

**Comment by jpark37** [comment] 2023-01-15 19:20
We had a similar issue on 28 that was addressed in 29 (#7790). That was HDR with HDR on though, and you're on 29 already, so this might be another corner case that we aren't handling. Unfortunately, I cannot reproduce this. Both windowed and fullscreen source projector look fine on my end.

Other draw calls that you have might not be restoring the renderer back to default and causing the problem, which would explain why I'm not seeing it in a fresh scene.

- Is this happening for you with a fresh scene and device capture only? 
- Did you customize the transition at all?

**Comment by jpark37** [comment] 2023-01-15 20:07
Your log shows your active scene (Main View) has a bunch of other stuff in it. My request to you is to start with a fresh scene collection. If the problem still happens with just the AverMedia capture, then I can't (easily) help. If it doesn't happen, try to add stuff back and figure out the minimal steps that cause the issue to appear.

**Comment by theacclaimed** [comment] 2023-01-16 18:15
It still occurs on a new scene with just the AverMedia capture source. If the Projector is the Source the issue occurs. If the projector is the scene, then it displays with the correct color space.

Here is the projector preview of the source
![capture-card-SDR-on-HDR-issue](https://user-images.githubusercontent.com/122300531/212743231-cca0772d-545c-45ce-a25a-0ee10fbb35d1.JPG)

Here is the projector preview of the scene
![projector-scene](https://user-images.githubusercontent.com/122300531/212743384-23d7a541-35e0-4e4b-a2a4-afd6fcb24fb3.JPG)

**Comment by RytoEX** [comment] 2023-01-16 18:45
> It still occurs on a new scene with just the AverMedia capture source.

A new _Scene Collection_, not just a new scene. Items in other scenes can still be active. Please also provide a log file when you do this.

**Comment by theacclaimed** [comment] 2023-01-17 02:44
Here is the latest log file with a brand new scene collection with only the Avermedia as the Video Capture device.
https://obsproject.com/logs/q4SL9qN85Q5FtO3o

![source-preview-vs-scene-preview](https://user-images.githubusercontent.com/122300531/212798409-4ecf6718-c25b-4d17-af71-a74d86c8a7e3.JPG)

**Comment by jpark37** [comment] 2023-01-17 07:00
Thanks. Unfortunately, I am still no closer to reproducing this. I tried opening scene and source projectors at the same time, and it's still fine on my end.

I can try Windows 10 at some point since I've been testing on Windows 11, but I don't have 10 installed anywhere, so it might take me a bit to find the time to set that up. That's the only guess I have at the moment from looking at the logs.

**Comment by jpark37** [comment] 2023-01-22 23:12
I couldn't repro on Windows 10 either. Can you try the modified OBS build for Windows x64 at the bottom of this page? It should add extra info into the log that might help.
https://github.com/obsproject/obs-studio/actions/runs/3981856598

Do NOT open two projectors when performing this test. Launch OBS, select the minimal scene collection, relaunch OBS to reset the log, open one projector, move it onto the monitor that reproduces the issue, and then close OBS.

**Comment by CrashTesteur** [comment] 2023-01-24 14:11
Hi, I just did 29.0 update and suddenly I had this issue… I tried the modified build, here's the log:
https://obsproject.com/logs/YpTrUcnmIH4yL1OT ( 1) HDR turned on on my monitor)
https://obsproject.com/logs/yFtdZAYD2XbzW9In ( 2) HDR turned off)
I see those are different between the two:
1) JP projector: 0 1 0 0 300
    JP projector: 0 1 3 0 300
2) JP projector: 0 1 0 0 300
    JP projector: 0 1 1 0 300

**Comment by CrashTesteur** [comment] 2023-01-24 14:31
Wait, I just found how to resolve this on my end: using Radeon Software -> Display -> (Display 2) Color Depth, it was 10 bpc and changing it to 8 bpc seems to work, I never used Radeon Software so I don't know how and why it only broke OBS 29 projector...
maybe something changed here? https://obsproject.com/logs/H8VuHpK7xJ1VY14z
I see it's only showing this once now
JP projector: 0 1 0 0 300

**Comment by jpark37** [comment] 2023-01-24 16:33
Thanks for the info; I was able to repro now. I think 29 added wide-color SDR preview support, and that's probably when this bug crept in. I made a pull request to fix the issue.

**Closed** 2023-01-25 03:39 UTC
