### ISSUE TITLE
Stream freezes on fullscreen in Vulkan 

### ISSUE THREAD

**Issue by Shoegzer** [obsproject/obs-studio#2219] opened 2019-12-03 21:34 UTC
Under a screen capture source, whenever a vulkan-based application switches to fullscreen, the stream freezes on the client.  Windowed vulkan apps stream just fine.  

This is a [known issue](https://steamcommunity.com/app/275850/discussions/0/1643171537290764199/) although it doesn't appear to have been reported on github.

Tested using OBS 24.0.3 flatpak, Linux Mint 19.2 with kernel 5.0, and with a game emulated through RPCS3 in vulkan.

**Comment by Fenrirthviti** [comment] 2019-12-03 21:43
OBS does not currently have Vulkan capture support. When the game runs fullscreen, it is exclusive mode so window/display capture may not work. This is not a bug or issue with OBS. Vulkan support is pending (for Windows) here: #2156 

Also, you deleted the issue template. Please make sure you follow the proper template when submitting a report.

**Comment by Shoegzer** [comment] 2019-12-04 17:41
Thanks @Fenrirthviti.  I should have mentioned that fullscreen _does_ work sometimes on this Vulkan/linux test system, but for some reason I haven't tracked down, it sometimes freezes as mentioned above.  I'll have someone try to connect to a fullscreen Vulkan event with it freezing consistently, even through reboots of the OBS system and other troubleshooting efforts, only to try again days later with the same person/client to find it suddenly works.  Very odd.  

Also, I can stop the freezing if I cause a different application to "draw" something else on the screen as an overlay.  For example, I can start my display settings widget which provides a visual indicator of the current monitor in a small box on the screen - and then the fullscreen vulkan event will stream without freezing even though that box is visible.  Also odd.

To be sure I understand properly, are you saying that because OBS doesn't support Vulkan, it  must fall back to "exclusive mode" which is independent of the graphics API?  Also, I haven't been able to find any discussion of linux vulkan support in OBS, are you aware of any?  

Sorry for deleting the template - I should have realized it was firm requirement and I'll keep it in mind next time.

**Comment by Fenrirthviti** [comment] 2019-12-05 22:06
Vulkan capture support on Linux would be nice, and is something we would like to do eventually, but is not in the current priority list. Exclusive Fullscreen is usually a Windows thing, but as we're just requesting the capture data from xcomposite, there might be something similar going on where the data is not being drawn properly to that capture method. I'll reopen this for now, as there might be something we can do with the other capture sources to avoid this. I strongly suspect it's an environment issue, however, and not an OBS bug.

**Comment by Shoegzer** [comment] 2019-12-06 17:57
Thanks @Fenrirthviti.  At least there's hope for linux vulkan support even if not in the near future.  I'm happy to help test anything you or the team comes up with.  You're probably right about it being an environment issue though; I'm curious if others with different linux distros have more positive or at least different experiences.

**Comment by Fenrirthviti** [comment] 2020-04-26 04:02
OBS now has Vulkan capture support, meaning this should no longer be an issue.

**Comment by Shoegzer** [comment] 2020-04-27 21:26
Thanks @Fenrirthviti.  Do you know if the flatpak release will pick up this update soon?  I'll be able to test once it is.

**Comment by dodgepong** [comment] 2020-04-27 21:39
Looks like this was closed with a misunderstanding. OBS has Vulkan capture _on Windows_, not on Linux.

Also the Flatpak is not managed by us.

**Comment by Shoegzer** [comment] 2020-04-27 21:46
Ah, that's too bad.  I hope linux gets the same treatment soon (any idea what it would take?).  Thanks for reopening though.

**Comment by PatTheMav** [comment] 2020-12-31 15:59
@Fenrirthviti @WizardCM I guess we keep this open as a way to track "Missing Vulkan support in Linux", but I am not sure if this is something we want to track via issues (given the amount of _actual_ issues we have on Github).

I'd vote to close this, as it is _not_ an issue, but a missing feature. Thoughts?

**Comment by dodgepong** [comment] 2020-12-31 17:04
Yeah I'm not really sure why I re-opened this. Linux doesn't have any sort of shared texture game capture to begin with, so it's not a bug as much as a feature that does not currently exist on Linux.

**Closed by dodgepong** 2020-12-31 17:04 UTC
Labels: Linux

**Comment by Shoegzer** [comment] 2020-12-31 19:09
@dodgepong are you saying linux itself has no shared texture game capture, or the linux variant of OBS?  In case of the latter I could reword this issue as a feature request instead, and we could reopen this for tracking.  

Again though, linux/vulkan apps **do** work in OBS, it's just that some of them freeze when displaying fullscreen, and not all the time.  For example, the yuzu emulator in fullscreen mode works fine in OBS all the time; however the rpcs3 emulator sometimes presents a still image on the far side when the presenter switches it to fullscreen (and at other times, seemingly randomly, this issue does not occur).

**Comment by dodgepong** [comment] 2020-12-31 19:16
The latter -- there is no shared texture capture plugin for OBS on Linux. We generally don't use Github issues for feature requests though, better to use https://ideas.obsproject.com/ or if you have an actual technical design proposal, then submit an [RFC](https://github.com/obsproject/rfcs).
