### ISSUE TITLE
Just crashing

### ISSUE THREAD

**Issue by luanfsp** [obsproject/obs-studio#10824] opened 2024-06-11 03:08 UTC
### Operating System Info

Windows 11

### Other OS

Windows 24H2 26100.745

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/tHRnPCAUchtTeCaV

### OBS Studio Crash Log URL

https://obsproject.com/logs/ylR3J2Gz6EEO2jvK

### Expected Behavior

at least open

### Current Behavior

Dont open with last beta

### Steps to Reproduce

1. Just trying to open

### Anything else we should know?

Nope, thanks

**Comment by derrod** [comment] 2024-06-11 03:14
Duplicate of #10799

**Closed by derrod** 2024-06-11 03:14 UTC
