### ISSUE TITLE
Stinger transiton target scene error

### ISSUE THREAD

**Issue by zengsansui** [obsproject/obs-studio#4925] opened 2021-06-21 01:57 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

no

### Expected Behavior

when switch scene1 to scene2 . Stinger play ends display scene 2, no flash scene 1.

### Current Behavior

when switch scene1 to scene2 . Stinger playback End Flash Scene1.

### Steps to Reproduce

1.create scene1.
2.create color source to scene1.
3.create scene2
4.create color source2 to scene2.
5.create stinger transiton 
6.set stinger propperties: select video file -> set transition point value more than the video duration -> clicl ok.
7.switch scene1 to scene2.
8.Stinger playback End Flash Scene1.

### Anything else we should know?

transition point is 3300.
this is test video ：
![26d27b00-8686-11eb-8123-339b8119590c](https://user-images.githubusercontent.com/30925319/122696834-a455ea80-d276-11eb-8666-689c4ef8eb3d.gif)

This is bug phenomenon:
![1624240551](https://user-images.githubusercontent.com/30925319/122696955-e848ef80-d276-11eb-9724-c9c3cedde00c.gif)

**Comment by RytoEX** [comment] 2021-06-21 04:55
Stingers are designed to transition at some point between 0 and the total duration of the transition, typically at a point where the transition covers the entire viewing area.  It is up to the user to specify a transition point that makes sense given the transition duration.  If a user sets a transition point after the transition's duration, then OBS will transition at that point as specified by the user.  I'm closing this as "working as intended".

**Closed by RytoEX** 2021-06-21 04:55 UTC
