### ISSUE TITLE
SVG images silently fail on Windows while working as expected on Linux

### ISSUE THREAD

**Issue by qwertychouskie** [obsproject/obs-studio#3481] opened 2020-09-18 18:29 UTC
## Platform

Operating system and version: Ubuntu 20.04 and Windows 7
OBS Studio version: 25.0.3 (Ubuntu)/25.0.8 (Windows)

## Expected Behavior

When importing a scene on Windows that was created on Linux using SVG sources, all the image sources should work in the same way they do on the Linux installation.

## Current Behavior

Using an SVG in an image source silently fails on Windows while it works as expected on Linux.

## Steps to Reproduce

1. Create a scene collection on Linux that uses SVG images
2. Export the scene
3. Import the scene in Windows
4. Images don't display but no errors are given

## Additional information

As a stopgap I will maintain PNG copies of all my images for the Windows system, but it'd be preferable to only maintain one set of images.

**Comment by dodgepong** [comment] 2020-09-18 18:33
When you say "using SVG images", what sort of source are you using to add them to your scene? Image source, media source, or something else?

**Comment by Fenrirthviti** [comment] 2020-09-18 18:35
Also please provide a log. As a note here, exporting a scene collection does *not* include the content. This means any images, videos, etc. are not exported as part of the collection.

**Comment by qwertychouskie** [comment] 2020-09-18 19:25
Image source.  I manually corrected the path on the Windows system to pint to the copied image but it still didn't display.

**Comment by Fenrirthviti** [comment] 2020-09-18 19:29
Same error I'm getting:

```14:27:15.516: User added source 'Image 3' (image_source) to scene 'Capture Card'
14:27:26.785: warning: Could not find codec parameters for stream 0 (Video: svg, none): unspecified size
14:27:26.785: Consider increasing the value for the 'analyzeduration' and 'probesize' options
14:27:26.785: Failed to find decoder for file 'C:/Users/fenri/Desktop/Freesample.svg'
14:27:26.785: gs_image_file_init_internal: Failed to load file 'C:/Users/fenri/Desktop/Freesample.svg'
14:27:26.785: [image_source: 'Image 3'] failed to load texture 'C:/Users/fenri/Desktop/Freesample.svg'```

Looks like the ffmpeg we ship on windows does not support svg.

**Comment by WizardCM** [comment] 2020-09-24 11:06
I can confirm I get the same error. A quick Google tells me "ffmpeg needs to be compiled with --enable-librsvg" ([source](https://stackoverflow.com/a/48217742))

**Comment by jbolduan** [comment] 2022-09-19 19:11
I know this thread is very old now but I was wondering if there was any plan to support SVG images for overlays in the future on Windows.

**Comment by jbolduan** [comment] 2022-09-19 19:24
I've never looked under the hood of this project but would I be correct in saying all that would need to happen is adding --enable-librsvg to the configure args here: https://github.com/obsproject/obs-deps/blob/master/deps.ffmpeg/99-ffmpeg.zsh ?

**Comment by RytoEX** [comment] 2022-09-19 19:50
While `--enable-librsvg` is what would be needed, we discussed this internally and decided that adding librsvg would introduce a large number of other dependencies that we are not comfortable adding at this time.

**Comment by jbolduan** [comment] 2022-09-19 20:22
Sounds good and thank you for the quick response!  I appreciate the work everyone who maintains and develops OBS Studio does.

**Comment by RytoEX** [comment] 2022-10-13 19:54
Closing per above comments.

**Closed by RytoEX** 2022-10-13 19:54 UTC
Labels: Windows, Confirmed
