### ISSUE TITLE
If you right click on a non active scene. OBS transitions to that scene

### ISSUE THREAD

**Issue by BarryCarlyon** [obsproject/obs-studio#7197] opened 2022-08-27 13:40 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/xmuPv06G-Qtx3wYv

### Expected Behavior

When you right click a scene the context menu appears to let you do whatever (such as rename or duplicate) without OBS transitioning to that scene

### Current Behavior

When you right click a scene OBS transitions

### Steps to Reproduce

1. Have two or more scenes
2. Right click the scene that is not being sent to "live"
3. See that OBS trnasitions to the right clicked scene and sets the right clicked scene as active in error

**Comment by WizardCM** [comment] 2022-08-28 02:31
This is not new to 28, but a known behaviour of how Qt's lists work.

A proper fix for this will require code to disentangle "active" vs "selected", or cancel "selected" events if it's a right click action.

**Comment by rmtracey** [comment] 2022-09-17 15:10
I'd also like to request that this be looked into. Right clicking causing a scene transition makes no sense and is very frustrating when trying to access the context menu of an inactive scene. I think it's worth trying to fix.

**Comment by PatTheMav** [comment] 2022-09-19 22:37
Closing this as it's not a bug but working as implemented. If additional functionality is desired, please use the existing channels for feedback to request this as a feature.

Could also be that https://github.com/obsproject/obs-studio/issues/7196 prohibits this from working, as as right click changes focus, but should not change selection, and right now (for better or worse) we entangled both.

**Closed by PatTheMav** 2022-09-19 22:37 UTC
