### ISSUE TITLE
ppc64le jpeg has vertical bars through it

### ISSUE THREAD

**Issue by dpocock** [obsproject/obs-studio#4054] opened 2021-01-12 12:27 UTC
## Platform

Operating system and version: Debian 10 buster on ppc64le (POWER9)
OBS Studio version: 26.1.0+dfsg1-1~bpo10+2

## Expected Behavior
I tried to add two versions of the same picture, one is a JPEG and the other is a PNG.  I expect to see the same picture.

## Current Behavior
The PNG appears correctly.  The JPEG appears with vertical strips through the image.

## Steps to Reproduce
1. open OBS
2. click to Add an image
3. select a JPEG
4. see the image appears with vertical bars

**Comment by WizardCM** [comment] 2021-01-12 12:29
As we don't officially support ppc directly, could you provide example pictures.

**Comment by dpocock** [comment] 2021-01-12 12:38
![this is the input file, forest-back](https://user-images.githubusercontent.com/1236687/104315342-1ada0980-54db-11eb-8ebe-d1fdc3bb72ef.jpg)
![this is a screenshot showing the bug, obs-jpeg-as-strips](https://user-images.githubusercontent.com/1236687/104315543-68ef0d00-54db-11eb-8a9a-a9b0a96ff38a.png)

**Comment by dpocock** [comment] 2021-01-12 12:40
There is a bug with similar symptoms in Blender:
https://developer.blender.org/T80912

**Comment by derrod** [comment] 2021-01-12 12:46
OBS uses ffmpeg for image decoding, so this may be an issue with ffmpeg rather than OBS itself.

**Comment by dpocock** [comment] 2021-01-12 12:46
For the JPEG that is rendered incorrectly:
```
forest-back.jpg:           JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1920x1080, components 3
```

For another JPEG that does work:
```
white-house-full-1080.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=17, description=WASHINGTON, DC - AUGUST 18:  The American flag sits next to a empty speaker podium before U.S. , manufacturer=Canon, model=Canon EOS-1D X, orientation=upper-left, xresolution=774, yresolution=782, resolutionunit=2, software=GIMP 2.10.8, datetime=2020:05:18 23:19:15], comment: "WASHINGTON, DC - AUGUST 18:  The American flag sits next to a empty speaker podium before U.S.", progressive, precision 8, 1920x1080, components 3
```

Here is the image that works:
![white-house-full-1080](https://user-images.githubusercontent.com/1236687/104316239-7658c700-54dc-11eb-80b3-00211b0bf564.jpg)

For those who want to use it with green screen, the lectern is here:
https://gitlab.com/freertc/scenes/-/tree/master/white-house

**Comment by dpocock** [comment] 2021-01-12 12:48
> OBS uses ffmpeg for image decoding, so this may be an issue with ffmpeg rather than OBS itself.

Can you suggest any tests that can be done from the command line to prove it is an issue in ffmpeg?

**Comment by WizardCM** [comment] 2021-01-12 12:50
Could you also add a session log from OBS (Help -> Log Files -> Upload Current Log) after reproducing the issue.

**Comment by dpocock** [comment] 2021-01-12 12:54
Here is the log

[2021-01-12 13-31-27.txt](https://github.com/obsproject/obs-studio/files/5802163/2021-01-12.13-31-27.txt)

**Comment by derrod** [comment] 2021-01-12 13:04
> Can you suggest any tests that can be done from the command line to prove it is an issue in ffmpeg?

Try converting the JPEG to BMP via ffmpeg, e.g. `ffmpeg -i in.jpeg out.bmp` and see if it's correct.

Otherwise the main difference between the images is that the broken one is chroma subsampled (4:2:0) whereas the one that's fine isn't (4:4:4). So this could be an issue with OBS' conversion to RGBA here: https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/libobs/graphics/graphics-ffmpeg.c#L143

**Comment by dpocock** [comment] 2021-01-12 13:08
My ffmpeg package is version 7:4.3.1-5~bpo10+1

I tried this command
```
ffmpeg -i forest-back.jpg out.bmp
```

and it produced a valid out.bmp file, I looked at it and it appears correct.

**Comment by WizardCM** [comment] 2021-01-12 13:11
As a side note, I just tested the provided forest JPG file on Windows OBS 26.1.1 and did not run into any issues.

**Comment by RytoEX** [comment] 2022-10-22 06:18
I cannot reproduce this on Windows 10 with OBS Studio 28.0.3. Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

**Comment by RytoEX** [comment] 2022-11-02 20:00
Closing per above. If this is still an issue, please comment with updated Steps To Reproduce and a new OBS log, and we can determine if we should reopen this or open a new Issue.

**Closed by RytoEX** 2022-11-02 20:00 UTC
