### ISSUE TITLE
Variable Fonts Don't Properly Display - Font Weights and Effects are ignored

### ISSUE THREAD

**Issue by dpkonofa** [obsproject/obs-studio#11596] opened 2024-12-08 04:44 UTC
### Operating System Info

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/b78SAsCYM5LrJ6Qf

### Expected Behavior

When adding a "Text (FreeType 2)" source to the scene, changing the font face, font weight, and text effects should reflect the changed settings in the scene as shown in the font selector.

### Current Behavior

This works with static fonts but does not work with variable fonts (e.g., Saira from Google Fonts). When selecting a variable font, only the main font style and weight are used and the effects have no effect.

<img width="1003" alt="Screenshot 2024-12-07 at 21 41 26" src="https://github.com/user-attachments/assets/669ee85e-d74f-4aef-94c1-d6c8004a8edd">

As you can see, despite the "Font" selection showing the font, the preview and the scene do not show that font correctly.

### Steps to Reproduce

1. Add a "Text (FreeType 2)" source to the scene.
2. Type some text into the box and select a variable font face. Set a font weight and apply a text effect.
3. Confirm the font settings and observe that the font selector shows the correct font and weight but the preview and scene do not.
...

**Comment by kkartaltepe** [comment] 2024-12-08 20:59
fonts with variable or custom axes are not supported in our text plugins.

Technically assuming the qt UI let you modify the various axes they are not passed to the renderer. Weight and Slant can usually get translated into bold/italic if you apply them enough and work through those font flags. Someone would need to implement support for passing these through and then implementing them in the text plugins.

**Comment by dpkonofa** [comment] 2024-12-08 22:43
It would be good to get this resolved. Downloading the static version of the fonts fixed the issue but, since more and more fonts are becoming variable/dynamic, this will both prevent confusion from future users and offer better support of common fonts like Google Fonts (which are now mostly being offered as variable fonts).

**Comment by Fenrirthviti** [comment] 2024-12-08 22:54
PRs are welcome, but there really isn't much demand for this kind of thing. Since this is a feature request, and not a bug, I will close this issue.

Feature requests can be made and upvoted on our [Ideas page](https://ideas.obsproject.com/)

**Closed by Fenrirthviti** 2024-12-08 22:54 UTC
Labels: New Feature
