### ISSUE TITLE
"Check for updates automatically never disappears"

### ISSUE THREAD

**Issue by mrfambo** [obsproject/obs-studio#5707] opened 2021-12-27 23:45 UTC
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/aEMYemor-oc20Trx

### Expected Behavior

I would like the modal to disappear when I click a button.

### Current Behavior

Here is the Loom of it. It never closes!

https://www.loom.com/share/2ef80e0cc9b544d48c3e83593d22ac52

### Steps to Reproduce

1. Install OBS
2. Launch it
3. Click on update preference and it never closes!
...

### Anything else we should know?

I re-installed it multiple times!

**Comment by WizardCM** [comment] 2021-12-27 23:47
Duplicate of #4904

**Closed by WizardCM** 2021-12-27 23:47 UTC
