### ISSUE TITLE
Lua: OBS doesn't search for native libraries in script's location

### ISSUE THREAD

**Issue by Smartkin** [obsproject/obs-studio#9100] opened 2023-06-17 22:09 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/V3rwlTs6CLrO4p0c

### Expected Behavior

Load the native binary just like the pure Lua files

### Current Behavior

When attempting to load native libraries from the script's location, OBS only attempts to search for .lua files and not native libraries. So if `local lib = require("mylib")` is in script's location and called `mylib.dll` OBS will only try to find `mylib.lua`

### Steps to Reproduce

1. Add any native library with Lua bindings into the script's location
2. Attempt to include that library in Lua's script using `require`

### Anything else we should know?

Currently there is a workaround to put the native library into any of the folders OBS does search, which are OBS's executable location and obs-scripting folder, but it's inconvenient to ask the script's user to go ahead and drag around library files.

**Comment by gxalpha** [comment] 2023-09-04 13:31
As presented this is a feature request and not a bug. We use GitHub Issues only for bug tracking.

Just for the record, me closing this issue is not meant to imply anything about the Pull Request you opened, we just don't consider this issue to be a bug.

**Closed by gxalpha** 2023-09-04 13:31 UTC
