### ISSUE TITLE
Google Chrome Loses Link

### ISSUE THREAD

**Issue by sgort87** [obsproject/obs-studio#4543] opened 2021-04-17 03:08 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/jcAA_ZuqjMHxF4is

### Expected Behavior

I have a few game scenes, one with a Chrome browser window in front of the rest. When using this scene, it should automatically relink to new site names.

### Current Behavior

It works correctly if the page name is close enough, like new tabs or Google-related sites seem to refresh it, but breaks if sites are changed to a name that's too different, when not using the scene which includes that browser source. I'm not sure, but it may require the browser window to be reopened while off the scene as well.

### Steps to Reproduce

1. Create two scenes, one with a Chrome browser (Browser Scene), and one without the browser (Non-Browser Scene). For this, let's use a "new tab" window name, which should be "[chrome.exe]: New Tab - Google Chrome".
2. Open Browser Scene and have a good time.
3. Change to Non-Browser Scene.
4. Close Chrome window.
5. Reopen Chrome window and go to a different (non-Google) site.
6. Open Browser Scene and have a bad time.
...

### Anything else we should know?

This was also an issue in at least version 26.

**Comment by RytoEX** [comment] 2021-04-17 07:24
This looks like a duplicate of #3537.

**Closed by RytoEX** 2021-04-17 07:24 UTC
