### ISSUE TITLE
[BUG] OBS adds scene collection that was previously deleted

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2711] opened 2020-04-13 19:04 UTC
If you exit OBS studio, completely delete all scene collections leaving the directory empty, then restart OBS studio it will automatically create a new scene collection and randomly name it the name of one of the collections that used to be there before they were all deleted.

## Platform

Operating system and version:  Windows 10 x64 (1909)
OBS Studio version:  25.0.4

## Expected Behavior

Since there are no scene collections because they've all been deleted, OBS should either start up without a scene collection until the user creates a new one in the menu, or if it is going to automatically add a collection itself, it should name it "Default" or something neutral, and not reuse the name of a collection the user previously might have had and deleted.

## Current Behavior

OBS automatically creates a new scene collection on startup if there are none, and it gives it the name of a scene collection that used to exist previously but was deleted by the user previously.

https://obsproject.com/logs/O92gvUS6x9MIvEq0

## Steps to Reproduce

1.  Fresh OBS installation with no plugins or addons installed.
2.  Create a new scene collection named "asdf" and switch to it.
3.  Exit OBS and go into the directory where scene collection JSON files are stored and delete all of them.
4.  Start OBS up, and it will automatically create a new scene collection named "asdf".

**Comment by skeletonbow** [comment] 2020-04-13 19:06
Note that it is not resurrecting the old scene collection that was deleted previously, it is just using the old collection's name when creating a blank new default configuration, which is a bit confusing and probably not what the user wants or expects.

**Comment by WizardCM** [comment] 2020-04-15 23:53
OBS stores the name of the currently active scene collection in a different config file. I'm not sure if we need to worry about users manually deleting the JSON file, but I'd prefer to pop an error message on startup (with a "continue anyway" button?) because if, for example, an antivirus deletes the scene collection, this way the user knows it's not something OBS did on its own.

**Comment by skeletonbow** [comment] 2020-04-19 23:44
Since the current behaviour upon starting and not finding any scene collections is to create a new one automatically, I would suggest from a user interface friendliness POV it might be friendlier to popup the "Add Scene Collection" dialog automatically, asking for a name for the collection that is about to be created, and preloading it with "Default" or "Untitled".  For first time users, perhaps a friendlier way would be a popup saying something of the manner of "Welcome to OBS, lets get started, first we need to create a new scene collection...".  Just some thoughts I had WRT user friendliness improvements that might be useful.

**Comment by Fenrirthviti** [comment] 2020-04-26 06:19
Going to close this as it's not a bug, and is working as intended. A suggestion to change this behavior should go on the Ideas page if desired.

**Closed by Fenrirthviti** 2020-04-26 06:19 UTC
