### ISSUE TITLE
CRASH when delete source

### ISSUE THREAD

**Issue by ogaaaan** [obsproject/obs-studio#10282] opened 2024-02-24 07:49 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/IyhkG0pFIB515W1d

### OBS Studio Crash Log URL

https://obsproject.com/logs/vwVOj3FhttcNaWnX

### Expected Behavior

my obs always crash when deleting any source.
everytime.

### Current Behavior

crashed

### Steps to Reproduce

1. select source (any)
2. click delete button
3. crash

**Comment by Fenrirthviti** [comment] 2024-02-24 07:51
Duplicate of #10245

**Comment by Fenrirthviti** [comment] 2024-02-24 07:51
Update the Stream Deck software, and this should be fixed.

**Closed by Fenrirthviti** 2024-02-24 07:51 UTC

**Comment by ogaaaan** [comment] 2024-02-24 07:53
thanks!!
