### ISSUE TITLE
Preview of the stutter that appears in streams/records on any change

### ISSUE THREAD

**Issue by Adega-Studio** [obsproject/obs-studio#8896] opened 2023-05-12 15:17 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/TlqFlouysN9CO1hy

### Expected Behavior

1. Smooth recording without stuttering and broadcasting like in a game
2. Uninterrupted work for more than 1 hour.

### Current Behavior

Any capture method leads to one problem. After 1 hour, in the interval of 1-2 hours, the staners appear for 15 minutes and then again smoothly and as if in a circle.
Here is a YouTube stream and trovo where this is regularly repeated.
https://youtu.be/W8d3BuCTan8?t=3981
https://trovo.live/s/Atdega/549790763401?vid=ltv-108668109_108668109_3270835008922642999&adtag=user.Atdega.clip
Start time of starters 1:06:00
There are many such videos. I hope my friends also give you all the video with the same problem

### Steps to Reproduce

1. Game capture or screen capture
2. Any game 60 fps recording or streaming 60 fps via OBS more than 1 hour. The problem can randomly appear from 1 hour to 2 hours
3. Any resolution and any encoder (no effect, tested)
...

### Anything else we should know?

There was a long time ago a solution from **jpark37** that removed stuttering https://github.com/obsproject/obs-studio/pull/5029 but it is outdated.

**Comment by AnnaSmile** [comment] 2023-05-16 12:10
Writing with google translator

Good Day, I see a problem like mine.
I confirm! The picture is normal, but after a while, terrible jerks / hiccups begin. Then it passes!
And today it repeats again!

I already run it as administrator, and the priority is high. And I looked at a bunch of setup guides, set them up.
In the end, absolutely nothing helps.

I have an old obs, there are no such problems, if all the functions worked, I would sit further on the old obs.

Developers, do you know what's the matter?, what brakes are happening, why haven't they fixed it yet?

One person was able to fix
the picture is smooth and nice to look at!

I don't think my pc is weak
Ryzen 5900x
RTX 3090
RAM 64
SSD 980 Pro.

Finally make OBS normal

This is not a game of freezing and stattering, In the game the picture is 60 fps smoothly, but in obs Hiccups and on the stream the picture also freezes !!

Time Kode 33:00, 57:00, 3:07:40, 3:24:30, 3:42:21 https://www.youtube.com/watch?v=ciZNI_7_ZOo&t=11348s
Time Kode 13:30, 1:11:20, 2:08:25, 2:43:05, 3:26:44 https://www.youtube.com/watch?v=0K8_Sn_mzCE
On other streams, everything is the same, in all games, friezes, lags, hiccups.
Let me remind you These Hiccups are exactly in obs, in games exactly 60 fps games go smoothly.
These time codes, selectively, and lags and friezes much more often, every 2-3 minutes
Encoder loaded 40-60%

Windows 10 64 bit. Obs version is also 29.1.1
But all the obs that come out freeze and lag the picture, at least screen capture, windows, games.

**Comment by Adega-Studio** [comment] 2023-05-17 16:32
Dear person**jpark37**. We need your help in the fight against cancer. You have already made a working version. We are ready for any test.

**Comment by Fenrirthviti** [comment] 2023-06-01 19:13
Duplicate of https://github.com/obsproject/obs-studio/issues/4191

**Closed by Fenrirthviti** 2023-06-01 19:13 UTC
