### ISSUE TITLE
OBS records third-party overlays (Steam) even though option disabled

### ISSUE THREAD

**Issue by bartmoss** [obsproject/obs-studio#3946] opened 2020-12-20 13:46 UTC
## Platform

Operating system and version: Windows 10 64bit 20H2, Build 19042.685
OBS Studio version: 26.1.0

## Expected Behavior

In the game capture source, there is an option "capture third party overlays /such as steam)". Disabling it should prevent the steam overlay from being captures.

## Current Behavior

Steam overlay is being captured, regardless of the state of the checkbox of the option.

## Steps to Reproduce

1. Disable overlay option
2. Record video
3. Overlay appears in video :-)

Screenshots: https://imgur.com/a/Cz6iVTV (2 screens, one of settings, one of video with overlay)

Note that this is also true for Steam notifications, not just the FPS counter, those are just more difficult to "catch".

## Additional information

This must be a reasonably new issue, I have footage recorded on 15th November, 2020, which does not include the overlay, and I am certain I am using the same configuration/capture sources/etc. One thing is, since the "old" nvenc encoder is no longer supported/no longer appears in the drop down, I switched to the new one, but I doubt that has any relevancy.

I should add that I may not have been on the latest OBS version in November, as I am usually pretty conservative about updates.

Do let me know if you need any additional information.

Also, I did search for any potentially known issues filed for this and didn't find any; my apologies if I overlooked something.

**Comment by derrod** [comment] 2020-12-20 13:49
This is a pretty old and known issue (also a duplicate of #2922). The option is "best effort" but not guranteed, in some cases OBS cannot ignore overlays and they will still be captured. Setting the game executable explicitly and using the fastest hook rate can increase the chances of it working however.

**Comment by bartmoss** [comment] 2020-12-20 14:00
I wonder if this is related to Cyberpunk 2077 being a DX12 game? I did a quick test with Legends of Grimrock and Dragon Age Inquisition and behavior seems to be correct in those. I don't think I have another DX12 game to check.

**Comment by derrod** [comment] 2020-12-20 14:04
Yeah OBS also has some issues with DX12 specifically. I'm not sure if those also affect overlays, but it is possible.

**Comment by bartmoss** [comment] 2020-12-20 14:24
So, yes, this is a DX12 specific issue. I have Civilization VI, which is a great test case.

Start game in DX12 mode: Same issue
Start game in DX11 mode: Option works as intended

Another user reports the same [here](https://obsproject.com/forum/threads/dx12-and-the-overlays.108974/).

Changing hook rate has no effect for me either.

**Comment by KomiMoe** [comment] 2021-01-29 20:06
XSplit Broadcaster don't have this BUG.

**Comment by staridiot** [comment] 2021-04-04 02:06
Any progress on a fix for this? I'm playing KF2 on DX11 and this issue happens regularly.

**Comment by Robyer** [comment] 2021-05-18 20:53
I have this issue on all DX12 games that I have tried (e.g. Resident Evil Village, Serious Sam 4, Observer: System Redux). Works correctly in DX11 games.

Comment from the [link](https://obsproject.com/forum/threads/dx12-and-the-overlays.108974/)
> Try adjusting your game capture source's Hook Rate to a faster setting. OBS needs to hook into the application first to be able to capture without the other overlays.

doesn't seem to be correct regarding current version of OBS, because for DX11 games I can first start the game, let Steam load its overlay and after that start OBS and capture the game - it still works and doesn't capture any overlays even though OBS wasn't registered first - so this bug doesn't seem to be timing related, but just DX12 related.

**Closed** 2021-08-17 15:24 UTC
Labels: Windows, Confirmed
