### ISSUE TITLE
The browser dock does not attach immediately after unpinning (when does not click to dock but only to bring the cursor closer and hover over the attachment point all OK)

### ISSUE THREAD

**Issue by SovaProgrammer** [obsproject/obs-studio#3729] opened 2020-11-13 17:58 UTC
## Platform
Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 26.0.2

## Expected Behavior
Dock panel is docked after undocked.

## Current Behavior
After undocked, the docking station does not insert into the docking station.

## Steps to Reproduce
1. Open OBS Studio.
2. Unpin any the dock and try to dock it.

## Additional information
[Video](https://youtu.be/b7qrIfBXiyU)

**Comment by WizardCM** [comment] 2020-11-14 00:21
Please do not create 3 such closely related tickets separately. Closing this in favour of the first ticket.

Duplicate of #3728

**Closed by WizardCM** 2020-11-14 00:21 UTC
