### ISSUE TITLE
[BUG] Filters applied to groups can break the alpha channel

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2852] opened 2020-05-02 18:39 UTC
When a group contains a source with partial transparency, when certain builtin filters are applied to the group itself, it causes the alpha channel to be rendered black, even when the filter itself is not doing anything, such as Color Correction default configuration.

## Platform

Operating system and version:  Windows 10 x64 (1909)
OBS Studio version: 25.0.8

## Expected Behavior

The pixels with partial alpha transparency in the source within the group that has the OBS filter applied, should be rendered as partial transparency without a grey tinge to them.

## Current Behavior

When the filter is turned off on the group, the source renders with proper alpha transparency,
blending into the background.  When the filter is enabled, the alpha channel is no longer rendered properly and grey pixels get added to the image rather than being blended properly with the background making it look like a drop shadow.

https://obsproject.com/logs/4pENgLTGqabVvVQE

## Steps to Reproduce

1. Within a scene, create "Group A"
2. Add an image source to the scene which contains partial transparency such as a partial transparent PNG.  It is best if this is in color rather than grey to make the problem more visually observable.
3. Move the image source into the group.
4. Add a white color source to the scene to see and emphasize the transparent pixels.
5. Add the Scroll filter to "Group A" (however the problem also occurs with any of the following filters applied:  Color Correction, Apply LUT (choose original.png so no changes occur), Sharpen, Crop/Pad or Scroll).  Leave the filter with its default settings.
6. Toggle the scroll filter on and off and observe the alpha channel on partially transparent pixels being incorrectly rendered when the filter is enabled.

## Additional information

If you apply the scroll or other filters to the source itself instead of the group, or to the scene instead, then the right thing happens and the pixels are rendered correctly.  The problem only occurs when a filter is applied to a group containing a source with partial transparency, causing it to work as if the underlying pixel is black instead of the actual background outside of and underneath the group.

**Comment by skeletonbow** [comment] 2020-05-02 18:40
![OBS-Groups-Alpha-bug-before-bug](https://user-images.githubusercontent.com/49483514/80872880-d5deb180-8c82-11ea-8285-3d11a465b9ab.png)
![OBS-Groups-Alpha-bug-after-bug](https://user-images.githubusercontent.com/49483514/80872890-e1ca7380-8c82-11ea-9ad2-006565315a70.png)

**Comment by Xaymar** [comment] 2020-05-03 16:52
I attempted to fix this by messing with the blending, but it does not seem to be something that can be fixed with that alone.

It seems that in order to fix this properly a custom blend function needs to be used. This can be done by disabling blending and then feeding a read-write rendertarget as both the target and the input, or alternatively rendering to two separate rendertargets, flipping between both.

Likely the correct blending here would be to do the following:

```
float3 DstColor = lerp(SrcColor, DstColor, DstAlpha);
return float4(lerp(DstColor, SrcColor, SrcAlpha), clamp(DstAlpha + SrcAlpha, 0, 1.));
```

Which should correctly mix if there is something in the background, but keep the original color if there is nothing behind it.

**Comment by WizardCM** [comment] 2020-09-09 10:12
Just going through active issues, and have independently verified this issue.

![2020-09-09_20-11-30](https://user-images.githubusercontent.com/941350/92585754-b878be80-f2d8-11ea-98ae-918dcfbcb061.gif)

**Comment by skeletonbow** [comment] 2020-11-08 11:36
A related alpha issue perhaps?   #3709

**Comment by Xaymar** [comment] 2021-03-28 11:10
I was able to work-around this issue by adding some lines ahead of this part [in `obs-source.c`](https://github.com/obsproject/obs-studio/blob/a52012e8c586e1ff63bf7b79d8b27fb9af1cf31c/libobs/obs-source.c#L3634-L3640):
```
	gs_enable_blending(true);
	gs_blend_function(GS_BLEND_ONE, GS_BLEND_INVSRCALPHA);
	
	passes = gs_technique_begin(tech);
	for (i = 0; i < passes; i++) {
		gs_technique_begin_pass(tech, i);
		gs_draw_sprite(tex, 0, width, height);
		gs_technique_end_pass(tech);
	}
	gs_technique_end(tech);
```

This makes groups render correctly, but #4401 (scenes are also broken) is not affected by this. I have not looked at other broken behavior with this "fix" applied - but safe to say that this most likely breaks a lot more compared to before.

**Edit:** The only true fix for this I can see is to add another buffer to render to, which increases the render stages further. This issue is a weird one where the origin isn't clearly traceable...

**Comment by RytoEX** [comment] 2022-09-22 20:49
Is this still a problem with OBS Studio 28.0.2?

**Comment by PatTheMav** [comment] 2022-10-20 16:48
I was not able to reproduce this in OBS 28 - the appearance of the image source did not change with the scroll filter disabled or enabled.

**Comment by skeletonbow** [comment] 2022-11-03 22:28
I haven't tested OBS 28.x yet, but plan to do so very soon.  I'll have to re-test this issue to see if it is still present.

**Comment by rulzb** [comment] 2023-10-14 20:42
I've been using OBS 29.x and it seems that the problem is still there. I though that this was Twitch VOD problem, but it's also happening when I just record something directly into my computer.

**Comment by Fenrirthviti** [comment] 2024-10-14 21:23
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

**Closed by Fenrirthviti** 2024-10-14 21:23 UTC
Labels: Confirmed
