### ISSUE TITLE
Random "&" symbols within text

### ISSUE THREAD

**Issue by AyeItsHarry** [obsproject/obs-studio#10598] opened 2024-04-25 16:50 UTC
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/x3UhV4lJkvuJ0hlT

### Expected Behavior

The dock names to render correctly

### Current Behavior

They have "&" symbols in them
![Screenshot_20240425_174930](https://github.com/obsproject/obs-studio/assets/134330512/1769ca25-40db-420b-87ab-549dcf3f934a)

### Steps to Reproduce

1. Install flatpak
2. Install OBS from flathub
3. Open OBS

**Comment by derrod** [comment] 2024-04-25 16:52
Duplicate of #10367

**Closed by derrod** 2024-04-25 16:52 UTC
