### ISSUE TITLE
Drag & Drop Sources no longer working

### ISSUE THREAD

**Issue by earthmeLon** [obsproject/obs-studio#4945] opened 2021-06-25 18:03 UTC
### Operating System Info

ArchLinux 5.12.12-arch1-1

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/5wVAaaf0rZ9_GJoc

### Expected Behavior

When clicking and dragging a Source in the Sources list, I expect to be able to move it as well as add it to existing groups.  This was the behavior of OBS for the few years I've been using it.

### Current Behavior

Today, when I click and start dragging, it selects multiple sources.  In this example, I click "YETI Microphone" and attempt to drag it up into the Audio group.  Instead, it selects any Source under the cursor:

![example](https://user-images.githubusercontent.com/598108/123466376-1cd4e800-d5a4-11eb-9444-f06919f42c95.png)

### Steps to Reproduce

1.  Load a new Scene
2.  Create a Group
3.  Create an audio Source
4.  Attempt to drag and drop the new audio Source into the new Group
...

### Anything else we should know?

When making sure I could reproduce, I ran `obs` from the terminal to inspect output.  I don't see any errors I feel are relevant, but here are the errors/warnings:

```
$ obs | grep -e "error|warning"
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
```

**Comment by tytan652** [comment] 2021-06-25 18:13
It was disabled because of a bug. See #4488

**Comment by notr1ch** [comment] 2021-06-25 19:53
Duplicate of #4488.

**Closed by notr1ch** 2021-06-25 19:53 UTC
