### ISSUE TITLE
 Visual bug when turning on a folder with Media and Text GDI sources in

### ISSUE THREAD

**Issue by gravelfreeman** [obsproject/obs-studio#7877] opened 2022-11-30 18:47 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/CWJaJI4u2sKlRuC3

### Expected Behavior

When I turn on a folder Source with a Media Source and a Text GDI source with a transition the Media Source start playing and the Text GDI transition both at the same time.

### Current Behavior

When I turn on a folder Source with a Media Source and a Text GDI source with a transition it ignores the transition but instead it flashes on screen and then the transition work as it should.

### Steps to Reproduce

1. Create a Scene "Lower Thirds"
2. Inside that scene add a Folder source as a lower third bin and add Fade transition
3. Inside that folder add an alpha WebM file Media Source as a lower third background
4. Inside that folder add a Text GDI Source and write something as a lower third text and add Swipe transition
5. Create a Scene with anything you want and add the "Lower Thirds" scene
6. Toggle on your lower third folder (I use a Streamdeck but whatever works for you) you created in step 2

### Anything else we should know?

[Example clip showing the issue in a livestream](https://clips.twitch.tv/FriendlySwissShrimpFUNgineer-uoKL3kTpoxBcdXOu)

**Goal:** For lower thirds using multiple Text GDI with transitions inside a folder is very convenient to start many sources at the same time during a livestream.

**Comment by gxalpha** [comment] 2023-03-15 20:46
Duplicate of #4667

**Closed by gxalpha** 2023-03-15 20:46 UTC
