### ISSUE TITLE
Outdated Runtime

### ISSUE THREAD

**Issue by firefoxlover** [obsproject/obs-studio#9640] opened 2023-09-28 13:02 UTC
### Operating System Info

Other

### Other OS

Fedora

### OBS Studio Version

29.1.3

### OBS Studio Log URL

no logs

### Expected Behavior

OBS Studio flatpak uses the outdated runtime

```
Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   com.obsproject.Studio
```

### Current Behavior

uses this runtime

### Steps to Reproduce

flatpak update

**Comment by tytan652** [comment] 2023-09-28 13:03
Duplicate of #9542

**Closed by tytan652** 2023-09-28 13:03 UTC
