### ISSUE TITLE
Recording with multiple audio tracks, but the first track is always 1 second longer then the others. Which offsets footage in my editing software.

### ISSUE THREAD

**Issue by rexxbxnes** [obsproject/obs-studio#10303] opened 2024-02-28 03:39 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/O9mSnmvrjUEg2lhf

### Expected Behavior

The multiple audio tracks to be all the same length.

### Current Behavior

While using multiple audio tracks in OBS, to record, I always have the first track a frame longer then the others. It offsets my entire footage and makes editing Hell. 

### Steps to Reproduce

1. Record or clip footage
2. Upload it into a video editor
3. Have the first track always be 1 frame longer.
...

### Anything else we should know?

I've tried many different things to fix it, and nothing helped. I think it's just a bug.
![Screenshot 2024-02-25 014452](https://github.com/obsproject/obs-studio/assets/161549090/cb7986a2-0caa-495d-a6db-26bff6c22cc5)

**Comment by RytoEX** [comment] 2024-02-28 03:42
This seems like a duplicate of #4530, which was supposed to have been fixed in OBS Studio 30.1.0-beta1 by #9957.
cc @flaeri @WizardCM @derrod who participated on the GitHub Issue or PR.

**Comment by rexxbxnes** [comment] 2024-02-28 03:43
It isn’t fixed, I’m on 30.1.0-beta1

**Comment by RytoEX** [comment] 2024-02-28 03:43
> It isn’t fixed, I’m on 30.1.0-beta1

I understand that. I'm explaining for the benefit of others that this was _supposed_ to have been fixed.

**Comment by rexxbxnes** [comment] 2024-02-28 03:45
ohhh that makes more sense, okay did I fill everything out okay?

**Comment by RytoEX** [comment] 2024-02-28 03:46
> ohhh that makes more sense, okay did I fill everything out okay?

We will ask for more info if needed. Please wait for now for us to investigate.

**Comment by rexxbxnes** [comment] 2024-02-28 03:47
Ok, thanks for the update. :)

**Comment by RytoEX** [comment] 2024-02-28 03:48
```
win-capture-audio.dll
```
Please try to reproduce this without any third-party plugins.

**Comment by rexxbxnes** [comment] 2024-02-28 03:50
Ok, I will try. I actually just had a thought, because you guys now have
the “game capture (capture audio of window as well) I don’t need the window
capture. Do you know how to remove plugins?

**Comment by rexxbxnes** [comment] 2024-02-28 05:45
after removing the win-capture third party program, I still have the issue.
I wanted to test something though, so what I did was instead of adding
audio sources, I just added 3 audio tracks, kept the mic and desktop audio
as the default. Then hit record, and the issue still persists! I switched
to the beta as well

here is my log link https://obsproject.com/logs/3VhmmjleU4py2qEx

**Comment by RytoEX** [comment] 2024-02-28 18:02
> after removing the win-capture third party program, I still have the issue. I wanted to test something though, so what I did was instead of adding audio sources, I just added 3 audio tracks, kept the mic and desktop audio as the default. Then hit record, and the issue still persists! I switched to the beta as well here is my log link https://obsproject.com/logs/3VhmmjleU4py2qEx

This log doesn't show a recording attempt.

So far, we cannot reproduce this. Please provide an OBS log that has a recording session that produces a file that has offset audio tracks. If possible, please also provide the file that has the issue.

**Comment by rexxbxnes** [comment] 2024-02-28 22:52
2024-02-28 15-50-20.mp4
<https://drive.google.com/file/d/1fwoYQAMv_3PLNF6ZrYOJ0dVXwnJpWeTN/view?usp=drive_web>
https://obsproject.com/logs/pVMPR5fHbGlosmVU

here's that link and file.

**Comment by derrod** [comment] 2024-02-28 22:59
The file is not shared publicly, we cannot access it.

**Comment by rexxbxnes** [comment] 2024-02-28 23:01
Please try now.

**Comment by rexxbxnes** [comment] 2024-02-28 23:16
You believe it’s a premiere pro issue?

**Comment by RytoEX** [comment] 2024-02-28 23:17
Please also mention which editing software (name and version) that shows this problem. We don't see any issue in DaVinci Resolve 18.6 or Audacity 3.4.1.

**Comment by rexxbxnes** [comment] 2024-02-28 23:23
Premiere Pro 2024

**Comment by RytoEX** [comment] 2024-02-28 23:23
> You believe it’s a premiere pro issue?

At this point, yes. Please report the issue to them. This would not be the first time they had a bug.

**Comment by alinsavix** [comment] 2024-02-29 00:00
Yep, can confirm the example file shows the issue in Adobe Premiere 24.2.1. Interestingly, the same file does _not_ have an issue in Adobe Audition, because, y'know, Adobe is so consistent. But OP should be able to prove to themselves that all the tracks are the same length using Audition.

mediainfo also shows the exact same length for all three audio tracks: 9.472s.

So yeah, definitely Premiere bug.

**Comment by rexxbxnes** [comment] 2024-02-29 00:05
Ok, thanks for the clarification. All of your help as well. :)

**Comment by Fenrirthviti** [comment] 2024-02-29 05:07
Closing per above.

**Closed by Fenrirthviti** 2024-02-29 05:07 UTC
