### ISSUE TITLE
Resizing a media source after it ends, breaks its transformation.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#8610] opened 2023-03-31 22:07 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/VNhRq6U2AhFJsmUX

### Expected Behavior

To keep its transformation.

### Current Behavior

It goes to 90001, 90001 width/height when resizing after playback ends.

### Steps to Reproduce

1. Add Media Source video file.
2. Open Transformation
3. Resize it while the animation runs, and keep dragging till after it ends.

### Anything else we should know?

Video of said issue:
https://streamable.com/rzaxem

I also _suspect_ this may be causing some of the "invisible" sources people have. At least this is one of mine where resetting transformation brings it back.

**Comment by RytoEX** [comment] 2023-05-19 23:03
Duplicate of #7962

**Closed by RytoEX** 2023-05-19 23:03 UTC
