### ISSUE TITLE
Изображения не отображаются

### ISSUE THREAD

**Issue by 2ndChannel** [obsproject/obs-studio#4835] opened 2021-06-07 23:26 UTC
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/8enZn46zLGMMym3f

### Expected Behavior

The image in the scene should have been displayed

### Current Behavior

The image is not displayed if you go to the scene to which it was added via Studio Mode. This happens if the "Unload images when not showing" checkbox is checked in the image properties

### Steps to Reproduce

1. Add picture to scene
2. Set checkbox "Unload images when not showing" in image properties
3. Move to another scene
4. Activate Studio Mode
5. Return to a scene with an image using Studio Mode

**Comment by WizardCM** [comment] 2021-06-07 23:27
Duplicate of #4801

**Closed by WizardCM** 2021-06-07 23:27 UTC
