### ISSUE TITLE
Moving a filter up crashes OBS

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#2995] opened 2020-05-28 07:42 UTC
## Platform

Operating system and version: KUbuntu 20.04
OBS Studio version: 25.0.8

## Steps to Reproduce

1. Create a microphone source.
2. Add filters : Noise gate, noise cancellation, compression, limiter, gain
3. Move gain filter up to the top with the up arrow

## Expected Behavior

Gain filter arrives at the top after several clicks.

## Current Behavior
OBS crashes when Gain should move up Noise cancellation

## Additional information
This has been happening for several versions of OBS and with KUbuntu 18.04. With other sources ans filter combinations too. Usually I would work around by moving down the other filter (which never caused a crash), but this time it is really annoying as there are many of them. This happens even if in Studio mode and the scene containing the object is not active.

**Comment by Fenrirthviti** [comment] 2020-05-28 13:40
Please provide the crash log.

**Comment by ysalmon** [comment] 2020-06-07 10:44
Here it is.
[gdb.txt](https://github.com/obsproject/obs-studio/files/4741821/gdb.txt)

**Comment by WizardCM** [comment] 2020-08-26 02:28
Closing this as a duplicate of #2909 as it's caused by the same code path.

**Closed by WizardCM** 2020-08-26 02:28 UTC
