### ISSUE TITLE
PBS Causes Windows to Not Respond when Hitting Exit on the Program

### ISSUE THREAD

**Issue by Music-Done-Digitally** [obsproject/obs-studio#5868] opened 2022-01-25 22:33 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

https://obsproject.com/logs/tzJ-Hkw3QqvgbWAB

### OBS Studio Crash Log URL

OBS didn't detect a crash.

### Expected Behavior

I expected OBS to close normally instead of instead of showing Windows Not responding

### Current Behavior

Right now it's just crashing internally within Windows instead of OBS just closing the program

### Steps to Reproduce

1. Hit exit on the bottom right
2. Wait 5 seconds 
3. Click on the program a couple of times
4.  Then You Will see the Not Responding thing

**Comment by Fenrirthviti** [comment] 2022-01-25 22:42
We will likely need some kind of memory dump in order to isolate what the cause of this might be given how little information is available as reported. If you're not getting the "Oops! OBS has crashed" message, then it's actually more likely the issue is something outside of OBS itself is causing the hang, possibly your capture device.

Since this report isn't actionable as it is here, I'm going to go ahead and close it for now, and ask that you reach out to us in the #beta-testing channel in our [Discord](https://obsproject.com/discord)

**Closed by Fenrirthviti** 2022-01-25 22:42 UTC
