### ISSUE TITLE
Program and Preview screen locations are swapped in portrait/vertical layout

### ISSUE THREAD

**Issue by blockchaaain** [obsproject/obs-studio#7493] opened 2022-09-29 10:54 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

Prior to 28.0, when "Settings->General->Studio Mode->Enable portrait/vertical layout" was enabled, the Preview screen would appear above the Program screen.

### Current Behavior

As of 28.0, the Program screen appears above the Preview screen.

### Steps to Reproduce

1. Install OBS Studio 28.0, 28.0.1, or 28.0.2.
2. Enable the checkbox "Settings->General->Studio Mode->Enable portrait/vertical layout".
3. Show the "Controls" dock.
4. Enable Studio Mode on the Controls Dock.

Compare to previous versions.

### Anything else we should know?

This reverses the workflow of every user who has the vertical layout selected.

See #1695 and #6444.
Be aware that #6444 leaves out most of the functionality of #1695, including the ability for users to restore the layout to match prior versions.

**Comment by gxalpha** [comment] 2022-09-29 10:58
> I strongly suggest reverting this change in a minor version update as soon as possible.

@blockchaaain there are no plans to revert the change.

As described on the closed PR by Fenrir, the previous layout was straight up wrong.
Both PRs were discussed by the core team, and there was mutual agreement that a toggle isn’t needed here. I admit that it can be a bit annoying to get used to new behavior, but it was worth the tradeoff of not getting yet another toggle in the setting (they are really cluttered already and we’d like to avoid even more), with more code that would have to be maintained for many years to come.

Closing as this is working as intended.

**Closed by gxalpha** 2022-09-29 10:58 UTC

**Comment by blockchaaain** [comment] 2022-09-29 11:05
I appreciate that there was internal discussion.

Public discussion did not claim that the previous layout was straight up wrong, and it is quite clearly subjective.
There is not a correct layout. OBS is as much an industry trendsetter as other software packages.

The third alternative not mentioned here would be to make no change.

> > I strongly suggest reverting this change in a minor version update as soon as possible.
> 
> @blockchaaain there are no plans to revert the change.
> 
> As described on the closed PR by Fenrir, the previous layout was straight up wrong. Both PRs were discussed by the core team, and there was mutual agreement that a toggle isn’t needed here. I admit that it can be a bit annoying to get used to new behavior, but it was worth the tradeoff of not getting yet another toggle in the setting (they are really cluttered already and we’d like to avoid even more), with more code that would have to be maintained for many years to come.
> 
> Closing as this is working as intended.

**Comment by gxalpha** [comment] 2022-09-29 11:14
> I appreciate that there was internal discussion.
Public discussion did not claim that the previous layout was straight up wrong

We’re working on improving how we document results of such discussions, here it indeed wasn’t optimal.

> OBS is as much an industry trendsetter as other software packages

As much as we’d love it to be, in many cases it really isn’t. Program being on top is the standard in the industry, and OBS having it on the bottom didn’t change this in the last years.

> The third alternative not mentioned here would be to make no change.
There is then little tradeoff to consider. No clutter and no change of expectations.

There’s still the tradeoff of having non-standard behavior.

**Comment by Fenrirthviti** [comment] 2022-09-29 18:50
Every change, no matter how minor, will affect someone's workflow somewhere. Even if it's a bug fix. See: Spacebar Heating XKCD. Please be mindful that these changes aren't done lightly, and we need to consider the larger userbase, years and years of industry practice, and balancing the customization of the UI when it comes to both end-user supportability and code sustainability. Another checkbox may not feel like clutter to you, but to us it's another point of failure. Another point we have to check while providing support to end users. Another consideration we have to take in to account if we want to make changes to Studio Mode in the future. It adds debt to the project, which is something we're being a lot more conscious of in the past year or so. It's not feasible or sustainable for us to support every single edge use case anymore. The project is simply too big with too many users for that to be viable.

We understand that some people might be upset when we make these kinds of decisions, but coming at us with an angry attitude, posting across all our platforms, and demanding change for your specific workflow without providing a wider context on why this would benefit *all* users of the program isn't the best way to go about it. Frankly, it comes off as entitled and selfish, though I understand that is certainly not your intent. If you feel there is a real use case for allowing this change, please do submit it as a suggestion on our [Ideas page](https://ideas.obsproject.com/), or comment on an existing post requesting this. Get people to upvote it, and show that it's a wider issue that affects multiple people and that multiple people want to see. Don't just go around posting "I don't like this" everywhere. Make an actual case for why. As it stands now, we have two very loud users shouting at us to change something. 

I only ask that you be respectful and understanding that there might be more to the discussion and factors, even public ones, that you aren't seeing. We welcome our users questioning us, we welcome being challenged, but simply getting angry and making demands isn't the way we prefer it happens. Our Discord is always open for these kinds of discussions, and we have an entire channel set up (#ideas-suggestions) to talk about changes for OBS.

Lastly, I do want to point out that one of the best things about OBS is that it's open source. It's easy, trivial even with our new and effectively automated build scripts available for anyone to use locally, to simply revert the one-line change and have a local version without this change if it is that important to you and your workflows. This is not a dismissal, this is an option that is available to you.

I look forward to keeping up with the discussion as it progresses.

**Comment by jlt525** [comment] 2022-09-29 22:31
Thank you for the detailed response.
First of all, I would like to apologise that I came off as loud and entitled. I tend to be frank in writing and my intent was not conveyed properly. My intention was only to add "my 2 cents" to the conversation.

Ultimately, I think people are going to suck it up and get used to the change even if it is frustrating that user customisation (for those who don't want to build the program themselves) is being sacrificed here. Though, the fact that the change was made with a major release does somewhat excuse the "breaking change" to workflows.
Also, I think some sort of documentation of the internal discussions would have helped a lot here. A comment on the pull request that got merged to master (#6444) saying that there _was_ an internal discussion and providing the reasoning behind the lack of a toggle (code debt and another possible point of failure) would have cleared things up for me significantly.

Lastly, I already added a toggle in my local version for switching preview and program around before I commented on this issue. That's why I mentioned I was going to open a pull request before I saw the response to this issue.

Anyway, I think I've said my piece and I don't expect there's going to be much more discussion regarding this. Just wanted to clear the air.

**Comment by RytoEX** [comment] 2022-09-29 23:25
> A comment on the pull request that got merged to master (#6444) saying that there _was_ an internal discussion and providing the reasoning behind the lack of a toggle (code debt and another possible point of failure) would have cleared things up for me significantly.

For what it's worth, this is something that we've been working on improving over the past few months. You may have seen a few comments on PRs or Issues that said, "per off-thread discussion" or "after some discussion internally" or something similar. We will continue to try to be mindful of this and to try to provide at least some kind of summary or commentary in such cases. Thank you for your feedback and your understanding.

**Comment by blockchaaain** [comment] 2022-09-30 13:25
I resign to accepting the change, and people will get used to it.

But I still do not understand the equivalence of "affect someone's workflow" and "reverse everyone's workflow".
The spacebar heater comic is specifically about unusual/niche usage, while this issue is about common and intended functionality frequently encountered by a large portion of users.
It feels incredibly reductive to even make the comparison.

I sincerely believe now that it was not treated lightly, but the available communications still come off as condescending to users.

This is not part of my workflow and I am not personally affected by the change. I am only concerned about the process.
