### ISSUE TITLE
Game Capture will stop capturing after activating a source transition across multiple scenes

### ISSUE THREAD

**Issue by Jazzotter** [obsproject/obs-studio#6713] opened 2022-07-11 09:43 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/clZj2T7xQ1vZnU77

### Expected Behavior

I am performing a macro using a stream deck that toggles the visibility of a game capture, in this case Vseeface, source across multiple scenes, so the source will toggle no matter which scene I'm in. There is a stinger transition that plays when visibility is toggled. Activating the macro should toggle the visibility of the source in each scene simultaneously(even though only one is visible on the screen), and play the transition without issue.

### Current Behavior

The sources will toggle off fine, but when toggling the sources back on, the capture will stop in one or more scenes upon switching to them. Sometimes the capture won't come up at all in the immediate scene, sometimes the capture will come up briefly and then stop, sometimes switching to another scene will cause that capture to stop, which can be seen in the log provided. This issue is typically "fixed" by switching scenes until a capture hooks, then the rest usually hook too.

### Steps to Reproduce

1. Activate a macro to toggle the visibility of the same game capture source(Vseeface) across multiple scenes, with a stinger transition
2. Activate the macro again to transition the sources to a visible state
3. Either witness the game capture stop in the immediate scene or transition to a different scene with the same source
...

**Comment by Fenrirthviti** [comment] 2022-07-11 17:15
Likely a dupe of https://github.com/obsproject/obs-studio/issues/5291

**Comment by Fenrirthviti** [comment] 2023-01-27 20:02
Duplicate of #5921

**Closed by Fenrirthviti** 2023-01-27 20:02 UTC
