### ISSUE TITLE
obs-ndi plugin does not work anymore with v28

### ISSUE THREAD

**Issue by lassos** [obsproject/obs-studio#7318] opened 2022-09-07 09:32 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

11:30:14.748: Skipping module '../../obs-plugins/64bit/obs-ndi.dll' due to possible import conflicts

### Expected Behavior

obs-ndi plugin does working

### Current Behavior

obs-ndi plugin does not work anymore with v28

### Steps to Reproduce

1.Install ndi plugin
2. starting obs
3.
...

**Comment by WizardCM** [comment] 2022-09-07 09:34
Duplicate of #7281

**Closed by WizardCM** 2022-09-07 09:34 UTC
