### ISSUE TITLE
Multi GPU NVENC Error on start recording/streaming

### ISSUE THREAD

**Issue by surcarance** [obsproject/obs-studio#4816] opened 2021-06-05 19:34 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/7QTbhSxGKtk89qHI

### OBS Studio Crash Log URL

https://obsproject.com/logs/gfiC-YOaG3EeveKQ

### Expected Behavior

Expected NVENC Encoding to work correctly on secondary GPU as did in 26.1.2

### Current Behavior

When Secondary GPU is selected for NVENC Encoding on streaming or recording,  (Settings -> Output -> Streaming/Recording -> GPU : 1) results in "Failed to open NVENC Codec: Generic Error in an external Library" "Set this back to 0 and try again"

### Steps to Reproduce

1. Settings -> Output -> Streaming -> GPU : 1
2. Start Streaming/recording
2.
3.
...

### Anything else we should know?

If I select the GPU back to the Primary ( 1080ti ), AKA 0,  Recording and Streaming work just fine.  It is only when I am trying to offload some of the work and still have a use for my Secondary GPU ( 780ti ) as the encoder when streaming/recording that I see this issue. 

I have only seen this issue with 27.0.0.  Version 26.1.2 worked fine with this configuration.  Looking at the NVidea Matrix, both my GPU's are NVENC capable. 

Nvidea Game Ready Driver 466.63

**Comment by notr1ch** [comment] 2021-06-05 19:39
Sounds like a duplicate of #4785.

Note that you are actually causing additional load by trying to offload it as the textures must be passed back and forth across the PCI-e bus instead of staying on the GPU. NVENC is a dedicated circuit and does not affect GPU performance when the CUDA features are disabled.

**Closed by notr1ch** 2021-06-05 19:39 UTC
