### ISSUE TITLE
mac microphone mode sound issue

### ISSUE THREAD

**Issue by kalysaar** [obsproject/obs-studio#8904] opened 2023-05-14 04:33 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F636682784156549152%2F1107142900661354526%2F2023-05-14_12-02-28.txt

### Expected Behavior

(I'm a Korean user.using a translator)
Use the microphone's noise filter as the microphone mode, and put the necessary elements into the microphone filter to broadcast

### Current Behavior

(I'm a Korean user.using a translator)

Occasionally, the micro mode of the Mac on the microphone connected to the OBS causes the sound to break.

### Steps to Reproduce

1. Connect a USB-type microphone to a MacBook through a USB-C hub and run obs
2. Select the microphone mode in the control center
3. The microphone's voice is broken when broadcasting
4. Test the usb port connected to the microphone over and over again for short-term resolution
...

### Anything else we should know?

I tried to solve this problem in discord, but it failed.
https://discord.com/channels/348973006581923840/636682784156549152/1107143819729842208

We did three tests. I re-run obs for each test.

1. Turn off all filters and activate mic mode only -> Problem occurs
2. Disable all filters and mic mode -> Resolved
3. Filter activation except VST, mic mode disabled -> Resolved

Finally, I think mic mode is the problem.. 
Or I'm not sure if it's because the usb hub connected to the microphone is running out of power.
When power supply is delivered to the MacBook through the usb hub, and when power supply is delivered directly to the MacBook and the usb hub receives it through the MacBook, problems occur and fail.

Or does mic mode have excessive CPU usage?

**Comment by rimelek** [comment] 2023-12-27 15:44
I believe I have this problem too. I actually had it always since I started to use the voice isolation feature. I thought it was a macOS issue, but today I found some clues.

**I start OBS while the voice isolation feature is on:**

- if my active Microphone is the USB mic, the audio is broken.
- Then I change it to the built-in "Macbook Air Microphone", and the audio works with that.
- Then I change it back to the USB mic again, and it works with that as well.

I also tried to start OBS while the selected mic was the built-in mic.

- The audio worked, but broke when I switched to the USB mic.
- So I switched to the built-in mic and back to the USB mic and it worked again.

**I start OBS while the voice isolation feature is off:**

- The audio works with my USB mic
- I enable voice isolation and the audio still works

So it looks loke it it works when I enbale voice isolation after starting to use the USB mic, but when I start OBS when voice isolation is already enabled, the audio never works the first time, but it works when I select the USB mic the second time.

My OBS version is "29.1.2" on MacBook Air with the M1 chip and the macOS version is Sonoma 14.2.1. The USB microphone is Trust GXT 255+ .

I can handle it this way, but sometimes I forget to test the audio and record 30 minutes with the wrong auido. I know, my mistake :)

**Comment by ChrisRiddell** [comment] 2023-12-29 10:47
I'm seeing the same thing and confirmed the work arounds that @rimelek has said.

**Comment by rimelek** [comment] 2024-03-15 16:10
it seems to be fixed in OBS 30.1.0.  Voice isolation is set, I start OBS, don't touch the microphone settings, start a recording and there is no audio distrortion with my USB mic. In case that matters, I removed the old OBS app (because someone in another issue recommended it related to the virtual camera), removed it from trash as well, and installed OBS 30.1.0.  My current macOS version is Sonoma 14.4. 

Can you confirm it @kalysaar, @ChrisRiddell ?

**Comment by RytoEX** [comment] 2024-04-16 20:39
Per the above, this sounds like a specific issue with macOS Voice Isolation on USB microphones. that may be resolved with either an OBS update or a macOS update. Realistically, this sounds like something that should be reported to Apple via Feedback Assistant while experiencing the issue. If someone does that, feel free to post the Feedback ID here.

**Closed by RytoEX** 2024-04-16 20:39 UTC
