### ISSUE TITLE
[BUG] VLC Video Source > Add Path/URL to Playlist > displays incorrectly in a Scene

### ISSUE THREAD

**Issue by chrishobcroft** [obsproject/obs-studio#2933] opened 2020-05-14 11:20 UTC
## Platform

Operating system and version: `Ubuntu Linux 20.04 LTS Desktop`
OBS Studio version: `25.0.8`

## Expected Behavior

I expect that when adding a @videolan "VLC Video Source" source, with a pre-defined frame size, it will display that source in OBS at the pre-defined frame size.

## Current Behavior

Currently, when adding a stream URL source with `256x144` framesize, OBS decides to transform the feed to `256x162` :frowning_face: :

![image](https://user-images.githubusercontent.com/2212651/81925047-96f31900-95fd-11ea-8d45-fee02888d19e.png)

## Steps to Reproduce

1. Run OBS as defined in Platform above:

![Screenshot from 2020-05-14 16-11-55](https://user-images.githubusercontent.com/2212651/81925115-b427e780-95fd-11ea-8c2b-761622c6212a.png)

2. Add "VLC Video Source"

![Screenshot from 2020-05-14 16-13-07](https://user-images.githubusercontent.com/2212651/81925246-e2a5c280-95fd-11ea-972b-6c543609417e.png)

3. Select the **+** and select "Add Path/URL":

Enter the URL of @videoDAC [community test-source `http://52.29.226.43:8935/stream/hello_world.m3u8`](http://52.29.226.43:8935/stream/hello_world.m3u8), and click OK, and OK again:

![Screenshot from 2020-05-14 16-20-49](https://user-images.githubusercontent.com/2212651/81925981-e71eab00-95fe-11ea-9b30-7ce5b6631907.png)

4. Run `curl http://52.29.226.43:8935/stream/hello_world.m3u8` to see:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=**256x144**
hello_world/source.m3u8
```

**This video source is `256x144`.**

5. Select to "Edit Transform" of the "VLC Video Source"

**_Unexpected Behaviour!_**: The source is being displayed with a transform of `256x162`

![Screenshot from 2020-05-14 16-04-39](https://user-images.githubusercontent.com/2212651/81926070-0c131e00-95ff-11ea-95a6-efd64484a873.png)

## Expected Behaviour

I expected OBS to display the VLC Video Source in the same format / framesize as the source = `256x144`

## Additional Information

@videoDAC is an independent open-source project as part of @livepeer community, and @ethereum, @obsproject, @videolan projects.

The @videoDAC [community test-source `http://52.29.226.43:8935/stream/hello_world.m3u8`](http://52.29.226.43:8935/stream/hello_world.m3u8) is served using a [`simple-streaming-server`](https://github.com/videoDAC/simple-streaming-server).

**Comment by dodgepong** [comment] 2020-05-14 13:12
How does VLC itself show the stream?

What happens if you use a media source instead?

**Comment by criticaltv** [comment] 2020-05-14 15:34
Media Source works fine.

VLC itself shows in 256x144

The test source is up "permanently", you can see you yourself: http://52.29.226.43:8935/stream/hello_world.m3u8

**Comment by WizardCM** [comment] 2020-09-09 11:21
I have verified this using 26 RC1 on Windows 10 and the provided m3u8, VLC Source loads with the incorrect 162px height.

![image](https://user-images.githubusercontent.com/941350/92591641-a0f20380-f2e1-11ea-8a85-cc13eea7adbe.png)

**Comment by PeterHindes** [comment] 2020-09-20 07:05
Is there any fix for this yet? I'm trying to use srt to stream from my friends obs to mine, but it is all blurry, and I cant get mediaSource to work with srt. I have to use ffplay and that is a bit janky.

**Comment by evilscientress** [comment] 2020-10-01 01:00
I have the same issue as well with a different stream. The stream has a resolution o 1920x1080 but the VLC Source renders it as 1920x1090 resulting in a blurry image. in VLC itself the video is displayed correctly, but what I noticed is that in the Codec Information window, the video stream has a buffer size of 1920x1088.

I think this might be related to this Issue which apparently was never fixed:
https://obsproject.com/mantis/view.php?id=860

**Comment by pmcgaley** [comment] 2021-09-17 22:49
I believe I have a fix for this, but the test source above seems to have changed to 256x256, which doesn't exhibit the issue (being multiples of 32 in each dimension). I've tried setting up an RTMP server locally and streaming similar test content from ffmpeg, but I haven't been able to reproduce the issue so far. Is there a current test source that exhibits the problem that I can use to test?

**Comment by mycroftcanner** [comment] 2022-02-03 16:16
@pmcgaley thanks for the aspect ratio fix... I just copied your version and it worked great! Many thanks again.

Please find attached a test source that are displayed with those grey artefacts.

https://user-images.githubusercontent.com/55385694/152382228-1734f282-4ef9-43b3-add4-b71f59a494f5.mov

**Comment by pmcgaley** [comment] 2022-02-03 16:21
Great, thanks for the feedback and test source! Might give me the impetus I need to finally open that PR :-)

**Comment by mycroftcanner** [comment] 2022-02-03 16:21
![Screenshot 2022-02-03 at 16 20 57](https://user-images.githubusercontent.com/55385694/152383547-06783bad-a430-4d0c-a54d-704a739aef94.png)

**Comment by pmcgaley** [comment] 2022-02-03 16:30
@mycroftcanner is that the output from my fork? If so, it confirms the issues are unrelated and your test source is probably more relevant to https://github.com/obsproject/obs-studio/issues/5252 - I'm unlikely to get around to investigating that one any time soon - I'm actually not a contributor to this project - just a passer-by who ran into the issue and went digging :-)

**Comment by mycroftcanner** [comment] 2022-02-03 17:22
@pmcgaley I'll take a look at #5252... the thing is that all the videos that had the aspect ratio glitch are all affected by the grey artefacts.

**Comment by pmcgaley** [comment] 2022-02-03 17:42
Are they all from phones? I have a feeling it's to with with the way certain phones are encoding the video - thought initially it might be only HEVC/H.265 but now not convinced about that either. But a lot of videos from phones are portrait, so it tends to be the same ones showing both issues, rather than being actually related issues if that makes sense. And completely separate fixes required most likely unfortunately.

**Comment by mycroftcanner** [comment] 2022-02-19 17:04
Another thing is that most of the video that have these glitches were video I edited in the Photos app.

**Comment by mycroftcanner** [comment] 2022-02-19 17:29
yes they are all from phones.

**Comment by pmcgaley** [comment] 2022-04-30 15:56
Months later... I have finally confirmed that the fix I mentioned above *does not* fix this issue - all the data coming from libvlc for streamed video is zeroes at the time we need it - there may be a way of waiting for the stream to start and then getting the correct dimensions, but I'm going to update the PR to say it doesn't fix this so it can be considered separately and hopefully can finally be merged in at some point.

**Comment by pmcgaley** [comment] 2022-04-30 16:10
since the original test source is no longer demonstrating the issue (dimensions have changed), here are steps to reproduce locally

Generate a test video in an MPEG2 transport stream with:
`ffmpeg -f lavfi -i testsrc=duration=10:size=256x144:rate=30 testsrc.ts`

Run a HTTP server locally, e.g.
`python3 -m http.server --cgi 8080`

Add a VLC Video Source and add a URL to the local server, `http://localhost:8080/testsrc.ts`. Transform should show 256x144 but for me it's 256x160, which is the buffer size coming from libvlc

**Comment by Fenrirthviti** [comment] 2022-09-28 19:24
Tested in 28, it does look like this is still an issue, however as the stream appears to have changed sizes I will updated with the current results, using http://52.29.226.43:8935/stream/hello_world.m3u8:

In VLC direct: Stream renders as 256x256
In media source in OBS: Stream renders as 256x256
In VLC source in OBS: Stream renders as 256x258

We aren't sure why this is happening, but just confirming that this is still an issue. This might be a bug in libvlc that is being handled in their UI, but it's unclear at this time.

**Comment by Fenrirthviti** [comment] 2024-10-14 21:24
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

**Closed by Fenrirthviti** 2024-10-14 21:24 UTC
Labels: Confirmed
