### ISSUE TITLE
The "aspect-ratio" media feature does not work on CEF. 

### ISSUE THREAD

**Issue by Lait-au-Cafe** [obsproject/obs-studio#8456] opened 2023-03-12 15:30 UTC
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/5GN9FTS8LisyindM

### Expected Behavior

When a web page, which contains media query with "aspect-ratio" media feature (such as `@media (min-aspect-ratio: 0) { ... }`) in its CSS, is read and rendered by Browser Source, it reflects its media query and changes its styles. 

### Current Behavior

It always ignores styles inside media query. 

### Steps to Reproduce

1. Prepare a html file, whose content is shown below. 
```
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>aspect-ratio test</title>
    <style>
        .box {
            width: 100px;
            height: 100px;
            background-color: red;
        }
        @media (min-aspect-ratio: 0) {
            .box {
                background-color: green;
            }
        }
    </style>
</head>
<body>
    <div class="box"></div>
</body>
```

2. Capture this file as Browser Source. 
![image](https://user-images.githubusercontent.com/29175977/224554554-e37a6ae6-908a-414c-8583-98a1c28ef93c.png)

3. Because `min-aspect-ratio: 0` has always to be satisfied, a green square should be displayed. However, it ignores media query and displays red one. The below is comparison between Chrome Browser (left) and a Devtool of OBS (right). 

![image](https://user-images.githubusercontent.com/29175977/224554677-8d6bbc5a-3fea-44d8-931b-460833036023.png)

**Comment by mihawk90** [comment] 2023-03-12 23:14
Can also confirm on Fedora.

For sanity check I also tested it on Vivaldi (Chromium 110) and it worked fine.

It should be working [since Chromium 4](https://caniuse.com/mdn-css_at-rules_media_aspect-ratio).

**Comment by gxalpha** [comment] 2023-09-04 13:21
Closing as per the comment above this is a feature request, not a bug.

**Closed by gxalpha** 2023-09-04 13:21 UTC
