### ISSUE TITLE
Linux compile fails with CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):   add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

### ISSUE THREAD

**Issue by dr431** [obsproject/obs-studio#8605] opened 2023-03-31 18:20 UTC
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):   add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.   CMake Error at deps/media-playback/CMakeLists.txt:6 (add_library):   add_library cannot create ALIAS target "OBS::media-playback" because target   "media-playback" does not already exist.   CMake Error at deps/media-playback/CMakeLists.txt:8 (target_sources):   Cannot specify sources for target "media-playback" which is not built by   this project.   CMake Error at deps/media-playback/CMakeLists.txt:20 (target_include_directories):   Cannot specify include directories for target "media-playback" which is not   built by this project.   CMake Error at deps/media-playback/CMakeLists.txt:21 (target_compile_options):   Cannot specify compile options for target "media-playback" which is not   built by this project.   CMake Error at deps/media-playback/CMakeLists.txt:22 (target_compile_definitions):   Cannot specify compile definitions for target "media-playback" which is not   built by this project.   CMake Error at deps/media-playback/CMakeLists.txt:24 (target_link_libraries):   Cannot specify link libraries for target "media-playback" which is not   built by this project.   -- Configuring incomplete, errors occurred! See also "/home/obs/obs-studio/build/CMakeFiles/CMakeOutput.log".   + ERROR during build step: configure build root@raspi:/home/obs/obs-studio/CI# CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):   add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

### Expected Behavior

Successful compile

### Current Behavior

CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):
  add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

CMake Error at deps/media-playback/CMakeLists.txt:6 (add_library):
  add_library cannot create ALIAS target "OBS::media-playback" because target
  "media-playback" does not already exist.

CMake Error at deps/media-playback/CMakeLists.txt:8 (target_sources):
  Cannot specify sources for target "media-playback" which is not built by
  this project.

CMake Error at deps/media-playback/CMakeLists.txt:20 (target_include_directories):
  Cannot specify include directories for target "media-playback" which is not
  built by this project.

CMake Error at deps/media-playback/CMakeLists.txt:21 (target_compile_options):
  Cannot specify compile options for target "media-playback" which is not
  built by this project.

CMake Error at deps/media-playback/CMakeLists.txt:22 (target_compile_definitions):
  Cannot specify compile definitions for target "media-playback" which is not
  built by this project.

CMake Error at deps/media-playback/CMakeLists.txt:24 (target_link_libraries):
  Cannot specify link libraries for target "media-playback" which is not
  built by this project.

-- Configuring incomplete, errors occurred!
See also "/home/obs/obs-studio/build/CMakeFiles/CMakeOutput.log".
  + ERROR during build step: configure build
root@raspi:/home/obs/obs-studio/CI# CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):
  add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.
CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):
  add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

CMake Error at deps/media-playback/CMakeLists.txt:6 (add_library):
  add_library cannot create ALIAS target "OBS::media-playback" because target
  "media-playback" does not already exist.

CMake Error at deps/media-playback/CMakeLists.txt:8 (target_sources):
  Cannot specify sources for target "media-playback" which is not built by
  this project.

CMake Error at deps/media-playback/CMakeLists.txt:20 (target_include_directories):
  Cannot specify include directories for target "media-playback" which is not
  built by this project.

CMake Error at deps/media-playback/CMakeLists.txt:21 (target_compile_options):
  Cannot specify compile options for target "media-playback" which is not
^Cadd_library INTERFACE library may not be used with EXCLUDE_FROM_ALL./CMakeLists.txt:5 (add_library):
root@raspi:/home/obs/obs-studio/CI# CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):
  add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

CMake Error at deps/media-playback/CMakeLists.txt:6 (add_library):
  add_library cannot create ALIAS target "OBS::media-playback" because target
  "media-playback" does not already exist.

CMake Error at deps/media-playback/CMakeLists.txt:8 (target_sources):
  Cannot specify sources for target "media-playback" which is not built by
  this project.

CMake Error at deps/media-playback/CMakeLists.txt:20 (target_include_directories):
  Cannot specify include directories for target "media-playback" which is not
  built by this project.

CMake Error at deps/media-playback/CMakeLists.txt:21 (target_compile_options):
  Cannot specify compile options for target "media-playback" which is not
  built by this project.

root@raspi:/home/obs/obs-studio/CI# not be used with EXCLUDE_FROM_ALL./CMakeLists.txt:5 (add_library):

### Steps to Reproduce

1. git clone --recursive https://github.com/obsproject/obs-studio.git
2. cd obs-studio/CI
3. ./build-linux.sh

### Anything else we should know?

 cmake version 3.18.4

**Comment by RytoEX** [comment] 2023-03-31 21:57
Duplicate of #8595

**Closed by RytoEX** 2023-03-31 21:57 UTC
