### ISSUE TITLE
Service docks are spawned floating when OBS is launched with --silent

### ISSUE THREAD

**Issue by NotAmiru** [obsproject/obs-studio#10915] opened 2024-06-23 18:50 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/yUfX9L7vOkJggCO4

### Expected Behavior

Currently have launch arguments in order to launch OBS with Replay Buffer and minimise to system tray  

### Current Behavior

when this occurs OBS launches twitch docks seperately instead of in the program as shown in image
![Screenshot 2024-06-23 183940](https://github.com/obsproject/obs-studio/assets/137094811/58abb5bb-7803-479a-9db7-e8628ed723dc)

### Steps to Reproduce

1. make sure OBS is closed
2. make a shortcut and place it into shell:startup
3. paste in "--disable-shutdown-check --silent --startreplaybuffer" as launch arguments
4. either restart system or open OBS and see if the error occurs with both or just one

### Anything else we should know?

This part should be in feature request but can we get a launch on startup as well as activate replay buffer on startup too mainly for people to tend to use OBS for a clipping software more than a streaming/recording software

**Comment by derrod** [comment] 2024-06-23 18:58
Duplicate of #8614

**Closed by derrod** 2024-06-23 18:58 UTC
