### ISSUE TITLE
[BUG] FFMPEG VAAPI rate control setting w/o effect

### ISSUE THREAD

**Issue by schirmeier** [obsproject/obs-studio#2741] opened 2020-04-17 14:09 UTC
## Platform
Operating system and version: Ubuntu 20.04
OBS Studio version: Ubuntu package obs-studio 25.0.3+dfsg1-2
EDIT: obs-studio 25.0.4-0obsproject3~focal (from the PPA) behaves identically

## Expected Behavior
When using the FFMPEG VAAPI encoder, setting "Rate Control" to CQP (or VBR) should affect the encoder behavior, reflected in the log by "rate_control: CQP" (respectively "rate_control: VBR").

## Current Behavior
info: ---------------------------------
info: [FFMPEG VAAPI encoder: 'streaming_h264'] settings:
        device:       /dev/dri/renderD128
        rate_control: **CBR**
        profile:      578
        level:        40
        qp:           0
        bitrate:      5000
        maxrate:      5000
        keyint:       60
        width:        1920
        height:       1080
        b-frames:     0

info: ---------------------------------
info: [FFmpeg aac encoder: 'Track1'] bitrate: 160, channels: 2, channel_layout: 3

info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/hsc/2020-04-17 16-05-21.mkv'...
[matroska @ 0x5595ad1423c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[matroska @ 0x5595ad1423c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

## Steps to Reproduce

1. Settings: Output / Output Mode "Advanced"; Streaming / Encoder "FFMPEG VAAPI"; Rate Control "CQP"
2. Start recording.

## Additional information
CPU, GPU: Intel(R) Core(TM) i7-6700HQ CPU, Intel Corporation HD Graphics 530
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1
intel-media-va-driver-non-free: 20.1.1+ds1-1

**Comment by Gol-D-Ace** [comment] 2020-04-17 14:20
Please note that we do not support the Debian package because it wasn't made by us.

Please use the PPA.
(Uninstall obs-plugins, libsobs0 and obs-studio before trying to reinstall from the PPA to avoid conflicts.)

Also see: https://bugs.launchpad.net/ubuntu/+source/obs-studio/+bug/1873400

**Comment by schirmeier** [comment] 2020-04-17 14:35
I know the related Ubuntu bug. I filed it.

**Comment by schirmeier** [comment] 2020-04-17 14:52
The issue is reproducible with obs-studio 25.0.4-0obsproject3~focal from the Ubuntu PPA.

**Comment by kkartaltepe** [comment] 2020-04-17 14:57
I cannot reproduce on master. Please provide the full log.

**Comment by schirmeier** [comment] 2020-04-17 15:04
obs-studio 25.0.4-0obsproject3~focal started up, settings -> checked that Rate Control is set to CQP, started recording, waited, stopped recording, exit.
[obs.log](https://github.com/obsproject/obs-studio/files/4493681/obs.log)

**Comment by dionney** [comment] 2020-04-17 15:37
When I try to stream to Twitch with x264 or FFmepg VAAPI, CBR is forced if the following is set:
[x] Enforce streaming service encoder settings

Please verify if it is the case for you.

**Comment by schirmeier** [comment] 2020-04-17 15:50
Good catch! When I disable this checkbox, I see "rate_control: CQP" in the log, both when streaming to YT and recording.

However, I'd expect this checkbox to have no effect on recording while not streaming -- which I used as a test case. With Recording -> Encoder set to "(use stream encoder)", CBR is still enforced when I only record.

**Comment by Gol-D-Ace** [comment] 2020-04-17 15:56
It's the same encoder with the same settings internally.
Just different output (to file)
This was made like this to avoid spawning 2 different encoders (I assume) when not using hardware encoding.

I agree it's not ideally solved UI wise.

Closing this issue because this isn't a "bug".

**Closed by Gol-D-Ace** 2020-04-17 15:56 UTC
