### ISSUE TITLE
Some VSTs may store large amounts of data in OBS' scene JSON file

### ISSUE THREAD

**Issue by firebelley** [obsproject/obs-studio#6730] opened 2022-07-13 21:25 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/4GsNIItA2WQ_-W9S

### Expected Behavior

Scene configuration files at `%AppData%\Roaming\obs-studio\basic\scenes` should be a reasonable size.

### Current Behavior

OBS was lagging a lot whenever modifying settings and filters even when not recording or streaming. Uninstalling and reinstalling didn't fix the issue. Deleting the scenes folder in `%appdata%` fixed the issue and to my surprise, I saw my scene JSON file was **over 500 MB**. I only have 4 scenes and 1-3 sources in each scene. I suspect OBS parses this when opening and modifying settings which is causing the interface to lag or hang for a few seconds.

Unfortunately I cannot upload the JSON file here because of size limits. I've uploaded it to my personal OneDrive account, please let me know if there's a more appropriate place I can upload it: https://1drv.ms/u/s!Aq0xcjvcGxyAjb4mOlK8gQyQItf_nA?e=JUJ7dx

### Steps to Reproduce

I do not know how to reproduce this. I am hoping the JSON file I provided has some clues.

**Comment by Fenrirthviti** [comment] 2022-07-13 21:57
Looks like you found the issue before we had a chance to reply, some VSTs will store obnoxious amounts of data like that. I don't recall if that's a fault of the plugin doing something wrong, or a missing method on our end where we should be shunting that data somewhere else. This isn't the first time this has come up, but I can't find any other issues related to it right now, so we can leave this open until a definitive answer is reached.

**Comment by alinsavix** [comment] 2022-07-13 22:19
My recollection, from when I had to deal with this a couple years back, is that OBS is basically responsible for storing a configuration blob from the VST, and giving it back to the VST the next time it is loaded (so that a DAW can have different VST configs for each project, or even each instance).

I suppose OBS could store those configs somewhere other than the scene collection json (so that it can load them as a blob instead of sending them through the json parser), but then you'd end up with the problem that the scene collection json would no longer contain the entire configuration for the scenes.

So OBS may just be between a rock and a hard place on being able to do anything better here.

**Comment by RytoEX** [comment] 2022-07-14 00:25
> Looks like you found the issue before we had a chance to reply, some VSTs will store obnoxious amounts of data like that. I don't recall if that's a fault of the plugin doing something wrong, or a missing method on our end where we should be shunting that data somewhere else. This isn't the first time this has come up, but I can't find any other issues related to it right now, so we can leave this open until a definitive answer is reached.

You're thinking of #6730, which had the exact same problem with the exact same VST.
> On the other profile I just removed the reacomp vst plugin from mic settings and it shrunk from ~250mb to 37kb.
> [...]
> Youlean Loudness Meter 2 is another offending plugin.

**Comment by firebelley** [comment] 2022-07-14 00:32
It does seem like this is a plugin problem rather than an OBS problem. I would pitch the idea that maybe there should be some kind of UX mitigation for this in OBS - for example, a warning displayed in the program when a scene JSON file exceeds a certain size. At least that would give a hint to the user that a VST is causing problems and that narrows down the issue substantially.

I thought there was a problem with my OBS installation and I went through all kinds of trouble to downgrade OBS, update my GPU drivers, etc.

**Comment by RytoEX** [comment] 2022-07-24 14:50
Duplicate of #5058

**Closed by RytoEX** 2022-07-24 14:50 UTC
