### ISSUE TITLE
obs: symbol lookup error: obs: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6

### ISSUE THREAD

**Issue by hrqmonteiro** [obsproject/obs-studio#10356] opened 2024-03-09 18:52 UTC
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

30.1.0-rc1

### OBS Studio Log URL

Can't access

### OBS Studio Crash Log URL

Can't access

### Expected Behavior

To open

### Current Behavior

Try to open, then get:

```
obs: symbol lookup error: obs: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
```

### Steps to Reproduce

Just try to open

### Anything else we should know?

No

**Comment by tytan652** [comment] 2024-03-09 18:53
Qt broke ABI between 6.6.1 and 6.6.2, so must rebuild it against 6.6.2. If it's a package ask the packager to rebuild it.

**Comment by tytan652** [comment] 2024-03-09 18:54
Duplicate of #10280

**Closed by tytan652** 2024-03-09 18:53 UTC
