### ISSUE TITLE
Source Transition for Grouped Sources does not show Source-specific Hide Transition

### ISSUE THREAD

**Issue by immrsv** [obsproject/obs-studio#5278] opened 2021-09-13 12:26 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/gHekgrzTWYCZs_TE

### Expected Behavior

Transition effect "Show" on subitem of group should play when container group is made visible.
Transition effect "Hide" on subitem of group should play when container group is made non-visible.

### Current Behavior

Transition effect "Show" on subitem of group does play when container group is made visible.
Transition effect "Hide" on subitem of group **does not** play when container group is made non-visible.

### Steps to Reproduce

1. Add group to sources
2. Add subitem to group
3. Set show and hide transitions for subitem
4. Toggle group visibilty

### Anything else we should know?

no

**Comment by WizardCM** [comment] 2021-09-13 12:30
I would personally say this is less of a bug, and more of an implementation decision. Therefore this'd be better off on the [Fider](https://ideas.obsproject.com/).

**Comment by Fenrirthviti** [comment] 2021-09-13 15:24
Closing per above, this is not a bug but working as intended. Requests to change the behavior should be submitted to the Ideas page (Fider) linked above.

**Closed by Fenrirthviti** 2021-09-13 15:24 UTC

**Comment by immrsv** [comment] 2021-09-13 16:11
No worries, heading to Fider.

But to confirm, the (current) intended behaviour is that Show transitions work for subitems, but Hide transitions don't?
