### ISSUE TITLE
Virtual Camera loopback crash

### ISSUE THREAD

**Issue by Juesto** [obsproject/obs-studio#4019] opened 2021-01-05 19:42 UTC
Virtual Camera is available for use as camera device which shouldn't be possible due to loopback nature. Regardless if the virtual camera is started or not.

## Platform
Operating system and version: Windows 7 SP1 x64
OBS Studio version: 26.1.0 64-bits windows

## Expected Behavior
Virtual Camera should not show up listed in the video capture source.

## Current Behavior
Virtual Camera is selectable in device list, causing a crash when clicking OK (IIRC)

## Steps to Reproduce
0. Feel free to try with both virtual camera active or not, done with the feature stopped here
1. Add a video capture device
2. Select OBS Virtual Camera
3. Crash

## Additional information
after restarting obs i had a freeze, i think, when trying to remove the scene where the source was added to.
i don't fully remember whatever it was a crash or a freeze.

**Comment by Fenrirthviti** [comment] 2021-01-05 20:03
Please provide the crash log.

**Comment by jp9000** [comment] 2021-01-05 20:04
Strangely I'm not reproducing it for some reason.

**Comment by Fenrirthviti** [comment] 2021-01-05 20:09
I can also not replicate this. It's likely that this could be a Windows 7 specific bug, which means we probably won't spend a whole lot of time fixing. I would recommend updating your operating system to something that is current and still supported. If you can provide the crash log, it might shed some light on what is going on. Unfortunately, I do not want to dedicate significant project resources to investigating Windows 7 environments.

**Comment by Juesto** [comment] 2021-01-05 20:12
here's my current crash and previous crashes:
[Crash 2021-01-05 17-06-39.txt](https://github.com/obsproject/obs-studio/files/5772355/Crash.2021-01-05.17-06-39.txt)
[Crash 2021-01-02 21-29-47.txt](https://github.com/obsproject/obs-studio/files/5772356/Crash.2021-01-02.21-29-47.txt)
[Crash 2021-01-02 21-31-54.txt](https://github.com/obsproject/obs-studio/files/5772357/Crash.2021-01-02.21-31-54.txt)

the first crash was before clicking ok in sources and it restored without it. the second was from removing the scene
on the current one, i was able to add the camera but it crashed a second later then it showed up after restarting.

**Comment by Juesto** [comment] 2021-01-05 20:12
> I can also not replicate this. It's likely that this could be a Windows 7 specific bug, which means we probably won't spend a whole lot of time fixing. I would recommend updating your operating system to something that is current and still supported. If you can provide the crash log, it might shed some light on what is going on. Unfortunately, I do not want to dedicate significant project resources to investigating Windows 7 environments.

i understand, apologies for that.
you can close it as wontfix if it's a specific win7 issue

**Comment by jp9000** [comment] 2021-01-05 20:13
huh, I wonder what `ipcameraadapter.dll` is.

**Comment by Fenrirthviti** [comment] 2021-01-05 20:13
Looks like some kind of third party virtual cam that is conflicting with ours. You'll need to remove that.

**Comment by Juesto** [comment] 2021-01-05 20:14
> huh, I wonder what `ipcameraadapter.dll` is.
discontinued bridge program for connecting mjpeg cameras, primarily intended to be used with ip camera android app, its listed as mjpeg camera

**Comment by Juesto** [comment] 2021-01-05 20:15
> Looks like some kind of third party virtual cam that is conflicting with ours. You'll need to remove that.

had no idea, and i could've found out this myself if i cared to read the crash log

**Comment by Fenrirthviti** [comment] 2021-01-05 20:18
No worries, glad we could help! Going to close this out as it's a third-party module conflict.

**Closed by Fenrirthviti** 2021-01-05 20:18 UTC

**Comment by Juesto** [comment] 2021-01-05 20:21
i'll update if i get anything further, thanks.
