### ISSUE TITLE
OBS doesn't launch when using checkinstall

### ISSUE THREAD

**Issue by cg2121** [obsproject/obs-studio#2347] opened 2020-01-22 23:46 UTC
## Expected Behavior
OBS should launch normally.

## Current Behavior
OBS doesn't launch when using checkinstall for a second time.

## Steps to Reproduce
1. Install OBS via instructions on wiki (works first time)
2. Install again with same instructions
3. Launch OBS. It doesn't launch now.
4. Error:
```
obs: error while loading shared libraries: libobs-frontend-api.so.0: cannot open shared object file: No such file or directory
```

## Additional information
Using Ubuntu 19.10.
Works again when using "apt remove --purge obs-studio" and installing again.

**Comment by WizardCM** [comment] 2020-01-22 23:48
Can confirm I was able to reproduce this in Ubuntu 19.04.

**Comment by TheDevMinerTV** [comment] 2020-06-17 09:48
Same here, Ubuntu 18.04.4 LTS (Budgie).

**Comment by chen244** [comment] 2020-08-30 07:21
Me too

**Comment by adremides** [comment] 2020-10-07 01:31
Kubuntu 20.04 here. Same issue. Using `sudo apt remove --purge obs-studio` as suggested and installed from generated deb didn't work either.
Compiling it from a downloaded version instead a cloned one works for me (but it says the ugly 0.0.1 version in title).

**Comment by settermjd** [comment] 2020-12-27 09:52
I had the same issue and was able to fix it by creating a symlink using `sudo ln -s /usr/lib/libobs-frontend-api.so.0.0 /usr/lib/libobs-frontend-api.so.0`.

**Comment by khaskelbergTAU** [comment] 2021-04-07 23:32
I dont know if thats what you meant, simply adding the symlink didnt fix it. it would say for me "failed to find graphics device" if i tried to launch after that. 
simply running checkinstall again fixed it.

**Comment by k-morozov** [comment] 2021-04-08 15:18
After reinstalling OBS runs ok. (Ubuntu 20.04)
I run command from documentation twice:
`sudo checkinstall --default --pkgname=obs-studio --fstrans=no --backup=no --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes`

**Comment by Rick-mad-lab** [comment] 2021-11-21 12:40
you can use auto remove it stop because it detecting as a malware in Linux

**Comment by RytoEX** [comment] 2022-09-22 19:44
Please confirm if this is still an issue with OBS Studio 28.0.2 on currently supported versions of Ubuntu.

**Comment by Rick-mad-lab** [comment] 2022-09-22 20:24
I thing you it fixed now

**Comment by RytoEX** [comment] 2022-09-23 18:14
Closing per above. If this is still an issue, please comment with information about your build environment, including:
* Distro name and version number
* checkinstall version
* /etc/checkinstallrc file contents

**Closed by RytoEX** 2022-09-23 18:14 UTC
Labels: Linux, Good first issue, Confirmed
