### ISSUE TITLE
Recording does not stop

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#8360] opened 2023-02-27 16:17 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/WOb6Nb43mDmOqvZg

### Expected Behavior

OBS stops recording after clicking record button while recording

### Current Behavior

When I clicked to stop recording it did not stop recording. When I killed OBS and tried to delete the file becouse I forgot to switch source of screen recording the file was missing

### Steps to Reproduce

1. Record correctly
2. hibernation cycle
3. repeat steps 1 and 2 multiple times
4. while in hibernation connect external monitor
5. start recording
6. record for some time
7. click stop recording
8. recording does not stop

### Anything else we should know?

I am using plugin which allows connecting phone to OBS as webcam.

**Comment by RytoEX** [comment] 2023-02-27 16:23
OBS is not designed to run through system sleep or hibernation cycles.

This is effectively a duplicate of #5660 . See @notr1ch 's [comment here](https://github.com/obsproject/obs-studio/issues/4187#issuecomment-773384991) and @Fenrirthviti 's [comment here](https://github.com/obsproject/obs-studio/issues/5660#issuecomment-995175826).

**Closed by RytoEX** 2023-02-27 16:23 UTC
