### ISSUE TITLE
libdrm/drm_fourcc.h is missing while building obs-studio on fedora 33

### ISSUE THREAD

**Issue by aquisx** [obsproject/obs-studio#5325] opened 2021-09-23 08:46 UTC
### Operating System Info

Other

### Other OS

Fedora 33

### OBS Studio Version

27.1.0-rc3

### OBS Studio Log URL

-

### Expected Behavior

Building OBS from Source with the following install instructions:
https://obsproject.com/wiki/Install-Instructions#fedora-build-directions 

### Current Behavior

Getting the following error:
```
/home/user/Downloads/obsnew/obs-studio/plugins/linux-capture/pipewire.c:33:10: schwerwiegender Fehler: libdrm/drm_fourcc.h: Datei oder Verzeichnis nicht gefunden
   33 | #include <libdrm/drm_fourcc.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make[2]: *** [plugins/linux-capture/CMakeFiles/linux-capture.dir/build.make:188: plugins/linux-capture/CMakeFiles/linux-capture.dir/pipewire.c.o] Fehler 1

```

### Steps to Reproduce

```
sudo dnf install \
        cmake \
        ffmpeg-devel \
        fontconfig-devel \
        freetype-devel \
        gcc \
        gcc-c++ \
        gcc-objc \
        git \
        glib2-devel \
        libcurl-devel \
        libglvnd-devel \
        libv4l-devel \
        libX11-devel \
        libXcomposite-devel \
        libXdamage \
        libXinerama-devel \
        luajit-devel \
        make \
        mbedtls-devel \
        pipewire-devel \
        pulseaudio-libs-devel \
        python3-devel \
        qt5-qtbase-devel \
        qt5-qtbase-private-devel \
        qt5-qtsvg-devel \
        qt5-qtwayland-devel \
        qt5-qtx11extras-devel \
        speexdsp-devel \
        swig \
        systemd-devel \
        wayland-devel \
        x264-devel
```

```
wget https://cdn-fastly.obsproject.com/downloads/cef_binary_4280_linux64.tar.bz2
  tar -xjf ./cef_binary_4280_linux64.tar.bz2
  git clone --recursive https://github.com/obsproject/obs-studio.git
  cd obs-studio
  mkdir build && cd build
  cmake -DUNIX_STRUCTURE=1 -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_4280_linux64" ..
  make -j$(nproc)
  sudo make install
  sudo echo "/usr/local/lib" >> /etc/ld.so.conf.d/local.conf
  sudo ldconfig

```
### Anything else we should know?
[buildlog.log](https://github.com/obsproject/obs-studio/files/7216135/buildlog.log)

_No response_

**Comment by mihawk90** [comment] 2021-09-23 08:51
Not a bug OBS, just an oopsie on the documentation.

Install `vlc-devel` and you should be good to go.

That said, if you're just building to get the browser working:

https://github.com/mihawk90/obs-studio.spec

**Comment by RytoEX** [comment] 2021-09-23 09:33
Closing per the above comment.

**Closed by RytoEX** 2021-09-23 09:33 UTC
