### ISSUE TITLE
OBS 6.1 doesn't work with Webex

### ISSUE THREAD

**Issue by R4miuS** [obsproject/obs-studio#3780] opened 2020-11-27 17:28 UTC
## Platform>
Operating system and version: MS Windows 10
OBS Studio version: 2.6.1 RC1

## Expected Behavior
The virtual cam works with Webex

## Current Behavior
Same message than for the 2.6.2

## Steps to Reproduce
1. Launch OBS
2. Launch Webex
3. Select the OBS virtual webcam
4. Error message while selecting OBS virtual webcam

**Comment by notr1ch** [comment] 2020-11-27 17:33
Duplicate of https://github.com/obsproject/obs-studio/issues/3453

**Closed by notr1ch** 2020-11-27 17:33 UTC
