### ISSUE TITLE
Application Audio Capture (Test) delay and crackle

### ISSUE THREAD

**Issue by ZRdRy** [obsproject/obs-studio#8309] opened 2023-02-20 18:33 UTC
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/vPy6ODmZ6QMBOvnO，https://obsproject.com/logs/oF4ofzG6VIEKsq24，https://obsproject.com/logs/BrLt24tBBPNLWiXO

### Expected Behavior

Fix application audio acquisition (test) delay and crackle

### Current Behavior

Delay (out of sync) and crackling when using Application Audio Capture (Test)
OBS Log Analyzer Analysis display Max Audio Buffering

### Steps to Reproduce

1. OBS adds "application audio acquisition (test)" source to record video. Windows11 system sound settings set 3.5mm audio as the default device "application audio acquisition (test)" track delay is very high (USB interface is not tested)
2. Use the independent sound card (I use MIDIPLUS M). There will be a delay if the recording time is long, but there will be a crackle when the recording time is small
3. Use the independent sound card+Voicemeter, set Voicemeter as the default device for Windows11 system sound, and the recording crackle disappears

### Anything else we should know?

I suspect it is related to independent sound card or ASIO

**Comment by RytoEX** [comment] 2023-02-20 18:40
Probably a duplicate of #8064 or #8086.

**Comment by ZRdRy** [comment] 2023-02-20 18:46
> 可能是#8064或#8086的复制品。

After two days of testing, OBS27 28 29 has this problem

**Comment by ZRdRy** [comment] 2023-02-20 19:04
> Probably a duplicate of #8064 or #8086.

After two days of testing, this problem occurred in the last version of OBS27, 28 and 29. I didn't test the older version

**Comment by RytoEX** [comment] 2023-02-20 19:32
> > Probably a duplicate of #8064 or #8086.
> 
> After two days of testing, this problem occurred in the last version of OBS27, 28 and 29. I didn't test the older version

It's impossible for this to occur in OBS Studio 27. The feature has only existed since OBS Studio 28.

**Comment by ZRdRy** [comment] 2023-02-21 02:09
> > > Probably a duplicate of #8064 or #8086.
> > 
> > 
> > After two days of testing, this problem occurred in the last version of OBS27, 28 and 29. I didn't test the older version
> 
> It's impossible for this to occur in OBS Studio 27. The feature has only existed since OBS Studio 28.

Sorry, I forgot to say that my win-capture-audio plug-in for OBS27

**Comment by Philaeux** [comment] 2023-03-09 11:15
I can confirm some delay that appears with application audio capture (beta). No crackle tho. I use this source to capture game sound in a scene imported in another scene. Maybe the scene composition is the issue. I could do logs if necessary.

**Comment by liketop** [comment] 2023-03-13 12:53
I have the same problem. Only with me it is also partially with the game audio (Tarkov), Spotify and Discord.

I use OBS 29. 

Is there anything I can do to help solve the problem?

**Closed** 2023-04-05 19:49 UTC
