### ISSUE TITLE
OBS screen is mostly white - NOT a conflict

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#11081] opened 2024-08-06 03:18 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/IoeCRLNTeur6gupU

### Expected Behavior

I expect OBS to not be mostly white.

### Current Behavior

OBS's window is mostly white.
![image](https://github.com/user-attachments/assets/f254bba6-414c-452e-96e1-02013cf19502)

### Steps to Reproduce

No idea. Been like this ever since I launched Borderlands 2.

### Anything else we should know?

I have the official NVIDIA drivers, and they are up to date. This issue only came about when I launched Borderlands 2 for the first time. No idea why this caused this issue, other than it might be a scaling issue because I have a 4K display and Windows was in the middle of rearranging everything on my display when I noticed the white-ness of OBS. OBS has been totally useless since this happened. I've downgraded 2 versions, and downgraded 1 version from current, and still no change.

I have also tried using DDU to clean install the NVIDIA drivers, that did nothing. I then tried turning off Hardware Accelerated GPU Scheduling, and that did nothing.

I've checked the provided link, and I've either followed all of the steps, or determined I have none of it installed to conflict with. 
https://obsproject.com/kb/known-conflicts
This is a bug with OBS, please do NOT close my issue.

**Comment by Fenrirthviti** [comment] 2024-08-06 03:22
Duplicate of https://github.com/obsproject/obs-studio/issues/11068

**Comment by Fenrirthviti** [comment] 2024-08-06 03:23
As mentioned in the other issue, please use the support channels.

**Closed by Fenrirthviti** 2024-08-06 03:22 UTC

**Comment by jadenquinn** [comment] 2024-08-06 04:12
> As mentioned in the other issue, please use the support channels.

Jesus fuck - This is an OBS bug, you guys need to fix it. The support channels have nothing to do with it. I followed all instructions, and the bug still remains. This is very clearly not an issue with some other application interfering.

**Comment by Fenrirthviti** [comment] 2024-08-06 04:52
This is likely not an OBS bug, and is a known problem that typically crops up when you have other third party software (as mentioned, likes some kind of software that installs some kind of virtual display or other screen mirroring drivers) that is interfering with OBS. There is no bug for us to fix. The issue on my system does not occur as described.

Again, use the support channels so someone can investigate it, we don't take support requests on GitHub. If it is determined to be a bug, and the details of how to reproduce it on another system so are provided, this issue can be reopened with those details.
