### ISSUE TITLE
OBS doesn't recognize that the Internet is disconnected

### ISSUE THREAD

**Issue by rulenma** [obsproject/obs-studio#3367] opened 2020-08-30 17:12 UTC
## Platform
Operating system and version: Ubuntu 20.04.1 LTS
OBS Studio version: 25.0.8 (64-bit)

## Expected Behavior
Like on Windows OBS, it should recognize that the internet connection is lost and automatically starts reconnecting.

## Current Behavior
If my internet connection is lost, OBS doesn't recognize that it is lost/disconnected and tries to send data to the server.
Dropped frames are getting higher and higher.
OBS gets stucked. Stop Streaming keeps freezing the button but nothing happens.
After killing OBS I can start connection again.

In the logfiles I only see that the Client is connected to the server... no more..

## Steps to Reproduce
1. Start Streaming
2. Manually shutdown the internet
3. OBS is trying to send data to the server instead of starting the reconnect process (like it work's on windows like a charm :))
4. The "Stop Streaming" button can be pressed but it won't disconnect
5. Only hard killing OBS and restarting it helps

**Comment by Gol-D-Ace** [comment] 2020-09-06 13:26
I'm getting the same behavior on Ubuntu.

**Comment by rulenma** [comment] 2020-09-07 08:49
Reconnect only works when you come with the same public ip
But in which cases does this apply? There are no.. plz fix :(

**Comment by AlexDaniel** [comment] 2020-10-18 11:26
Was about to open a new ticket but I think this is exactly the issue I have. The internet connection disappears and appears again shortly, but OBS keeps sending the data until at one point it attempts to “Reconnect”. Except that it gets stuck reconnecting no matter how much I wait. If I hit “Stop streaming” then it gets stuck trying to stop the stream. The only solution is to restart OBS, but that obviously interrupts the recording, which is highly unwanted in some cases.

I wish OBS had logic that would guarantee that an actual reconnection attempt is made at a certain interval after the connection is lost, regardless of the fact that the old connection can't be dropped gracefully.

**Comment by Fenrirthviti** [comment] 2020-10-18 23:14
We do have that logic, this is a recent bug and an edge case that we're uncertain why it happens. I cannot replicate this on Windows or macOS, for example.

**Comment by AlexDaniel** [comment] 2020-10-23 10:04
OK, I was trying to figure out a workaround and I kinda stumbled upon something. First of all, I was able to reliably reproduce the issue by replugging the computer into a different router that has a different connection. When you do that, OBS starts dropping frames but doesn't attempt to reconnect (basically, this issue). If you hit reconnect then it gets stuck.

However, I was playing with various settings, including stream delay. And it seems like if you press “stop streaming and discard the delay” then it actually stops! Meaning that a temporary workaround for those who want to be able to forcibly restart the stream without restarting OBS is to set a stream delay to 1s or so. Don't take my word for it because there are a bunch of other settings I have changed, but I am definitely no longer seeing OBS getting stuck while trying to stop the stream.

**Comment by Techjar** [comment] 2022-01-20 05:09
This issue appears to be happening to me as well with self-compiled latest build of OBS on Arch Linux.

The log doesn't seem to have any clues, but here it is anyways: https://obsproject.com/logs/PUO85axab0r6eB49

**Comment by RytoEX** [comment] 2022-10-13 19:16
As far as we know, this was fixed by #6374. Please re-test in OBS Studio 28.0.3 or newer to confirm if this is fixed or if this is still an issue. If this is still an issue, we can reopen this.

**Closed by RytoEX** 2022-10-13 19:16 UTC
Labels: Linux, Confirmed

**Comment by Energie24** [comment] 2023-04-20 07:23
Hello, after 5 years I switched from Streamlabs to OBS Studio and I am very satisfied. However, I also noticed that after a longer stream time, the stream loses the connection without the OBS Studio even noticing this. Would be great if someone can watch the whole thing again. The internet connection was stable at all times and there were no lost frames.
