### ISSUE TITLE
Possible Issue with Studio Mode in 28.0.3

### ISSUE THREAD

**Issue by junkyard-dave** [obsproject/obs-studio#7653] opened 2022-10-24 13:02 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/EcqI7U4SmdnQhMSv

### Expected Behavior

Studio Mode is a mode that allows you to work on a scene in the background while displaying another scene. In particular, we sometimes have a Discord call open where 4-5 people are sharing their screen, and we're able to crop every individual window to an overlay so people can race games in real-time, while using Studio Mode to display a transition screen as people wait to avoid editing the overlay in front of everyone live.

### Current Behavior

Hey there.

I've streamed on Twitch for the last 6 years or so and regularly host speedrunning events (races). I use Studio Mode quite often to have either a transition screen displayed if someone is finished while setting up people in the background, and twice after updating to 28.0.3 I had a Discord call open (which has always worked in the past) of 5 people sharing their screen to individually crop into an overlay. During cropping, and while in Studio Mode, the dimensions of the window you're trying to crop become like 1 pixel x 1 pixel and no longer visible. The only way to successfully crop in Studio Mode into an overlay where there's multiple screens being shared from Discord (or a program like Streamlink where you have multiple streams open) is to exit Studio Mode and crop from the main scene itself. Studio Mode doesn't seem to work or function.

### Steps to Reproduce

1. Have 4-5 people sharing a screen in a Discord call. View all 4-5 of their streams at the same time.
2. Have Studio Mode open and have "Window Capture" selected for the Discord call.
3. Start cropping individual screens in Studio Mode into the overlay, I don't think it matters, as it happened three separate times in Studio Mode in general, but the first time I was cropping the game feeds (x4) into boxes that were 718x538, and the second time 5 different gamefeeds from Discord into 641x541 windows. Both times Studio Mode stopped responding and I couldn't see the Window Capture anymore (I also couldn't re-add the Window capture) until I left Studio Mode and transitioned to a single screen. The third time there was no specific dimensions I was cropping the shared screen on Discord into. I had Studio Mode open, and was going to crop the Window Capture, and again the Window Capture became 1x1 pixel and I couldn't see it anymore. I've been holding speedrunning events randomly ranging from just 2 people to 60 people on Twitch for the last 5-6 years and never once experienced this issue until 28.0.3 (current version I'm using and version it happened on). Thanks. :)
...

### Anything else we should know?

Nothing else I can think of. I attached the log as required, hopefully that helps, but the behaviour didn't result in a crash. I did have some crashes updating to 28.0.3, but that was likely due to TUNA and other things being outdated or not compatible. Since I updated the plugins, I haven't had any crash issues. If I can help somehow else, please let me know! Thank you!

[Edit]: I should specify after I updated the plugins I use, which is really just TUNA to display music, the behaviour still existed. I don't think it's related to any plugins, as both before (with plugin issues) after (after updating plugins) and just in general not using any plugins, Studio Mode would still freak out and eventually not be able to display the Discord Window Capture where 4-5 people are sharing their screen. Discord recently updated so I don't know the previous version, sorry.

The version before this build:

Stable 153655 (4461450) 

[Edit 2]:

https://www.twitch.tv/videos/1627189225?t=0h15m50s

It probably doesn't help much, but you can kind of see it there from the viewer side, as I was doing that in Studio Mode with that screen up and then it failed, so I had to swap to a single screen and edit everyone live like that.

**Comment by RytoEX** [comment] 2022-10-24 14:24
The log attached is not the log from when this event occurred, at least with respect to the linked VOD. Having a log where the issue occurred is ideal, as it allows us to follow along and attempt to recreate the setup that led to the issue.

So far, I cannot reproduce this in vanilla OBS Studio 28.0.3 (no plugins). Please try to reproduce this in a fresh scene collection (to make it easier to read the log). Ideally, also try to reproduce this without any plugins installed.

**Comment by CodeYan01** [comment] 2022-11-05 19:06
Were you perhaps pressing ctrl-z while editing? 
See issue https://github.com/obsproject/obs-studio/issues/5516, which will be fixed with https://github.com/obsproject/obs-studio/pull/5800

**Comment by junkyard-dave** [comment] 2022-11-06 05:36
> Were you perhaps pressing ctrl-z while editing? See issue #5516, which will be fixed with #5800

Hi there! Great sleuth work.

I almost certainly was. I align stuff by the pixel so if I moved things over too far, I would of CTRL + Z to remove it. 

I would likely assume this is what happened for sure.

**Closed** 2022-12-07 21:19 UTC
