### ISSUE TITLE
Image Mask filter on a group containing a source with Chroma Key or Luma Key filter results in dimmed colors

### ISSUE THREAD

**Issue by cowboy** [obsproject/obs-studio#3903] opened 2020-12-16 05:12 UTC
## Platform

Operating system and version: Windows 10 Pro 1909 18363.1256
OBS Studio version: 26.1.0 (64 bit)

## Expected Behavior
I expect to see the colors stay the same when applying an Image Mask to a group containing a source with Chroma Key / Luma Key filter

## Current Behavior
I'm seeing the colors dim when applying an Image Mask to a group containing a source with Chroma Key / Luma Key filter

## Steps to Reproduce

**Note: scroll to the bottom of the issue for the referenced sample images**

### Applying both the Chroma Key and Image Mask/Blend filters to the same source works as I expect:

1. Add the sample image source to a scene
2. Add a Chroma Key filter to it with the default settings
3. Add an Image Mask/Blend filter to it with the default settings, selecting the sample mask image

Image source with Image Mask disabled:
![image](https://user-images.githubusercontent.com/54051/102307437-78a62080-3f32-11eb-9fe3-29bc8fea4024.png)

Image source with Image Mask enabled:
![image](https://user-images.githubusercontent.com/54051/102307373-557b7100-3f32-11eb-816a-59e0c93921c3.png)

### Applying an Image Mask/Blend filter to a group containing a source with a Chroma Key filter does not work as I expect:

1. Add the sample image source to a scene
2. Add a Chroma Key filter to it with the default settings
3. Create a group
4. Move the image source created in step 1 into the group
5. Add an Image Mask/Blend filter to the group with the default settings, selecting the sample mask image

Group with Image Mask disabled:
![image](https://user-images.githubusercontent.com/54051/102307221-177e4d00-3f32-11eb-8162-2000e18d9d2c.png)

Group with Image Mask enabled - Note the color differences (I see similar behavior with the Luma Key filter)
![image](https://user-images.githubusercontent.com/54051/102307244-1f3df180-3f32-11eb-96bb-a4d414cd5d07.png)

## Additional resources

Sample image to be masked:
![color bars](https://user-images.githubusercontent.com/54051/102306761-f2d5a580-3f30-11eb-95ee-63c8be23f8a4.jpg)

Sample mask:
![circle mask](https://user-images.githubusercontent.com/54051/102306770-fcf7a400-3f30-11eb-8ee9-f0fb582a6292.png)

**Comment by WizardCM** [comment] 2020-12-16 05:14
This looks like a duplicate of #2852

**Comment by cowboy** [comment] 2020-12-16 05:18
> This looks like a duplicate of #2852

Ah ok, I didn't come across that one in my searching. In my examples, the sources in the groups have no transparency.

**Comment by flaeri** [comment] 2022-10-19 21:31
Tested on 28.0.3 with the files and steps included, and I can no longer reproduce. I assume its been resolved by the numerous color pipeline changes that has been implemented since the PR was created.

**Comment by RytoEX** [comment] 2022-10-19 21:47
Closing per the above comment by @flaeri .

**Closed by RytoEX** 2022-10-19 21:47 UTC
