### ISSUE TITLE
Green tint on stream to icecast/use the recording function

### ISSUE THREAD

**Issue by chris-yooo** [obsproject/obs-studio#7442] opened 2022-09-23 13:03 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/fSBCwwbjAjTQK2JT

### Expected Behavior

Yesterday in version 8.0.1 were all ok,
i took an update for maybe 1 hour and my streamed picture is complete green :S

look at screeny:
![Screenshot (1)](https://user-images.githubusercontent.com/55069641/191965373-4899b77c-88da-434d-bee9-2ab484d13ded.png)

i stream with the recording function look at screeny:

to an icecast server..

![Screenshot (2)](https://user-images.githubusercontent.com/55069641/191965796-61732661-c104-425c-b9ff-08942b90c7f8.png)

i downgraded to 8.0.1 and it worked again, now i upgraded allready to 8.0.2 to explain the failure.

### Current Behavior

the picture at streaming is green ^^

### Steps to Reproduce

1. start streaming

### Anything else we should know?

I think the error is related to the NV12 color format. I think we need an fast hotfix for this.

i will downgrade to 8.0.1 and stream further.

**Comment by Fenrirthviti** [comment] 2022-09-23 16:26
Can you validate if this is resolved by switching the color range from Full back to Limited?

**Comment by chris-yooo** [comment] 2022-09-23 17:10
i try :)

**Comment by Fenrirthviti** [comment] 2022-09-23 17:20
We've identified the issue, thank you for confirming the color range setting was related.

**Comment by Fenrirthviti** [comment] 2022-09-23 17:30
This is caused by https://github.com/obsproject/obs-studio/commit/70f8e833536d849d3f10dddd39d35e77dd3710ca

We're working on a fix.

**Comment by nabaxo** [comment] 2022-09-24 10:08
Just adding that this affects the virtual camera function too.

**Closed** 2022-09-24 23:45 UTC
Labels: Regression

**Comment by keriszafir** [comment] 2022-09-30 08:55
Got a similar problem in 28.0.2 in Linux, amd64. Recording is tinted, streaming and virtualcam are OK.

**Comment by chris-yooo** [comment] 2022-09-30 15:45
is it also green when you set the color space to limited instead of full?

**Comment by chris-yooo** [comment] 2022-09-30 15:45
> Got a similar problem in 28.0.2 in Linux, amd64. Recording is tinted, streaming and virtualcam are OK.

is it also green when you set the color space to limited instead of full?

**Comment by keriszafir** [comment] 2022-10-01 09:28
NV12 or P010 full color space: tinted
NV12 or P010 limited: OK
other color formats, full color space: OK

pt., 30 wrz 2022 o 17:45 chris_yooo ***@***.***> napisał(a):

**Comment by Fenrirthviti** [comment] 2022-10-01 18:38
Then this is already fixed in #7447.
