### ISSUE TITLE
Jack input client is not created on OBS startup

### ISSUE THREAD

**Issue by knipknap** [obsproject/obs-studio#4551] opened 2021-04-18 10:45 UTC
### Operating System Info

Ubuntu 20.10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/3snZpqyLKmA-kCzL

### Expected Behavior

When OBS is started, the input client should automatically be created in Jack, if a Jack input source is configured in OBS.

### Current Behavior

Upon starting OBS, no Jack input client exists in Jack, even if OBS is configured to use a Jack input client.
The input client in Jack is only created after opening the existing Jack input client settings in OBS, and temporarily changing the number of channels.

### Steps to Reproduce

1. Add "Jack input client" to a scene
2. Note that it works and the client can be used as intended.
3. Close OBS
4. Open OBS again
5. Note that the input client does not register any input
6. Open Carla, note that the input client does not exist in Jack
7. Back in OBS, double click the input client
8. Change the number of channels from 2 to 1
9. Check in Carla to see that the input client was now created and can be used again (after re-creating the patches in Carla)

**Comment by kkartaltepe** [comment] 2021-04-18 18:11
I cannot replicate this, all of my jack clients in all scenes register on start. It looks like you are using a weird patched version of debian's packaging. Instead try using our official packages.

**Comment by maxdrfr** [comment] 2021-07-29 13:09
I can't reproduce it on 27.0.1 Debian 11.

Can we close this ticket?

**Comment by Fenrirthviti** [comment] 2021-07-30 15:22
Closing per above comments.

**Closed by Fenrirthviti** 2021-07-30 15:22 UTC
Labels: Linux
