### ISSUE TITLE
Systray icon does not change "recording" to "paused" when recording is paused

### ISSUE THREAD

**Issue by solidmaple** [obsproject/obs-studio#2189] opened 2019-11-22 05:48 UTC
version 24.0.3
OS: windows10 64bit

Systray icon does not change "recording" to "paused" when recording is paused

this could be more "feature request" than bug:

but i would like systray icon to be changed to "paused" instead of "recording icon" when recording is paused.

thanks

**Comment by TeroKeso** [comment] 2019-11-22 15:37
Its not in 24.0.3 build. Its just been pulled to master. I think it will be part of next release...

**Comment by Fenrirthviti** [comment] 2019-11-22 16:04
This has already been merged to master and will be in the next release:

https://github.com/obsproject/obs-studio/pull/2093

Additionally, this is not a bug report, so you should not use GitHub Issues. Please use the Ideas page for feature requests: https://ideas.obsproject.com

**Closed by Fenrirthviti** 2019-11-22 16:04 UTC
