### ISSUE TITLE
Hardware encoders on intel Mac are not available in the simple output mode

### ISSUE THREAD

**Issue by stephane-archer** [obsproject/obs-studio#9711] opened 2023-10-14 00:35 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/4bNg3aJwCByPWLmW

### Expected Behavior

have Hardware accelerated options in the simple output mode

### Current Behavior

<img width="984" alt="Screenshot 2023-10-13 at 19 41 24" src="https://github.com/obsproject/obs-studio/assets/2981437/289cee02-a395-4af5-a314-41f438a16d7d">
<img width="982" alt="Screenshot 2023-10-13 at 19 43 20" src="https://github.com/obsproject/obs-studio/assets/2981437/2dd6d347-e0c8-4c36-9a7f-675fcd06add5">

### Steps to Reproduce

1.
2.
3.
...

**Comment by kkartaltepe** [comment] 2023-10-14 00:40
Dupe of their previous issue, and this is intentional.

**Comment by stephane-archer** [comment] 2023-10-14 00:57
Why is this intentional? Can't we have sensitive default settings for these encoders? Why would you hide them from beginner users? Sofware encoding just doesn't work on Intel Mac, it requires too much CPU to be usable

**Comment by Fenrirthviti** [comment] 2023-10-14 03:27
> Why is this intentional? Can't we have sensitive default settings for these encoders? Why would you hide them from beginner users? Sofware encoding just doesn't work on Intel Mac, it requires too much CPU to be usable

For posterity, they were excluded because the hardware encoders are unreliable/buggy on Intel macs and since they have been effectively abandoned by Apple at this point, there is little to no chance they will get fixed.

**Closed** 2023-10-14 03:59 UTC
