### ISSUE TITLE
Crash when using SVT-AV1 encoder

### ISSUE THREAD

**Issue by jh10001** [obsproject/obs-studio#10745] opened 2024-05-28 14:07 UTC
### Operating System Info

Other

### Other OS

Windows Server 2019

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/eVMB8MEsL63512bs

### Expected Behavior

Recording to start successfully without any crashes.

### Current Behavior

When initiating recording, OBS Studio crashes after 2-3 seconds. No new video files are generated in the capture folder. The crash log does not generate.

### Steps to Reproduce

1. Open OBS Studio.
2. Select SVT-AV1 encoder.
3. Click "Start Recording."
4. OBS Studio crashes after 2-3 seconds.

### Anything else we should know?

Attempted using multiple versions, and found that version 30.0.2 does not have this issue. Versions 30.1 and onwards exhibit the same crash behavior.

The logs were obtained from version 30.1, and the logs outputted by version 30.1.2 are the same.

**Comment by RytoEX** [comment] 2024-05-28 16:03
This is a known crash in the SVT-AV1 library caused by an MSVC compiler bug in certain versions of MSVC that only happens on SVT-AV1 presets lower than 10. This has already been fixed in our git repo due to CI's MSVC being updated and will be fixed in the next OBS release.

**Closed by RytoEX** 2024-05-28 16:03 UTC
