### ISSUE TITLE
Obs doesn't record desktop audio after uptading to Fedora 35

### ISSUE THREAD

**Issue by Barfguy** [obsproject/obs-studio#5540] opened 2021-11-18 13:32 UTC
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/T4WhjIlM52_YrEoV

### Expected Behavior

I was expecting that OBS-would record my desktop/game audio

### Current Behavior

It only records my voice from microphone

### Steps to Reproduce

1. Start obs on fedora 35
2. Hit record

### Anything else we should know?

I found some others with the same problem, and there seems to be no good and easy fix for this. I guess this is pipewire-related problem? Only real fixing suggestion that I found was related to pipewire and wireplumber, and somehow switching away from that wireplumber to pipewire-media-session would fix it, but it didn't work for me.

I have tried with both flatpak and rpm packages, and it's no different

Others on the net with same problem:
https://obsproject.com/forum/threads/fedora-35-no-sound-recorded.149433/
https://obsproject.com/forum/threads/desktop-audio-not-working.150245/#post-549710
https://bugzilla.rpmfusion.org/show_bug.cgi?id=6113
https://ask.fedoraproject.org/t/no-sound-after-upgrade-install-of-fedora-35-rawhide/16302/19

**Comment by RytoEX** [comment] 2021-11-18 13:40
This seems like a duplicate of #5533.

**Closed** 2021-11-18 16:19 UTC
