### ISSUE TITLE
Output timer stops video prematurely

### ISSUE THREAD

**Issue by weichensw** [obsproject/obs-studio#6558] opened 2022-05-29 19:04 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/forum/threads/output-timer-stops-video-prematurely.118949/

### Expected Behavior

When using output timer, the video should be always stopped as expected

### Current Behavior

When using the output timer functionality, the recording will sometimes stop immediately, producing a 1kb file. The UI however shows that it is still recording. Normally when it is recording the file size is 0kb and will show the real size when the recording is complete. If I don't notice the 1kb file immediately, it will just keep running without throwing any errors. I for sure have the correct timer settings.

### Steps to Reproduce

When using the output timer functionality, the recording will sometimes stop immediately, producing a 1kb file. The UI however shows that it is still recording. Normally when it is recording the file size is 0kb and will show the real size when the recording is complete. If I don't notice the 1kb file immediately, it will just keep running without throwing any errors. I for sure have the correct timer settings.

### Anything else we should know?

The bug has been reproing since 25.0.4, see here: https://obsproject.com/forum/threads/output-timer-stops-video-prematurely.118949/

**Comment by Fenrirthviti** [comment] 2022-05-29 20:04
Please include a full log file instead of a link to a forum post with only a snippet.

**Comment by weichensw** [comment] 2022-05-30 18:32
I have a set of recording needs to be done asap so I reverted back to 24.0.4. I will go back to latest version after done. I might not be able to get a full log until then but I can confirm 24.0.4 doesn't have this problem.

**Comment by AntoineGR** [comment] 2022-11-16 18:47
I can reproduce and confirm this bug 100%

My Timer is set to stop recording after 4 seconds.
When opening OBS I can make a few recordings (2-4) without any issue,
but then it happens : recording stops instantly, creating a corrupt 4kb file.

**After that initial bug, every other recording stops prematurely = 50% of corrupts recordings !**
After each corrupt file the log shows an increasing number of "Stopping recording due to OutputTimer timeout" message.

Here attached is a full log showing : 
- 4 good recordings
- a first corrupt recording (@19:25:49.299)
- a series of 6 recordings alternating good/corrupt
[2022-11-16 19-24-35.txt](https://github.com/obsproject/obs-studio/files/10024791/2022-11-16.19-24-35.txt)

**Comment by DevSejin** [comment] 2023-01-04 17:55
windows 10, 28.1.2 64bit
still problem...

**Comment by guidoising** [comment] 2023-03-12 14:23
I had initially posted an inquiry relative to this already April 2nd, 2020 in the forum (https://obsproject.com/forum/threads/output-timer-potential-bug.118065/#post-444711) . 

It appears this bug-report has been created finally to address this issue. 

Strangely enough, the bug seemed fixed with some OBS release following 25.0.1 and I did not have issues for a year. But after upgrade to OBS 29.x the bug as describe here, re-appeared. (The fact that it went away may have been subject to a change in my use-pattern and it may well have been there all the time and never fixed.) This is just to say: YES, it still is there and pretty annoying, spoiling somehow the user-experience of this otherwise mighty fine piece of software.

**Comment by mriamnobody** [comment] 2023-05-29 00:08
@Fenrirthviti @weichensw I'm also facing the same issue. I'm using version 29.1.1, Windows 11 and latest Nvidia drivers

**Comment by mriamnobody** [comment] 2023-05-29 00:10
As @AntoineGR mentioned, the issue follows a pattern. One or two proper video recordings and then the issue surfaces.

**Comment by mriamnobody** [comment] 2023-05-29 00:11
I will attach full log file and a screen recording of the issue as soon as I reach home.

**Comment by SuslikV** [comment] 2023-06-03 16:39
**Recorded inside VirtualBox environment**
OBS v29.1.2
On video the issue is in 8th recording (stops before timeout), timecode - 00:01:01

https://github.com/obsproject/obs-studio/assets/19683044/fe7f2929-c1f6-4ffe-b341-58bb7e273c4c

OBS log
[2023-06-03 15-39-24.txt](https://github.com/obsproject/obs-studio/files/11643205/2023-06-03.15-39-24.txt)

**Note**
With each timer start (run) the number of messages:

> Stopping recording due to OutputTimer timeout

in the log increases by 1.

The issue may happen more frequently with increased number of timer runs (about 30-60 is nice point to start).

**Comment by raynerdacruz** [comment] 2023-08-16 23:35
Is anyone working on this issue?

**Comment by gxalpha** [comment] 2023-08-17 10:31
@raynerdacruz I am not aware of anyone actively working on this issue at this time.

**Comment by ljlongwing** [comment] 2023-10-02 18:03
Just adding a +1 to this.  I'm using Windows 29.1.3 with this bug

**Closed** 2023-11-20 22:02 UTC

**Comment by mriamnobody** [comment] 2024-02-04 07:55
This issue is not resolved (at least for my setup). I face this issue twice again. I OBS Studio 30.0.2, Windows 11

**Comment by RytoEX** [comment] 2024-02-04 23:15
> This issue is not resolved (at least for my setup). I face this issue twice again. I OBS Studio 30.0.2, Windows 11

The fix commit is only in OBS Studio 30.1.0-beta1, not 30.0.2.

**Comment by mriamnobody** [comment] 2024-02-05 04:21
> > This issue is not resolved (at least for my setup). I face this issue twice again. I OBS Studio 30.0.2, Windows 11
> 
> The fix commit is only in OBS Studio 30.1.0-beta1, not 30.0.2.

Thanks @RytoEX for clarification. I apologize for any confusion or misunderstanding from my side.
