### ISSUE TITLE
Any key(s) released while a hotkey is held will trigger the hotkey action

### ISSUE THREAD

**Issue by hoffr** [obsproject/obs-studio#4655] opened 2021-05-05 16:28 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/EkGuhxWhUaAGI-xg

### Expected Behavior

Action should probably not trigger on release of any key during a hotkey hold.

### Current Behavior

Any key(s) released while a hotkey is held will trigger the hotkey action.

The hotkey itself as expected does not trigger on release, only a key other than the hotkey.

Example: Let's say I bind the h key to both 'Show' and 'Hide' on a single source, so it acts as a toggle every time h is pressed down.

### Steps to Reproduce

1. Press and hold the hotkey (in this case: h)
2. Release any other key, regardless of if it was held before or after the hotkey was pressed down
3. The hotkey action triggers

### Anything else we should know?

While the hotkey is still held down, any release of any key will trigger the hotkey action. You can press and release for instance the g key many times while h is held, and on every release of g the action will trigger. You can hold g and f and d simultaneously while h is held, and each of them will trigger it on release except h.

This is happening with show/hide on image, color and display source, and 'slideshow next' on slideshow source. I haven't tested other sources.

**Comment by Fenrirthviti** [comment] 2021-05-05 16:41
This is effectively a duplicate of #4408, closing.

**Closed by Fenrirthviti** 2021-05-05 16:41 UTC

**Comment by hoffr** [comment] 2021-05-05 17:44
> 
> 
> This is effectively a duplicate of #4408, closing.

This is not a duplicate, it's a completely separate issue.

#4408 presents as an issue that the hotkey action will trigger if the hotkey is pressed even if a modifier is held. This appears to be intended behavior to me.

I'm presenting a separate issue that while a hotkey is held, any key that is not the hotkey that is RELEASED will trigger the hotkey action. This does not pertain specifically to modifiers and does not appear to be intended behavior, it's a very different phenomenon from #4408 . I wrote an example in the OP that should help understand, i know it's a bit weird.

EDIT to OP: Added a bit about how holding a modifier affects press/release

I personally would be thankful if this were resolved because I'm doing some work that requires this not to happen. Thanks for your time regardless.

**Comment by Fenrirthviti** [comment] 2021-05-06 14:40
It might seem different, but this is the exact same issue where hotkeys are not checking for their own exclusivity, which causes all sorts of weirdness to occur. "Modifier" keys are really any key held in addition to another. "L" could be considered a modifier key as far as the code is concerned. It's all the same underlying issue with how the Qt hotkey system (which is what we use) functions by default. If this turns out to not be solved by fixing #4408, we can reopen.
