### ISSUE TITLE
Update check dialog is not closing on MacOS (M2) (video attached)

### ISSUE THREAD

**Issue by vajahath** [obsproject/obs-studio#8221] opened 2023-02-06 08:03 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/gDhk888gA1mGichX

### Expected Behavior

When we click the "Check automatically" or "Dont check" buttons on the "automatic update confirm dialog", it should work and close the dialog. That is not happening.

### Current Behavior

Update check dialog buttons are not responding and the dialog is not closing.

https://user-images.githubusercontent.com/12165822/216916474-69057ce4-34fc-43aa-9616-692ae9022750.mp4

### Steps to Reproduce

1. I installed the OBS on Mac
2. Dragged into applications
3. Opened the app. Then this dialog appears and it never goes.

### Anything else we should know?

MacOS 13.2
Apple M2 Chip
Using OBS Apple Silicon version.

**Comment by gxalpha** [comment] 2023-02-06 11:25
Duplicate of #4904

**Closed by gxalpha** 2023-02-06 11:25 UTC
