### ISSUE TITLE
Browser hardware acceleration broken since v27.2

### ISSUE THREAD

**Issue by davethejackal** [obsproject/obs-studio#7670] opened 2022-10-26 20:24 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2 and all later

### OBS Studio Log URL

https://obsproject.com/forum/attachments/2022-02-15-20-26-44-txt.80278/

### Expected Behavior

Smooth 3d animation from HTML 5.

### Current Behavior

Browser 3d acceleration seems broken since the browser revamp in 27.2 - checked with latest version and it still occurs.

See video here: https://www.youtube.com/watch?v=JsadRuyKZI0

No plugins are used, it's all HTML5 and javascript running in the OBS browser. 

### Steps to Reproduce

1. Multiple 3d CSS animations running in the browser addon.
2.
3.
...

**Comment by notr1ch** [comment] 2022-10-26 20:30
Please fill in proper reproduction steps. A screenshot of `chrome://gpu` in a browser source might also be useful, it shows hardware acceleration is working fine for me in 28.0.3.

**Comment by Fenrirthviti** [comment] 2022-10-26 20:30
20:28:59.011: obs-browser: Not allowed to load local resource: file:///G:/StreamData/Videos/intro.small/headlander.mp4 (source: http://absolute/G:/StreamData/Scenes/Videointro/cockpitbanner.html:0)

Doesn't seem to be an issue with hardware acceleration, but rather local file access which has changed due to security, but I don't recall the workaround for it.

**Comment by RytoEX** [comment] 2023-02-22 22:22
From what I recall, OBS Studio 27.2.0 (specifically that point release) had several issues related to browser source hardware acceleration. [OBS Studio 27.2.1](https://github.com/obsproject/obs-studio/releases/tag/27.2.1) fixed multiple issues with that, so this should have fixed this Issue.

We believe this should be fixed, so I will close this Issue. Feel free to re-test in OBS Studio 29.0.2 (or newer) and report back with a new log file and the results of `chrome://gpu` for a browser source.

**Closed by RytoEX** 2023-02-22 22:22 UTC

**Comment by TStod** [comment] 2023-03-11 18:34
> > Doesn't seem to be an issue with hardware acceleration, but rather local file access which has changed due to security, but I don't recall the workaround for it.
> 
> I think I am using the workaround. it's not loaded as a local file - though it used to be. This is the working version in 27.1.3.
> 
> ![image](https://user-images.githubusercontent.com/20055435/198135594-a7d00036-1384-4104-83c3-dc9036d46e98.png)

Had a similar issue where local files were not loading embeded mp4s or webms correctly at times.
This is the first mention I have seen since 27.1.3 of changing file path to `file:///` instead of using the `Local file` checkbox and after some limited testing it seems to have completely resolved my issue.

**Comment by jrhcodes** [comment] 2023-03-31 23:02
> > > Doesn't seem to be an issue with hardware acceleration, but rather local file access which has changed due to security, but I don't recall the workaround for it.
> > 
> > 
> > I think I am using the workaround. it's not loaded as a local file - though it used to be. This is the working version in 27.1.3.
> > ![image](https://user-images.githubusercontent.com/20055435/198135594-a7d00036-1384-4104-83c3-dc9036d46e98.png)
> 
> Had a similar issue where local files were not loading embeded mp4s or webms correctly at times. This is the first mention I have seen since 27.1.3 of changing file path to `file:///` instead of using the `Local file` checkbox and after some limited testing it seems to have completely resolved my issue.

That's just the background video and not the videos on the rotating carousel which are loaded in the browser/html. If I change the loading to local for the HTML file, that HTML file cannot then load the videos for the carousel from the local drive.

**Comment by jrhcodes** [comment] 2023-03-31 23:31
it also plays the movies really slowly in the rotating windows, like they're each 2-6fps

**Comment by jrhcodes** [comment] 2023-04-01 22:26
So it seems to be something to do with video streaming in all browsers based on the chromium engine and the version introduced in 27.2. At least that's what I assume after trying it in firefox, where it was glassily smooth, whereas it was jerky with slow video playback in chrome, opera GX, edge and OBS.

![image](https://user-images.githubusercontent.com/119757667/229316680-87bd8082-ea24-45e2-9fcd-de4f31d518c1.png)

**Comment by jrhcodes** [comment] 2023-04-02 01:07
It is being caused by the animation on the neon glow of the rotating letters which looks like this:

```
@keyframes neon {
  from {
 	text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #fff, 0 0 40px red, 0 0 70px red, 0 0 80px red;
  }
  16% {
 	text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #fff, 0 0 20px red, 0 0 35px red, 0 0 40px red;
  }
  33% {
 	text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #fff, 0 0 40px green, 0 0 70px green, 0 0 80px green;
  }
  49% {
 	text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #fff, 0 0 20px green, 0 0 35px green, 0 0 40px green;
  }
  67% {
 	text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #fff, 0 0 40px blue, 0 0 70px blue, 0 0 80px blue;
  }
  83% {
 	text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 15px #fff, 0 0 20px blue, 0 0 35px blue, 0 0 40px blue;
  }
  to {
 	text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #fff, 0 0 40px red, 0 0 70px red, 0 0 80px red;
  }
}

.neon {
	animation: neon 20s 0s infinite; 
}
```

If I remove this, it works on all browsers and in obs

It works fine with:

.neon {
	text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #fff, 0 0 40px #fff, 0 0 70px #fff, 0 0 80px #fff;
}

**Comment by Fenrirthviti** [comment] 2023-04-02 02:50
This issue has been closed for several months, and it's unclear exactly what is being reported here as it doesn't seem directly related to the original issue. Please open a new issue with specific steps to reproduce, a log file, and any additional information you have.
