### ISSUE TITLE
A bug of SRT streaming from 26.0

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#3519] opened 2020-09-30 04:55 UTC
## Platform

Operating system and version:
OBS Studio version: 26.0

## Steps to Reproduce

1. A bug of SRT streaming from 26.0

## Additional information

12:51:00.983: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 160, channels: 2, channel_layout: 3
12:51:00.983: 
12:51:00.990: ==== Streaming Start ===============================================
12:51:00.990: [ffmpeg muxer: 'adv_stream'] Writing file 'srt://192.168.10.11:10000?mode=listener'...
12:51:02.079: [ffmpeg muxer: 'adv_stream'] os_process_pipe_write for packet data failed
12:51:02.079: [ffmpeg muxer: 'adv_stream'] ffmpeg-mux: Couldn't open 'srt://192.168.10.11:10000?mode=listener', Unknown error occurredCouldn't initialize muxer
12:51:02.079: [srt @ 000001c57a841e80] Connection setup failure: unable to create/configure SRT socket: Í¨³£Ã¿¸öÌ×½Ó×ÖµØÖ·(Ð­Òé/ÍøÂçµØÖ·/¶Ë¿Ú)Ö»ÔÊÐíÊ¹ÓÃÒ»´Î¡£

**Comment by WizardCM** [comment] 2020-09-30 05:00
Which operating system? I cannot reproduce this on Windows 10. And please post the full log file.

**Comment by iesvme** [comment] 2020-09-30 05:03
Thank you for your replying! Please have a check.

12:50:41.467: CPU Name: AMD Ryzen 5 3600 6-Core Processor              
12:50:41.467: CPU Speed: 3600MHz
12:50:41.467: Physical Cores: 6, Logical Cores: 12
12:50:41.467: Physical Memory: 32721MB Total, 29046MB Free
12:50:41.467: Windows Version: 10.0 Build 17763 (release: 1809; revision: 1490; 64-bit)
12:50:41.467: Running as administrator: false
12:50:41.467: Aero is Enabled (Aero is always on for windows 8 and above)
12:50:41.467: Windows 10 Gaming Features:
12:50:41.467: 	Game DVR: On
12:50:41.468: Sec. Software Status:
12:50:41.469: 
12:50:41.469: 
12:50:41.469: 
12:50:41.470: 
12:50:41.470: Current Date/Time: 2020-09-30, 12:50:41
12:50:41.470: Browser Hardware Acceleration: true
12:50:41.470: Portable mode: false
12:50:43.122: OBS 26.0.0 (64-bit, windows)
12:50:43.122: ---------------------------------
12:50:43.136: ---------------------------------
12:50:43.136: audio settings reset:
12:50:43.136: 	samples per sec: 48000
12:50:43.136: 	speakers:        2
12:50:43.136: ---------------------------------
12:50:43.136: Initializing D3D11...
12:50:43.136: Available Video Adapters: 
12:50:43.138: 	Adapter 0: AMD Radeon RX 580 2048SP
12:50:43.138: 	  Dedicated VRAM: 4273827840
12:50:43.138: 	  Shared VRAM:    4270678016
12:50:43.138: 	  PCI ID:         1002:6fdf
12:50:43.138: 	  Driver Version: 26.20.15029.27017
12:50:43.139: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=DELL U2417H
12:50:43.139: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=60, name=FH-DP4K
12:50:43.140: Loading up D3D11 on adapter AMD Radeon RX 580 2048SP (0)
12:50:43.171: D3D11 loaded successfully, feature level used: b000
12:50:43.171: DXGI increase maximum frame latency success
12:50:43.171: D3D11 GPU priority setup failed (not admin?)
12:50:43.568: ---------------------------------
12:50:43.568: video settings reset:
12:50:43.568: 	base resolution:   1920x1080
12:50:43.568: 	output resolution: 1920x1080
12:50:43.568: 	downscale filter:  Bicubic
12:50:43.568: 	fps:               30/1
12:50:43.568: 	format:            NV12
12:50:43.568: 	YUV mode:          709/Partial
12:50:43.568: NV12 texture support enabled
12:50:43.570: Audio monitoring device:
12:50:43.570: 	name: Wave Out 2/3 (kX 10k2.5 Audio (3553) - Generic)
12:50:43.570: 	id: {0.0.0.00000000}.{f388dd7c-7e1e-457a-9d60-d4bf0827b96d}
12:50:43.570: ---------------------------------
12:50:43.571: trying 'C:/Program Files/obs-studio/bin/64bit'
12:50:43.571: found curl library at 'C:/Program Files/obs-studio/bin/64bit/libcurl.dll'
12:50:43.571: curl loaded successfully
12:50:43.573: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
12:50:43.573: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
12:50:43.772: [AMF] Version 2.7.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.16.0, Library: 1;4;16;0;19.50.29.27;202005151521;CL#2116351).
12:50:43.850: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'AMD Radeon RX 580 2048SP (VEN_1002/DEV_6fdf/SUB_e3531da2/REV_00ef)':
12:50:43.850:   H264/AVC: Supported
12:50:43.850:   H265/HEVC: Supported
12:50:43.850: 
12:50:43.863: [obs-browser]: Version 2.8.7
12:50:43.866: [obs-ndi] hello ! (version 4.9.0)
12:50:43.866: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
12:50:43.866: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
12:50:43.869: [obs-ndi] NDI runtime loaded successfully
12:50:43.871: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
12:50:44.098: Failed to load 'zh-CN' text for module: 'source-switcher.dll'
12:50:44.100: VLC found, VLC video source enabled
12:50:44.104: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
12:50:44.104: No blackmagic support
12:50:44.107: ---------------------------------
12:50:44.107:   Loaded Modules:
12:50:44.107:     win-wasapi.dll
12:50:44.107:     win-mf.dll
12:50:44.107:     win-dshow.dll
12:50:44.107:     win-decklink.dll
12:50:44.107:     win-capture.dll
12:50:44.107:     vlc-video.dll
12:50:44.107:     text-freetype2.dll
12:50:44.107:     source-switcher.dll
12:50:44.107:     rtmp-services.dll
12:50:44.107:     obs-x264.dll
12:50:44.107:     obs-vst.dll
12:50:44.107:     obs-transitions.dll
12:50:44.107:     obs-text.dll
12:50:44.107:     obs-qsv11.dll
12:50:44.107:     obs-outputs.dll
12:50:44.107:     obs-ndi.dll
12:50:44.107:     obs-filters.dll
12:50:44.107:     obs-ffmpeg.dll
12:50:44.107:     obs-browser.dll
12:50:44.107:     image-source.dll
12:50:44.107:     frontend-tools.dll
12:50:44.107:     enc-amf.dll
12:50:44.107:     decklink-ouput-ui.dll
12:50:44.107:     coreaudio-encoder.dll
12:50:44.107:     advanced-scene-switcher.dll
12:50:44.107: ---------------------------------
12:50:44.107: ==== Startup complete ===============================================
12:50:44.116: All scene data cleared
12:50:44.116: ------------------------------------------------
12:50:44.137: [obs-ndi] started A/V threads for source 'SONG-002 (OBS-002)'
12:50:44.137: [obs-ndi] A/V thread for 'OBS-002' started
12:50:44.137: [duplicator-monitor-capture: 'æ¾ç¤ºå¨æè·'] update settings:
12:50:44.137: 	display: 1 (1920x1080)
12:50:44.137: 	cursor: false
12:50:44.150: [Media Source 'cross.mp4']: settings:
12:50:44.150: 	input:                   D:/Bible/OBS/cross.mp4
12:50:44.150: 	input_format:            (null)
12:50:44.150: 	speed:                   100
12:50:44.150: 	is_looping:              no
12:50:44.150: 	is_hw_decoding:          no
12:50:44.150: 	is_clear_on_media_end:   yes
12:50:44.150: 	restart_on_activate:     yes
12:50:44.150: 	close_when_inactive:     no
12:50:44.375: Failed to open file 'D:/Bible/OBS/qrcode.png': No such file or directory
12:50:44.375: gs_image_file_init_internal: Failed to load file 'D:/Bible/OBS/qrcode.png'
12:50:44.375: [image_source: 'äºç»´ç '] failed to load texture 'D:/Bible/OBS/qrcode.png'
12:50:44.383: [source-switcher: 'åç¹è½®æ­'] switch to 'åç¹_A'
12:50:44.585: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_B' using 'å¹»ç¯ç' for 1000 ms, resize {0,0}
12:50:44.735: Switched to scene 'è¯éåé¡¾'
12:50:44.766: ------------------------------------------------
12:50:44.766: Loaded scenes:
12:50:44.766: - scene 'HOME':
12:50:44.766:     - source: 'æåéå¤´' (scene)
12:50:44.766:     - source: 'date&time' (text_gdiplus_v2)
12:50:44.766:     - source: 'cross' (image_source)
12:50:44.766: - scene 'æ¬æè®°å¿µ':
12:50:44.766:     - source: 'æåéå¤´' (scene)
12:50:44.766:     - source: 'æ¾ç¤ºå¨æè·' (monitor_capture)
12:50:44.766:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.766: - scene 'ä½¿å¾ä¿¡ç»':
12:50:44.766:     - source: 'creed.html' (browser_source)
12:50:44.766: - scene 'ä¸»æ¥è¯é':
12:50:44.766:     - source: 'æåéå¤´' (scene)
12:50:44.766:     - source: 'è²å' (color_source)
12:50:44.766:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.766:     - source: 'åç¹è½®æ­' (source_switcher)
12:50:44.766:     - source: 'åç¹_C' (text_gdiplus)
12:50:44.766:     - source: 'åç¹_B' (text_gdiplus)
12:50:44.766:     - source: 'åç¹_A' (text_gdiplus)
12:50:44.766:     - source: 'è¯éäºº' (text_gdiplus)
12:50:44.766:     - source: 'é¢ç®' (text_gdiplus)
12:50:44.766: Advanced Scene Switcher started12:50:44.766:     - source: 'ç»æ' (text_gdiplus)

12:50:44.766:     - source: 'Logo' (group)
12:50:44.766:         - source: 'cross' (image_source)
12:50:44.766:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.766:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'è¯ç­ç®å±':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²å' (color_source)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767:     - source: 'cross' (image_source)
12:50:44.767:     - source: 'è¯ç­ç®å±éå¥' (text_gdiplus)
12:50:44.767:     - source: 'è¯ç­ç®å±æ è¯­' (text_gdiplus)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'ä»ä¸å¥ç®':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²å' (color_source)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767:     - source: 'cross' (image_source)
12:50:44.767:     - source: 'ä»ä¸å¥ç®éå¥' (text_gdiplus)
12:50:44.767:     - source: 'ä»ä¸å¥ç®æ è¯­' (text_gdiplus)
12:50:44.767:     - source: 'äºç»´ç ' (image_source)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'ä¸¾è¡å£é¤':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²å' (color_source)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767:     - source: 'cross' (image_source)
12:50:44.767:     - source: 'ä¸¾è¡å£é¤éå¥' (text_gdiplus)
12:50:44.767:     - source: 'ä¸¾è¡å£é¤æ è¯­' (text_gdiplus)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'å®¶äºåäº«':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²å' (color_source)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767:     - source: 'cross' (image_source)
12:50:44.767:     - source: 'å®¶äºåäº«éå¥' (text_gdiplus)
12:50:44.767:     - source: 'å®¶äºåäº«æ è¯­' (text_gdiplus)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'éç¥':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²æº 2' (color_source_v2)
12:50:44.767:         - filter: 'è²å¼' (color_key_filter)
12:50:44.767:     - source: 'éç¥åå®¹' (text_gdiplus)
12:50:44.767:     - source: 'éç¥æ é¢' (text_gdiplus)
12:50:44.767:     - source: 'Group' (group)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'ç½²å' (text_gdiplus)
12:50:44.767: - scene 'ç§»è½¦æé':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²æº 2' (color_source_v2)
12:50:44.767:         - filter: 'è²å¼' (color_key_filter)
12:50:44.767:     - source: 'æå­' (text_gdiplus)
12:50:44.767:     - source: 'æ é¢' (text_gdiplus)
12:50:44.767: - scene 'ç¥ç¦ç¥·å':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'è²å' (color_source)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767:     - source: 'cross' (image_source)
12:50:44.767:     - source: 'ç¥ç¦ç¥·åéå¥' (text_gdiplus)
12:50:44.767:     - source: 'ç¥ç¦ç¥·åæ è¯­' (text_gdiplus)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'æ»å¨å­å¹':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'éå¥' (text_gdiplus)
12:50:44.767:     - source: 'æ»å¨æå­' (text_gdiplus)
12:50:44.767:         - filter: 'æ»å¨' (scroll_filter)
12:50:44.767:     - source: 'Logo' (group)
12:50:44.767:         - source: 'cross' (image_source)
12:50:44.767:         - source: 'date&time' (text_gdiplus_v2)
12:50:44.767:         - source: 'é¢æ©å ' (text_gdiplus_v2)
12:50:44.767: - scene 'è¯éåé¡¾':
12:50:44.767:     - source: 'è¯éåé¡¾è§é¢é' (vlc_source)
12:50:44.767:         - monitoring: monitor and output
12:50:44.767: - scene 'ç»ä¸­ç»':
12:50:44.767:     - source: 'æåéå¤´' (scene)
12:50:44.767:     - source: 'OBS-002' (ndi_source)
12:50:44.767: - scene 'é³ä¹åè¾':
12:50:44.767:     - source: 'VLC è§é¢æº' (vlc_source)
12:50:44.767:         - monitoring: monitor and output
12:50:44.767:         - filter: 'åªå£°æå¶' (noise_suppress_filter)
12:50:44.767: - scene 'èªå¨æ²é':
12:50:44.767:     - source: 'cross.mp4' (ffmpeg_source)
12:50:44.767:         - monitoring: monitor and output
12:50:44.767: - scene 'èªå¨æ­æ¾':
12:50:44.767:     - source: 'æ¾ç¤ºå¨æè·' (monitor_capture)
12:50:44.767:         - filter: 'è²å½©æ ¡æ­£' (color_filter)
12:50:44.767: - scene 'æåéå¤´':
12:50:44.767: ------------------------------------------------
12:50:49.433: Switched to Preview/Program mode
12:50:49.433: ------------------------------------------------
12:50:49.758: Switched to scene 'è¯éåé¡¾'
12:50:49.759: Switched to regular Preview mode
12:50:49.759: ------------------------------------------------
12:50:50.096: Switched to Preview/Program mode
12:50:50.096: ------------------------------------------------
12:50:50.254: Switched to scene 'è¯éåé¡¾'
12:50:50.256: Switched to regular Preview mode
12:50:50.256: ------------------------------------------------
12:50:50.447: Switched to Preview/Program mode
12:50:50.447: ------------------------------------------------
12:50:50.590: Switched to scene 'è¯éåé¡¾'
12:50:50.592: Switched to regular Preview mode
12:50:50.592: ------------------------------------------------
12:50:50.766: Switched to Preview/Program mode
12:50:50.766: ------------------------------------------------
12:50:50.926: Switched to scene 'è¯éåé¡¾'
12:50:50.927: Switched to regular Preview mode
12:50:50.927: ------------------------------------------------
12:50:51.317: Switched to Preview/Program mode
12:50:51.317: ------------------------------------------------
12:50:51.630: Switched to scene 'è¯éåé¡¾'
12:50:51.631: Switched to regular Preview mode
12:50:51.631: ------------------------------------------------
12:50:51.965: Switched to Preview/Program mode
12:50:51.965: ------------------------------------------------
12:51:00.979: ---------------------------------
12:51:00.979: [x264 encoder: 'streaming_h264'] preset: veryfast
12:51:00.979: [x264 encoder: 'streaming_h264'] settings:
12:51:00.979: 	rate_control: CBR
12:51:00.979: 	bitrate:      1200
12:51:00.979: 	buffer size:  1200
12:51:00.979: 	crf:          0
12:51:00.979: 	fps_num:      30
12:51:00.979: 	fps_den:      1
12:51:00.979: 	width:        1920
12:51:00.979: 	height:       1080
12:51:00.979: 	keyint:       250
12:51:00.979: 
12:51:00.983: ---------------------------------
12:51:00.983: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 160, channels: 2, channel_layout: 3
12:51:00.983: 
12:51:00.990: ==== Streaming Start ===============================================
12:51:00.990: [ffmpeg muxer: 'adv_stream'] Writing file 'srt://192.168.10.11:10000?mode=listener'...
12:51:02.079: [ffmpeg muxer: 'adv_stream'] os_process_pipe_write for packet data failed
12:51:02.079: [ffmpeg muxer: 'adv_stream'] ffmpeg-mux: Couldn't open 'srt://192.168.10.11:10000?mode=listener', Unknown error occurredCouldn't initialize muxer
12:51:02.079: [srt @ 000001c57a841e80] Connection setup failure: unable to create/configure SRT socket: Í¨³£Ã¿¸öÌ×½Ó×ÖµØÖ·(Ð­Òé/ÍøÂçµØÖ·/¶Ë¿Ú)Ö»ÔÊÐíÊ¹ÓÃÒ»´Î¡£

12:51:02.079: 
12:51:02.079: 
12:51:02.080: [ffmpeg muxer: 'adv_stream'] Output of file 'srt://192.168.10.11:10000?mode=listener' stopped
12:51:02.080: Output 'adv_stream': stopping
12:51:02.080: Output 'adv_stream': Total frames output: 1
12:51:02.080: Output 'adv_stream': Total drawn frames: 33
12:51:02.083: ==== Streaming Stop ================================================
12:51:14.171: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_C' using 'å¹»ç¯ç' for 1000 ms, resize {1920,330}
12:51:44.204: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_A' using 'å¹»ç¯ç' for 1000 ms, resize {1920,330}
12:52:14.238: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_B' using 'å¹»ç¯ç' for 1000 ms, resize {1920,330}
12:52:44.271: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_C' using 'å¹»ç¯ç' for 1000 ms, resize {1920,330}
12:53:14.304: [source-switcher: 'åç¹è½®æ­'] transition to 'åç¹_A' using 'å¹»ç¯ç' for 1000 ms, resize {1920,330}
12:53:27.153: ==== Shutting down ==================================================
12:53:27.165: Advanced Scene Switcher stopped
12:53:27.323: [obs-ndi] audio thread for 'OBS-002' completed
12:53:27.377: All scene data cleared
12:53:27.377: ------------------------------------------------
12:53:27.478: [obs-ndi] goodbye !
12:53:27.493: [Scripting] Total detached callbacks: 2
12:53:27.552: Freeing OBS context data
12:53:27.584: == Profiler Results =============================
12:53:27.584: run_program_init: 3499.08Â ms
12:53:27.584:  â£OBSApp::AppInit: 17.135Â ms
12:53:27.584:  â âOBSApp::InitLocale: 1.663Â ms
12:53:27.584:  âOBSApp::OBSInit: 3382.6Â ms
12:53:27.584:    â£obs_startup: 3.008Â ms
12:53:27.584:    âOBSBasic::OBSInit: 1713.82Â ms
12:53:27.584:      â£OBSBasic::InitBasicConfig: 0.37Â ms
12:53:27.584:      â£OBSBasic::ResetAudio: 0.114Â ms
12:53:27.584:      â£OBSBasic::ResetVideo: 433.86Â ms
12:53:27.584:      â£OBSBasic::InitOBSCallbacks: 0.006Â ms
12:53:27.584:      â£OBSBasic::InitHotkeys: 0.043Â ms
12:53:27.584:      â£obs_load_all_modules: 536.9Â ms
12:53:27.584:      â â£obs_init_module(advanced-scene-switcher.dll): 0.274Â ms
12:53:27.584:      â â£obs_init_module(coreaudio-encoder.dll): 0.388Â ms
12:53:27.584:      â â£obs_init_module(decklink-ouput-ui.dll): 0.497Â ms
12:53:27.584:      â â£obs_init_module(enc-amf.dll): 275.648Â ms
12:53:27.584:      â â£obs_init_module(frontend-tools.dll): 3.304Â ms
12:53:27.584:      â â£obs_init_module(image-source.dll): 0.006Â ms
12:53:27.584:      â â£obs_init_module(obs-browser.dll): 0.254Â ms
12:53:27.584:      â â£obs_init_module(obs-ffmpeg.dll): 0.266Â ms
12:53:27.584:      â â ânvenc_check: 0.253Â ms
12:53:27.584:      â â£obs_init_module(obs-filters.dll): 0.024Â ms
12:53:27.584:      â â£obs_init_module(obs-ndi.dll): 10.67Â ms
12:53:27.584:      â â£obs_init_module(obs-outputs.dll): 0.007Â ms
12:53:27.584:      â â£obs_init_module(obs-qsv11.dll): 215.131Â ms
12:53:27.584:      â â£obs_init_module(obs-text.dll): 0.192Â ms
12:53:27.584:      â â£obs_init_module(obs-transitions.dll): 0.005Â ms
12:53:27.584:      â â£obs_init_module(obs-vst.dll): 0.001Â ms
12:53:27.584:      â â£obs_init_module(obs-x264.dll): 0.002Â ms
12:53:27.584:      â â£obs_init_module(rtmp-services.dll): 0.421Â ms
12:53:27.584:      â â£obs_init_module(source-switcher.dll): 0.001Â ms
12:53:27.584:      â â£obs_init_module(text-freetype2.dll): 0.077Â ms
12:53:27.584:      â â£obs_init_module(vlc-video.dll): 1.313Â ms
12:53:27.584:      â â£obs_init_module(win-capture.dll): 1.12Â ms
12:53:27.584:      â â£obs_init_module(win-decklink.dll): 1.252Â ms
12:53:27.584:      â â£obs_init_module(win-dshow.dll): 1.192Â ms
12:53:27.584:      â â£obs_init_module(win-mf.dll): 0Â ms
12:53:27.584:      â â£obs_init_module(win-wasapi.dll): 0.004Â ms
12:53:27.584:      â âreset_win32_symbol_paths: 0.062Â ms
12:53:27.584:      â£OBSBasic::ResetOutputs: 0.356Â ms
12:53:27.584:      â£OBSBasic::CreateHotkeys: 0.319Â ms
12:53:27.584:      â£OBSBasic::InitService: 0.086Â ms
12:53:27.584:      â£OBSBasic::InitPrimitives: 0.213Â ms
12:53:27.584:      âOBSBasic::Load: 660.141Â ms
12:53:27.584: obs_hotkey_thread(25Â ms): min=0.002Â ms, median=0.01Â ms, max=10.682Â ms, 99th percentile=1.851Â ms, 100% below 25Â ms
12:53:27.584: audio_thread(Audio): min=0Â ms, median=0.044Â ms, max=9.444Â ms, 99th percentile=8.109Â ms
12:53:27.584:  âreceive_audio: min=0.002Â ms, median=0.315Â ms, max=0.846Â ms, 99th percentile=0.846Â ms, 0.00740043 calls per parent call
12:53:27.584:    â£buffer_audio: min=0.001Â ms, median=0.001Â ms, max=0.017Â ms, 99th percentile=0.017Â ms
12:53:27.584:    âdo_encode: min=0.018Â ms, median=0.313Â ms, max=0.813Â ms, 99th percentile=0.813Â ms
12:53:27.584:      âencode(avc_aac_stream): min=0.016Â ms, median=0.311Â ms, max=0.811Â ms, 99th percentile=0.811Â ms
12:53:27.584: obs_graphics_thread(33.3333Â ms): min=0.054Â ms, median=9.85Â ms, max=597.154Â ms, 99th percentile=11.492Â ms, 99.9796% below 33.333Â ms
12:53:27.584:  â£tick_sources: min=0.001Â ms, median=0.017Â ms, max=592.497Â ms, 99th percentile=0.045Â ms
12:53:27.585:  â£output_frame: min=0.05Â ms, median=8.215Â ms, max=9.907Â ms, 99th percentile=9.388Â ms
12:53:27.585:  â â£gs_context(video->graphics): min=0.05Â ms, median=8.214Â ms, max=9.878Â ms, 99th percentile=9.375Â ms
12:53:27.585:  â â â£render_video: min=0.004Â ms, median=8.129Â ms, max=9.803Â ms, 99th percentile=9.286Â ms
12:53:27.585:  â â â â£render_main_texture: min=0.002Â ms, median=8.127Â ms, max=9.802Â ms, 99th percentile=9.284Â ms
12:53:27.585:  â â â â£render_convert_texture: min=0.007Â ms, median=0.008Â ms, max=0.017Â ms, 99th percentile=0.017Â ms, 0.00673332 calls per parent call
12:53:27.585:  â â â âstage_output_texture: min=0.002Â ms, median=0.077Â ms, max=0.123Â ms, 99th percentile=0.123Â ms, 0.00673332 calls per parent call
12:53:27.585:  â â â£gs_flush: min=0.022Â ms, median=0.076Â ms, max=1.044Â ms, 99th percentile=0.201Â ms
12:53:27.585:  â â âdownload_frame: min=0Â ms, median=0.03Â ms, max=0.079Â ms, 99th percentile=0.079Â ms, 0.00673332 calls per parent call
12:53:27.585:  â âoutput_video_data: min=0.24Â ms, median=0.357Â ms, max=1.196Â ms, 99th percentile=1.196Â ms, 0.00652928 calls per parent call
12:53:27.585:  ârender_displays: min=0Â ms, median=1.609Â ms, max=12.518Â ms, 99th percentile=3.289Â ms
12:53:27.585: video_thread(video): min=2.023Â ms, median=2.345Â ms, max=9.185Â ms, 99th percentile=9.185Â ms
12:53:27.585:  âreceive_video: min=2.018Â ms, median=2.343Â ms, max=9.184Â ms, 99th percentile=9.184Â ms
12:53:27.585:    âdo_encode: min=2.018Â ms, median=2.343Â ms, max=9.183Â ms, 99th percentile=9.183Â ms
12:53:27.585:      âencode(streaming_h264): min=2.017Â ms, median=2.342Â ms, max=2.658Â ms, 99th percentile=2.658Â ms
12:53:27.585: =================================================
12:53:27.585: == Profiler Time Between Calls ==================
12:53:27.585: obs_hotkey_thread(25Â ms): min=24.074Â ms, median=25.803Â ms, max=85.938Â ms, 48.7061% within Â±2% of 25Â ms (0.0154036% lower, 51.2785% higher)
12:53:27.585: obs_graphics_thread(33.3333Â ms): min=2.84Â ms, median=33.333Â ms, max=597.16Â ms, 99.9592% within Â±2% of 33.333Â ms (0.0204082% lower, 0.0204082% higher)
12:53:27.585: =================================================
12:53:27.615: Number of memory leaks: 0

**Comment by iesvme** [comment] 2020-09-30 05:16
And when inputting srt://192.168.10.11:10000, it can't stop streaming.

**Comment by Fenrirthviti** [comment] 2020-10-18 23:07
Duplicate of #3588

**Closed by Fenrirthviti** 2020-10-18 23:07 UTC
