### ISSUE TITLE
Undo crash when restoring deleted scene with sources

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#5515] opened 2021-11-11 04:25 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 27.1.3-144-g0815d5c88 (64-bit, windows)

### OBS Studio Log URL

https://obsproject.com/logs/yfgkBu1bEjjz4F_E

### OBS Studio Crash Log URL

https://obsproject.com/logs/EAhC0vxpZqFjVz8n

### Expected Behavior

It will be restored normally.

### Current Behavior

Version: Nightly builds
Crash.

Version : 27.1.3
It doesn't crash, but it doesn't restore properly.

### Steps to Reproduce

Version : Nightly builds
1. Create a scene / scene 2 / scene 3.
2. Add the source to Scene 3. (Browser / Color Source)
3. Add Scene 3 to Scene and Scene 2.
4. Delete Scene 3.
5. Restore Scene 3. (undo)
6. It will not be restored and OBS will crash.

Version : 27.1.3
1. Create a scene / scene 2 / scene 3.
2. Add a source to Scene 3. (Browser / Color Source)
3. Add Scene 3 to Scene and Scene 2.
4. Delete scene 3.
5. Restore Scene 3. (undo)
6. It doesn't crash, but it doesn't restore properly.

### Anything else we should know?

https://user-images.githubusercontent.com/1337354/141227049-c65331bb-fa5a-4443-97db-8034a1020544.mp4

We are using translation. We apologize if the English is not correct.

This is a different problem from the previous report. I apologize for the confusing title.

**Comment by RytoEX** [comment] 2021-11-11 04:42
I would guess that the reason it crashes in the current git builds is because https://github.com/obsproject/obs-studio/commit/a7e0affd36c547292fc5ae83a767d0ef2c1125fa (#5495) was merged.  @gxalpha ?

**Comment by WizardCM** [comment] 2021-11-11 04:48
In future, if a fix for a previously reported Issue changes the behaviour but does not fix the issue, please comment on the original Issue report so that it can be reopened.

**Comment by style1925** [comment] 2021-11-11 05:21
Thank you for changing the title.
I understand!

**Comment by gxalpha** [comment] 2021-11-11 06:15
I can confirm this is an issue, however: The issue described in the 27.1.3. section seems to appear in both 509e44d6ea4cdbf42e7a4314be12960cc58e36a5 and a7e0affd36c547292fc5ae83a767d0ef2c1125fa.
Simple repro steps: Scene 1 in Scene 2 -> Delete Scene 1 -> Undo -> Scene 1 not recreated in Scene 2
I got it to crash once, but couldn't reproduce it so far. I'll do more testing later.

**Comment by gxalpha** [comment] 2021-11-12 08:36
To follow up on this: I found out what's going on, the tldr is:
When deleted, the scene doesn't get destroyed if it's nested in multiple other scenes (though it should get destroyed). The crash on master/wrong recreation in 27.1 is a symptom of that problem.

**Closed** 2021-11-24 06:00 UTC
