### ISSUE TITLE
No audio in Twitch stream after reconnecting when using the Twitch VOD Track

### ISSUE THREAD

**Issue by badasafish** [obsproject/obs-studio#6101] opened 2022-03-07 21:36 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/EyvsoKCTI2fZwgP3

### Expected Behavior

I expected to be able to reconnect and the audio would be just as before the reconnection. i.e. mic, game sounds, music all audible with the music not being passed into the Twitch VOD.

### Current Behavior

Upon reconnecting there was zero audio in the stream or the VOD.  The only way to fix this was to stop and restart the stream which is far from ideal.

### Steps to Reproduce

1. Start streaming with the "Twitch VOD Track" enabled.
2. Force disconnection by disabling network adaptor.
3. Automatically reconnects with no audio.

Repeat the above but uncheck the "Twitch VOD Track" and the reconnect will occur with audio as expected.

**Comment by Fenrirthviti** [comment] 2022-03-07 21:40
Duplicate of https://github.com/obsproject/obs-studio/issues/5572

**Closed by Fenrirthviti** 2022-03-07 21:40 UTC
