### ISSUE TITLE
[Audio Mixer UI Bug] Weirdly Shaky Volume decibel info on v28

### ISSUE THREAD

**Issue by JoqniX** [obsproject/obs-studio#7343] opened 2022-09-11 05:49 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Um5IwHnFl5kFVjlN

### Expected Behavior

Audio Source Volume changes should have updated normally~ like it should in previous versions before v28~

and should give out the accurate volume data on the ui, and on obs-ws when pulled for volume data~ 

### Current Behavior

Audio Source Volume, seems to act weirdly if you manually / automatically ( via obs-ws) change volume~ and also seems to mess up the volume data if its been read by obs-ws
 

### Steps to Reproduce

The following Steps of Reproduction will be split into 2 parts / versions ( one without the use of SAMMI, and with use of SAMMI ) 

( Without the use of Sammi - ( normal use ) ( not using any applications which is connected to obs-ws etc )
1.  Launch OBS v28.0.1
2.  Go to any Audio source, you see on your Audio Mixer
3. Now try to change the volume of the source, by dragging the volume slider~
4. while dragging make sure, to drag it to left ( 0% =-inf ) and right (100% = 0.0db) , and keep it in random positions between 0% and 100% and check if it does the shaky thingy~ and dances around www xD 

( With the use of SAMMi  ( must be connected to obs-websocket4.9.1 QT6 compati / default obsv28 obswebsocket 5) 

1. Launch OBS v28.0.1 ( you can choose to launch SAMMI before or after obs launch ( no changes , same result on both ) 
2. Make sure you are connected to OBS via SAMMI 
3. you need to pull the source value of your audio sources ( here we need to pull volume / volume dB ) 
make a button in SAMMI, add the command -> OBS Pull Source Value > direct it to the source you want to check for volume,  put the pull value as Volume / or Volume dB, and make sure to save this as a variable ( give it any name you want) 

Put this on a Re-enable Command so this button gets triggered every 2s checking for volume updates in obs 

4. right click on the button and add a trigger for obs connected, ( so it starts when its connected to websocket) 
5. open the variable viewer in sammi and locate your button ID ( of the button you made in SAMMI - it can be found on the button when it double click it,) and check your variable ( now keep an eye on this ) 
6. try changing your volume in obs ( repeat the same step from 4*  [ normal use ( the one above this part ) ]
7. notice that the values is not accurate at all? and keeps on changing even if you didnt change the volume ( tho its still dancing around in obs ) 

*note to the dev reviewer of this bug
if these 2 parted steps above is hard to do ( especially  the 2nd part , if you're not used to using SAMMI ) i've provided an video example of both versions mentioned here~ 

Video Examples of this bug~
Normal Use w/o use of any software version  -> https://youtu.be/IlgttqVKbOk
using Sammi version -> https://youtu.be/oaXaZ26vQdU

Gif Examples - https://cdn.discordapp.com/attachments/1003138527200026634/1018390818391851048/NVIDIA_Share_NoPWWaNJaL.gif
https://cdn.discordapp.com/attachments/871139421892788294/1016747602286485544/NVIDIA_Share_iEgkIW6sl6.gif

### Anything else we should know?

This bug was found on OS - win11 insider~ ( OS build -22622.590) 

This bug was reported to both obs-websocket discord and to SAMMI discord too~ seems its not from their end. 

also the application im using "SAMMI" is currently having some crashing issues when connecting to ws5,  which would be fixed in their next patch i believe~ ( but the video examples were tested on obsws4.9.1 qt6 compati ( latest version) and on sammi version 2022.4.3  

this bug was found on obsv28 release ( v28.0 - v28.0.1) ~

ngl those dB seems to be grooving xD 

i hope this bug could be fixed ~ my whole obs setup for changing volume per scene switch, and other volume automations has been affected. but yea i hope the devs could fix this~ 

thank you for always working hard obs team <3

**Comment by WizardCM** [comment] 2022-09-11 05:54
I can't reproduce this with vanilla 28.0.1 without any plugins connected via websocket.

**Comment by JoqniX** [comment] 2022-09-11 06:20
> I can't reproduce this with vanilla 28.0.1 without any plugins connected via websocket.
i just tried to reproduce on a portable  fresh obs28.01 on ws5. seems this bug cant be reproduced~ 
tried it on my stream pc ( one i reproduced this bug on my main obs)  , and game pc~ 

if its being caused by a plugin? i wonder which one is the culprit here causing this? 
and most of these audio sources just has a limiter filter~

**Comment by WizardCM** [comment] 2022-09-11 06:36
Very likely. You have the following third party plugins installed

```
09:53:48.326:   Loaded Modules:
09:53:48.326:     win-spout.dll
09:53:48.326:     win-capture-audio.dll
09:53:48.326:     waveform.dll
09:53:48.326:     virtual-cam-filter.dll
09:53:48.326:     transition-table.dll
09:53:48.326:     time-warp-scan.dll
09:53:48.326:     streamup.dll
09:53:48.326:     StreamFX.dll
09:53:48.326:     spectralizer.dll
09:53:48.326:     source-switcher.dll
09:53:48.326:     source-record.dll
09:53:48.326:     source-dock.dll
09:53:48.326:     source-copy.dll
09:53:48.326:     scrab.dll
09:53:48.326:     scene-notes-dock.dll
09:53:48.326:     scene-collection-manager.dll
09:53:48.326:     recursion-effect.dll
09:53:48.326:     obs_scene_tree_view.dll
09:53:48.326:     OBSInfoWriter.dll
09:53:48.326:     obs-teleport.dll
09:53:48.326:     obs-soundboard.dll
09:53:48.326:     obs-shaderfilter.dll
09:53:48.326:     obs-ndi.dll
09:53:48.326:     obs-midi-mg.dll
09:53:48.326:     move-transition.dll
09:53:48.326:     gradient-source.dll
09:53:48.326:     freeze-filter.dll
09:53:48.326:     dynamic-delay.dll
09:53:48.326:     durchblick.dll
09:53:48.326:     downstream-keyer.dll
09:53:48.326:     advanced-scene-switcher.dll
```

It could be any one of them, or a combination of them.

**Comment by JoqniX** [comment] 2022-09-12 10:45
update~ 
so i tried using all these plugins from main obs (the one i had encountered this bug on) so apparently i dont see this happen on a portable fresh obs~ having all these plugins installed~ ah im so  confused what is going on~ can be cuased by cache or something? ill try to do more tests~ and report back here~

**Comment by RytoEX** [comment] 2022-09-12 11:38
Add your plugins back one-by-one and test for the issue each time. When you finally reproduce the issue again, write down the name of the last plugin that you added. Then, remove all plugins except the last one that you added, and retest. If you can reproduce the issue with just that plugin, then it's likely caused by that one plugin.

**Comment by PatTheMav** [comment] 2022-09-19 20:40
@JoqniX please confirm if the issue still persists without 3rd party plugins as discussed in the thread?

**Comment by JoqniX** [comment] 2022-09-20 00:41
> @JoqniX please confirm if the issue still persists without 3rd party plugins as discussed in the thread?

Ahh sorry~ i wasn't able to test it recently due to being busy~ but now im back~ 

so yea~ I FINALLY FOUND IT~ 

The culprit was audio monitor plugin~ by exeldro~ 
( i did even check by adding the latest version of it and the issue still persists~ )

**Comment by JoqniX** [comment] 2022-09-20 00:53
sadly i cant reproduce this in a fresh build?? 
adding the audio monitor plugin~ TuT now im really confused~ what is really going on~

**Comment by JoqniX** [comment] 2022-09-20 01:11
https://user-images.githubusercontent.com/54277349/191145606-c0240b2f-9683-4286-9b01-029332ba620a.mp4

yup~ its still going brrrr~ ( deleted scenes and profiles in this config folder)

**Comment by RytoEX** [comment] 2022-09-20 02:37
If this bug is caused by the audio-monitor plugin, please report this on that plugin's GitHub repository: https://github.com/exeldro/obs-audio-monitor

**Comment by JoqniX** [comment] 2022-09-20 02:53
if exeldro is hopping on here~ or someone else~ who can check this config file of audio monitor ~ do read this okie~ or to reproduce this bug~ just add this to your config > plugin_config > extract the zip there~ ( sadly github didnt allow to upload json file so yea~ )
[audio-monitor.zip](https://github.com/obsproject/obs-studio/files/9603609/audio-monitor.zip)

i tried deleting each items from plugin_config folder~ ( at first i thought it might be "obs-browser" cuz it's file size was like 800mb or so~) but yea the culprit was audio monitor file~ 

which i quote
> (when deleting config > plugin_config > audio monitor file~)
seems the bug is angry now~ it just grovved so hard when i dragged the slider from 0 to 100 ( 0.0db) and in time it slowed down? wahh

here i said that~ it seemed to reproduce the bug when deleting it from plugin_config~ hmm idk what's happening but ill try doing more testing on this~

**Comment by JoqniX** [comment] 2022-09-20 02:54
> If this bug is caused by the audio-monitor plugin, please report this on that plugin's GitHub repository: https://github.com/exeldro/obs-audio-monitor

oh okie~ ill do that ~ thank yu

**Comment by Fenrirthviti** [comment] 2022-09-20 19:41
Closing per above, as this has been reported to the audio monitor repo.

**Closed by Fenrirthviti** 2022-09-20 19:41 UTC

**Comment by joelcarlton** [comment] 2022-10-02 16:29
We are having this issue as well.
