### ISSUE TITLE
fish: Job 1, '/usr/bin/obs' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by tetoNidan** [obsproject/obs-studio#9817] opened 2023-11-06 18:11 UTC
### Operating System Info

Other

### Other OS

Arch - Garuda

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://pastebin.com/ZD57bHKW

### Expected Behavior

Open ODS-Studio

### Current Behavior

Crashes with: fish: Job 1, '/usr/bin/obs' terminated by signal SIGSEGV (Address boundary error)

### Steps to Reproduce

1. Open osb from terminal or .desktop file
2. Wait for error if using terminal or view log if not

### Anything else we should know?

Im not sure where the obs crash logs are kept? Is it the sable location as the log file? I would like to provide the best information I can so let me know if there is something not provided and if there is something I can do to help.

I did notice that it was complaining about:

1. decklink-captions.so
2. decklink-output-ui.so
3. decklink.so

So I thought that I might try to install `decklink-apk` from the AUR but this did not help. I also noticed there are other AUR packages like `ffmpeg-decklink` but I haven't tried to install them.

Any way let me know if there is more info I can provide and thanks for OBS Studio, really is the best screen capture software I've used.

**Comment by Fenrirthviti** [comment] 2023-11-06 18:20
Please also provide a gdb backtrace of the crash.

**Comment by fzwoch** [comment] 2023-11-06 18:23
Looks like https://github.com/obsproject/obs-studio/issues/8056

**Comment by tytan652** [comment] 2023-11-06 18:40
Please check my comments on the issue that @fzwoch mentionned.

**Comment by tetoNidan** [comment] 2023-11-06 18:42
Reading Paethon's commnet led me to search for `libva-vdpau-driver` and it is installed and he said removing it solved the issue. I think your right. I will talk to Garuda and see if removing it is a good idea as `garuda-video-linux-config` is the only Required By in the `pacman -Qi libva-vdpau-driver`

I will talk to garuda and get back to you after removal of the driver to confirm the issue is indeed solved.

Thanks!

**Comment by tetoNidan** [comment] 2023-11-06 21:16
Still waiting for Garuda team to get back to me. Thought I'd do my best to give you all a `gdb` as you asked. I have never done this before so my apologies of this isn't what you need. I had to follow an older tutorial.

Here is what I've got:
https://pastebin.com/Td71KgWf

**Comment by tytan652** [comment] 2023-11-06 21:20
```
#0  XDisplayString (dpy=0x0) at /usr/src/debug/libx11/libX11-1.8.7/src/Macros.c:119
#1  0x00007fff95445a1d in __vaDriverInit_1_13 () at /usr/lib/dri/nvidia_drv_video.so
```

Duplicate of #8056

**Comment by tytan652** [comment] 2023-11-06 21:20
Duplicate of #8056

**Closed** 2023-11-06 21:21 UTC

**Comment by tytan652** [comment] 2023-11-06 21:22
Feel free to link the distribution issue/thread link for other Garuda user.
