### ISSUE TITLE
Lua: Many API functions and constants available in 27.2.4 aren't available in a build of recent master

### ISSUE THREAD

**Issue by OldBaldGeek** [obsproject/obs-studio#6539] opened 2022-05-25 15:42 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0-431-gfb639e303 (64-bit) 5/24/2022 11:29:46 AM from obsbot.rodney.io, and in my local builds

### OBS Studio Log URL

https://obsproject.com/logs/mQ7E5p4qKMgVD4M8

### Expected Behavior

Lua should be able to call API functions such as obs.obs_frontend_get_current_scene and obs.obs_frontend_get_current_preview_scene.

Lua should be able to use API constants such as obs.OBS_FRONTEND_EVENT_SCENE_CHANGED

These items work in the 27.2.4 (64 bit) release, and worked in earlier versions at least back to 27.1.3.

Examples of use may be found in scripts such as refresh-browser-specific.lua [https://obsproject.com/forum/resources/reload-browser-in-preview-scene.1030/](url)

obs-schedulecountdown.lua [https://obsproject.com/forum/resources/advanced-countdown-with-schedule.1306/](url)

obs-visca-control-1.6 [https://obsproject.com/forum/resources/control-visca-over-ip-based-cameras.1173/](url)

### Current Behavior

Lua can call obs.obs_frontend_get_current_scene, but obs.obs_frontend_get_current_preview_scene fails, claiming nil value. 
Various other functions are also missing.

Similarly, many constants such as obs.OBS_FRONTEND_EVENT_SCENE_CHANGED are nil.

The attached script explicitly tests several functions and constants for undefined/nil. Results are shown in the log and in the script UI
[wtf.lua.txt](https://github.com/obsproject/obs-studio/files/8772507/wtf.lua.txt)

### Steps to Reproduce

1. Build master, or get a build from obsbot.rodney.io
2. Run OBS, and install wtf.lua, or one of the scripts listed in "Expected Behavior"
3. Script UI will show results for wtf.lua
4. For refresh-browser-specific.lua, pressing the "Refresh Browsers" button will log an error
5. For the other mentioned scripts, some configuration is required. But inspection of the code shows usage of the missing items.
...

**Comment by RytoEX** [comment] 2022-05-26 03:15
Testing out each of these items...

While a call to `obs.obs_frontend_get_current_preview_scene()` does not fail in 27.2.4, a subsequent call to `obs.obs_source_get_name(scene)` returns nil. Does this actually work as expected in 27.2.4? As far as I can tell, it doesn't. I think that the current CI builds are correct here in that I don't think that function is actually exposed to scripting.

`obs.OBS_FRONTEND_EVENT_SCENE_CHANGED` is the only thing that you've explicitly mentioned/tested that seems to have changed between 27.2.4 and now. Rather, the obs_frontend_event enum seems to now be inaccessible/undefined in Lua. From a quick bisect of CI artifacts, this appears to be due to #5155. I will defer to @PatTheMav on what's happening there.

`obs.OBS_EDITABLE_LIST_TYPE_STRINGS` returns `0`, while `obs.OBS_EDITABLE_LIST_TYPE_FILES` returns 1, which are the expected values. I didn't test all of the enums in [`libobs/obs-properties.h`](https://github.com/obsproject/obs-studio/blob/30b8987badbb33818bf39dc6ec0e63ff50ff74ac/libobs/obs-properties.h), but I'd expect them to be fine.

**Comment by OldBaldGeek** [comment] 2022-05-26 13:36
The items mentioned in my report are _examples_ of missing items: that's why I said "such as." I can work up an exhaustive list if necessary, but I presume that these are processed in bulk (by SWIG?), so that if we find the cause for one or a few omissions, that will affect the others as well.

`obs.obs_source_get_name(scene)` returns nil if "scene" is nil, but works in old and current build for valid scenes. If you are using wtf.lua for your tests, remember that the first call to `script_defaults` happens before any scenes are loaded, so `obs.obs_frontend_get_current_scene` will return nil. If you use the circled-arrows button in the script dialog to refresh the script, scene will be non-nil and you will get a name. wtf.lua was intended as a simple-as-possible demo of the bug, not as a useful script.

I listed three scripts from the obs forums (found in a few minutes searching) that are broken under the current build, to indicate that these items clearly worked and were used by other people under previous builds. And every Sunday I run a stream using three of my scripts that work fine in 27.2.4 and earlier but not in the current build.

The missing `obs.OBS_FRONTEND_EVENT_XXX` constants are necessary for sane use of `obs.obs_frontend_add_event_callback,` since the event reported to the callback IS one of those constants.

Please let me know if you need me to provide a more extensive list of formerly available items that are missing in the current build.

I don't use Python with OBS, but I would be surprised if these same items are NOT broken for Python scripts as well.

**Comment by RytoEX** [comment] 2022-05-26 13:54
> `obs.obs_source_get_name(scene)` returns nil if "scene" is nil, but works in old and current build for valid scenes. If you are using wtf.lua for your tests, remember that the first call to `script_defaults` happens before any scenes are loaded, so `obs.obs_frontend_get_current_scene` will return nil. If you use the circled-arrows button in the script dialog to refresh the script, scene will be non-nil and you will get a name. wtf.lua was intended as a simple-as-possible demo of the bug, not as a useful script.

Yes, I refreshed the script quite often to test after the scene collection was loaded. `obs.obs_source_get_name(scene)` returns nil in all cases, as I described. If you enable Studio Mode, it does suddenly return a scene name, which seems odd to me, as I'd expect the preview/program scene to always be the current scene when not in Studio Mode, but that's a problem for another day.

Since I can see that it does return a scene name when in Studio Mode, I can more or less conclude that the breakage has the same root cause.
 
> The missing `obs.OBS_FRONTEND_EVENT_XXX` constants are necessary for sane use of `obs.obs_frontend_add_event_callback,` since the event reported to the callback IS one of those constants.

I'm aware, and I did not contest that they are necessary. I simply pointed to when the breakage likely occurred. Thank you for your patience while we sort this out.

> Please let me know if you need me to provide a more extensive list of formerly available items that are missing in the current build.

I've already done a pretty thorough investigation while looking into this Issue, but thank you for the offer.

**Comment by OldBaldGeek** [comment] 2022-05-27 21:56
I just did a checkout aa2a819ad1c5f0cbba9eeea288ac462a11fc9df3 (roughly May 1 2022) and the issue exists in a build of that as well.

**Comment by RytoEX** [comment] 2022-05-27 22:28
> I just did a checkout [aa2a819](https://github.com/obsproject/obs-studio/commit/aa2a819ad1c5f0cbba9eeea288ac462a11fc9df3) (roughly May 1 2022) and the issue exists in a build of that as well.

Yes. As I said, the issue is caused by #5155, which was merged back in March. I've already confirmed this and pinged @PatTheMav for further investigation, and he has already been in touch with me off-thread.

**Closed** 2022-05-28 23:23 UTC
Labels: Regression, Confirmed
