### ISSUE TITLE
Segmentation fault on `pipewire.c:492` (drm_formats)

### ISSUE THREAD

**Issue by 0x656b694d** [obsproject/obs-studio#9916] opened 2023-11-25 11:18 UTC
### Operating System Info

Other

### Other OS

Fedora 39

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/PygioQRR0h5etE9B

### OBS Studio Crash Log URL

https://obsproject.com/logs/PygioQRR0h5etE9B

### Expected Behavior

No crash

### Current Behavior

Crash, sometimes.

### Steps to Reproduce

1. Make a scene with pipewire window capture
2. Restart OBS
3. Observe a crash, too often.
...

### Anything else we should know?

Crashed with flatpak version. I then installed OBS via dnf, ran into a similar crash, and then ran under gdb to get the backtrace.
Intel integrated graphics.

**Comment by tytan652** [comment] 2023-11-25 11:36
Duplicate of #9844

**Comment by tytan652** [comment] 2023-11-25 11:37
Please provide a backtrace

**Comment by theHamsta** [comment] 2023-11-25 12:30
Could you apply https://github.com/obsproject/obs-studio/pull/9845/files `n_drm_formats` not properaly initialized could cause a reference of a NULL drm_formats as shown in your stacktrace https://obsproject.com/logs/PygioQRR0h5etE9B (see end of log)
```
(gdb) print n_drm_formats
$3 = 140733193388078
```

**Comment by tytan652** [comment] 2023-11-25 12:33
Sorry, I didn't that your log contained the backtrace.

**Comment by tytan652** [comment] 2023-11-25 12:34
Duplicate of #9844

**Closed by tytan652** 2023-11-25 12:34 UTC
