### ISSUE TITLE
Crackly monitoring, reducing the output makes it worse

### ISSUE THREAD

**Issue by rmnvgr** [obsproject/obs-studio#4759] opened 2021-05-26 08:25 UTC
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

https://obsproject.com/logs/MspCsI_8LpqbrChn

### Expected Behavior

The monitoring audio is fine. When reducing the source output volume, the source sounds quieter in the monitor.

### Current Behavior

At normal volume, the output in the monitor is crackly. Reducing the source output volume doesn't make it quieter in the monitor but more crackly.

Only the monitoring is affected, when recording the output everything sounds fine.

All audio sources are affected: Media sources, Pulseaudio capture sources, Jack sources.

After some time there's also a noticeable delay in the monitoring: reducing the output volume or scrubbing the media source take several seconds before being heard in the monitor.

---

**Recording of a media source in "Monitoring only"** (warning, high volume levels):

https://user-images.githubusercontent.com/66537460/119626215-423ace80-be0b-11eb-81d1-ffbd5d488d28.mp4

**Recording of the same media source in "Monitoring disabled"**:

https://user-images.githubusercontent.com/66537460/119626602-b1182780-be0b-11eb-9042-d34cfa95a375.mp4

### Steps to Reproduce

1. Add a media source
2. Go in advanced audio settings and set it as "Monitoring and output"
3. Adjust the output volume

### Anything else we should know?

- GNOME 40
- Flatpak OBS Studio 27.0.0-rc6
- Pipewire 0.3.28

**Comment by dodgepong** [comment] 2021-05-26 15:36
Does this happen on v26.1?

**Comment by rmnvgr** [comment] 2021-05-26 19:06
Yes, it also happens on 26.1.

**Comment by kkartaltepe** [comment] 2021-05-26 19:12
Please replicate with pulseaudio instead of pipewire.

**Comment by rmnvgr** [comment] 2021-05-26 20:20
It doesn't seem to happen with Pulseaudio. I've open an issue on Pipewire repository: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1238

**Comment by kkartaltepe** [comment] 2021-06-14 02:04
Closing as a dupe of #3664, likely since pipewire doesnt grow the buffer you get crackling instead of latency.

**Closed by kkartaltepe** 2021-06-14 02:04 UTC

**Comment by XRohitKS** [comment] 2022-08-27 05:32
I also got issue with pipewire .
so i uninstalled the pipewire-pulse module and it start working fine as before.
