### ISSUE TITLE
NVENC error on Kepler's GPU

### ISSUE THREAD

**Issue by kartavkun** [obsproject/obs-studio#10479] opened 2024-04-04 11:52 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/aLg4H9WToBzvvIyt

### Expected Behavior

Start recording video or start streaming via NVENC H.264 codec.

### Current Behavior

OBS gave me an error message "The installed NVIDIA driver does not support this NVENC version, try updating the driver." But NVENC works fine on OBS 29.1 version. 

### Steps to Reproduce

1. Download OBS latest version via Steam
2. Turn on portable mode for OBS, to import my settings, scenes and other stuff
3. Make sure I have NVENC as a codec on "Output"
4. Press button "Start recording" or "Start streaming"
5. Got an error message about NVENC

### Anything else we should know?

I have GTX 650, and before OBS 30.1.1 I had a good expirience, but then I reinstalled Windows another time, I tried to stream and got an error message about NVENC. I installed latest driver(472.12), but it doesn't helped me. I tried OBS 29.1 version and IT WORKS FINE. 
Updated: I got the same error on Arch Linux with NVIDIA proprietary drivers. I haven't tested on OBS 29.1, but the fact is that it doesn't work on 30.1.1.
Updated 2: I checked OBS 30.0.2 it works fine too. I've read patch notes for 30.1 and didn't find any mention about old GPUs and support for them

**Comment by kartavkun** [comment] 2024-04-04 11:56
Updated: I got the same error on Arch Linux with NVIDIA proprietary drivers. I haven't tested on OBS 29.1, but the fact is that it doesn't work on 30.1.1.

**Comment by fzwoch** [comment] 2024-04-04 12:23
Feels like #10445.

**Comment by Mister36MN** [comment] 2024-04-04 14:02
Kepler GPUs are no longer supported due to necessary updates to the Nvidia SDKs as of 30.1

![image](https://github.com/obsproject/obs-studio/assets/36009507/aa20307e-ab90-4e7c-9a4e-76be48e8146e)

**Comment by RytoEX** [comment] 2024-04-04 14:28
Duplicate of #10431

**Closed by RytoEX** 2024-04-04 14:28 UTC

**Comment by kartavkun** [comment] 2024-04-06 15:09
Today OBS released an update 30.1.2 and fixed my problem, so my issue is solved
![image](https://github.com/obsproject/obs-studio/assets/69749101/af8d599f-649a-4804-9c44-bb3977319982)
