### ISSUE TITLE
OBS 26.1 crashes in MacOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by lgarrido** [obsproject/obs-studio#3957] opened 2020-12-22 13:12 UTC
Operating system and version: MacOS 10.13.6 (High Sierra)
OBS Studio version: 26.1

OBS 26.0.2 does work fine. However, OBS 26.1 crashes. Relevant part from the crash report, a full version can be provided on request.

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

```

**Comment by dodgepong** [comment] 2020-12-22 13:16
Duplicate of https://github.com/obsproject/obs-studio/issues/3887

**Closed by dodgepong** 2020-12-22 13:16 UTC
