### ISSUE TITLE
No screen capture!

### ISSUE THREAD

**Issue by slackjeff** [obsproject/obs-studio#4836] opened 2021-06-08 02:27 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.0

### OBS Studio Version (Other)

27.0.0

### OBS Studio Log URL

https://slackjeff.com.br/2021-06-07%2022-27-41.txt

### Expected Behavior

Show display monitor

### Current Behavior

Display monitor dont show

### Steps to Reproduce

1. Open obs
2. Source Display DONT SHOW
3. 
...

**Comment by mihawk90** [comment] 2021-06-08 03:01
Install pipewire.
It is a hard dependency on the Arch package and still marked as optional in it.

Complain to your package maintainer.

Arch package is *not* provided by the OBS Team.

**Comment by WizardCM** [comment] 2021-06-08 03:09
Duplicate of #4823

**Closed by WizardCM** 2021-06-08 03:09 UTC
