### ISSUE TITLE
Accessibility problems

### ISSUE THREAD

**Issue by gabrielschuck** [obsproject/obs-studio#3627] opened 2020-10-18 03:07 UTC
Hi! I am a screen reader user and I am no longer able to access the start and stop recording / transmission buttons. I had to go back to the version I was using (25.0.8). Could they solve this problem? Thanks!

**Comment by WizardCM** [comment] 2020-10-18 03:09
Duplicate of #3524

**Closed** 2020-10-18 03:10 UTC
