### ISSUE TITLE
Crash on exit (obs-browser.dll!BrowserClient::OnConsoleMessage+0xa1)

### ISSUE THREAD

**Issue by iarspider** [obsproject/obs-studio#7707] opened 2022-11-02 17:41 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/dTLisKZ3rNqL6_6N

### OBS Studio Crash Log URL

https://obsproject.com/logs/GTRMAGv2xvTbtGX_

### Expected Behavior

Exit cleanly

### Current Behavior

OBS displays crash message after closing. I am unable to close that message normally, the message box just hangs.

### Steps to Reproduce

1. Start OBS
2. Wait a bit for the browsers to load
3. Close OBS
...

**Comment by cr08** [comment] 2022-11-02 19:07
Had the same thing occur on my machine when upgrading to 28.1. Would run fine until closing out and then it would crash and the error popup would be completely frozen and require you to end task in task manager. And this has been 100% consistent every run.

Sadly I was dumb and forgot to back up my profile before I did some additional checking and troubleshooting, but I had some old browser sources in a buried scene that pointed to some VDO.Ninja pages. Once I deleted those it seemed to clear it up. I still have a ton of other browser sources but they are all SE overlays (I also have a weather widget page but that is still in here and seems to be behaving).

Crash log:
https://obsproject.com/logs/s9jX3Fdsrlz4nG4E

Running log pre-browser source removal:
https://obsproject.com/logs/w3cy8VP3OWAEcKZ5

New running log:
https://obsproject.com/logs/T2QxfQhI7EN-7kex

I'll have to see if maybe I can replicate this again or find a profile backup if I still have one somewhere.

**Comment by WizardCM** [comment] 2022-11-02 22:40
Uh oh, this is likely my fault. We didn't change much in the browser in 28.1, but I did touch the function that's crashing https://github.com/obsproject/obs-browser/commit/d31b5fc467b79315666a4ba72e0058faad09268b

**Comment by WizardCM** [comment] 2022-11-02 22:50
Those of you who have run into this issue, could you also upload the `debug.log` file that's in `bin\64bit\` alongside your `obs64.exe`?

**Comment by WizardCM** [comment] 2022-11-02 23:07
Note: my current running theory is that this crash occurs specifically when a webpage loaded by a browser source tries to log an error right as the source has been destroyed, but before the browser component has unloaded.

I haven't been able to reproduce it myself yet, but a session log up to the point of the crash might help provide insight.

**Comment by cr08** [comment] 2022-11-03 01:12
Unfortunately no debug log on my machine. I did manage to find a scene backup with the culprit browser sources and on loading that, the crash came back like clockwork. Still no debug log in this state. If there's a way to turn it on, I'd be happy to do so.

Here's the URL's of what I believe are the culprit browser sources on my end:

https://vdo.ninja/beta/?view=pifgicT

https://streamkit.discord.com/overlay/voice/813231241646178305/818164599639375893?icon=true&online=true&logo=white&text_color=%23ffffff&text_size=14&text_outline_color=%23000000&text_outline_size=0&text_shadow_color=%23000000&text_shadow_size=0&bg_color=%231e2124&bg_opacity=0.95&bg_shadow_color=%23000000&bg_shadow_size=0&invite_code=&limit_speaking=false&small_avatars=false&hide_names=false&fade_chat=0

https://vdo.ninja/?view=FerdamLoL&scene&room=DERP&password=DERP&as&meterstyle=1&aec=no&denoise=0&ab=320&vb=6000&mvb=10000&obsfix=0&codec=vp9&quality=1&s=1

I did get a DOM exception in one of my logs for one of the VDO browser sources, but removing that specific source and restarting OBS did not resolve the crash. So far none of the other culprit browser sources are producing any entries in the main log file.

`[obs-browser: 'Browser 3'] Error: [object DOMException] (https://vdo.ninja/beta/webrtc.js?ver=528:1)`

**Comment by cr08** [comment] 2022-11-03 01:21
I think maybe I've narrowed it down to the discord streamkit overlay on this end. I also have some custom CSS in that too (basically the common tutorial code for doing fancy avatar popups on screen):

````
li.voice-state:not([data-reactid*="160922867494682625"]) { display:none; }
.avatar {
content:url(https://cdn.discordapp.com/attachments/813231242362880020/909612208328159282/breadnon_inact.png);
  height:auto !important;
  width:auto !important;
  border-radius:0% !important;
  filter: brightness(50%); 
/*Change brightness to 100%, if you don’t want the image to dim*/
}

.speaking {
  border-color:rgba(0,0,0,0) !important;
  position:relative;
  animation-name: speak-now;
  animation-duration: 1s;
  animation-fill-mode:forwards;
  filter: brightness(100%);
content:url(https://cdn.discordapp.com/attachments/813231242362880020/909612211062833202/breadnon_act.png);
}

@keyframes speak-now {
  0% { bottom:0px;  }
  15% { bottom:10px;  }
  30% { bottom:0px;  }
}

li.voice-state{ position: static; }
div.user{ position: absolute; left:40%; bottom:5%; }

body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }
````

**Comment by WizardCM** [comment] 2022-11-03 02:22
I have verified the issue and confirmed the cause. Some browser sources print errors to the console when shutting down, which my code was not built to handle.

**Closed** 2022-11-03 02:26 UTC
Labels: Confirmed
