### ISSUE TITLE
When pasting sceneitems (>1) as references, they all share the same transform properties.

### ISSUE THREAD

**Issue by MarioMey** [obsproject/obs-studio#5437] opened 2021-10-21 18:21 UTC
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

27.1.3

### OBS Studio Log URL

Nop.

### Expected Behavior

When coping several sceneitems-references of the same source, when pasting them, every sceneitem should maintain its original transform properties (position, rotation, crop, etc).

### Current Behavior

Every sceneitem pasted has the same transform properties as the last selected when copied.

### Steps to Reproduce

1. Create a Capture Window source.
2. Crop it to show just a portion of the window.
3. Copy and paste it as reference. Change its tranform properties (for example, crop)
4. Do it more times or just two
5. Select all of that sceneitems and copy them.
6. Go to another scene, paste them as references.
7. Ta-dan! They all have the same transform properties.
...

### Anything else we should know?

Example. Sceneitems copied:
![imagen](https://user-images.githubusercontent.com/4954109/138334543-293e7710-2d41-4795-99db-671107c4deb1.png)

Sceneitems pasted as references:
![imagen](https://user-images.githubusercontent.com/4954109/138334682-20aafad4-374c-41a5-a5d1-9e0369411c45.png)

After moving them a bit:
![imagen](https://user-images.githubusercontent.com/4954109/138334772-a53bdd56-01d2-49a3-b5bd-982151b5ccd8.png)

**Comment by WizardCM** [comment] 2021-10-21 22:02
Duplicate of #3632

**Closed by WizardCM** 2021-10-21 22:02 UTC
