### ISSUE TITLE
YouTube HLS Stream: Limited To One Hour

### ISSUE THREAD

**Issue by jasonmvp** [obsproject/obs-studio#5116] opened 2021-08-12 14:42 UTC
### Operating System Info

macOS 11.4

### Other OS

technically 11.5.2

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/t2mnrpv4Ze4sssjr

### Expected Behavior

1.  Start YouTube 4K/60 HLS stream.
2. Stream stays live until I manually stop it.

### Current Behavior

Exactly one hour after I start the HLS stream, the connection between YouTube and OBS is closed.  I've tied it four times so far, and it's failed four times.

### Steps to Reproduce

1.  Start a YouTube HLS 4K/60 stream
2.  Wait 60 minutes

**Comment by Gol-D-Ace** [comment] 2021-08-12 18:24
Can't confirm this behavior on Windows at least.

**Comment by Gol-D-Ace** [comment] 2021-08-12 19:45
You tried with x264 already to confirm it's the VT Encoder right?

**Comment by jasonmvp** [comment] 2021-08-12 20:00
x264 with a 4K/60 50Mbit/sec stream is basically impossible, even on this machine, even with settings like "ultrafast".  More importantly, it doesn't happen with RTMP(S).

**Comment by Gol-D-Ace** [comment] 2021-08-12 20:05
Does it happen with lower resolution as well?

**Comment by jasonmvp** [comment] 2021-08-12 20:07
I've sent a black, motionless 4K/60 stream of 1100bits/sec (Which youtube constantly complained about) and, at exactly 1 hour: it disconnected.  So bitrate doesn't matter.  I haven't tried lower resolutions and am not going to.  Haven't the time.  It's 4K hardware encoding or bust. :-)

**Comment by Fenrirthviti** [comment] 2021-08-12 20:12
I am also unable to replicate this using a standard 1080p30fps stream with either NVENC or x264 to HLS.

If you are unwilling to test in the environment where this is occurring to isolate the actual cause, then I will close this, as we cannot replicate and you are not willing to assist isolating the actual conditions that cause the fault.

**Comment by jasonmvp** [comment] 2021-08-12 20:19
This literally takes an hour to reproduce, and I'm sorry that I have a "day job" that takes 12 hours of my day.  Jim suggested I open this for tracking, and now you're closing it because I won't test a lower resolution?  I'm 100% certain it's nothing to do with resolution because as I stated: I already sent low-bitrate 1 hour stream.  Lowering the resolution isn't going to make a lick of difference.

**Comment by Fenrirthviti** [comment] 2021-08-12 20:24
Bitrate has nothing to do with resolution, which is why we are asking you to test. We've tested (both on macOS and Windows) and have not been able to replicate. Without further information to identify exactly _what_ is causing the issue, this isn't actionable.

Most people (except for Jim and DIllon) have day jobs on the project as well. Submitting a bug report, and then saying to the maintainers of the project "I don't know why this happens but you figure it out for me" is an incredibly entitled attitude. Opening an issue for tracking is fine, but your refusal to assist in troubleshooting means there's no further action we can take, as we can't replicate. This is, as far as we know, isolated and something specific to your system, and therefor not a bug in OBS that we can fix.

Thank you for your understanding.

**Comment by jp9000** [comment] 2021-08-12 21:00
Hey, thanks for opening the bug report.

> I've sent a black, motionless 4K/60 stream of 1100bits/sec (Which youtube constantly complained about) and, at exactly 1 hour: it disconnected. So bitrate doesn't matter. I haven't tried lower resolutions and am not going to. Haven't the time. It's 4K hardware encoding or bust. :-)

I think @Gol-D-Ace was not necessarily suggesting that you should use a lower resolution, more so as a test case using your setup to see whether the issue was related to resolution. We would not typically ask someone to stream at a different resolution, especially if there were a bug -- instead, we're just trying to perform a process of elimination in order to whittle down the source of the potential bug. I believe that was @Gol-D-Ace's intent in asking that question.

I completely understand your point of view; just remember that even if we ask something strange like this of you, it's not because we want to change what you're doing or anything like that. We're just trying to help so we can figure out what's going on. I know it's a lot to ask to have you perform that long of a test under differing conditions.

Keep in mind @Gol-D-Ace has also been testing under those long conditions to try to isolate what's going wrong as well.

I completely understand that this is a pain to deal with. I will see if I can reproduce the issue on my mac.

**Comment by jasonmvp** [comment] 2021-08-12 22:47
Tried again with libx264 and ultrafast.  Still dies at exactly 1 hour.  The FIN-ACK is coming from YouTube without an apparent FIN from my system.

**Comment by jasonmvp** [comment] 2021-08-13 10:35
- I've tried from my Macbook Pro and replicated the issue.
- I've tried from my Windows 10 rig and was not able to replicate the issue.  Have had an HLS stream running for over an hour and 15 minutes so far and it's still going.

Interesting data.  Seems to happen on both Macs using either VT or libx264, but not the Win rig.

**Comment by jp9000** [comment] 2021-08-13 12:54
Hey thank you for taking the time to test, I appreciate it. I'll see if I can confirm on my mac today. I remember way back in the day we had this one bug that only cropped up after about 8 hours. These sort of issues are always the nastiest.

**Comment by jasonmvp** [comment] 2021-08-13 13:28
Further tested with 26.1.2 on the Mac: same thing happens at 1 hour exactly.  Could be something systemic with macOS, or something to do with how both of my Macs are configured.

**Comment by jp9000** [comment] 2021-08-15 13:25
I can verify that this does happen after one hour exactly on mac when using HLS. If I had to guess I'd suspect it's a dependency issue, very annoying.

**Comment by jasonmvp** [comment] 2021-08-15 13:56
Glad you were able to reproduce it Jim.  Thanks for doing that.

Can we open this back up so it can be tracked?  Thanks.

**Comment by jasonmvp** [comment] 2021-08-16 12:53
Interesting data from the `tcpdump` I ran a couple of times when trying to test this out:  For some odd reason, YouTube's server sends the **FIN-ACK** when the connection is closing.  But I never once saw my Mac send out a **FIN** to begin the session tear-down.  That's quite odd and against TCP standards of course.

The only guess I can make is that something in the data PUSH right at 60 minutes is being interpreted by YT's server as a **FIN**.

**Comment by RytoEX** [comment] 2021-12-31 16:50
After discussion with YouTube, we're fairly certain this is a bug in FFmpeg before FFmpeg 4.3, specifically [FFmpeg Trac ticket 7975](https://trac.ffmpeg.org/ticket/7975).  That bug is fixed in FFmpeg 4.3+.  We updated FFmpeg on macOS to FFmpeg 4.4.1 as part of obsproject/obs-deps#77 (https://github.com/obsproject/obs-deps/commit/2aa0b21bf3f99d518949fc7c3699d43202028e6d), which has been used on the obs-studio CI [since December 6](https://github.com/obsproject/obs-studio/commit/b58f83a44df8e350c00c991c4f1d953b44cf1ade).

Accordingly, this should be fixed on CI builds as of that date and fixed in OBS Studio 27.2, so I am closing this Issue.  Please let us know if this behavior still occurs, and we will reopen this to investigate further.

**Closed by RytoEX** 2021-12-31 16:50 UTC
Labels: macOS, Confirmed

**Comment by RytoEX** [comment] 2022-01-04 22:09
For the record, @jasonmvp confirmed via Discord:
> live for over an hour w/HLS on the Mac.  looks like it's fixed.
