### ISSUE TITLE
obs not grabbing screen (black screen)

### ISSUE THREAD

**Issue by jedi2610** [obsproject/obs-studio#4839] opened 2021-06-08 06:09 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.0

### OBS Studio Log URL

http://0x0.st/-_Gz.txt

### Expected Behavior

OBS should be able to capture the screen and shouldn't crash when right clicking on the Screen Capture source.

### Current Behavior

OBS doesn't grab the screen and the preview is black. When i right click on the Screen Capture source OBS crashes

### Steps to Reproduce

1. Open OBS
2. The preview is black.
3. Try to record and the output is fully black

### Anything else we should know?

This happens only on the latest version. I downgraded to `26.1.2-2` and it works perfectly fine.

**Comment by WizardCM** [comment] 2021-06-08 06:11
Duplicate of #4823

**Closed by WizardCM** 2021-06-08 06:11 UTC
