### ISSUE TITLE
Apple VT Encoder (mac-vth264) recording with fractional frame rate does not match OBS frame rate

### ISSUE THREAD

**Issue by juniorporciuncula** [obsproject/obs-studio#2760] opened 2020-04-20 00:56 UTC
## Platform
Operating system and version: macOS Mojave (10.14.6)
OBS Studio version: 25.0.7

## Expected Behavior
Streaming and Recording must record the files with the selected frame rate on OBS

## Current Behavior
Streaming and Recording are recorded with 25 fps (even if I set OBS for 30fps) and 50fps (even if I set OBS for 60fps)
This doesn't happen with x264. On x264 the recording will respect the OBS frame rate.

## Steps to Reproduce
Set OBS for 30 fps and record the video using Apple VT Hardware Encoder.

## Additional information
I've tried a lot of versions of OBS, but this problem occurs with all version, in any macOS I've tested (Yosemite, El Capitan, High Sierra and Mojave)
![Captura de Tela 2020-04-19 às 21 52 56](https://user-images.githubusercontent.com/10005660/79705133-f5410c00-828a-11ea-976d-c52a240ade1e.png)

**Comment by Fenrirthviti** [comment] 2020-04-20 01:05
Can you please properly fill out the bug report template?

**Comment by juniorporciuncula** [comment] 2020-04-20 01:07
Sorry. I'll do that!

**Comment by snicolai-blog** [comment] 2020-04-20 01:37
I just used the VT hardware encoder at 30 fps for a recording over an hour long this morning.  The local recording is at 30 fps as shown by the QuickTime player.  The primary video source was a video camera at 1280x720 30 fps.

MacOS X 10.14.6 (18G4032) MacBook Pro (Retina, 15-inch, Mid 2014)  Running with en-us locale settings.

OBS 25.0.6

**Comment by juniorporciuncula** [comment] 2020-04-20 01:38
> I just used the VT hardware encoder at 30 fps for a recording over an hour long this morning. The local recording is at 30 fps as shown by the QuickTime player. The primary video source was a video camera at 1280x720 30 fps.
> 
> MacOS X 10.14.6 (18G4032) MacBook Pro (Retina, 15-inch, Mid 2014) Running with en-us locale settings.
> 
> OBS 25.0.6

Please, download the software "Invisor Lite" and check the REAL (Original) fps of your video

**Comment by snicolai-blog** [comment] 2020-04-20 01:57
That shows 30 fps as well.
<img width="477" alt="Screen Shot 2020-04-19 at 8 49 37 PM" src="https://user-images.githubusercontent.com/59782525/79706895-5ca58e80-8280-11ea-932b-848ec8e1b21c.png">

**Comment by juniorporciuncula** [comment] 2020-04-20 02:05
> That shows 30 fps as well.
> <img alt="Screen Shot 2020-04-19 at 8 49 37 PM" width="477" src="https://user-images.githubusercontent.com/59782525/79706895-5ca58e80-8280-11ea-932b-848ec8e1b21c.png">

You must look at the EXTENDED tab

**Comment by snicolai-blog** [comment] 2020-04-20 02:14
It's 30 fps there as well.

<img width="353" alt="Screen Shot 2020-04-19 at 9 08 32 PM" src="https://user-images.githubusercontent.com/59782525/79707465-2cf78600-8282-11ea-9dc7-81797ab83479.png">

Can you fill out the template properly with the information about your setup?  This may be something very specific about your setup, and you haven't told us anything about it.

**Comment by juniorporciuncula** [comment] 2020-04-20 02:20
My setup is i7 8700k, 32GB RAM, Vega 64, Samsung EVO 860 1TB

Your video information show Variable Framerate, mine show Constant, I dont know why, these options doesn't even show on OBS settings

![Captura de Tela 2020-04-19 às 23 17 46](https://user-images.githubusercontent.com/10005660/79707881-46093280-8294-11ea-985f-1bb30e3dce5e.png)

**Comment by snicolai-blog** [comment] 2020-04-20 02:26
Here's another short one off my FaceTime camera.  This is off a recorded mkv file.  The other one was an mkv remuxed by OBS to mp4.

<img width="350" alt="Screen Shot 2020-04-19 at 9 24 22 PM" src="https://user-images.githubusercontent.com/59782525/79708166-4d284480-8284-11ea-81ae-627265e5a1d5.png">

**Comment by snicolai-blog** [comment] 2020-04-20 02:30
What is your video source?  Can you repeat the test I just did?  Record a few seconds of the FaceTime camera to an mkv file.  Try it with both a 1920x1080 and a 1280x720 canvas and output.

**Comment by juniorporciuncula** [comment] 2020-04-20 02:34
> What is your video source? Can you repeat the test I just did? Record a few seconds of the FaceTime camera to an mkv file. Try it with both a 1920x1080 and a 1280x720 canvas and output.

My video source is a Blackmagic Cinema Camera connected to a Blackmagic Intensity Pro (HDMI). I also have an Logitech BRIO. I'll recording both x264 and Apple VT on both cameras. My OBS is set to 30fps.

**Comment by energizerfellow** [comment] 2020-04-20 06:58
I'd laugh if Apple VT is trying to be "helpful" by using PAL fps rates if the OS is set to a locale in one of the traditional PAL/SECAM markets.

**Comment by RytoEX** [comment] 2020-04-20 11:54
@juniorporciuncula Could you please verify your system locale setting?  Could you please also post an OBS log from a session where this happens?  You can attach it to a post rather than posting it inline.

**Comment by PatTheMav** [comment] 2020-04-30 15:42
So I just checked with Apple VT Hardware encoding (and I'm firmly in PAL territory) and FaceTime Cam included and the recordings had 60fps and 30fps respectively (no other "Original Frame Rate").

Note that recorded MKVs will have a Constant Framerate, the MP4s muxed by OBS will have variable frame rates.

**Comment by juniorporciuncula** [comment] 2020-04-30 21:36
Hi, guys. Here is the Log: https://obsproject.com/logs/yV-rF_XEPhBO-ZAi

Here is a recorded video using Apple VT: https://drive.google.com/open?id=1hMAKbsEViP1tFEMeALnUybFFZp1-Ubva

My locate is Brasil

Here is the media info on Invisor Lite
![Captura de Tela 2020-04-30 às 18 34 58](https://user-images.githubusercontent.com/10005660/80761641-4fef2900-8b11-11ea-9a7c-f3c5f34d432d.png)

**Comment by juniorporciuncula** [comment] 2020-04-30 21:59
I also tried the recording on MKV format, but the problem is the same. There aren't 30 frames per second, you can see the "jumping" frames on the recorded video.

**Comment by RytoEX** [comment] 2020-04-30 23:23
Looking at your log, you have your OBS video FPS set to 29.97 FPS (30000/1001), not 30 FPS.  This turns out to be an important detail.

On Windows, I am unable to reproduce this using NVENC.  However, QuickSync does seem to produce files that MediaInfo shows as VFR if using a fractional FPS that does not reduce to an integer value in OBS.  It is possible that the VT encoder on your system is using QuickSync (from the i7-8700K) under the hood and resulting in the same issue.

I'm not sure if this is something we can fix, or if this is an issue with QuickSync or the VT encoder.

**Comment by juniorporciuncula** [comment] 2020-04-30 23:26
29,970 is to mantain the TBC with my Blackmagic Camera. But the problems occurs even with the OBS set to 30fps. If somebody want I can generate a new log with OBS on 30fps

**Comment by juniorporciuncula** [comment] 2020-04-30 23:27
with x264 OBS records perfect with 30, 29,970, 24... with Apple VT OBS only records with 25fps or 50fps.

**Comment by RytoEX** [comment] 2020-04-30 23:40
Yes, I do want a log showing the exact issue you're describing.  These are invaluable diagnostic tools for us.

The fact that it works fine on x264 but not on Apple VT is interesting, but I'm not sure exactly what's going on here.  Curiously, 25.111/29.97, 25/30, 50/60 are all about 0.83.  I'll need the macOS folks to look into it and weigh in.

**Comment by snicolai-blog** [comment] 2020-05-01 16:19
In addition to the log, you mentioned that you have a different camera, but we haven't seen if it can be reproduced with a different camera, or is it something specific to the Blackmagic setup you are using.  If you can reproduce it with a built-in FaceTime camera, that will make it easier for others to reproduce it, since they likely have that hardware.

Apple also has a software version of the VT encoder.  Does it happen with that?

**Comment by datalooper** [comment] 2020-05-09 10:13
I can also confirm that VT is only really working in 25fps or 50fps. I just went through for about 2 hours trying to get non-choppy video using the Apple VT and changing the fps to one of those values worked brilliantly. WTF.

**Comment by humphd** [comment] 2020-06-08 01:21
I'm really happy to have stumbled on this issue, since I'd just about given up on using the Apple VT encoder.  Then I switched my frame rate to 25 and it's perfect.

**Comment by carlosferrari** [comment] 2020-06-29 22:11
Hi everyone!
I have a similar issue with my OBS. My main goal is to record from my Sony A7III using a BM Deck Link Mini Recorder 4K.
I'm recording at 2160p@24 from camera using Apple VT H264 Hardware Encode but the output file is a 20fps.
Here is the log: https://obsproject.com/logs/ZWWKAYNAjnUD-WK0
Here is the screenshot from invision lite:
 ![Screen Shot 2020-06-29 at 18 53 37](https://user-images.githubusercontent.com/20654868/86060594-6a734f00-ba3b-11ea-9ce1-cf09975ef52a.png)

I tough it was from my camera/capture device (I have tried an Elgato CamLink 4K too) but when I was recording the screen to edit with the capture from the camera I got the same wrong fps with VT H264 when recording at 1080p@24fps. 
Here is the log: https://obsproject.com/logs/wIECwmlwV1vqK-y_
Here is the screenshot from invision lite:
![Screen Shot 2020-06-29 at 19 06 42](https://user-images.githubusercontent.com/20654868/86060704-b0301780-ba3b-11ea-937a-8be3981cc472.png)

Fun fact, I'm from Brazil as is the OP @juniorporciuncula 
x264 works without an issue
Feel free to ask me what you need!

**Comment by energizerfellow** [comment] 2020-06-29 23:59
> Yes, I do want a log showing the exact issue you're describing. These are invaluable diagnostic tools for us.
> 
> The fact that it works fine on x264 but not on Apple VT is interesting, but I'm not sure exactly what's going on here. Curiously, 25.111/29.97, 25/30, 50/60 are all about 0.83. I'll need the macOS folks to look into it and weigh in.

This is almost certainly a bug in Apple VT relating to the Brazil-specific legacy of PAL-M.  PAL-M was unique in the world for combining the PAL color system on a 59.95 hz M system (525-line with 60 * 1000 / 1001 ~= 59.94 fps) instead of the global standard of PAL color on 50 hz .  The math here being:

50 / ( 60 * 1000 / 1001 ) ~= 0.834167

This multiplier seems to apply on all these cases as you end up with things like:

24 * ( 50 / ( 60 * 1000 / 1001 ) ) = 20.02

More info on PAL-M:
https://en.wikipedia.org/wiki/NTSC#PAL-M_(Brazil)
https://en.wikipedia.org/wiki/PAL-M

In theory setting your locale to anything other than Brazil in macOS should fix this issue.

**Comment by carlosferrari** [comment] 2020-06-30 13:01
> In theory setting your locale to anything other than Brazil in macOS should fix this issue, but might require a non-ISDB-T country.

Hi! Unfortunately setting locale to US didn't work. When setting 24fps records at 20fps, when setting 29.97fps records at 25fps, when setting 30fps records at 30fps.

Should I test with other locale?

**Comment by snicolai-blog** [comment] 2020-06-30 14:32
It may not be the locale, it might be something in the video descriptor that the VT encoder sees and triggers this behavior.

**Comment by energizerfellow** [comment] 2020-06-30 19:40
> Here is the log: https://obsproject.com/logs/ZWWKAYNAjnUD-WK0
> Here is the screenshot from invision lite:
> ![Screen Shot 2020-06-29 at 18 53 37](https://user-images.githubusercontent.com/20654868/86060594-6a734f00-ba3b-11ea-9ce1-cf09975ef52a.png)

@carlosferrari I noticed in your OBS logs that you're running in RGBA mode, which may be part of the problem.  The Apple VT encoder will have to do the RGB -> yuv420p transcode.

> It may not be the locale, it might be something in the video descriptor that the VT encoder sees and triggers this behavior.

@snicolai-blog Quite possible, yes, but I've seen some increasing evidence that Intel's Quick Sync encoding may be broken at sub-30 fps (not sure if NTSC 29.97 or true 30.00 yet) on older iGPUs, if not all of them.  Not sure if this is a hardware and/or driver side issue, but I've seen this in the wild on Windows as well.

> When setting 24fps records at 20fps, when setting 29.97fps records at 25fps, when setting 30fps records at 30fps.

@carlosferrari What do you get when you try 29.97 fps?

**Comment by carlosferrari** [comment] 2020-07-03 19:44
> @carlosferrari I noticed in your OBS logs that you're running in RGBA mode, which may be part of the problem. The Apple VT encoder will have to do the RGB -> yuv420p transcode. You're also getting full-range YUV output, which can cause color accuracy problems in lots of players/editors/transports.
> @carlosferrari What do you get when you try 29.97 fps with a YUV-native output mode like NV12, i420, or i444? Also try fps rates in the 60-120+ range to see if the final encode gets the correct fps rate. Partial vs full-range may have an effect as well.

Sorry for the late reply, busy week. Here are the results. With constant framerates it work. When using NTSC 24P or 23.97 or 59.97 it doesn't.

![60fps](https://user-images.githubusercontent.com/20654868/86494591-3013f580-bd4c-11ea-84b4-65bf7ca1e475.png)
![59 97fps](https://user-images.githubusercontent.com/20654868/86494596-32764f80-bd4c-11ea-966e-b0d8e31e373c.png)
![50fps](https://user-images.githubusercontent.com/20654868/86494598-330ee600-bd4c-11ea-8d65-56ff37579bc5.png)
![48fps](https://user-images.githubusercontent.com/20654868/86494599-33a77c80-bd4c-11ea-9716-df31f98a4346.png)
![30fps](https://user-images.githubusercontent.com/20654868/86494600-34401300-bd4c-11ea-832a-07359426e8bb.png)
![29 97fps](https://user-images.githubusercontent.com/20654868/86494601-34401300-bd4c-11ea-8eb7-356e0c03703b.png)
![25fps](https://user-images.githubusercontent.com/20654868/86494602-34d8a980-bd4c-11ea-8e94-89c5cad40612.png)
![20fps](https://user-images.githubusercontent.com/20654868/86494603-34d8a980-bd4c-11ea-97aa-ff30c137abc2.png)
![10fps](https://user-images.githubusercontent.com/20654868/86494604-35714000-bd4c-11ea-9c65-c9a760127189.png)

**Comment by carlosferrari** [comment] 2020-07-29 18:37
How can we bump this? OBS for mac is useless with this bug.

**Comment by thomaslfessler** [comment] 2021-03-29 17:33
Bump as well.   The macOS version needs more attention.  The windows based codebase chews up CPU and GPU bandwith on macos.   Frame rate performance issues are just a drop in the bucket.

**Comment by PatTheMav** [comment] 2021-03-29 21:31
As with any Open Source project, you are free to fork and clone the repository, investigate issues and contribute to their solutions. Bumping the issue won't do a thing, as to my knowledge no maintainer has been able to reproduce this issue.

**Comment by RytoEX** [comment] 2022-02-13 04:54
We can confirm that recording with the Apple VT encoder with a fractional frame rate results in the files appearing to have (in metadata viewers or other software that displays a media file's frame rate) a frame rate that does not match what the user set. We are still investigating this.

Using the Apple VT encoder with integer frame rates seems to work fine.

**Comment by WizardCM** [comment] 2022-06-25 23:18
Fixed by #6644

**Closed by WizardCM** 2022-06-25 23:18 UTC
Labels: macOS, Confirmed
