### ISSUE TITLE
Nested Scenes deletion freezes and crahes OBS

### ISSUE THREAD

**Issue by msmafra** [obsproject/obs-studio#6484] opened 2022-05-15 18:47 UTC
### Operating System Info

Other

### Other OS

Fedora Workstation

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/PdwOfvPaOekJGVSt

### Expected Behavior

To remove the nested scene from all parent scenes and not crash after/while deleting it.

### Current Behavior

It crashes after deleting the original nested scene. Empty Nested scenes (no sources, items etc.) in it take more time to crash. A full configured one locks/freezes OBS Studio and crashes.
Also, while using the flatpak version, is always reported that OBS crashed by Gnome's notification system, even if it closes smoothly. It was a problem before the official release of 27.2.0 (using beta, rc), stopped with 27.2.0 official release, but started again after .1 or .2 (no sure which one).

### Steps to Reproduce

1. Create a scene, preferably with sources, text etc;
2. Create an empty or normal scene and add the first one to it;
3. Delete the first one and wait for the freeze and crash;
...

### Anything else we should know?

It's been happing for a while, I just figured it out recently, that this was what was causing the crashes.

**Comment by tt2468** [comment] 2022-05-15 19:13
It looks like you have a lot of third-party plugins added, which may be affecting the situation. Please validate that this bug still persists without third-party plugins.

Additionally, I recommend disabling Debug Logging in obs-websocket, as it makes logs very difficult to read.

**Comment by msmafra** [comment] 2022-05-27 16:12
Sorry about the delay. 
I removed the plugins manually installed and the ones installed via Flatpak.

When you have a nested scene with nothing it deletes. As soon as you add a source it won't and OBS freezes.

**Comment by RytoEX** [comment] 2023-01-11 21:29
I cannot reproduce this on Windows 10 with OBS Studio 29. Please retest in OBS Studio 29 or newer.

**Comment by RytoEX** [comment] 2023-05-11 19:41
As we are unable to reproduce this, and no additional details were provided, we are closing this Issue. If this is still occurring, please comment with a new OBS log for the latest stable version (29.1.1 at time of writing), and we can consider reopening this.

**Closed by RytoEX** 2023-05-11 19:41 UTC
