### ISSUE TITLE
QSV: Hardware device returned unexpected errors (MFX_ERR_DEVICE_FAILED)

### ISSUE THREAD

**Issue by BrentonPoke** [obsproject/obs-studio#9825] opened 2023-11-08 07:58 UTC
### Operating System Info

Other

### Other OS

Fedora 39

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/IpzYJgIHHo3vrxHa

### Expected Behavior

A matroska file should be created and start recording video

### Current Behavior

I get the following in an error modal:
```
Starting the output failed. Please check the log for details.

Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.
```

### Steps to Reproduce

1. Have a video source captured by OBS
2. Go to settings and use Standard for recording type, selecting QuickSync AV1 for video enocder
3. Save
4. Press "Start Recording"

### Anything else we should know?

I noticed the following in the log:
```
02:18:09.470: [qsv encoder: 'advanced_video_recording'] debug info:
02:18:09.481: 	surf:           SysMem
02:18:09.491: [qsv encoder: 'msdk_impl'] Hardware device returned unexpected errors (MFX_ERR_DEVICE_FAILED)
02:18:09.491: [qsv encoder: 'advanced_video_recording'] qsv failed to load
```
This seems to affect other QSV encoding options, as I can't use any of them. My Mesa drivers are up to date and the rest of my display and video capability seems perfectly fine.

**Comment by kkartaltepe** [comment] 2023-11-08 15:13
`MFX_ERR_DEVICE_FAILED` means your vaapi drivers failed to load, make sure your system is up to date, you dont have multiple intel qsv drivers, and you have rebooted.

After that try adding `--verbose` flags when starting obs and re-uploading the log.

**Comment by BrentonPoke** [comment] 2023-11-08 23:46
[New log file](https://obsproject.com/logs/UDU3f0e6d56f4BBV)
I tried it again with verbosity and while there's a lot more stuff from my microphone, I was able to catch this:
```
18:33:30.455: >>> gpu tex not active, fall back to old qsv encoder
18:33:30.455: [qsv encoder: 'advanced_video_recording'] settings:
18:33:30.455: 	codec:          AV1
18:33:30.455: 	rate_control:   CBR
18:33:30.455: 	target_bitrate: 3500
18:33:30.455: 	Lookahead Depth:60
18:33:30.455: 	target_usage:   TU4
18:33:30.455: 	profile:        main
18:33:30.455: 	keyint:         0
18:33:30.455: 	latency:        normal
18:33:30.455: 	b-frames:       3
18:33:30.455: 	enhancements:   on
18:33:30.455: 	fps_num:        60
18:33:30.455: 	fps_den:        1
18:33:30.455: 	width:          1920
18:33:30.455: 	height:         1080
18:33:30.455: [qsv encoder: 'advanced_video_recording'] debug info:
18:33:30.466: 	surf:           SysMem
18:33:30.475: [qsv encoder: 'msdk_impl'] Hardware device returned unexpected errors (MFX_ERR_DEVICE_FAILED)
18:33:30.475: [qsv encoder: 'advanced_video_recording'] qsv failed to load
18:33:30.475: 	major:          1
18:33:30.475: 	minor:          35
```

**Comment by kkartaltepe** [comment] 2023-11-09 02:30
> I did notice that FFMPEG VAAPI H264 works so long as I don't use Fedora's hot-corner feature (the OS may crash afterward).

Unfortunately this isnt very useful, obs and intel's vpl libraries probe the driver a lot while ffmpeg vaapi only probes the driver once. So bugs in intel's vaapi driver during loading wont happen when using vaapi directly instead of intel's vpl/qsv libraries.

 > Everything is up to date and I checked that the latest intel-media-driver was installed.

It looks like you are mixing intel/rhel and fedora repositories. Doing this is probably causing your problem.

**Comment by BrentonPoke** [comment] 2023-11-09 02:33
> > Everything is up to date and I checked that the latest intel-media-driver was installed.
> 
> It looks like you are mixing intel/rhel and fedora repositories. Doing this is probably causing your problem.
I already rectified that and the rhel libraries are no-longer installed. The problem persists and nothing seems to have changed.

**Comment by A1RM4X** [comment] 2023-11-09 18:54
Salut!

I have the exact same issue here on Arch Linux with the latest obs studio compiled from git and an Intel A380.

I can provide more info if required. Thanks.

**Comment by kkartaltepe** [comment] 2023-11-10 00:43
Unfortunately anyone who can replicate is likely going to need to debug the intel drivers and file the bug against them or provide some insight into how we can workaround it in obs. I've never replicated this issue and so far most people who reported it later reported it was fixed by using up to date system packages.

Or figure out why it replicates on your machine and provide me a means to replicate it.

**Comment by BrentonPoke** [comment] 2023-11-10 01:24
What packages did they need and where was that discussion? Mine are up to date and this is not working.

**Comment by luyu-wu** [comment] 2023-11-11 17:31
Also experiencing the same problem!

Arch Linux
Iris Xe (1135G7)

**Comment by BrentonPoke** [comment] 2023-11-12 06:15
@A1RM4X @luyu-wu What intel packages do you have installed? Can you do `list installed "intel*"` with pacman?

**Comment by BrentonPoke** [comment] 2023-11-12 07:30
I think I found the main issue. Walk with me:

There is a package called `oneVPL-intel-gpu` that requires a sort of "parent" package, `oneVPL`. The problem is that if I try to install it...
![image](https://github.com/obsproject/obs-studio/assets/6861851/eb2727b3-b60a-4857-9959-2bc626d61944)

...and I now direct your attention to the conflict:
```
Error: Transaction test error:
  file /usr/lib64/libvpl.so.2 from install of oneVPL-2023.3.1-1.fc39.x86_64 conflicts with file from package libvpl2-2022.1.5.0-i419.el8.x86_64
```
It seems that `libvpl2` is actually required by OBS and numerous other things, but I wondered if removing it and installing oneVPL anyway would work. It turns out it did - sorta. I can now produce an AV1 encoded file in a 2-cp setup with OBS streaming from windows to nginx in a container alongside OBS both on linux.

Now here's the new problem - stability. The system crashes all the time when trying to do this, and i'm not convinced it's the chips. The system is a 6800K with an A770 and 48GB of system RAM, so i'm pretty sure this isn't a chip issue. I think it's a wayland issue, but I have no proof because I'm not sure how to debug the crashes since it's not OBS crashing, but the entire system due to OBS.

**Comment by miah-7** [comment] 2023-11-12 10:14
Have the same issue on stable 30.0 when trying to record with QuickSync H.264
Fedora Linux 39, UHD 620

**Comment by kkartaltepe** [comment] 2023-11-12 14:55
As always, saying "me too" is functionally useless. If you feel like posting that please include a log from obs that includes the error at minimum or you may have a completely different issue and be wasting your time waiting for a possible fix for this issue.

> There is a package called oneVPL-intel-gpu that requires a sort of "parent" package, oneVPL. The problem is that if I try to install it...

as originally pointed out you are mixing repostiories that shouldnt be mixed. If you cannot remove all non-fedora repositories on the system I think we can just close the issue as your system is unsupportable in this state.

**Comment by BrentonPoke** [comment] 2023-11-12 15:05
They've already been disabled, but that doesn't remove packages. And it does no good to close this when people who are still having similar issues and just reopen it. Don't be so defensive about this.

**Comment by luyu-wu** [comment] 2023-11-12 16:35
> @A1RM4X @luyu-wu What intel packages do you have installed? Can you do `list installed "intel*"` with pacman?

Sorry for the delayed response!
![image](https://github.com/obsproject/obs-studio/assets/116970666/d5611639-0be0-4ef3-8f01-3299b723936c)
There shouldn't be anything conflicted here.

**Comment by BrentonPoke** [comment] 2023-11-12 19:30
You might also need the oneVPL gpu package.  I'm not sure if Arch packages oneVPL as a dependency or combined as one package, but can you try that and see what happens?

**Comment by jthomaschewski** [comment] 2023-11-12 20:08
>  You might also need the oneVPL gpu package. I'm not sure if Arch packages oneVPL as a dependency or combined as one package, but can you try that and see what happens?

Thanks, installing the package `onevpl-intel-gpu` solved this issue for me on Arch. 

Intel i7-1260P. Vaapi decoding/encoding worked fine in other applications but OBS.

**Comment by kkartaltepe** [comment] 2023-11-12 20:43
Closing this as people are mixing different issues and as expected most people just are unable to figure out the mess of packages to get intel's runtime working. I recommend you create a page on the wiki about what packages are required for your various distributions as we dont want to track this in our issue tracker.

For system stability issues you should file a bug against intel, especially if it happens playing back files without obs running. If you find a change to obs that improves your experience this please send a patch.

**Closed by kkartaltepe** 2023-11-12 20:43 UTC
Labels: Linux

**Comment by BrentonPoke** [comment] 2023-11-12 20:58
You could've been helpful by adding the  oneVPL package as a confidential dependency for obs, since there is no indication it would even be necessary for this and you currently pull something else in its place.

**Comment by kkartaltepe** [comment] 2023-11-12 21:27
> You could've been helpful by adding the oneVPL package as a confidential dependency for obs, since there is no indication it would even be necessary for this and you currently pull something else in its place.

We do not maintain fedora packages, so you should provide appropriate packager with your feedback if you feel it was packaged poorly.

**Comment by k1gen** [comment] 2023-11-13 16:14
hey, I have a similar error, MFX_ERR_NOT_FOUND (https://paste.c-net.org/CopyingBowing) on Arch, with UHD620. I have these packages installed:
```
$ pacman -Q | rg "intel|onevpl"
intel-compute-runtime 23.30.26918.9-1
intel-gmmlib 22.3.12-1
intel-gpu-tools 1.27-2
intel-graphics-compiler 1:1.0.14828.8-1
intel-media-driver 23.3.5-1
intel-ucode 20230808-1
lib32-vulkan-intel 1:23.2.1-2
onevpl 2023.3.1-1
onevpl-intel-gpu 23.3.4-1
vulkan-intel 1:23.2.1-2
```

**Comment by miah-7** [comment] 2023-11-13 16:28
> We do not maintain fedora packages, so you should provide appropriate packager with your feedback if you feel it was packaged poorly.

Just tried the rpm OBS package from fedora repo and it works fine
As @jthomaschewski has already said the problem is in the flatpak build

**Comment by A1RM4X** [comment] 2023-11-13 19:11
Sorry for the late answer guys.

Just reinstalled a fresh Arch to troubleshoot. I confirm the error disappeared, might have too many drivers installed on my previous OS installation.

For information:

Hardware - Intel Arc a380
Distro: Arch
Packages installed:
pacman -Qq | grep intel
intel-gmmlib
intel-media-driver
onevpl-intel-gpu

Thanks for the AWESOME work, we can finally play with our Arc intel GPU within OBS.

**Comment by kkartaltepe** [comment] 2023-11-14 01:10
> hey, I have a similar error, MFX_ERR_NOT_FOUND (https://paste.c-net.org/CopyingBowing) on Arch, with UHD620. I have these packages installed:
> 

No this is a very different error, and conflating these two is precisely why I would prefer users not continue to append their varied QSV issues into this issue.

We prefer not to use our issues for support on what drivers to install for every package and Id prefer not to lock this issues for becoming a QSV support dumping ground. As recommended if you want a place to collaborate on documenting the proper way to install QSV for your preferred distribution you can use our forum or our wiki or anywhere else you prefer to collate information about how to properly install drivers.

**Comment by k1gen** [comment] 2023-11-14 19:59
> > hey, I have a similar error, MFX_ERR_NOT_FOUND (https://paste.c-net.org/CopyingBowing) on Arch, with UHD620. I have these packages installed:
> 
> No this is a very different error, and conflating these two is precisely why I would prefer users not continue to append their varied QSV issues into this issue.
> 
> We prefer not to use our issues for support on what drivers to install for every package and Id prefer not to lock this issues for becoming a QSV support dumping ground. As recommended if you want a place to collaborate on documenting the proper way to install QSV for your preferred distribution you can use our forum or our wiki or anywhere else you prefer to collate information about how to properly install drivers.

could you please help me instead of complaining that I "dump my errors here"? I am here because I couldn't find any information on installing drivers for QSV on Arch, for Skylake cards.

**Comment by BrentonPoke** [comment] 2023-11-15 00:53
> > hey, I have a similar error, MFX_ERR_NOT_FOUND (https://paste.c-net.org/CopyingBowing) on Arch, with UHD620. I have these packages installed:
> 
> No this is a very different error, and conflating these two is precisely why I would prefer users not continue to append their varied QSV issues into this issue.
> 
> We prefer not to use our issues for support on what drivers to install for every package and Id prefer not to lock this issues for becoming a QSV support dumping ground. As recommended if you want a place to collaborate on documenting the proper way to install QSV for your preferred distribution you can use our forum or our wiki or anywhere else you prefer to collate information about how to properly install drivers.

The reason they're not going to the forums is because nobody else does. Most of those threads have zero replies and it's a bit cynical to expect people to use a useless forum most people don't know about for any issue. You can't have everything you want. Fact of the matter is, there's still an issue with OBS crashing linux every time you press the record button, when the system is fine otherwise. Your refusal to even look into why OBS crashes systems so much is part of the problem, and makes it seem you're being defensive about your PR.

**Comment by kkartaltepe** [comment] 2023-11-15 02:52
> could you please help me instead of complaining that I "dump my errors here"? I am here because I couldn't find any information on installing drivers for QSV on Arch, for Skylake cards.

This is precisely what we hope to avoid in our issues, so if thats the discussion thats going to happen here we will need to lock this to ensure people know that they should be going to obsproject.com/help instead.

> The reason they're not going to the forums is because nobody else does. Most of those threads have zero replies and it's a bit cynical to expect people to use a useless forum most people don't know about for any issue. You can't have everything you want. Fact of the matter is, there's still an issue with OBS crashing linux every time you press the record button, when the system is fine otherwise. Your refusal to even look into why OBS crashes systems so much is part of the problem, and makes it seem you're being defensive about your PR.

If you still think obs is fault and want this reopened you would need some exceptional evidence. To quote your earlier comment "I'm not sure how to debug the crashes since it's not OBS crashing", this strongly suggests there is a bug in something outside of obs (or more likely your early sabotage of your system is still in effect). If you cannot investigate further then it seems everything is done for this bug and we await someone to reply with a fix or more information to make it worth opening.

**Comment by BrentonPoke** [comment] 2023-11-15 03:23
> > The reason they're not going to the forums is because nobody else does. Most of those threads have zero replies and it's a bit cynical to expect people to use a useless forum most people don't know about for any issue. You can't have everything you want. Fact of the matter is, there's still an issue with OBS crashing linux every time you press the record button, when the system is fine otherwise. Your refusal to even look into why OBS crashes systems so much is part of the problem, and makes it seem you're being defensive about your PR.
> 
> If you still think obs is fault and want this reopened you would need some exceptional evidence. To quote your earlier comment "I'm not sure how to debug the crashes since it's not OBS crashing", this strongly suggests there is a bug in something outside of obs (or more likely your early sabotage of your system is still in effect). If you cannot investigate further then it seems everything is done for this bug and we await someone to reply with a fix or more information to make it worth opening.
> 
> 
> 

You deliberately cut off a key part of that sentence, which was that the system was crashing because of obs. There is no _graceful_ failure by obs that allows me to see the log file afterwards, but a catastrophic one that can be reproduced by just using the software. But you haven't helped find any way to get telemetry about what happens when obs crashes the entire system if the log can't be counted on.

**Comment by Fenrirthviti** [comment] 2023-11-15 03:32
As a reminder, please remain respectful and don't resort to personal attacks, which is against our [CoC](https://github.com/obsproject/obs-studio/blob/master/COC.rst)

As it stands, all evidence points towards broken/incompatible packages on the system which we cannot reproduce, and without reliable steps to reproduce the issue, there is unfortunately not much for us to investigate. If you would like this issue to bn reopened/reconsidered, we would need full steps to reproduce the broken state from a clean Fedora install.

Thanks for understanding.

**Comment by leodip** [comment] 2023-11-28 16:39
@k1gen Have you found a solution to this problem? I'm having the same here. 
https://github.com/obsproject/obs-studio/issues/9930

**Comment by k1gen** [comment] 2023-11-28 20:37
> @k1gen Have you found a solution to this problem? I'm having the same here. #9930

no, haven't found anything, switched back to vaapi. also, the forum is dead, so if you want to get help - I think the only place left to ask is discord

**Comment by Motaphe** [comment] 2024-06-26 14:00
> You might also need the oneVPL gpu package. I'm not sure if Arch packages oneVPL as a dependency or combined as one package, but can you try that and see what happens?

Thanks, installing the package onevpl-intel-gpu solved this issue for me on Arch.

**Comment by AgenttiX** [comment] 2025-03-11 15:27
Installing the package libmfx-gen1.2 solved this issue for me for Kubuntu 24.10 on ThinkPad L14 Gen 5 with Intel Core Ultra 5 125U.

**Comment by Auxority** [comment] 2025-04-11 16:13
@Motaphe thank you so much, fixed it for me on Arch as well :)

**Comment by DomingoMontoya** [comment] 2025-04-28 19:34
Confirmed that installing `vpl-gpu-rt` on Arch fixed it for me as well.
