### ISSUE TITLE
OBS triggers a screen sharing icon in the macOS menu bar that won't go away upon exit

### ISSUE THREAD

**Issue by yllekz** [obsproject/obs-studio#9805] opened 2023-11-05 02:20 UTC
### Operating System Info

macOS 14

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/nlkKIrWFb3TjOMOP

### Expected Behavior

OBS should not cause the screen sharing menu bar icon to become a permanent resident after it is closed out.  This also happened in macOS Ventura.

### Current Behavior

It appears that OBS Studio may be utilizing "[an older API that is deprecated in Sonoma](https://old.reddit.com/r/MacOS/comments/16t5zwt/is_there_a_way_to_get_this_screen_sharing_icon/k2dcjgp/)" when it comes to macOS screen sharing. When OBS is invoked, it triggers a purple screen sharing icon in the menu bar that lingers and won't go away even after OBS is closed. The system effectively must be rebooted to make it go away.

### Steps to Reproduce

1. Open OBS
2. Add sources such as Application Capture, macOS Screen Capture, Video Capture Device, etc.
3. Observe the menu bar and the screen sharing icon generated by macOS.
...

**Comment by WizardCM** [comment] 2023-11-05 02:22
Duplicate of #9796

**Closed by WizardCM** 2023-11-05 02:22 UTC
