### ISSUE TITLE
Windows GUI Performance Extremely Sluggish in Insider Preview Dev and Beta

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-studio#4807] opened 2021-06-03 21:01 UTC
### Operating System Info

Windows 10

### Other OS

Windows 10 Dev Build 21382

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/k8xEXwmCOv6Gx_8F

### Expected Behavior

The windows desktop and OBS GUI interface remain smooth after opening OBS.

### Current Behavior

On the latest windows 10 dev build with AMD drivers version attached below, opening OBS (seems to be all versions, I tested 26.0.1 and 27.0) causes windows gui elements to become extremely unresponsive and OBS itself is very unresponsive to mouse cursor hovering, updating the audio mixer preview, etc. Linked here is a video of the issue. Occasionally the GUI and Windows GUI returns back to normal responsiveness but soon go back to poor responsiveness.

I have not observed issues in any other programs which is why I am recording the problem here. Running the program as Admin was never required before in order to get good performance and does not alleviate the issue.

https://user-images.githubusercontent.com/28281419/120710171-d0f2bf80-c48b-11eb-9c74-fc140eb12f8e.MOV

```
Software Version - 2021.0413.1252.23166
Driver Version - 21.10.03.09-210520a-367674E
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01494
OpenGL® Version - 29.20.11000.14830
AMD Audio Driver Version - 10.0.1.18
Vulkan™ Driver Version - 2.0.179
Vulkan™ API Version - 1.2.170
Windows Version - Windows 10 (64 bit)
```

### Steps to Reproduce

1. Switch to the Windows 10 Dev channel and run build 21382 (the latest when tested)
2. Update the AMD GPU drivers to 21.10.03.09-210520a-367674E
3. Install OBS Studio 27 release
4. Run OBS and observe the windows 10 desktop experience becomes verry sluggish in response to mouse hovering over the taskbar icons as well as the categories in task manager. The OBS gui window is very slow to respond mouse movements as well as showing changes in the docks when docked to the main window only. The rendered preview remains smooth.
...

### Anything else we should know?

As stated previously, I am not aware of the root cause of the problem but as OBS is the only program which I have seen to cause these issues I am posting the issue here.

**Comment by Fenrirthviti** [comment] 2021-06-03 21:52
This looked to be a duplicate of #4803. Closing.

**Comment by Fenrirthviti** [comment] 2021-06-03 21:56
Actually, my apologies, I thought 4803 was an insider build. Reopening this as it appears to be different, but as this is a development build of Windows it's unlikely we will look at this any time soon.

**Comment by theofficialgman** [comment] 2021-06-04 00:40
to add more details to this issue. As soon as I pop out the audio mixer dock into a floating window, the obs GUI as well as the Windows 10 GUI and apps immediatly are responsive again and stay that way. Re-docking the audio mixer brings back the poor performance

**Comment by tt2468** [comment] 2021-06-09 09:15
Running Dev build 21390, experiencing almost the exact same issue on my machine.

**Comment by tt2468** [comment] 2021-06-09 09:25
Realized I still had my Windows.Old folder. Restored from that point (20H2) and everything works flawlessly.

**Comment by RytoEX** [comment] 2021-06-09 16:24
If these issues are occurring with Insider builds of Windows, please make sure to report them to Microsoft.  We've seen issues surface in Insider builds before that were then resolved in future builds.

**Comment by theofficialgman** [comment] 2021-06-13 02:23
As of now, I have created a problem report in the feedback hub.
You may comment on the issue or view it for a follow up here: https://aka.ms/AAcwnb5

**Comment by WizardCM** [comment] 2021-06-30 11:11
I have verified this issue exists on Windows 11 build 22000.

**Comment by SmitheeGuy** [comment] 2021-07-23 00:00
Workaround for this (kinda) is to disable built in preview viewport and enable projector window instead. Stuttering stops if you do so. That's why i don't think it's insider build alone fault. I think it's something related to built in preview composition and/or rendering methods as well.

**Comment by IonicEcko** [comment] 2021-09-08 05:58
Still affects the beta branch (build 22000.176 - the one to be released shortly). Appears to be hardware agnostic as I've replicated it across 4 devices all with different processors/audio devices etc.

**Closed** 2021-09-11 03:19 UTC
Labels: Windows, Dependency Issue, Confirmed
