### ISSUE TITLE
OBS causes NVIDIA driver timeout

### ISSUE THREAD

**Issue by 40wattrange** [obsproject/obs-studio#7714] opened 2022-11-03 18:14 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/8CziJ2sFuAUHCblc

### Expected Behavior

To not timeout my display driver

### Current Behavior

Just by having OBS open, my nvidia driver will time out. Sometimes it successfully restarts, other times it will require a hardboot of my system to get video back. All browser sources vanish and will not return until I restart OBS.

This also causes the OBS preview to shrink horizontally by half, and only corrects when I resize OBS.

I do not have to be recording or streaming. Simply having OBS open will lead to this issue. It does not occur in any other situation. It only occurs when OBS is open.

### Steps to Reproduce

1. Open OBS 
2. Wait some time (or if you'd like to force it you can open GeForce Experience)
3. Driver timeout
...

### Anything else we should know?

This only started happening after the 28 update. I saw the twitter post stating that there were issues with the 526 driver, but this happens on all driver versions going back to 512 (where I stopped testing). It really appears to be an OBS issue as the driver is fine until OBS is open.

This has persisted across 2 different GPU's (1660Ti and 3060Ti) as well as 3 different driver versions, utilizing the official nvidia driver/application removal tool in between driver installs.

I can reproduce the timeout by opening obs, then opening GeForce Experience. Roughly 40% of the time this will cause a timeout, and its a 50% chance that the driver will recover, while the other 50% of the time it requires me to hard boot the machine to get video back.

Here is a link to it happening while streaming. Please note this is not an emulator running on PC, but a console being captured via capture card. Please note how the stream does not recover until the driver restarts, and all browser sources at that point vanish, and cease to work until I restart OBS - refreshing the cache of the sources does not kick it back into gear.

https://clips.twitch.tv/CautiousAverageTireTBTacoLeft-_sZ3tiBWknq1VmGd

On my end OBS briefly pauses, then changes my preview window to half the horizontal length.

The linked log is from me doing a reproduction via the GeForce Experience method. As OBS itself does not crash, there are no crash reports from OBS.

My Event viewer also logs the timeout.

**Comment by Fenrirthviti** [comment] 2022-11-03 18:30
This log file is extremely difficult to parse because it contains over 50,000 lines of spam about a failing websocket connection:

12:44:31.178: [obs-websocket] [WebSocketServer::onClose] WebSocket client `[::ffff:127.0.0.1]:52751` has disconnected with code `4010` and reason: You appear to be attempting to connect with the pre-5.0.0 plugin protocol. Check to make sure your client is updated.
12:44:31.179: [obs-websocket] [WebSocketServer::onOpen] New WebSocket client has connected from [::ffff:127.0.0.1]:52752

The reported freeze on 526 is *only* related to video capture devices, and has something to do with enumerating devices, so whatever this might be, is likely not related to that.

I am seeing a lot of other indicators that your PC is overloaded and unstable in the little of the file I can read before it gets overwhelmed by the websocket spam, such as max audio buffering which is usually a performance issue indicator. Please replicate this in a clean scene collection, and without any third-party plugins installed, as the current reproduction steps are not sufficient at this time.

**Comment by 40wattrange** [comment] 2022-11-03 21:04
After testing further for the rest of the day, the issue does seem to be window capture sources and the "multi adapter compatiblity mode" option.

Again, I dont have multiple GPUs in crossfire/SLI.

Is this expected behavior, or should I close out this ticket and open a new one?

It does resolve the issue for me, but not sure that is expected behavior since im on a single GPU.

**Comment by Fenrirthviti** [comment] 2022-11-03 21:26
In practice, the "multi adapter compatibility" options forces shared memory textures (i.e. running through normal RAM instead of staying on GPU), and shouldn't ever be used outside of no other options for cross-GPU capture. Crashes with it enabled are curious, but also point further towards some kind of overall system instability. We can leave this open for now, until we get some time to test on our end, as knowing that option might cause a problem is certainly curious, and not something very commonly tested in depth, especially now that WGC capture more or less eliminates the need for it.

**Comment by 40wattrange** [comment] 2022-11-03 21:37
Just to clarify, when the option is unchecked is when it does crash. If I
check off the option enable it it runs smoothly and never crashes. And I am
not running in crossfire or SLI.

**Comment by RytoEX** [comment] 2022-11-03 21:56
The phrase "check off" makes it sound like "turning the check off", so it has, at times, been difficult to follow this conversation. Please clarify with "checked" vs. "unchecked", "enabled" vs. "disabled", "with Multi-adapter Compatibility" vs. "without Multi-adapter Compatibility" or some other description that is less ambiguous.

Furthermore, the option is not available with WGC. Do you have any issues with using WGC instead of BitBlt?

As requested above, please provide a new log file from a clean scene collection, with just an affected window capture source, without third-party plugins, so that we can more easily isolate relevant information from the log.

**Comment by 40wattrange** [comment] 2022-11-03 23:28
My apologies, I will use "enabled" and "disabled" from now on for clarity. To reiterate the situation with more clarity and with knowing the actual issue:

When OBS 28 came out, I started receiving random NVIDIA driver timeouts while using OBS28. It did not have to be recording or streaming, but only running to produce this timeout, and never occurred unless OBS was running. After two weeks of troubleshooting I submitted this issue as it seemed semi-related to the other driver issues that were being reported.

After submitting this report I started to dig through the logs further as I had also noticed all the websocket issues. Through further troubleshooting I had come to find that it would only cause a driver timeout when I was actively running apps that were being captured via Windows Capture with OBS, as well as OBS itself. It is specifically the combination of OBS running, and capturing windows of the active apps. Though it seems to be capturing any window, in my case specifically I am capturing LiveSplit and RetroSpy. These are independent apps and have no plugins tied to OBS. If these apps are not open while OBS is running, therefore not capturing them, it would be fully stable. If I run these apps while OBS is closed, the driver is fully stable - so it seems to be an issue tied to OBS capturing windows of active apps. I can reproduce the issue with either app on its own.

After narrowing down the issue to this specifically I started digging through the capture windows settings and noticed the "Multi-Adapter Compatibility" option - which is disabled by default. Just for the hell of it I decided to enable it even though my system only has a single GPU (at first a 1660Ti which I later replaced with a 3060Ti, still having these issues). After enabling this option on all of my window capture sources, I could no longer reproduce the issue.

To test further I disabled the multi-adapter compatibility. As soon as I did I was able to reproduce the issue again. I then enabled the option again, and was unable to reproduce, disabled it and was again able to reproduce. I would randomly test this over the course of 2 hours, and each time the results were the same; if MultiAdapter Compatibility was enabled my driver seemed stable, if it was disabled (the default setting) it would timeout.

As requested above - I have now created a new scene profile and started with a completely empty scene, adding just the window captures - and I no longer seem to be able to recreate the issue, even with the default settings that were causing the issues previously.

Switching back to my previous Scene Collection, the issue occurred immediately. So I moved back to the fresh scene collection and added my Video Capture Device use to capture my consoles. At that moment it immediately timed the driver out on the fresh scene that was only the single capture and the 2 windows captures. Removing the 2 window captures, I cannot reproduce the issue. So now it seems to be a combination of OBS, Windows Capture, and Video Capture all with the default settings.

On this fresh scene, I then enabled the "multi adapter compatibility" option on both of the window captures and was no longer able to reproduce the issue. To then test this further I disabled the option, and was able to reproduce the issue.

So to summarize the issue:
Fresh Scene Collection: 2 Window Captures and 1 Video Capturing Device (also 1 window capture and 1 video capturing device tested)
The driver will time out when Multi Adapter Compatibility is disabled.
The driver does not seem to ever time out if Multi Adapter Compatibility is enabled.

Again, I only have a single GPU (unless you count the built in graphics on my mobo/intel proc) but enabling the Multi Adapter Compatibility option seems to keep the system stable.

Here you can find the log file that was generated while I did all of this testing:
https://obsproject.com/logs/2xPq-4tiobw784Ws

Here you can find the log file created after closing obs, deleting all logs, then generating a fresh log file with a driver timeout which occurred as soon as I opened OBS:
https://obsproject.com/logs/6AzGe8DsXArmWPLE

I hope this clarifies the situation better with a fresh scene.

**Comment by 40wattrange** [comment] 2022-11-03 23:36
Seeing this comment I tested this request:
Furthermore, the option is not available with WGC. Do you have any issues with using WGC instead of BitBlt?

My captures were set to automatic. Moving them specifically to WGC (which I assume is the option just titled Windows 10 (1903 and up)) it seems I am unable to reproduce the driver timeout. I tested both the fresh scene collection and my normal scene collection.

So it seems the automatic selection is the cause. Not sure why that changed between OBS27 and OBS28 - but so far this has seemed to fix the issue.

I will continue to test as sometimes it just shows itself randomly, but it does seem that specifying the windows capture method corrected the behavior.

I appreciate everyone's patience and assistance.

**Comment by RytoEX** [comment] 2022-11-04 00:16
> Though it seems to be capturing any window

Please confirm if you can reproduce this capturing some other application.

> These are independent apps and have no plugins tied to OBS.

What we meant by "no third-party plugins" is "use an OBS installation without any third-party OBS plugins". This has nothing to do with whether or not the target applications being captured have OBS plugins. We mean in a fresh OBS installation (or portable mode installation) to rule those out as possible contributing factors.

> Fresh Scene Collection: 2 Window Captures and 1 Video Capturing Device (also 1 window capture and 1 video capturing device tested)

The Video Capture Device is interesting. What devices are listed as available to capture?

> Again, I only have a single GPU (unless you count the built in graphics on my mobo/intel proc) but enabling the Multi Adapter Compatibility option seems to keep the system stable.

Yes, the iGPU is a GPU, so we would count that. Multi-adapter Compatibility essentially forces a capture method that is more reliable when multiple GPUs are present, though is not as performant. Please confirm that all displays are physically connected to the NVIDIA GPU and that none are connected to the iGPU on the motherboard. If possible, please also verify the driver version of the Intel iGPU.

**Comment by 40wattrange** [comment] 2022-11-04 19:55
At this time I really think changing the method of window capture from automatic to "windows 10 (1903 and up)" has been the true fix for this issue.

Though, I am still willing to help if you think this is a problem with OBS that needs to be looked into and verified if a bug or not.

Please let me know if you'd like me to continue with the above troubleshooting steps, because I'm willing to keep going with it just to figure out why "automatic" is causing the driver timeouts.

**Comment by RytoEX** [comment] 2022-11-04 21:12
"Automatic" is automatically selecting "BitBlt". In theory, you would encounter the same issue if you manually selected "BitBlt" and ensured that "Multi-adapter Compatibility" was unchecked. "Automatic" itself just chooses either "BitBlt" or "Windows 10 (1903 and up)" (which we refer to as WGC or Windows Graphics Capture). "Automatic" is not, itself, another capture method.

My questions above are to determine if there is some sort of bug that we actually need to address.

**Comment by 40wattrange** [comment] 2022-11-04 21:20
With the known setup that will cause the timeout I captured notepad instead of livesplit and/or RetroSpy and was able to still make the driver timeout. It happened right when I switched from WGC to Automatic.

The options available with the Video Capture device were:
My HDMI Capture Card used for the console (just lists it as its serial number) - this is the device selected and in use
Elgato Cam Link 4k (to capture my DSLR camera)
Microsoft LifeCam Studio (an additional webcam)
OBS Virtual Camera
[2022-11-04 16-15-59.txt](https://github.com/obsproject/obs-studio/files/9942014/2022-11-04.16-15-59.txt)

All monitors are plugged into the NVIDIA 3060Ti. I never use the onboard graphics in any way, though they are enabled in my device manager.

Attached is a fresh log file on the fresh scene collection that only contains the capture card and windows capture of notepad.

**Comment by RytoEX** [comment] 2022-11-05 00:49
I would still like to see this reproduced in an OBS installation that does not have third-party plugins installed.

**Comment by 40wattrange** [comment] 2022-11-05 01:10
Just downloaded the portable zip, cleared log files, launched it, reproduced situation instantly.
[2022-11-04 20-08-59.txt](https://github.com/obsproject/obs-studio/files/9942646/2022-11-04.20-08-59.txt)

**Comment by 40wattrange** [comment] 2022-11-05 01:12
I noticed the log file said something about GPU priority since it wasnt admin, so I redid this while launching portable OBS as admin, same results.
[2022-11-04 20-11-36.txt](https://github.com/obsproject/obs-studio/files/9942653/2022-11-04.20-11-36.txt)

**Comment by 40wattrange** [comment] 2022-11-05 04:08
Looking at error 887A0005 on google I see a lot of stuff about Hardware Accelerated GPU scheduling.

**Comment by 40wattrange** [comment] 2022-11-05 19:23
Just to provide further info - this morning my OBS was on a rampage just timing out the driver left and right no matter what. 

Attempted OBS27 - Same results
Attempted Streamlabs Studio - Same results.

Formatted my machine and reinstalled Windows 11

Back to the situation prior - Stable with WGC, timeout with Auto/Win7.

Not sure if that means its a system thing, or a software thing.

**Comment by Fenrirthviti** [comment] 2022-11-05 20:12
Just as a note, 887A0005 error code is a Windows error code that means: DXGI_ERROR_DEVICE_REMOVED

In practice, this just means "the driver crashed for some reason" and doesn't really provide any additional context on what or why. There are a bunch of different causes for it, all the google results are currently poisoned with a bunch of people complaining about Call of Duty specifically, but it's not directly tied to or related to HAGS itself.

**Comment by 40wattrange** [comment] 2022-11-05 21:11
I wasn't denying it was an OS error, but software can do things to cause the OS to generate errors. Make of it what you will with the information provided - at this point it seems stable and I can no longer to force it to crash when HAGS is disabled. Though time will tell since I thought WGC was stable, and eventually had further issues.

I only had issues with OBS (Streamlabs too, but I know that's just OBS source) so figured I would provide the information. If you consider this some sort of fluke with windows, so be it. No games, nor other software that utilized my GPU, generated these timeouts.

It happened on my old Windows installation, a fresh Windows install, and on both the fresh and old image disabling HAGS no longer produces the error so far - even using BitBLT.

I just didn't wanna ghost anyone and wanted to provide all information. Feel free to ignore this, close this, write it off as a Windows error.

Thanks for everyone's help. If something further happens I'll post it up, or if someone has any further questions I can answer them, but as of now I'm taking a break from this.

**Comment by RytoEX** [comment] 2022-11-06 00:14
> Though time will tell since I thought WGC was stable, and eventually had further issues.

Are you saying that you had driver timeouts when using WGC? I didn't see that previously mentioned, so I wanted to ask to be sure.

**Comment by 40wattrange** [comment] 2022-11-06 00:32
This is correct. Last night I attempted to add a VLC Source to my scene. It had a single video - and this caused everything to completely go haywire.

Even after removing the source and closing OBS for the night - I woke up and opened obs and it was just timing the driver out left and right - constantly out of control - and only stopped once I closed OBS. Previously I had no VLC sources that contained video, only audio.

After that I tested OBS27 and even Streamlabs Studio. All 3 could cause the issue, whereas before 27 did not.

At that point I imaged my machine, wiped it, installed a fresh copy of 11, and it still would happen. Then I remembered the 887A0005 error, so I disabled HAGs and it all went away.

So at that point, I restore the image I took, disabled HAGs, and so far I cannot reproduce the issue in any way, shape, or form.

I'm not holding my breathe, because obviously we have been here before, but even now BitBLT is working without issue, and I haven't had a single timeout with OBS running the entire time since posting last.

Since it was happening on OBS27, which it had never done prior, this leads me to believe it is possibly an issue with Windows 11 22H2.

![image](https://user-images.githubusercontent.com/1192974/200148558-ed890991-88d5-4761-8a3a-946630f63092.png)

**Comment by 40wattrange** [comment] 2022-11-06 00:58
Also I found this when Googling "obs windows hardware accelerated gpu scheduling"

https://obsproject.com/wiki/How-to-disable-Windows-10-Hardware-GPU-Scheduler

**Comment by 40wattrange** [comment] 2022-11-09 05:39
Just wanted to circle back here and say that since disabling HAGS I haven't had a single issue.

**Comment by 40wattrange** [comment] 2022-11-16 17:37
Final update from myself unless I notice anything has changed moving forward; another 8 days have gone by, streaming almost every day, not a single issue.

I may try to enable HAGS again at some point just to see what happens. If I do, and I see any different results I will update, otherwise I'll be going radio silent on the issue.

**Comment by RytoEX** [comment] 2022-11-16 18:49
Closing as a HAGS/driver issue, per above.

**Closed by RytoEX** 2022-11-16 18:49 UTC

**Comment by Fenrirthviti** [comment] 2022-11-16 23:48
As a final note to this, we've heard reports that the driver issue with HAGS is resolved, or at least significantly mitigated, in driver version 526.98.

**Comment by DarkestFantasies** [comment] 2022-11-20 10:18
hello, i have same issue but my gpu is rx 550, same error in log files, but this video card does not even have HAGS
