### ISSUE TITLE
Fullscreen Projector blank (gray) on startup with "Save projectors on exit" turned on.

### ISSUE THREAD

**Issue by sprEEEzy** [obsproject/obs-studio#5197] opened 2021-08-26 21:08 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Y19SkUR8CniD6dml

### Expected Behavior

1. Turn on "Save projectors on exit"
2. Set a fullscreen projector on a monitor
3. Close OBS
4. Open OBS
5. Fullscreen projector opens and shows the preview image

### Current Behavior

After closing OBS, and re-opening it, the Fullscreen projector is opened, but it's only displaying a blank / gray screen.
![Capture](https://user-images.githubusercontent.com/9414375/131035736-33b0ed13-9ac8-432b-8f5e-9b323b1f4982.JPG)

It should be showing the preview.

### Steps to Reproduce

1. Turn on "Save projectors on exit"
2. Set a fullscreen projector on a monitor
3. Close OBS
4. Open OBS
5. Fullscreen projector is now open, but displays a blank gray screen, instead of the preview image
...

### Anything else we should know?

Replicated on two different monitors.

**Comment by sprEEEzy** [comment] 2021-08-28 08:03
Related: https://obsproject.com/forum/threads/obs-studio-portable-deployment-with-fullscreen-projector-give-a-gray-projector-preview-screen.144792/

**Comment by lublak** [comment] 2022-01-14 16:04
I have the same issue (on windows 10).
All monitors are the same type. (MSI MAG274QRF-QD)
If i can provide a log please then just mention me.
I use obs it in portable mode.
I i open the projector manually it works fine.

**Comment by gxalpha** [comment] 2022-11-30 20:57
Duplicate of #5083

**Closed by gxalpha** 2022-11-30 20:57 UTC
