### ISSUE TITLE
Hibernation and Standby issues with active replay buffer

### ISSUE THREAD

**Issue by fwillo** [obsproject/obs-studio#4187] opened 2021-02-04 14:58 UTC
Hey,

I'm running OBS as a replacement for Shadow Play in order to capture some events while playing etc. Unfortunately, I'm running into some problems: on my computer, the replay buffer is always active and I'm frequently using hibernation and/or standby. Here's the description:

## Platform

Operating system and version: Windows 10 1909
OBS Studio version: 26.1.1 (64-bit)

## Expected Behavior

When running OBS with active replay buffer, putting Windows into...
- Standby should bring the computer into standby and resume (not necessarily with a continous replay buffer) without malfunction of OBS and replay buffer
- Hibernation, resuming from it should result in a flawless operational mode of OBS with active replay buffer

## Current Behavior

Respectively to the list of expected behaviour, it...
- is not going correctly into Standby, only the screen fades to black. Any key pressing etc. brings the system back, however.
- is messing something up with OBS. My CPU usage of OBS with active replay buffer increases from ~1% before Hibernation to ~15% after resuming. Capturing the replay buffer is not responding. OBS ist not responding when turning of replay buffer and has to be killed by the task manager. Restarting OBS restores the functionality of the replay buffer

## Steps to Reproduce

1. Extreme simple setup only providing the capability of replay buffering in OBS
2. Going into Standy or Hibernation, respectively.

## Additional information

Maybe it helps to catch Standy or Hibernation signals from the system in order to deactivate the replay buffer only to reactivate it after resuming? This might be a workaround. A continous replay buffer between the two events is probably not beneficial.

**Comment by notr1ch** [comment] 2021-02-04 15:16
Many places in OBS expect consistent, linear timestamps and sleep and hibernation break this assumption. A better solution may be to script OBS shut down / start up on suspend / resume. I don't think this is something that's feasible for us to fix without considerable changes to many different processing pipelines in OBS.

**Comment by fwillo** [comment] 2021-02-04 15:24
When manually deactivate replay buffer before standby/hibernation and then manually actiavte it after resuming respectively, I'm not experiencing any problems mentioned above. Saving the replay buffer after resuming gives a correct output.

**Comment by JonnyHaystack** [comment] 2021-04-15 20:08
Anyone got any pointers on how to get a script to run on hibernation and resume?

**Comment by Meachamp** [comment] 2021-04-20 02:15
Here's a quick plugin I whipped up to address this: https://github.com/Meachamp/OBS-NoPreventSleep
It's a bit hacky, but should work fine if all you're using it for is the replay buffer. Currently only supports windows x64.

**Comment by RytoEX** [comment] 2022-11-02 20:59
Per @notr1ch 's comment above, this is by design, so I will close this as "working by design".

**Closed by RytoEX** 2022-11-02 20:59 UTC
Labels: Windows

**Comment by 2048khz-gachi-rmx** [comment] 2024-05-06 14:35
Figured i should share a workaround, since this issue pops up as the first result in Google:
OBS doesn't allow Windows to hibernate, but you can override this behavior by running this in the command line [\(credits\)](https://obsproject.com/forum/threads/obs-prevents-screen-sleep-any-work-around.111687/post-606655):
`powercfg -requestsoverride process obs64.exe display system awaymode`  

This will allow hibernating with OBS on, but then you'll run into another issue: after waking up, OBS will start choking and dying while consuming all the CPU time it can. As mentioned in the issue, you won't be able to stop/save the replay buffer and the only option you'll have is to kill and restart OBS. However, you can automate this via the Task Scheduler built into Windows. Create a new task, add an "At log on" trigger, then add these actions:
- Start a program
Program: `taskkill`
Arguments: `/f /im "obs64.exe"`
  
- Start a program
Program: `C:\obs-studio\bin\64bit\obs64.exe` **(change the path to your installation path!)**
Arguments: `--startreplaybuffer --minimize-to-tray --disable-shutdown-check --multi`
Start in: `C:\obs-studio\bin\64bit\` **(change the path to your installation path!)**

This will essentially kill the previous instance of OBS then immediately launch a new one with the replay buffer on.

--------

**UPD:** After some windows updates, it stopped prompting me for my password after sleep, and i found out that if windows doesn't lock your PC then it never generates "at log on"/"on workstation unlock" events either (\#justwindowsthings)

You can add another trigger if yours doesn't have a lock screen either:
"On an event"
**Log:** System
**Source:** Power-Troubleshooter **(Use the dropdown menu, otherwise it won't work \#justwindowsthings)**
**Event ID:** 1
