### ISSUE TITLE
OBS Icon with multiple monitors

### ISSUE THREAD

**Issue by CyrosX** [obsproject/obs-studio#4869] opened 2021-06-11 10:33 UTC
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/dq3sfNqkrzQEtQvB

### Expected Behavior

Mac Bar Icon looks normal

### Current Behavior

Non-active monitor (clicked something on the other one)
shows an ugly icon
<img width="141" alt="obs" src="https://user-images.githubusercontent.com/15161462/121673410-242ec880-cab1-11eb-81f2-82b29aa94a66.png">

### Steps to Reproduce

1. Have 2 monitors (not mirrored)
2. Start OBS
3. Look at the Mac Bars

**Comment by gxalpha** [comment] 2021-06-11 10:42
I can confirm this, however it seems to happen with every non-Apple app, it’s not OBS-specific

**Comment by CyrosX** [comment] 2021-06-11 10:45
> I can confirm this, however it seems to happen with every non-Apple app, it’s not OBS-specific

I have several non-Apple apps, like MiniWOL or Rectangle - the icons are normal on both monitors.

**Comment by asher-the-thrasher** [comment] 2021-06-11 10:45
This happens to me as well, but the entire menu bar is like that so not an OBS issue but a Apple issue. I’ve found that clicking the menu bar generally fixes the issue for me

**Comment by gxalpha** [comment] 2021-06-11 12:13
Some research makes this seem like [QTBUG-88600](https://bugreports.qt.io/browse/QTBUG-88600)
I will look into this some more when I come home in a few hours, but if that is the case, there are 2 things:
- It should be fixed in QT 5.15 and QT 6.1, so once the update to QT 6.2 (which to my knowledge is planned anyways since it’ll enable Native Apple Silicon) is done, that would fix this bug
- There seems to be a workaround but again, I’ll look into that later today

**Comment by PatTheMav** [comment] 2021-06-25 14:19
Should be fixed via the patch applied as part of https://github.com/obsproject/obs-deps/pull/60.

**Comment by RytoEX** [comment] 2022-02-23 00:14
This should be fixed as of OBS Studio 27.2.0.

**Closed by RytoEX** 2022-02-23 00:14 UTC
Labels: macOS
