### ISSUE TITLE
OBS preview causes PC and mouse to stutter and chug on recent AMD GPU driver versions.

### ISSUE THREAD

**Issue by IDLauncher** [obsproject/obs-studio#7884] opened 2022-12-01 23:38 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/forum/attachments/2022-11-30-14-43-44-txt.89314/

### Expected Behavior

PC performance to not become stuttery and chunky

### Current Behavior

Upon opening OBS, PC and mouse would begin to heavily stutter making operating the PC difficult.

### Steps to Reproduce

1. Use an AMD 6900XT GPU with driver version 22.10.2 or newer
2. Open OBS with preview enabled
3. PC Performance immediately degrades

### Anything else we should know?

Having solved the issue by downgrading my GPU driver I consider this to be AMD's problem, but figured OBS group should be aware of it in case they can mitigate it themselves OR influence AMD to resolve it.

I have reported it to AMD as well. All for good measure. Thanks for reading.

**Comment by RytoEX** [comment] 2022-12-01 23:45
If the issue is not observed with AMD's Recommended drivers for this OS+GPU configuration (22.5.1), then I would consider this an AMD driver issue.

**Comment by IDLauncher** [comment] 2022-12-01 23:56
> 

While I have not tried 22.5.1 specifically, the version I am currently using (22.10.1) does not seem to have the issue in my tests

I have verified that the bug IS present in 22.10.2, 22.10.3, 22.11.1, and 22.11.2

Thanks again.

**Comment by IDLauncher** [comment] 2023-01-12 05:41
Update for anyone encountering this issue. I managed to get newer drivers to behave by disabling something called "Multiplane overlay" in the Windows registry.

I don't know if that's something AMD should sort out but this is a better solution than using older drivers that crash in VRChat. :P

I'm not sure if this should be closed or not at this point, so I'll let someone else make that choice, but thanks for reading, and I hope this helps someone else not have to deal with this.

**Comment by Fenrirthviti** [comment] 2023-03-15 20:56
Appears to have been related to AMD drivers, closing.

**Closed by Fenrirthviti** 2023-03-15 20:56 UTC
