### ISSUE TITLE
RAM Fills Up Streaming With SRT

### ISSUE THREAD

**Issue by krakow10** [obsproject/obs-studio#7305] opened 2022-09-05 20:32 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/PDd6LGiSG30A1uz7

### Expected Behavior

Memory stays around 600M

### Current Behavior

OBS memory usage increases with total stream data transmitted

### Steps to Reproduce

1. Stream SRT at high bitrate 100mbps or low bitrate for a long time
2. Watch memory usage climb

### Anything else we should know?

I tested RTMP streaming and did not see the memory buildup.  I also tested this on an unpatched master build and saw the same behaviour even though the log is using a patched OBS version.

**Comment by pkviet** [comment] 2022-09-05 20:59
i repro'd on windows and indeed it's leaking while the older output was not.
I'm investigating the root cause.

**Comment by pkviet** [comment] 2022-09-05 23:41
Fixed by https://github.com/obsproject/obs-studio/pull/7306

**Comment by krakow10** [comment] 2022-09-06 05:17
The patch works for me, now I can use OBS 28.  Thanks for addressing this!

**Closed** 2022-09-10 22:31 UTC
Labels: Fix available, Confirmed
