### ISSUE TITLE
[BUG] Switching scene collections OBS thinks scenes from previous collection are in current one.

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2709] opened 2020-04-13 18:28 UTC
## Platform

Operating system and version:  Windows 10/x64 1909
OBS Studio version: 25.0.4

## Expected Behavior

When switching from one Scene Collection to another in OBS studio, the previous scene collection should be completely unloaded and not interfere with the new Scene Collection being switched to.

## Current Behavior

After switching from one collection to another, if I try to add a new scene named "Scene 2", OBS defaults to wanting to call it "Scene 3" because it insists there is already a scene called "Scene 2" available.  In reality, the previous scene collection had a "Scene 2" in it, and OBS studio seems to think it still exists in the new scene collection after switching even though it does not exist in the new one.

https://obsproject.com/logs/daEbQVFfyyT2I7sk

## Steps to Reproduce

1. Clean OBS installation
2. In default setup, add a new scene called Scene 2.
3. Now create a new scene collection and OBS switches to it, it only has a scene called "Scene"
4. Try to add a new scene, and OBS defaults its name to "Scene 3" and if you try to call it "Scene 2" it says that that scene already exists.

## Additional information

I believe this is a part of a bigger bug in which OBS is misinterpreting and/or copying data from one scene collection to another, potentially corrupting scene collections with duplicated scenes etc. which I am currently working on creating additional bug reports for as I narrow down simple to reproduce test cases.

**Comment by notr1ch** [comment] 2020-04-17 19:05
This is a caused by the same issue as https://github.com/obsproject/obs-studio/issues/2724 - scene data is not properly cleared. Going to close this so we have a single ticket to track.

**Closed by notr1ch** 2020-04-17 19:05 UTC
