### ISSUE TITLE
select monitor crash 

### ISSUE THREAD

**Issue by glepnir** [obsproject/obs-studio#9655] opened 2023-10-02 10:21 UTC
### Operating System Info

Other

### Other OS

Arch linux with hyprland

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/jB6NS2Ot4KcWmREa

### Expected Behavior

works fine

### Current Behavior

after select monitor crash

### Steps to Reproduce

open from command line then select monitor crash

### Anything else we should know?

this is crash debug log

```
󰘧 obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Platform: Wayland
info: CPU Name: Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
info: CPU Speed: 3491.775MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 10582MB Total, 6160MB Free
info: Kernel Version: Linux 6.5.5-arch1-1
info: Distribution: "Arch Linux" Unknown
info: Desktop Environment: Hyprland (hyprland)
info: Session Type: wayland
info: Qt Version: 6.5.3 (runtime), 6.5.1 (compiled)
info: Portable mode: false
info: OBS 29.1.3-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter AMD AMD Radeon RX 580 Series (polaris10, LLVM 16.0.6, DRM 3.54, 6.5.5-arch1-1)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.2.1-arch1.1, shading language 4.60
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Bicubic
        fps:               60/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
warning: v4l2loopback not installed, virtual camera disabled
error: VAAPI: Failed to initialize display in vaapi_device_h264_supported
info: FFmpeg VAAPI H264 encoding not supported
error: VAAPI: Failed to initialize display in vaapi_device_hevc_supported
info: FFmpeg VAAPI HEVC encoding not supported
info: ---------------------------------
info:   Loaded Modules:
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.80) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.80) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
info: pulse-input: Started recording from 'alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback' (default)
info: [Loaded global audio device]: 'Mic/Aux'
info: PipeWire initialized
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Screen Capture (PipeWire)' (pipewire-desktop-capture-source)
info: ------------------------------------------------
info: [pipewire] Screencast session created
info: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)

QWidgetWindow(0x55fb8caf9da0, name="previewWindow") must be a top level window.
info: [pipewire] Asking for desktop
info: [pipewire] desktop selected, setting up screencast
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
info: [pipewire] Server version: 0.3.80
info: [pipewire] Library version: 0.3.80
info: [pipewire] Header version: 0.3.72
info: [pipewire] Created stream 0x55fb8ed27440
info: [pipewire] Stream 0x55fb8ed27440 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x55fb8ed27440
info: [pipewire] Stream 0x55fb8ed27440 state: "paused" (error: none)
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 7 (Spa:Enum:VideoFormat:RGBx)
info: [pipewire]     Size: 1920x1080
info: [pipewire]     Framerate: 0/1
info: [pipewire] Stream 0x55fb8ed27440 state: "streaming" (error: none)
zsh: segmentation fault (core dumped)  obs

```

**Comment by tytan652** [comment] 2023-10-02 10:43
Duplicate of #9617

**Closed by tytan652** 2023-10-02 10:43 UTC
