### ISSUE TITLE
OBS hangs/breaks/crashes when talking to a badly implemented rtmp server

### ISSUE THREAD

**Issue by udoprog** [obsproject/obs-studio#4135] opened 2021-01-25 16:06 UTC
I'm working on an RTMP protocol implementation for Rust currently named `tournie` which is incomplete. And I'm using OBS to test the implementation, and while doing so I've found some cases where OBS can hang, crash, or otherwise end up in such state that it's unable to establish new RTMP connections.

Note that while this specific issues is caused by OBS talking to a bad or malicious implementation. The issue I'll be outlining below seems to occur primarily because the client disconnects in the middle of processing a `connect` command. Something that could plausibly happen in the real world due to a connection loss.

While working on `tournie` I've also found some more cases where malicious implementations of RTMP can cause OBS to crash. If you'd like I can submit them as separate issues. But note that they are also more artificial.

## Platform
Operating system and version: Windows 10, 10.0.19041 (probably doesn't matter)
OBS Studio version: 26.1.1

## Expected Behavior
OBS should recover from broken RTMP sessions.

## Current Behavior
OBS doesn't recover from a broken RTMP session.

## Steps to Reproduce
I've made the experimental code available for you to reproduce. A version of `tournie` that triggers this bug can be checked out from here: https://github.com/udoprog/tournie/tree/obs-result-bug

1. Start the server with `cargo run` (you need to have Rust installed, see: https://rustup.rs).
2. Configure OBS Studio to use a Custom server and set it to `rtmp://localhost`. Stream key doesn't matter.
3. Start Streaming. A popup (see below) will show up saying that you failed to connect.
4. If you don't crash:
  * Try to connect to `tournie` again (Custom server). You'll notice that you get an error saying that the handshake from OBS was incorrect (see screenshot).
  * Switch to a different streaming service (I've tried `Twitch`). Trying to stream hangs forever or crashes after pressing `Start Streaming`.

**Failed to connect popup**
![image](https://user-images.githubusercontent.com/111092/105729456-87b6c000-5f2d-11eb-8446-85e2f2be1dc3.png)

**Invalid handshake from OBS**
![image](https://user-images.githubusercontent.com/111092/105729832-e9772a00-5f2d-11eb-967f-f2b4c0bbdba6.png)

## Additional information
Some RTMP protocol details:

The branch of `tournie` I've provided is implemented to close the connection immediately after returning the `_result` command response from a `connect` attempt. This is a rough timeline of what it does:

```text
 +--------------+                              +-------------+
 |    Client    |               |              |    Server   |
 +------+-------+               |              +------+------+
        |               Handshaking done              |
        |                       |                     |
        |                       |                     |
        |                       |                     |
        |                       |                     |
        |----------- Command Message(connect) ------->|
        |                                             |
        |<------- Window Acknowledgement Size --------|
        |                                             |
        |<----------- Set Peer Bandwidth -------------|
        |                                             |
        |<------------ Command Message ---------------|
        |         (_result- connect response)         |
        |                                             |
        |                                             | *close connection*
```

Screenshot of wireshark for the exchange (can provide a pcap file if you want it, but it's easy enough to do yourself):
![image](https://user-images.githubusercontent.com/111092/105734531-03673b80-5f33-11eb-8407-9a93ccf9ea3c.png)

> We specifically do not receive the "Acknowledgement" packet sent by the client, and we don't send a `StreamBegin` command.

After this, it seems like OBS is unable to perform additional handshakes. The fact that I also encounter sporadic crashes could mean that we are seeing some form of memory corruption.

**Comment by WizardCM** [comment] 2021-01-30 03:33
Could this be a duplicate of #2865?

**Comment by udoprog** [comment] 2021-01-30 04:04
Oh yeah. Especially this sounds rather familiar: https://github.com/obsproject/obs-studio/issues/2865#issuecomment-647130593

**Comment by WizardCM** [comment] 2021-01-31 02:29
Great! In that case, I'll close this one as a duplicate for now. If the PR doesn't fix this issue, we can always reopen.

Duplicate of #2865

**Closed by WizardCM** 2021-01-31 02:29 UTC
