### ISSUE TITLE
Video plays in slow motion when replayed

### ISSUE THREAD

**Issue by CSMBY** [obsproject/obs-studio#5469] opened 2021-10-31 09:09 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/1jm7gwnVGSkkAxcz

### Expected Behavior

Video plays normally

### Current Behavior

Video plays in slow motion

### Steps to Reproduce

1. Create media source
2. Add MP4 video file
3. Set 'Restart playback when source becomes active'
4. Set 'Close file when inactive'
5. First time video plays normally
6. Deactivate media source
7. Activate media source within a few seconds
8. Video can be played in slow motion. If not, repeat from step 6. 

This bug is repeated with the 'Use hardware decoding when available' option enabled or disabled. This bug is not present in version 25-

**Comment by MattyFresh68** [comment] 2021-10-31 10:11
Sounds like a support issue not a bug report. Any media sources play back just fine.

**Comment by CSMBY** [comment] 2021-10-31 10:42
> Sounds like a support issue not a bug report. Any media sources play back just fine.

This is a random bug. You can repeat it 10 times, and everything will be fine, or you can get slow motion playback a second time. I tested different versions on the same hardware and with the same settings:
25.0.8 - no bug
26.1.1 - no bug
27.0.1 - no bug
27.1.3 - BUG

**Comment by MattyFresh68** [comment] 2021-10-31 11:58
Your steps for reproduction seem very lacking. You have no attached log. I stream on average 12 hours/week on 27.1.3 and have not experienced this with my media sources

**Comment by WizardCM** [comment] 2021-10-31 12:51
As this does not have valid reproduction steps, nor a log, I am closing this for now.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) for support. For more info, check our [Help page](https://obsproject.com/help).

**Comment by CSMBY** [comment] 2021-10-31 19:03
Brilliant!!! I already thought that I was stupid. I downloaded OBS 27.1.3 on a clean computer, with completely different hardware, create a media source, add a file and repeat the situation in 5 minutes!!!
Here are the valid steps, with the new step:
1. Create a media source
2. Add a MP4 video file (short, 5-10 seconds)
3. Set 'Restart playback when source becomes active'
4. Set 'Close file when inactive' (NEW STEP)
5. First time video plays normally
6. Deactivate media source
7. Activate media source
8. Video can be played in slow motion. If not, repeat from step 6 10-20 times

This is the critical bug, but it gets closed without even trying to reproduce it normally.

**Comment by CSMBY** [comment] 2021-10-31 19:13
A great chance to get this error is to deactivate the video without waiting for it to end, but during playback. Further activation may leads to slow playback

**Comment by Fenrirthviti** [comment] 2021-10-31 19:24
We also needed a log file. I understand that you're frustrated by us closing this issue which you believe to be a bug, but you did not provide sufficient replication steps, you did not provide a log (which I should add is a required field, so you consciously chose to ignore that step by entering a bullet in the field instead of a valid link), and we were not able to replicate the issue. This means, unfortunately, that we cannot take any action if it's an issue that is only occurring on your system. We reserve the github issues for confirmed and replicable issues, and regularly ask that users go through our support channels first if those are not available. When you ignore our bug report process and leave out critical information, it means we can't take action.

We will likely need more information and this should be triaged through our support channels first, which have been provided. If this is validated and better replication steps are found outside "do this and maybe it will break" we can certainly reopen this.

**Comment by CSMBY** [comment] 2021-10-31 20:09
I think, a log file is useless. There is enough info to reproduce this bug. Now I can repeat this bug everywhere on any hardware (AMD & NVIDIA videocards, AMD & Intel CPU)...
But if you want to see useless information, here it is from clean computer:
https://obsproject.com/logs/1jm7gwnVGSkkAxcz

**Comment by CSMBY** [comment] 2021-10-31 20:31
Video of reproducing this bug:

https://user-images.githubusercontent.com/45597461/139600262-1b81bc1e-d140-41c0-af93-3c68d8b845ea.mp4

**Comment by alinsavix** [comment] 2021-10-31 21:50
> I think, a log file is useless.

This is a problem that is obviously not experienced by everyone (I somehow doubt you're the only one that uses the media source and has it restart), there's obviously something about your environment which is triggering this, and the OBS log has all sorts of useful information about your environment. Why _wouldn't_ the log be useful?

Do you think when a maintainer says "I need a log to troubleshoot this" that they're just ... lying? They're not, but even if they were, why would you antagonize the people from whom you are asking for help (and some of the only people that would be able to actually, y'know, fix a real bug, if found)? Seems like that'd be more likely to make people **_less_** interested in working with you or investigating your problem.

**Actual OBS support content:** I set up a media source as directed, and spent a good 20 minutes turning it on and off trying to reproduce this, with varied 'on' and 'off' lengths of time, without success. I did sometimes notice the first couple of frames seem to stutter (which makes sense, if the media is having to be reopened every time), but nothing lasting beyond the first second or so.

My log, should it be helpful in narrowing down what set of things causes this: https://obsproject.com/logs/hNdLsH_tiLP-DGxW

**Comment by CSMBY** [comment] 2021-10-31 22:55
> I set up a media source as directed

The second step was about a MP4 file, not a MOV. And the chance of getting a bug significantly increases if a minimum time passes between deactivation and activation.

Some other info:
![bug](https://user-images.githubusercontent.com/45597461/139603950-ee2818e1-be9e-4869-9b0a-5a52cab7f28b.png)

**Comment by CSMBY** [comment] 2021-11-01 11:45
I tested it on a laptop with two video cards (Core i7-8750H). It's almost impossible to catch a bug on GTX 1050 Ti. But if I run OBS on Intel UHD Graphics 630, then the bug is caught in a few minutes. The better and faster a video card, the less likely it is to catch a bug.

**Comment by alinsavix** [comment] 2021-11-01 15:32
Okay, so this is interesting. Took my previous test video, ran ffmpeg across it to visually number the frames, and output as mp4. Configuration otherwise identical to previous log. Hit record on OBS, poked the button a few times.

First run through test video: 1:1 match between frames of test video and frames of OBS recording.

Source was disabled in the middle of playback.

Source was enabled shortly thereafter (approx 0.5s). The last displayed frame of the previous run through the video is recorded for 30 frames, followed by a correctly playing video starting at frame 1

Source again disabled in the middle of playback

Source enabled again (approx 1.5s later). The last displayed frame of the previous run is again recorded for 30 frames, but this time is followed by the test video **playing back at half speed** for 60 frames of the recording (30 frames of the test video). After 60 frames of the recording, the test video plays back at the correct speed, **but only every other frame** -- so the frames end up being displayed as `31,31,33,33,35,35,37,37` (etc)

So this absolutely appears to be a genuine bug that may be hard to visually identify (depending on the test video), but is easily visible under test conditions (numbering the test video frames and stepping through the frames of the resulting recording).

I'm happy to provide my test recording if anyone on the OBS team would like it.

**Comment by PeterAkakpo** [comment] 2021-11-04 09:09
OBS team is in the habit of dismissing issues that come up with the software and referring them to discord without any proper investigation. the most annoying thing of all is that they are in a hurry to mark the issue as closed. its a bad attitude

**Comment by Fenrirthviti** [comment] 2021-11-04 16:36
> OBS team is in the habit of dismissing issues that come up with the software and referring them to discord without any proper investigation. the most annoying thing of all is that they are in a hurry to mark the issue as closed. its a bad attitude

This goes both ways, we don't "dismiss" issues, we ask that users go through the proper support channels to collect information and verify reports first. As it stood, this report did not have the proper information for us to replicate the conditions reliably, and when asked for more information, the original poster was combative and rude. So, yes, those kinds of issues will get closed. We have processes for a reason, and GitHub issues (as has been explained in the PR template itself, and by several members of the community on dozens of issues) are reserved for verified bugs with proper replication steps.

**Comment by CSMBY** [comment] 2021-11-04 17:10
> As it stood, this report did not have the proper information for us to replicate the conditions reliably, and when asked for more information, the original poster was combative and rude.

Ahhhh ))) You confuse cause and effect. The bug was closed before "the original poster was combative and rude". No any more information was asked before the bug was closed.

Some bugs was promoted to features and then closed - https://github.com/obsproject/obs-studio/issues/5101
This closed "feauture" leads to others bugs:
https://github.com/obsproject/obs-studio/issues/5470
https://github.com/obsproject/obs-studio/issues/5444

As a result, everything stopped working as it should. Replays do not work, APNG does not work, PNG does not work, there is no more way to solve these problems... In old working versions, the necessary plugins are buggy, and if they are fixed, then they work only in new versions. Vicious circle...

**Comment by Fenrirthviti** [comment] 2021-11-04 18:04
I'm happy to discuss this on our Discord, but let's please keep this on-topic. Cross posting issues to unrelated reports is not an appropriate use.

**Comment by RytoEX** [comment] 2021-11-11 02:01
I can reproduce this in OBS Studio 27.1.3 and a build from git at commit 1017cd5430602f695713f191ef8f5fa9940baee6 with the updated steps to reproduce in [this comment](https://github.com/obsproject/obs-studio/issues/5469#issuecomment-955774966).  The combination of both "Restart playback when source becomes active" and "Close file when inactive" are _required_.  I have updated the steps to reproduce in the original issue post to make them easier to find.

This is much easier to see with a video that starts immediately with noticeable motion, because the effect only occurs for a short period.  Perhaps OBS is still unloading the source data from the Hide/Deactivate action while it's trying to load it anew for the Show/Activate action?

It's worth noting that I no longer see this behavior with commit 0815d5c887c934c7ad9e03cfd18fb1103fabf49b, which reverted commit 96c1a7652305784e4bf531933bc82535adcaf320.  That being the case, we'll likely consider this issue resolved.  The Windows 64-bit build is [available from GitHub Actions](https://github.com/obsproject/obs-studio/suites/4320374697/artifacts/113016277).

For the record, Media Source settings are contained in the OBS logs, so we would have been able to see that "Restart playback when source becomes active" and "Close file when inactive" were enabled from a log file.  This sort of information is very useful to help us reproduce issues like this.

**Comment by kkartaltepe** [comment] 2022-04-04 00:50
Can this be closed? With https://github.com/obsproject/obs-studio/commit/0815d5c887c934c7ad9e03cfd18fb1103fabf49b released in 27.2 this no longer occurs?

**Comment by RytoEX** [comment] 2022-04-04 03:42
Closing per the above comments.

**Closed by RytoEX** 2022-04-04 03:42 UTC
Labels: Confirmed
