### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by t2303** [obsproject/obs-studio#7519] opened 2022-10-03 23:20 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/JElinMNJGCAtLmfi

### Expected Behavior

In version 27 and previous, there would be a preview window that showed the entire window in the main frame, when oculus mirror opens the game capture would then place this window over the previous window while it was opened.

Going into the full screen preview should fill the screen with either the background video or game capture window

### Current Behavior

The main preview screen is only showing the top left with full screen preview mode having very little effect. Similar to #7428 
<img width="960" alt="SS2" src="https://user-images.githubusercontent.com/84062386/192937972-3c24a3de-4e59-4865-a05d-9441ab474d3d.PNG">

The game capture window is completely blank even when the window it is meant to capture is opened
<img width="960" alt="SS1" src="https://user-images.githubusercontent.com/84062386/192939341-a1549be9-4a57-4933-94e9-5a1c51918dca.PNG">

### Steps to Reproduce

Preview Window Issue

+ This happens as soon as OBS is opened

Capture Window:

1. Click on add source and select game capture (display capture also seems to have the same issue)
2. Give it a name
3. Set Mode to Capture Specific window
4. Select Oculus Mirror

### Anything else we should know?

In order to fix I have restarted the computer and reinstalled OBS (both version 28.0.2 and the last 27 version, both had the fault)

I often check drivers are kept up to date and the computer is running on AMD graphics. 

Changing display scaling to 100% makes the preview take up the whole area as if it is sitting behind the other GUI elements and the full screen preview starts to work

**Comment by Fenrirthviti** [comment] 2022-10-03 23:22
This typically only occurs with third-party display emulation/drivers, and given the target of your capture there being a VR screen mirror application, I would wager this is the cause of the problem. Can you confirm if this still occurs with the Oculus Mirror uninstalled? There is likely not much we can do, as those kinds of applications mess with how OBS is able to render its content.

**Comment by energizerfellow** [comment] 2022-10-03 23:26
Both your Intel and AMD GPU drivers need to be updated as well. See if there's a behavior change after updating these drivers.

**Comment by RytoEX** [comment] 2022-10-07 23:44
I'm going to close this, as this is almost certainly due to either GPU driver issues or Oculus Mirror, as @Fenrirthviti stated. Please try updating the Intel GPU drivers. The latest available Intel drivers are [31.0.101.2111](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html).

The AMD GPU is already using the latest AMD GPU driver package from Intel. Yes, Intel manages the driver packages for this particular GPU. See:
* https://ark.intel.com/content/www/us/en/ark/products/130409/intel-core-i78809g-processor-with-radeon-rx-vega-m-gh-graphics-8m-cache-up-to-4-20-ghz.html
* https://www.intel.com/content/www/us/en/download/19282/radeon-rx-vega-m-graphics.html

If the issue still occurs after updating GPU drivers and uninstalling Oculus Mirror, please let us know, and we can investigate further.

**Closed by RytoEX** 2022-10-07 23:44 UTC
