### ISSUE TITLE
bug: virtual camera only starts once after boot

### ISSUE THREAD

**Issue by veryspry** [obsproject/obs-studio#5787] opened 2022-01-13 05:48 UTC
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Rfk8KdJWcpf3fTE5

### Expected Behavior

Ability to start and stop the virtual camera as many times as you like.

### Current Behavior

Can only start and stop the virtual camera one time after booting the system. If you start the virtual camera and then stop it, the virtual camera will not start again on subsequent tries.

### Steps to Reproduce

1. Ensure that you haven't opened OBS since the last system reboot. If you have, reboot
2. Open OBS
3. Click the "start virtual camera" button (and enter your password in the sudo prompt)
4. Confirm that virtual camera starts
5. Click the "stop virtual camera" button
6. Click the "start virtual camera" button (the virtual camera should not start)

### Anything else we should know?

This gets written to the log file each time I try and start the virtual camera (with the exception of the first start when it starts like expected)

```
Failed to start virtual camera
```

After clicking to start the virtual camera the first time, I get a sudo prompt but do not get the sudo prompt on subsequent tries to start the camera. This makes me wonder if the obs needs to explicitly ask for sudo permissions every time the virtual camera is started.

**Comment by WizardCM** [comment] 2022-01-13 05:50
Duplicate of #4808

**Closed by WizardCM** 2022-01-13 05:50 UTC
