### ISSUE TITLE
Full/partial color range switch is broken when using custom output through FFmpeg

### ISSUE THREAD

**Issue by mia-is-baka** [obsproject/obs-studio#8199] opened 2023-02-03 10:39 UTC
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/BgY3fRZrYgONbSLt

### Expected Behavior

Full/partial color range switch is working properly with custom FFmpeg output

### Current Behavior

If you select full color range in advanced settings and try to record video through custom FFmpeg output, OBS marks output file as full range in metadata (you can see it with MediaInfo, for example), but actually encodes it always as partial range, so colors get washed out

### Steps to Reproduce

1. Launch OBS
2. Setup custom FFmpeg output (for example, mkv container with plain H.264 through libx264 or h264_nvenc)
3. Set color range to full
4. Record short video
5. Look at washed out result

### Anything else we should know?

It worked properly until release 28.x.x

#### Broken full range example

<details>
    <summary>OBS settings</summary>
    <img src="https://user-images.githubusercontent.com/109112234/216574642-5c904d38-23a0-4449-9b64-d13d610277db.png" alt=""/>
    <img src="https://user-images.githubusercontent.com/109112234/216574661-ad90c1c9-efbc-4249-a9fc-70204405715a.png" alt=""/>
    <img src="https://user-images.githubusercontent.com/109112234/216574674-9c4a664e-029e-4436-aea2-abcc33a73a8e.png" alt=""/>
</details>

<details>
    <summary>MediaInfo</summary>
    <img src="https://user-images.githubusercontent.com/109112234/216576115-1ea868d7-b895-4cbd-be62-a232a2067359.png" alt=""/>
</details>

<details>
    <summary>Reference image</summary>
    <img src="https://user-images.githubusercontent.com/109112234/216579504-0a452fa9-d45d-4120-9e54-792e304196bf.jpg" alt=""/>
</details>

<details>
    <summary>Frame from video (screenshot of clsid2/mpc-hc  with madVR)</summary>
    <img src="https://user-images.githubusercontent.com/109112234/216579657-d6646497-6d85-436c-98b3-e93680da75ae.jpg" alt=""/>
</details>

**Comment by mia-is-baka** [comment] 2023-02-03 14:07
I did a little research on the code and found that in video-io.c:video_output_connect video_scale_info field of input is not initialized properly

```c
-- snip --

    if (video_get_input_idx(video, callback, param) == DARRAY_INVALID) {
        struct video_input input;
        memset(&input, 0, sizeof(input));

        input.callback = callback;
        input.param = param;

        if (conversion) {
            input.conversion = *conversion;
        } else {
            input.conversion.format = video->info.format;
            input.conversion.width = video->info.width;
            input.conversion.height = video->info.height; <-- not initializing range and colorspace fields
        }

        if (input.conversion.width == 0)
            input.conversion.width = video->info.width;
        if (input.conversion.height == 0)
            input.conversion.height = video->info.height;

        success = video_input_init(&input, video);
        if (success) {
            if (video->inputs.num == 0) {
                if (!os_atomic_load_long(&video->gpu_refs)) {

-- snip --
```

I tried to initialize these fields like this:

```c
input.conversion.range = video->info.range;
input.conversion.colorspace = video->info.colorspace;
```

and it fixed full range output, but not RGB output (it's still metadata issue I guess)

**Comment by flaeri** [comment] 2023-02-03 22:43
I am a little bit confused about this report. In the title, and in several other places, you type "RGB color format", but in the settings and screenshots, you show i444/yuv444.

Additionally, full range seem to work fine (is full range, and tagged as such) for me with BGRA for me in custom ffmpeg output, both with cineform and utVideo. The issue posted as is makes it sound like its a core issue with custom ffmpeg output, but that has not been my experience with these other codecs.

If I set i444 color format, full range color, and the libx264, I can reproduce the color range mismatch you're describing. I still think its important that the issues be as specific as possible.

Is this issue multiple issue? If yes, I personally think they should be split into seperate issue, and each have their own reproduction steps.

**Comment by mia-is-baka** [comment] 2023-02-04 05:20
> I am a little bit confused about this report. In the title, and in several other places, you type "RGB color format", but in the settings and screenshots, you show i444/yuv444.

Oh, sorry. I originally wanted to report only color range issue, but then I decided that this problems may be caused by the same thing and mentioned problem with RGB output too

> Additionally, full range seem to work fine (is full range, and tagged as such) for me with BGRA for me in custom ffmpeg output, both with cineform and utVideo. The issue posted as is makes it sound like its a core issue with custom ffmpeg output, but that has not been my experience with these other codecs.

Oh, interesting. In code both problems look like a core issue:

In `libobs/media-io/video-io.c` color conversion output isn't configured properly, so wrong color range used even before encoding and full range must be broken with any codec and encoder

 in `plugins/obs-ffmpeg/obs-ffmpeg-output.c` `config.colorspace` is set like its YUV/YCbCr even if actually RGB color space is used, so encoders that rely on this must not encode RGB properly too. Maybe cineform and utVideo just ignores this and always assumes that input is RGB?

> If I set i444 color format, full range color, and the libx264, I can reproduce the color range mismatch you're describing. I still think its important that the issues be as specific as possible.
> 
> Is this issue multiple issue? If yes, I personally think they should be split into seperate issue, and each have their own reproduction steps.

Oh, it's a multiple issue I guess. I agree with you, how can I split it?

**Comment by flaeri** [comment] 2023-02-04 08:21
You may be right. RGB formats in partial do not make much sense, so it plausible that certain codecs are implied to be full range, even if its not said explicitly.

I think I would keep this issue for the yuv/i444 problems, since it seems the most data and information is regarding that.
Then I'd move all mentions/issues/information regarding RGB over to a new issue.

I saw your PR, and while it may fix both scenarios, I still think you'll have more luck getting it merged when you have clear and concise information, and since it is two seperate problems, I think its better to split them, so that seperate information, repro steps etc can easily be viewed.

I'll test your PR later today, thank you 👍

**Comment by mia-is-baka** [comment] 2023-02-04 09:39
> I think I would keep this issue for the yuv/i444 problems, since it seems the most data and information is regarding that. Then I'd move all mentions/issues/information regarding RGB over to a new issue.

Thanks! I separated RGB issue as #8209

**Comment by TheDude53** [comment] 2023-02-11 04:25
Also having this issue. Using the NV12 format with sRGB space and full range still produces a partial range output (16-235). Interestingly, this only seems to occur (for me at least) with libx264; other encoders such as libvpx-vp9 work fine.

**Comment by JonasCz** [comment] 2023-02-28 10:58
I can also confirm this (I think), to reproduce:

1. Drag the following PNG file onto OBS to add it as an image source:
![1920x1080_color_range_test_chart](https://user-images.githubusercontent.com/10514959/221823899-f95dc172-0d4e-4543-85c1-5ff12ff56a99.png)

2. Advanced -> Colour Format: I444, Colour Space: 709, Range: Full
3. Output: Advanced, Recording: custom FFMPEG, Container: matroska, Encoder: ffv1.
4. All other settings per OP (defaults)
5. Record video.
6. 
Looking at resulting video in a player / editor / Histogram tool, it's not full range:

For example `ffplay "test.mkv" -vf "histogram"`, (with correct full range video it should extend all the way to the left and right): 

![Screenshot (15)](https://user-images.githubusercontent.com/10514959/221833315-6d194b4d-8181-4c0e-94d7-4ad03bc1056d.png)

As a result in other tools and players (e.g. VirtualDub2, or MPC-HC as per OP), it's washed out. 

VLC seems to be OK and not washed out, perhaps because of this VLC bug: [Full/Limited Video Levels incorrectly displayed](https://code.videolan.org/videolan/vlc/-/issues/25118).

OBS 28.1.2 also has this problem for me, unlike OP.

In the real world: I have a capture card which can output full range, OBS set to full range everywhere seems to scale to 16-235 and flag the file as full range anyway.

**Closed** 2023-03-03 21:49 UTC
