### ISSUE TITLE
Faild to load Video Capture Device Options

### ISSUE THREAD

**Issue by Radium-bit** [obsproject/obs-studio#8425] opened 2023-03-08 10:17 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Z1seANCflOPw1hk1

### OBS Studio Crash Log URL

https://obsproject.com/logs/Z1seANCflOPw1hk1

### Expected Behavior

OBS Studio cannot add a video capture device. And it will clash

### Current Behavior

When I try to add a video capture device it crashes.

### Steps to Reproduce

1. Launch OBS Studio
2. Add Vedio Capture Devices.
3. It clash.
...

### Anything else we should know?

This behavior will definitely happen, the recurrence rate is 100%
Other than that, I have completely uninstalled and reinstalled OBS Studio

**Comment by Radium-bit** [comment] 2023-03-09 13:08
> Sounds like a duplicate of #7812 (3rd party software interference). Do you have any vtuber / unity-based virtual camera installed?

Yes, I confirmed that the problem is in UnityCapture. I need to use it for my work, can you tell me the solution? If there is a newer compatible version, thank you.

**Comment by notr1ch** [comment] 2023-03-09 14:03
If you're the author of a unity-capture based virtual camera, be aware that we will be blocking all filters called `unitycapturefilter64bit.dll` in a future release. To prevent your filter being blocked, make sure it has a different name. If it is already named something else, please share the name so we can block the old versions that don't have the deadlock fix.

**Comment by RytoEX** [comment] 2023-03-09 19:13
As @notr1ch wrote, this is a duplicate of #7812. If you are building software that uses the Unity Capture virtual camera, please rename the DLL file that you use and let us know the new DLL name so that we do not block it in future releases of OBS.

**Comment by RytoEX** [comment] 2023-03-09 19:13
Duplicate of #7812

**Closed by RytoEX** 2023-03-09 19:13 UTC
