### ISSUE TITLE
[BUG] In-app updater does not increase program version in Add or Remove Programs

### ISSUE THREAD

**Issue by GenericMadScientist** [obsproject/obs-studio#2897] opened 2020-05-09 16:57 UTC
## Platform
Operating system and version: Windows 10 Version 1909
OBS Studio version: 25.0.4 / 25.0.8 (see bug)

## Expected Behavior
When updating OBS Studio from 25.0.4 to 25.0.8 with the in-app updater, the program version in Add or Remove Programs should increase from 25.0.4 to 25.0.8.

## Current Behavior
The program version stays at 25.0.4 in Add or Remove Programs even after OBS Studio is updated.

## Steps to Reproduce
Video: https://www.youtube.com/watch?v=24dgldK0
Note the video is concerned with PatchMyPC, but after these steps the program version in Add or Remove Programs is unchanged.
1. Have no version of OBS Studio installed on the computer, aside from potentially OBS Classic (I have reproduced this bug with and without OBS Classic installed).
2. Install version 25.0.4 of OBS Studio.
3. Open OBS Studio and update when given the option.

## Additional information
I recall seeing this bug before, I think when I updated from 25.0.1 to 25.0.4. I had to uninstall and reinstall OBS Studio fully to get the correct version number.

**Comment by RytoEX** [comment] 2020-05-10 04:47
I can verify that this does occur when using the updater.
![image](https://user-images.githubusercontent.com/624931/81491077-beda2980-9257-11ea-8c98-691562895167.png)

**Comment by WizardCM** [comment] 2020-05-10 04:49
I can confirm the same. I'm not sure if it's a registry thing, or purely because the OBS Updater doesn't touch the `uninstall.exe` file.

**Comment by RytoEX** [comment] 2020-05-10 05:50
I can confirm that we can update a registry key or two (or three) to get "Programs and Features" or "Apps and Features" to show the correct version number.  Not sure if replacing the `uninstall.exe` would also work.

**Comment by skeletonbow** [comment] 2020-05-10 11:33
I noticed this a couple weeks ago as well and meant to report it, so I can confirm also.

**Comment by RytoEX** [comment] 2020-05-10 11:55
I think I've worked out how to address this.  Will be experimenting and looking at this further.

**Comment by asjimene** [comment] 2020-08-25 20:13
This could be fixed by updating the DisplayVersion property in the registry under: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\OBS Studio. That reg value is what is populated in Add/Remove Programs

**Comment by RytoEX** [comment] 2020-08-25 20:36
It's a bit more nuanced than that, but yes, that's the general idea.  I just hadn't circled back around to it because I had other commitments.

**Comment by asjimene** [comment] 2020-08-25 20:40
No worries, thank you for the quick response. I looked a little bit to see if I could help in any way, but quickly realized this was way out of my element 😅

**Comment by alexwhitman** [comment] 2022-09-07 11:22
I've just noticed that this is a slightly more visible issue if using winget. At the time of writing, I have 28.0.1 installed by the built in updater (from 28.0.0) but winget belives there is an update available:
![image](https://user-images.githubusercontent.com/422013/188865146-d919d62e-35d9-4f03-97c1-1df01db9b44a.png)

**Comment by aisgbnok** [comment] 2023-05-03 02:35
This is still an issue as of `29.1.0`. I updated from `29.0.2` to `29.1.0`, but the version has not updated in Windows. This is somewhat annoying when using [`winget`](https://github.com/microsoft/winget-cli).

![Windows Settings listing OBS 29.0.2 but OBS about page listing 29.1.0 installed.](https://user-images.githubusercontent.com/10838153/235822924-bc32d6da-8fec-4b4c-842b-03bb7047e281.png)

**Closed** 2023-07-22 23:33 UTC
Labels: Windows, Confirmed
