### ISSUE TITLE
Image source: Automatic update fails without recovery when file is locked during read attempt

### ISSUE THREAD

**Issue by YorVeX** [obsproject/obs-studio#3275] opened 2020-08-12 18:50 UTC
## Platform

Operating system and version: Windows 10 Pro x64 Build 1909
OBS Studio version: 25.0.8

## Expected Behavior
When an image is shown by an image source and the underlying image file is updated it should always trigger a refresh of the image. Should the image file be locked and unreadable the second OBS tries to access it, then OBS should remember that this file changed and retry and update it e.g. one second later.

It should never be possible to create a situation where the actual image file and the image shown by the image source in OBS differ from each other.

## Current Behavior
When an image is still being written and therefore locked while OBS already tries to access the file then the image shown in OBS is not updated, not even after writing the file finished and the file lock disappeared. It seems that when OBS fails to read the file it still internally marks the file as updated, instead of leaving it marked as not updated and trying again later.

## Steps to Reproduce
1. Create a scene with an image source that is based on a file.
2. Keep on overwriting the image file, in best case with a program (e.g. an image editing software) that takes some time to write the image file (a direct copy might be too fast to reproduce this).
3. At some point the file shown in OBS will not match the contents of the file - this happens when OBS tries to access the file during the exact time when it is still written.
4. Wait for a while: even after many seconds the image source will not update.
5. Now change the file again - unless a lock situation occurs again the image source will now again be updated by OBS from the file.

**Comment by WizardCM** [comment] 2020-08-13 04:14
This is caused by the same issue as #3011 - I vote closing this in favour of the other, with a note that this affects any source that reads a file.

**Comment by YorVeX** [comment] 2020-08-15 12:19
Fine by me. I just hope it can be fixed. In the meantime I will try whether it helps to write to a separate file name first and then exchange old and new files by renaming them as a workaround.

**Comment by YorVeX** [comment] 2020-08-15 13:03
Nevermind, this workaround doesn't help, it still happens ;-(

So that this means one cannot even avoid this problem with control over the program/code that writes the file (which is not the case for everyone anyway). It must really be fixed on OBS side.

**Comment by RytoEX** [comment] 2022-10-05 20:05
Duplicate of #3011

**Closed by RytoEX** 2022-10-05 20:05 UTC
Labels: Confirmed
