### ISSUE TITLE
[BUG] Linux: Browser doesn't accept certain keystrokes

### ISSUE THREAD

**Issue by christianhujer** [obsproject/obs-studio#2614] opened 2020-04-02 06:46 UTC
## Platform

Operating system and version: Kubuntu 18.04.04 LTS
Details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ uname -a
Linux Nelkinda-Blade-Stealth-2 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

OBS Studio version: 25.0.3 (linux)
Installed via: Ubuntu installation instructions
```
$ cat /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-bionic.list
deb http://ppa.launchpad.net/obsproject/obs-studio/ubuntu bionic main
# deb-src http://ppa.launchpad.net/obsproject/obs-studio/ubuntu bionic main
```

## Expected Behavior
When using "Interact" to interact with the browser, the interaction works like with a real browser, that is, all keystrokes are accepted, including keystrokes like `.` or `F5`.

## Current Behavior
When using "Interact" to interact with the browser, the interaction is limited. I could not enter `.` to enter an email address for logging into a G Suite account, I could not press Backspace to delete a mistyped character, I could not press F5 to reload the page, and I could not press Ctrl+Shift+F5 to start a Google Slides presentation.

## Steps to Reproduce
Live example: https://youtu.be/U2f35JMrFJ8

1. Create a scene.
2. Add a Browser to the scene.
3. Configure the browser to display a page that requires input, like https://google.com/
4. Interact with the Browser
5. Enter something into the page, and then try to delete it (backspace), move the cursor, enter periods, or reload the page (F5). You will notice that this doesn't work properly.

## Additional information
In case this is relevant:
Desktop: KDE Plasma

## Workaround
Use a fullscreen browser on another screen and use a screen source instead. (Only works well for people with multiple screens.)

**Comment by WizardCM** [comment] 2020-04-02 06:49
This is a duplicate of https://github.com/obsproject/obs-browser/issues/200 so I'm closing this issue in favour of that one.

As a note - the browser source is not designed to be used as a web browser directly, but to create overlays using web technologies.

**Closed by WizardCM** 2020-04-02 06:49 UTC
