### ISSUE TITLE
Linear 16-bit PNGs too dark as of 27.0.1

### ISSUE THREAD

**Issue by Techjar** [obsproject/obs-studio#4890] opened 2021-06-13 07:19 UTC
### Operating System Info

Other

### Other OS

Linux, but should affect all platforms

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FMfjIOqzH6PCxtrz (ignore the -modified, git is just being weird with submodules)

### Expected Behavior

I have several 16-bit PNGs that are exported in linear space, with an embedded ICC profile explicitly making them linear sRGB (gamma 1.0) instead of the usual non-linear sRGB (gamma 2.2). OBS should read this color profile and interpret it properly. I guess that makes this also somewhat of a feature request.

### Current Behavior

OBS assumes the images are non-linear, and as a result they appear way too dark. I confirmed this is caused by #4788. I *could* re-export the images in non-linear space, but this is tedious and shouldn't be necessary.

### Steps to Reproduce

1. Add this image to a scene: https://qimg.techjargaming.com/i/OCUHq8AU.png

Note how most web browsers will read the ICC profile and display it properly.

### Anything else we should know?

There was a lot of discussion in the Discord server around this 16-bit PNG functionality, in the now-deleted beta testing channel.

**Comment by RytoEX** [comment] 2021-06-14 03:30
OBS doesn't support ICC profiles and I'm not aware of plans to add it any time soon.

> I guess that makes this also somewhat of a feature request.

I would agree with this conclusion, so I'm closing this as "by design / not a bug" or "working as intended".  Feature requests should be submitted at https://ideas.obsproject.com/.

**Closed by RytoEX** 2021-06-14 03:30 UTC

**Comment by Techjar** [comment] 2021-06-16 23:36
Well then in the meantime can an option be added to restore the previous behavior of treating the RGB as linear in addition to the alpha? ICC profile support was more of a bonus; the issue of OBS displaying my linear PNGs wrong is still at hand.
