### ISSUE TITLE
PipeWire Invalid memory type

### ISSUE THREAD

**Issue by nicokimmel** [obsproject/obs-studio#6302] opened 2022-04-09 16:18 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

Flatpak 

### OBS Studio Log URL

https://obsproject.com/logs/QcbFZScdcxRts6pr

### Expected Behavior

Expected to capture windows like in Gnome 41.

### Current Behavior

Happens since the update to Gnome-Shell 42.
When I select PipeWire as a capture source and then select the window to record the preview is just gray. I dont see a mouse cursor.

https://media.discordapp.net/attachments/483318095985770517/962150875231576184/unknown.png
https://media.discordapp.net/attachments/483318095985770517/962151215230246954/unknown.png
(Those are screenshots from Isaac, in the log I tested The Elder Scrolls Online. But I think that does not make a difference.)

It does happen to any window, no specific ones.

The journal reports:
`pipewire[6459]: invalid memory type 8`
`gnome-shell[6082]: Invalid buffer data`

I tried with a fresh installation and I installed `xdg-desktop-portal` and `xdg-desktop-portal-gnome`.

### Steps to Reproduce

1. Open OBS
2. Add a new Element and select PipeWire
3. Select a window
4. See a empty gray preview
5. Press OK and see a empty window capture
...

### Anything else we should know?
It is working for Discord and Chromium.

**Comment by columbarius** [comment] 2022-04-09 16:29
Please paste the output of https://gist.github.com/columbarius/50239ea3c4c70df8f240aa50f88e801a

**Comment by nicokimmel** [comment] 2022-04-09 16:33
![grafik](https://user-images.githubusercontent.com/31391271/162582944-7dc14f19-6c14-4335-a7e0-d2ea802e4cb6.png)
My language is set to German. Output should be something like `Computer is not active`.

**Comment by columbarius** [comment] 2022-04-09 16:36
ok, you should not need root... can you please upload just the output of `pw-dump > pw-dump.json`?

**Comment by nicokimmel** [comment] 2022-04-09 16:50
https://pastebin.com/Y6hyxpzB

**Comment by columbarius** [comment] 2022-04-10 14:55
Looks like the issue is gnome failing to create a buffer. Maybe some assumptions don't hold true on nvidias gbm backend.

**Comment by nicokimmel** [comment] 2022-04-10 16:24
It does work for Discord (Chromium in general) and Firefox.

**Comment by columbarius** [comment] 2022-04-10 16:34
Interesting.. Can you please provide a pw-dump for firefox and chromium on wayland?
You don't have more than one gpu?

**Comment by Gavintime** [comment] 2022-04-10 18:53
Hi, I believe I'm having the same issue as OP. 

My setup: Arch Linux, Gnome 42, Wayland, pipewire.
Screen capture worked fine with Gnome 41 and pipewire.

obs-studio 27.2.3-1 from arch repos (I also tried with the flatpak release, no difference)
I have a dual monitor setup. Just mentioning this because I've had Wayland multi monitor specific issues in the past. 

After selecting window capture (pipewire) and selecting a window, it only shows a black screen. Pipewire also reports "invalid memory type 8" every time I create a window capture. The same issue happens with screen capture.

nicokimmel mentioned that Discord/Chromium window capture works, however they use webrtc by default. I suspect this is some upstream issue with gnome, but just in case it's not here's my logs.

obs log
https://obsproject.com/logs/c9GH1NMtr9UZk0tv

Below are the outputs of the debug script for each respective case.

obs with screen capture (pipewire)
https://pastebin.com/GmttitM4

obs with window capture (pipewire), for this example I tried capturing gnome-terminal.
https://pastebin.com/2R93wx2g

**Comment by columbarius** [comment] 2022-04-10 23:49
If you are using flatpak, can you please download the buildartefact from https://github.com/obsproject/obs-studio/pull/6313 and test if sth. changed? (Detail->Summary->below the diagram)

**Comment by nicokimmel** [comment] 2022-04-11 00:40
> If you are using flatpak, can you please download the buildartefact from #6313 and test if sth. changed? (Detail->Summary->below the diagram)

This did not help, sadly. Same issue.

**Comment by nicokimmel** [comment] 2022-04-18 00:27
I found some more errors. Not sure if this is a OBS issue or a xdg-desktop-portal issue.

`org.gnome.Software.desktop[226158]: info: User added source 'asdfg' (pipewire-window-capture-source) to scene 'Szene'`
`org.gnome.Software.desktop[226158]: info: [pipewire] screencast session created`
`org.gnome.Software.desktop[226158]: info: [pipewire] asking for window…`
`xdg-desktop-por[1221]: Unhandled parent window type `
`xdg-desktop-por[1221]: Failed to associate portal window with parent window `
`org.gnome.Software.desktop[226158]: info: [pipewire] window selected, setting up screencast`
`wireplumber[1286]: <WpPortalPermissionStorePlugin:0x55b8a6a19ce0> Failed to call Lookup: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for camera`
`org.gnome.Software.desktop[226158]: info: [pipewire] server version: 0.3.50`
`org.gnome.Software.desktop[226158]: info: [pipewire] library version: 0.3.40`
`org.gnome.Software.desktop[226158]: info: [pipewire] header version: 0.3.40`
`org.gnome.Software.desktop[226158]: info: [pipewire] created stream 0x560a17a83810`
`org.gnome.Software.desktop[226158]: info: [pipewire] playing stream…`
`gnome-shell[900]: No supported PipeWire stream buffer data type could be negotiated`
`gnome-shell[900]: No supported PipeWire stream buffer data type could be negotiated`
[...]
`gnome-shell[900]: No supported PipeWire stream buffer data type could be negotiated`
`gnome-shell[900]: No supported PipeWire stream buffer data type could be negotiated`
`gnome-shell[900]: pipewire remote error: id:0 connection error`

**Comment by lolsniperftw** [comment] 2022-04-27 07:03
This is an issue with the Nvidia driver and will be fixed in Gnome 42.1

https://gitlab.gnome.org/GNOME/mutter/-/issues/2155#note_1437148

**Comment by RytoEX** [comment] 2022-04-27 16:36
@GeorgesStavracas @kkartaltepe Given the above, is there anything remaining for us to do here? Should this be closed?

**Comment by GeorgesStavracas** [comment] 2022-04-27 16:43
Not an OBS issue, nothing to be done here, and was already fixed in the relevant place.

Closing.

**Closed by GeorgesStavracas** 2022-04-27 16:43 UTC

**Comment by nicokimmel** [comment] 2022-04-29 10:06
Can confirmed it's fixed.
Tested with mutter-git from AUR. 👍
