### ISSUE TITLE
[BUG] OBS on HiDPI displays on W10 is barely usable everything is tiny

### ISSUE THREAD

**Issue by jsoref** [obsproject/obs-studio#2634] opened 2020-04-03 22:08 UTC
## Platform

Operating system and version: Windows 10 x64- 2004 (19592.1001)
OBS Studio version: 25.0.1

## Expected Behavior
Fonts should be readable

## Current Behavior
Some portions of text/widgets are incredibly tiny. But not everything.

## Steps to Reproduce
1. Laptop is a Dell w/ high dpi, text size is 250% (display settings), display res is 3200x1800 (recommended)
2. Download the OBS 25.0.1 installer on Windows 10
3. Use defaults and walk through to the wizard.

![image](https://user-images.githubusercontent.com/2119212/78408534-720a8f80-75d5-11ea-863a-1aa930eebc67.png)
![image](https://user-images.githubusercontent.com/2119212/78408553-7b93f780-75d5-11ea-859f-cf4f3056f326.png)
![image](https://user-images.githubusercontent.com/2119212/78408582-8fd7f480-75d5-11ea-9e3a-02fd355cfaf2.png)
![image](https://user-images.githubusercontent.com/2119212/78408647-b007b380-75d5-11ea-977b-8eb2182a932e.png)
![image](https://user-images.githubusercontent.com/2119212/78408683-c1e95680-75d5-11ea-9e71-4fd3a988e96b.png)

![image](https://user-images.githubusercontent.com/2119212/78408322-ceb97a80-75d4-11ea-8b9a-cfb7705e3b5b.png)
![image](https://user-images.githubusercontent.com/2119212/78408402-06282700-75d5-11ea-93c5-ab3bfec097d1.png)
![image](https://user-images.githubusercontent.com/2119212/78408520-661ecd80-75d5-11ea-96f5-b4c82450d059.png)

**Comment by WizardCM** [comment] 2020-04-04 00:20
This is a known limitation of the Qt version we're using (our UI library). For the moment, this is our recommendation:

> Due to issues with how Qt handles high-DPI display scaling, you may encounter some oddities in the OBS Studio UI when using DPI scaling. As a workaround, you can disabled DPI scaling for OBS:
> 
> 1. Close OBS Studio.
> 2. Find your OBS Studio shortcut, either on your desktop or in your start menu (Right click -> Open file location).
> 3. Right click on it and select "Properties".
> 4. Go to the "Compatibility tab".
> 5. Click "Change high DPI settings".
> 6. Tick "Override high DPI scaling behavior".
> 7. In the dropdown, change it to "System (Enhanced)".
> 8. Click OK to exit out of the scaling settings.
> 9. Click OK to save the new properties.
> 10. Launch OBS Studio as you normally would.

It'll be fixed when we're able to bump our Qt version to 5.14 or above (we're currently on 5.10)

**Comment by dodgepong** [comment] 2020-04-04 00:30
Gonna keep this open until we actually update to Qt 5.14.

**Comment by jbzdarkid** [comment] 2020-04-19 21:32
I tried this, but every time I relaunch OBS the setting gets ignored.
Here's the steps I'm taking, with the registry values between each launch.
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`

1. Reset the regkey.
1. `C:\Progam Files (x86)\obs-studio\bin\64bit\obs64.exe = ""`
1. Go to OBS -> Properties -> Compatibility -> Change high DPI settings -> System (Enhanced)
1. `C:\Progam Files (x86)\obs-studio\bin\64bit\obs64.exe = "~ GDIDPISCALING DPIUNAWARE"`
1. Launch OBS
1. Everything is working fine, no High DPI issues.
1. Reg key has been changed, however:
1. `C:\Progam Files (x86)\obs-studio\bin\64bit\obs64.exe = "~ GDIDPISCALING DPIUNAWARE HIGHDPIAWARE"`
1. Close and re-open OBS, and issues appear again.

I don't see anything obvious in the source that would be doing this, so maybe this is to do with the way OBS registers its manifest?

**Comment by Heufneutje** [comment] 2020-04-20 06:55
That workaround usually works fine for me. Sometimes updates reset it but relaunches certainly don't for me.

**Comment by jbzdarkid** [comment] 2020-04-20 17:25
@Heufneutje Can you check to see if your registry settings are being changed in the same way?

**Comment by Heufneutje** [comment] 2020-04-21 06:52
I cannot reproduce step 7/8. The registry key does not change for me.

**Comment by Syping** [comment] 2020-05-21 12:05
Qt 5.6 supports already High DPI scaling with the Qt Application attribute Qt::AA_EnableHighDpiScaling: [See there](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt)
I used to set the environment value QT_AUTO_SCREEN_SCALE_FACTOR to 1 and did not had problems using OBS with it, so from my experience it should be possible to do in Qt 5.10 too.
But could agree on first enabling it in Qt 5.14 as the Support is improved further, but Qt 5.6+ have enough support for most cases, so i would see no problem in enabling it for Qt 5.10 by default without the environment value.

Not scaled
![Not scaled image](https://i.imgur.com/WrhFuKw.png)

Scaled
![Scaled image](https://i.imgur.com/Fom3dXK.png)

**Temporary workaround** would be like that.
`set QT_AUTO_SCREEN_SCALE_FACTOR=1`
`"C:\Program Files\obs-studio\bin\64bit\obs64.exe"`

**Comment by RytoEX** [comment] 2020-05-21 13:13
@Syping We're aware of that flag.  See #1602 for some history on why we only enable it for Qt 5.11+.

**Comment by jbzdarkid** [comment] 2020-05-24 06:44
I started Process Monitor, and as far as it was concerned, no application was modifying this key.
So, I wrote a small batch script to reset the key and launch OBS, then pointed my shortcut at it:
```batch
REG ADD "HKCU\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe" /t REG_SZ /d "~ GDIDPISCALING DPIUNAWARE" /f
start "" "obs64.exe"
```

**Comment by Dunnymeister** [comment] 2020-09-17 15:51
I was sick of the squished UI on my high DPI screen and stumbled across this while searching for how to fix it. I tried the suggested work around in the latest RC2 and the dockable windows don't behave correctly at all.

![Example 1](https://puu.sh/GtE7E/cb3452bf44.png), ![Example 2](https://puu.sh/GtE7c/fc50c0d002.png)

**Comment by SimplexPL** [comment] 2020-10-10 10:31
> > Due to issues with how Qt handles high-DPI display scaling, you may encounter some oddities in the OBS Studio UI when using DPI scaling. As a workaround, you can disabled DPI scaling for OBS:

Hi,

When I disable DPI scaling for OBS it's impossible to add Windows Capture - the captured windows is zoomed in, only 1/4 of the windows is visible (on a 4K display).

**Comment by clankill3r** [comment] 2020-11-27 20:36
When I change dpi scaling to "System (Enhanced)" Only 1/4th of the windows I capture are shown:

![windows_I_hate_you](https://user-images.githubusercontent.com/738650/100482888-7d787100-30f8-11eb-8bc0-254749578d06.png)

**Comment by WizardCM** [comment] 2020-12-09 09:46
Heads up - we bumped the Qt version in OBS 26.1.0 - please verify in either rc2 or the final release, depending on when you check. Closing this issue as it should now be fixed.

**Closed by WizardCM** 2020-12-09 09:46 UTC
Labels: Confirmed, Dependency Issue, Windows

**Comment by javajon** [comment] 2020-12-09 19:43
Verified fixed in 26.1.0-rc2 (64 bit)

**Comment by Lordmau5** [comment] 2020-12-15 18:44
Updating from 26.0 to 26.1 and I'm having issue with it again (both with and without the DPI properties setting that was suggested as a fix)

<details>
<summary>OBS on my 1080p monitor (default scaling, 100%)</summary>

OBS 26.0.2:

![image](https://user-images.githubusercontent.com/1345036/102258029-c0668100-3f0d-11eb-9a26-dfad5a75c131.png)


OBS 26.1 (Default):

![image](https://user-images.githubusercontent.com/1345036/102257201-bdb75c00-3f0c-11eb-8d11-2188b54d7af4.png)
</details>

<details>
<summary>OBS on my 4K monitor (150% scaling)</summary>

OBS 26.0.2:

![image](https://user-images.githubusercontent.com/1345036/102257820-84cbb700-3f0d-11eb-94b8-8e7df3e6b23b.png)

OBS 26.1 (Default):

![image](https://user-images.githubusercontent.com/1345036/102257310-dcb5ee00-3f0c-11eb-89a1-29e2aa0b17a8.png)

OBS 26.1 (High DPI Override - System (Enhanced)):

![image](https://user-images.githubusercontent.com/1345036/102257475-138c0400-3f0d-11eb-84ca-c0ca91e623d0.png)
</details>

I'd really love if there'd still be a way to revert to what it looked like in 26.0.2 on my 4K monitor.
Perhaps a setting to get back these "old" DPI settings?

**Comment by Fenrirthviti** [comment] 2020-12-15 19:17
It's unfortunately not that simple. Most of the issues here in with how Qt handles the scaling, which is something we don't have a whole lot of control over, save rewriting the entire UI to have explicit support for fractional DPI scaling. Updating to Qt 5.15.2 fixed a host of other UI and Qt bugs, and in some cases makes the DPI scaling function better. Some cases, it functions worse. I don't think there is an ideal solution here that will make everyone happy, unfortunately.

**Comment by Lordmau5** [comment] 2020-12-15 20:04
I'm gonna look a bit more in-depth into this later today.
I *think* the "Default (Dark)" theme actually looked closer to what it should look like on my 4K monitor with 150% scaling.
Maybe it's something within the themeing engine, or in this case Acri specifically, that needs to be fixed for this?

Alternative thought that crossed my mind - is there perhaps some calculation going on in combination with all monitors the user has? In my case 3 monitors - 2 of which are 1080p at 100% scaling and my 4K monitor at 150% scaling.

**Comment by Lordmau5** [comment] 2020-12-15 21:28
Alright so I installed 26.1 again and noticed one major thing:
- The icons are abnormally large
- The audio bars are taller / bigger than before
- The header text is way too large (Acri-specific)

To me it seems like Acri has some special spacing / sizing code that none of the other themes have...
I wonder if, when adjusted to the new DPI adjustments that came with 26.1, this could be fixed...?

<details>
<summary>Default (Dark)</summary>

![image](https://user-images.githubusercontent.com/1345036/102274364-0dede880-3f24-11eb-8353-b75e06c3b3b5.png)
</details>

<details>
<summary>Acri (even larger than before)</summary>

![image](https://user-images.githubusercontent.com/1345036/102274558-602f0980-3f24-11eb-83ca-4debd4d108c7.png)
</details>

<details>
<summary>Rachni (seems to have smaller icons...?)</summary>

![image](https://user-images.githubusercontent.com/1345036/102274613-73da7000-3f24-11eb-87ef-1756f56a0349.png)
</details>

<details>
<summary>System (also ow my eyes)</summary>

![image](https://user-images.githubusercontent.com/1345036/102274652-85bc1300-3f24-11eb-845b-24bef3f2754e.png)
</details>

All these screenshots were taken with OBS on my 4K monitor.
However, it's also this big on one of my 1080p monitors.

**Comment by digitalentropy** [comment] 2020-12-17 17:42
Yes, the changes in 26.1 actually have caused major display problems for me as well.

My setup involves a HiDPI laptop as the primary display with a standard DPI external display (where OBS is normally run) and anytime OBS is in the external monitor the menu's and icons are almost unusable. My workaround has been to override application scaling by using Windows 10's compatibility settings.
