### ISSUE TITLE
[Flatpak] Runtime org.kde.Platform branch 6.4 is end-of-life

### ISSUE THREAD

**Issue by rabin-io** [obsproject/obs-studio#9725] opened 2023-10-17 17:34 UTC
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

30.0.0-rc1

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/t71awhkcONjXZl1o

### Expected Behavior

Not to show any warning on flatpak update.

### Current Behavior

```
Looking for updates…

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   com.obsproject.Studio

```

### Steps to Reproduce

1. flatpak update
2.
3.
...

**Comment by tytan652** [comment] 2023-10-17 17:34
Duplicate of #9542

**Closed** 2023-10-17 17:34 UTC
