### ISSUE TITLE
Decklink input not working correctly in 26.1

### ISSUE THREAD

**Issue by BlackScreen** [obsproject/obs-studio#3897] opened 2020-12-15 17:33 UTC
## Platform
Operating system and version: Windows 10, 2004
OBS Studio version: 26.1

## Expected Behavior
Input of Decklink card should be captured correctly.

## Current Behavior
Decklink video is only completely green, does not work correctly. When closing it crashes.
I went back to 26.0.2 where it works problem free.

## Steps to Reproduce
1. Open OBS
2. Insert Decklink source

I should add, thank you for this awesome piece of software! :)

**Comment by Fenrirthviti** [comment] 2020-12-15 17:38
Duplicate of #3872

**Closed by Fenrirthviti** 2020-12-15 17:38 UTC
