### ISSUE TITLE
Media source stops playing video-file after a combination of showing/hiding the source, switching scenes and using source transition.

### ISSUE THREAD

**Issue by itroy187** [obsproject/obs-studio#6397] opened 2022-04-30 03:57 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/1annEf3Eq31NAsWu

### Expected Behavior

The media source to play the video file even after
- Toggling hide/show multiple times
- Switching scenes multiple times
- Using a source transition on the media source

### Current Behavior

A few weeks ago, I stumbled across an odd behavior in OBS, in which after streaming for some hours, seemingly out of nowhere some of my media sources stopped working. I have a fairly large scene collection and a ton of things going on, an therefore the search for the culprit wasn't easy.. But I think I was able to narrow it down to a combination of the following
- Showing/hiding a media source 
- Source transition
- Switching between scenes which have a nested scene containing the media source

https://user-images.githubusercontent.com/6821126/166089411-b9c88436-04ef-4b68-a85f-29cf9d8ea07d.mp4

### Steps to Reproduce

1. Make a new scene with a media source in it, choose a video (for easier testing make sure it's only a few seconds long) for the source. Leave settings at default.
2. Right click on the media source and activate "show transition" and "hide transition" (e.g. "slide")
3. Make two new scenes and add the previously created scene as a source in each of them
4. For easier testing I used hotkeys to hide/show the media source and for switching between the two scenes from step 3 (I used the keys 1,2,3 and 4)
5. Now quickly and continuously switch between the scenes created in step 3 while also quickly and continuously switching between hiding and showing the media source created in step 1. Just randomly spam the 4 hotkeys for about 5 seconds (or longer).
6. Make sure to let the media source play to the end (if it even shows up at this point)
-> Media source doesn't play anymore in any of the scenes until OBS is restarted

[scene-collection-media-source-bug.zip](https://github.com/obsproject/obs-studio/files/8595613/scene-collection-media-source-bug.zip)

### Anything else we should know?

I attached my scene collection which I used for testing in the video.

My workaround solution for the time being: I removed all source transitions.

**Comment by Fenrirthviti** [comment] 2022-04-30 21:21
Duplicate of #5291

**Closed by Fenrirthviti** 2022-04-30 21:21 UTC
