### ISSUE TITLE
OBS Mac Browser click position all wrong

### ISSUE THREAD

**Issue by Nyceane** [obsproject/obs-studio#3212] opened 2020-07-25 09:25 UTC
## Platform
Operating system and version: Mac OS X Mojave 10.14.6
OBS Studio version: 25.0.8

## Expected Behavior
Browser Source interact would click like normal web page

## Current Behavior
When right click "interact" on browser source, you'd see entire mouse is clicking in wrong spots.

## Steps to Reproduce
1. Open OBS
2. Add a Browser
3. enter "https://www.kirupa.com/snippets/examples/move_to_click_position.htm"
4. (optional) remove Custom css
5. Right click on Browser -> Interact
6. the positions are just wrong

## Additional information
Log as below

02:22:13.846: CPU Name: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
02:22:13.846: CPU Speed: 2900MHz
02:22:13.846: Physical Cores: 4, Logical Cores: 8
02:22:13.846: Physical Memory: 16384MB Total
02:22:13.846: OS Name: Mac OS X (NSMACHOperatingSystem)
02:22:13.846: OS Version: Version 10.14.6 (Build 18G5033)
02:22:13.846: Kernel Version: 18.7.0
02:22:13.851: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
02:22:13.851: Portable mode: false
02:22:14.041: OBS 25.0.8 (mac)
02:22:14.041: ---------------------------------
02:22:14.042: ---------------------------------
02:22:14.042: audio settings reset:
02:22:14.042: 	samples per sec: 44100
02:22:14.042: 	speakers:        2
02:22:14.043: ---------------------------------
02:22:14.043: Initializing OpenGL...
02:22:14.067: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 560 OpenGL Engine
02:22:14.067: OpenGL loaded successfully, version 4.1 ATI-2.11.21, shading language 4.10
02:22:14.152: ---------------------------------
02:22:14.152: video settings reset:
02:22:14.152: 	base resolution:   1280x720
02:22:14.152: 	output resolution: 640x360
02:22:14.152: 	downscale filter:  Bicubic
02:22:14.152: 	fps:               30/1
02:22:14.152: 	format:            NV12
02:22:14.152: 	YUV mode:          601/Partial
02:22:14.152: NV12 texture support not available
02:22:14.152: Audio monitoring device:
02:22:14.152: 	name: Default
02:22:14.152: 	id: default
02:22:14.153: ---------------------------------
02:22:14.155: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
02:22:14.161: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found
02:22:14.161: 
02:22:14.161: [Python] Could not load library: libpython3.7m.dylib
02:22:14.203: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
02:22:14.203: No blackmagic support
02:22:14.264: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
02:22:14.289: [obs-browser]: Version 2.8.6
02:22:14.298: VLC found, VLC video source enabled
02:22:14.298: Ignoring old obs-browser.so version
02:22:14.299: Loading iOS Camera Plugin (version 2.6.1)
02:22:14.300: ---------------------------------
02:22:14.300:   Loaded Modules:
02:22:14.300:     obs-ios-camera-source.so
02:22:14.300:     vlc-video.so
02:22:14.300:     text-freetype2.so
02:22:14.300:     rtmp-services.so
02:22:14.300:     obs-x264.so
02:22:14.300:     obs-vst.so
02:22:14.300:     obs-transitions.so
02:22:14.300:     obs-outputs.so
02:22:14.300:     obs-libfdk.so
02:22:14.300:     obs-filters.so
02:22:14.300:     obs-ffmpeg.so
02:22:14.300:     obs-browser.so
02:22:14.300:     mac-vth264.so
02:22:14.300:     mac-syphon.so
02:22:14.300:     mac-decklink.so
02:22:14.300:     mac-capture.so
02:22:14.300:     mac-avcapture.so
02:22:14.300:     linux-jack.so
02:22:14.300:     image-source.so
02:22:14.300:     frontend-tools.so
02:22:14.300:     decklink-ouput-ui.so
02:22:14.300:     coreaudio-encoder.so
02:22:14.300: ---------------------------------
02:22:14.300: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
02:22:14.300: 
02:22:14.300: ==== Startup complete ===============================================
02:22:14.313: All scene data cleared
02:22:14.314: ------------------------------------------------
02:22:14.347: coreaudio: device 'iShowU Audio Capture' initialized
02:22:14.347: [Loaded global audio device]: 'Mic/Aux'
02:22:14.347: Switched to scene 'Scene'
02:22:14.348: ------------------------------------------------
02:22:14.348: Loaded scenes:
02:22:14.348: - scene 'Scene':
02:22:14.348: ------------------------------------------------
02:22:14.780: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
02:22:14.780: 
02:22:32.262: User added source 'Browser' (browser_source) to scene 'Scene'

**Comment by WizardCM** [comment] 2020-07-27 11:55
Closing as this is a duplicate of https://github.com/obsproject/obs-browser/issues/99

**Closed by WizardCM** 2020-07-27 11:55 UTC
