### ISSUE TITLE
Displaycapture fails to display secondary screen

### ISSUE THREAD

**Issue by khezuu** [obsproject/obs-studio#8987] opened 2023-05-29 12:37 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/cI20ifjVpiOkVGat

### Expected Behavior

When having 2 displays connected to you computer Display Capture is able to switch between displays

### Current Behavior

Display capture shows 2 screens available to capture but no matter which one is selected it will still preview the primary screen

### Steps to Reproduce

1. Add a Display Capture to your scene
2. Switch between your 2 available screens inside display capture options
3. Observe no change in the preview
...

### Anything else we should know?

This issue was introduced in 29.0. 
This issue does not exist in 28.X.X and downgrading works.

**Comment by notr1ch** [comment] 2023-05-29 14:22
Duplicate of https://github.com/obsproject/obs-studio/issues/8181, see steps there for a possible workaround.

**Closed by notr1ch** 2023-05-29 14:22 UTC
