### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [obsproject/obs-studio#4520] opened 2021-04-13 19:03 UTC
### Operating System Info

Other

### OBS Studio Version

Git

### OBS Studio Log URL

x

### Expected Behavior

Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [pitch_search](https://github.com/obsproject/obs-studio/blob/3564e446ffa076ace93bb1f69f3dcddc93025b6e/plugins/obs-filters/rnnoise/src/pitch.c#L300)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [jack_create](https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/plugins/linux-jack/jack-input.c#L95)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [SocksSetup](https://github.com/obsproject/obs-studio/blob/244b6c92e66019c5fb07cfab28b6f7a3f35b5e79/plugins/obs-outputs/librtmp/rtmp.c#L557)

### Current Behavior

Undefined software behaviour may occur.

### Steps to Reproduce

[Perform another bit of source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis").

**Comment by gxalpha** [comment] 2021-04-13 19:10
You could just create a pull request

**Comment by elfring** [comment] 2021-04-13 19:14
:thinking: I imagine that [there are some aspects to consider for remaining open issues](https://cwe.mitre.org/data/definitions/252.html "Checking more return values").

**Comment by gxalpha** [comment] 2021-04-13 19:22
could you elaborate on these issues with further explanation?

Also maybe without posting links?

**Comment by elfring** [comment] 2021-04-13 19:28
I find [referenced information sources helpful](https://wiki.sei.cmu.edu/confluence/display/c/ERR00-C.+Adopt+and+implement+a+consistent+and+comprehensive+error-handling+policy "Adopt and implement a consistent and comprehensive error-handling policy.") for this issue.

**Comment by RytoEX** [comment] 2021-04-14 00:16
Including referenced sources of information can be helpful, but please explain or summarize how the references are related to the issue at hand.  Simply dropping links isn't as helpful as providing actual context for them.  Can you please explain or summarize the links you are referencing and how they relate to the issue that you've opened?

If you're using static analysis tools, please say what tools you're using and which issues each tool flags.  Please also tell us if you tested these changes in any compilers or not.

**Comment by elfring** [comment] 2021-04-14 16:05
>Can you please explain or summarize the links you are referencing and how they relate to the issue that you've opened?

I suggest to reconsider software development consequences from overlooked function return values.
Under which circumstances would you dare to read referenced information yourself?


>If you're using static analysis tools, please say what tools you're using and which issues each tool flags.

You can choose source code search software for this purpose, can't you?

**Comment by RytoEX** [comment] 2021-04-14 23:06
> I suggest to reconsider software development consequences from overlooked function return values.
> Under which circumstances would you dare to read referenced information yourself?

I have read the referenced information in the original post, and I've skimmed the two links in follow-up comments.  I believe your point is that we're not checking return values from the functions called.  That doesn't change or invalidate my request.  Can you please explain or summarize the links you are referencing and how they relate to the issue that you've opened?  You're just forcing maintainers to do additional reading instead of briefly summarizing your points.

> You can choose source code search software for this purpose, can't you?

I want to know _specifically_ what tool _you_ used for these, so that _we_ can reproduce these findings ourselves.

So I repeat:  If you're using static analysis tools, please say what tools you're using and which issues each tool flags.

And as asked [elsewhere](https://github.com/obsproject/obs-studio/issues/4519#issuecomment-818958667):
> Is this causing a problem somewhere? If not, could you just submit a pull request?
>
> We don't typically use Github issues for tracking fixup issues.

**Comment by alinsavix** [comment] 2021-04-14 23:57
So, I went and looked at the github activity history for this person. For the last half-year or (I got bored and haven't looked back further than that), his entire "contributions" to projects, with perhaps one exception, consists of opening dozens or hundreds of issues (but only a few per project) citing the results of what would appear to be some sort of static code analyzer, without providing actual useful information, patches, or even coherent discussion, with many responses being like the ones here -- links to various descriptions of issues around the internet, and most of the rest basically being "this is wrong [from a purely academic perspective] don't you want to fix this?"

Every now and then he raises an issue that isn't purely from an automated code review, and every now and then someone goes "oh, yeah, we should check that return code" or "okay, yeah, we don't need that null pointer check", but the vast majority of his open issues are either untouched, closed without action, or closed without action and then locked by the project owner because he kept debating.

Best I can tell, it's basically impossible to get anything actually actionable out of him, except by blind luck.

Recepts:
  * incoherence: https://github.com/c0fec0de/anytree/issues/160
  * no real point and refusal to actually work with the project team in their preferred way: https://github.com/symfony/symfony/issues/40724
  * vague requests, nonresponsive answers to questions, and general insults ("your imaginations are too limited for my needs"): https://github.com/symfony/symfony/issues/40594, https://github.com/symfony/symfony/issues/40577, https://github.com/symfony/symfony/issues/40509
  * arguing with the developer over how their software actually works: https://github.com/coccinelle/coccinelle/issues/243
  * "tired of your reports, please provide specifics" + "but I said you needed null pointer checks, isn't that specific enough?": https://github.com/michaelrsweet/htmldoc/issues/407, https://github.com/michaelrsweet/htmldoc/issues/406
  * just a bit of everything: https://github.com/michaelrsweet/pappl/issues/113
 
...out of the 50 or so issues I looked through, opened by this person, not a single one contained anything I would consider to be a material contribution to a project, but plenty contained project contributors spending obviously nontrivial amounts of their own time "discussing" things with him, for no benefit.

I suggest just closing these tickets and blocking that account from opening new ones.

**Comment by RytoEX** [comment] 2021-04-15 01:04
After further consideration and discussion with other project members, we've decided to close this issue.  If you have proposed fixes for these issues, please feel free to submit pull requests.

**Closed by RytoEX** 2021-04-15 01:04 UTC

**Comment by elfring** [comment] 2021-04-15 09:54
>I believe your point is that we're not checking return values from the functions called.

Yes. — A few places are affected here.


>You're just forcing maintainers to do additional reading

Maybe.


>instead of briefly and clearly summarizing your points.

I wonder why you would need another summary.


>I want to know _specifically_ what tool you used for these, …

I found questionable implementation details with [the help of the GitHub source code search interface](https://docs.github.com/en/github/searching-for-information-on-github/searching-code "Searching code").


> > Is this causing a problem somewhere?

I suggest to [reconsider risks also according to undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers").

**Comment by elfring** [comment] 2021-04-15 10:05
>Best I can tell, it's basically impossible to get anything actually actionable out of him, except by blind luck.

I propose to reconsider also this view.

The software development interests are varying for reported issues.


>…, not a single one contained anything I would consider to be a material contribution to a project, …

:thinking: I guess that you can find helpful items in my published contribution history.

**Comment by bershanskiy** [comment] 2021-04-15 10:45
You might find this interesting:
https://github.com/torvalds/linux/commits?&author=elfring

So I believe @elfring is using Coccinelle and had actually contributed to Linux kernel a lot of commits. If you look at these commit messages, you'll see:
- that they are all incredibly generic and appear to be just a verbatim output of a script (commits are not grouped together and sqwashed)
- some commits go against established security principles (like [removing NULL initialization of a pointer](https://github.com/torvalds/linux/commit/9376e4a5a318e1dbf1c53a31cfbe919e0ba926b0))
- most commits don't really change anything, they mostly enforce some linting rules

**Comment by elfring** [comment] 2021-04-15 11:13
>So I believe … is using Coccinelle and had actually contributed to Linux kernel a lot of commits.

I imagine that there is no “believe” needed. — You can refer to published facts.

**Comment by PatTheMav** [comment] 2021-04-15 13:57
In the interest of not wasting time on deciphering more word salad masquerading as comments, I'm locking this issue for further comments.
