### ISSUE TITLE
'Check For Updates' Dialog Box Not Operating As Exepected.

### ISSUE THREAD

**Issue by scramblr** [obsproject/obs-studio#5068] opened 2021-08-04 11:27 UTC
### Operating System Info

macOS 10.15

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/bvcAWly2S6k7ph1Y

### Expected Behavior

I expected to be able to click "Don't Check" or "Check Automatically", however neither button seems to work and thus the nag screen is impossible to get rid of. The only way to use OBS is to click on the other screens and hide the nag screen. This seems like an easy fix, but sadly I am not able to provide a patch at this time. 

Thanks.

### Current Behavior

Nothing. "Check for updates automatically?" screen is impossible to get rid of. 

### Steps to Reproduce

1. Open OBS
2. Breathe, move mouse a bit, see the screen asking if whether OBS should "Check for updates automatically?"
3. Exhale, realizing that no amount of clicking or injecting kitten hair into my power supply will solve this issue
4. Click on the screens behind the nag screen, hoping OBS wont crash at some point because this question was left unanswered, or that it is an indicator of a larger issue. I have no idea. 

### Anything else we should know?

I like kittens.

**Comment by WizardCM** [comment] 2021-08-04 11:59
Duplicate of #4904

**Closed by WizardCM** 2021-08-04 11:59 UTC
