### ISSUE TITLE
nix: do not add bad plugins paths

### ISSUE THREAD

**Issue by zlice** [obsproject/obs-studio#11084] opened 2024-08-06 17:29 UTC
### Operating System Info

Other

### Other OS

void linux

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/qZkFPBGAgWNQjgfi

### Expected Behavior

Plugin directories that do not exist do not wipe out working plugin directories.

### Current Behavior

Built with https://github.com/void-linux/void-packages/blob/master/srcpkgs/obs/template#L8 `-DCMAKE_INSTALL_DATAROOTDIR=/usr/share` the directories are already not found because https://github.com/obsproject/obs-studio/blob/master/libobs/obs-nix.c#L74 uses a relative path with `OBS_DATA_PATH`.

But even if you supply `OBS_PLUGINS_PATH=/lib/obs-plugins` and `OBS_PLUGINS_DATA_PATH=/usr/share/obs/obs-plugins/` the hard coded directories https://github.com/obsproject/obs-studio/blob/master/libobs/obs-nix.c#L92 (which may not exist and some are also relative) get added after scanning user defined plugin paths.

Printing out in various places shows that `make_data_directory` https://github.com/obsproject/obs-studio/blob/master/libobs/obs-module.c#L439 > https://github.com/obsproject/obs-studio/blob/master/libobs/obs-module.c#L495 `process_found_module` somehow appends or changes the currently loaded plugin that would work, even though some directory doesn't exist.

### Steps to Reproduce

1. use linux package (may require DCMAKE_INSTALL_DATAROOTDIR build?)
2. launch obs
3. capture display with fade cut doesn't work because fade wasn't found at `/usr/usr/share/obs/obs-plugins` and nukes the plugin that was loaded from `/usr/share/obs/obs-plugins` (this was me messing with hardcoded paths and prints)

### Anything else we should know?

Adding a check if the directory is even valid fixes this, but it's more of a hack.

https://github.com/obsproject/obs-studio/blob/master/libobs/obs-nix.c#L92

```
  struct stat stat_info;

  for (int i = 0; i < module_patterns_size; i++) {
    if ((stat(module_bin[i], &stat_info) == 0 && !!S_ISDIR(stat_info.st_mode) )
        && (stat(module_data[i], &stat_info) == 0 && !!S_ISDIR(stat_info.st_mode) ) )
      obs_add_module_path(module_bin[i], module_data[i]);
  }
```

I was going to use `is_dir` from https://github.com/obsproject/obs-studio/blob/master/libobs/util/platform-nix.c but I think that needs extra linking or something.

#### Request

What I think should be fixed is:

1. Check that directories exist before adding them. Maybe print out that there was an attempt like other things do.
2. `CMAKE_INSTALL_DATAROOTDIR` / `OBS_DATA_PATH` / `OBS_DATA_DESTINATION` should be sync'd. I did not see a way for it to actually be used correctly given that `/usr/share/obs` becomes relative to the exe dir and some mess of `/usr/bin/../usr/usr/?????`
3. `UI/window-basic-main.cpp:	s = getenv("OBS_PLUGINS_DATA_PATH");` should probably be an override and added **after** the rest of the modules? If it exist.

**Comment by tytan652** [comment] 2024-08-06 17:31
Duplicate of #11029

**Closed by tytan652** 2024-08-06 17:31 UTC
