### ISSUE TITLE
Cannot record multi-layer games

### ISSUE THREAD

**Issue by Yackitori** [obsproject/obs-studio#3610] opened 2020-10-15 03:54 UTC
## Platform
Operating system and version: Windows 10 ver. 1909
OBS Studio version: 26.0.2

## Expected Behavior
Game should be recorded like what is seen on screen.

## Current Behavior
Only the crosshair is displayed on a purple background, and movement is rather choppy. The audio records perfectly fine.

## Steps to Reproduce
See https://gfycat.com/everlastingcheerfulbarnowl for video.
1. Launch Mad Dog McCree 1993 from CD Rom drive
2. Start window capture
3. Begin recording
4. Finish recording and see only the crosshair

## Additional information
After some research, I have been told that this error occurs due to the game running in layers. The background is made up of videos, while the crosshair and HUD are on a separate layer. OBS, and every free screen capture software I tried appears to only record the HUD crosshair layer.

**Comment by WizardCM** [comment] 2020-10-15 03:55
Are you using Game Capture, or Window Capture. If the latter, is it BitBlt or WGC?

**Comment by skeletonbow** [comment] 2020-10-15 05:09
It may be possible to record old games like this by reconfiguring them.  This is a technical support problem and not a bug however, you can seek support on either OBS Discord or OBS forums on the website and someone might be able to offer some tips.

**Comment by Yackitori** [comment] 2020-10-15 21:33
@WizardCM 
I tried running it in both game capture and window capture. Game capture outright failed to detect anything, and I tried both window capture settings to the same result. Just capturing the HUD and crosshair.

**Comment by derrod** [comment] 2020-10-16 00:13
What about display capture?

Not ideal but it's unlikely anybody will spend time on a workaround for very old games like that.

**Comment by Yackitori** [comment] 2020-10-16 01:51
@derrod 
Display capture fails as well. Same result.

**Comment by derrod** [comment] 2020-10-16 01:55
As I suspected. Some older games (mainly fmv) use an old method of rendering video that essentially bypasses all of the (fast/modern) capturing APIs windows provides us with. I don't believe that will ever be solved unless somebody passionate enough about capturing old FMV games figures out some way to do that. So for the time being I'll mark this as a "wontfix".

**Closed by derrod** 2020-10-16 01:55 UTC
Labels: Won't Fix

**Comment by mufunyo** [comment] 2020-10-16 10:55
I would recommend playing games like this in a VM, and using OBS to capture the VM. It's unlikely that any performance penalty from running games in a VM will meaningfully affect such old games running on modern hardware. There are free virtualisation solutions with adequate DirectX emulation like VMware Player or VirtualBox.
