### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by steinraf** [obsproject/obs-studio#9637] opened 2023-09-28 07:04 UTC
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/FdjCdpBORdQkZIdQ

### Expected Behavior

startup

### Current Behavior

Crash before app starts

### Steps to Reproduce

1. Open OBS
2. Observe Crash

### Anything else we should know?

when running with gdb it outputs the following message

```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c01cd4 in QScreen::geometry() const () from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
```

deleting the `~/.config/obs-studio/global.ini` file fixes the issue until the next start

**Comment by RytoEX** [comment] 2023-09-28 16:22
Looks like #7284.

**Comment by kkartaltepe** [comment] 2023-09-29 00:34
duplicate of #7284

probably, since user does not provide the full stack.

**Closed by kkartaltepe** 2023-09-29 00:34 UTC
