### ISSUE TITLE
[regression in 28.0.0] It installs the whole build directory

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#7265] opened 2022-09-02 04:47 UTC
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.0.0

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

Installs these files into ```$PREFIX```:
```
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/bin/obs
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/bin/obs-ffmpeg-mux
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-frontend-api.so
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-frontend-api.so.0
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-frontend-api.so.28
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-opengl.so
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-opengl.so.1
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-opengl.so.28
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-scripting.so
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-scripting.so.1
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-scripting.so.28
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs.so
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs.so.0
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs.so.28
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobsglad.so
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobsglad.so.1
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobsglad.so.28
...
...
```

### Steps to Reproduce

normal build

**Comment by kkartaltepe** [comment] 2022-09-02 15:26
I believe we added soversion support which might have prompted cmake to install the associated symlinks. Im not sure that this is actually an issue as soversion links are supported and used on every platform so changing to using them is not a regression.

**Comment by yurivict** [comment] 2022-09-02 15:28
soversion support shouldn't install files **into the build directory**.

**Comment by kkartaltepe** [comment] 2022-09-02 15:37
On master all files install into the prefix as expected, if your only concern is that the _build_ directory has different files than last time then this is not considered an issue.

Notably some users have difficulty with the installation concept of cmake and so we construct a mostly usable staged install during build time for developer users to use without installing.

**Comment by yurivict** [comment] 2022-09-02 16:11
> [...] if your only concern is that the build directory has different files than last time then this is not considered an issue.

No, all packagers would have a problem with this because the package would re-create the build directory on all user sites.

**Comment by kkartaltepe** [comment] 2022-09-02 16:30
I dont understand your concern. As I said before cmake install only installs files into the install prefix. If your packaging tools have specific dependencies on the build directory we cannot support that.

**Comment by kkartaltepe** [comment] 2022-09-02 16:54
I also deleted the build/rundir and ran the install step again to confirm that install does not place anything into the build/rundir even silently.

**Comment by yurivict** [comment] 2022-09-02 22:38
When 'make install' installs from the build directory
```/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build```
into the stage directory
```/tmp/stage```
it creates files like
```/tmp/stage/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.build/rundir/Release/lib/libobs-frontend-api.so```.

Why is this file created under the stage directory?

**Comment by kkartaltepe** [comment] 2022-09-02 22:40
It does not happen for me, please provide more information on how you are configuring cmake.

**Comment by yurivict** [comment] 2022-09-04 17:27
cmake arguments:
-DOBS_VERSION_OVERRIDE:STRING="28.0.0" -DBUILD_BROWSER:BOOL=false -DENABLE_JACK=TRUE -DENABLE_PULSEAUDIO=TRUE -DENABLE_SNDIO=TRUE -DBUILD_VST:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DUNIX_STRUCTURE:BOOL=ON -DENABLE_PIPEWIRE:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.9 -DBOOST_PYTHON_SUFFIX:STRING=39

**Comment by yurivict** [comment] 2022-09-04 17:28
make environment:
NINJA_STATUS="[%p %s/%t] " LUA_MODLIBDIR=/usr/local/lib/lua/5.2  LUA_MODSHAREDIR=/usr/local/share/lua/5.2  LUA_MODDOCSDIR=/usr/local/share/doc/lua52  LUA_INCDIR=/usr/local/include/lua52  LUA_LIBDIR=/usr/local/lib  LUA_VER=5.2  LUA_VER_STR=52 QT_SELECT=qt5 QMAKEMODULES="/disk-samsung/freebsd-ports/multimedia/obs-studio/work/obs-studio-28.0.0/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" XDG_DATA_HOME=/disk-samsung/freebsd-ports/multimedia/obs-studio/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/multimedia/obs-studio/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.cache  HOME=/disk-samsung/freebsd-ports/multimedia/obs-studio/work PATH=/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/disk-samsung/freebsd-ports/multimedia/obs-studio/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES DESTDIR=/disk-samsung/freebsd-ports/multimedia/obs-studio/work/stage LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fPIC -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"

**Comment by kkartaltepe** [comment] 2022-09-04 17:30
`-DCMAKE_INSTALL_PREFIX:PATH="/usr/local" `

`PREFIX=/usr/local LOCALBASE=/usr/local`

It seems are you not configuring your install prefix at all in cmake. Id recommend your packaging tools configure the install prefix if they want things to be installed into the right place.

**Comment by yurivict** [comment] 2022-09-04 17:32
> It seems you are not configuring your install prefix at all in cmake.

This is done with ```DESTDIR```.

**Comment by kkartaltepe** [comment] 2022-09-04 17:32
Since there are no references to the location you reported before, im also not sure how to diagnose further into that.

**Comment by yurivict** [comment] 2022-09-04 17:33
Install prefix is one thing, stage dir is another. cmake doesn't know about the stage dir. It works only at the make phase.

**Comment by yurivict** [comment] 2022-09-04 17:37
Now I tried with gmake instead of ninja - and the problem went away.
This might be a bug in ninja that only manifests itself in 28.0.0

**Comment by kkartaltepe** [comment] 2022-09-04 18:00
I am also using ninja, but i am installing into the prefix.

**Comment by yurivict** [comment] 2022-09-04 18:07
Package managers all install into a stage dir.

I use ninja-1.10.2

**Comment by PatTheMav** [comment] 2022-09-11 21:32
We use CMake's `install` command to set up a runtime directory inside the build tree which is used on Windows to create a runnable instance of OBS for debugging with MSVC and also creates a runnable instance on Linux when using portable build config. This is why an instance of OBS with all associated libraries and files will reside in the the build directory.

If you set `DESTDIR` globally this would probably influence this setup. Instead you should only set it for the install step:

`DESTDIR=<YOUR DESIRED PREFIX> cmake --install <BUILD_DIR> --prefix /usr/local --config RelWithDebInfo`

This should ensure that `DESTDIR` is only used for installing and not for the build process (which installs the runtime directory). Specifying it only for the install step is the suggested way for CMake as well as Meson.

**Comment by yurivict** [comment] 2022-09-11 22:02
On FreeBSD the ports framework routinely adds the DESTDIR environment variable to all make invocations, including to ```make all```.

**Comment by kkartaltepe** [comment] 2022-09-11 22:06
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

> DESTDIR should be supported only in the install* and uninstall* targets, as those are the only targets where it is useful. 

This seems like an abuse of DESTDIR by the freebsd packaging tool. Im not sure we want to deal with this if `make` handles this edge case successfully, perhaps file a bug against ninja to have to behave similarly when abusing DESTDIR.

**Comment by PatTheMav** [comment] 2022-09-11 22:20
IMO this is not a Ninja issue - CMake prepends the value of `DESTDIR` to destinations in each target's `cmake_install.cmake`:

```
"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}
```

We create a rundir install component (that is excluded from the `ALL` target) which is added to this file and appropriately uses the same pattern to set the destination directory.

So when we run `cmake --install` as a post-build command, it will pick up `DESTDIR` set in the environment:

```
  POST_BUILD = cd <TARGET_DIR> && cmake --install . --config RelWithDebInfo --prefix <PREFIX> --component obs_libobs > /dev/null [...]
```

That's all Ninja sees, so it's CMake who will pick up the `DESTDIR` at compile time.

**Comment by eli-schwartz** [comment] 2022-09-12 04:53
> https://www.gnu.org/prep/standards/html_node/DESTDIR.html
> 
> > DESTDIR should be supported only in the install* and uninstall* targets, as those are the only targets where it is useful.
> 
> This seems like an abuse of DESTDIR by the freebsd packaging tool. Im not sure we want to deal with this if `make` handles this edge case successfully, perhaps file a bug against ninja to have to behave similarly when abusing DESTDIR.

FreeBSD is correct here, in accordance with the GNU standards. DESTDIR can be set whenever, but only the install and uninstall targets should consult the variable and make use of them.

Per the GNU standards, obs is broken, because it has targets running as a POST_BUILD which "support" DESTDIR when they should not.

This must be fixed by obs, not by FreeBSD.

**Comment by eli-schwartz** [comment] 2022-09-12 04:59
> We use CMake's `install` command to set up a runtime directory inside the build tree which is used on Windows to create a runnable instance of OBS for debugging with MSVC and also creates a runnable instance on Linux when using portable build config. This is why an instance of OBS with all associated libraries and files will reside in the the build directory.

This seems like an abuse of the install command IMHO, and also is likely to not work quite as well as you'd want it to because of things like rpath. If you want to create an instance that resides in the build directory, the best way to do that is probably to have an additional configured build directory that installs into `$PWD/devtree` or something.

CMake will set up build-time rpaths so that at least executables can find their uninstalled libraries. Meson does this too, and also has `devenv` to handle various generic cases...

**Comment by PatTheMav** [comment] 2022-09-12 08:11
Personally I’d rather remove the rundir installation on any OS but Windows (where it’s needed due to how the MSVC project is set up for debugging), but that’s for Linux maintainers to decide how they want/need debugging to work in their IDE’s and come up with PRs for that.

It is necessary to some degree due to how OBS uses paths relative to its binaries to discover core plugins and more (which also change whether or not you create a ‘portable’ build), but I’m out of energy trying to thread that needle on my own for all OSes simultaneously.

I’ll probably hotfix this one if I can get it not to break Windows and then I’ll need to step back from supporting Linux build systems and leave it to contributors to fix and PR what they need.

**Comment by eli-schwartz** [comment] 2022-09-12 18:09
Instead of using installer rules, shouldn't it be possible to use `cmake -E copy` in a custom script perhaps bound to a build rule called "ninja devenv" or something?

**Comment by PatTheMav** [comment] 2022-09-12 18:33
We used the `copy` command before, but it also didn't allow us to copy files _after_ other targets have finished (as you can only add custom build commands to targets defined on the same level as the current script), required additional complexity to support all our OSes, and also didn't allow us to "bundle" files of different targets into a single copy step (it also doesn't skip existing files and requires manual attention to symlinks). We'd also have to add manual mixup steps (e.g. for RPATHs, code signatures, etc.).

The `install` command implements lots of functionality (including but not limited to only copying updated files) and improved our build speeds. Also it made sense to use the `install` command to run an automatic installation of the project into the "rundir".

**Closed** 2022-09-17 23:15 UTC
Labels: Fix available, Confirmed, Other OS (*nix)
