### ISSUE TITLE
Virtual Cam shows a red screen instead of video

### ISSUE THREAD

**Issue by markflorkowski** [obsproject/obs-studio#7333] opened 2022-09-09 19:13 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/i5aP5GOrwhY0Sic1

### Expected Behavior

Virtual camera should show the currently selected output scene

### Current Behavior

Red screen in application attempting to use virtual camera

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/11494384/189426467-c7edf219-e782-4284-9b96-129dfa10c54f.png">

### Steps to Reproduce

1. Open OBS, start virutal camera
2. attempt to use virtual camera in google chrome (eg. meet.google.com)
3. note that camera just shows red
...

### Anything else we should know?

On a 2019 MacBook Pro with the following specs:
- macOS version: 12.3.1
- Processor: 2.4 GHz 8-Core Intel Core i9
- Memory: 64 GB 2667 MHz DDR4
- Graphics: AMD Radeon Pro 5500M 8 GB, Intel UHD Graphics 630 1536 MB

**Comment by BenDMyers** [comment] 2022-09-09 19:20
I was getting this issue today as well.

**OBS version:** 28.0.1

On a 2019 MacBook Pro with the following specs:
- **macOS version:** 12.5.1
- **Processor:** 2.3 GHz -Core Intel Core i9
- **Memory:** 16 GB
- **Graphics:** AMD Radeon Pro 5500M 8 GB, Intel UHD Graphics 630 1536 MB

Encoded with the Apple VT H264 Hardware Encoder.

**Comment by markflorkowski** [comment] 2022-09-09 20:17
The placeholder shows correctly if I disable the virtual camera in OBS and use it in an application

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/11494384/189436049-80c076ba-db62-4994-ba5c-9c8cf92356b0.png">

**Comment by TheoBr** [comment] 2022-09-09 20:23
I have not been able to replicate on either my M1 Macbook Air or M1 Pro, but can reliably repro on my intel machine. I am relatively certain this is intel specific

**Comment by markflorkowski** [comment] 2022-09-09 20:24
Also was unable to replicate on my Mac Studio, so that is one more point towards it being an Intel-specific issue

**Comment by prgmitchell** [comment] 2022-09-09 20:29
Can confirm I am getting a blank green screen when trying to use virtual cam on 28.0.1. Also on an intel macbook pro.

**Comment by PatTheMav** [comment] 2022-09-09 20:31
> Also was unable to replicate on my Mac Studio, so that is one more point towards it being an Intel-specific issue

That seems to be the case, wasn't able to reproduce on any of my M1 Macs, but on my last remaining Intel-mac it appeared in Firefox immediately.

**Comment by sethpjohnson** [comment] 2022-09-12 22:49
Confirming the same red output on 2013 Trashcan Intel Mac. Placeholder is fine.

**Comment by watling** [comment] 2022-09-13 09:11
same issue with red output on MacPro Intel - MacOS 13 Beta and OBS 28.0.1

**Comment by PatTheMav** [comment] 2022-09-13 09:13
Thank you, but at this time we are not in need of any more confirmations of the bug (as we confirmed it ourselves). We welcome PRs to fix the bug however.

**Comment by decorear** [comment] 2022-09-13 11:56
When setting the video input from Zoom application, the Red screen dissapears and shows the virtual camera on Google Meet as normal. However, after closing the setting screen or changing to another setting page, it turned to red screen again.

MBP 16" Intel i9 - Monterey v12.5

**Comment by in-op** [comment] 2022-09-15 21:04
If I output to 1280x720, it's all red, however if I output to 1920x1080, it's all green. My base canvas resolution is 2560x1440. Hopefully this is a clue that helps. I'm also running an intel chip on a mac 12.6, OBS 28.0.1

**Closed** 2022-09-21 15:04 UTC
Labels: macOS, Fix available, Confirmed

**Comment by in-op** [comment] 2022-10-27 20:08
I still have this in 28.0.3

**Comment by PatTheMav** [comment] 2022-10-27 21:40
@in-op Please open a new issue with the filled-out issue template so we can track your specific environment.

**Comment by verstaerkermusic** [comment] 2023-01-16 00:58
i can confirm the issue , i only got the actual output when switching the color format to
I420 
but that doesnt seem to compatible with every video conferencing (looks very low quality in Jitsi for example)

**Comment by Shiyazudeen** [comment] 2023-01-30 17:06
macOS Ventura 13.1 (22C65) - OBS Virtual Cam on _Teams_ shows green screen when switched on. If the virtual cam is switched off, the placeholder image shows broken. OBS version 29.0.0 (64 bit). Toggling either the 'adjust brightness' or the 'soft focus' options doesn't make any difference. 

![obs-virtualcam-mac-issue](https://user-images.githubusercontent.com/6204612/215544538-cc266ef6-97f1-424d-8a68-ce7afa557f93.jpg)

**Comment by Jacques-from-Canny** [comment] 2023-02-01 18:23
> Following. I too am seeing a Red output when turning on Virtual Camera.
> 
> * OBS v29.0.0 (also tested with v28.1.2)
> * Base canvas/Output resolution: 1920x1080
> * I see camera offline+obs graphic when I turn the camera off.
> * Output type: I've tested all of them.
> * Output Selction: I've tested all of them.
> * iMac Pro (Intel chip)
> * I've also have obs-ndi installed.
> * I've also deleted obs-ndi + obs, and did a clean install with just obs.

Not sure why this issue is closed. I'm seeing it as well. I tried to uninstall and reinstall, and no fix.

**Comment by PatTheMav** [comment] 2023-02-01 18:28
The issue is closed because a fix was merged via https://github.com/obsproject/obs-studio/pull/7403 (as explicitly called out by the issue timeline).

GitHub issues are a tool for project maintainers and developers, so once a bug is fixed in code, the associated issue is closed. Expect this fix to be released in an upcoming OBS update.
