### ISSUE TITLE
Pause and Resume Recording Doubles or Triples CPU usage

### ISSUE THREAD

**Issue by pllovervoltage** [obsproject/obs-studio#3148] opened 2020-07-10 02:38 UTC
## Platform
Operating system and version: Windows 10 1809
OBS Studio version: 25.08

Repeatable in two systems. (System1 i5-1035G1) (System2 2200G + RX 580)

## Expected Behavior
CPU usage remains low at 7-12%

## Current Behavior
Pausing and then resuming the recording increases cpu to 20-40%
Increased cpu usage persists until end of recording (>30min)

## Steps to Reproduce
1. Start Recording
2. Pause Recording
3. Resume Recording

System1
Before Pausing
![11](https://user-images.githubusercontent.com/68091363/87110206-6d730880-c2a1-11ea-9226-54ba065f11c9.PNG)

After Pausing
![12](https://user-images.githubusercontent.com/68091363/87110227-782d9d80-c2a1-11ea-94dc-67d576a98788.PNG)

High Usage Persists for more than 5 min
![13](https://user-images.githubusercontent.com/68091363/87110237-7bc12480-c2a1-11ea-80de-33a127f40fd8.PNG)

System2
Before Pausing
![11](https://user-images.githubusercontent.com/68091363/87110288-9d221080-c2a1-11ea-884a-336794357e97.PNG)

After Pausing
![12](https://user-images.githubusercontent.com/68091363/87110289-9e533d80-c2a1-11ea-9bdc-ae97db523e1e.PNG)

High Usage Persists for more than 5 min
![13](https://user-images.githubusercontent.com/68091363/87110293-a01d0100-c2a1-11ea-85d0-705e86c29b10.PNG)

## Additional information
Settings: 
![1](https://user-images.githubusercontent.com/68091363/87109471-bf1a9380-c29f-11ea-96d5-c4ea64d7cd50.PNG)

Default settings with attached page with changes. Two changes not in screen are...
Video > Output Resolution > Changed to match base resolution
Output > Audio > Track 1 > Audio Bitrate > Changed to 64

Logs:
https://obsproject.com/logs/IR9mIidpY0kogFPy

https://obsproject.com/logs/kJE2zrdi5WV6WYR-

**Comment by Gol-D-Ace** [comment] 2020-07-10 02:50
I can reproduce this.

**Comment by notr1ch** [comment] 2020-07-23 23:52
Any special tricks to reproduce this? I can't seem to trigger it in either simple or advanced mode, even with the settings above.

**Comment by skeletonbow** [comment] 2020-08-02 12:00
Found this bug report while having the exact same problem when playing (rather than recording) media files with 25.0.8.  I've reproduced the playback issue with the current nightly build without any plugins or scripts present, my CPU usage when playing video starts at 8% with the stable release or 4% with the nightly (the difference most likely being plugins used with the stable release), and when the video is paused it jumps to 20% on stable release or 14% on nightly, approx 10-12% CPU usage increase for pausing a video.

Not sure if it is related to this recording bug, but similar symptoms so I thought I'd mention it here.  Having said that, I decided to test for this recording bug also and my CPU usage does not increase on pausing a recording oddly enough.  I'm using AMD Radeon hardware (HD7850) with the stock AMF hardware encoder in case that is a useful data point for this particular bug report.

Will file a separate report for the media playback CPU spike if I can't find one already present as the playback and recording issues could be separate issues.

**Comment by skeletonbow** [comment] 2020-08-02 12:16
Tested this recording bug on my nVidia laptop (1050Ti) using native Nvenc(new) encoder (override stream encoder), and unable to reproduce the CPU spike during pause on record so far.  Could be specific encoder settings that cause it perhaps?

**Comment by Gol-D-Ace** [comment] 2020-08-02 12:21
@skeletonbow 
The log shows the usage of x264 and I reproduced it with x264.

I honestly didn't come up with the idea to try NVENC because it isn't a CPU (software) based Encoder.

**Comment by Gol-D-Ace** [comment] 2020-08-02 12:23
@skeletonbow 
You should probably create a separate issue for the problem you mentioned if none exists yet.

**Comment by skeletonbow** [comment] 2020-08-02 15:45
Tested with x264 and can confirm a 15% spike in CPU usage during recording pause.

**Comment by RytoEX** [comment] 2020-10-23 04:57
@Gol-D-Ace and I were trying to reproduce this recently.  I was unable to reproduce on 26.0.2, but @Gol-D-Ace was able to reproduce on 26.0.2.  One of the only common elements I could see between the logs was that the affected systems all had 8GB of RAM, including one or two other logs that I examined.  This seems like it would be irrelevant, but it's the only thing that stood out to me.

@skeletonbow Can you still reproduce this and provide a log?

**Comment by pllovervoltage** [comment] 2020-10-24 13:49
@RytoEX funny you mentioned that because when my system also has 1x8gb. I recently upgraded to 16GB and didn't see the bug. I thought it was the latest update but perhaps it has to do with the ram?

**Comment by pllovervoltage** [comment] 2020-10-24 14:05
@RytoEX I recently upgraded 2200g system from 8GB to 16Gb and on latest obs version I still experience cpu bug.

**Comment by Gol-D-Ace** [comment] 2020-10-24 14:32
In case you are trying to reproduce this.
I need multiple tries to trigger this.

Usually I close OBS after an failed attempt and open it again.

So far I was able to reproduce this with x264 in simple (recording preset) and advanced mode.

R1CH does have the feeling it might be something related to Qt.

**Comment by flaeri** [comment] 2020-10-24 14:49
Tested with both 32gb and 8gb ram, also under 85+% usage of those 8gb of memory in use, and it did not seem to matter. Cant reproduce. i7-8700, win 2004, obs 26.2

**Comment by Gol-D-Ace** [comment] 2020-10-24 15:29
> @RytoEX I recently upgraded 2200g system from 8GB to 16Gb and on latest obs version I still experience cpu bug.

Can you reproduce this every try or do you need multiple attempts as well?

**Comment by pllovervoltage** [comment] 2020-10-24 17:49
@Gol-D-Ace I've been able to reproduce this consistently every time.

**Comment by Andrefty** [comment] 2021-03-15 15:19
I am having the same issue on a i5-8365U powered laptop.

**Comment by Orlean54** [comment] 2021-05-22 22:30
Am facing the same issue on windows. Without pausing cpu usage is around 8% whereas pausing and unpausing causes cpu usage to skyrocket to around +55% causing encoding overloads and it stays at a high usage until the recording is stopped.
Tried this in linux, didn't face this issue there.

**Comment by IMadering** [comment] 2021-05-27 11:12
I have this problem! OBS-Studio-27.0-rc6-Full-x64
Start record 13% CPU > Pause & Unpause > 13% CPU Pause & Unpause > 63% CPU!!!!
HELP!

**Comment by daltontf** [comment] 2021-09-22 13:50
Just experienced this on LinuxMint 20.2 running OBS Studio 27.0.1. Here is seems the second pause/unpause really pegs the CPU.

**Comment by DerHeimerdinger** [comment] 2022-01-25 10:09
2022 and problem still not fixed?

**Comment by PatTheMav** [comment] 2022-10-07 17:22
Wasn't able to reproduce this on macOS 12.5 with M1 Max and 32GB RAM, CPU usage went by half (if not more) when recording was paused.

Will test in my Windows VM later.

**Comment by pllovervoltage** [comment] 2022-10-08 01:00
I think key point in reproducing issue is using the cpu x264 encoder

**Comment by PatTheMav** [comment] 2022-10-08 07:47
> I think key point in reproducing issue is using the cpu x264 encoder

Well, I did use x264, which spawned 22 encoder threads. I remarked off-thread how that required me summing up each individual cpu time to get the actual time spent by the CPU encoding because otherwise the OpenGL renderer would have been the heaviest stack.

So I’m still unsure what the other necessary conditions are.

**Comment by RytoEX** [comment] 2022-10-13 23:10
I'm not seeing this on Windows 10 with OBS Studio 28.0.3. Please retest this on OBS Studio 28.0.3 (or newer). If this is still an issue, then we can consider reopening this or opening a new Issue.

**Comment by pllovervoltage** [comment] 2022-10-14 00:33
Updated to OBS studio 28.0.3. Still seeing issue of higher cpu usage after pausing.
Before
![before](https://user-images.githubusercontent.com/68091363/195735951-7a047b04-eb52-436d-84ea-aec11f462a5f.png)
After
![after](https://user-images.githubusercontent.com/68091363/195735955-181e7fdd-c741-4f05-b13b-6f0aeac0123e.png)

**Comment by RytoEX** [comment] 2022-10-14 01:28
> Updated to OBS studio 28.0.3. Still seeing issue of higher cpu usage after pausing.

Please provide a log file of a session where this occurs. Simply providing images gives us no extra context.

**Comment by pllovervoltage** [comment] 2022-10-14 05:03
I've included two logs in the initial post.

Here's an additional log in 28.0.3
https://obsproject.com/logs/IGo9R2ndjQmko8Y1

**Comment by RytoEX** [comment] 2022-10-14 05:58
> I've included two logs in the initial post.
> 
> Here's an additional log in 28.0.3 https://obsproject.com/logs/IGo9R2ndjQmko8Y1

New versions have new logging. It also helps us to see more context to what actions you took to produce the issue, what sources could possibly be related, as we have had little luck reproducing it on our end. Ideally, it would be most helpful to reproduce this with a completely empty scene collection, or one with just one source, to rule out as many factors as possible.

**Comment by pllovervoltage** [comment] 2022-10-14 07:16
Understood. I deleted my appdata folder to reset obs to default settings. Only setting I changed afterwards was setting encoder to x264. Problem repeated.

https://obsproject.com/logs/rTzHofwoZmv6rPk2

**Comment by Krydax** [comment] 2022-10-27 20:02
I am having this issue consistently (but strangely).

It seems to be a bit of a crapshoot based entirely on *when I open OBS*. 

Steps:

1. Open OBS (with admin privileges)
2. Start recording
3. pause
4. unpause
5. look at CPU usage. ITS HIGH
6. close OBS
7. open OBS (again with admin)
8. start recording
9. pause
10. unpause
11. look at CPU usage. Now it's normal?
12. repeat

It seems like OBS either has a good start or bad start. If it's a bad start, nothing I do (scene changes, even recording an empty blank scene, etc) will make the pause/unpause issue go away. If it's a GOOD start, then it just works, and keeps working normally, again even if I change scenes or do multiple recording start/stops etc.

Log from a bad start: https://obsproject.com/logs/7ft4zMT5VDF29NB8

another bad one: https://obsproject.com/logs/J-BUFccebObmqYnh

Log from a good start (no issue): https://obsproject.com/logs/0wWaSXVWgXMvnnZp

Hope this is helpful. It's a super weird issue. 

P.S.  I tried changing from NVENC H.264 to HEVC or x264 and the issue persisted. Also persisted whether I had something like CQP or CBR selected

**Comment by notr1ch** [comment] 2022-10-27 21:43
Have you checked your CPU frequencies when the issue happens? Perhaps the CPU downclocks when OBS is paused but doesn't feel the need to go to max frequency after unpausing?

**Comment by Krydax** [comment] 2022-10-27 23:14
> 

As far as I could tell, CPU didn't downclock at all (looking at resource monitor) while paused. GPU usage was about the same whether issue was happening or not.

**Comment by pllovervoltage** [comment] 2023-01-25 12:03
Issue no longer present in 29.0.0.

**Comment by Krydax** [comment] 2023-01-25 16:38
Issue is still present in 29.0.0 for me. Please do not close this :D

I have to play OBS roulette every time I want to record. I hit record, pause/unpause real quick, and if CPU usage shoots, up, close and open OBS again until it doesn't shoot up.

**Comment by Krydax** [comment] 2023-01-25 16:39
I even got a whole new mobo, CPU, and ram, and the issue is still present!

**Comment by jcyrss** [comment] 2023-08-02 01:25
I met the same issue here on Mac mini M1 with OBS 29.1.2

**Comment by ThaiCat** [comment] 2024-02-20 13:08
Still present in OBS 30.0.2

**Comment by Fenrirthviti** [comment] 2024-10-14 21:16
Since this issue is just being used as a catch-all for generic performance issues in OBS, and the original report is very outdated and unactionable, I am closing this.

Anyone experiencing performance issues should first go through our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance. If a specific set of reproduction steps for unintended high usage can be found, please open a new issue with those steps against the latest release of OBS.

**Closed by Fenrirthviti** 2024-10-14 21:16 UTC
Labels: Confirmed
