### ISSUE TITLE
Popup "Check for updates automatically" doesn't close on MacOS

### ISSUE THREAD

**Issue by raulcraveiro** [obsproject/obs-studio#5222] opened 2021-08-31 01:30 UTC
### Operating System Info

macOS 11.5

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/g5JcsRn1WT9Jdl7U

### Expected Behavior

On the popup "Check for updates automatically", when I click "Don't check" or "Check automatically" it should accept the option selected and close the popup.

### Current Behavior

The popup never closes, no matter the button that I press.

### Steps to Reproduce

1. Make sure the option to check updates when opening OBS is active;
2. Open OBS;
3. The popup should appear by itself

### Anything else we should know?

I'm using a Mac Mini with the M1 chip.

**Comment by WizardCM** [comment] 2021-08-31 01:31
Duplicate of #4904

**Closed by WizardCM** 2021-08-31 01:31 UTC
