### ISSUE TITLE
Support for VK_FORMAT_A2B10G10R10_UNORM_PACK32

### ISSUE THREAD

**Issue by dzimanAMD** [obsproject/obs-studio#2796] opened 2020-04-24 19:12 UTC
I have noticed that VK_FORMAT_A2B10G10R10_UNORM_PACK32 is not correctly supported and currently cast into DXGI_FORMAT_R10G10B10A2_UNORM. This will result in incorrectly captured colors because vkCmdCopyImage is being used.

See: https://github.com/obsproject/obs-studio/blob/b35c3a21f734e6c477f23406648662e416523fce/plugins/win-capture/graphics-hook/vulkan-capture.h#L490

https://github.com/obsproject/obs-studio/blob/b35c3a21f734e6c477f23406648662e416523fce/plugins/win-capture/graphics-hook/vulkan-capture.c#L915

I suggest switching from vkCmdCopyImage to vkCmdBlitImage to do conversion to a supported DXGI format.

**Comment by Fenrirthviti** [comment] 2020-04-26 06:44
Are you able to test this change and submit a PR for it? I don't think anyone on the team will have time to look at this for some time.

**Comment by jpark37** [comment] 2020-04-26 21:55
Did you mean VK_FORMAT_A2R10G10B10_UNORM_PACK32? VK_FORMAT_A2B10G10R10_UNORM_PACK32 seems to work fine when I hack up vkcube. VK_FORMAT_A2R10G10B10_UNORM_PACK32 produces reversed colors.

The hook currently hopes that the queue passed to vkQueuePresentKHR is capable of performing transfer operations, and we'd potentially need to add logic to submit and synchronize against a separate graphics queue to support vkCmdBlitImage. (I don't see any guarantee in the spec that transfer operations are always supported, but this hasn't bit us yet.)

Alternatively, we can remember that we need to swap channels, and do it in the shader when we render the game capture image.

**Comment by jpark37** [comment] 2020-04-26 22:20
We could also do nothing, and hope games don't pick jerk formats that don't exist in DX.

**Comment by WizardCM** [comment] 2020-08-26 01:14
Per the above & the linked PR that was merged, closing this as By Design / Won't Fix. If it becomes necesarry in the future, we can revisit it.

**Closed by WizardCM** 2020-08-26 01:14 UTC
