### ISSUE TITLE
XRGB for video format of video capture device should be rgb24 not rgb32

### ISSUE THREAD

**Issue by EtherealAO** [obsproject/obs-studio#6270] opened 2022-04-03 22:44 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/w0ED97cqgoWFPwvy

### Expected Behavior

XRGB should be rgb24 not rgb32, or give an alternative. Most 4k60 capture cards were PCIe 2.0 x4 (according to https://obsproject.com/forum/resources/capture-card-documentation-latency-decode-modes-formats-more.777/), which doesn't have enough bandwidth to perform 4k60 rgb32 capture.

### Current Behavior

Using XRGB@4K60 on PCIe 2.0 x4 capture card(like AverMedia GC573) causes an obvious FPS drop. Using XRGB@2K60 or NV12@4K60 works fine, so I guess the problem is XRGB.

### Steps to Reproduce

1.Add a video capture device
2.Set video format to XRGB and resolution to 3840x2160 and FPS to 60
3.Felling the FPS drop
...

**Comment by derrod** [comment] 2022-04-03 22:49
Duplicate of #4176, but it sounds like an issue with your setup, since XRGB should fall back to RGB24 if the directshow device doesn't support RGB32. And most people don't have issues with the GC573 at 4K60 unless the PCIe bandwidth is bottlenecked somewhere.

**Closed by derrod** 2022-04-03 22:49 UTC

**Comment by EtherealAO** [comment] 2022-04-04 10:31
![@N11W5SBRN`U_5RY}I75T)4](https://user-images.githubusercontent.com/28262778/161525175-693d608f-4cc4-42cf-8737-08f2d8122f61.png)
Setup was fine as Recentral works normally, and this problem only happens when using 4K 60FPS XRGB together.
I wonder if it's possible to give an option to force use RGB24 instead of trying RGB32 first.
