### ISSUE TITLE
WHIP crash

### ISSUE THREAD

**Issue by ArdariaWorld** [obsproject/obs-studio#9909] opened 2023-11-23 12:22 UTC
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/5sxgvTJOdKZwobKo

### Expected Behavior

I click on "Start Streaming" -> the stream starts

### Current Behavior

I click on "Start Streaming" -> OBS crashes

### Steps to Reproduce

1. Install OBS from Flatpak
2. Start a stream
3.
...

### Anything else we should know?

I have OBS 30 installed on my machine (.deb package) and both OBS 30 flatpak.
I realised after not finding WHIP that I needed to install from flatpak.
Stream with standard Twitch service works well.

**Comment by tytan652** [comment] 2023-11-23 12:22
Duplicate of #9846

**Closed by tytan652** 2023-11-23 12:22 UTC
