### ISSUE TITLE
[BUG] Applying Image Mask to a group instead of source results in quality loss

### ISSUE THREAD

**Issue by owlmostdead** [obsproject/obs-studio#2873] opened 2020-05-06 14:27 UTC
## Platform

Operating system and version: Windows 10 Pro 1909 Build 18363.815
OBS Studio version: 25.0.8

## Expected Behavior
 Applying Image Mask to Group should not change quality of source

## Current Behavior
 Applying an Image Mask to Group instead of source results in noticeable quality loss
 

## Steps to Reproduce

 Here an example of the quality loss https://youtu.be/VzLBhbLr3GY although it is not as noticeable due to YouTube's compression 
1. Group 1 Source into own Group
2. Apply Image Mask to Group 
3. Noticeable quality loss

## Additional information
Applying the same Image Mask directly to the Source results in no quality loss, which makes me believe this is a bug.
 It seems that also applying a cropping filter to group leads to quality loss

**Comment by WizardCM** [comment] 2020-10-03 07:32
This sounds like a duplicate of #2852 - can you confirm that's the issue you're seeing?

**Comment by owlmostdead** [comment] 2020-10-10 18:49
It could be the same issue I am seeing although on my end it just looks like the resolution gets lower/worse rather then grey pixels being added. Even if it's not the same issue I think it definitely relates to #2852 in some way.

**Comment by WizardCM** [comment] 2020-12-09 10:02
Alright. I'll close this for now.

Duplicate of #2852.

**Closed by WizardCM** 2020-12-09 10:02 UTC
