### ISSUE TITLE
UI rendering glitches on Fedora 38 DNF package + GNOME Wayland + fractional scaling

### ISSUE THREAD

**Issue by snoopdouglas** [obsproject/obs-studio#9004] opened 2023-06-01 22:50 UTC
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/SNzwOAzcEDFgvssT

### Expected Behavior

The UI renders correctly.

### Current Behavior

The UI renders with glitches; the mouse hitbox for buttons and the top menu is off by half, buttons which were previously hovered still show their hover state, and there are various rendering errors which make the UI see-through:

![Screenshot from 2023-06-01 23-42-23](https://github.com/obsproject/obs-studio/assets/4892574/52ad5ab1-8a82-4cf8-b481-eb7fec8c1d79)

### Steps to Reproduce

1. On Fedora 38, install `obs-studio`
2. Use GNOME on Wayland
3. Fire up OBS.

### Anything else we should know?

Apologies if this is a Qt problem rather than an OBS one! Other Qt apps *seem* to be okay on my system though

**Comment by RytoEX** [comment] 2023-06-01 22:55
Duplicate of #8910 ?

**Comment by snoopdouglas** [comment] 2023-06-01 23:01
Hmm- I've just tested the Flatpak and that works fine.

**Comment by kkartaltepe** [comment] 2023-06-02 02:17
> Duplicate of #8910 ?

Looks like it. Feel free to add any additional info there. Like a log from what "works fine".

**Closed by kkartaltepe** 2023-06-02 02:17 UTC

**Comment by snoopdouglas** [comment] 2023-06-02 07:51
Sure, Flatpak logs are here: https://obsproject.com/logs/ynevOLiWwDEQIC7C

Screenshot of the Flatpak running, all looks well:

![image](https://github.com/obsproject/obs-studio/assets/4892574/db051959-57a9-4155-9605-1bdbaec37b22)

**Comment by RytoEX** [comment] 2023-06-06 18:19
Duplicate of #8910
