### ISSUE TITLE
OBS26 can't stop streaming when address is srt://192.168.10.11:10000.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#3522] opened 2020-09-30 07:32 UTC
## Platform

Operating system and version: win10 1809_x64
OBS Studio version: 26.0

## Steps to Reproduce

1. inputting the localhost address srt://192.168.10.11:10000 or srt://192.168.10.11:10000?mode=listener
2. start streaming
3. and then it can't stop
4. forcing quit obs, however, it still remain in the background of system.

**Comment by Fenrirthviti** [comment] 2020-09-30 16:41
Duplicate of #3519

**Closed by Fenrirthviti** 2020-09-30 16:41 UTC
