### ISSUE TITLE
Hotkeys stop working in version 29

### ISSUE THREAD

**Issue by ChloeoeoeZ** [obsproject/obs-studio#8287] opened 2023-02-18 01:39 UTC
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/t1k7FuyX9cE1B7lH

### Expected Behavior

I expect hotkeys to respond normally.

### Current Behavior

When OBS is first launched, hotkeys work normally. When I click on a scene to change it with my mouse, the hotkeys stop responding. When I click somewhere else other than a scene, the hotkeys start working again. Hotkey Focus Behaviour is set to "Never Disable Hotkeys". 

### Steps to Reproduce

1. Launch OBS
2. Use Hotkeys normally
3. Select a scene with the mouse
4. Hotkeys stop working
...

### Anything else we should know?

This was also happening for me in the earlier versions of OBS 29
I don't have this issue in OBS 28.1.2 and below.

**Comment by gxalpha** [comment] 2023-04-13 19:42
Which hotkeys were you using? As in, which keys did you set?

**Comment by gac1990** [comment] 2023-05-02 08:13
I am experiencing this as well, it's causing me major problems with my production.

**Comment by ChloeoeoeZ** [comment] 2023-05-03 05:02
@gxalpha I’m using mostly function keys.

**Comment by gxalpha** [comment] 2023-05-11 20:03
We unfortunately cannot reproduce this on our side.
Please try using OBS 29.1.1. If it also happens there, please specify which hotkeys you're using to trigger which actions, and which of them stop working.

**Comment by ChloeoeoeZ** [comment] 2023-05-11 22:23
@gxalpha I just updated from OBS 28.1.2 to 29.1.1 and the issue is resolved for me.

**Comment by gxalpha** [comment] 2023-05-11 22:31
Great! I'm going to close this issue then as it appears to be fixed.

**Closed by gxalpha** 2023-05-11 22:31 UTC
