### ISSUE TITLE
In Flatpak FFMPEG VAAPI H.264 Encoder Fails To Start Recording

### ISSUE THREAD

**Issue by BrodieRobertson** [obsproject/obs-studio#8001] opened 2023-01-03 06:22 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/4wa8Qs4voymK2r8Y

### Expected Behavior

Recording/streaming to begin upon clicking the start recording/streaming button

### Current Behavior

Upon pressing the record button I am presented with this pop up

![2023-01-03_16-48](https://user-images.githubusercontent.com/30792656/210308250-add16b70-c28f-4e8f-8e9c-84e79440837e.png)

### Steps to Reproduce

1. Press start record/stream
2. Problem occurs

### Anything else we should know?

My drivers and flatpaks are fully up to date, if I use the non flatpak version in my distro repo the problem does not occur.

This is just a guess but it seems as if the version of VAAPI that the OBS Flatpak is looking for is older than what is available to the flatpak.

```
flatpak run org.freedesktop.Platform.VaInfo

Trying display: wayland
Trying display: x11
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.16.0)
vainfo: Driver version: Mesa Gallium driver 22.2.4 for AMD Radeon RX 6750 XT (navi22, LLVM 14.0.6, DRM 3.49, 6.1.2-arch1-1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

From the terminal output of the OBS Flatpak
```
[AVHWDeviceContext @ 0x5568e0616c40] libva: /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x5568e0616c40] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

**Comment by kkartaltepe** [comment] 2023-01-03 06:31
duplicate of #7956

**Closed by kkartaltepe** 2023-01-03 06:32 UTC
