### ISSUE TITLE
Amd h.264 encoder lags like crazy in the newest obs update

### ISSUE THREAD

**Issue by Welpyes** [obsproject/obs-studio#10435] opened 2024-03-26 13:39 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/Zuzcb9yxeBGQl6Ke

### Expected Behavior

recording is smooth and at a constant frame rate

https://drive.google.com/file/d/1xBkVJWcNGU99rfDmyoFJWnDrAecXGj3h/view?usp=drive_link

### Current Behavior

recording is laggy and looks like a slideshow

https://drive.google.com/file/d/1PrcnjeQUd7fcd9NsPaLBj05PKVEwgd76/view?usp=sharing

### Steps to Reproduce

1.have an gpu or an igpu that is a radeon r7 
2.download the latest obs
3.record with amd h.264 
...

### Anything else we should know?

i recommend downloading the clips
and playing it locally

**Comment by derrod** [comment] 2024-03-26 13:48
Duplicate of #10368, disable b-frames. Unfortunately some older AMD hardware reports that they are supported when they very much are not.

**Closed by derrod** 2024-03-26 13:48 UTC
