### ISSUE TITLE
OSX catalina browser "interact" out of focus

### ISSUE THREAD

**Issue by beaug** [obsproject/obs-studio#3264] opened 2020-08-09 07:24 UTC
The mouse in interact mode is referencing the incorrect part of the screen. 

Video here showing it https://youtu.be/lxIl-rKXqv0

You can see I am moving the mouse well below the menu but OBS thinks that I'm moving directly along the menu buttons

Changing the resolution to the same resolution of my screen just changed where OBS thought the mouse was. 

End of log

17:06:38.676: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
17:06:38.676:
17:06:38.676: ==== Startup complete ===============================================
17:06:38.694: Service '' not found
17:06:38.697: All scene data cleared
17:06:38.697: ------------------------------------------------
17:06:39.382: coreaudio: device 'Display Audio' initialized
17:06:39.383: [Loaded global audio device]: 'Mic/Aux'
17:06:39.417: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
17:06:39.417:
17:06:39.427: Switched to scene 'Browser Only'
17:06:39.427: ------------------------------------------------
17:06:39.427: Loaded scenes:
17:06:39.427: - scene 'Scene':
17:06:39.427: - source: 'Display Capture' (display_capture)
17:06:39.427: - scene 'Browser Only':
17:06:39.427: - source: 'Browser' (browser_source)
17:06:39.427: ------------------------------------------------

**Comment by WizardCM** [comment] 2020-08-09 07:31
This is a duplicate of https://github.com/obsproject/obs-browser/issues/99

**Closed by WizardCM** 2020-08-09 07:31 UTC
