### ISSUE TITLE
Crash after install new font on closing application

### ISSUE THREAD

**Issue by elmakong** [obsproject/obs-studio#3170] opened 2020-07-16 00:24 UTC
## Platform
Operating system and version: Windows 10 (1909 build 18363.959)
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior
Application closes gracefully

## Current Behavior
Application showing crash alert when closed after installing new font

## Steps to Reproduce
1. start OBS Studio, use as usual
2. adding new sources (Text GDI+)
3. install new font to windows (any font will do)
4. check font selection in OBS, new font not found
5. attempt to close OBS

## Additional information
i believe this is another issue, but adding new sources doesnt directly shown up on the list. must change scenes and go back.

**Comment by Fenrirthviti** [comment] 2020-07-16 00:26
Please provide the crash log.

**Comment by elmakong** [comment] 2020-07-16 01:24
[Crash 2020-07-15 20-55-59.txt](https://github.com/obsproject/obs-studio/files/4928790/Crash.2020-07-15.20-55-59.txt)
here you go

**Comment by WizardCM** [comment] 2020-08-28 01:44
This crash is caused by the same issue as #3310 - closing this one to keep dicussion in a single location.

**Closed by WizardCM** 2020-08-28 01:44 UTC
