### ISSUE TITLE
Crashed multiple times today while streaming

### ISSUE THREAD

**Issue by Battousai-IBIF** [obsproject/obs-studio#5768] opened 2022-01-10 03:17 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 2

### OBS Studio Log URL

https://obsproject.com/logs/KQAIp8qitQIGRZct

### OBS Studio Crash Log URL

https://obsproject.com/logs/hEtup7H0X5xQslUl

### Expected Behavior

Expected steady and stable streaming

### Current Behavior

Computer completely locked up and had to be hard reset.  After restarting, OBS crashed multiple times.

### Steps to Reproduce

I'm not certain exactly what triggered it, but the first crash coincided with running a browser source for Twitch Guru.

**Comment by Fenrirthviti** [comment] 2022-01-10 03:18
Please provide the crash log as well.

**Comment by Battousai-IBIF** [comment] 2022-01-10 17:03
> Please provide the crash log as well.

Crash log URL is in there

**Comment by Fenrirthviti** [comment] 2022-01-10 17:08
Your system is simply running out of memory. I would recommend closing any unnecessary applications and attempting to reduce overall system memory usage. There is not really much we can do on our end as this is not a bug, but if you need further troubleshooting assistance, please use our Forums or Discord.

https://obsproject.com/help

**Closed by Fenrirthviti** 2022-01-10 17:08 UTC

**Comment by Battousai-IBIF** [comment] 2022-01-10 17:12
> Your system is simply running out of memory. I would recommend closing any unnecessary applications and attempting to reduce overall system memory usage. There is not really much we can do on our end as this is not a bug, but if you need further troubleshooting assistance, please use our Forums or Discord.
> 
> https://obsproject.com/help

Thanks for looking into that.  I do find it strange that it says it was running out of memory though, I have 48GB of RAM installed and never peaked over 50% in resource monitoring.
