### ISSUE TITLE
restoring obs from tray makes preview area hollow on wayland

### ISSUE THREAD

**Issue by Kazimazi** [obsproject/obs-studio#4007] opened 2021-01-03 12:04 UTC
## Platform

Operating system and version: Linux 5.10.3 NixOS 21.03.20201229.733e537
OBS Studio version: 69a80066e358a752aea94a59dcf4a10d915420a3
I'm using swaywm.
Installed via nix package manager, from [this overlay](https://github.com/colemickens/nixpkgs-wayland).
You would have to install flake enabled version of nix and run `nix shell "github:colemickens/nixpkgs-wayland#obs-studio" --command obs` to start the same [wayland-fixed up](https://github.com/obsproject/obs-studio/pull/2484) obs as I did, or install it some other way.
I have some plugins installed too which are not relevant to this issue.

## Current Behavior
Preview area becomes hollow upon restoring it from tray bar and I can see my wallpaper through it.
The error I'm getting in the [log](https://gist.github.com/Kazimazi/acf3ce1d06b4671a3f86b94abad260e3): `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

![20210103_12h54m52s_grim](https://user-images.githubusercontent.com/5616737/103477979-081d5180-4dc4-11eb-8535-98a20a4129bb.png)

## Steps to Reproduce

1. Click on tray icon to hide window.
2. Click on it again to show window.

**Comment by dodgepong** [comment] 2021-01-03 15:15
You skipped the part of the issue template that asks how you installed OBS -- did you build from source, or use some sort of package?

**Comment by Kazimazi** [comment] 2021-01-04 03:05
Edited original issue accordingly.

**Comment by WizardCM** [comment] 2021-01-04 03:08
As the issue is with a fork & branch that has not been merged, it'd probably be better to post this issue as a comment on the Wayland PR, as OBS doesn't officially support Wayland at the moment.

**Closed by WizardCM** 2021-01-04 03:08 UTC
