### ISSUE TITLE
SRT: OBS unusable and uncloseable after starting stream to invalid srt server

### ISSUE THREAD

**Issue by basisbit** [obsproject/obs-studio#5791] opened 2022-01-13 20:06 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/i0MmL1JbOIWU7u7x

### Expected Behavior

- OBS should not show that it connected successful when the srt stream server URL is invalid, but instead show the usual stream error message
- User should be able to stop streaming and later be able to start streaming again after correcting the srt server url
- User should be able to close OBS

### Current Behavior

- OBS shows that it connected successfully, stream bitrate counter stays at 0b/s. After some time it shows the `OBS Studio: Disconnected. Reconnecting ...` notification.
- Pressing the `Stop streaming` button only makes its text change to `Stopping Stream...` and then OBS is unusable for any further streaming.
- OBS then can not be closed any more. Or rather, if you press the close button or File -> Exit the window disappears but the obs.exe process stays open infinitely until manually killed using Task Manager or restarting the computer
- Dropped Frame counter seems to be not working at all when using SRT, and `Dynimaically change bitrate to manage congestion (Beta)` also does not work when using srt. (However, srt support seems to be rather new in OBS so far and SRT already handles packet loss very well, so those two features are absolutely low priority imho.)

![image](https://user-images.githubusercontent.com/10870269/149400185-40a1e784-e904-4976-9825-6cbe978e6351.png)

### Steps to Reproduce

1. Set Settings -> Stream -> Server to `srt://google.com:443/this/is/not/a/srt/server?latency=500000`
2. Set Settings -> Advanced -> `Automatically Reconnect` to Enabled with Retry Delay `10s`.
2. Close settings. Start streaming. Watch OBS for 30 seconds.
3. Press the `Stop streaming` button, then wait 30 seconds.
4. Close OBS, wait 30 seconds, then open Task Manager and check in the Details/Processes tab to see OBS still being run.

### Anything else we should know?

Streaming using SRT is infinitely more reliable than using rtmp, especially when network congestion happens on some peerings between the streamer and the ingest server, or when short bursts of packet loss happen for example on LTE/5G or Wifi/WLAN or Docsis based shared last mile. OBS adding SRT support some time in 2020 (afaik) meant a huge improvement in reliability when using self-hosted or small video streaming distribution services which don't have ingest servers in every country close to the user. Thank you so much for adding it!

**Comment by pkviet** [comment] 2022-01-13 20:40
we're aware; I had written several possible fixes.
The issue is a bit complex because there's an interference from the auto-reconnect mechanism.
In order to avoid this issue, for now disable auto-reconnect in Settings > Advanced.
I had written a temptative fix which stops the auto-reconnects if there's a failed connection. But if the failure is from some temporary dns issue, some people would prefer to reconnect.
I'll rediscuss this with other devs to see if we can find some fix.

**Comment by basisbit** [comment] 2022-01-13 21:12
Thank you for the quick response! Until there is a permanent solution, please consider automatically temporarely disabling auto-reconnect for srt based streams (and maybe show popup warning) after starting the stream.

**Comment by pkviet** [comment] 2022-01-25 13:54
There's info also in this now closed PR: https://github.com/obsproject/obs-studio/pull/5752

**Comment by basisbit** [comment] 2022-04-18 22:47
Any update on this? From my experience, SRT is a major requirement if you want to do affordable and reliable video streaming with OBS over the public internet. This bug here shows severe problems in how SRT support is integrated in OBS and no one seems to work on this? What do others use instead of SRT, when they need good reliability across networks with congested peerings / transit between autonomous systems or when streaming over shitty internet connections of hotels for events and so on?

**Comment by pkviet** [comment] 2022-04-20 10:59
Well, the simplest workaround is to disable auto reconnect in Advanced Settings.
The problem has no easy fix. I offered a solution (see the pr i linked above) but the conundrum is about treating correctly connection errors due to temporary DNS issues.
People in that situation will want to be able to have auto reconnect.
If you'd prefer instead the connection to fail, you have to disable auto reconnect. Or a middle ground could be to decrease the number of attempts to reconnect
I bring to your attention rist which is an excellent alternative to srt & is supported by obs.
A better support of srt and rist is forthcoming, pending the merging of a recent PR i submitted.
The fact that the uri is unreachable will be logged so it'll be easier to find out if one mistyped the uri.

**Comment by basisbit** [comment] 2022-04-20 11:08
@pkviet just a reminder that this here issue is not just about the connection-failure handling. The issue description mentions a couple of problems that are not addressed by the linked pull requests.

**Comment by basisbit** [comment] 2022-04-20 11:21
I just saw #6134 and assume that this PR also improves error handling, would allow for monitoring lost frames, would allow for easier fixing of the thread / memory / ffmpeg instance leaks and thus should allow fixing this here bug-issue?

**Comment by pkviet** [comment] 2022-04-20 11:24
yeah this should fix the errors mentioned in the issue + monitoring lost frames since stats are logged. It doesn't use ffmpeg to handle protocol but our own implementation so it'll be a big improvement with the proviso that it won't be available before v28 in a few months. There will be test builds much earlier though but their existence rely on another PR w/ obs-deps to be merged as a pre-requisite.

**Comment by mariozubac** [comment] 2022-04-25 13:46
Beside the described error, OBS srt can only serve one client. Is there a way of configuring this so it acks as a server? mode=listener.

**Comment by basisbit** [comment] 2022-05-13 13:41
@mariozubac have you tried specifying it as parameter as part of the srt URL (url-encoded)?

**Comment by basisbit** [comment] 2022-06-10 17:45
@pkviet thank you so much for this update and for working on this!! 🚀

**Closed** 2022-07-30 15:27 UTC
Labels: Fix available, Confirmed
