### ISSUE TITLE
OBS gets confused when webcam is added or removed to system

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#4595] opened 2021-04-25 08:43 UTC
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

26.1.1

### OBS Studio Log URL

I do not understand what that means

### Expected Behavior

The presence of a new webcam should not cause any disturbance.

The removal of a webcam not actually linked to a video source should not cause disturbance.

The removal of a webcam used by a video source in OBS should cause it to be grayed out or a warning to be displayed or the source just providing any image, without impacting other video sources.

### Current Behavior

The association of video sources to webcam gets shuffled : a source will get a different webcam stream, or a source will be in an ill-configured state.
It is not really possible to correct this live, one has to close OBS again and restart it.

### Steps to Reproduce

1. Create a scene with several video sources.
2. Select appropriate webcam for each video source.
3. Close OBS.
4. Add or remove a webcam (either a USB webcam or a virtual webcam).
5. Open OBS again.

### Anything else we should know?

Here are logs after removing a camera that was used by a video.
[With problem ocurring](https://github.com/obsproject/obs-studio/files/6371551/2021-04-25.10-05-00.txt)
[After selected the camera I want for the main video source and restarting OBS](https://github.com/obsproject/obs-studio/files/6371556/2021-04-25.10-06-00.txt)

The problem seems to be caused by the fact that although the GUI shows camera device names, the setting appears to be recorded as ``/dev/videoX`` with the number being dependent on whether there are other cameras on the system.

**Comment by gxalpha** [comment] 2022-11-16 20:44
Duplicate of #3003

**Closed by gxalpha** 2022-11-16 20:44 UTC
Labels: Linux
