### ISSUE TITLE
Streaming to udp://224.0.0.1 no longer works, cannot connect error.

### ISSUE THREAD

**Issue by evs248** [obsproject/obs-studio#3629] opened 2020-10-18 07:21 UTC
Platform
Operating system and version: Windows 10
OBS Studio version: 26.0.2

Expected Behavior
Streaming to udp://<address> with mpegts should work.

Current Behavior
25.0.8 works.
26.0.2 does not.

Error message is along the lines of "av_interleaved_write_frame failed: Invalid data found when processing input [megts 2 <memory adddress>] H.264 bitstream malformed, no startcode found, use the video bitstream filter "h264_mp4toannexb' to fix it (-bsf:v h264_mp4toannexb' option within ffmpeg"

![2020-10-18-175702_894x661_scrot](https://user-images.githubusercontent.com/66814315/96360942-3d26ea00-116d-11eb-98c0-8cd33a58514a.png)

Steps to Reproduce
Set stream link to udp://224.0.0.1:2000
Click start stream

**Comment by WizardCM** [comment] 2020-10-18 07:23
Please fill in the issue template, and provide a full log from the session where this occurred.

**Comment by evs248** [comment] 2020-10-18 07:34
Thanks.
When browsing to another issue I found some headings.


log files, for 25.0.8 an 26.0.2
[2020-10-18 18-06-54.txt](https://github.com/obsproject/obs-studio/files/5397169/2020-10-18.18-06-54.txt)
[2020-10-18 17-54-36.txt](https://github.com/obsproject/obs-studio/files/5397170/2020-10-18.17-54-36.txt)

**Comment by Fenrirthviti** [comment] 2020-10-18 22:58
Duplicate of #3588

**Closed by Fenrirthviti** 2020-10-18 22:58 UTC
