### ISSUE TITLE
Memory leak when streaming or recording with QSV on Ice Lake

### ISSUE THREAD

**Issue by michielgardner** [obsproject/obs-studio#5257] opened 2021-09-08 12:14 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/IFU9L09FGec7t3rM

### Expected Behavior

When streaming or recording with QSV the memory usage should stay the same

### Current Behavior

When streaming or recording with QSV the memory usage keeps growing forever

### Steps to Reproduce

1. Install OBS
2. Choose QSV for streaming or recording
3. Start streaming or recording

### Anything else we should know?

I tried upgrading the GPU driver to latest Intel DCH driver, but it didn't solve the problem.

Things that do solve the problem:

- Use x264 instead of QSV
- Use 'Rescale Output' (even if it's set to the output resolution)
- Use I420 color format instead of NV12
- Use OBS 25.0.8

On my Coffee Lake machine everything works fine and I don't have to do any of these things.

The difference in the logs between my Coffee Lake machine and my Ice Lake machine:

My Ice Lake machine has: 

`NV12 texture support enabled`

And my Coffee Lake machine has:

`NV12 texture support not available`

**Comment by invertego** [comment] 2021-11-09 10:24
Looks like a duplicate of #4777, but the extra details in this report are illuminating. They point strongly to change #1786 being at fault, consistent with the following observations:
1. Changing the format away from NV12 or enabling 'Rescale Output'  will opt out of the behavior introduced by this change, as seen here: https://github.com/obsproject/obs-studio/blob/c36a5ae92b32d7b8401c468c7f20fabeb05d775f/plugins/obs-qsv11/obs-qsv11.c#L743-L753
2. This change first appeared in OBS 26.0, so it would not be present in 25.0.8

**Comment by yaoxinshi-intel** [comment] 2022-01-24 03:13
The issue should be solved by this PR: https://github.com/obsproject/obs-studio/pull/5829

**Comment by WizardCM** [comment] 2022-02-12 23:42
Should be fixed by #5829. Please test in 27.2 and let us know if it's not fixed.

**Closed by WizardCM** 2022-02-12 23:42 UTC
