### ISSUE TITLE
OBS v30.0.1 for Mac Silicon crashes after fresh install.

### ISSUE THREAD

**Issue by jeffschwartz** [obsproject/obs-studio#9986] opened 2023-12-10 16:51 UTC
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

na

### OBS Studio Crash Log URL

na

### Expected Behavior

Expected OBS v30.0.1 not to crash on Apple Mac M1 after installing it.

### Current Behavior

Crashed after launching 1st time after installation.

### Steps to Reproduce

1. Install OBS v30.0.1 on M1 Mac
2. Launch App
3.
...

### Anything else we should know?

Here's the crash report generated by Mac OS:
[OBS Studio-2023-12-10-112907.ips.zip](https://github.com/obsproject/obs-studio/files/13628564/OBS.Studio-2023-12-10-112907.ips.zip)

**Comment by tytan652** [comment] 2023-12-10 16:52
Duplicate of #9985

**Comment by JohnyRingo68** [comment] 2023-12-10 19:22
I concure, same issue here on M1 Mac OS 12.7.1. Immediate crash after launch

**Comment by glenru** [comment] 2023-12-10 19:56
Same issue here on M1 Mac OS 14.2 Immediate crash after launch

**Comment by gxalpha** [comment] 2023-12-10 20:27
We're working on deploying a fix as soon as possible.
In the meantime, please revert to [30.0.0](https://github.com/obsproject/obs-studio/releases/tag/30.0.0).

**Comment by gxalpha** [comment] 2023-12-10 22:44
We have released OBS 30.0.2 which fixes this problem. Go to https://obsproject.com/download to download 30.0.2 if you're having 30.0.1 and can't auto-update through the app.

**Closed by gxalpha** 2023-12-10 22:44 UTC

**Comment by jeffschwartz** [comment] 2023-12-11 02:23
That’s awesome and thank you :)
