### ISSUE TITLE
Display Capture black when starting OBS on macOS Big Sur

### ISSUE THREAD

**Issue by heckseven** [obsproject/obs-studio#4050] opened 2021-01-12 04:31 UTC
When starting OBS, the Display Capture fails and shows a black screen. If I add a new Display Capture, it works as expected until I close and reopen OBS. It seems others are https://obsproject.com/forum/threads/macos-bigsur-beta-20b5022a-display-capture-always-stops-working-after-restarting-obs-and-must-be-readded.133391/.

## Platform

Operating system and version: macOS Big Sur 11.1
OBS Studio version: 26.1.2

## Expected Behavior

When I open OBS, the Display Capture should capture the display.

## Current Behavior

When I open OBS, the Display Capture is black and reports the device is not connected.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/54460388/104269220-fdf9f380-5452-11eb-8efc-376aa568a837.png">

When I remove and re-add the Display Capture, it works as expected. Until I close and reopen OBS.

Current log:
```
21:20:17.261: CPU Name: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
21:20:17.261: CPU Speed: 2400MHz
21:20:17.261: Physical Cores: 8, Logical Cores: 16
21:20:17.261: Physical Memory: 32768MB Total
21:20:17.261: OS Name: Mac OS X (NSMACHOperatingSystem)
21:20:17.261: OS Version: Version 11.1 (Build 20C69)
21:20:17.261: Kernel Version: 20.2.0
21:20:17.271: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
21:20:17.272: Current Date/Time: 2021-01-11, 21:20:17
21:20:17.272: Browser Hardware Acceleration: true
21:20:17.272: Portable mode: false
21:20:17.358: OBS 26.1.2 (mac)
21:20:17.358: ---------------------------------
21:20:17.359: ---------------------------------
21:20:17.359: audio settings reset:
21:20:17.359: 	samples per sec: 44100
21:20:17.359: 	speakers:        2
21:20:17.360: ---------------------------------
21:20:17.360: Initializing OpenGL...
21:20:18.873: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 5500M OpenGL Engine
21:20:18.873: OpenGL loaded successfully, version 4.1 ATI-4.2.13, shading language 4.10
21:20:18.944: ---------------------------------
21:20:18.944: video settings reset:
21:20:18.944: 	base resolution:   1920x1080
21:20:18.944: 	output resolution: 1920x1080
21:20:18.944: 	downscale filter:  Bicubic
21:20:18.944: 	fps:               30/1
21:20:18.944: 	format:            NV12
21:20:18.944: 	YUV mode:          709/Partial
21:20:18.945: NV12 texture support not available
21:20:18.945: Audio monitoring device:
21:20:18.945: 	name: Default
21:20:18.945: 	id: default
21:20:18.945: ---------------------------------
21:20:18.947: Failed to load 'en-US' text for module: 'decklink-captions.so'
21:20:18.948: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
21:20:19.028: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:20:19.028: No blackmagic support
21:20:19.031: [mac-virtualcam] version=1.3.0
21:20:19.100: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
21:20:19.103: [obs-browser]: Version 2.10.0
21:20:19.103: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
21:20:19.132: VLC found, VLC video source enabled
21:20:19.133: Failed to load 'en-US' text for module: 'obs-mac-virtualcam.so'
21:20:19.133: [obs-mac-virtualcam] version=1.2.1
21:20:19.134: obs_register_output: Output id 'virtualcam_output' already exists!  Duplicate library?
21:20:19.135: [obs-ndi] hello ! (version 4.9.0)
21:20:19.135: [obs-ndi] Trying ''
21:20:19.135: [obs-ndi] Trying '/usr/lib'
21:20:19.135: [obs-ndi] Trying '/usr/local/lib'
21:20:19.135: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.4.dylib'
21:20:19.136: [obs-ndi] NDI runtime loaded successfully
21:20:19.137: [obs-ndi] NDI library initialized successfully (NDI SDK APPLE 11:50:41 Apr  1 2020 4.5.1)
21:20:19.138: ---------------------------------
21:20:19.138:   Loaded Modules:
21:20:19.138:     obs-ndi.so
21:20:19.138:     obs-mac-virtualcam.so
21:20:19.138:     vlc-video.so
21:20:19.138:     text-freetype2.so
21:20:19.139:     rtmp-services.so
21:20:19.139:     obs-x264.so
21:20:19.139:     obs-vst.so
21:20:19.139:     obs-transitions.so
21:20:19.139:     obs-outputs.so
21:20:19.139:     obs-filters.so
21:20:19.139:     obs-ffmpeg.so
21:20:19.139:     obs-browser.so
21:20:19.139:     mac-vth264.so
21:20:19.139:     mac-virtualcam.so
21:20:19.139:     mac-syphon.so
21:20:19.139:     mac-decklink.so
21:20:19.139:     mac-capture.so
21:20:19.139:     mac-avcapture.so
21:20:19.139:     image-source.so
21:20:19.139:     frontend-tools.so
21:20:19.139:     decklink-ouput-ui.so
21:20:19.139:     decklink-captions.so
21:20:19.139:     coreaudio-encoder.so
21:20:19.139: ---------------------------------
21:20:19.139: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
21:20:19.139: 
21:20:19.139: ==== Startup complete ===============================================
21:20:19.156: All scene data cleared
21:20:19.156: ------------------------------------------------
21:20:19.290: coreaudio: device 'MacBook Pro Microphone' initialized
21:20:19.290: [Loaded global audio device]: 'Mic/Aux'
21:20:19.301: coreaudio: device 'Loopback' initialized
21:20:19.330: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds (source: Loopback)
21:20:19.330: 
21:20:19.347: MBP camera: Selected device 'FaceTime HD Camera (Built-in)'
21:20:19.350: MBP camera: Using preset 1280x720
21:20:19.419: coreaudio: failed to find device uid: AppleUSBAudioEngine:Blackmagic Design:Blackmagic Design:d9b85d1350bf49e798af0e44908eace8:7, waiting for connection
21:20:19.420: ATEM video: Could not initialize device with unique ID '0x144000001edbbe49'
21:20:19.420: C920 video: Could not initialize device with unique ID '0x14344000046d0892'
21:20:19.423: coreaudio: failed to find device uid: AppleUSBAudioEngine:Unknown Manufacturer:HD Pro Webcam C920:371593EF:3, waiting for connection
21:20:19.427: coreaudio: device 'MacBook Pro Microphone' initialized
21:20:19.448: Failed to create source 'Display Capture'!
21:20:19.448: Switched to scene 'desktop'
21:20:19.449: ------------------------------------------------
21:20:19.449: Loaded scenes:
21:20:19.449: - scene 'ATEM':
21:20:19.449:     - source: 'ATEM video' (av_capture_input)
21:20:19.449:     - source: 'ATEM audio' (coreaudio_input_capture)
21:20:19.449: - scene 'ATEM && heckseven':
21:20:19.449:     - source: 'ATEM video' (av_capture_input)
21:20:19.449:     - source: 'ATEM audio' (coreaudio_input_capture)
21:20:19.449:     - source: 'HECKSPLASH' (image_source)
21:20:19.449: - scene 'PERFORMANCE':
21:20:19.449:     - source: 'ATEM video' (av_capture_input)
21:20:19.449:     - source: 'C920 video' (av_capture_input)
21:20:19.449:         - filter: 'Color Correction' (color_filter)
21:20:19.449:     - source: 'MBP camera' (av_capture_input)
21:20:19.449:     - source: 'ATEM audio' (coreaudio_input_capture)
21:20:19.449:     - source: 'HECKSPLASH' (image_source)
21:20:19.449:     - source: 'ems-logo' (image_source)
21:20:19.449:     - source: 'ems-logo-dark' (image_source)
21:20:19.449:     - source: 'hecktube' (image_source)
21:20:19.449: - scene '---------------':
21:20:19.449: - scene 'webcam_mic':
21:20:19.449:     - source: 'MBP camera' (av_capture_input)
21:20:19.449:     - source: 'MBP mic' (coreaudio_input_capture)
21:20:19.449: - scene 'ATEM && webcam':
21:20:19.449:     - source: 'ATEM video' (av_capture_input)
21:20:19.449:     - source: 'ATEM audio' (coreaudio_input_capture)
21:20:19.449:     - source: 'MBP camera' (av_capture_input)
21:20:19.449: - scene 'C920_mic':
21:20:19.449:     - source: 'C920 video' (av_capture_input)
21:20:19.449:         - filter: 'Color Correction' (color_filter)
21:20:19.449:     - source: 'C920 audio' (coreaudio_input_capture)
21:20:19.449:     - source: 'ems-logo-dark 2' (image_source)
21:20:19.449:     - source: 'hecktube 2' (image_source)
21:20:19.449: - scene 'C920_mic  && webcam':
21:20:19.449:     - source: 'C920 video' (av_capture_input)
21:20:19.449:         - filter: 'Color Correction' (color_filter)
21:20:19.449:     - source: 'MBP camera' (av_capture_input)
21:20:19.449:     - source: 'C920 audio' (coreaudio_input_capture)
21:20:19.449:     - source: 'ems-logo-dark 2' (image_source)
21:20:19.449:     - source: 'hecktube' (image_source)
21:20:19.449: - scene '----------------':
21:20:19.449: - scene 'desktop':
21:20:19.449:     - source: 'C920 video' (av_capture_input)
21:20:19.449:         - filter: 'Color Correction' (color_filter)
21:20:19.449:     - source: 'Display Capture' (display_capture)
21:20:19.449:     - source: 'Loopback' (coreaudio_input_capture)
21:20:19.449:     - source: 'C920 audio' (coreaudio_input_capture)
21:20:19.449: ------------------------------------------------
```

## Steps to Reproduce

I'm not confident in the steps to reproduce, but I will elaborate on my setup. I have installed:
* Loopback
* iShowU Audio (already uninstalled)
* NDI
* Virtual Cam

**Comment by WizardCM** [comment] 2021-01-12 04:32
Duplicate of #4011

**Closed by WizardCM** 2021-01-12 04:32 UTC
