### ISSUE TITLE
Broken on i386 architecture: ld: error: relocation R_386_PC32 cannot be used against symbol 'strlist_split'; recompile with -fPIC

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#10481] opened 2024-04-05 01:20 UTC
### Operating System Info

Other

### Other OS

FreeBSD 14.0

### OBS Studio Version

30.1.1

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

```
[ 38% 172/446] : && /usr/bin/cc -fPIC -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG  -fPIC -Wl,--undefined-version -fstack-protector-strong -shared  -o plugins/obs-x264/obs-x264.so deps/opts-parser/CMakeFiles/opts-parser.dir/opts-parser.c.o plugins/obs-x264/CMakeFiles/obs-x264.dir/obs-x264.c.o plugins/obs-x264/CMakeFiles/obs-x264.dir/obs-x264-plugin-main.c.o  -Wl,-rpath,/usr/local/lib/../lib:/wrkdirs/usr/ports/multimedia/obs-studio/work/.build/libobs:  /usr/local/lib/../lib/libx264.so  libobs/libobs.so.30  -lpthread && cd /wrkdirs/usr/ports/multimedia/obs-studio/work/.build/plugins/obs-x264 && /usr/local/bin/cmake -E env DESTDIR= /usr/local/bin/cmake --install .. --config Release --prefix /wrkdirs/usr/ports/multimedia/obs-studio/work/.build/rundir/Release --component obs_obs-x264 > /dev/null
FAILED: plugins/obs-x264/obs-x264.so 
: && /usr/bin/cc -fPIC -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG  -fPIC -Wl,--undefined-version -fstack-protector-strong -shared  -o plugins/obs-x264/obs-x264.so deps/opts-parser/CMakeFiles/opts-parser.dir/opts-parser.c.o plugins/obs-x264/CMakeFiles/obs-x264.dir/obs-x264.c.o plugins/obs-x264/CMakeFiles/obs-x264.dir/obs-x264-plugin-main.c.o  -Wl,-rpath,/usr/local/lib/../lib:/wrkdirs/usr/ports/multimedia/obs-studio/work/.build/libobs:  /usr/local/lib/../lib/libx264.so  libobs/libobs.so.30  -lpthread && cd /wrkdirs/usr/ports/multimedia/obs-studio/work/.build/plugins/obs-x264 && /usr/local/bin/cmake -E env DESTDIR= /usr/local/bin/cmake --install .. --config Release --prefix /wrkdirs/usr/ports/multimedia/obs-studio/work/.build/rundir/Release --component obs_obs-x264 > /dev/null
ld: error: relocation R_386_PC32 cannot be used against symbol 'strlist_split'; recompile with -fPIC
>>> defined in libobs/libobs.so.30
>>> referenced by opts-parser.c
>>>               deps/opts-parser/CMakeFiles/opts-parser.dir/opts-parser.c.o:(obs_parse_options)

ld: error: relocation R_386_PC32 cannot be used against symbol 'bmalloc'; recompile with -fPIC
>>> defined in libobs/libobs.so.30
>>> referenced by opts-parser.c
>>>               deps/opts-parser/CMakeFiles/opts-parser.dir/opts-parser.c.o:(obs_parse_options)
```

### Steps to Reproduce

Regular build.

### Anything else we should know?

Only i386 is affected.

[log](https://pkg-status.freebsd.org/beefy11/data/140i386-default/65ec83d48838/logs/obs-studio-30.1.1.log)

**Comment by derrod** [comment] 2024-04-05 01:39
We don't support 32 bit so unless this also affects 64 bit builds I don't think we'll do anything here.

**Comment by RytoEX** [comment] 2024-04-05 01:45
We haven't supported 32-bit builds in general since OBS Studio 27.2. Trivial PRs welcome to fix this, but I do not currently consider this a valid bug.

**Comment by RytoEX** [comment] 2024-04-05 01:45
Also, possibly duplicate of #10316

**Closed by RytoEX** 2024-04-05 01:45 UTC

**Comment by kkartaltepe** [comment] 2024-04-05 02:02
Its probably unrelated to the person who built python themselves incorrectly, its more likely a problem with the build environment. 

https://buildd.debian.org/status/fetch.php?pkg=obs-studio&arch=i386&ver=30.0.2%2Bdfsg-3&stamp=1711896616&raw=0

debian seems to have no problem so i would guess some compiler/linker flag set by your build system is not working as expected.
