### ISSUE TITLE
OBS 28.0.1 Virtual Camera output only RED rectangle on Intel Mac

### ISSUE THREAD

**Issue by Teressss** [obsproject/obs-studio#7375] opened 2022-09-14 08:01 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/lMRDAH-y7bLZ68tF

### Expected Behavior

I expect OBS Virtual Camera to show output of OBS to Microsoft Teams / Skype, etc...

### Current Behavior

on Intel 2019 Mac Pro and latest OBS 28.0.1 the Virtual Camera is outputting only RED screen to Microsoft Teams. Same behavior is also in latest Skype version. mimoLive app's "virtual camera" is working fine in those 2 apps.
BTW on same version of OBS and MS Teams and Skype the OBS's Virtual Camera works great on Apple Silicon M1 Ultra Mac Studio, but not on Intel Mac. All SW versions are the most recent ones at this moment = macOS Monterey 12.7 + OBS 28.0.1

### Steps to Reproduce

1. open OBS
2. start Virtual Camera
3. In Microsoft Teams I see only RED background instead of actual OBS output
...
<img width="829" alt="Screen Shot 2022-09-12 at 3 22 09 PM" src="https://user-images.githubusercontent.com/37613557/190096489-81326f32-f642-472e-8f0c-93a6e9e7186a.png">

**Comment by WizardCM** [comment] 2022-09-14 08:21
Duplicate of #7333

**Closed by WizardCM** 2022-09-14 08:21 UTC
