### ISSUE TITLE
Can't change options in capture device source in Linux

### ISSUE THREAD

**Issue by Velkas** [obsproject/obs-studio#4960] opened 2021-06-30 01:49 UTC
### Operating System Info

Other

### Other OS

Debian (Sparkylinux 6 Gameover Edition)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://gist.github.com/Velkas/3bb4b5ed47c2a7eb56c772052e4b5a4b

### Expected Behavior

Selecting any of the property options in Video Capture Device source opens a menu to select the appropriate options.

### Current Behavior

Selecting any of the property options in Video Capture Device source does not open the menu to select the appropriate options. In addition, selecting OK or CANCEL doesn't work in the dialog unless pressed repeatedly.

### Steps to Reproduce

1. Open OBS
2. Add new source to scene (Video Capture Device)
3. Attempt to change any of the properties inside.
![image](https://user-images.githubusercontent.com/7484211/123888706-9b82aa00-d943-11eb-8752-8be07179b2fa.png)

### Anything else we should know?

This is a Debian environment with XFCE4. Most things in OBS seem to work fine, including actually streaming (test streaming) to twitch. I just can change the options in my capture card source to let me use the higher quality stream instead of the low-latency low-quality stream.

**Comment by imaltont** [comment] 2021-07-09 23:07
This has unfortunately been an issue for a while. Duplicate of #3733.

**Comment by kkartaltepe** [comment] 2022-04-01 06:14
Closing this as #5287 from the referenced issue should have resolved it.

**Closed by kkartaltepe** 2022-04-01 06:14 UTC
Labels: Linux
