### ISSUE TITLE
v4l2 should access phisical cameras in /dev/v4l/by-id/* if possible.

### ISSUE THREAD

**Issue by MarioMey** [obsproject/obs-studio#3824] opened 2020-12-04 02:59 UTC
## Platform
Operating system and version: Debian 10
OBS Studio version: 26.0.2-83

## Steps to Reproduce
1. Plug USB WebCam "A" (linux configures it as /dev/video0).
2. Configure OBS to get it as capture source.
3. Close OBS.
4. Disconnect WebCam "A"
5. Connect WebCam "B" (linux configures it as /dev/video0)
6. Connect WebCam "A" (linux configures it as /dev/video1)
7. Run OBS...

## Expected Behavior
- OBS should take capture source with WebCam "A" (despite it is in /dev/video1)

## Current Behavior
- OBS takes WebCam "B" (that it is in /dev/video0)

## Additional information
Linux (as I know, Debian derivates and Raspberri do) configures symlinks to WebCams by its ID and "path". Example for my 2 cams:
```
mario@debian:~$ ls /dev/v4l/by-id/
usb-046d_HD_Pro_Webcam_C920_22F75AFF-video-index0  usb-_Webcam_C170-video-index0
usb-046d_HD_Pro_Webcam_C920_22F75AFF-video-index1  usb-_Webcam_C170-video-index1
mario@debian:~$ ls /dev/v4l/by-path/
pci-0000:01:00.0-usb-0:1:1.0-video-index0  pci-0000:01:00.0-usb-0:2:1.0-video-index0
pci-0000:01:00.0-usb-0:1:1.0-video-index1  pci-0000:01:00.0-usb-0:2:1.0-video-index1
```
OBS, instead of taking and store WebCams as `/dev/video0`, it should take by its symlink `/dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_22F75AFF-video-index0`. So, if you disconnect/connect several cameras in different order, OBS should take the same camera each source.

**Comment by RytoEX** [comment] 2020-12-04 13:16
This looks like a duplicate of #3003, which would mean #3437 is addressing it.

**Closed by RytoEX** 2020-12-04 13:16 UTC

**Comment by subhajitsarkar91** [comment] 2021-07-20 11:38
please mention how to use the /dev/v4l/by-path / as I have same cameras so I need path variable to be implemented 
" fswebcam -d /dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-video-index0 --skip 16 --jpeg 95 /home/pi/capture.jpg " but it doesn't work
