### ISSUE TITLE
Copy & Paste can't be used in custom browser dock (e.g. Twitch Chat)

### ISSUE THREAD

**Issue by TheTommynator** [obsproject/obs-studio#7207] opened 2022-08-28 09:08 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/hmnKRdUJMs5ltait

### Expected Behavior

Should be able to do CMD + C and CMD + V to copy and paste in a custom browser dock.

### Current Behavior

Using the standard keyboard shortcuts doesn't do anything. So copy & paste in a custom browser dock isn't possible right now.

### Steps to Reproduce

1. insert twitch chat in a custom browser dock using it's URL
2. Try to copy & paste using cmd c and cmd v

**Comment by WizardCM** [comment] 2022-08-28 09:13
Duplicate of https://github.com/obsproject/obs-browser/issues/365

**Closed by WizardCM** 2022-08-28 09:13 UTC
