### ISSUE TITLE
About box does not show about text

### ISSUE THREAD

**Issue by ryandesign** [obsproject/obs-studio#3969] opened 2020-12-24 23:11 UTC
## Platform
Operating system and version: macOS 11.0.1
OBS Studio version: 26.1.0

## Expected Behavior
I presume that there is some text that should be shown in the text area in the About box.

## Current Behavior
The About box shows no text in the text area until the Authors or License links are clicked. Clicking the About link does not change the contents of the text area.

https://user-images.githubusercontent.com/429209/103108156-b2e68080-460a-11eb-8776-4ad1e93dca9e.mov

## Steps to Reproduce
1. Open OBS
2. Select About OBS from the OBS menu: text area in About window is blank
3. Click Authors or License links: text area fills with authors or license text
4. Click About link: nothing happens

## Additional information

**Comment by gxalpha** [comment] 2020-12-24 23:44
The text shown there are the Top Patreon contributions.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/59806498/103111170-53a86080-464a-11eb-85c2-b8bc05b3d397.png">

I was able to reproduce this by unplugging my ethernet cable, to me it seems like the contributions get loaded from the internet, obviously can't be found (since the cable / Wifi isn't connected), and then the text field is just left blank.

An error message would probably be the best solution(?).

**Comment by ryandesign** [comment] 2020-12-25 00:05
My computer certainly has Internet access...

**Comment by WizardCM** [comment] 2020-12-25 00:14
This is the URL it tries to load

https://github.com/obsproject/obs-studio/blob/20fb235b8fe86284fcd0de7848a76056b0771228/UI/window-basic-about.cpp#L68

If you're using a VPN it might not work.

**Comment by ryandesign** [comment] 2020-12-25 20:26
I'm not using a VPN. The URL works fine in a browser or in curl on the command line.

I tried on another computer running macOS 10.13.6 and OBS 26.0.2 and it worked (the About box showed the sponsors). I upgraded that computer to OBS 26.1.0 and it stopped working (About box blank).

**Comment by heyitsjk** [comment] 2020-12-25 21:56
About Window shows as empty for me too, connected to internet - no VPN

macOS 10.14.6
OBS 26.1.0

**Comment by PatTheMav** [comment] 2020-12-28 15:43
@WizardCM I can imagine this being an issue with OBS using `curl` to fetch this URL and our latest release is linked against the merged `curl` from Homebrew which handles HTTPS connections differently.

https://github.com/obsproject/obs-studio/pull/3895 might have fixed this as it ensures OBS uses system-provided `curl`.

**Comment by PatTheMav** [comment] 2020-12-28 15:44
@ryandesign Please check if the issue persists with this build: https://github.com/PatTheMav/obs-studio/releases/download/26.1.0-preview/obs-studio-26.1.0-tech-preview-cef-4183.dmg

**Comment by RytoEX** [comment] 2020-12-28 20:19
> 
> 
> @WizardCM I can imagine this being an issue with OBS using `curl` to fetch this URL and our latest release is linked against the merged `curl` from Homebrew which handles HTTPS connections differently.
> 
> #3895 might have fixed this as it ensures OBS uses system-provided `curl`.

Sorry, I had typed this reply, and delayed submitting it due to the holiday period:
> @WizardCM @PatTheMav Could this be a manifestation of #3887 as an SSL/TLS curl connection failure with the dependencies for OBS 26.1.0?

Seems Pat had the same idea.  They could probably try to run an OBS update check (if that exists on macOS) or upload a log file to see if that fails similarly.  Upload log also uses `RemoteTextThread` on an HTTPS URL, like the About block here, so trying to upload a log might be the easiest way to check.

**Comment by ryandesign** [comment] 2020-12-28 23:01
> @ryandesign Please check if the issue persists with this build: https://github.com/PatTheMav/obs-studio/releases/download/26.1.0-preview/obs-studio-26.1.0-tech-preview-cef-4183.dmg

Thank you, that works (tested on macOS 10.13.6).

**Comment by WizardCM** [comment] 2020-12-28 23:19
Fixed by #3887

**Closed by WizardCM** 2020-12-28 23:19 UTC
Labels: Dependency Issue, Fix available, macOS
