### ISSUE TITLE
OBS Studio Update Preference Window does not close

### ISSUE THREAD

**Issue by Volatus** [obsproject/obs-studio#6800] opened 2022-07-23 23:52 UTC
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/5Tpjzp_rhIizfzIb

### Expected Behavior

OBS Studio after launch asks for whether I'd like automatic updates or not. Choosing either option does not close the window and behavior is persistent even after killing the process and relaunching the app. I expect to be able to choose and then the window should close.

### Current Behavior

Currently neither button works properly.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/46189206/180626447-e72b200c-ff0f-4d3d-918c-ba2871a0f8b2.png">

### Steps to Reproduce

1. Run OBS
2. Wait for OBS to ask for update preferences
...

### Anything else we should know?

This is on `darwin/arm64`, just so you know.

**Comment by RytoEX** [comment] 2022-07-23 23:53
Duplicate of #4904

**Closed by RytoEX** 2022-07-23 23:53 UTC
