### ISSUE TITLE
Auto-Configuration Wizard incorrectly detects current display resolution on UHD displays

### ISSUE THREAD

**Issue by bershanskiy** [obsproject/obs-studio#4398] opened 2021-03-26 11:25 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

N/A

### Expected Behavior

On device with only one 3840*2400 display attached, the Auto-Configuration Wizard "Video Settings" page resolution dropdown contains option "Use Current (3840x2400)".

### Current Behavior

On device with only one 3840*2400 display attached, the Auto-Configuration Wizard "Video Settings" page resolution dropdown contains option "Use Current (1920x1080)".

### Steps to Reproduce

1. Launch OBS built from current master on Windows 10 device with active screen running at 3840x2400
2. Open Auto-Configuration Wizard, go to "Video Settings" page
3. Open "Base (Canvas) Resolution)" and see options "Use Current (1920x1080)" and "Display 1 (3840x2400)"
4. Of cource, display 1 and current display are the same thing and should have the same resolution.

### Anything else we should know?

#4393 fixed display resolution of devices listed as "Display #", but not the active one. Also, this bug probably affects other users of `obs_get_video_info()`.

Image for your convinience:

![image](https://user-images.githubusercontent.com/45960703/112623819-e0c3a700-8e3d-11eb-8b2c-7183c4bdb8ce.png)

**Comment by WizardCM** [comment] 2021-03-26 11:26
Duplicate of #4298

**Closed by WizardCM** 2021-03-26 11:26 UTC

**Comment by Nirusu** [comment] 2021-03-26 12:41
Since that was my PR:

Current means currently set _canvas resolution_, not current _display resolution_.

When OBS is initialized with a new config, it defaults to 1920x1080 if your screen is above 1080p in resolution, likely because 1080p+ streaming / recording can still be unexpectedly stressing for your hardware.

That's actually intended in the code. If the behavior makes sense or if there are better approaches... Well, I think the wording is a bit weird, I agree here. It confused me the first time too.

**Comment by bershanskiy** [comment] 2021-03-26 12:52
> Current means currently set canvas resolution, not current display resolution.
>
> I think the wording is a bit weird, I agree here. It confused me the first time too.

Oh, that makes sense. Then there is no bug at all, it is the intended behavior.

**Comment by Nirusu** [comment] 2021-03-26 13:01
Yup. Not a bug per se, just shown in a confusing way :) 

Maybe someone could redesign this in a way it is more apparent, especially since someone mentioned in the issue that this also seems to break for resolutions above >4096 in one dimension.
