### ISSUE TITLE
Image Slide Show: A .gif file in combination with other image types will stop the animation

### ISSUE THREAD

**Issue by DachsbauTV** [obsproject/obs-studio#3606] opened 2020-10-14 16:30 UTC
As soon as an animated .gif is included in the list of the images, the automatic slide show will pause or, when it is the first image, it will only cycle through the first two files.
It still can be triggered manually.

## Platform
Operating system and version: Win10 2004
OBS Studio version: 26.0.2

## Expected Behavior
Move through images regardless of filetype after a specific amount of time.

## Current Behavior
Movement stops when animated .gif is included or it will only cycle through the first two

## Steps to Reproduce
1. Add Image Slide Show Source
2. Add image files
3. Add .gif

**Comment by skeletonbow** [comment] 2020-10-14 18:10
How big are the animated GIF files?  There is a maximum decompressed size of all images in a slide show of about 512MB of VRAM that can be used.  If the amount of image data in a slideshow exceeds this further images will not show up.  Animated images could be a fair bit larger by nature which could have the potential to cut a slideshow shorter than intended.  Also keep in mind the VRAM usage is after decompression so images/GIFs take up a lot more space than their size on disk in memory.

**Comment by DachsbauTV** [comment] 2020-10-14 18:12
it is only one file with 1,3MB

**Comment by arrowgent** [comment] 2020-10-15 16:10
> How big are the animated GIF files? There is a maximum decompressed size of all images in a slide show of about 512MB of VRAM that can be used. If the amount of image data in a slideshow exceeds this further images will not show up. Animated images could be a fair bit larger by nature which could have the potential to cut a slideshow shorter than intended. Also keep in mind the VRAM usage is after decompression so images/GIFs take up a lot more space than their size on disk in memory.

why is this a limit? i would also like to use more than 17 gif images as a slideshow but adding more just omits them

is it possible to change this limit?  512mb seems like a windows xp limitation from 20 years ago
considering we can use a webm file that is 30gb

is there a way to run a test simulation on this process to show how much ram is being used by a source or scene???

**Comment by arrowgent** [comment] 2020-10-15 16:19
https://github.com/obsproject/obs-studio/issues/3366

**Comment by Fenrirthviti** [comment] 2020-10-15 18:50
Closing as duplicate of https://github.com/obsproject/obs-studio/issues/3366 to keep discussion from being spread too thin.

Please continue discussion there or on the RFC: https://github.com/obsproject/rfcs/pull/17

**Closed by Fenrirthviti** 2020-10-15 18:50 UTC
