### ISSUE TITLE
AMF encoder error

### ISSUE THREAD

**Issue by xana43** [obsproject/obs-studio#4648] opened 2021-05-04 20:05 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/bMd3xneytSnZeUlU

### Expected Behavior

I believe the expected behavior is that obs is meant to actually use the AMF encoder and not fall back on certain options (for instance the configured colorspace is i444 but it falls back to NV12)

### Current Behavior

it says 
[AMF] <Id: 3> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)
and certain options fallback to default (as stated above)

### Steps to Reproduce

1.Open OBS 
2.Select any AMF based hardware encoder
3.Set color format to I444
4.Record

### Anything else we should know?

I've reinstalled the radeon drivers a few times to see if that would fix the issue, i've tried every other setting configuration, the only configuration that doesn't cause this issue is CPU based x264

**Comment by MattyFresh68** [comment] 2021-05-04 20:29
https://github.com/obsproject/obs-amd-encoder/wiki/hardware-support#Capabilities
I dont believe AMF supports i444

**Comment by notr1ch** [comment] 2021-05-04 20:42
Closing as this is by design, I444 is not supported.

**Closed by notr1ch** 2021-05-04 20:42 UTC
