### ISSUE TITLE
29.1.0-rc1 not compile due error: call to '_curl_easy_setopt_err_write_callback' declared with 'warning' attribute: curl_easy_setopt expects a curl_write_callback argument for this option

### ISSUE THREAD

**Issue by AngryPenguinPL** [obsproject/obs-studio#8808] opened 2023-04-26 13:33 UTC
### Operating System Info

Other

### Other OS

Linux OpenMandriva Cooker

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.0-rc1

### OBS Studio Log URL

none

### Expected Behavior

OBS compile fine.

### Current Behavior

When trying to compile OBS-Studio 29.1.0-rc1 on Linux I see this compilation error:

```
builddir/build/BUILD/obs-studio-29.1.0-rc1/deps/file-updater/file-updater/file-updater.c:115:2: error: call to '_curl_easy_setopt_err_write_callback' declared with 'warning' attribute: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror,-Wattribute-warning]
DEBUG util.py:445:          curl_easy_setopt(info->curl, CURLOPT_WRITEFUNCTION, http_write);
DEBUG util.py:445:          ^
DEBUG util.py:445:  /usr/include/curl/typecheck-gcc.h:59:15: note: expanded from macro 'curl_easy_setopt'
DEBUG util.py:445:                _curl_easy_setopt_err_write_callback();                   \
DEBUG util.py:445:                ^
DEBUG util.py:445:  /builddir/build/BUILD/obs-studio-29.1.0-rc1/deps/file-updater/file-updater/file-updater.c:124:3: error: call to '_curl_easy_setopt_err_write_callback' declared with 'warning' attribute: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror,-Wattribute-warning]
DEBUG util.py:445:                  curl_easy_setopt(info->curl, CURLOPT_HEADERFUNCTION,
DEBUG util.py:445:                  ^
DEBUG util.py:445:  /usr/include/curl/typecheck-gcc.h:59:15: note: expanded from macro 'curl_easy_setopt'
DEBUG util.py:445:                _curl_easy_setopt_err_write_callback();                   \
DEBUG util.py:445:                ^
DEBUG util.py:445:  2 errors generated.
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/71339296d5378cdd596a70450dd1cf5b2c63cb52.log?show=true

I see this compilation failure is both Clang 16 and GCC 13.1.0.

### Steps to Reproduce

1. Use OpenMandriva Cooker or other distro with Clang 16 / GCC 13.1
2. Install Curl 8.0.1
3. Try compile OBS 29.1.0-rc1
4. See build error

**Comment by tytan652** [comment] 2023-04-26 14:32
It seems that using the latest compilers triggers a new code path in cURL headers.

**Comment by RytoEX** [comment] 2023-04-26 17:40
We currently target curl 7.x (roughly 7.68 through 7.88.1). Curl 8/8.0.1 came out on March 20, 2023. We will investigate supporting newer dependency versions in the future.

**Comment by notr1ch** [comment] 2023-04-28 00:04
Is this actually a dependency issue or is this because we have mismatching types on the `http_write` callback? We use a `uint8_t *` and Curl expects `char *`.

**Comment by tytan652** [comment] 2023-04-28 06:00
Dependency issue with GNUC 4.3 and later which enable a new code path in cURL headers which add typecheck.

`http_write` must match one of those https://github.com/curl/curl/blob/curl-7_88_1/include/curl/typecheck-gcc.h#L569

**Comment by tytan652** [comment] 2023-04-28 07:29
I want to note that even if the type check needs to checked/fixed.

We might not support all the flags that you add through your build-system:
```
'-DCMAKE_C_FLAGS=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic' 
'-DCMAKE_C_FLAGS_RELEASE=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -DNDEBUG' 
'-DCMAKE_C_FLAGS_RELWITHDEBINFO=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic' 
'-DCMAKE_CXX_FLAGS=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic' 
'-DCMAKE_CXX_FLAGS_RELEASE=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -DNDEBUG'
'-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic' 
'-DCMAKE_EXE_LINKER_FLAGS=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -Wl,-O2   ' 
'-DCMAKE_SHARED_LINKER_FLAGS=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -Wl,-O2   '
'-DCMAKE_MODULE_LINKER_FLAGS=-Os -fomit-frame-pointer -g3 -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -Wl,-O2'
```

**Comment by tytan652** [comment] 2023-04-28 09:53
I couldn't reproduce on Arch Linux, so it might mean that the a unsupported flag is added in OpenMandriva build-system.

Clang is not able to trigger this codepath in cURL header since it simulate GCC 4.2 so more likely an issue with your llvm/clang build.
But GCC 12 or 13 can and do but no warning was found until now, so the issue might rely in your build system.

I will close this issue for now, if you want to provide more information feel free but it must be with Clang since this warning/error is only possible with GCC.

**Closed** 2023-04-28 09:54 UTC
Labels: Dependency Issue
