### ISSUE TITLE
Hotkeys (Such as "OBS_KEY_13") don't work while OBS is active window.

### ISSUE THREAD

**Issue by Joefis-x20s** [obsproject/obs-studio#2193] opened 2019-11-23 18:50 UTC
### Hotkeys F13 and above no longer work in OBS

Since the added feature to chose hotkey focus behaviour there has been a problem with hotkeys that use function keys above F12 ("OBS_KEY_F20")

I currently use a program that utilizes keybinds in that range however they don't work while the OBS is in focus despite the hotkey focus behavior setting. (Even when I have 2 OBS's open putting either one into focus will disable the use of OBS_KEY_etc

Another issue is now you cant assign hotkeys above F12 within OBS as it doesn't register the key while in focus.

**Expected Behavior:**
Press hotkey while OBS is in focus and it will do what it was assigned to do (When Hotkey Focus Behavior is set to Never disable hotkeys)

When pressing F13 and up OBS will add it as a hotkey (Like previous versions)

**Current Behavior:**
While OBS is in focus it will ignore anykey that is OBS_KEY_etc (Such as F13 & up)

Pressing F13 & up in the hotkey settings doesn't work to assign the key.

**Steps to Reproduce:**
Try using F13 and up keys in OBS as hotkeys (OBS_KEY_etc)

**Comment by Fenrirthviti** [comment] 2020-04-26 04:37
Is this still present in the latest release? What OS is this being encountered on?

**Comment by QHayward** [comment] 2020-04-29 01:25
This continues to be a problem for me.  I'm on OBS 25.0.4.

This problem seems to be Linux specific (I can't reproduce it on Windows).

OBS hotkeys seem to ignore F13\~F24 completely.
Although I managed to bind some F13\~F24 keys by manually editing files in the ~/.config/obs-studio/basic/ directory, OBS still ignores them when I press them.

A OBS plugin I'm using, Input Overlay, has no problem detecting these keys.

Unlike @Joefis-x20s , OBS does not recognize these keys for me regardless of whether or not OBS is in focus.

**Comment by Geekhat** [comment] 2020-06-27 16:03
Also getting this as of today on 25.0.8, even when the option under advanced settings is set to "Never disable hotkeys."

**Comment by pmichaud** [comment] 2020-08-11 05:48
Perhaps look at the comment I added in #3138.  I have F13..F24 (and higher) working fine on my Linux system (Kubuntu 20.04) -- I found that the xmodmap tables didn't have F13..F24 defined so they are never registered.

You can use the ```xev``` command to see what keys are registering as when pressed.  On my system, F13 wsa coming across as XF86Activity5 or something like that (and obs-studio doesn't recognize or receive the XF86* keystrokes for some reason).

More details on xmodmap in issue #3138 .  Hope this helps.

Pm

**Comment by PatTheMav** [comment] 2020-12-31 15:57
Seems to be fixed via the steps outlined by https://github.com/obsproject/obs-studio/issues/2193#issuecomment-671740507. 

Closing this for now.

**Closed by PatTheMav** 2020-12-31 15:57 UTC
Labels: Good first issue, Linux

**Comment by Frogging101** [comment] 2021-08-24 01:12
I'm on Kubuntu 20.04, and OBS does not recognize an F13-F24 key pressed by `xdotool`. xev does recognize it as F13 (`keycode 191 (keysym 0xffca, F13)`), and I created the .Xmodmap file quoted in #3138; though it makes no difference though, since this key is being generated in software anyway.

OBS hotkey configuration will not pick it up.

**Comment by Frogging101** [comment] 2021-08-24 01:14
Also, the reason I'm doing this is because I wanted to use my mouse forward button as a push-to-talk hotkey, but it doesn't work. OBS doesn't respond to it (or does so only very briefly)

**Comment by pmichaud** [comment] 2021-09-20 16:33
> I'm on Kubuntu 20.04, and OBS does not recognize an F13-F24 key pressed by `xdotool`. xev does recognize it as F13 (`keycode 191 (keysym 0xffca, F13)`), and I created the .Xmodmap file quoted in #3138; though it makes no difference though, since this key is being generated in software anyway.
> 
> OBS hotkey configuration will not pick it up.

FWIW, my experience is that a lot of applications won't honor the synthetic keypress events generated by xdotool and other event generating programs.

In my case, I've worked around a lot of hotkey issues by using a websockets interface to control a lot of OBS features.  ( https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-from-websockets.466/ )   Then I can use xbindkeys to grab the mouse/keyboard event and a short command line or shell script to tell OBS what to do.

Pm

**Comment by Frogging101** [comment] 2021-09-20 19:29
For push-to-talk when streaming I wrote a [python program](https://gist.github.com/Frogging101/6d1660ddbfde0d615a11af3a1754202c) to monitor evdev for my push to talk key and mute/unmute my pulseaudio source. It works nicely, even with programs that don't support push to talk. It's very portable and should even work on Wayland, where Xinput (Xorg input API) or a standard equivalent is not available. I recommend any future input handling should use evdev for this reason.

**Comment by Yowlen** [comment] 2022-06-18 06:35
I can confirm this is still an issue in OBS 27.2.4. I'm running OBS from the official PPA on Xubuntu 20.04, in case it matters.

Specifically, I've tested it and gotten the following results:

- **Never disable hotkeys:** Hotkeys only work when OBS has focus
- **Disable hotkeys when main window is in focus**: Hotkeys only work when OBS is not in focus
- **Disable hotkeys when main window is not in focus**: Hotkeys only work when OBS has focus

As we can see, the latter two options are working as intended. It's only the "Never disable hotkeys" one that's broken, and specifically only when the window doesn't have focus, making it effectively the same as the last option.

OBS is clearly capable of grabbing input when out of focus thanks to the 2nd option, so this bug should be easily fixable since a simple comparison of each function's code should show what the problem is.
