### ISSUE TITLE
help! Developer cannot modify OBSBasic.ui

### ISSUE THREAD

**Issue by laoyebisheng** [obsproject/obs-studio#5061] opened 2021-08-03 16:51 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

no

### Expected Behavior

I am a program Qt development engineer and I recently encountered a problem。
I want to modify OBSBasic.ui the layout and I want to add some buttons。
in the past(25.0.0 Version or 26.0.0) version ， After modifying  OBSBasic.ui  the file and recompiling，no error。
when I git fetch 27.0.0，if button is added on the OBSBasic.ui, many errors will be reported after recompiling. 
The error says it can't be found
"error C2039: "previewDisabledWidget": not a member of "Ui::OBSBasic""

please tell me How to modify OBSBasic

### Current Behavior

![obs bug](https://user-images.githubusercontent.com/30955451/128054809-bd15cdce-50cc-4100-8d7f-c3cc6ac51655.png)

### Steps to Reproduce

1.open OBSBasic.ui by Qt Designer
2.add pushbutton to centralwidget
3.compiling
4.log out error

### Anything else we should know?

VS2019+QT5.15.2

**Comment by notr1ch** [comment] 2021-08-03 16:59
Duplicate of https://github.com/obsproject/obs-studio/issues/5053.

**Closed by notr1ch** 2021-08-03 16:59 UTC

**Comment by laoyebisheng** [comment] 2021-08-03 17:01
> [重复#5053。](https://github.com/obsproject/obs-studio/issues/5053)

Previous reply，Didn't tell me how to modify。

**Comment by Fenrirthviti** [comment] 2021-08-03 17:43
Development questions should be submitted to the Forums or discussed on our Discord, not to Github.
