### ISSUE TITLE
Browser Source no longer Builds on Git Version

### ISSUE THREAD

**Issue by rob215x** [obsproject/obs-studio#11229] opened 2024-08-31 22:11 UTC
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/u6mnA5mpwgSonghU

### Expected Behavior

I saw someone else reported this, https://github.com/obsproject/obs-studio/issues/11227 but I'm going to try to provide some additional information because I have 2 PCs and on PC #1, I did all of my updates on 2024-08-24 then Built OBS and it WORKS FINE. 

**_The Log URL above is from my WORKING OBS!!_**

Yesterday, I did all of my updates on PC #2, and then Built OBS. It Builds and works but there is NO Browser Source!

So, just now, I tried a Build on PC #1 (where my OBS works!!) and I see this in my Build:

```
                      _                   _             _ _       
                 ___ | |__  ___       ___| |_ _   _  __| (_) ___  
                / _ \| '_ \/ __|_____/ __| __| | | |/ _` | |/ _ \ 
               | (_) | |_) \__ \_____\__ \ |_| |_| | (_| | | (_) |
                \___/|_.__/|___/     |___/\__|\__,_|\__,_|_|\___/ 

OBS:  Application Version: 30.2.2-179-g34735be09 - Build Number: 1
==================================================================================


------------------------       Enabled Features           ------------------------
 - OpenGL renderer
 - PipeWire 0.3.60+ camera support
 - Plugin Support
 - PulseAudio audio monitoring (Linux)
 - RNNoise noise suppression
 - Scripting Support (Frontend)
 - Scripting support
 - SpeexDSP noise suppression
 - User Interface
 - Wayland compositor support (Linux)
------------------------       Disabled Features          ------------------------
 - Browser sources are not enabled by default (set CEF_ROOT_DIR and ENABLE_BROWSER)
 - Restream API connection
 - Twitch API connection
 - YouTube API connection
------------------------        Enabled Modules           ------------------------
 - decklink
 - decklink-captions
 - decklink-output-ui
 - frontend-tools
 - image-source
 - linux-alsa
 - linux-capture
 - linux-jack
 - linux-pipewire
 - linux-pulseaudio
 - linux-v4l2
 - obs-ffmpeg
 - obs-filters
 - obs-libfdk
 - obs-nvenc
 - obs-outputs
 - obs-qsv11
 - obs-transitions
 - obs-vst
 - obs-webrtc
 - obs-websocket
 - obs-x264
 - obslua
 - obspython
 - rtmp-services
 - text-freetype2
 - vlc-video
------------------------        Disabled Modules          ------------------------
 - aja
 - aja-output-ui
 - obs-browser
 - sndio
 - test-input
----------------------------------------------------------------------------------
-- Configuring done (6.0s)
-- Generating done (0.3s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_BROWSER
    CEF_ROOT_DIR

```

### Current Behavior

On PC #1
- The OBS build I did on 2024-08-24 works fine with all my browser sources.
- If I go to build it today, the currently working obs-browser module will be disabled.
- I have not updated any other binaries on this machine since 2024-08-24. I built OBS that day and it still works fine. 

On PC #2
- I already built OBS and it works but has no browser sources, because the obs-browser module is disabled.
- As far as I can tell, all of my related binaries are the same.

### Steps to Reproduce

Currently building OBS will result in a disabled obs-browser module. It worked fine last week with all other binaries (to my knowledge) being the same. 

### Anything else we should know?

If you want any additional info, please let me know. I'm happy to help.

**Comment by tytan652** [comment] 2024-08-31 22:13
Duplicate of #11227

**Closed by tytan652** 2024-08-31 22:13 UTC

**Comment by tytan652** [comment] 2024-08-31 22:14
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

**Comment by rob215x** [comment] 2024-08-31 22:19
@tytan652 I know you guys are super busy, but how is this not a bug report? If you changed something in the code and parts of the program no longer work, then why would that be a support request? 

And the reason I go to the trouble to post details is to help others, not just myself. =)

**Comment by tytan652** [comment] 2024-08-31 22:25
> but how is this not a bug report?

You are building the master that can have major changes on how the program and/or the buildsystem change.
This is not a bug, the issue is that maintaining `-git` packages requires the maintainer to keep up with how the master behave. Which is not an easy task.

So it falls under support for people building their own build and on the packager for the `-git` package.

**Comment by rob215x** [comment] 2024-08-31 22:27
@tytan652 thanks for your reply. That makes sense now.
