### ISSUE TITLE
Menu of OBS Studio is not showing when using KDE Plasma Global Menu with Wayland

### ISSUE THREAD

**Issue by jandie1505** [obsproject/obs-studio#9071] opened 2023-06-11 15:31 UTC
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://pastebin.com/NLUcia81

### Expected Behavior

The menu of OBS should be displayed either in the application or in the Global Menu of KDE Plasma.

### Current Behavior

The menu of OBS is not displayed in the application or in the Global Menu of KDE Plasma.

### Steps to Reproduce

1. Be in a **Wayland Session**, this problem does not occur on XOrg.
2. Be on **KDE Plasma** with a **Global Menu** Widget.
3. Open OBS Studio
  
--> The menu of OBS is not displayed in the application or in the Global Menu of KDE Plasma.

**Comment by tytan652** [comment] 2023-06-11 15:36
Duplicate of #8361

**Closed by tytan652** 2023-06-11 15:36 UTC

**Comment by jandie1505** [comment] 2023-06-12 15:22
It seems that displaying the OBS menu in the KDE Global Menu is currently not possible. However, there is a workaround to at least show the menu within the application itself which makes it possible to use functions that are only accessible through the menu. This workaround only applies to the Flatpak version of OBS.

To get the menu back, the following command can be used:
`sudo flatpak override com.obsproject.Studio --no-talk-name=com.canonical.AppMenu.Registrar`
(This command prevents OBS from accessing the dbus interface for the global menu. This causes the menu to be displayed in OBS itself).
