### ISSUE TITLE
macOS pick screen color picker does not work out side of key color window

### ISSUE THREAD

**Issue by kcr-random** [obsproject/obs-studio#7801] opened 2022-11-18 05:08 UTC
### Operating System Info

macOS 13

### OBS Studio Version

28.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

The color picker should remain active once outside of the Key Color window so that you can choose any color on any part of the screen.

### Current Behavior

The color picker stops detecting colors on the screen once outside of the Key Color window.

### Steps to Reproduce

1. Open Chroma Key Filter
2. Choose Key Color Type Custom
3. Select Color
4. Pick Screen Color
5. Mouse outside of Key Color window
...

**Comment by RytoEX** [comment] 2022-11-18 05:17
Duplicate of #4081

**Closed by RytoEX** 2022-11-18 05:17 UTC
