### ISSUE TITLE
Theora is not working with OBS

### ISSUE THREAD

**Issue by sabotagebeats** [obsproject/obs-studio#3575] opened 2020-10-08 06:31 UTC
## Platform

Operating system and version: windows 10 
OBS Studio version: 26.0.2

## Expected Behavior
should stream to icecast with OGG (worked in previous versions)

## Current Behavior
An unspecified error occured while recording. Couldn't find encoder 'theora'

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/27985126/95423163-7baee000-08f5-11eb-98b5-ad5df7cd6169.png)

apply, ok, start recording

![image](https://user-images.githubusercontent.com/27985126/95422406-21f9e600-08f4-11eb-89ef-aaec870db255.png)

## Additional information

if i find a copy of ffmpeg shared libraries https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-4.3.1-2020-09-21-full_build-shared.zip 
copy ffmpeg-4.3.1-2020-09-21-full_build-shared\bin\* to C:\Program Files (x86)\obs-studio\bin\64bit\
then overwrite the bin directory with the shared libraries, this used to work but no longer works on the current version of OBS

edit: this still works when I overwrite the files, close OBS, and then restart

**Comment by sabotagebeats** [comment] 2020-10-08 06:43
after doing the steps in additional information, then restarting the program, now it works. 

my friend is using a mac and getting the same error but does not know where to put the files.

**Comment by Fenrirthviti** [comment] 2020-10-08 06:45
Were you always replacing these files I older versions, and it's the replacement that is no longer working?

**Comment by sabotagebeats** [comment] 2020-10-08 07:10
> Were you always replacing these files in older versions, and it's the replacement that is no longer working?

in much older versions it worked without replacing it. At some point around version 22 I had to start replacing the files. 

I was able to get it to work by replacing the files again. Really this is a blocker for new users who don't know how to do such things.

**Comment by sabotagebeats** [comment] 2020-10-08 07:11
additionally every time i upgrade OBS, I have to replace the files again.

**Comment by Fenrirthviti** [comment] 2020-10-08 07:14
To be frank, audio only streaming to ice cast through custom ffmpeg output mode is square in unsupported territory. That said, this doesn't sound like a bug but more likely that we fixed a bug that was previously allowing for abuse of the custom ffmpeg output mode. Would need a log to see what is actually going on.

**Comment by sabotagebeats** [comment] 2020-10-08 07:15
not sure how settings available in the stock version of OBS crashing and saying "theora not available" would be a "feature" not a bug...

**Comment by sabotagebeats** [comment] 2020-10-08 07:17
I also get random crashes and not working when I tried with this tutorial 
ogg has been the only stable video stream for icecast i've found so far
https://nwgat.ninja/quick-easy-streaming-webm-with-ffmpeg-icecast2/

**Comment by sabotagebeats** [comment] 2020-10-08 07:17
it seems like vp9 is broken

**Comment by sabotagebeats** [comment] 2020-10-08 07:20
here is the logs 

`23:30:12.532: Couldn't find encoder 'theora'
23:30:12.532: ffmpeg_data_init failed
23:30:12.545: ==== Recording Stop ================================================
23:30:14.830: Couldn't find encoder 'theora'
23:30:14.830: ffmpeg_data_init failed
23:30:14.847: ==== Recording Stop ================================================
23:30:38.857: Couldn't find encoder 'theora'
23:30:38.857: ffmpeg_data_init failed
23:30:38.869: ==== Recording Stop ================================================
23:30:43.298: ==== Shutting down `

**Comment by sabotagebeats** [comment] 2020-10-08 07:27
this might be the issue: https://stackoverflow.com/questions/19454509/ffmpeg-unable-to-find-encoder-libvorbis
`Your ffmpeg build is not compiled with --enable-libvorbis which is required if you want libvorbis support in ffmpeg`

you would need to enable libvorbis when compiling OBS distribution.

**Comment by Fenrirthviti** [comment] 2020-10-08 07:35
Custom ffmpeg output mode is provided as an advanced output option with no warranty or guarantee. It doesn't sanity check any settings or check for availability of specific options. The mode in general is effectively unsupported, and even further so if you're replacing the distributed versions of ffmpeg. As mentioned before, streaming audio only to ice cast is already an abuse of what OBS was designed to do. I am not trying to dismiss the issue here, just explaining the reality of the situation, and that this is something we might not have any interest or desire to spend time on fixing.

Also, when asked for a log file, please provide the full log and not just the sections you feel are relevant.

**Comment by Fenrirthviti** [comment] 2020-10-08 07:37
As an aside, we do compile ffmpeg with vorbis enabled, per our CI scripts here: https://github.com/obsproject/obs-deps/blob/master/build-package-deps-osx.sh#L297-L315

**Comment by sabotagebeats** [comment] 2020-10-08 08:18
@Fenrirthviti here I have removed only a portion for privacy reasons but this log should contain all the relevant information that you need. 

`23:29:57.120: CPU Name: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
23:29:57.120: CPU Speed: 3504MHz
23:29:57.120: Physical Cores: 4, Logical Cores: 4
23:29:57.120: Physical Memory: 32653MB Total, 10465MB Free
23:29:57.120: Windows Version: 10.0 Build 19042 (release: 2009; revision: 546; 64-bit)
23:29:57.120: Running as administrator: false
23:29:57.120: Aero is Enabled (Aero is always on for windows 8 and above)
23:29:57.121: Windows 10 Gaming Features:
23:29:57.121: 	Game DVR: On
23:29:57.123: Sec. Software Status:
23:29:57.128: 	Microsoft Defender Antivirus: enabled (AV)
23:29:57.128: 	Windows Firewall: enabled (FW)
23:29:57.129: Current Date/Time: 2020-10-07, 23:29:57
23:29:57.129: Browser Hardware Acceleration: true
23:29:57.129: Portable mode: false
23:29:57.747: OBS 26.0.2 (64-bit, windows)
23:29:57.747: ---------------------------------
23:29:57.748: ---------------------------------
23:29:57.748: audio settings reset:
23:29:57.748: 	samples per sec: 48000
23:29:57.748: 	speakers:        2
23:29:57.750: ---------------------------------
23:29:57.750: Initializing D3D11...
23:29:57.750: Available Video Adapters: 
23:29:57.754: 	Adapter 0: Radeon RX 580 Series
23:29:57.754: 	  Dedicated VRAM: 4273827840
23:29:57.754: 	  Shared VRAM:    4234782720
23:29:57.754: 	  PCI ID:         1002:67df
23:29:57.755: 	  Driver Version: 27.20.1034.6
23:29:57.755: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=59, name=LG IPS FULLHD
23:29:57.755: 	Adapter 1: Intel(R) HD Graphics 530
23:29:57.755: 	  Dedicated VRAM: 134217728
23:29:57.755: 	  Shared VRAM:    4234782720
23:29:57.755: 	  PCI ID:         8086:1912
23:29:57.756: 	  Driver Version: 27.20.100.8682
23:29:57.756: 	  output 0: pos={-1920, 0}, size={1920, 1080}, attached=true, refresh=59, name=LG IPS FULLHD
23:29:57.756: 	Adapter 2: Radeon RX 580 Series
23:29:57.756: 	  Dedicated VRAM: 4273827840
23:29:57.756: 	  Shared VRAM:    4234782720
23:29:57.756: 	  PCI ID:         1002:67df
23:29:57.757: 	  Driver Version: 27.20.1034.6
23:29:57.761: Loading up D3D11 on adapter Radeon RX 580 Series (0)
23:29:57.807: D3D11 loaded successfully, feature level used: b000
23:29:57.807: DXGI increase maximum frame latency success
23:29:57.807: D3D11 GPU priority setup failed (not admin?)
23:29:58.338: ---------------------------------
23:29:58.338: video settings reset:
23:29:58.338: 	base resolution:   1920x1080
23:29:58.338: 	output resolution: 1920x1080
23:29:58.338: 	downscale filter:  Bicubic
23:29:58.338: 	fps:               30/1
23:29:58.338: 	format:            NV12
23:29:58.338: 	YUV mode:          709/Partial
23:29:58.338: NV12 texture support enabled
23:29:58.340: Audio monitoring device:
23:29:58.340: 	name: Audio 8 DJ (Ch D, Out 7|8) (Audio 8 DJ WDM Audio)
23:29:58.340: 	id: {0.0.0.00000000}.{6f396f51-fe84-48a1-8cf9-2ef774151f81}
23:29:58.340: ---------------------------------
23:29:58.355: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
23:29:58.358: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
23:29:58.936: [AMF] Version 2.7.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.17.0, Library: 1;4;17;0;20.10;202008211317;CL#2161569).
23:29:59.084: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'Radeon RX 580 Series (VEN_1002/DEV_67df/SUB_8a921462/REV_00e7)':
23:29:59.084:   H264/AVC: Supported
23:29:59.084:   H265/HEVC: Supported
23:29:59.084: 
23:29:59.235: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'Radeon RX 580 Series (VEN_1002/DEV_67df/SUB_8a921462/REV_00e7)':
23:29:59.235:   H264/AVC: Supported
23:29:59.235:   H265/HEVC: Supported
23:29:59.235: 
23:29:59.269: [obs-browser]: Version 2.8.7
23:29:59.414: Couldn't find VLC installation, VLC video source disabled
23:29:59.433: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
23:29:59.444: No blackmagic support
23:29:59.460: ---------------------------------
23:29:59.460:   Loaded Modules:
23:29:59.461:     win-wasapi.dll
23:29:59.461:     win-mf.dll
23:29:59.461:     win-ivcam.dll
23:29:59.461:     win-dshow.dll
23:29:59.461:     win-decklink.dll
23:29:59.461:     win-capture.dll
23:29:59.461:     vlc-video.dll
23:29:59.461:     text-freetype2.dll
23:29:59.461:     rtmp-services.dll
23:29:59.461:     obs-x264.dll
23:29:59.461:     obs-vst.dll
23:29:59.461:     obs-transitions.dll
23:29:59.461:     obs-text.dll
23:29:59.461:     obs-qsv11.dll
23:29:59.461:     obs-outputs.dll
23:29:59.461:     obs-filters.dll
23:29:59.461:     obs-ffmpeg.dll
23:29:59.461:     obs-browser.dll
23:29:59.461:     image-source.dll
23:29:59.461:     frontend-tools.dll
23:29:59.461:     enc-amf.dll
23:29:59.461:     decklink-ouput-ui.dll
23:29:59.461:     coreaudio-encoder.dll
23:29:59.461: ---------------------------------
23:29:59.461: ==== Startup complete ===============================================
23:30:12.532: Couldn't find encoder 'theora'
23:30:12.532: ffmpeg_data_init failed
23:30:12.545: ==== Recording Stop ================================================
23:30:14.830: Couldn't find encoder 'theora'
23:30:14.830: ffmpeg_data_init failed
23:30:14.847: ==== Recording Stop ================================================
23:30:38.857: Couldn't find encoder 'theora'
23:30:38.857: ffmpeg_data_init failed
23:30:38.869: ==== Recording Stop ================================================
23:30:43.298: ==== Shutting down ==================================================
23:30:43.372: WASAPI: Device 'Realtek HD Audio 2nd output (Realtek(R) Audio)' Terminated
23:30:43.379: WASAPI: Device 'Realtek HD Audio 2nd output (Realtek(R) Audio)' Terminated
23:30:43.385: WASAPI: Device 'Microphone (Realtek(R) Audio)' Terminated
23:30:43.392: All scene data cleared
23:30:43.392: ------------------------------------------------
23:30:43.707: [Scripting] Total detached callbacks: 0
23:30:43.774: Freeing OBS context data
23:30:43.815: == Profiler Results =============================
23:30:43.815: run_program_init: 3706.38 ms
23:30:43.816:  ┣OBSApp::AppInit: 94.418 ms
23:30:43.816:  ┃ ┗OBSApp::InitLocale: 1.76 ms
23:30:43.816:  ┗OBSApp::OBSInit: 3521.57 ms
23:30:43.816:    ┣obs_startup: 8.72 ms
23:30:43.816:    ┗OBSBasic::OBSInit: 2894.64 ms
23:30:43.816:      ┣OBSBasic::InitBasicConfig: 0.67 ms
23:30:43.816:      ┣OBSBasic::ResetAudio: 0.339 ms
23:30:43.816:      ┣OBSBasic::ResetVideo: 592.286 ms
23:30:43.816:      ┣OBSBasic::InitOBSCallbacks: 0.008 ms
23:30:43.816:      ┣OBSBasic::InitHotkeys: 0.041 ms
23:30:43.816:      ┣obs_load_all_modules: 1119.92 ms
23:30:43.816:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 10.555 ms
23:30:43.816:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.655 ms
23:30:43.816:      ┃ ┣obs_init_module(enc-amf.dll): 874.695 ms
23:30:43.816:      ┃ ┣obs_init_module(frontend-tools.dll): 4.29 ms
23:30:43.816:      ┃ ┣obs_init_module(image-source.dll): 0.005 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-browser.dll): 0.55 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 1.266 ms
23:30:43.816:      ┃ ┃ ┗nvenc_check: 1.247 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-filters.dll): 0.036 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-outputs.dll): 0.011 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-qsv11.dll): 113.356 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-text.dll): 0.573 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-transitions.dll): 0.009 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-vst.dll): 0.002 ms
23:30:43.816:      ┃ ┣obs_init_module(obs-x264.dll): 0.001 ms
23:30:43.816:      ┃ ┣obs_init_module(rtmp-services.dll): 2.568 ms
23:30:43.816:      ┃ ┣obs_init_module(text-freetype2.dll): 0.078 ms
23:30:43.816:      ┃ ┣obs_init_module(vlc-video.dll): 0.067 ms
23:30:43.816:      ┃ ┣obs_init_module(win-capture.dll): 3.321 ms
23:30:43.816:      ┃ ┣obs_init_module(win-decklink.dll): 22.687 ms
23:30:43.816:      ┃ ┣obs_init_module(win-dshow.dll): 8.093 ms
23:30:43.816:      ┃ ┣obs_init_module(win-ivcam.dll): 0.004 ms
23:30:43.816:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
23:30:43.816:      ┃ ┣obs_init_module(win-wasapi.dll): 0.009 ms
23:30:43.816:      ┃ ┗reset_win32_symbol_paths: 0.493 ms
23:30:43.816:      ┣OBSBasic::ResetOutputs: 0.774 ms
23:30:43.816:      ┣OBSBasic::CreateHotkeys: 0.045 ms
23:30:43.816:      ┣OBSBasic::InitService: 0.221 ms
23:30:43.816:      ┣OBSBasic::InitPrimitives: 0.197 ms
23:30:43.816:      ┗OBSBasic::Load: 770.369 ms
23:30:43.816: obs_hotkey_thread(25 ms): min=0.005 ms, median=0.009 ms, max=1.724 ms, 99th percentile=0.238 ms, 100% below 25 ms
23:30:43.816: audio_thread(Audio): min=0 ms, median=0.05 ms, max=9.21 ms, 99th percentile=0.304 ms
23:30:43.816: obs_graphics_thread(33.3333 ms): min=0.077 ms, median=1.382 ms, max=393.327 ms, 99th percentile=4.296 ms, 99.8511% below 33.333 ms
23:30:43.816:  ┣tick_sources: min=0.001 ms, median=0.03 ms, max=387.083 ms, 99th percentile=2.185 ms
23:30:43.816:  ┣output_frame: min=0.069 ms, median=0.579 ms, max=4.2 ms, 99th percentile=1.789 ms
23:30:43.816:  ┃ ┗gs_context(video->graphics): min=0.068 ms, median=0.579 ms, max=4.199 ms, 99th percentile=1.788 ms
23:30:43.816:  ┃   ┣render_video: min=0.01 ms, median=0.35 ms, max=3.958 ms, 99th percentile=1.342 ms
23:30:43.816:  ┃   ┃ ┗render_main_texture: min=0.003 ms, median=0.345 ms, max=3.448 ms, 99th percentile=1.337 ms
23:30:43.816:  ┃   ┗gs_flush: min=0.058 ms, median=0.212 ms, max=3.986 ms, 99th percentile=0.656 ms
23:30:43.816:  ┗render_displays: min=0 ms, median=0.716 ms, max=29.66 ms, 99th percentile=1.369 ms
23:30:43.816: =================================================
23:30:43.816: == Profiler Time Between Calls ==================
23:30:43.816: obs_hotkey_thread(25 ms): min=24.271 ms, median=25.527 ms, max=84.236 ms, 48.6412% within ±2% of 25 ms (0.554631% lower, 50.8042% higher)
23:30:43.816: obs_graphics_thread(33.3333 ms): min=0.708 ms, median=33.333 ms, max=393.334 ms, 90.462% within ±2% of 33.333 ms (4.61997% lower, 4.91803% higher)
23:30:43.816: =================================================
23:30:43.852: Number of memory leaks: 0
`

**Comment by timo** [comment] 2020-10-09 10:27
> As mentioned before, streaming audio only to ice cast is already an abuse of what OBS was designed to do.

i think sabotagebeats is trying to stream audio and video, why else would they want theora?

**Comment by sabotagebeats** [comment] 2020-10-19 07:41
> i think sabotagebeats is trying to stream audio and video, why else would they want theora?

yes.

**Comment by Fenrirthviti** [comment] 2020-10-19 19:49
Can you confirm the latest version of OBS Studio where this worked without requiring the ffmpeg libraries to be replaced?

**Comment by sabotagebeats** [comment] 2020-10-23 03:59
> Can you confirm the latest version of OBS Studio where this worked without requiring the ffmpeg libraries to be replaced?

no, it was some point last year. I can only relay that it used to work anecdotally.

**Comment by Fenrirthviti** [comment] 2020-10-23 04:43
Thanks, I think we can consider this not really a bug, but more of a request for support of Theora through custom ffmpeg output. In theory this should work on macOS with the current version of ffmpeg we use there.

**Comment by tormyvancool** [comment] 2020-10-23 22:54
This issue is occurring to me right now with OBS 26.0.2
Same identical.
I did install https://github.com/BtbN/FFmpeg-Builds/releases the shared ones, but it still don't find Theora

**Comment by Fenrirthviti** [comment] 2020-10-23 23:11
Again, this is not really an issue, but more that we don't build our ffmpeg deps with Theora support. I have a hard time believing that we ever did, honestly. There is no bug here to fix, and this should really be submitted to the Ideas page as a feature request. That said, we are working on updating our dependencies for Windows and macOS for the next release, and I have it marked as a note to add Theora to our ffmpeg compile flags. I'm going to close this issue for now as it's not a bug.

**Closed by Fenrirthviti** 2020-10-23 23:11 UTC
