### ISSUE TITLE
OBS Crash on Audio Input assignement from Multi-Track Audio Source (MacOS)

### ISSUE THREAD

**Issue by PhatAdam** [obsproject/obs-studio#10220] opened 2024-02-08 21:45 UTC
### Operating System Info

MacOS 14.3

### Other OS

M1 Pro 16"

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://drive.google.com/drive/folders/1p7j3dHfH0EJZgnqiZ552styZdfQsp1NW?usp=sharing

### Expected Behavior

I created a blank scene, added an audio input capture - selected the RODECaster Pro II Multi-track - instant crash.

### Current Behavior

Just a hard app crash -- it does come back up - and happens again when you reselect the same audio source

### Steps to Reproduce

1. Add new OBS to App, Open
2. Add new Audio Input Capture 
3. Select Multi-Track device -- I used RodeCaster Pro 2 - in USB MultiTrack Settings
4. Crash.
5. OBS relaunches on default audio -- and loops if you select the same device again.
[2024-02-08 14-48-21.txt](https://github.com/obsproject/obs-studio/files/14214960/2024-02-08.14-48-21.txt)
[2024-02-08 14-51-13.txt](https://github.com/obsproject/obs-studio/files/14214961/2024-02-08.14-51-13.txt)
[2024-02-08 14-54-29.txt](https://github.com/obsproject/obs-studio/files/14214962/2024-02-08.14-54-29.txt)
[2024-02-08 14-54-57.txt](https://github.com/obsproject/obs-studio/files/14214963/2024-02-08.14-54-57.txt)

...

### Anything else we should know?

None

**Comment by omik** [comment] 2024-02-14 10:08
Same behavior here. OBS crashes when I add the rodecaster duo as a source with the beta versions.

**Comment by PatTheMav** [comment] 2024-02-14 17:09
To investigate this we need the associated crash logs - you can find past crash reports in Console.app: https://support.apple.com/guide/console/reports-cnsl664be99a/mac

**Comment by PhatAdam** [comment] 2024-02-15 14:14
Gladly. It’s easily replicated will get for you.

**Comment by PhatAdam** [comment] 2024-02-16 19:29
> To investigate this we need the associated crash logs - you can find past crash reports in Console.app: https://support.apple.com/guide/console/reports-cnsl664be99a/mac
> 
> Do not post crash reports as a GitHub comment - instead export the crash report as a text file and upload it to your comment.

https://drive.google.com/drive/folders/1p7j3dHfH0EJZgnqiZ552styZdfQsp1NW?usp=sharing

**Comment by PatTheMav** [comment] 2024-02-16 19:42
Duplicate of https://github.com/obsproject/obs-studio/issues/10017.

**Closed by PatTheMav** 2024-02-16 19:42 UTC

**Comment by PhatAdam** [comment] 2024-03-19 16:50
This is confirmed fixed in the full release of 30.1.0 // and channel selecting on the multi-track for the rodecaster pro 2 works great!
