### ISSUE TITLE
Virtual camera gets green after update from last version

### ISSUE THREAD

**Issue by ICEDStriker** [obsproject/obs-studio#7452] opened 2022-09-24 12:42 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

i dont have it sry

### Expected Behavior

virtual camera works normal like before

### Current Behavior

virtual camera works, but the picture is only green (you can see the picture thats supposed to be shown, but its only green)

### Steps to Reproduce

1. Install / update to newest obs version (at time of writing)
2. select a ascene with a video or some input playing
3. start virtual camera and look at the image

**Comment by MattyFresh68** [comment] 2022-09-24 14:20
A log file would probably be a bit useful here. Top of obs. Help > log files > upload current log

**Comment by Fenrirthviti** [comment] 2022-09-24 14:23
Duplicate of #7442

**Closed by Fenrirthviti** 2022-09-24 14:23 UTC
