### ISSUE TITLE
Monochrome cursors on Windows are recorded as all-black instead of the correct color

### ISSUE THREAD

**Issue by caesay** [obsproject/obs-studio#6794] opened 2022-07-23 11:09 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

n/a

### Expected Behavior

When a monochrome cursor is visible on top of a black background, it should appear white in the OBS recording

### Current Behavior

When a monochrome cursor is visible on top of a dark background, it currently appears black. It will be completely invisible on a black background, or very hard to see on a dark grey background.

### Steps to Reproduce

1. Start recording in OBS on Windows
2. Hover cursor over any application that uses a dark background and a monochrome cursor such as the I-Beam (Visual Studio dark mode, VS Code, etc)
3. Observe that the cursor recorded by OBS is nearly invisible because it is black instead of white

### Anything else we should know?

There are two types of cursors in windows: coloured, and monochrome. 

For coloured cursors, there are two bitmaps (`hbmColor` and `hbmMask`) and the usage is straight forward. This is working correctly in OBS.
![image of coloured cursors](https://user-images.githubusercontent.com/1287295/180602254-03081a38-3fe8-4cf0-a51b-c524dee554dc.png)

For monochrome cursors, there is only a single bitmap (`hbmMask`). This is currently **not working** in OBS, it will always be shown as black and will not correctly invert what is underneath it.
![image of monochrome cursor](https://user-images.githubusercontent.com/1287295/180602276-6efbc526-a240-4d6a-bef5-307ed4994dc0.png)

When drawing the cursor on to the captured surface, the top half of this monochrome cursor must first be applied with an AND operation to the recorded frame. In the example image provided above, this is a no-op because it is all white. The bottom half of the monochrome bitmap must then be applied to the recorded frame as XOR operation, so it will invert any colour underneath it. Using this technique a monochrome cursor is capable of drawing always-black, always-white, or background-inverted pixels. 

For example:
 - A pixel that is black in both the top and bottom half will always be black in the final image
 - A pixel that is black in the top and white in the bottom will always be white in the final image
 - A pixel that is white in the top and white in the bottom will invert (XOR) the colour underneath it.
 - A pixel that is white in the top and black in the bottom is a no-op.

The [current implementation of `cursor_capture_icon`](https://github.com/obsproject/obs-studio/blob/db8145e8a2f1e1d0a3cba671504f6a56c2e2200c/plugins/win-capture/cursor-capture.c#L159) seems to flatten both halves of the monochrome cursor in `copy_from_mask` into a single bitmap of half the height which is then returned in `cursor_data`. It's important however that both the AND and XOR layers of the monochrome cursor are preserved until they are drawn on to the recording.

**Comment by mufunyo** [comment] 2022-07-23 13:58
Duplicate of #3454.

**Closed** 2022-11-18 04:54 UTC
Labels: Windows, Fix available
