### ISSUE TITLE
OBS Segfaulting on click for  "Browse" of an Image source

### ISSUE THREAD

**Issue by hikkamorii** [obsproject/obs-studio#10708] opened 2024-05-22 22:26 UTC
### Operating System Info

Other

### Other OS

OpenSUSE Tumbleweed, KDE 6.0.4

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/lDfh6DINFiNHos5g

### Expected Behavior

OBS Should spawn file picker to pick an image for the Image source

### Current Behavior

OBS Segfaults

### Steps to Reproduce

1. Add an Image source
2. Click "Browse" to pick an image
3. OBS will freeze for a second, and crash.

### Anything else we should know?

This issue happens with Flatpak build too, and likely is related to Qt. 

My DE:
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0

Backtrace below.
[crash.log](https://github.com/obsproject/obs-studio/files/15409234/crash.log)

**Comment by mihawk90** [comment] 2024-05-22 22:30
See #10683

**Comment by hikkamorii** [comment] 2024-05-22 22:34
Thanks,  didn't see that issue! Hopefully new KDE Framework version will be released soon.

**Comment by hikkamorii** [comment] 2024-05-22 22:39
I noticed KDE guys talking about this being an issue with palette, so I tried setting theme to "System" instead of any of the  OBS specific ones. It actually fixed the issue, even though OBS now looks quite ugly 😄

**Comment by derrod** [comment] 2024-05-22 23:05
Duplicate of #10683

**Closed by derrod** 2024-05-22 23:05 UTC
