### ISSUE TITLE
Installer is blocked by Playnite processes (CefSharp.BrowserSubprocess)

### ISSUE THREAD

**Issue by Murazaki** [obsproject/obs-studio#8883] opened 2023-05-10 13:59 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

N/A

### Expected Behavior

While installing OBS should ask user to close apps by naming them, and provide them the choice to shut them down.

### Current Behavior

Since several updates, OBS can't update while Playnite is running, asking the user to close apps using `CefSharp.BrowserSubprocess`.

This blocks automated installation processes like Winget package manager.

### Steps to Reproduce

1.Install Playnite
2.Run Playnite
3.Install OBS

**Comment by notr1ch** [comment] 2023-05-10 14:17
It sounds like the current behavior matches the expected behavior. The NSIS based installer cannot overwrite files that are in use by other applications, and force-closing them without prompting the user could lead to data loss.

**Closed by notr1ch** 2023-05-10 14:17 UTC

**Comment by Destroy666x** [comment] 2024-03-13 18:38
@notr1ch there's A LOT you can do and you only close issues created by people about this nonsense. No other application that I used, and I used hundreds on Windows, has this miserable of install/upgrade process, TBH. Here I am struggling again trying to find which C# app to close that uses some, who knows which, files from OBS installation.

Here's a list of things you could do:
- option to autokill the processes that OBS doesn't like (this is a must have for package managers like choco IMO, that currently are unusable with OBS)
- option to kill them with a button instead, lots of installers have that
- listing the PID together with/instead of process names - PIDs are unique, process names are clearly not. Just check the below screenshot and tell me this is good UX:
![image](https://github.com/obsproject/obs-studio/assets/3606072/1b5eed6f-d60c-4a6a-9412-3feac877588a)

**Comment by Fenrirthviti** [comment] 2024-03-13 18:54
As had been mentioned, most of this is not possible with this specific instance. We're already doing what we can with the APIs we have access to.

> * option to autokill the processes that OBS doesn't like (this is a must have for package managers like choco IMO, that currently are unusable with OBS)

We have no official packages in chocolatey, so supporting their installation requirements isn't a priority for us. However, even if we added an autokill this doesn't solve the problem of us not being able to tell what the process is we even need to kill.

> * option to kill them with a button instead, lots of installers have that

Again, same issue. The problem is with specific other applications, not with OBS here.

> * listing the PID together with/instead of process names - PIDs are unique, process names are clearly not. Just check the below screenshot (especially the scrollbar, I closed a few applications before that BTW) and tell me this is good UX:

PID could be useful, but is also irrelevant to a standard end user, and someone packaging OBS for deployment shouldn't be relying on our end-user installer in the first place. Probably harmless to add, but I can't make any promises that we'll assign our limited resources to it.

> * listing the files that are being used

Also probably irrelevant. Knowing what OBS file is being locked doesn't help in any meaningful way to an end user. It doesn't matter that graphicshook64.dll is in-use, that provides nothing helpful to someone who doesn't already understand exactly what and how to look for this anyway.

> I don't know why this issue is swept under the rug. Of course autoupdater helps, but only with e.g. a single user installation, not with automation of installation on 100 machines in a company, let's say.

Nothing is swept under the rug, but you need to understand that we are an open source project with an extremely limited number of developers, and we need to spend our time carefully, and focus efforts on improvements that benefit the most users we can. Issues like this are pretty much only brought up by sysadmins who work in managed environments that already have tools far better suited to handle this than asking us to write a custom, bespoke plugins for NSIS.

**Comment by journeym** [comment] 2024-04-15 13:16
Yeah yeah "that's not our problem" behaivior instead of fixing your shitty intaller.
