### ISSUE TITLE
Setting push to mute delay timer doesn't save the settings linux

### ISSUE THREAD

**Issue by JoneKone** [obsproject/obs-studio#3467] opened 2020-09-13 15:50 UTC
Operating system and version: Linux Ubuntu 20.04
OBS Studio version: 25.0.8-0obsproject1~focal

## Expected Behavior
When in GUI in Settings in Audio in Hotkeys Enabling push to mute and then setting Push-to-mute delay 100ms it should keep the setting after pushing apply. And change value in config file.

## Current Behavior
set Push-to-mute delay 100ms and push apply button the delay turns back to 0 ms.
log [https://hastebin.com/eregocehuv.sql](https://hastebin.com/eregocehuv.sql)
## Steps to Reproduce
1. Enable Push to mute on input or output device.
2. Change Push to mute delay to 100ms.
3. Press apply.

## Additional information
Changing the value from Untitled.json config file changes the value in GUI but doesn't take effect. And changes back to 0 ms after pushing ok.

**Comment by kkartaltepe** [comment] 2021-01-28 07:27
I could replicate it on linux, it seems it could also be replicated on windows.

**Comment by Xaymar** [comment] 2021-01-28 07:28
Replicated on Windows. [Found a thread from 2013 with a reply in 2017 documenting a similar if not the same issue.](https://obsproject.com/forum/threads/push-to-talk-delay-resetting-itself.4588/)

**Comment by Xaymar** [comment] 2021-01-28 07:34
Affects both Push to Mute and Push to Talk.

**Comment by WizardCM** [comment] 2021-01-28 07:40
Code for reference:

https://github.com/obsproject/obs-studio/blob/d2ca8b5d908955cd6d4c054dff2819809841bc81/UI/window-basic-settings.cpp#L2304

https://github.com/obsproject/obs-studio/blob/d2ca8b5d908955cd6d4c054dff2819809841bc81/UI/window-basic-settings.cpp#L3566

**Comment by Fenrirthviti** [comment] 2021-01-28 15:11
Duplicate of #4143

Closing that one as this one has more discussion despite being the newer issue.

**Closed** 2022-01-08 06:38 UTC
Labels: Windows, Linux, Confirmed
