### ISSUE TITLE
Hotkeys trigger even when extra meta/modifier keys are held

### ISSUE THREAD

**Issue by igavronski** [obsproject/obs-studio#4408] opened 2021-03-29 18:10 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

there is no need

### Expected Behavior

1) Assign F3 to start recording
2) Assign ALT+F3 to start virtual cam
3) When pressing ALT+F3, start virtual cam but not start recording.

### Current Behavior

Because OBS treats ALT+F3 as F3 as well, both start v cam and start recording fire when hitting ALT+F3

### Steps to Reproduce

Already described in expected behaviour.

### Anything else we should know?

Support channel members in Discord said it is expected behaviour. I politely discord.

**Comment by dodgepong** [comment] 2021-03-29 18:11
This would be better submitted on https://ideas.obsproject.com/ since this is technically intended behavior by Qt.

**Comment by Fenrirthviti** [comment] 2021-03-30 00:48
Going to re-open this and modify the request, as it's not very explicit on what's going on here, but this is something we should track and fixed. Original Mantis ticket here: https://obsproject.com/mantis/view.php?id=925

**Comment by igavronski** [comment] 2021-03-30 10:44
@Fenrirthviti thanks Joel. I guess treating both the key and alt+key the same way is not the expected behaviour for any user, regardless of Qt's defaults.

**Comment by berghetti** [comment] 2021-04-02 14:19
Hi,
on my system
using `obs --platform wayland` , keyboard shortcut not working,
all fields appear blank and I cannot assign any key.

OBS Studio - 26.1.2-344-gbaf980f7a (linux) (builded from source)
Linux debian 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux
debian_version: bullseye/sid

**Comment by Fenrirthviti** [comment] 2021-04-02 18:30
> Hi,
> on my system
> using `obs --platform wayland` ,
> I get the same behavior.
> 
> OBS Studio - 26.1.2-344-gbaf980f7a (linux) (builded from source)
> Linux debian 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux
> debian_version: bullseye/sid

This does not appear related to this bug report, please use the support channels (Discord/Forums) for more assistance instead of posting on an unrelated issue report.

**Comment by Fenrirthviti** [comment] 2021-04-02 18:40
Looks like you edited the original post. If you are unable to set hotkeys entirely, as your original post stated, you should use the support channels.

**Comment by lindenkron** [comment] 2021-04-25 15:09
Have this happening on Windows 10 OBS 26.1.1 64-bit as well. Still. I believe I reported this sometime on mantis a few years ago and it's still occurring.

It's obstructing to set Shift + F1, and have the F1 hotkey fire when you're clearly pressing Shift + F1 and not F1. Makes hotkey management painful, intentional behavior from QT or not - this shouldn't be how hotkeys behave.

**Comment by Fenrirthviti** [comment] 2021-05-06 14:41
Please note that anyone working to fix this issue should also check if the fix corrects #4655, as they should be caused by the same underlying issue with how hotkeys are being triggered.

**Comment by hoffr** [comment] 2021-05-06 19:46
from #4655 
> 
> 
> It might seem different, but this is the exact same issue where hotkeys are not checking for their own exclusivity, which causes all sorts of weirdness to occur. "Modifier" keys are really any key held in addition to another. "L" could be considered a modifier key as far as the code is concerned. It's all the same underlying issue with how the Qt hotkey system (which is what we use) functions by default. If this turns out to not be solved by fixing #4408, we can reopen.

I'll reiterate though that in OBS I'm not able to assign a hotkey by pressing two keys at once unless one is a 'known' modifier (ctrl, shift, alt, etc), so creating a hypothetical hotkey L+G will set it to L on press of L, and with L held, on press of G it will be set only to G. Not sure if it's worth mentioning though

**Comment by RobMayer** [comment] 2021-09-27 18:57
I hate to bump this, but I've been smacking my head against this issue for weeks now. Would very much love to see the PR merged.

**Comment by Fenrirthviti** [comment] 2021-09-27 19:00
We are planning on merging the PR, it just currently has some design issues that need to be addressed first. v27.1 has been in beta testing for a few weeks now, so additional reviews and testing has slowed down a bit. It's definitely on our radar.

**Closed** 2022-05-29 00:13 UTC
Labels: Confirmed
