### ISSUE TITLE
Crash on start.

### ISSUE THREAD

**Issue by safocl** [obsproject/obs-studio#8107] opened 2023-01-21 10:32 UTC
### Operating System Info

Other

### Other OS

Archlinux

### OBS Studio Version

29.0.0

### OBS Studio Log URL

http://0x0.st/oh3D.txt

### OBS Studio Crash Log URL

http://0x0.st/oh3k.txt

### Expected Behavior

normal start

### Current Behavior

crash on run

### Steps to Reproduce

1. run `obs` (in the terminal or from GUI menu)

### Anything else we should know?

it is on wayland session, but it is olso on xorg session.

**Comment by tytan652** [comment] 2023-01-21 10:36
Duplicate of #8056

**Closed by tytan652** 2023-01-21 10:36 UTC
