### ISSUE TITLE
Recording stops on its own about once every 3-12 recordings

### ISSUE THREAD

**Issue by dege13** [obsproject/obs-studio#9363] opened 2023-08-04 17:03 UTC
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/JvYjz1SdD9NAyI4w

### Expected Behavior

I expect recording to continue until it is manually stopped, stopped by the Output Timer, or a fille hard drive.

### Current Behavior

The recording sometimes stops on it's own. The resulting file is 705kb or 717kb, depending on the encoder used.
Image of the issue in OBS: [https://imgur.com/a/AmxAqCa](url)

I have reproduced on OBS 29.0.2 up to 29.1.3, and back as far as OBS 27.2.4.
I have four computers, each running multiple OBS instances, recording several hundred VHS tapes.

When the issues happens on one OBS instance, it typically happens after the same number of recordings on the other OBS instances on the same machine (assuming all OBS instances were started at the same time).

### Steps to Reproduce

1. Open OBS studio
2. Open Output Timer
3. Set record timer for 10 seconds (just to make repeating fast)
4. Start recording with output timer
5. Wait for the issue to happen or the timer to stop
6. Repeat until the issue happens
(You can identify the issue by the Output Timer showing the Stop button for recording, but the main OBS window showing the Start Recording button)
Log 1: [2023-02-24 08-24-09.txt](https://github.com/obsproject/obs-studio/files/12262749/2023-02-24.08-24-09.txt)
Screenshot: ![Capture](https://github.com/obsproject/obs-studio/assets/3587941/515745e6-e803-4794-870a-5625a372c07d)
Log 2: [2023-02-25 08-55-52.txt](https://github.com/obsproject/obs-studio/files/12262738/2023-02-25.08-55-52.txt)

Also tried default, clean OBS install on new OS. Issue still happens.
Happens with NVEMC H.264 and x264.

### Anything else we should know?

Log lines which may be relevant for three different logs of the issue happening three different times on two different computers:
`08:46:16.170: ==== Recording Start ===============================================
08:46:16.170: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/chew/Videos/2023-02-25 08-46-16.mkv'...
08:46:16.709: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/chew/Videos/2023-02-25 08-46-16.mkv' stopped
08:46:16.709: Output 'adv_file_output': stopping
08:46:16.709: Output 'adv_file_output': Total frames output: 1
08:46:16.709: Output 'adv_file_output': Total drawn frames: 13
08:46:16.710: ==== Recording Stop ================================================
08:46:16.739: warning: 2 frames left in the queue on closing
08:48:37.906: ==== Shutting down ==================================================`

`07:44:49.010: ==== Recording Start ===============================================
07:44:49.010: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/chew/Videos/2023-02-27 07-44-48.mkv'...
07:44:49.548: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/chew/Videos/2023-02-27 07-44-48.mkv' stopped
07:44:49.548: Output 'adv_file_output': stopping
07:44:49.548: Output 'adv_file_output': Total frames output: 1
07:44:49.548: Output 'adv_file_output': Total drawn frames: 13
07:44:49.548: ==== Recording Stop ================================================
07:44:49.577: warning: 2 frames left in the queue on closing
08:01:42.834: ==== Shutting down ==================================================`

`08:20:29.685: ==== Recording Start ===============================================
08:20:29.685: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/dege1/Videos/2023-02-28 08-20-29.mkv'...
08:20:30.735: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/dege1/Videos/2023-02-28 08-20-29.mkv' stopped
08:20:30.735: Output 'adv_file_output': stopping
08:20:30.735: Output 'adv_file_output': Total frames output: 1
08:20:30.735: Output 'adv_file_output': Total drawn frames: 31
08:20:30.736: ==== Recording Stop ================================================
08:20:30.771: warning: 2 frames left in the queue on closing`

Latest production of the issue:
https://obsproject.com/logs/JvYjz1SdD9NAyI4w
Screen recording: https://github.com/obsproject/obs-studio/assets/3587941/54346e29-f83c-4e1a-999e-7c918a900ac2
`12:57:00.806: ==== Recording Start ===============================================
12:57:00.806: [ffmpeg muxer: 'simple_file_output'] Writing file 'C:/Users/dege1/Videos/2023-08-04 12-57-00.mkv'...
12:57:01.866: [ffmpeg muxer: 'simple_file_output'] Output of file 'C:/Users/dege1/Videos/2023-08-04 12-57-00.mkv' stopped
12:57:01.866: Output 'simple_file_output': stopping
12:57:01.866: Output 'simple_file_output': Total frames output: 1
12:57:01.866: Output 'simple_file_output': Total drawn frames: 32
12:57:01.866: ==== Recording Stop ================================================`

I tried getting help on the forums, but there was not much response. [https://obsproject.com/forum/threads/recording-with-output-timer-sometimes-stops-on-its-own.164668/](https://obsproject.com/forum/threads/recording-with-output-timer-sometimes-stops-on-its-own.164668/)

**Comment by RytoEX** [comment] 2023-08-04 17:10
Likely a duplicate of #9210 or #6558.

**Comment by gxalpha** [comment] 2023-08-10 19:11
Duplicate of https://github.com/obsproject/obs-studio/issues/6558

**Closed by gxalpha** 2023-08-10 19:11 UTC

**Comment by dege13** [comment] 2023-08-10 19:47
For context, this happens every time OBS is opened and you do 3~12 recordings in that session. It is not an intermittent issue.

**Comment by RytoEX** [comment] 2023-08-10 20:04
> For context, this happens every time OBS is opened and you do 3~12 recordings in that session. It is not an intermittent issue.

We still believe the core issue to essentially be the same as #6558, and we'll investigate further there.
