### ISSUE TITLE
PipeWire capture glitches on cursor movement with KDE Plasma

### ISSUE THREAD

**Issue by cooltyp100** [obsproject/obs-studio#8630] opened 2023-04-02 19:19 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/VBrVVkirFbKkWiOr

### Expected Behavior

PipeWire screen and window capture work normally without glitches. (Like in 29.0.2 and previous version)

### Current Behavior

With the PipeWire window and screen capture, while moving the cursor over the captured window/screen, previous/old frames show up.

### Steps to Reproduce

1. Start a screen or window capture (whether "Show cursor" is checked doesn't matter)
2. Move cursor inside region of captured screen/window (for window capture the window doesn't need to be in the foreground)
3. Observe previous/old frames flickering in and out while the cursor is moved

### Anything else we should know?

I already bisected the issue to commit e0a4d8628d287217cebc3d05d2077e1f0709b450. The problem seems to be that kwin sends cursor updates as separate pipewire buffers which only contain the cursor metadata and has the chunk size set to 0: https://invent.kde.org/plasma/kwin/-/blob/86a9796a5acde8004a5c357dad70f99442a5b351/src/plugins/screencast/screencaststream.cpp#L632. This causes obs to read and render stale/old frame data, whereas before the commit it always checked the chunk size.

I am unsure if obs or kwin are in the wrong here. According to the pipewire documentation mentioned in the commit message the chunk size should be ignored by obs for DMA-BUFs. So is kwin supposed to set `SPA_CHUNK_FLAG_CORRUPTED` for all chunks of a buffer when it only contains a cursor update or is sending just cursor movement updates without also updating the DMA-BUFs invalid behavior in general?

**Comment by CorneliusCornbread** [comment] 2023-04-04 03:14
Reproduced on Nobara, having the exact same issue.

https://user-images.githubusercontent.com/8294697/229677725-a7513c61-db43-4405-8933-76a842d93b7d.mp4

**Comment by GeorgesStavracas** [comment] 2023-04-04 13:09
@columbarius have you seen this? Seems like a regression from the buffer corruption bit

**Comment by columbarius** [comment] 2023-04-04 15:59
This is an error in kwin. `data[i].maxsize` and `data[i].chunk->size` are required for mapping the buffers via mmap and should not be used for buffer validity. DMABUFs should not be used and don't have a well defined size, as such those values can be 0. Kwin should be patched to use the correct flags, like it's done for [mutter](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2323)

**Comment by aleixpol** [comment] 2023-04-04 16:53
Well in this case no mmap should be happening. I looked at the MR you mentioned and I only see them marking as SPA_CHUNK_FLAG_CORRUPTED which is wrong because these are not corrupt but fully intended as such. Then there's the SPA_CHUNK_FLAG_EMPTY flag we could use I guess although the documentation says it might be for black frames. We could agree that this means "no payload delta", but that would need deciding.

The documentation is not especially clear on that front anyway: https://docs.pipewire.org/group__spa__buffer.html#gaa81bf44471d5f53efd5976eda41985f5

**Comment by columbarius** [comment] 2023-04-04 17:17
The `SPA_CHUNK_FLAG_EMPTY` was added on 24.06.2022. The usage of `SPA_CHUNK_FLAG_CORRUPTED` was discussed previous to that, since the expected behaviour of the client is the same: Don't import the buffer. What currently happens is kwin submitting an buffer with old content, which could be seen as a corruption of the time continuity, if I may allow myself that joke. Anyway the situation at that time was:

`SPA_META_HEADER_FLAG_CORRUPTED` = The whole buffer including cursor and content should not be used.
`SPA_CHUNK_FLAG_CORRUPTED` = Cursor and metadata may be valid, but content should be used. 

Would you suggest adding this convention to the PipeWire documentation, or would you propose a separate flag for this case?

**Comment by aleixpol** [comment] 2023-04-04 18:18
> Would you suggest adding this convention to the PipeWire documentation, or would you propose a separate flag for this case?

Either, if SPA_CHUNK_FLAG_CORRUPTED is already in use, it can make sense to just document it.

I'll send a MR to use SPA_CHUNK_FLAG_CORRUPTED in kwin as suggested for now.

FWIW, it's quite hard to get a full picture of how everything interacts in pipewire documentation. I've learned how it works mostly by looking at code and these details are easy to omit.

**Comment by aleixpol** [comment] 2023-04-04 18:25
https://invent.kde.org/plasma/kwin/-/merge_requests/3937
https://invent.kde.org/plasma/kpipewire/-/merge_requests/54

**Comment by kkartaltepe** [comment] 2023-04-05 01:48
How far back is this behavior in KDE? Do we need to worry about having a workaround for our PPA?

**Comment by aleixpol** [comment] 2023-04-05 19:03
> How far back is this behaviour in KDE?

Since the feature it once first added (5.20.0) I'd say.

> Do we need to worry about having a workaround for our PPA/Flatpak?

If adding an `|| chunk->size == 0` is possible and easy (see the kpipewire change), it would probably save users a few headaches. If you think it's too much then saying "please update to Plasma 5.27.5" wouldn't be the worst outcome either.

**Comment by columbarius** [comment] 2023-04-05 19:46
> it can make sense to just document it.

If you have a good wording please add this to the spa header.

**Comment by columbarius** [comment] 2023-04-05 21:10
> If adding an `|| chunk->size == 0`

I'm fine with this if it's expected to be dropped after some compatibility time. I'd like to drop https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/src/screencast/pipewire_screencast.c#L383.

**Comment by RytoEX** [comment] 2023-04-12 15:52
> https://invent.kde.org/plasma/kwin/-/merge_requests/3937 https://invent.kde.org/plasma/kpipewire/-/merge_requests/54

It seems that these have both been merged.

@GeorgesStavracas @kkartaltepe @columbarius is there anything we need to address on our side to more gracefully handle older versions without those fixes?

**Comment by kkartaltepe** [comment] 2023-04-14 02:47
I had meant to take a look around ubuntu to see what they backport and patch. So I took a look just now and probably yes we do need to handle the old KDE behavior until either we phase out ubuntu 22 support or someone backports the patches to kwin 5.24 and 5.18 make releases and those releases make it out to ubuntu.

**Closed** 2023-04-22 23:45 UTC
Labels: Linux, Fix available, Confirmed
