### ISSUE TITLE
Audio monitor for VLC Video Source has volume control and stop / play latency compared to the stream

### ISSUE THREAD

**Issue by conlanpatrek** [obsproject/obs-studio#9439] opened 2023-08-15 15:57 UTC
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/WLPOUx7NZBg4qfdq

### Expected Behavior

The monitor output of the playlist should update immediately when changing the playlist state (volume, play/stop, hide visibility).

The volume of the playlist in the monitor should reflect the volume that is being output.

### Current Behavior

The longer the stream is running, the more offset my playlist changes become in the monitor. The live stream, the audio mixer levels, and the recordings reflect the updates immediately, but the audio monitor won't update for... say... 30 seconds to a minute if OBS has been open for 4 hours.

I have had the program open for only as much time as it took to write the STR for this ticket, and I'm already about 12 seconds offset.

### Steps to Reproduce

1. Create a VLC Video Source, and point it at a folder with a bunch of audio files.
2. Turn on Loop Playlist, Shuffle Playlist, and set the Visibility Behavior to "Stop when not visible, restart when visible"
3. Configure the source to output to  Output and Monitor in the audio mixer settings
4. Let OBS sit open with this playlist running in a scene for an hour or so. It can be at zero volume. It just has to be playing I think.
5. Attempt to change the volume and listen to the monitor.

### Anything else we should know?

The issue becomes worse the longer OBS is open with a playlist playing. I can kind of reset the issue by turning the playlist invisible or stopping it, waiting the latency period for the playlist to update state in the monitor, and letting it sit for a bit without visibility before turning it back on.

I have had this issue since I started using OBS. I heavily use the monitors in my stream.

**Comment by Fenrirthviti** [comment] 2023-08-15 16:27
Duplicate of https://github.com/obsproject/obs-studio/issues/4531

**Closed by Fenrirthviti** 2023-08-15 16:27 UTC
