### ISSUE TITLE
XRGB/444 Video Capture Device is very Broken

### ISSUE THREAD

**Issue by EposVox** [obsproject/obs-studio#6566] opened 2022-05-31 02:44 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/w8cnyLGlwvM-LZFJ

### Expected Behavior

4:4:4 Video Capture via a XRGB-supporting capture card should work as normally, and has in years' past.
While a specific user's PCIe etc. bandwidth considerations need to be made, it should function and display properly.

### Current Behavior

Setting a capture device to XRGB at 4K60 or 1080p60 results in screen tearing, flickering, and other artifacts.
This affects both the OBS preview and the captured file.
Tested with Magewell Quad 1080p HDMI, AVerMedia Live Gamer 4K, AVerMedia Live Gamer Ultra, Elgato 4k60 Pro mk2.
Tested on Intel Z690 motherboard + 12900k and 1660 GPU, Threadripper 3970x + Titan RTX, and Threadripper 3960x + 2060 GPU. Same results in 4K and 1080p, same results on all 3 machines and all 4 different capture cards.

Setting to YUY2 (on cards that support it) seems to possibly still be affected as well, meanwhile NV12/auto seems to be fine, functioning as intended. 

Tested on OBS 27.1.3 as well as latest public update.

### Steps to Reproduce

1. Set OBS to 1080p 59.94 or 4K 59.94
2. Set OBS to RGB or I444 color space
3. Add Video Capture Device
4. Set Capture Device to 1080p 59.94/highest FPS or 4K 59.94/highest FPS
5. Set Capture Device to XRGB _(And possibly YUY2)_

### Anything else we should know?

Windows 11 is the only consistent denominator here across the machines that I could not change as a variable. (That and Nvidia GPUs, I suppose).

This issue does not impact VirtualDub2 for capture or preview.

[Here is a sample](https://youtu.be/JRvnh9E28G4) of the issue in a capture.
[Here is a capture](https://www.youtube.com/watch?v=4P-A1xTSRT4) of OBS and VirtualDub2 side by side (2 different capture cards, but both set to 444, and both would show the same issues in OBS)

**Comment by RytoEX** [comment] 2022-05-31 04:06
Does this affect _capture_ or _encoding_? this a duplicate of #6062 and #4631?

**Comment by EposVox** [comment] 2022-05-31 04:20
Affects both, as stated, seems to be completely irrelevant to either of those two, as my tests were primarily with utvideo via Simple mode (though NVENC did have the same issue).

**Comment by derrod** [comment] 2022-05-31 05:03
Just to clarify, this happens on both 27.2 and 27.1? Any idea what the last version that worked correctly is?

**Comment by derrod** [comment] 2022-05-31 09:35
Testing with my Live Gamer 4K on my Windows 10 machines and it seem perfectly fine (the odd dropped frame here or there is more likely due to my PC being kinda shit):

https://user-images.githubusercontent.com/3123295/171142530-4aec1eb0-be22-43aa-b5cd-e2f88d9ce95f.mp4

Unfortunately I don't have any desktops on Win 11 nor any external capture devices that do 444

**Comment by EposVox** [comment] 2022-05-31 20:31
Alright, I'm still getting the same issue with Live Gamer 4K and a fresh Windows 10 21H2 install on WRX80 (_plenty_ of PCIe bandwidth) with only it and a GPU installed.
I feel like I'm going crazy here.

**Comment by EposVox** [comment] 2022-05-31 22:59
OK so this MAY have been a Nvidia driver issue.
Updating drivers/testing further on test machine, I now _mostly_ have it down to where this only impacts the preview and is no longer present in the encode.
The tearing on preview is still a concern, it's acting like the GPU is struggling to keep up with rendering, despite sitting pretty at ~18% 3D load. 
Will keep poking at it, as this has been super weird.

**Comment by derrod** [comment] 2022-06-01 10:33
Alright, I believe @Fenrirthviti has a 4K60 Pro Mk.2 he could use to try to reproduce this issue on his machine. Also perhaps @jpark37 as I believe he also has a Live Gamer 4K/Ultra.  
Not sure if anybody has a system with an AMD graphics card to cross-check.

Perhaps you could also try and see what happens with current git master (https://obsbot.rodney.io/build/windows) in portable mode to start with a "clean" OBS.

**Comment by Fenrirthviti** [comment] 2022-07-16 05:33
Spoke about this, seems there's a lot going on outside OBS that is contributing to issues here. Going to close this for now, and will reopen if more info is uncovered.

**Closed by Fenrirthviti** 2022-07-16 05:33 UTC
Labels: Windows
