### ISSUE TITLE
obs frame obtaining randomly goes out of sync decays and then recovers ( no rendering encoding lag / no in game lag ) 

### ISSUE THREAD

**Issue by JackTheRipperGB** [obsproject/obs-studio#6437] opened 2022-05-08 14:34 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/forum/attachments/2022-04-29-15-56-05-txt.83083/

### Expected Behavior

For obs display non stuttering perfectly smooth image

### Current Behavior

So before i get told that my settings or smth incorrect, ive spend countless hours on obs windows support with no one seeing anything wrong in mY settings. I tried every possible fix by now

Game runs 100% perfectly smooth but recording/ stream stutters for random period of times with random intervals inbetween, for majority of time its fine
i use in game engine framerate counter + frametime, it never drops not by a tiny bit, i though it was pc fault

High end pc 12900k / 3080ti 32 gb 4600 ddr4 (gear 2) ram 

the framerate of the game goes out of sync with obs, this happends quite randomly and periodically, and length of that period is non consistent and so are intervals between it. The game can be running completely fine for long period of time, or the stuttering can start right from the start
Stuttering clearly seen in the preview and it translates into recording / stream => no reported dropped frames recording or encoding lag.

Sometimes it feels like perfomance degrades over the time, as if it starts occasionally missing a frame here and there and then it feels less smoother until it becomes quite obviously stuttery and then resyncs to smooth and perfect and repeats the cycle

I tried switching on / off game mode / resizeable bar / admin mode / hags / both monitors are running 120 refreshed rates, all games vsync fps locked
I tried disabling preview, switching monitors, turning off a single monitor, keeping obs on main monitor etc
Tried full reinstall of windows 11 from the scratch, using new installer file ( not inside the os option to make sure its perfectly clean)
the only thing installed on streamign pc is steam discord epic games and chrome

All Game runs perfectly 60 / 120 fps no fps drops / no frametime drops. No noticeable lag in game (buttery smooth) when its happening on preview and stream

Outside of this laggy moment, obs capturing everything correctly and smoothly

Using windows 11, high end pc => obs never even close to utilizing pc to its fullest, bios chipset driver nvidia driver up to date

Happends on multiple games.

Alt tabbing seems to somewhat resync the game sometimes, so does starting recording, restarting obs (basically any action that kinda affects the interaction of obs and the game)
!!!!!!! Multiple instances of when game capture can be laggy, but switching to display capture and it runs smooth with no lags (and opposite is the case as well) Switching back you can observe choppy motion.

Hard to replicate, multiple times i though i solved by changing settings and no lags were showing up for like 30-50 mins when testing for it to reppeat later. Seems like once the issue starts happening in obs, it intesifies drastically until you restart obs

Really in desperate state of needing help to resolve this issue, been spending countless hours trying to resolve it to no result

### Steps to Reproduce

1. Open the game, no need to record or stream (just keep obs open)
2. Game preview strts stuttering when game runs perfectly fine
3.
...
however again, it doesnt seem tied well to any specific moments, happens irregularly. Can record video/stream with no issue for long time until it appears

### Anything else we should know?

Willing to provide any information to resolve the case.
Im a small streamer, and streaming is my main source of income, i would rly love to get this issue resolved.
I understand everyone has their own stuff to care about, but if anyone wanna help out and maybe try to figure it out with me, since im not tech savvy at all, that would be lovely. ( Assuming its on my side, and not obs / windows ) 
If money is at question, i can compensate as long as this can get resolved.

**Comment by JackTheRipperGB** [comment] 2022-05-08 14:46
https://clips.twitch.tv/DarkEncouragingAdminResidentSleeper-Cicmdir1XgmPwydK This is an example of what im complaining about, the game capture randomly seems to be missing 5-10 or so frames per second out of 60, its not like terrible terrible stutter but this quite annoying chopness. And no this is not elden ring fault even though that game has fps issue, this happens in many games. The game at the moment was running perfect smooth 60 fps

**Comment by Fenrirthviti** [comment] 2022-05-08 22:35
I am watching this clip, but I don't see any noticeable frame drops or stuttering in the clip at all.

Additionally, it would help to have raw video recording rather than a stream clip, as there's a lot that can happen between OBS and playback that might be affected it.

**Comment by Fenrirthviti** [comment] 2022-05-08 22:37
I'm going to go ahead and close this as a support issue, however, as the reproduction steps are far too broad to be actionable. I'd recommend using the normal support channels for someone to take a look (possibly the #encoding-talk channel on our Discord as they like a good challenge with this kind of thing), and if it can be narrowed down to something more actionable other than "it happens sometimes I don't know" we can reopen this.

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Closed by Fenrirthviti** 2022-05-08 22:37 UTC

**Comment by lapppy-git** [comment] 2022-05-08 23:35
I am very familiar with this issue having experienced it many times myself and it is indeed present in his clip. The clip displays at a visually smooth 60 fps but then starts to "skip" frames at around the 7-8 second mark (when he turns the camera). Sometimes this is accompanied by visual tearing in the output. A PR that could have potentially fixed this (or the tearing at the very least) was submitted at #3814, but I don't know if an alternative fix for the tearing issue was merged since then.
This has been an issue for many years and I have been tracking a few forum threads on the subject since then, this is just a sample.
[https://obsproject.com/forum/threads/game-capture-frames-de-syncs-after-30-minutes.68969](https://obsproject.com/forum/threads/game-capture-frames-de-syncs-after-30-minutes.68969)
[https://obsproject.com/forum/threads/random-stuttering-in-preview-which-goes-into-recorded-videos.77744](https://obsproject.com/forum/threads/random-stuttering-in-preview-which-goes-into-recorded-videos.77744)
[https://obsproject.com/forum/threads/unusual-tearing-artifacts-when-using-game-capture.95335](https://obsproject.com/forum/threads/unusual-tearing-artifacts-when-using-game-capture.95335)
[https://obsproject.com/forum/threads/how-do-you-actually-stream-at-true-60-fps-100-of-the-time.95213](https://obsproject.com/forum/threads/how-do-you-actually-stream-at-true-60-fps-100-of-the-time.95213)
[https://obsproject.com/forum/threads/regular-stutterings-on-preview-recorded-videos.80031](https://obsproject.com/forum/threads/regular-stutterings-on-preview-recorded-videos.80031)
[https://obsproject.com/forum/threads/frame-rate-is-cut-in-half-stutters-every-10-minutes.39269](https://obsproject.com/forum/threads/frame-rate-is-cut-in-half-stutters-every-10-minutes.39269)
[https://obsproject.com/forum/threads/jitter-in-frame-capture-causing-duplicate-and-missed-frames-preventing-fluid-motion.21144](https://obsproject.com/forum/threads/jitter-in-frame-capture-causing-duplicate-and-missed-frames-preventing-fluid-motion.21144)
After trying many different solutions to mitigate the issue with none of them solving the issue in its entirety, I strongly believe that this is a problem within the software itself and/or how the software is capturing frames, and goes beyond community support. For now, the best a user can do to limit it's impact is to ensure that the source they are capturing (in this case, a game) is being played at twice of OBS capture framerate, and ensure that their monitors refresh rate is an exact multiple of OBS capture frame rate.

**Comment by Fenrirthviti** [comment] 2022-05-09 03:55
There's been several attempts to fix the "target capture framerate doesn't match OBS" problem in the past, but they have all introduced more problems than what they have solved, as was explained in the mentioned PR. This is more or less a known side effect of not capping framerates, and basically any capture application is going to be subject to the same problems. It's impossible for us to know what frames to keep and what to discard to maintain "smooth" playback without introducing significant latency or other performance issues, as has been attempted in the past. If there was a simple fix for that, it would have already been done.

**Comment by JackTheRipperGB** [comment] 2022-05-09 04:45
The framerate is capped, i wrote it in my original post, that all games i use have perfect stable 60/120 fps vsync with no frame drops at all, yet this starts happening. The windows support / tech talk on your obs discord, i have been there and spend endless hours, trying to fix this or asking for help, no one seems to notice anything abnormal. 
I mentioned that clip doesnt have like bad bad stuttering but its clearly missing frames for no apparent reason, while the source running buttery smooth 60

**Comment by Adega-Studio** [comment] 2022-05-10 07:31
I confirm all of the above. Obs has a problem with the frame capture method and this is especially evident when rotating the camera in the game. I wrote a lot here and tried everything, but apparently this is a congenital defect obs(.
jpark37 [jpark37](https://github.com/jpark37) made a test version, which, even in desktop capture mode, eliminates image stuttering. But jpark37 abandoned further development(.
I am ready for any tests, except for the replacement of iron. I lost a lot of money looking for a smooth picture, but it turns out that obs (.

**Comment by AnnaSmile** [comment] 2022-05-10 19:16
Hello. Yes! I confirm, micro jerks in the stream. I did everything, but to no avail. And the capture of the Game, And the capture of the window, And the capture of the desktop. Ryzen 5900x processor. RTX 3090. 64GB RAM. Solve the Question Please.

**Comment by JackTheRipperGB** [comment] 2022-05-15 10:38
Any chance for the development regarding this issue?

**Comment by JackTheRipperGB** [comment] 2022-05-18 16:10
From my testing it seems that alt tabbing into another programs and back always seems to fix the issue with resyncing back and frames going perfectly smooth, it also seems like alt tab seems to cause the issue as well, as if alt tabbing into another programm can result in desync, but not guaranteed. Anyone have any idea what os interaction could be responsible for this?

**Comment by Adega-Studio** [comment] 2022-05-30 17:27
It is a pity that there is no solution to jerks. Apparently you have to come to terms with this and continue to hope for a miracle.

**Comment by Aurora-Lex** [comment] 2023-08-02 04:46
What fixed this issue for me was changing the output framerate from 60 fps 59.94 fps.

The issue seems to stem from a sync mismatch between capture sources and stream output framerate.
For me the 60 fps streams would look as if they dropped to 30 fps for a couple of seconds and then recovered.

In my case, captures from two V-synced sources with a very slight difference in vertical sync.
1. A monitor that Windows 11 reports as being 60Hz, but in actuality runs at 59.94Hz.
2. A VR headset running at true 120 Hz.

This discrepancy in refreshrate is ~0,1%, meaning that the cycle length from being "the most in phase"-"most out of phase" is 
once every ~16,7 seconds.

To achieve a framerate of 59.94 in OBS, go to "Settings", "Video", change "Common FPS Values" to "Fractional FPS Value", and set "Numerator" to 59940, and "Denominator" to 1000.

If you experience this issue on a 30 fps stream, then a fractional framerate of 29.97 is what you want instead.

The only drawback I've found is that the OBS preview window will display screen tearing, however the stream output will not.
I've tested watching the streams on three Android devices and one PC without issue, and no viewers have complained. Twitch reports the streams as 60 fps.

Hope this helps!

**Comment by mufunyo** [comment] 2023-08-05 13:25
> To achieve a framerate of 59.94 in OBS, go to "Settings", "Video", change "Common FPS Values" to "Fractional FPS Value", and set "Numerator" to 59940, and "Denominator" to 1000.

This is not the correct way to achieve that frame rate. Either select "59.94" from the "Common FPS Values" dropdown, or select a numerator of 60000 with a denominator of 1001 (OBS does this internally if you select 59.94 from the common values dropdown).

**Comment by Aurora-Lex** [comment] 2023-08-06 02:02
> > To achieve a framerate of 59.94 in OBS, go to "Settings", "Video", change "Common FPS Values" to "Fractional FPS Value", and set "Numerator" to 59940, and "Denominator" to 1000.
> 
> This is not the correct way to achieve that frame rate. Either select "59.94" from the "Common FPS Values" dropdown, or select a numerator of 60000 with a denominator of 1001 (OBS does this internally if you select 59.94 from the common values dropdown).

Ok, thank you!
I didn't even realize this was an option in the "Common FPS Values" dropdown.
