### ISSUE TITLE
[BUG] Browser Source properties (URL!) get messed up on scene collection switch when using same source name

### ISSUE THREAD

**Issue by TreZc0** [obsproject/obs-studio#2733] opened 2020-04-16 22:00 UTC
## Platform
Operating system and version: Windows 10 1909 18363
OBS Studio version: 25.0.4

## Expected Behavior
For our restreaming service, we use 3 different scene collections to feed 3 different channels. All 3 collections are identical, all scenes and sources have identical names, the only difference is that all browser sources inside (as we use dynamic browser sources as layouts powered by NodeCG (which OBS is familiar with)) point to a different URL containing the information for that specific channel.
When switching between these collections, it's to be expected that the correct URLs are loaded from the Scene collection JSON file. 
Example: Scene collection 1 - Scene Countdown - Source Introscreen (Browser Source, URL: https://1.xyz.com/countdown.html)
Scene collection 3 - Scene Countdown - Source Introscreen (Browser Source, URL: https://3.xyz.com/countdown.html)
On a switch from Scene collection 1 to Scene collection 3, the Source Introscreen should have the URL "https://3.xyz.com/countdown.html" as initially configured.

## Current Behavior
Instead of loading the proper property values from the new scene collection file, OBS will override the source property (here, the URL) with the value from the scene collection that was loaded before. This will also override the permanent value in the JSON storage file, making the bad change permanent.
Initial Setup (visible in the SCollection JSON files)
Scene collection 1 - Scene Countdown - Source Introscreen (Browser Source, URL: https://1.xyz.com/countdown.html)
Scene collection 3 - Scene Countdown - Source Introscreen (Browser Source, URL: https://3.xyz.com/countdown.html)

After switch from scene collection 1 to scene collection 3
Scene collection 1 - Scene Countdown - Source Introscreen (Browser Source, URL: https://1.xyz.com/countdown.html)
Scene collection 3 - Scene Countdown - Source Introscreen (Browser Source, URL: https://1.xyz.com/countdown.html)

## Steps to Reproduce
1. Create two different scene collections that have identical scenes and sources, just with different URL property for the browser source.
2. Switch from one scene collection to the other.
3. Check the now corrupted browser source URL property.

## Additional information
Note that this behavior doesn't seem to be 100% persistent. Most likely, a race condition applies sometimes. 
It is however reproducible, but will not happen on every single switch.
It could theoretically be related to the size of the scene collections too (as ours have 30+ scenes)

This is actually a dealbreaker and makes the scene collection feature, which is absolutely indispensable for any multi channel or broadcasting service, especially without a grouping feature for scenes, so unreliable that it basically cannot be used anymore.

**Comment by Fenrirthviti** [comment] 2020-04-16 22:02
Likely related to the issue uncovered in #2724

**Comment by TreZc0** [comment] 2020-04-16 22:04
Potentially true, but without any nesting of scenes involved.

**Comment by TreZc0** [comment] 2020-05-03 17:15
Any info about this? This is actually a major issue for us.

**Comment by Fenrirthviti** [comment] 2020-05-03 19:30
I've tested your replication steps but am not able to replicate on my end, so there is something missing.

**Comment by TreZc0** [comment] 2020-05-03 19:33
I imagine this only happens on big scene collections, causing CleanSceneData to not be done in time.
Related to #2709 too.

**Comment by WizardCM** [comment] 2021-06-13 11:48
Duplicate of #2733

**Closed by WizardCM** 2021-06-13 11:48 UTC
