### ISSUE TITLE
macOS: captured windows on other Spaces move/stutter via Window Capture

### ISSUE THREAD

**Issue by feetstv** [obsproject/obs-studio#5824] opened 2022-01-19 01:33 UTC
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Spm9VmT7QOlY09Ec

### Expected Behavior

The window should not shift when switching spaces, it should appear to be still.

### Current Behavior

The window shifts when switching spaces.

### Steps to Reproduce

1. Have OBS capture a window on the current space using Window Capture.
2. Place that window either in another space or make it a full-screen window.
3. Start recording.
4. Switch to the window in the other space, then switch back to the space with OBS.
5. Stop recording. In the recording, the window appears to move, even though it should be still.

### Anything else we should know?

Video of the issue: https://youtu.be/Usd8IJXH_YM

**Comment by WizardCM** [comment] 2022-01-19 01:56
This sounds like a duplicate of #5824 and may be outside of our control.

**Comment by gxalpha** [comment] 2022-12-14 21:19
Duplicate of #3222

**Closed by gxalpha** 2022-12-14 21:19 UTC
