### ISSUE TITLE
Blackmagic Decklink source flicker on AMD under Linux

### ISSUE THREAD

**Issue by marvimarv** [obsproject/obs-studio#4724] opened 2021-05-19 05:10 UTC
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/788asu--FZZuEnwZ

### Expected Behavior

When using input sources they should display without flickering. 

### Current Behavior

Input devices flicker with a black frame. They are all connected with a Blackmagic Decklink 4K card, but the problem only shows in OBS Studio. Using any other software to look at the input the flicker doesn’t appear. 

Video: https://youtu.be/XgR9l8GS7ZE

### Steps to Reproduce

The bug randomly appears. It has no pattern but it never goes away. I just open OBS Studio and the bug is there.

**Comment by LGCW** [comment] 2021-05-19 16:18
If that's a Decklink HDMI Quad they drop frames on AMD Threadripper and looking at your video Ryzen 7 3700X as well. I reported the bug almost a year ago to Blackmagic and they confirmed it. That ticket is still open without a resolution. Seems to only be an issue when using Linux. 


From a post on a video I made about the issue:
_"For some reason, Black Magic continue to use Intel Memtest A dylib compiled libraries without too much care in the world for AMD users. Using Virtualisation like Proxmox, you are easily able to pass thru the BMD Decklink card and enjoy full intel compatibility, with four SDI (separate cameras) inputs/outputs.
Under Windows everything works fine."_

**Comment by marvimarv** [comment] 2021-05-20 13:16
Sadly we are using different card: 2x Decklink 4K Mini and 1x Mini. 

It’s so weird that this happens just in OBS Studio and not on any other capture software. That’s why I think the bug might be sitting there. 

Thanks anyways!

**Comment by marvimarv** [comment] 2021-06-15 19:32
Hello. Do you think there is any way of fixing this? We are using OBS in a studio and the bug is really irritating for the recording. Maybe there is a way to prioritize solving a bug by paying someone?

**Comment by LGCW** [comment] 2021-06-15 19:45
> Hello. Do you think there is any way of fixing this? We are using OBS in a studio and the bug is really irritating for the recording. Maybe there is a way to prioritize solving a bug by paying someone?

This is a BlackMagic issue, not a OBS issue. The best way to help is by submitting a bug report to Blackmagic.

**Comment by marvimarv** [comment] 2021-06-15 19:47
That’s weird, because the error only appears in OBS, not on any other capturing software. So it must be an error with OBS?!

**Comment by LGCW** [comment] 2021-06-15 20:09
It happens with MediaExpress as well but it's far less frequent. 

I say this is a Blackmagic bug since I had record a lot of footage to show that it happened in Mediaexpress and OBS. I submitted a report to Blackmagic with the video and they were able to reproduce the problem using an AMD CPU.

That ticket is still open without resolution.

**Comment by marvimarv** [comment] 2021-06-15 20:45
But for us the problem doesn’t appear in Media Express, that’s different to you. We are also using different capture cards.

**Comment by norihiro** [comment] 2021-06-16 14:00
I experienced decklink source randomly shows old frame with CentOS8 on Intel i7700 and I'm using this patch as a workaround with OBS 26.0.2.
[decklink-ignore-unupdated-frame.patch.txt](https://github.com/obsproject/obs-studio/files/6663513/decklink-ignore-unupdated-frame.patch.txt)
It's just ignoring a frame if its first or last line is zero and reset the frame buffer after it was copied.

**Comment by RytoEX** [comment] 2022-11-16 21:56
The Issue title says "on AMD", but your log shows and NVIDIA GPU. By "on AMD", did you mean the CPU? Please retest in OBS Studio 28.1.2 (or newer) to confirm if this is still an issue. If this is still occurring, please provide new logs.

**Comment by marvimarv** [comment] 2022-11-17 08:45
> The Issue title says "on AMD", but your log shows and NVIDIA GPU. By "on AMD", did you mean the CPU? Please retest in OBS Studio 28.1.2 (or newer) to confirm if this is still an issue. If this is still occurring, please provide new logs.

Thanks for replying. At the moment we had to disassemble our studio, so I can not test this behavior. But you are correct, I was referring to the CPU. As soon as we reassemble it (which will be around next summer), I will test this again. I think we can probably close this issue for now and I will post a new one if the error still occurs.

**Comment by Fenrirthviti** [comment] 2022-11-17 18:04
Closing per above. Feel free to just comment on this one as well in the future, and we can just reopen this one instead of opening a new one.

**Closed by Fenrirthviti** 2022-11-17 18:04 UTC
Labels: Linux, Dependency Issue
