### ISSUE TITLE
Crash when I open the software for the first time

### ISSUE THREAD

**Issue by Artaherzadeh** [obsproject/obs-studio#6180] opened 2022-03-21 04:11 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/H8Jtcurxb3fOqC5C

### OBS Studio Crash Log URL

https://obsproject.com/logs/c_3mTFEm_dFMXqIZ

### Expected Behavior

The app shouldn't crash

### Current Behavior

When I open the app the first time it crashes but the next ties its okay and without any problem.it's

### Steps to Reproduce

1. Start the PC and go to windows
2. Start the software ( it crashes )

**Comment by Artaherzadeh** [comment] 2022-03-21 04:11
I also reinstalled and installed the software again. Still have the problem.

**Comment by WizardCM** [comment] 2022-03-21 04:12
This is definitely an unwanted crash - the virtual camera is crashing for some reason.

**Comment by Fenrirthviti** [comment] 2022-03-21 14:49
Please remove Kaspersky and try again. Kaspersky is known to be overly aggressive and cause crashing within OBS.

**Comment by Artaherzadeh** [comment] 2022-03-21 15:38
> Please remove Kaspersky and try again. Kaspersky is known to be overly aggressive and cause crashing within OBS.

I removed the virtual camera and the problem is fixed + OS security is more important than one OBS crash.

**Comment by Fenrirthviti** [comment] 2022-03-29 00:14
Closing this as it's caused by third party software. You might want to re-evaluate your correlation between "Kaspersky" and "OS Security"

**Closed** 2022-03-29 00:13 UTC
