### ISSUE TITLE
VLC Video Source tints color with files encoded in HEVC

### ISSUE THREAD

**Issue by Auroric** [obsproject/obs-studio#3456] opened 2020-09-12 00:12 UTC
## Platform

Operating system and version: Windows 10 (2003)
OBS Studio version: 26.0.0-rc1

## Expected Behavior

VLC Video Source streams with proper color
## Current Behavior

VLC Video Source streams with tinted color, lighter colors appear blue while colors that should be blue appear green/red.
## Steps to Reproduce

1. Add VLC Video Source 
2. Select file encoded in HEVC (H.264)
3. Play file through media controls 

## Additional information

The issue appears to occur only with files that are encoded in HEVC (H.265), and does not occur in the Media Source or the VLC application itself, only with OBS's VLC Video Source. I've only tested with files formatted in .mkv, so I'm unsure if it'll occur with other containers, such as .mp4. 

What OBS displays (H.265): 
![image](https://user-images.githubusercontent.com/8205005/92982023-52fc0d80-f451-11ea-8622-f5fb89eaf89b.png)

What it *should* display (H.264): 
![image](https://user-images.githubusercontent.com/8205005/92982053-745cf980-f451-11ea-855d-18d13df92f2f.png)

Images are from the intro credits of Weathering With You.

**Comment by Fenrirthviti** [comment] 2020-09-12 00:14
Can you test if the same thing happens in VLC itself?

**Comment by energizerfellow** [comment] 2020-09-12 00:17
It would also be useful if you could attach a text file export of the video file's metadata from a tool like Mediainfo.

**Comment by Auroric** [comment] 2020-09-12 00:24
@Fenrirthviti Here is the log file: 
[2020-09-11 17-18-14.txt](https://github.com/obsproject/obs-studio/files/5211939/2020-09-11.17-18-14.txt)

@energizerfellow And here is the metadata:
[metadata.txt](https://github.com/obsproject/obs-studio/files/5211940/metadata.txt)

**Comment by kkartaltepe** [comment] 2020-09-12 00:27
There is no tinting going on (White is clearly white) it looks like a red/blue swap to me.

**Comment by Auroric** [comment] 2020-09-12 01:40
I've just tested the h.265 video against a version of itself converted to h.264 using ffmpeg, and it appears to have the same issue, so the bug might not be with the codec. However, I also tested some other files that had incorrect and correct colors, and it appears that all videos with 10-bit color are affected by the issue, while videos with 8-bit color are not.

**Comment by kkartaltepe** [comment] 2020-09-12 01:49
I could have sworn this has been reported before (10bit files in vlc) but I cannot find it in old issues. If vlc source is providing 10bit textures then they wont be down converted to 8bits correctly in OBS (ffmpeg may be doing this automatically?).

**Comment by Auroric** [comment] 2020-09-12 02:42
It's interesting that VLC itself doesn't seem to be affected by the same issue though.

**Comment by notr1ch** [comment] 2020-09-12 13:25
Duplicate of https://github.com/obsproject/obs-studio/issues/3396 which is fixed in https://github.com/obsproject/obs-studio/commit/c13357ff91ede253346edd78d1047ffa8eefad00

Please update to RC2.

**Closed by notr1ch** 2020-09-12 13:25 UTC
