### ISSUE TITLE
OBS Output Timer Not working properly/Output TImer Timeout

### ISSUE THREAD

**Issue by hunterxtwitch** [obsproject/obs-studio#9210] opened 2023-07-06 21:42 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/DlDoGZTQs9bgwqB8

### Expected Behavior

output timer to start and stop the recording and or stream at a specified time length when enabled

### Current Behavior

the output timer when set to any value above zero for any length of time will auto trigger even if it is disabled and cause it to end recordings 
![screenshre](https://github.com/obsproject/obs-studio/assets/138826196/ecc558b3-2007-4993-b056-adab0458b9f6)
as shown in the screenshot i don't have it enabled but when i click record it starts the timer as if it was enabled and i have tested it multiple ways with it on and off and it does the same thing it also writes in the log "Output Timer Timeout"

### Steps to Reproduce

1.head over to tool's and click output timer 
2.set any given amount of time anything above 00:00:00

**Comment by RytoEX** [comment] 2023-07-06 22:23
Probably a duplicate of #6558?

**Comment by dege13** [comment] 2023-08-04 18:36
It does sound like the description in #6558

**Comment by gxalpha** [comment] 2023-08-10 19:11
Duplicate of #6558

**Closed by gxalpha** 2023-08-10 19:11 UTC
