### ISSUE TITLE
Image Slide Show does not show all pictures before looping

### ISSUE THREAD

**Issue by an0ndev** [obsproject/obs-studio#3366] opened 2020-08-30 15:11 UTC
## Platform
Operating system and version: Debian Linux v10
OBS Studio version: 26.6.0-rc1 (latest from repo as of today)

## Expected Behavior
More than 68 slides should be shown.

## Current Behavior
When pressing the "next slide" button after showing the 68th slide, the slideshow loops back to the first slide.
I checked the log file and no errors show up.

## Steps to Reproduce

1. Load at least 69 slides into an Image Slide Show source.
2. Navigate to the 68th slide and attempt to navigate forwards (Slide 1 is shown), or navigate backwards with Loop enabled (Slide 68 is shown).

**Comment by dodgepong** [comment] 2020-08-30 15:28
This is not a cap on the number of slides, but the size of the images themselves. OBS currently decodes all images in a slideshow ahead of time for performance reasons and stores them in VRAM, which can end up taking a lot of VRAM. Thus, it limits the amount of VRAM a slideshow source can use. If your images were higher resolution, you would get fewer images. If they were lower resolution, you could get more images.

There is a proposal for an alternative implementation here, with more discussion about the issue: https://github.com/obsproject/rfcs/pull/17

**Comment by An0nDev** [comment] 2020-08-30 15:50
Sounds good, thanks. Should I leave the issue open until a solution is implemented to avoid duplicates?

**Comment by dodgepong** [comment] 2020-08-30 15:53
I don't think there is an issue open for this yet so I suppose we can leave it open.

**Comment by An0nDev** [comment] 2020-10-05 18:43
Removing the limit on the amount of VRAM is probably some sort of violation of OBS' design guidelines, but I wanted to do so anyway for personal use, and in case anyone else wanted to, I figured I'd make a quick guide here on what to do:

All you have to do is follow the normal build guide for your system, except before running `make`, edit `plugins/image-source/obs-slideshow.c`.
If you want to remove the limit entirely, remove the lines starting with `#DEFINE BYTES_TO_MBYTES` and `#DEFINE MAX_MEM_USAGE` as well as the `if` and `break` statements that check the memory usage against the maximum (`if (ss->mem_usage >= MAX_MEM_USAGE) break;` in two places).
Alternately, if you'd like to keep but raise the limit, you can leave everything in place but raise the number of megabytes in the `MAX_MEM_USAGE` definition.

To keep your change present while being able to update the source and rebuild, just add your change to Git (`git add plugins/image-source/obs-slideshow.c` from the `obs-studio` directory) and make a commit out of the change (`git commit -m "obs-slideshow: removal of limit on VRAM usage"`). Now, to update the source and rebuild, you can just run `git pull` and go through the build instructions again, skipping the beginning part where you run `git clone`.

**Comment by skeletonbow** [comment] 2020-10-10 10:39
Hopefully the image slideshow will be updated in the future to dynamically handle more images and/or allow more GPU RAM usage by default or make it configurable.  The new generation of GPUs are sporting 8/12/16/20/24GB of VRAM and games only use 6 or so GB of that for the most part.  The majority of people have 8GB or less but that'll be changing before long.  nvidia/AMD are marketing the high-RAM cards for content creators, which IMHO includes live streaming so having a built in option to runtime configurably take advantage of all the VRAM not used by other stuff would be great.

**Comment by An0nDev** [comment] 2020-10-10 18:39
Agreed @skeletonbow, at least a config option to toggle or modify the max would be nice. Maybe once I'm more experienced with the repo's coding style, I'll try for a PR, but in the meantime, hopefully my guide will do.

**Comment by DachsbauTV** [comment] 2020-10-16 16:29
My merged issue is kind of different to this, as the overload of VRAM is not a problem.

To summarize: An animated Gif within the image playlist will stop the slide show.

**Comment by TheRenegadist** [comment] 2020-11-25 10:56
Have any new developments been made in this regard, any news on implementation?

**Comment by An0nDev** [comment] 2020-11-26 16:42
I'll take a crack at adding a global config value for the memory limit rather than using a preprocessor constant, and will link the PR here when it's open. As I mentioned earlier, take a look at the RFC for more meta discussion, and you can also use my instructions to patch your own copy and raise or remove the limit.

**Comment by TheRenegadist** [comment] 2020-11-27 07:59
Couldn't someone do a plugin that has the same functionality as the current slideshow source but modified to increase, remove, or allow the user to set the limit?

**Comment by dodgepong** [comment] 2020-11-27 13:22
The solution to this problem isn't to increase the limit or allow users to increase the limit. The solution is to rewrite the slideshow source to load images dynamically instead of all images at once.

**Comment by TheRenegadist** [comment] 2020-11-28 21:12
> 
> 
> The solution to this problem isn't to increase the limit or allow users to increase the limit. The solution is to rewrite the slideshow source to load images dynamically instead of all images at once.

Can that be done as I mentioned, it being a plugin that users can install and use instead of the normal slideshow?

**Comment by dodgepong** [comment] 2020-11-28 22:15
Someone could rewrite the image slideshow plugin, sure.

**Comment by TheRenegadist** [comment] 2020-12-15 22:09
How come no one has then, I figured by now people would have done so instead of waiting for it to be updated in OBS.

**Comment by TheRenegadist** [comment] 2021-01-08 05:39
Been radio silent for some time, any word?

**Comment by WizardCM** [comment] 2021-01-08 05:44
We had a feature freeze for 26.1, release, christmas, new years, and a 26.1.1 patch release. Nobody on the team has currently looked into the RFC linked above, so this bug has not been touched. Please remember that the OBS team is made up of volunteers and 1 full-time developer.

**Comment by DarkDust** [comment] 2021-01-16 14:02
There is a complete and working implementation of the RFC by me, for half a year now. I just accidentally saw this issue here since I was going to make it compile with the current OBS version. But discussion on the RFC and whole topic starved, I thought nobody except me is interested in this.

If you want to give it a try, here's the implementation: https://github.com/DarkDust/obs-studio/tree/feature/slideshow2a

**Comment by danielmiletic** [comment] 2021-01-20 10:39
@DarkDust Thank you so much for the effort. I'm looking forward having a limitless slideshow in 2021. Until then, how do I implement your code in OBS Mac version? Thx

**Comment by DarkDust** [comment] 2021-01-20 10:45
Check out the branch and [follow the instructions for building OBS Studio from source](https://obsproject.com/wiki/install-instructions). I developed on macOS, recently ran it on Windows. Works fine on both.

**Comment by danielmiletic** [comment] 2021-01-21 10:25
Thanks a lot @DarkDust

**Comment by TheRenegadist** [comment] 2021-04-23 21:53
We're now in April coming on May, any word on this being officially implemented? Has someone created a plugin for OBS with these important changes in mind so no compiling of the source is required?

**Comment by TheRenegadist** [comment] 2021-05-31 23:49
So what does that mean, By Design/Not a bug, this doesn't mean the entire idea/improvement will be thrown out will it?

**Comment by an0ndev** [comment] 2022-04-01 19:50
> The solution to this problem isn't to increase the limit or allow users to increase the limit. The solution is to rewrite the slideshow source to load images dynamically instead of all images at once.
> There is also an open RFC that still needs to be reviewed, we just haven't had the time yet.

I've made a smaller, temporary-type change (above ^) that hopefully someone can review and merge more quickly in the meantime.

**Comment by glenneroo** [comment] 2022-05-10 02:00
A temporary workaround is to resize all of your images to be the size of your output (which I guess is for most people 720p-1080p). I just resized 400 images which were 1.6GB to HD (1920 on the long side) using IrfanView batch mode (jpg quality level 88) and now they only consume 150MB which is well within the limits of any graphics card.

**Comment by TheRenegadist** [comment] 2022-05-21 02:39
That doesn't work in my situation, I want to use the slideshow source to cycle through various fan-art but because the resolutions are so widely different I can't just simply rescale them all without messing with the original quality/perspective.

**Comment by glenneroo** [comment] 2022-05-21 04:19
> That doesn't work in my situation, I want to use the slideshow source to cycle through various fan-art but because the resolutions are so widely different I can't just simply rescale them all without messing with the original quality/perspective.

IrfanView batch convert (B hotkey) has under Advanced Options > Resize the option to only resize the long or short side to a specific resolution, as well as a checkbox to Preserve Aspect Ratio (proportional).

**Comment by robmonte** [comment] 2022-05-28 19:07
OBS 23.0 had changes that did dynamic loading of images for a slideshow. It was reverted for supposed render lag/CPU utilization issues, however I've not noticed any issues at all while using it. It makes it more frustrating to know that this version works for me and potentially many others without issue yet have no way of using it. Can we simply get this version of the feature as a beta plugin somehow?

**Comment by PatTheMav** [comment] 2022-10-20 17:05
As mentioned in the thread before, this is not an actual bug, but a deliberate implementation of the slideshow.

We _are_ aware that in the best possible scenario the slideshow could handle any number of images and allocate as much memory and resources as necessary, however that would require an entirely different architecture of the plugin (RFCs and suggestions have been made to address this).

Our position is still to rather switch to a variant of the plugin that addresses the root cause making a memory limit necessary than tweak that limit itself, as it would just doctor around the symptoms.

On top of that we will try and communicate this limitation (for the time being) of the slideshow better in the future to increase awareness that this limit exists to ensure recording and/or streaming stability and performance.

**Comment by robmonte** [comment] 2022-10-20 17:44
I think that all sounds reasonable, but I also think it's reasonable to request the OBS 23.0 version of the plugin to be available as a user-installable beta plugin. If a user is willing to install the plugin manually, they can have that choice of workaround with the accepted risk of lag or CPU utilization.

**Comment by PatTheMav** [comment] 2022-10-20 17:46
You are free (and encouraged) to take the source code from the state of the plugin in OBS 23.0 and fashion it into a standalone plugin and release it - that's the beauty of open source software.

**Comment by DarkDust** [comment] 2022-10-20 19:34
> We _are_ aware that in the best possible scenario the slideshow could handle any number of images and allocate as much memory and resources as necessary, however that would require an entirely different architecture of the plugin (RFCs and suggestions have been made to address this).
> 
> Our position is still to rather switch to a variant of the plugin that addresses the root cause making a memory limit necessary than tweak that limit itself, as it would just doctor around the symptoms.

Yeah, well, that variant actually exists for a long time now: https://github.com/obsproject/rfcs/pull/17

**Comment by PatTheMav** [comment] 2022-10-20 22:52
> > We _are_ aware that in the best possible scenario the slideshow could handle any number of images and allocate as much memory and resources as necessary, however that would require an entirely different architecture of the plugin (RFCs and suggestions have been made to address this).
> > Our position is still to rather switch to a variant of the plugin that addresses the root cause making a memory limit necessary than tweak that limit itself, as it would just doctor around the symptoms.
> 
> Yeah, well, that variant actually exists for a long time now: [obsproject/rfcs#17](https://github.com/obsproject/rfcs/pull/17)

That is specifically what I alluded to.

**Comment by hutber** [comment] 2023-05-14 16:39
No to add salt to this, but its pretty annoying :D

**Comment by gxalpha** [comment] 2024-01-18 20:53
Fixed by https://github.com/obsproject/obs-studio/pull/10088.

**Closed by gxalpha** 2024-01-18 20:53 UTC
Labels: By Design / Not a bug, Confirmed

**Comment by an0ndev** [comment] 2024-12-08 18:27
Fix was released in 30.1. Note that since the fix involved creation of a new "mk2" source, rather than replacement of the existing one, users of the previous source would need to delete and recreate the slideshow source to see the difference.
