### ISSUE TITLE
obs-scripting + reload button : full OBS freeze with official example lua scripts

### ISSUE THREAD

**Issue by ludolpif** [obsproject/obs-studio#9201] opened 2023-07-04 10:28 UTC
### Operating System Info

Windows 10

### Other OS

It also happens on Debian 12

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

It also happens on 28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/nvt7rdgAlkzjZK5Z

### Expected Behavior

Using a blank OBS with default configuration, loading then reloading a few times the shipped scripts/clock-source.lua should not deadlock whole OBS instance.

### Current Behavior

It hangs OBS immediately after clicking the script reload button  with a probability that cannot be taken as risk during live streaming. On my poor Intel GPU it's like 1 out 3, on a more capable Nvidia GPU it's like 1 out 20.

Probably a deadlock when source_info.create() hook calls obs.obs_enter_graphics() after a reload. It first ran into this trouble with a shader based filter which compiles an effect in source_info.create() hooks, but it happens to exist also with clock-source.lua which don't compile any shader. I can reproduce the bug also with https://obsproject.com/wiki/Scripting-Tutorial-Halftone-Filter-Listing "First part" lua+effect. The second part is not pasted correctly on the page (missing end of hlsl code).

I see no freeze in my own lua script if I defer all calls to obs.obs_enter_graphics() from source_info.create() hook to source_info.video_render() hook.

### Steps to Reproduce

1. Install OBS 29.1.3 with blank config, no plugins, it seems not-OS dependent
2. Script menu, load shipped clock-source.lua
3. Add a source in the default scene
4. No need to start stream ou record
5. Script menu, select clock-source.lua, press many times the reload script button
6. Depending on hardware and OBS business, it could take 1, 3 or 20 button press to  got the freeze

### Anything else we should know?

I've tried to obs.script_log() all calls and returns of obs.obs_enter_graphics() and obs.obs_leave_graphics() and also in my case custom lua filter, all calls to obs.obs_source_process_filter_begin() and obs.obs_source_process_filter_end() and the log output before hangs didn't show an enter twice or enter between filter_begin and filter_end, it just hangs without outputing anything after "will call obs_enter_graphics()" log message, obs_enter_graphics() never returns.

**Comment by PatTheMav** [comment] 2023-07-04 16:18
Duplicate of https://github.com/obsproject/obs-studio/issues/6674.

The Lua clock source can deadlock when manual reloads are triggered because reloading the script requires a lock on the script object and because the script itself renders output it also requires a lock on the graphics thread.

When the Lua clock source is active however, the graphics thread will first acquire a lock on the graphics thread and then a lock on the script object to call into the Lua function.

This creates a situation where the graphics thread cannot call the Lua functions because the UI thread has locked the script for reloading, but the initialisation cannot succeed because it needs to call the graphics thread, whose thread holds the lock itself.

It's a known issue of the scripting system and there is no fix or workaround for it short of a rewrite or substantial extension of the current system that would allow scripts to interact with graphics in a way that avoids this deadlock.

**Closed by PatTheMav** 2023-07-04 16:18 UTC
