### ISSUE TITLE
OBS Controls UI elements create artifacts after changing DPI Scaling settings in Windows

### ISSUE THREAD

**Issue by nshire** [obsproject/obs-studio#3963] opened 2020-12-23 05:39 UTC
## Platform

Operating system and version:
Windows 10 x64 Version 2004 (OS Build 19041.685)
OBS Studio version:
26.1.0 (64 Bit)
Nvidia driver version:
457.51

## Expected Behavior

The UI should properly adjust to the DPI scaling changes
## Current Behavior

The UI elements artifact and overlap over each other, sometimes becoming unclickable.

[2020-12-22 16-35-03.txt](https://github.com/obsproject/obs-studio/files/5733442/2020-12-22.16-35-03.txt)

## Steps to Reproduce

https://user-images.githubusercontent.com/26775827/102962682-35046700-449c-11eb-8e65-7b7f2f102309.mp4

1. Change Windows DPI Scaling options, ideally starting at 150% before OBS is opened and then setting it to 100% while OBS is open.
2. The bug will occur.

## Additional information

Frequently happens when playing games at resolutions other than the monitor's native resolution.

**Comment by WizardCM** [comment] 2020-12-24 05:57
I am unable to reproduce this issue on my laptop. Qt should be triggering a full rerender which'd fix the issue, not sure why it's not on your machine.

**Comment by zavitax** [comment] 2021-01-03 11:50
Noticed all sorts of weird artifacts as well.

**Comment by RytoEX** [comment] 2022-10-14 05:09
Please try to reproduce this in OBS Studio 28.0.3 (or newer). This issue should be resolved, or the behavior improved at least somewhat.

**Comment by gxalpha** [comment] 2022-11-17 00:29
Closing as we believe that this is fixed and there hasn't been a response in a month.

If this is still an issue, please leave a comment here or open a new report with updated reproduction steps.

**Closed by gxalpha** 2022-11-17 00:29 UTC
Labels: Windows
