### ISSUE TITLE
Window positions and sizes not saved

### ISSUE THREAD

**Issue by josh-65** [obsproject/obs-studio#4673] opened 2021-05-08 23:31 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

it not a crash

### OBS Studio Crash Log URL

its not a crash

### Expected Behavior

windows like Settings, Advance audio mixer or others it should save the size and position when they were closed.

### Current Behavior

It will reset to the original position and size

### Steps to Reproduce

1. open a window
2. resize/position that window
3. close window
4. reopen window
5. it has reset

**Comment by WizardCM** [comment] 2021-05-09 00:12
This is by design, they center to where the OBS window is. That way they can't get "lost" across displays. Especially as you generally shouldn't be opening and closing them repeatedly.

**Closed by WizardCM** 2021-05-09 00:12 UTC

**Comment by josh-65** [comment] 2021-05-09 00:24
They should still keep the sizes set at least. It doesn't fit the windows to well for me. Settings is too wide and not tall as I want it and the advance auto mixer is a little too small so it doesn't show the audio track 6
