### ISSUE TITLE
Mouse not showing up when using window capture windows 10 (1903 and up) for some applications

### ISSUE THREAD

**Issue by HenkoHallows** [obsproject/obs-studio#7301] opened 2022-09-05 14:22 UTC
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/6U59JRCLiVIMXuVG

### Expected Behavior

I Expected to be able to capture in either Windows 7 and up or windows 10 (1903 and up) like i used to be able to, but it can't capture the applications in win 7 option.

### Current Behavior

if i use the win 10 option it captures properly but now i can't see my mouse in game only on the OBS window happens on every game if I'm trying to capture my Vtuber model at the same time with the window capture It happens in the PrprLive And Vtube Studio. Tried deleting all my OBS settings and reinstall OBS but that did nothing.

### Steps to Reproduce

1.Install Any 2D VTuber software: PrprLive, VTube Studio, Sometimes happens with the league client as well. Only seen it a few times there.
2. Use a Vtuber model.
3. Try to capture the model with a green screen and chroma the green screen out using the chroma key filter.
4. Use Game Capture to capture a game fx. Necesse, Project Zomboid.
5. Enter the game, and you wont be able to see the mouse on your main screen only in the OBS capture window.

**Comment by Fenrirthviti** [comment] 2022-09-06 04:44
I've tried everything I can think of to try and replicate this, and I can't replicate it. There is likely some kind of environment issue at play here, but I'm at a loss as to what. OBS simply captures, it can't affect how the OS draws a cursor. We draw the cursor based on position rather than part of the window capture itself, which is probably why it shows up in OBS.

**Comment by HenkoHallows** [comment] 2022-09-07 16:19
I am perplexed as well it doesn't seem to make any logical sense. Thank you for trying.

**Comment by RytoEX** [comment] 2022-10-22 06:42
Are there any sample Vtuber models or something that we can use to try to reproduce this?

**Comment by chinook77** [comment] 2022-11-14 12:38
I have the same bug.

**Comment by HenkoHallows** [comment] 2022-11-14 14:38
They should work.

https://workshop.bilibili.com/work/12482

https://workshop.bilibili.com/work/12257

**Comment by RytoEX** [comment] 2023-08-03 22:34
I've tested this on Windows 11 with VTube Studio (from Steam), OBS 29.1.3, and Overwatch. My mouse cursor appeared just fine in the Overwatch menu UI. I don't have Project Zomboid to test against. Please test for this behavior again. I'll close this for now, as I am unable to reproduce it. We can consider reopening it if more refined Steps To Reproduce are provided that produce the described behavior.

**Closed by RytoEX** 2023-08-03 22:34 UTC

**Comment by DefomCode** [comment] 2024-07-12 19:38
why problem is close?
