### ISSUE TITLE
[BUG] Obs x64 crash every time with VST plugin "pitchproof" enabled when exit.

### ISSUE THREAD

**Issue by PHCLMicoTW** [obsproject/obs-studio#2638] opened 2020-04-04 07:28 UTC
## Platform

Operating system and version: Windows 10 x64 build 18362
OBS Studio version: Obs 25.0.1 64-bit (Also occur on older version).

## Expected Behavior

Plugin work fine and:
Type 1: Closing and save all the data like normally.
Type 2: Can be disable plugin in sound filter dialog.

## Current Behavior

Plugin work fine but:
Type 1: Obs crash on exit every time with VST plugin "pitchproof" enabled.
Type 2: When disabling plugin in sound filter, Obs will crash like when it exiting.
Note: After remove plugin it will save sound filter setting (some times not), but others don't.

Logs: [obs crashes logs.zip](https://github.com/obsproject/obs-studio/files/4430893/obs.crashes.logs.zip)

## Steps to Reproduce

0. Install VST plugin "pitchproof" to the computer.

1.   Add VST 2.x plugin filter to any of sound source and choose "pitchproof-x64".
2.   To crash Obs:
2-1. Close Obs.
2-2. Remove "pitchproof" from sound filters list.
3.   Obs crashed.

Video: (Youtube)
 [![Reproducing Obs "pitchproof" plugin crash.](http://img.youtube.com/vi/Kt78WgStnUo/0.jpg)](http://www.youtube.com/watch?v=Kt78WgStnUo)
*P.S. I forgot I'm using another OBS for recording, so you can't hear what's the plugin sound like, but it work find.*

## Additional information

Only "pitchproof" will lead to Obs crash, I tested another plugin "GSnap" (which is a autotune plugin) it work totally fine.

### Edited
Add plugin download page here:
[Pitchproof is a free audio plug-in that can shift the pitch of the input.](https://aegeanmusic.com/pitchproof-specs)

**Comment by WizardCM** [comment] 2020-04-04 12:15
I have been able to reproduce this.

Where the error occurs:
https://github.com/obsproject/obs-vst/blob/master/VSTPlugin.cpp#L185

![image](https://user-images.githubusercontent.com/941350/78450419-2b4a9180-76ca-11ea-8aa5-cea8a7278dd7.png)

**Comment by notr1ch** [comment] 2020-04-04 22:56
Looks like this is an issue with the VST plugin if it's crashing inside the DLL after calling close.

**Comment by Fenrirthviti** [comment] 2020-04-26 05:59
Closing as this appears to be an issue with the plugin itself, not the OBS VST plugin. However, that said, if the plugin developer wishes to contest that, this issue should be reopened on the [obs-vst](https://github.com/obsproject/obs-vst) repo instead.

**Closed by Fenrirthviti** 2020-04-26 05:59 UTC
