### ISSUE TITLE
Can't set custom keybinds in OBS on Wayland

### ISSUE THREAD

**Issue by Alenygam** [obsproject/obs-studio#5021] opened 2021-07-22 18:30 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.1-2

### OBS Studio Log URL

https://obsproject.com/logs/L7oWIYh7lo5zO-J1

### Expected Behavior

The keybind would set fine.

### Current Behavior

The keyboard wasn't set, and while pressing the keys for setting the keybind nothing actually happened.

### Steps to Reproduce

1. Run Wayland (with QT_QPA_PLATFORM=wayland)
2. Settings > Hotkeys
3. Click on any hotkeys field field
4. Press keys
5. Enjoy bug

**Comment by fzwoch** [comment] 2021-07-22 18:38
Duplicate of #4992.

**Comment by Fenrirthviti** [comment] 2021-07-22 18:41
Duplicate of #4992

**Closed** 2021-07-22 18:40 UTC
