### ISSUE TITLE
SRT latency is insanely high

### ISSUE THREAD

**Issue by dgatwood** [obsproject/obs-studio#6536] opened 2022-05-24 06:03 UTC
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/En6SGtPit4_pmJP-

### Expected Behavior

I own a Panasonic AG-CX350, and have used it in the past as an NDI source.  I wanted to move to SRT because the latest firmware adds the ability to stream 4K video, but its NDI support is nerfed (limited to 1080p).

So I configured the camera to use 10 milliseconds of latency (I've also tried passing latency=10000 in the SRT URL).  This is over a wired LAN, so the round-trip latency is sub-millisecond).  Based on those settings, I would expect the captured video to be rendered with relatively low latency.

### Current Behavior

Video playback is delayed by an entire **second**, which means OBS's SRT ingest support is not even remotely usable for real-world production purposes.

And this all appears to be latency between the libraries and OBS itself.  I can actually bring the network latency down to the point where the connection becomes unreliable and it starts dropping out, but playback remains massively delayed.  So I think there must be some sort of timestamp bug involved.

### Steps to Reproduce

1.  Get a camera or other source of SRT video.
2. Connect OBS to it.
3. Observe the high latency.

**Comment by dgatwood** [comment] 2022-05-24 06:03
Also reported by several other people in the forums over the past couple of years on various operating systems.

**Comment by dgatwood** [comment] 2022-05-24 07:33
If I yank on the tripod, about one full second later, the image on my screen moves.  That one-second delay is independent of video mode, and occurs even when the camera is in iframe-only 1080p mode (single-frame GOP).

I would call that latency.  It's probably not *network* latency, but rather pipeline latency somewhere in the media source code (or, more likely, excessively cautious display timestamp computation).

**Comment by pkviet** [comment] 2022-05-24 07:34
Try setting a 0 buffer in Media Source

**Comment by pkviet** [comment] 2022-05-24 07:53
tested with larix broadcaster; i get indeed about 2 sec latency;
bug confirmed.

**Comment by flaeri** [comment] 2022-05-24 10:07
how are we testing?

Maybe I'm going about it in a flawed manner.
"ffplay" (the obs media source) inherently has a fair bit of buffering, unless you force its hand, which we can on latest master.

Caller, ffmpeg:
```
ffmpeg -f lavfi -i smptebars=duration=600:size=1920x1080:rate=60 -f lavfi -re -i sine=frequency=500:duration=6000:sample_rate=48000 -vf drawtext="fontsize=15:timecode='00\:00\:00\:00':rate=60:text='TCR\:':fontsize=72:fontcolor='white':\boxcolor=0x000000AA:box=1:x=860-text_w/2:y=960" -pix_fmt yuv420p -c:v libx264 -tune zerolatency -b:v 4000k -g 60 -keyint_min 60 -profile:v high -preset veryfast -f mpegts srt://127.0.0.1:10000
```

Gives me 60fps output, and displays a timecode that changes every frame (last digit, goes 00-59). 1sec gop, x264 tuned zerolatency, veryfast preset.

One the OBS side (listener), in a media source, I do:
Network buffer: 0mb
Input: srt://127.0.0.1:10000?mode=listener
Input format: mpegts

On current master, we also get "FFmpeg Options" exposed, in which I put the following:
`probesize=32 sync=ext`
(without this, there is a fair bit more delay, more than 60 frames I think.)

I record the ffmpeg window side by side with the OBS preview, and take notes of the time in the ffmpeg output and the frame number in the OBS preview. I review the video, and frame advance until ffmpeg ticks over to a new time and compare with OBS. I get the following:

```
run 1, 60fps, 19 frames
run 2, 60fps, 23 frames
run 3, 60fps, 23 frames
run 4, 60fps, 19 frames
```
Explanation:
60fps, = 0,06 per frame.
ffmpeg shows 70 = 700 milliseconds = 700*0,06 = 42 frames
obs shows frame #23 = 42-23 = 19 frames of delay

Examples:
![image](https://user-images.githubusercontent.com/50419942/170006315-a6b759b3-5beb-4be1-9198-9cdae833072b.png)

**Comment by pkviet** [comment] 2022-05-24 10:12
oh that's great @flaeri 
you should add this to the wiki.
I wasn't aware probesize could be set.
For the sake of accuracy, we don't use ffplay at all for Media Source. It's a separate implementation. The probesize is just an avformat demuxer option which works nevertheless.
Closing since it's fixed in master.

**Closed by pkviet** 2022-05-24 10:12 UTC
Labels: Confirmed

**Comment by flaeri** [comment] 2022-05-24 11:46
done @pkviet 
<https://github.com/obsproject/obs-studio/wiki/Streaming-With-SRT-Or-RIST-Protocols#latency>
