### ISSUE TITLE
CPU 

### ISSUE THREAD

**Issue by ForthtuN** [obsproject/obs-studio#3980] opened 2020-12-27 06:17 UTC
Operating system and version: Windows 10 64 bit, latest version
OBS Studio version: Latest version, 26.1.0

High cpu usage when upgrading from a older obs version and keeping scenes, reason is the media source from old upgrades.

The cpu is using more resources when using a old media source, source. Don't know how far back the faulty media source is but atleast a couple of years back in OBS versions.

## Steps to Reproduce

More info about it here:
https://obsproject.com/forum/threads/possible-cpu-hog-and-fix-steps-in-thread-if-using-a-old-media-source.131228/

## Additional information

Look in this thread for more info about it: https://obsproject.com/forum/threads/possible-cpu-hog-and-fix-steps-in-thread-if-using-a-old-media-source.131228/

**Comment by WizardCM** [comment] 2020-12-27 06:45
This is not a valid bug report. Please provide a session log file, and ideally scene collection JSON files of before and after.

**Comment by RytoEX** [comment] 2020-12-27 21:48
Please write isolated steps to reproduce the issue in the bug report rather than simply pointing to an external resource.  While you can additionally link to another resource, you should provide steps to reproduce here.

Are you saying that creating a Media Source in an older version of OBS and then updating OBS causes that Media Source to have high CPU usage?  And then deleting the Media Source and recreating it, without changing any settings, resolves this issue?

As @WizardCM said, we would need to see log files from before and after you recreated your Media Sources.  We may also need to see your scene collection file before and after you recreated an affected Media Source.

----

I've tried to reproduce this based on the information available by doing the following:
1. Open OBS Multiplatform 0.12.3.
2. Create a Media Source with default settings.
3. Create a second blank scene.
4. Switch scenes and observe CPU usage is about the same.
5. Close OBS.
6. Transfer settings to OBS Studio 26.1.0.
7. Open OBS Studio 26.1.0.
8. Observe that "Restart playback when source becomes active" is enabled.
9. Switch to the blank scene and observe that CPU usage drops when viewing the blank scene.
10. Switch to the scene with the Media Source.
11. Disable "Restart playback when source becomes active" on the Media Source.
12. Switch to the blank scene and observe that CPU usage is about the same in both scenes.

Since OBS Studio/Multiplatform 0.13.0, a Media Source will have "Restart playback when source becomes active" enabled by default, which will stop playing a Media Source once it is no longer active, thus reducing CPU usage (or GPU usage if hardware decoding is enabled).  This setting will automatically apply to Media Sources created in versions of OBS before 0.13.0 once they are loaded in version 0.13.0 or newer.

What _could_ have happened is that you had a Media Source with "Restart playback when source becomes active" explicitly disabled, and then when you recreated it, the setting was enabled by default, thus causing the CPU usage to drop when the source became inactive.  Log files from before and after recreating an affected Media Source would show its settings.

**Comment by eazydripz** [comment] 2021-06-03 14:11
Thank you.

**Comment by RytoEX** [comment] 2021-06-04 03:57
In the absence of any new information, I'm going to close this as it's too vague to be actionable.  I'm reasonably confident that at some point, the Media Sources in question had "Restart playback when source becomes active" explicitly disabled, and then recreating them from scratch enabled the option by default.  The OBS logs before and after would have had this information.  If this theory is correct, then this is also "Working as intended".

**Closed by RytoEX** 2021-06-04 03:57 UTC
Labels: Incomplete
