### ISSUE TITLE
OBS wont boot Normal, Safe mode works, Full reset does nothing

### ISSUE THREAD

**Issue by b14ckw1d0w** [obsproject/obs-studio#10192] opened 2024-02-03 11:23 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/FzM30bMhESLOEZbp

### Expected Behavior

To open as normal and function

### Current Behavior

Wont boot unless in Safe Mode, which works fully. I have deleted the obs folder in .config with the same result.

It worked before a reinstall. I tried to downgrade obs to a working version for nvenc which didn't work.

### Steps to Reproduce

1. Open OBS

**Comment by tytan652** [comment] 2024-02-03 11:24
Duplicate of #10174

**Closed by tytan652** 2024-02-03 11:24 UTC
