### ISSUE TITLE
In last version OBS can't record with second GPU

### ISSUE THREAD

**Issue by d4rkd3n1337** [obsproject/obs-studio#4826] opened 2021-06-06 16:39 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/nicorS1QiSR9EZs5

### Expected Behavior

Record with another gpu in 27.0 ver

### Current Behavior

If I am set GPU to 1 in 27.0.0 version, i can't start record screen. https://i.imgur.com/aZeh2YX.png

But if I install older version of OBS, all will work properly!

### Steps to Reproduce

1. Setting '1' for GPU NVENC in settings
2. Start record

**Comment by RytoEX** [comment] 2021-06-06 16:56
This is because the GTX 760 does not support Psycho Visual Tuning.  Disable Psycho Visual Tuning if you want to use the GTX 760 for NVENC.  Though arguably, you're getting worse performance this way than just using the GTX 960, which also has a standalone NVENC chip.  Shifting encoding to a second GPU is actually worse for performance, and you're using an older/worse generation of NVENC in this configuration as well.

This is either a support case or a duplicate of #4785, so I'm closing this.

**Closed by RytoEX** 2021-06-06 16:56 UTC

**Comment by d4rkd3n1337** [comment] 2021-06-06 17:53
Thanks a lot! Its helped!!! Have a nice day!
