### ISSUE TITLE
Enhanced broadcasting causes other services like Kick to fail

### ISSUE THREAD

**Issue by prgmitchell** [obsproject/obs-studio#11456] opened 2024-10-27 18:14 UTC
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/wj5DNd6evoaos70I

### Expected Behavior

Swapping over to a non-Twitch service should disable enhanced broadcasting

### Current Behavior

![image](https://github.com/user-attachments/assets/c7178458-c089-406a-af4b-8670536d9fa6)

You get this error because although you have swapped services the state of the enhanced broadcasting tick box does not reset.

### Steps to Reproduce

1. Connect a Twitch account
2. Tick the box to enable enhanced broadcasting
3. Switch service to custom and enter a Kick URL/stream key
4. Try to start stream

### Anything else we should know?

I have provided a log from the 31.0.0 beta but this is not unique to this version.

**Comment by derrod** [comment] 2024-10-27 19:38
I believe this is a duplicate of #11079

**Closed** 2024-10-27 20:13 UTC
