### ISSUE TITLE
OBS keeps the Microphone hooked even when the source is disabled

### ISSUE THREAD

**Issue by EmmaKnijn** [obsproject/obs-studio#10112] opened 2024-01-17 16:03 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/I1AtzYMtd5elnaQQ

### Expected Behavior

I expect OBS to not hook the Microphone when hiding the source, causing audio quality to improve on bluetooth headphones (and some wired ones)

### Current Behavior

OBS keeps the microphone active in the background causing horrible audio quality  on bluetooth headphones (as expected, this is normal if you're intending to use the microphone).

### Steps to Reproduce

1. Connect Bluetooth Headphones (I'm using Sennheiser Momentum 4's over USB
2. Inside of OBS, add a source with the bluetooth headphones' microphone
3. hide the source
4. See bug

### Anything else we should know?

I'm aware bluetooth decreases the audio quality when using the microphone. I intend to mute the microphone when I want high quality audio and unmute the microphone when I want to talk. This is however currently not possible.

**Comment by flaeri** [comment] 2024-01-17 16:20
Unfortunately, I believe this is by design. The "eye" (hide) is not actually a enable/disable (active/inactive if you will), it is just a "hide/unhide". That means that it is active, and its intended to be active, but hidden (removed from the mix).

**Comment by EmmaKnijn** [comment] 2024-01-17 17:01
In that case, this would be a feature request. Although I do think hiding some other sources (like the video capture source, for webcams, do unhook it)

**Comment by RytoEX** [comment] 2024-01-17 17:19
> In that case, this would be a feature request. Although I do think hiding some other sources (like the video capture source, for webcams, do unhook it)

Hiding a Video Capture Device still leaves the device active. If your webcam has an activity light, you can see that it is still lit. You can also see that it is likely not able to be loaded by other applications.

**Comment by EmmaKnijn** [comment] 2024-01-19 07:07
Alright, then its actually a feature request, should I open a new issue for it?

**Comment by flaeri** [comment] 2024-01-19 09:54
@EmmaKnijn unfortunately not, they don't do feature requests on github. It would go on the ideas page, here:
https://ideas.obsproject.com/

**Comment by gxalpha** [comment] 2024-01-19 14:57
Closing per the above. Please submit a feature request.

**Closed by gxalpha** 2024-01-19 14:57 UTC

**Comment by andybryant9** [comment] 2024-01-29 09:39
I couldn't find a feature request open on this; so [opened one here](https://ideas.obsproject.com/posts/2507/ability-to-unhook-microphone-from-obs-without-removing-it-from-settings)
