### ISSUE TITLE
OBS no see hw codec amdvce in VEGA3

### ISSUE THREAD

**Issue by woodsleaf** [obsproject/obs-studio#7983] opened 2022-12-29 16:27 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/L6GrBwmJXVpDqtz_

### Expected Behavior

in codec can choice  amd vce

### Current Behavior

only h264 and nvidia, can choice amd vce

### Steps to Reproduce

1. open settings
2. output
3. press left button on input list when codec choice

### Anything else we should know?

cpu Athlon 200GE
igpu Vega 3
AMD Driver version 22.11.2
windows 10 22H2

! in other software 'Handbrake' i see codec amd vce and can use it.

**Comment by RytoEX** [comment] 2022-12-30 15:05
I'm fairly certain this is fixed in OBS Studio 29 Beta 3. Please retest in OBS Studio 29 Beta 3 (or newer).

**Comment by gxalpha** [comment] 2023-04-05 19:11
We believe this is a duplicate of https://github.com/obsproject/obs-studio/issues/7130 and was fixed in OBS Studio 29.0.

**Closed by gxalpha** 2023-04-05 19:11 UTC
