### ISSUE TITLE
MacOS Silicon 

### ISSUE THREAD

**Issue by jasongoldsmith1** [obsproject/obs-studio#7336] opened 2022-09-10 13:47 UTC
### Operating System Info

macOS 12

### Other OS

12.5.1

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/E44uYRE4-lSfF7gb

### Expected Behavior

Copy and paste inside OBS Studio chat box not following expectations. 

When I have text in my clipboard and I want to paste it into the chat box in OBS, it pastes into the preview scene instead of the chat box. Expected behaviour would be for text to be able to be pasted (command V) into the chat box rather than pasting into the preview scene. Right click > paste works, but command V doesn't. 

### Current Behavior

When text is on the clip board and I attempt to paste it in to the chat box, it pastes into the preview scene instead as a new source. 

### Steps to Reproduce

1. Copy text onto the clipboard
2. Set focus on the chat box window
3. Press Command V to paste the text into the chat box
4. OBS preview scene receives the pasted text instead
...

**Comment by RytoEX** [comment] 2022-09-10 15:19
Duplicate of https://github.com/obsproject/obs-browser/issues/365

**Closed by RytoEX** 2022-09-10 15:19 UTC
