### ISSUE TITLE
Unusual Twitch Stream Reconnection Audio Bug

### ISSUE THREAD

**Issue by kkgm13** [obsproject/obs-studio#6557] opened 2022-05-29 13:18 UTC
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://gist.github.com/cf4a75cf455783cf659211fbb719cbdf

### Expected Behavior

A disconnected Twitch stream should reconnect back to Twitch streaming services as normal with audio, even with the Disconnect Protection option.

### Current Behavior

A _unusual_ case scenario where the network reconnecting to Twitch stream causes the audio to not transmit requiring to **manually** restart the Twitch Stream. (Currently noticeable towards Twitch EU servers, dunno for other Twitch servers or providers with OBS [eg. YouTube])

### Steps to Reproduce

1. Stream normally (ensure Disconnect Protection is on)
2. If a random disconnect from Twitch happens, let it reconnect normally
3. Check stream to see if audio is being sent on stream. Stream should be completely muted despite stream should be unmuted. OBS sees audio passing through
...

### Anything else we should know?

I have noticed another streamer friend of mine having this issue as well and have experience it twice. I am lead to believe it might be a connection issue between Twitch servers and OBS during the reconnection. I personally don't which of the two is responsible. 

Also the log file sent was the first half of that stream, the second half of the log for the same stream is no longer available.

**Comment by derrod** [comment] 2022-05-29 13:22
This is a known issue when using the VOD track option. I don't know if we've heard back from Twitch yet on whether that issue is on our end or theirs.

**Comment by gxalpha** [comment] 2022-05-29 18:36
Duplicate of #5572

**Closed by gxalpha** 2022-05-29 18:36 UTC

**Comment by kkgm13** [comment] 2022-05-29 22:14
ah so it was Twitch itself.. that saves me a lot of headaches to explain to my friend about that then.

**Comment by OtterNas3** [comment] 2022-07-22 09:36
Any update on this one?
I experienced this issue a couple of times actually, each time on a reconnect.

Moo,
Otter
