### ISSUE TITLE
Device not connected or not available issue

### ISSUE THREAD

**Issue by Abdurahman-hassan** [obsproject/obs-studio#6667] opened 2022-06-28 06:22 UTC
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/jUn80bXKWQFFHYln

### Expected Behavior

once I select a capture screen it should start normally without any issues even though i closed the application and open it again

### Current Behavior

" Device not connected or not available "
And the  OBS already takes a screen recording permission
every time I need to remove the current screen capture and add a new one to solve an issue temporarily

### Steps to Reproduce

1. I Open the OBS app 
2. makes sure that the permissions of screen recording is taken normally
3. I click on add button to add a screen capture 
4. the black screen shows instead of the normal screen 
5. I removed the screen capture  with the minus button 
6. I add the screen capture again it shows normally without any issue 

### Anything else we should know?

thank you, i hope to solve this issue

**Comment by WizardCM** [comment] 2022-06-28 06:25
Duplicate of #4011

**Closed by WizardCM** 2022-06-28 06:25 UTC
