### ISSUE TITLE
Media control doesn't update when scene selected via hotkeys or remote apps

### ISSUE THREAD

**Issue by BevDan** [obsproject/obs-studio#4540] opened 2021-04-16 12:46 UTC
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/5IFsgl20iyI0mZ33

### Expected Behavior

When I select a scene by clicking on the scene the Media timer starts counting down the length of the video, I expect the same to occur when using hotkeys or remote control app (Touch Portal)

### Current Behavior

using hotkeys or remote app (Touch Portal), the scene changes normally but the Media timer does not update to the new scene, just ends with the previous scene's media file, I suspect the media timer is event driven from mouse click on the scene

### Steps to Reproduce

1. Set up two or more scene's with at least a media file (Video) in each scene
2. Clicking on a scene and then transitioning from preview to program the media timer starts counting
3. Clicking on the next scene cause the media title to update and the timer is reset 0:00:00 and hold until transitioning
4. Setup hotkeys eg (number pad 1 = Switch to scene 1, number pad 2 = Switch to scene 2, + key is used for transition)
5. Click on scene 1 and transition it by mouse click, media timer starts counting, press number pad 2, the media title doesn't update, pressing the + to transition or click transition does not start the media timer

**Comment by WizardCM** [comment] 2021-04-17 00:00
Could you retest this in OBS 27 RC2?

**Comment by RytoEX** [comment] 2022-11-16 20:39
We've tested on OBS Studio 28.1.2 and cannot reproduce this, so we're closing this as fixed (it was likely fixed back in OBS Studio 27). If you test in the current release of OBS Studio and still experience this issue, please reply with new Steps To Reproduce and we can consider whether to reopen this issue or open a new issue.

**Closed by RytoEX** 2022-11-16 20:39 UTC
