### ISSUE TITLE
[BUG] Memory leak in VLC source when playing .FLV files on macOS

### ISSUE THREAD

**Issue by desplesda** [obsproject/obs-studio#2919] opened 2020-05-12 04:58 UTC
## Platform

Operating system and version: macOS 10.15.4
OBS Studio version: 25.0.8

## Expected Behavior

VLC video sources that load a .FLV file on macOS play back video, with minimal memory usage gain over extended periods of play.

## Current Behavior

The memory usage of OBS grows rapidly (on the order of 1GB every 30 seconds) while the source is playing. This eventually causes the entire machine to run out of memory.

## Steps to Reproduce

1. Create an empty scene.
2. Add a VLC player.
3. Add a .FLV file to its playlist.
4. Open Activity Monitor, and observe that the memory usage is growing rapidly.

## Additional information

The memory usage stops growing when the VLC source is removed, but the memory usage does not go down. This suggests that the memory has been leaked.

I saw this issue appear when playing back video from the local disk, from a network share, and via an RTMP server (which serves video as FLV streams).

I observed this issue on macOS 10.14 as well.

The issue did **not** appear on Windows 10 (using the same input files), or when playing back a .mp4 file on macOS.

The issue also does not appear in VLC, when I play the same video files directly - I've only seen it appear when I play the video in a VLC source in OBS.

I've attached a zip that contains a video file demonstrating the problem.

[Screen Recording 2020-05-12 at 2.44.35 pm-720p.mp4.zip](https://github.com/obsproject/obs-studio/files/4613464/Screen.Recording.2020-05-12.at.2.44.35.pm-720p.mp4.zip)

**Comment by DarkDust** [comment] 2020-05-30 14:30
I'm also having memory usage explode with VLC playback (VLC 3.0.10 via Homebrew, macOS 10.14.6), but only for certain videos. I was trying to find and fix it, but failed so far. I was able to isolate it somewhat: here are two videos that trigger the issue: 

* https://www.youtube.com/watch?v=AQO1gVfLPfY&list=RDEM1-vAN9DgPgugabI9Pwo-vg&index=5
* https://www.youtube.com/watch?v=EvlKzrN2iyc

 (Download them via JDownloader2.)

I did manage to find a minor memory leak, though: in `vlc-video-source.c`, function `vlcs_get_metadata`. Here we query a media via `libvlc_media_player_get_media_`, which returns a _retained_ reference. It needs to be released via `libvlc_media_release_(media);` at the end of the function.

**Comment by DarkDust** [comment] 2020-06-01 14:40
I was able to track it down and fix it: the memory leak here is happening in VLC: [VLC ticket #20576](https://trac.videolan.org/vlc/ticket/20576). Thus an update of VLC with that fix is required to resolve this memory leak.

**Comment by RytoEX** [comment] 2020-06-01 21:59
If the issue is in VLC itself, then should this ticket be closed?  We don't actually distribute any VLC binaries.  We only use VLC's code headers and then use VLC if the user has it installed.

**Comment by Fenrirthviti** [comment] 2020-06-01 22:33
Indeed, closing as the fix has been submitted upstream to VLC. Thanks for tracking it down!

**Closed by Fenrirthviti** 2020-06-01 22:33 UTC
Labels: Dependency Issue, macOS
