### ISSUE TITLE
[30.2.3/31.0.0-beta3] Bug the replay buffer option

### ISSUE THREAD

**Issue by Alzyon** [obsproject/obs-studio#11489] opened 2024-11-05 06:42 UTC
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/rwaamdzkXxwAvKwh

### Expected Behavior

I would want disable the replay buffer, because use not it.

### Current Behavior

Hi,

When I uncheck the replay buffer option, and restart OBS, the option is active again. I've tried repairing and upgrading to 31.0.0-beta3, but the problem still seems to be there.

### Steps to Reproduce

1. Launch OBS Studio 30.2.3 or 31.0.0-beta3
2. Uncheck the replay buffer option and confirm
3. After reboot OBS Studio, the replay buffer option is checked again

### Anything else we should know?

Not at the moment. But I'll keep you posted.

**Comment by Penwy** [comment] 2024-11-05 06:50
Does it still happen if obs is launched in safe mode?

**Comment by Penwy** [comment] 2024-11-05 22:25
Then this is a support issue, not a bug, and doesn't warrant a bug report.
I'd suggest closing this issue, and asking in the [forums](https://obsproject.com/forum/) or [discord server](https://obsproject.com/discord/).

**Comment by DerekTurtleRoe** [comment] 2024-11-06 03:44
I've actually been encountering this issue since version 30.0, and after several reinstalls and versions, I think it is safe to say something is buggy.

I have confirmed the issue on Windows 11 Pro, and OBS version 30.2.3 as well as 31.0.0-beta3.

Portable installs and regular installs are both affected, regardless of plugins installed.

I also tried with no plugins installed and using the default settings. The issue occurs no matter what I've tried.

**Comment by Penwy** [comment] 2024-11-06 03:48
@DerekTurtleRoe if _your_ issue also happens in safe mode, then it is not, in fact, the same issue as the one discussed here.
If it does not happen in safe mode, but does happen without any third party plugin, then it's caused either by a script, or by something connect to websockets (and not caused by obs itself).

**Comment by DerekTurtleRoe** [comment] 2024-11-06 03:51
> @DerekTurtleRoe if _your_ issue also happens in safe mode, then it is not, in fact, the same issue as the one discussed here. If it does not happen in safe mode, but does happen without any third party plugin, then it's caused either by a script, or by something connect to websockets (and not caused by obs itself).

Well, the issue does occur in safe mode, and I don't have any scripts or websocket items in my main OBS install. Nor did I have them in my portable installs, obviously.

So should I open another issue?

**Comment by 2008dmx** [comment] 2024-11-07 20:14
https://www.videohelp.com/software/x264-Encoder
Latest version
164 r3198 (October 26, 2024) 
Update the library libx264-164.dll, as well as AAC & Opus !!!

**Comment by 2008dmx** [comment] 2024-11-07 20:16
PLEASE(!)

**Closed as completed** 2024-11-07 22:39 UTC
