### ISSUE TITLE
Performance regression on Wayland / Gnome / Nvidia?

### ISSUE THREAD

**Issue by ioquatix** [obsproject/obs-studio#9895] opened 2023-11-20 08:32 UTC
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JcApW2lpxDu3HH9L

### Expected Behavior

Can record a video. I have an AMD 7950 + Nvidia 4090.

### Current Behavior

OBS eating a decent chunk of CPU:

![image](https://github.com/obsproject/obs-studio/assets/30030/ad6d15a2-83aa-476e-b78f-7fb40e84cb29)

Gnome Shell eating a decent chunk of CPU:

![image](https://github.com/obsproject/obs-studio/assets/30030/15749e96-7277-4cc7-9662-1ea461969174)

After 10-20 seconds of recording, error reported:

```
An encoder error occurred while recording:

Encoder NVIDIA NVENC H.264 (FFmpeg) is taking too long to encode (timeout: 5 seconds)
```

### Steps to Reproduce

1. Add Screen Capture (PipeWire)
2. Add Video Capture (optional)

Try to record using default settings (according to setup wizard).

With only video capture, I can easily hit 60FPS:

![image](https://github.com/obsproject/obs-studio/assets/30030/b00b702b-4ff9-46ba-a8ed-5272e89ca900)

As soon as I enable Screen Capture (PipeWire), I get potato FPS:

![image](https://github.com/obsproject/obs-studio/assets/30030/e562c30f-ccb9-454a-87b2-adb71ebd123b)

### Anything else we should know?

I have been running OBS on X11 just fine with a similar setup. I will test this further.

`nvidia-smi` output during recording:

```
> nvidia-smi
Mon Nov 20 21:25:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.02              Driver Version: 545.29.02    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0  On |                  Off |
|  0%   50C    P2             107W / 450W |   6723MiB / 24564MiB |     65%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     40714      G   /usr/bin/gnome-shell                        565MiB |
|    0   N/A  N/A     41010      G   /usr/bin/gnome-software                      27MiB |
|    0   N/A  N/A     41234      G   /usr/lib/xdg-desktop-portal-gnome            10MiB |
|    0   N/A  N/A     41267      G   /usr/bin/Xwayland                          2480MiB |
|    0   N/A  N/A     84120      G   ...Y2Q3ZGZjMDRlZjI3ODEw&browser=chrome       58MiB |
|    0   N/A  N/A    183148      G   /usr/lib/epiphany-search-provider             6MiB |
|    0   N/A  N/A    184876    C+G   obs                                        3502MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by ioquatix** [comment] 2023-11-20 08:48
Here is the performance data... not surprisingly, it looks bad.

```
info: audio_thread(Audio): min=0.003 ms, median=0.11 ms, max=1.135 ms, 99th percentile=0.452 ms
info:  ┗receive_audio: min=0.001 ms, median=0.225 ms, max=1.008 ms, 99th percentile=0.413 ms, 0.413059 calls per parent call
info:    ┣buffer_audio: min=0 ms, median=0.001 ms, max=0.015 ms, 99th percentile=0.008 ms
info:    ┗do_encode: min=0.094 ms, median=0.221 ms, max=1.001 ms, 99th percentile=0.409 ms
info:      ┣encode(simple_aac): min=0.093 ms, median=0.208 ms, max=0.317 ms, 99th percentile=0.294 ms
info:      ┗send_packet: min=0.001 ms, median=0.008 ms, max=0.724 ms, 99th percentile=0.217 ms
info: obs_graphics_thread(16.6667 ms): min=0.076 ms, median=0.795 ms, max=5711.32 ms, 99th percentile=1278.8 ms, 74.4615% below 16.667 ms
info:  ┣tick_sources: min=0 ms, median=0.003 ms, max=113.917 ms, 99th percentile=0.072 ms
info:  ┣output_frame: min=0.034 ms, median=0.261 ms, max=2189.31 ms, 99th percentile=684.534 ms
info:  ┃ ┣gs_context(video->graphics): min=0.034 ms, median=0.26 ms, max=2187.72 ms, 99th percentile=684.534 ms
info:  ┃ ┃ ┣render_video: min=0.012 ms, median=0.211 ms, max=2.567 ms, 99th percentile=1.261 ms
info:  ┃ ┃ ┃ ┣render_main_texture: min=0.01 ms, median=0.206 ms, max=1.996 ms, 99th percentile=0.693 ms
info:  ┃ ┃ ┃ ┣render_convert_texture: min=0.015 ms, median=0.043 ms, max=0.532 ms, 99th percentile=0.532 ms, 0.0646154 calls per parent call
info:  ┃ ┃ ┃ ┗stage_output_texture: min=0.009 ms, median=0.019 ms, max=1.934 ms, 99th percentile=1.934 ms, 0.0646154 calls per parent call
info:  ┃ ┃ ┣gs_flush: min=0.002 ms, median=0.004 ms, max=0.896 ms, 99th percentile=0.181 ms
info:  ┃ ┃ ┗download_frame: min=0 ms, median=0.002 ms, max=0.005 ms, 99th percentile=0.005 ms, 0.0646154 calls per parent call
info:  ┃ ┗output_video_data: min=0 ms, median=2.406 ms, max=4.032 ms, 99th percentile=4.032 ms, 0.0615385 calls per parent call
info:  ┗render_displays: min=0.012 ms, median=0.262 ms, max=753.45 ms, 99th percentile=31.391 ms
info: video_thread(video): min=2.06 ms, median=11.911 ms, max=1997.52 ms, 99th percentile=1997.52 ms
info:  ┗receive_video: min=1.57 ms, median=8.173 ms, max=19.648 ms, 99th percentile=13.719 ms, 21.2353 calls per parent call
info:    ┗do_encode: min=1.57 ms, median=8.172 ms, max=19.647 ms, 99th percentile=13.719 ms
info:      ┣encode(simple_video_stream): min=1.566 ms, median=8.136 ms, max=13.863 ms, 99th percentile=13.702 ms
info:      ┗send_packet: min=0.001 ms, median=0.011 ms, max=1.019 ms, 99th percentile=0.24 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.038 ms, median=25.083 ms, max=27.647 ms, 99.6546% within ±2% of 25 ms (0% lower, 0.345423% higher)
info: obs_graphics_thread(16.6667 ms): min=1.467 ms, median=16.667 ms, max=5711.34 ms, 51.2346% within ±2% of 16.667 ms (22.8395% lower, 25.9259% higher)
info: =================================================
info: Number of memory leaks: 0
```

**Comment by tiberium-v** [comment] 2023-11-20 09:05
Maybe related: https://github.com/obsproject/obs-studio/issues/9870
A downgrade of the driver resolve they problem.

**Comment by ioquatix** [comment] 2023-11-20 09:26
I have isolated at least one facet of the problem. Using the ultra-wide resolution 7680x2160 has performance issues as outlined above while changing my SCREEN resolution to 3840x2160 allows me to achieve close to 60FPS.

In both cases, the base resolution and output resolution remains the same, 4k: 3840x2160 - so no changes on OBS configuration, only on screen resolution. Could this be an issue with pipewire?

**Comment by kkartaltepe** [comment] 2023-11-20 15:32
pipewire sends obs the entire screen, we are using the entire 7680x2160 buffer if you set your screen to that. Since gpu work appears to be the issue it makes sense that reducing the size of your screen improves the situation. 

provide the entire log that contained the performance portion please.

**Comment by erik-kz** [comment] 2023-11-20 17:07
Unfortunately GNOME currently disables dma-buf screen sharing with the NVIDIA driver, meaning it will fall back to a CPU copy. It's not particularly surprising that this would perform poorly at higher resolutions.

**Comment by ioquatix** [comment] 2023-11-20 21:01
Ah, that makes sense. Is there any way to enable it for testing?

**Comment by ioquatix** [comment] 2023-11-21 01:49
I did a bit of digging and found https://gitlab.gnome.org/GNOME/mutter/-/commit/2b4a24132bc5e5d0ed8dd097ef155d083e302187

It looks like it's hitting this case:

```
Nov 15 17:01:09 aiko gnome-shell[11959]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
Nov 16 12:42:56 aiko gnome-shell[40159]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
Nov 16 12:54:54 aiko gnome-shell[40714]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
Nov 20 21:41:53 aiko gnome-shell[1168]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
Nov 20 21:42:11 aiko gnome-shell[1809]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
Nov 21 13:19:31 aiko gnome-shell[31223]: Disabling DMA buffer screen sharing (implicit modifiers not supported)
```

I assume we can't do anything until Nvidia decides to support it?

**Comment by kkartaltepe** [comment] 2023-11-21 02:11
Closing this as there seems to be no regressions based on discussions.

**Closed by kkartaltepe** 2023-11-21 02:11 UTC

**Comment by erik-kz** [comment] 2023-11-21 03:09
> Assume it's this extension? [EGL_EXT_image_dma_buf_import_modifiers](https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_image_dma_buf_import_modifiers.txt)? Looks like it's not really supported: https://forums.developer.nvidia.com/t/egl-ext-image-dma-buf-import-broken-egl-bad-alloc-with-tons-of-free-ram/165552/4

The issue described in that forum post isn't really related to this, and in fact what they were trying to do should now work with recent versions of the driver.

This is a different bug with our implementation of that extension. Essentially, we *require* applications to provide "explicit" format modifiers but the extension says they should be optional. If they are not provided we're supposed to use an "implicit" modifier instead but that doesn't work.

It *is* something we intend to fix, but I can't provide a timeline yet, sorry.

**Comment by ioquatix** [comment] 2023-11-21 03:16
@erik-kz is there somewhere I can track progress on this issue so I can help test and provide feedback etc.

**Comment by erik-kz** [comment] 2024-02-22 22:34
My colleague Dogukan has contributed the following change to GNOME which I believe should fix this issue https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3537
