### ISSUE TITLE
Record using svt-av1, crash happens!

### ISSUE THREAD

**Issue by ChenGXQQ** [obsproject/obs-studio#10926] opened 2024-06-27 08:20 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/JR6LlaGkHybIVeVh

### Expected Behavior

svt-av1 encode goes well.

### Current Behavior

Obs crash

### Steps to Reproduce

1.Settings -> output and choose output mode as Advanced -> Recording and set video encoder as "SVT-AV1"
2. click "Start Recording".  Wait a minute, obs crash!

![image](https://github.com/obsproject/obs-studio/assets/20234781/e1ed9013-15e9-421d-a9fa-fac5764a5e7d)

**Comment by flaeri** [comment] 2024-06-27 12:37
I think its very likely that this is a duplicate of https://github.com/obsproject/obs-studio/issues/10745

You can confirm by setting the CPU preset to 10 or higher.

**Comment by ChenGXQQ** [comment] 2024-06-28 00:51
You are right. No crash happens when I set the preset to be higher than 10. Thank you.

**Comment by Fenrirthviti** [comment] 2024-06-28 03:32
Duplicate of #10745

**Closed by Fenrirthviti** 2024-06-28 03:32 UTC

**Comment by chrcoluk** [comment] 2024-10-01 14:39
Same issue in build 31.0.2.
