### ISSUE TITLE
OBS Studio 27 RC2 doesn't record at 60fps from the Wayland session of Fedora 34 Workstation (Linux)

### ISSUE THREAD

**Issue by cold-distance** [obsproject/obs-studio#4590] opened 2021-04-24 15:40 UTC
### Operating System Info

Other

### Other OS

Fedora

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/_rZQCxlVXziqhFW9

### Expected Behavior

Obviously, I expect to truly record at 60fps from the Wayland session of Fedora 34 Workstation with PipeWire.

### Current Behavior

Hi, I'm trying to record from a Wayland session using Fedora 34 Workstation (GNOME), but I can't record at 60fps. I tried to record from a Xorg session and it's capable to record at 60fps. I didn't have the same issue with Fedora 33 Workstation.

I'm not sure if it's a PipeWire problem or a OBS problem, so I will try to ask here first. The log file says there is no issues, but booting the application with the terminal always says me that the application detected three memory leaks (I don't know if it's useful or not). I tried to force DMA-BUF without any change in the results.

`gsettings set org.gnome.mutter experimental-features "['dma-buf-screen-sharing']"`

My current hardware is a Ryzen 1700 with a RX 580 GPU with drivers provided by the Fedora repositories.

-Trying to record from the Wayland session of Fedora 34 Workstation: https://drive.google.com/file/d/1z4QTOXpYhNrQhld56TMR3JJIAhZ_dQW6/view?usp=sharing

-Trying to record from the Xorg session of Fedora 34 Workstation: https://drive.google.com/file/d/1gYSSNjMG1f8p2dfhq0TJmCQXVhsq2JWq/view?usp=sharing

### Steps to Reproduce

1. Install OBS Studio 27 RC2 from RPMFusion or the Flatpak version from Flathub.
2. Set the app to record the whole desktop (screen capture with PipeWire)
3. After doing the recording, you can see that the resultant video is not running at 60fps because it wasn't recorded at 60fps even if the application is correctly configured.

**Comment by GeorgesStavracas** [comment] 2021-04-26 12:24
Just to make sure: is OBS Studio itself configured to capture at 60 FPS? You can see that in the "Video" tab of the "Settings" dialog?

Other than that, this can be anything from your graphics card not keeping up with the stream, to Mutter not being fast enough, to PipeWire not properly scheduling frames as expected, to OBS Studio taking too long to render each monitor frame. At some point I'd like to add some profiling helpers into the PipeWire code inside OBS Studio, but that didn't happen yet.

**Comment by cold-distance** [comment] 2021-04-26 13:46
I'm sure that everything is OK. I tried software encoding and hardware encoding with DMA-BUF activated and deactivated and I always have the same result. Hardware encoding doesn't mind for me because the support for AMD GPUs is not very good, but I always been able to record at 60fps smoothly (and I even can record at 60fps with Xorg on Fedora 34).

I'm also thinking it could be a problem with Mutter or PipeWire, but my knowledge is not enough to determine what is failing.

![Captura de pantalla de 2021-04-26 15-33-45](https://user-images.githubusercontent.com/43167050/116092756-5f626d00-a6a6-11eb-8643-d95e02c50a2b.png)
![Captura de pantalla de 2021-04-26 15-33-36](https://user-images.githubusercontent.com/43167050/116092760-5ffb0380-a6a6-11eb-9eec-fd1e2af3beb2.png)
![Captura de pantalla de 2021-04-26 15-30-17](https://user-images.githubusercontent.com/43167050/116092763-60939a00-a6a6-11eb-9839-0b29b3ec679c.png)
![Captura de pantalla de 2021-04-26 15-29-42](https://user-images.githubusercontent.com/43167050/116092765-60939a00-a6a6-11eb-90d9-4e9fca497ca4.png)
![Captura de pantalla de 2021-04-26 15-29-30](https://user-images.githubusercontent.com/43167050/116092767-60939a00-a6a6-11eb-9510-b4eae17e021c.png)

**Comment by RytoEX** [comment] 2021-04-26 14:53
> 
> 
> Just to make sure: is OBS Studio itself configured to capture at 60 FPS? You can see that in the "Video" tab of the "Settings" dialog?
> 
> Other than that, this can be anything from your graphics card not keeping up with the stream, to Mutter not being fast enough, to PipeWire not properly scheduling frames as expected, to OBS Studio taking too long to render each monitor frame. At some point I'd like to add some profiling helpers into the PipeWire code inside OBS Studio, but that didn't happen yet.

The log file can answer most of this.

Here's the Video settings:
> 17:16:31.410: video settings reset:
> 17:16:31.410: 	base resolution:   1920x1080
> 17:16:31.410: 	output resolution: 1920x1080
> 17:16:31.410: 	downscale filter:  Bilinear
> 17:16:31.410: 	fps:               60/1
> 17:16:31.410: 	format:            NV12
> 17:16:31.410: 	YUV mode:          709/Partial

Here's the Output (encoder) settings:
> 17:16:37.635: [x264 encoder: 'simple_h264_recording'] preset: veryfast
> 17:16:37.635: [x264 encoder: 'simple_h264_recording'] profile: high
> 17:16:37.635: [x264 encoder: 'simple_h264_recording'] settings:
> 17:16:37.635: 	rate_control: CRF
> 17:16:37.635: 	bitrate:      0
> 17:16:37.635: 	buffer size:  0
> 17:16:37.635: 	crf:          16
> 17:16:37.635: 	fps_num:      60
> 17:16:37.635: 	fps_den:      1
> 17:16:37.635: 	width:        1920
> 17:16:37.635: 	height:       1080
> 17:16:37.635: 	keyint:       250

The recording session:
> 17:16:37.648: ==== Recording Start ===============================================
> 17:16:37.648: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/user/Vídeos/2021-04-24_17-16-37.mkv'...
> 17:16:43.328: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/user/Vídeos/2021-04-24_17-16-37.mkv' stopped
> 17:16:43.328: Output 'simple_file_output': stopping
> 17:16:43.328: Output 'simple_file_output': Total frames output: 302
> 17:16:43.328: Output 'simple_file_output': Total drawn frames: 340
> 17:16:43.328: ==== Recording Stop ================================================

43.328 - 37.648 = 5.68 seconds
5.68 seconds at 60 FPS = 340.8 frames

Nothing in the profiler section at the end of the log looks terribly out of place that would indicate such bad render lag that we drop from 60 FPS to 30 FPS:
> 17:16:44.279: obs_graphics_thread(16,6667 ms): min=0,08 ms, median=0,482 ms, max=21,326 ms, 99th percentile=4,941 ms, 99,87% below 16,667 ms
> [...]
> 17:16:44.279: video_thread(video): min=1,113 ms, median=2,103 ms, max=13,209 ms, 99th percentile=3,713 ms


I'm inclined to say that this is caused by something outside of OBS.

**Comment by cold-distance** [comment] 2021-04-28 19:01
I tried to record just now with my laptop, that has an Comet Lake processor with just integrated graphics and I can record at 60fps, so it seems a problem with drivers.

**Comment by vchernin** [comment] 2021-05-03 01:54
As others have suspected, this does not look to be a OBS studio-specific bug. It seems that when dma-buf screen sharing is enabled, Mutter incorrectly assumes to use dma-buf for all screen sharing. This assumption causes bugs like this one, since Mutter is not actually capable of correctly using dma-buf for screen sharing in every case. Mutter should only use dma-buf when the client (like OBS) explictly negotaties for it. See this [mutter bug](https://gitlab.gnome.org/GNOME/mutter/-/issues/1736).

A similar incorrect assumption and bug is present in WebRTC, see this [chromium flatpak discussion](https://github.com/flathub/org.chromium.Chromium/pull/88).

[This comment from grulja reiterates this point](https://github.com/flathub/org.chromium.Chromium/pull/88#issuecomment-824802875).
> Indeed. I talked to Jonas Ådahl and we should fix it in WebRTC. I hopefully will be able to look into it soon.  
> 
> On the other hand he told me that Mutter does it wrong as well, it shouldn't default to use dma-bufs by default when enabled, but it should (and will in future) use it only when the client explicitly requests it, which is something WebRTC doesn't do.

**Comment by WizardCM** [comment] 2021-05-13 23:54
Per the above comment, I will close this issue for now. If, once Mutter has fixed on their end, and there are still issues with OBS, feel free to comment below and we'll revisit the issue.

**Closed by WizardCM** 2021-05-13 23:54 UTC

**Comment by yhojann-cl** [comment] 2022-06-16 02:40
Same problem using OBS 27.2.4 on Ubuntu 22.04 LTS (wayland) over Flatpack package. I use PipeWire for capture and record current screen but have lost fps, i setting the best quality and 60fps in obs but in the final video file only can see ~30 fps.
