### ISSUE TITLE
Auto updater doesn't change version number in Windows Installed Programs list

### ISSUE THREAD

**Issue by TheJanzap** [obsproject/obs-studio#7728] opened 2022-11-06 13:10 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/foT-hS36B_zROf7n

### Expected Behavior

When running the auto updater and installing a new version, the version stored in the registry used in Windows' program list should be updated to the new value.

### Current Behavior

Version number remains the same

### Steps to Reproduce

1. Install older version of OBS (I used 28.0.3)
2. Verify the version number in the Windows system settings -> Apps -> OBS Studio
3. Run OBS and install the OBS Upgrade when offered
4. Check version number again. It remains on the previous version (28.0.3 instead of 28.1.2)

### Anything else we should know?

This is significant because the Windows "packet mananger" winget uses this version number to determine if an update is available, so I'm getting prompted by winget to update OBS even though I'm on the latest version.

**Comment by gxalpha** [comment] 2022-11-06 13:11
Duplicate of #2897

**Closed by gxalpha** 2022-11-06 13:11 UTC
