### ISSUE TITLE
OBS crashes with second Decklink Card (or Decklink Duo)

### ISSUE THREAD

**Issue by frainge** [obsproject/obs-studio#9697] opened 2023-10-12 10:21 UTC
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/jz32J1pwuXuZBmMF

### OBS Studio Crash Log URL

https://obsproject.com/logs/rcTgK8rEEkCugN0B

### Expected Behavior

The Decklink Output should show the correct Output or Preview Output after clicking on "Start" Button.
OBS Studio should not crash after clicking on "Stop"-Button

### Current Behavior

Tools - >Decklink Output:
I actived (Start) the "Output"-Decklink Card "Decklink SDI (1)" first and then the "Preview Output" "Decklink SDI (2)"  - Result: Bove Monitors are showing the Output Signal 👎 
I activated (Start) the "Preview Output" first and then the "Output" - Result: Everything is okay! 👍 

Then I stop the Decklink Output and the Decklink Preview Output OBS Studio crashes every time. No matter which sequence.

### Steps to Reproduce

1. A Decklink Card with 2 outputs is necessary. 
2. Tools -> Decklink Output
3. Start first / Start second -> wrong output on second card (also Output is showen, not the Preview Output)
4. OBS crashes after stopping both outputs
...

### Anything else we should know?

The error also occurs in version 29. 
I haven't tested version 28. 
In version 27 everything was still correct.

**Comment by RytoEX** [comment] 2023-10-12 15:53
> The error also occurs in version 29.

Which version of 29? 29.0.2? 29.1.3?

> I haven't tested version 28.

Please test both 28.0.3 and 28.1.2. It is important for us to know exactly which versions work and which versions do not.

**Comment by frainge** [comment] 2023-10-12 16:30
Hi Ryan, 

Thank you for your work on developing OBS Studio.
I use OBS Studio productively in a German football stadium. Version 27.2.4 works fine there with 2 different computers and different Blackmagic Design Decklink cards. 

At home I tested it with a Decklink Duo card and the newest Blackmagic Studio software/driver (Desktop Video 12.7).

My results:
27.2.4 works fine
28.0.3 works fine
28.1.2 works fine
29.0.2 works fine
**29.1-beta1 first version with errors (same as in my descrition)**
29.1.3 error
30 RC1 error

**Comment by RytoEX** [comment] 2023-10-12 17:47
> My results:
> 27.2.4 works fine
> 28.0.3 works fine
> 28.1.2 works fine
> 29.0.2 works fine
> **29.1-beta1 first version with errors (same as in my description)**
> 29.1.3 error
> 30 RC1 error

Thank you, this is very helpful.

**Comment by RytoEX** [comment] 2023-10-14 05:33
Possibly a duplicate of #8922? The crash stack is the same.

**Comment by frainge** [comment] 2023-10-14 13:19
Only the crashing of OBS Studio after clicking on both Stop-Buttons is the same in both issues.
The freezing **is ony in the Decklink card wich shows the Preview Output**. I haven't noticed that yet. (Test in 29.1.0-beta1)

This problem was not described in issue #8922 :
- The wrong behavior depending on the order in which Output starts first (Main Output first or Preview Output first)
    - Main Output first and then Preview Output: Both Deckling cards show the Main Output simultaneously without freezing
    - Preview Output first and then Main Output:  is correct, **BUT:** freezing in Preview Output!

**Comment by frainge** [comment] 2023-10-14 13:25
I would like to add the following:
The freezing of Preview Output only occurs then you start **both** Outputs. 
Then you only start Preview Output, everything is correct. In this case the program does not crash then you click on Stop.

**Comment by RytoEX** [comment] 2023-10-14 15:37
> Only the crashing of OBS Studio after clicking on both Stop-Buttons is the same in both issues. The freezing **is only in the Decklink card wich shows the Preview Output**. I haven't noticed that yet. (Test in 29.1.0-beta1)

A GitHub Issue should be scoped to one problem. I'd like to focus on the crash mentioned in the title. If #9712 does not fix an additional problem (output freezing), then it should be reported as a new Issue with separate Steps To Reproduce.

**Closed** 2023-10-25 06:11 UTC
