### ISSUE TITLE
Acri theme: sources are unreadable when docked and windowed. UI elements in general feel too small compared to text inside them

### ISSUE THREAD

**Issue by Destroy666x** [obsproject/obs-studio#5120] opened 2021-08-14 07:57 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/d1W85eJTTHKqmkNe

### Expected Behavior

Sources and other UI elements should be readable on all themes.

### Current Behavior

They are far from readable on Acri theme. All other themes seem ok. Resizing anything doesn't help. Examples:

Windows sources:
![image](https://user-images.githubusercontent.com/3606072/129439021-98fc0d55-cf95-4a97-92d8-9c394fa8cfd4.png)
Docked sources (and some other labels also can be seen to be overlapped):
![image](https://user-images.githubusercontent.com/3606072/129439083-d203df6e-1954-40bc-9378-4ecca3529b9a.png)

### Steps to Reproduce

1. Change to Acri theme.
2. Check mentioned UI elements.

Not sure if I enabled anything extra that caused this, I set all settings in one go. 

### Anything else we should know?

Maybe related to https://github.com/obsproject/obs-studio/issues/4058? But I don't think I have any scaling in Windows 10. I checked settings and it was "100%" there. 1920x1080 resolution.

I have a quick question BTW. I see some plugins may be implemented into OBS. How can I check, as an unfamiliar user, which plugins are irrelevent now? It seems to me like some plugins are in OBS but still downloadable on your website without any depreciation warning. E.g. I see "Advanced Scene Switcher" in menu but I don't recall installing that.

**Comment by Warchamp7** [comment] 2021-08-14 20:11
Not an issue I've seen before, and not something I can reproduce either

![image](https://user-images.githubusercontent.com/1554753/129458945-9d60c0d8-383d-4391-bc04-0afa82284012.png)


To your side question, Advanced Scene Switcher is a third party plugin and was never bundled with OBS before. It's something you would have installed yourself manually.

**Comment by Destroy666x** [comment] 2021-08-14 21:17
Actually, I can't reproduce it anymore either 🤔. And I've done almost nothing in OBS today. I basically added one more source to, removed one scene and that's it. All on dark theme. Then I switched back to Acri now to take pic of whole layout but nope, looks normal now. Weird. I'll let you know if I encounter it again.

> To your side question, Advanced Scene Switcher is a third party plugin and was never bundled with OBS before. It's something you would have installed yourself manually.

Thanks. Maybe I installed it a long time ago an deleted the installer accientally (I store all installers). But the general question still stands - how to tell if plugin is not needed anymore? They don't look to be removed from the website as there was one plugin with depreciation notice, presumabl because they work with older version. But what if plugin author didn't update the description?

**Comment by Warchamp7** [comment] 2021-08-15 17:23
> Actually, I can't reproduce it anymore either 🤔. And I've done almost nothing in OBS today. I basically added one more source to a scene, removed one scene and that's it. All on dark theme. Then I switched back to Acri now to take pic of whole layout but nope, looks normal now. Weird, maybe it's related to number of items on lists? I'll let you know if I encounter it again.
> EDIT: oh, I also exported scene collection and profile, but I don't think this would matter for UI.
> 
> > To your side question, Advanced Scene Switcher is a third party plugin and was never bundled with OBS before. It's something you would have installed yourself manually.
> 
> Thanks. Maybe I installed it a long time ago an deleted the installer accientally (I store all installers). But the general question still stands - how to tell if plugin is not needed anymore? They don't look to be removed from the website as there was one plugin with depreciation notice, presumably because they work with older versions. But what if plugin author didn't update the description?

Advanced Scene Switcher is still an available plugin and works fine.

There is no formal uninstall or removal process for plugins currently. You can either reinstall OBS (Without removing your settings) or manually delete the relevant plugin files from your OBS directory.

If you have more questions you can swing by the Discord, I'm gonna close this issue as the main bug here seems to be non reproducible.

**Closed** 2021-08-15 17:31 UTC
