### ISSUE TITLE
Segmentation fault on version 29

### ISSUE THREAD

**Issue by OlegSadJktu** [obsproject/obs-studio#8148] opened 2023-01-25 19:48 UTC
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/hSB4g9prla8ZYPJh

### Expected Behavior

Normal start

### Current Behavior

App crashes when i open it. There is no information in the log

### Steps to Reproduce

1. Launch app

### Anything else we should know?

![image](https://user-images.githubusercontent.com/64313274/214672928-13b607b0-7e02-4378-afc8-b533dcb23337.png)

**Comment by tytan652** [comment] 2023-01-25 19:48
Duplicate of #8056

**Closed by tytan652** 2023-01-25 19:48 UTC
