### ISSUE TITLE
OBS Switches from Full Screen to Windowed

### ISSUE THREAD

**Issue by hoga2443** [obsproject/obs-studio#9599] opened 2023-09-15 19:01 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/QB9DUn3S6krmpAnF

### Expected Behavior

If the OBS user interface is full-screen (Maximized), it should remain full-screen unless the user changes it by clicking on the "Restore" button of the window.

### Current Behavior

When previewing a video media source, OBS is switched from full-screen to windowed (Restore).

### Steps to Reproduce

1.  Open OBS.
2.  Maximize the window.
3.  Select a scene with a video media source.
4.  Initiate playback of the video media source.
5.  The OBS window is switched from "Maximized" to windowed as if I had clicked on the "Restore" button.

### Anything else we should know?

My monitor resolution is 1920x1080.  My base and output resolution are also 1920x1080.

**Comment by RytoEX** [comment] 2023-09-15 23:40
Just a note: fullscreen and maximized are two different concepts. Pressing F11 or selecting "View -> Fullscreen Interface" from the OBS menu bar activate fullscreen mode. Selecting the OBS icon and selecting "Maximize" or pressing the maximize button in the window controls in the upper right maximizes the window size. Which are you using?

**Comment by hoga2443** [comment] 2023-09-16 05:42
I'm using "Maximize" clicking on the maximize button in the window controls in the upper right.  OBS seems to revert from maximized to restored when I select a media source, not just when I start playing the source.  It also does it with audio sources, not just video sources.  Thanks!

**Comment by RytoEX** [comment] 2023-09-18 18:19
I've so far been unable to reproduce this on Windows 11, but it sounds a little like [QTBUG-115699](https://bugreports.qt.io/browse/QTBUG-115699). Maybe something in the source toolbar changing triggers this.

**Comment by hoga2443** [comment] 2023-09-21 19:49
Here is a video of it occurring.  https://drive.google.com/file/d/1sIpt_nEKk78z1QUlxpp-LqRJ5O3-M3Qq/view?usp=sharing

**Comment by Fenrirthviti** [comment] 2023-09-21 19:59
This is being caused by your lower thirds panel changing sizes, which is causing the geometry to update. There's a chance this is fixed by the linked QTBUG, but 6.5.3 has not yet been released, so we'll have to wait to test.

**Comment by RytoEX** [comment] 2023-09-26 17:35
> This is being caused by your lower thirds panel changing sizes, which is causing the geometry to update. There's a chance this is fixed by the linked QTBUG, but 6.5.3 has not yet been released, so we'll have to wait to test.

I agree with this assessment. I'm pretty sure the lower thirds panel is causing the minimum size of the window and thus bringing the window out of maximized state. Should be fixed in Qt 6.5.3, which will hopefully be available soon.

**Closed** 2023-09-29 15:10 UTC
