### ISSUE TITLE
Users unable to change scene names

### ISSUE THREAD

**Issue by rongxin-liu** [obsproject/obs-studio#3330] opened 2020-08-24 22:51 UTC
In the latest version of OBS (or even the previous version), some users can not change the scene names on Mac.
[https://obsproject.com/forum/threads/can-not-rename-scenes-after-they-are-created-obs-24-0-6-mojave-10-14-6-mac.115518/](https://obsproject.com/forum/threads/can-not-rename-scenes-after-they-are-created-obs-24-0-6-mojave-10-14-6-mac.115518/)

## Platform
Operating system and version: macOS Catalina, Version 10.15.6
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior
User should be able to change the scene name

## Current Behavior
User can not change the scene name. For example, when OBS is fresh installed, user can change the default scene name from "Scene" to "A new Scene Name". Then, user is not able to change the scene name. When entered a new name, hit enter, the name stays the same. If the user adds new scene, none of the scenes can be renamed. The only way to "rename" is via duplication and provide a new name there.

## Steps to Reproduce
1. Download and Install OBS
2. Open OBS, skip configuration wizard
3. Change the default scene name, succeed
4. Change the name again, failed
5. Add new scene and change its name, failed
6. Duplicate an arbitrage scene, give it a new name, succeed
7. Try changing the duplicated scene, failed

**Comment by Scrxtchy** [comment] 2020-08-25 07:01
looks like there is a mitigation as posted in [this thread](https://obsproject.com/forum/threads/cant-rename-scenes-objects-mac-10-14-5-obs-23-2-1.109105/) is to use <kbd>Cmd+Return</kbd> or <kbd>Fn+Return</kbd>.
This should provide a short term solution until the bug is found and patched.
OBS might not be checking for a regular <kbd>Return</kbd> press

**Comment by WizardCM** [comment] 2020-08-25 07:09
This is a duplicate of #3044. While this does include a completed issue template (thank you!), a discussion is already ongoing in the other ticket, and any feedback should be added there.

**Closed by WizardCM** 2020-08-25 07:09 UTC
