### ISSUE TITLE
Screen recording source completly white.

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#7939] opened 2022-12-17 22:54 UTC
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/rdeFLKLoLFzCaUgf

### Expected Behavior

Recording succeed completly

### Current Behavior

Recording turned nearly completly white after 1h 25min of recording after switching from directX11 game to different program (steam)

### Steps to Reproduce

1. Play Polda 7 untill you get to JZD
2. Start recording
3. get to lab in  "Vojenský prostor Březina"
4. switch to desktop or other application
5. switch back
6. white screen
...

**Comment by flaeri** [comment] 2023-02-06 22:24
There seems to be an issue with your display capture. This might have been fixed in an update as well, so please make sure you're up to date. If it still happens, please post a log on the latest version.

**Comment by Fenrirthviti** [comment] 2023-03-29 19:29
Cannot reproduce, and we believe this is fixed. No response, closing.

**Closed by Fenrirthviti** 2023-03-29 19:29 UTC
