### ISSUE TITLE
[Application Audio Capture (beta)] Audio starts to be behind the video with time

### ISSUE THREAD

**Issue by Dev1neR** [obsproject/obs-studio#8086] opened 2023-01-18 18:47 UTC
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Bni6ynSYm5OV462f and https://obsproject.com/logs/KEzKxIuduFhSPIcS (for the full sync VOD)

### Expected Behavior

Application audio should be always synced with the video

### Current Behavior

Application audio with time starts to crackle and then it becomes out of sync with the video. Time when it starts to get out of sync is random. It can be 10 minutes, it can be 20, 30 etc.

You can see the examples of how responsive audio is here (already with a timestamp): https://youtu.be/BC4ThC3WOmU?t=48
In the same video here but 14 minutes later, you can hear how audio starts to crackle: https://youtu.be/BC4ThC3WOmU?t=883
And here you can already hear that audio is behind the video: https://youtu.be/BC4ThC3WOmU?t=939, https://youtu.be/BC4ThC3WOmU?t=1004

Same moment, but with synced audio you can see here to compare: https://youtu.be/-yllSyhwzXM?t=110

### Steps to Reproduce

1. Set game/window capture and application audio capture for the application (Browser, game etc)
2. Start recording or streaming for some time (20-30 minutes)
3. Stop the recording or streaming and check for the audio delay to appear on VOD

### Anything else we should know?

I've seen a lot of people encountering this issue on streams or posting about that on OBS forums so that's not the single person issue. Encoder during recording the VODs provided was not overloaded. If I avoid using Application Audio Capture feature and use a normal desktop audio as a way of audio capture, it works just fine and I've never encountered crackling sound and audio drift. Something has to do with this feature specific.

**Comment by RytoEX** [comment] 2023-01-19 17:37
To debug this issue, we would likely need someone on an affected system to perform [these debugging steps](https://github.com/obsproject/obs-studio/pull/5218#issuecomment-1071522440).

**Comment by pandages** [comment] 2023-01-25 21:10
I've encountered this same issue and have samples I can provide if necessary.  I could also get a debug log, if that's still needed.

**Comment by adarhef** [comment] 2023-03-20 21:54
This has been happening consistently for me since 29 on Windows 10 as well. Link to a clip:
[https://www.twitch.tv/addarre/clip/ElegantAgileAppleOhMyDog-OKPciTDv5D8m_7en](url)

**Comment by TawapahDev** [comment] 2023-04-01 14:34
I have also notice this streaming to Twitch.

What would be the best alternative until this has been fixed? Have anyone tried this [plugin](https://github.com/bozbez/win-capture-audio)?

**Comment by RytoEX** [comment] 2023-04-01 22:07
> I have also noticed this streaming to Twitch.
> 
> What would be the best alternative until this has been fixed? Has anyone tried this [plugin](https://github.com/bozbez/win-capture-audio)?

That plugin can encounter the same problem. Both that plugin and our implementation use the same Windows APIs.

**Comment by gxalpha** [comment] 2023-04-05 19:59
Root issue likely to be a duplicate of #8064.

**Closed by gxalpha** 2023-04-05 19:59 UTC
