### ISSUE TITLE
[CRASH] OS X random crashing with EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by paularmstrong** [obsproject/obs-studio#2623] opened 2020-04-03 01:47 UTC
## Platform

Operating system and version: OS X 10.15.3
OBS Studio version: 24.0.6

## Expected Behavior

Does not randomly crash

## Current Behavior

Here are some crash logs:
* [obs_2020-04-02-183748_t.txt](https://github.com/obsproject/obs-studio/files/4424619/obs_2020-04-02-183748_t.txt)
* [obs_2020-04-02-184221_t.txt](https://github.com/obsproject/obs-studio/files/4424621/obs_2020-04-02-184221_t.txt)
* [obs_2020-04-02-183418_t.txt](https://github.com/obsproject/obs-studio/files/4424617/obs_2020-04-02-183418_t.txt)

## Steps to Reproduce
Unsure. It appears to be random, but within 10-15 minutes of starting the application. Does not need to be streaming or recording to happen.

**Comment by PatTheMav** [comment] 2020-04-03 09:30
Might be related to https://github.com/obsproject/obs-studio/issues/2292 as the crash happens during hotkey handling.

**Comment by paularmstrong** [comment] 2020-04-03 15:46
@PatTheMav that may be likely. It did seem to happen often when I used keyboard commands to open windows, new tabs, etc (in other apps) and not the actual hotkeys that are configured for OBS. Oddly, today, there are no issues at all.

**Comment by WizardCM** [comment] 2020-04-04 00:27
Closing as this is a duplicate of #2292

**Closed by WizardCM** 2020-04-04 00:27 UTC

**Comment by paularmstrong** [comment] 2020-04-04 14:27
@WizardCM I think this is different, as it's unrelated to secure entries.

**Comment by paularmstrong** [comment] 2020-04-13 15:41
This is happening when switching apps like with CMD+TAB and even when clicking in some text editors, like iTerm and SublimeText
