### ISSUE TITLE
PPA repo does not work on Ubuntu 24.04

### ISSUE THREAD

**Issue by raivisdejus** [obsproject/obs-studio#10908] opened 2024-06-22 07:34 UTC
### Operating System Info

Other

### Other OS

Ubuntu 24.04

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

-

### OBS Studio Crash Log URL

-

### Expected Behavior

Can install OBS on Ubuntu 24.04

### Current Behavior

```
sudo add-apt-repository ppa:obsproject/obs-studio

...

Err:9 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release' does not have a Release file.

```

### Steps to Reproduce

1. Execute `sudo add-apt-repository ppa:obsproject/obs-studio` on Ubuntu 24.04

**Comment by tytan652** [comment] 2024-06-22 07:37
Duplicate of #10861

**Closed by tytan652** 2024-06-22 07:37 UTC
