### ISSUE TITLE
Video capture device with odd frame-rate super choppy w/o work-around (Hz not in list)

### ISSUE THREAD

**Issue by BOLL7708** [obsproject/obs-studio#5737] opened 2022-01-04 21:05 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/XxMJjNeao9wFlIHO

### Expected Behavior

For me to be able to set a custom frame-rate for a device that is not in the list of pre-defined values.

### Current Behavior

The device output is very choppy when I pick any of the frame-rate options in the source settings for the `Video Capture Device`, the correct one does not appear in the list.

### Steps to Reproduce

1. Have a `Valve Index` connected to your system, or other video device that has a Hz that is not in the list of custom rates.
2. Add the device in `OBS` as a `Video Capture Device`, in my case `eTronVideo` is the device.
3. Change Resolution to what the device supports, in my case `1920x960`
4. Set the frame-rate to anything at all, the frame-rate is in the single digit range.

### Anything else we should know?

I thought this was a USB issue, but even with a new controllers it did not fix it. Then after more experimentation I noticed that if I open the device in the `Camera` application in Windows, it would work fluidly, and when looking closer I saw that it runs the camera at 54 Hz.

If I after having used it in `Camera` then load `OBS` the device will actually work properly, but if I then open the source settings again and fiddle with the frame-rate, it is forever choppy again. I can fix it though, just deactivate it in `OBS` and run `Camera` again and it will be set to the right mode, which means shutting down `Camera` and activating in `OBS` again will have it work there too.

And as noted in steps to reproduce, I'm running a pretty odd video device, in this case the Valve Index VR headset, which has a built in machine learning camera that gives a 2:1 1920x960 image, apparently at 54 Hz, according to [Camera](https://i.imgur.com/JMbfpc3.png), which does not show up in the [list in OBS](https://i.imgur.com/1bnFH2s.png).

**Comment by flaeri** [comment] 2022-01-26 11:59
As per your log, the autodetect quite happily chose the 54fps option that you wanted, multiple times.
```
9:15:32 PM.824: [DShow Device: 'CAM Index Headset'] settings updated: 
9:15:32 PM.824: 	video device: eTronVideo
9:15:32 PM.824: 	video path: \\?\usb#vid_28de&pid_2400&mi_00#7&22dd252d&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
9:15:32 PM.824: 	resolution: 1920x960
9:15:32 PM.824: 	flip: 0
9:15:32 PM.824: 	fps: 54.00 (interval: 185185)
9:15:32 PM.824: 	format: YUY2
```
I would expect when you leave it on auto, it would pick this option (or "highest FPS").
If you let it auto to to 54, are you happy with the stuttering/smoothness?

Regardless, it seems like quite an oddball framerate to explicitly add. At that point one might as well ask for it to be completely user set (you input the value).

I don't think this is very user-friendly however, and I have my doubts the devs would accept such a change.

Hopefully this will fix your issue by letting it auto/highest fps. If it dosent, try enabling "buffer" options in the Video Device Capture settings.

**Comment by BOLL7708** [comment] 2022-01-26 12:52
As I cannot get OBS to use the right frame-rate for it, I'm starting to think the "Highest FPS" is not getting the right value? And using "Device Default" does not fix it, for some reason. 

Maybe it has saved the wrong default Hz in Windows somehow, but then the Camera app gets it right? I have a friend who is using this camera just fine, also on a pre-order Index, but I am guessing he never changed any of the settings, like ever.

In any case, [here](https://youtu.be/k6CSmWJEkE0) is a 5min video show-casing the issue, and the odd work-around. And [this](https://obsproject.com/logs/osJCuoJsiW0wgdw1) is the log for the session in the video. I did the work-around once, so I expect the above happy scenario above to also show up once. 🤔

**Comment by dodgepong** [comment] 2022-01-26 15:56
I have a Valve Index and cannot reproduce with the given reproduction steps. The Index camera source maintains a solid framerate for me regardless of what FPS value is set in OBS video settings or camera settings. It all appears to behave as expected.

**Comment by ALETTERR** [comment] 2022-12-23 14:16
how to set 1024x576

**Comment by RytoEX** [comment] 2023-01-27 19:49
Closing this as we were unable to reproduce this with the specified Steps To Reproduce, and there have been no follow-ups from the OP with new information. If this is still an issue in OBS Studio 29.0.0 (or newer), please comment with updated Steps To Reproduce and a new OBS log.

**Closed by RytoEX** 2023-01-27 19:49 UTC

**Comment by BOLL7708** [comment] 2023-01-27 22:52
Ah whoops, yeah my Index stopped having the camera work at all so perhaps it was a hardware issue, who knows 🤣 Valve were kind enough to send me a replacement Index eventually as the whole headset went kaput, but I haven't even tried to use the camera on the new one since the old one had it act up. In the end it seems more like a liability to have it active as it might cause the USB connection to freak out, so I just don't use it a tall now 😅
