### ISSUE TITLE
Media Source will not play if source transitions are set and hidden after media ends

### ISSUE THREAD

**Issue by edru** [obsproject/obs-studio#4821] opened 2021-06-06 04:57 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/MuZMpCXD2McpYPXx

### Expected Behavior

Media file to play again when retriggered

### Current Behavior

If media file ends and closes, before hidden w/ transition, then it will not open to play again.

### Steps to Reproduce

1. Media Source, local file mp4, Restart playback, Use hardware decoding, show nothing when playing ends, and close file when inactive checked and hide the source.
2. Set a start and end transition for the media file.
3. Unhide source, let media file play, end, and close, then hide source
4. When you now unhide that source, the video file will no longer trigger.
5. If you edit the source, or change scenes and change back, the media source will trigger again, but only once
6. If you hide the media file before it ends and closes, and it allows the transition to occur, the media file will play again no problem, until it closes before the transition can occur.
...

### Anything else we should know?

Yall rock.

**Comment by WizardCM** [comment] 2021-06-06 04:58
This is likely caused by the same bug as #4801

Please try the [latest nightly](https://github.com/obsproject/obs-studio/actions/runs/910739418) to see if it's fixed.

**Comment by edru** [comment] 2021-06-06 05:01
@WizardCM you were correct, that fixed the issue.

**Comment by WizardCM** [comment] 2021-06-06 05:04
Excellent, thank you for verifying. I'll close this for now - if the issue pops up again in a nightly or in 27.0.1 (when it's released), please comment below & I'll reopen the issue.

**Closed by WizardCM** 2021-06-06 05:04 UTC
