### ISSUE TITLE
A window capture shows 1 second later after I switch to a scene contains it

### ISSUE THREAD

**Issue by agoudbg** [obsproject/obs-studio#4877] opened 2021-06-12 02:12 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/F9J0ct49Egk4jyTA

### Expected Behavior

A window capture shows at the moment that I switch to a scene contains it.

### Current Behavior

A window capture shows 1 second later after I switch to a scene contains it.
![a](https://user-images.githubusercontent.com/55237525/121762100-5ea66d00-cb66-11eb-8e1d-e4680f630bfb.png)

### Steps to Reproduce

1. Create a window capture. Any capture method has this issue. 
2. Create another scene. It can contain the window capture that you just created or other sources. The issue will happen whether the scenes you switch from or to.
3. Open studio mode or this issue won't happen.
4. Switch the two scenes. You'll see that the window capture shows about a second after you switch the scenes.

**Comment by WizardCM** [comment] 2021-06-12 02:36
Duplicate of #4801

**Closed by WizardCM** 2021-06-12 02:36 UTC

**Comment by agoudbg** [comment] 2021-06-12 03:04
Now I have updated to 27.0.1 but this still happens.
