### ISSUE TITLE
Macos Frame rendering slowly increases over time

### ISSUE THREAD

**Issue by thomaslfessler** [obsproject/obs-studio#7422] opened 2022-09-21 01:07 UTC
### Operating System Info

macOS 12

### OBS Studio Version

28.0.1

### OBS Studio Version (Other)

also tested in a private build of 27.2

### OBS Studio Log URL

https://obsproject.com/logs/6zP_hmDXfy5euTTn

### Expected Behavior

Frame rendering should remain consistent and should not slowly increase over time.

### Current Behavior

Frame rendering slowly increases over time.    Going from 1.5ms to 6 to 8ms over an hour timeframe.  This issue occurs in OBS built for ARM CPU's on a private build of 27.2 and on 28.0.1

### Steps to Reproduce

in 1920x1080p/60fps scene scene with a elgato camline 4k capture device and virtual camera enabled.   Over the period of an hour, frame rendering starts off at 1.5ms and slowly increases over time reaching 6 to 8ms.    Quitting and restarting the app corrects the issue.  

### Anything else we should know?

This appears to be something 'leaking' in the rendering process that's affecting MacOS rendering performance.  When trying to stream at 1080p/60fps, rendering needs to be at 13ms or lower before framerate starts to suffer, every millisecond counts.

**Comment by jadenquinn** [comment] 2022-09-22 10:02
This is demonstrated here: https://youtu.be/UK9CODMbE_0 (I used the bug creatively)

**Comment by PatTheMav** [comment] 2022-09-22 11:45
Can you try to reproduce this issue without StreamFX and other 3rd party plugins loaded? We need to eliminate other sources influencing the render subsystem first.

Also OpenGL on M1 is implemented in Metal, so some inefficiency is expected, but frame times should stay consistent with consistent scene complexity.

It would also be important to know if you can observe the same behaviour without an external video source (e.g. just using a media source playing back a video) and without Virtual Camera enabled - either of these could introduce the issue, so we need to eliminate them one by one.

**Comment by thomaslfessler** [comment] 2022-09-25 21:42
With an empty scene, rendering starts off at 1.3ms is erratic and over 10+ mins, the high-end can increase to 3.1ms.    I've noticed that the preview window increases rendering time, as does window projectors and virtual camera.   It seems that rendering timeframe in OBS includes the time to render + the time to push the rendered content to the display system.

Perhaps looking at separate values / processes for rendering and displaying the rendering could help to isolate the root cause of the issue.    Realistically speaking, rendering an empty scene should have a consistent rendering load on the OBS system, not something that is jumping around.

Hopefully looking at this from a system perspective helps.

On a side note, have we considered focusing on the media capabilities of the M1 series of chips to accelerate OBS performance?  There is only one Mac left being manufactured with intel CPU's, perhaps it's time to shift focus to the future.

**Comment by Fenrirthviti** [comment] 2022-09-26 01:40
Can you provide the log from that test session?

**Comment by thomaslfessler** [comment] 2022-10-02 02:55
Jumping to the latest version of MacOS and OBS new profile with one empty scene.  
Sharing a session where OBS started up with a 5.3 ms rendering out of the gate. 
https://obsproject.com/logs/MySDxEniUzgvIsDk
After about 5 mins of sitting, rendering dropped to ~2.5ms

Adding a 2nd empty scene.  Switching between essentially 2 empty scenes, renderning pops up to ~7ms.
https://obsproject.com/logs/j2YlQPrPwB1Ajbd2
After about 5 mins of sitting, rendering dropped to ~2.5ms and is never consistent, it's always going up and down.

Taking a look at the GPU...  Utilization increases when switching between the scenes and GPU utilization is never released, it only increases with OBS sitting idle 

<img width="431" alt="drag10-1-2219 52 07" src="https://user-images.githubusercontent.com/4650526/193435786-c2093f7a-68b1-418f-9950-7fa2d5456ec9.png">

**Comment by PatTheMav** [comment] 2022-10-03 18:33
Unfortunately utilisation graphs can be misleading given that CPUs and GPUs constantly change their clock speeds to meet the current processing demands and if you do not correlate the usage with the clock speeds at the moment of measurement, you can't really say if usage went up or down.

This is _especially_ true of the M-series chips which aggressively optimise for power usage. So the issue could be down to our GPU thread running on an efficiency core instead of a performance core, the GPU clocking down, or something else entirely. Alas OBS has not seen any code changes to accommodate the new E-core/P-core situation on modern CPUs (e.g. scheduling threads on the right cores).

You could try to analyse this via a longer trace in Instruments and look at variations in "time spent" on certain calls over time.

**Comment by jadenquinn** [comment] 2022-10-12 15:23
I don't really give a damn what the graphs say, the performance isn't good enough for making a watchable YouTube video, and as that's what a lot of people do with OBS, I can safely say we can't blame the graphics here.

**Comment by jcm93** [comment] 2024-03-27 01:57
This was recently discussed offthread; copying the consensus here. This probably not an issue. Frame render times as well as utilization correspond inversely with clock speeds, per Pat's comment above. None of the posted logs show any dropped frames due to rendering lag; the system will dynamically adjust the GPU clock if it needs to, and you will then see lower render times. If you are dropping frames, you should visit a support channel with a log demonstrating that and go from there.

**Comment by RytoEX** [comment] 2024-03-27 17:36
I tested an approximately 1 hour session on my MacBook that had multiple Media Sources and multiple Video Capture Device sources. For the first 30 minutes, I had only the Virtual Camera output running. Render time started at 6-7ms and rose to 7-8ms over time. Then I started an AOM AV1 recording and render times _dropped_ to 3-5ms and stayed there for the next 30 minutes.

This suggests that this is indeed a hardware clocking effect, so I am going to close this. If someone starts encountering actual render lag (frame render times above the required target time for your selected frame rate) and can provide an OBS log from the affected session _and_ the previously requested trace from Instruments, then we can reconsider this.

**Closed by RytoEX** 2024-03-27 17:36 UTC
