### ISSUE TITLE
Mac audio monitor stays live when source isn't in scene. Mutes on Windows.

### ISSUE THREAD

**Issue by nottooloud** [obsproject/obs-studio#4181] opened 2021-02-03 20:12 UTC
## Platform
Operating system and version: OSX 10.13.6
OBS Studio version: 26.1.2

## Expected Behavior
When an audio source is in the active scene, with Monitor out selected, it should be heard through the monitor.
When I switch to scene that does not include that source, it should not be heard.

## Current Behavior
When I switch to an empty scene on OSX, the source can still be heard.
When I switch to an empty scene on Win 10, the source can not be heard.

## Steps to Reproduce
1. Disable all global inputs
2. Create a scene with an audio input, set to Monitor Only, or Monitor and Output.
3. Create another scene, with no inputs.
4. Switch scenes and listen.

## Additional information

[https://obsproject.com/forum/threads/monitor-audio-is-spilling-over-different-scenes.122239/](url)
[https://obsproject.com/forum/threads/audio-input-source-still-plays-through-even-if-not-in-scene.132181/](url)

**Comment by verstaerker-583** [comment] 2021-02-03 21:52
I can confirm this for at least video and browser sources and found it, like you, to be unexpected in the beginning ... but actually found this to be a feature - for example allowing you to communicate with or to monitor guests not visible and audible in the current scene. I am using this for a director in OBS Ninja being able to speak to the presenter running OBS.

You can always actively mute the source, which would also mute the signal in the monitor - if you feel disturbed.

**Comment by Fenrirthviti** [comment] 2021-02-03 21:58
Certain sources have a checkbox to control if they shutdown when not visible or active, have you checked to see if that is the issue?

Can you be more specific about what exact source you are testing with, any provide a log file? I'm not able to replicate this with sources that are properly being disabled when not visible/active, so I suspect this is just a support issue and not a bug.

**Comment by WizardCM** [comment] 2021-02-03 22:15
My understanding is that if something isn't in the mixer, it shouldn't be heard by monitoring. That's is how it behaves on Windows. What you're describing has been mentioned at least once on the Discord - discovered when we were testing the updated Browser Source (specifically with "Control Audio via OBS" enabled), but was reproduced with a Media Source too.

**Comment by verstaerker-583** [comment] 2021-02-03 22:16
One might have good reasons to not shut down for example browser sources when not visible ... but yes, I don't hear sources properly shut down in the monitor. It is actually a little bit surprising, but in my opinion not a bug, to hear a signal in the monitor which would neither be streamed or recorded.

**Comment by nottooloud** [comment] 2021-02-03 23:14
Source is a simple Audio Input Capture, internal mic or USB interface or audio from a USB cam. No options to disable when not active. USB sources were moved between platforms to test. Either it should mute in OSX, or it shouldn't mute in Win10. One of them is wrong. I vote for changing OSX, since Voicemeeter exists if you want full-time monitoring.

The use case in most of the posts I linked to is Zoom et al, where people are grabbing the Monitor output because they can't access the actual output. So it is streamed *and* recorded. Cut to another scene, such as a video playback, and the mics in the first scene are still hot. Muting sources individually on the fly is not a reasonable option.

If we could use the actual output, this wouldn't be a problem for that application. However, it would still be an inconsistent behavior across platforms.

**Comment by nottooloud** [comment] 2021-02-04 14:34
[https://obsproject.com/forum/threads/audio-monitoring-bug-all-inputs-hot-macos-version-only.138621/](url)

**Comment by MacNut808** [comment] 2021-02-04 20:23
Just chiming in: I believe having all audio inputs hot in the monitor output can be achieved with Voicemeeter, Loopback, or with global audio sources + the audio monitor plugin. Having the audio sources switch in and out appropriately on the audio monitoring output allows an audio feed for Zoom, etc., as it's therefore needed for proper use of the Virtual Camera feature. Most importantly, it allows the OBS operator to monitor the audio as a close approximation of what the audience can hear (since OBS doesn't allow an audio output port that matches the stream/recording audio).

**Comment by PatTheMav** [comment] 2021-02-25 13:11
IMO the current behaviour on macOS is insofar "correct" as it mimics the monitoring behaviour on hardware mixers (where you can monitor sources regardless of fader levels as it's always pre-fader). By that token the current behaviour in Windows is "wrong" but part of OBS' "implicit magic behaviour" on Windows that I'm not much a fan of.. 😅

Alas OBS does currently not have a post-fader/post-mix output that people could use (e.g. for virtual camera usage) so people resort to monitoring output as a crutch. As such I'd much rather see that implemented as a feature and keep monitoring behave like proper monitoring.

PS: Do note that monitoring is pre-effects and pre-mixer, so you'll probably also run into desync issues between audio and virtual camera video.

**Comment by unsoluble** [comment] 2021-04-01 17:58
This behaviour is problematic as-is, as it makes it impossible to keep monitored audio _out_ of specific scenes without compromising other aspects of your scene workflow.

In particular, if you don't want a certain source to be monitored in one scene, the only way to achieve this is to explicitly _add_ that source to the scene and then mute it. But audio sources can't currently be added as `Duplicate`, only `Reference`, so muting the source in that one scene also mutes it in every _other_ scene it's in.

**Comment by noxludo** [comment] 2022-07-15 21:19
Any news on this problem ?

I definitely can't find any workaround… we need the behaviour to be consistent with the Windows version, or at least have another option or feature to handle this the way we need

As @PatTheMav says, it could be nice to have a post-mix feature, but maybe we could already fix this inconsistent behaviour before developing any new feature ?

**Comment by WizardCM** [comment] 2022-07-26 11:30
Fixed by #6808 merged yesterday.

**Closed by WizardCM** 2022-07-26 11:30 UTC
Labels: macOS, Confirmed
