### ISSUE TITLE
Screen Capture (PipeWire) always black

### ISSUE THREAD

**Issue by holzdieb** [obsproject/obs-studio#11107] opened 2024-08-10 07:17 UTC
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/Ag4QGsgDp5gHdv3g

### Expected Behavior

Scene created
Screen capture selected
Game selected under Properties

### Current Behavior

When I try to record a game, select Screen Capture (PipeWire) under Sources, then select the game to be recorded, the scene remains black. I cannot see the game in OBS.

### Steps to Reproduce

1. Create Screen
2. Select Screen Capture in Sources
3. Select Game in Screen Capture Properties
...

**Comment by tytan652** [comment] 2024-08-10 07:18
Duplicate of #10409

**Closed by tytan652** 2024-08-10 07:18 UTC
