### ISSUE TITLE
Default sound output device change detection

### ISSUE THREAD

**Issue by xklonx** [obsproject/obs-studio#2316] opened 2020-01-13 19:17 UTC
I turn on the broadcast, while the sound is output in the speakers (the default device), they are selected as the sound source and everything is fine. Now I connect bluetooth headphones, windows changes the default device to them and the sound starts to be output in them, while the default device is selected in obs, but obs loses sound. Moreover, if you go into the properties of the playback device, the default device is selected there and if you just click ok, then the sound starts to pick up correctly again.

## Expected Behavior
Obs must correctly detect the default device change.

https://obsproject.com/mantis/view.php?id=1069

**Comment by Fenrirthviti** [comment] 2020-04-26 04:18
This is confirmed, and there is probably an argument for keeping it the same as it is now, as much as changing it. Changing the selected device while OBS is active (especially in automated scenarios like you mentioned) could be disruptive while streaming or recording is active. I'm not sure what the best way to handle it would be.

**Comment by xklonx** [comment] 2020-04-26 21:00
This is an example of default device change handling https://stackoverflow.com/questions/6163119/handling-changed-audio-device-event-in-c-sharp i checked and it works. I think that this is not an option to force the user to manually change the device, since it even looks like an error, you didnt even change something, just hit save and it starts working. If the obs will change the device automatically, it will not be more disruptive than if the user does it manually.

**Comment by Fenrirthviti** [comment] 2020-04-26 23:07
I think this is less about how to do it, and more about if we should do it. You're right it's not more disruptive than a user changing it manually, but Windows likes to automatically change the default devices all the time (like if you plug a USB device that has a microphone or desktop audio device as part if it, Windows will "helpfully" switch your default to that), which might result in confusion and frustration for users. I'm all in favor of allowing this option, but we need some kind of feedback for when it happens.

**Comment by mkrupczak3** [comment] 2020-07-24 20:10
Bump.

I have a very annoying issue related here where my microphone is somehow picked up by default instead of the desktop audio, when my microphone is normally push to talk. 

The first time I start streaming with OBS after I switch profiles, I have to change the audio device from default to something else, then back to default to work around this bug. 

After this, it (correctly) doesn't pick up my mic and does pick up desktop audio. 

I think I accidentally read out my social security number on my last twitch stream, lol. 

Pleas fix this, thanks!

Ubuntu Server 18.04 LTS Bionic Beaver
OBS 25.0.8 64 bit

**Comment by mkrupczak3** [comment] 2020-07-24 20:15
Video of bug:
https://www.twitch.tv/videos/688793653

**Comment by Fenrirthviti** [comment] 2020-07-24 20:22
That bug does not sound related to this, which is specifically about following the default audio device on Windows.

I would recommend using the Discord for support to take a closer look.

**Comment by mkrupczak3** [comment] 2020-07-24 21:10
Big oof. 

I guess I'll try and hop on over there to let them know

**Comment by kinsi55** [comment] 2020-10-27 20:11
Would love to see this implemented. When starting SteamVR it will automatically switch the default recording device to the one of the HMD (And back when exiting it again). Having OBS pick up on that without manually needing to trigger it would be a great QOL improvement.

**Comment by Fenrirthviti** [comment] 2020-10-27 20:14
Also, just to document the discussion that happened in Discord regarding this issue, we agree that this should be changed. Current target is looking at this for v27, per the milestone.

**Comment by PatTheMav** [comment] 2020-12-31 16:20
Wouldn't the simplest fix be to remove the "default" audio device in OBS and make device selection explicit? Explicit is always better than implicit imo.

**Comment by energizerfellow** [comment] 2020-12-31 17:07
The other wrinkle here is that Windows has two different concepts of "default" on both input and output. The Default Device and the Default **_Communications_** Device.

The added bonus here is that many modern devices seem to (correctly) flag themselves as either a communication (e.g. headset) or non-communication (e.g. capture card) audio source, yet OBS is (currently) only written to handle the Default Communication Device. This is made even worse UI/UX-wise as OBS's UI calls it Default, which using Communications Default on the back-end.

You know what makes it even worse? Windows 10's current audio settings panel is limited/bugged in such a way that the UI only sets the and indicates the non-Communications Default. The UI has concept of a Communications Default. You need to pull up the legacy Sound control panel to see or set the Communications Default. This is discussed in #3898.

The only real workable fix I see is to add separate Default Device and Default Communications Device, both with real-time hotplug change following. To be consistent with Windows itself, the labels in OBS should be exactly "Default Device" and "Default Communications Device".

To make the end-user experience much clearer, I strongly recommend adding the name of the device to the OBS UI, which would mean "Default Device ([device_name])" and "Default Communications Device ([device_name])". Every teleconferencing client worth mentioning does this for a reason.

I get wanting to keep the audio device selection static, I really do, but the reality is that Windows following audio device hotplug for Default changing has ben a thing since at least XP and very much expected by end-users.

**Comment by dodgepong** [comment] 2020-12-31 17:14
> Wouldn't the simplest fix be to remove the "default" audio device in OBS and make device selection explicit? Explicit is always better than implicit imo.

I disagree here, because in the case of things like USB headphones/microphones, many users _want_ the OBS to follow whatever the default device is when it changes, without any user intervention.

**Comment by PatTheMav** [comment] 2020-12-31 17:18
Fair enough, that's a very Windows thing then. The peculiarities with communication devices as outlined by @energizerfellow I noticed as well, it's a mess even without OBS in the mix (e.g. USB devices becoming the default audio device during a GPU driver update when HDMI output was the default otherwise).

**Comment by Fenrirthviti** [comment] 2020-12-31 18:32
I can also confirm it's a learned behavior on Windows that would be detrimental for us to move away from. When we get a proper user feedback system in place, this is a good candidate to send a notification for on device change.

**Comment by jp9000** [comment] 2021-02-06 20:15
Fixed https://github.com/obsproject/obs-studio/commit/74e64481951e9247a7dec0af6d3660027dd57fb4 and https://github.com/obsproject/obs-studio/commit/6cf22c54dc843b0a17b4cb399afc7b52fba0b63d

**Comment by mkrupczak3** [comment] 2021-02-06 21:54
Holy crap, jp ur my hero

I was having an issue with incorrect device detection on Linux (I would have to change the device to something else, then back to default to get it to recognize the first device), it would be a miracle if this fixed it?

What version release number will this be implemented in?

**Comment by Fenrirthviti** [comment] 2021-02-06 22:45
The recent commits only affect Windows audio capture, not Linux. This will be available in the Windows release of v27.

**Comment by mkrupczak3** [comment] 2021-02-07 07:01
Big oof

I reported the issue on Linux anyways, but I think that thread eventually got deleted...

**Comment by jp9000** [comment] 2021-02-07 08:24
Oh woops. Well I'll reopen it for now.

**Comment by paullyvenne** [comment] 2021-02-27 17:46
> This is confirmed, and there is probably an argument for keeping it the same as it is now, as much as changing it. Changing the selected device while OBS is active (especially in automated scenarios like you mentioned) could be disruptive while streaming or recording is active. I'm not sure what the best way to handle it would be.

I would disagree, if you change the default device with Windows 10, OBS should change with you. I've streamed so many times and OBS ignored my device change. The argument against it doesn't make much sense  because they wouldn't choose DEFAULT device in the first place if they were worried about devices changing on them. Why not just fix it so it changed to the DEFAULT device in real time.

**Comment by paullyvenne** [comment] 2021-02-27 17:49
> I think this is less about how to do it, and more about if we should do it. You're right it's not more disruptive than a user changing it manually, but Windows likes to automatically change the default devices all the time (like if you plug a USB device that has a microphone or desktop audio device as part if it, Windows will "helpfully" switch your default to that), which might result in confusion and frustration for users. I'm all in favor of allowing this option, but we need some kind of feedback for when it happens.

Then they wouldn't set the audio device to DEFAULT, they would set it to the device they'd want to be the primary, and how rarely does someone plug in new audio devices during a stream, but they will change from speaker to headphones often while OBS has started.

**Comment by Fenrirthviti** [comment] 2021-02-27 18:58
We already implemented this on Windows, so we don't need any further incentive. Thank you for the comments though!

This issue is still open because it has not been implemented on Linux yet.

**Comment by paullyvenne** [comment] 2021-02-27 20:42
> We already implemented this on Windows, so we don't need any further incentive. Thank you for the comments though!
> This issue is still open because it has not been implemented on Linux yet.

It's still happening in version 26.1.1 perhaps I'm not familiar with your release management, how do I get it with the fixed version... 27.0 isn't available, correct?

**Comment by Fenrirthviti** [comment] 2021-02-27 21:08
Correct, this will be in v27 as mentioned a few comments up, which hasn't been released yet. You can either build yourself against current master, or grab one of our nightly builds from CI.  Keep in mind those builds will not be signed, so you might run in to issues with game capture being blocked (or overly aggressive antivirus blocking functionality).

**Comment by RytoEX** [comment] 2022-09-22 20:09
As the original Mantis Issue was about WASAPI (Windows-only), and this Issue was a mirror to that Mantis Issue, and we have fixed the Windows case, we're going to close this as fixed. If there is a similar Linux issue with sound devices regarding changing default sound devices, please file a new Issue with detailed steps to reproduce.

**Closed by RytoEX** 2022-09-22 20:09 UTC
Labels: Linux, Mantis Duplicate, Confirmed
