### ISSUE TITLE
Linux - Segfault on Launch in QScreen

### ISSUE THREAD

**Issue by 14ercooper** [obsproject/obs-studio#10936] opened 2024-07-01 10:35 UTC
### Operating System Info

Other

### Other OS

Pop!_OS 22.04 LTS

### OBS Studio Version

30.1.2

### OBS Studio Log URL

(cannot launch OBS to upload)

### OBS Studio Crash Log URL

No crash log file generated

### Expected Behavior

OBS launches without crashing

### Current Behavior

OBS crashes before I can even get into OBS. Log file prior to the segmentation fault below:

```04:27:48.587: [Safe Mode] Unclean shutdown detected!
04:27:51.617: [Safe Mode] User elected to launch normally.
04:27:51.618: Using EGL/X11
04:27:51.618: CPU Name: AMD Ryzen 5 7640HS w/ Radeon 760M Graphics
04:27:51.618: CPU Speed: 2403.566MHz
04:27:51.619: Physical Cores: 6, Logical Cores: 12
04:27:51.619: Physical Memory: 15168MB Total, 1668MB Free
04:27:51.619: Kernel Version: Linux 6.9.3-76060903-generic
04:27:51.619: Distribution: "Pop!_OS" "22.04"
04:27:51.619: Desktop Environment: pop:GNOME (pop)
04:27:51.619: Session Type: x11
04:27:51.619: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
04:27:51.619: Qt Version: 6.2.4 (runtime), 6.2.4 (compiled)
04:27:51.620: Portable mode: false
04:27:51.637: OBS 30.1.2 (linux)
04:27:51.637: ---------------------------------
04:27:51.637: ---------------------------------
04:27:51.637: audio settings reset:
04:27:51.637: 	samples per sec: 48000
04:27:51.637: 	speakers:        2
04:27:51.637: 	max buffering:   960 milliseconds
04:27:51.637: 	buffering type:  dynamically increasing
04:27:51.655: ---------------------------------
04:27:51.655: Initializing OpenGL...
04:27:51.809: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
04:27:51.809: OpenGL loaded successfully, version 3.3.0 NVIDIA 550.67, shading language 3.30 NVIDIA via Cg compiler
04:27:51.834: ---------------------------------
04:27:51.834: video settings reset:
04:27:51.834: 	base resolution:   2560x1440
04:27:51.834: 	output resolution: 2560x1440
04:27:51.834: 	downscale filter:  Bicubic
04:27:51.834: 	fps:               60/1
04:27:51.834: 	format:            NV12
04:27:51.834: 	YUV mode:          Rec. 709/Partial
04:27:51.834: NV12 texture support enabled
04:27:51.834: P010 texture support not available
04:27:51.862: Audio monitoring device:
04:27:51.862: 	name: 既定
04:27:51.862: 	id: default
04:27:51.862: ---------------------------------
04:27:51.892: No AJA devices found, skipping loading AJA UI plugin
04:27:51.892: Failed to initialize module 'aja-output-ui.so'
04:27:51.919: No AJA devices found, skipping loading AJA plugin
04:27:51.919: Failed to initialize module 'aja.so'
04:27:51.940: Failed to load 'en-US' text for module: 'decklink-captions.so'
04:27:51.960: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
04:27:51.980: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
04:27:51.980: Failed to initialize module 'decklink.so'
04:27:52.518: [pipewire] Available captures:
04:27:52.518: [pipewire]     - Desktop capture
04:27:52.518: [pipewire]     - Window capture
04:27:52.577: [obs-browser]: Version 2.23.4
04:27:52.577: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
04:27:52.690: NVENC supported
04:27:52.797: VAAPI: API version 1.14
04:27:52.800: FFmpeg VAAPI H264 encoding supported
04:27:52.800: FFmpeg VAAPI AV1 encoding not supported
04:27:52.809: FFmpeg VAAPI HEVC encoding supported
04:27:52.981: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.4.2 | RPC Version: 1)
04:27:52.981: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.2.4 | Qt version (run-time): 6.2.4
04:27:52.981: [obs-websocket] [obs_module_load] Linked ASIO Version: 101801
04:27:52.986: [obs-websocket] [obs_module_load] Module loaded.
04:27:53.108: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
04:27:53.108: ---------------------------------
04:27:53.108:   Loaded Modules:
04:27:53.108:     vlc-video.so
04:27:53.108:     text-freetype2.so
04:27:53.108:     rtmp-services.so
04:27:53.108:     obs-x264.so
04:27:53.108:     obs-websocket.so
04:27:53.108:     obs-vst.so
04:27:53.108:     obs-transitions.so
04:27:53.108:     obs-qsv11.so
04:27:53.108:     obs-outputs.so
04:27:53.108:     obs-libfdk.so
04:27:53.108:     obs-filters.so
04:27:53.108:     obs-ffmpeg.so
04:27:53.108:     obs-browser.so
04:27:53.108:     linux-v4l2.so
04:27:53.108:     linux-pulseaudio.so
04:27:53.108:     linux-pipewire.so
04:27:53.108:     linux-jack.so
04:27:53.108:     linux-capture.so
04:27:53.108:     linux-alsa.so
04:27:53.108:     image-source.so
04:27:53.108:     frontend-tools.so
04:27:53.108:     decklink-output-ui.so
04:27:53.108:     decklink-captions.so
04:27:53.109: ---------------------------------
04:27:53.109: QWidget::setTabOrder: 'first' and 'second' must be in the same window
04:27:53.109: ==== Startup complete ===============================================
04:27:53.131: All scene data cleared
04:27:53.131: ------------------------------------------------
04:27:53.135: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.3) 15.0.0'
04:27:53.135: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
04:27:53.135: pulse-input: Started recording from 'alsa_output.pci-0000_05_00.6.analog-stereo.monitor' (default)
04:27:53.136: [Loaded global audio device]: 'デスクトップ音声'
04:27:53.136: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.3) 15.0.0'
04:27:53.136: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
04:27:53.136: pulse-input: Started recording from 'alsa_input.usb-Generic_Blue_Microphones_LT_220514162012AD0200D4_111000-00.iec958-stereo' (default)
04:27:53.136: [Loaded global audio device]: 'マイク'
04:27:53.136: v4l2-input: Start capture from /dev/video2
04:27:53.152: v4l2-input: Input: 0
04:27:53.154: v4l2-input: Resolution: 1920x1080
04:27:53.154: v4l2-input: Pixelformat: YUYV
04:27:53.154: v4l2-input: Linesize: 3840 Bytes
04:27:53.154: v4l2-input: Framerate: 60.00 fps
04:27:53.157: v4l2-input: /dev/video2: select timeout set to 83333 (5x frame periods)
04:27:53.157: Switched to scene 'Main Scene'
04:27:53.157: ------------------------------------------------
04:27:53.157: Loaded scenes:
04:27:53.157: - scene 'Main Scene':
04:27:53.157:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
04:27:53.157: ------------------------------------------------
04:27:53.246: YT: InitYTUserUrl() User is not signed
04:27:53.259: YT: InitYTUserUrl() User is not signed
04:27:53.289: v4l2-input: /dev/video2: select timed out
04:27:53.289: v4l2-input: /dev/video2: failed to log status```

### Steps to Reproduce

1. Launch OBS, do anything
2. Close and then attempt to re-open OBS

If I delete/rename my configuration files to simulate a "clean install", I can launch OBS exactly one time, and then subsequent launches segfault before I can even interact with the UI. It does not seem to matter what I configure, if anything, since the config files existing seems to already be enough to cause OBS to crash.

### Anything else we should know?

I attempted to track down how to install debugger symbols, but couldn't locate them, and also couldn't get OBS to build in debug mode on my machine to test. If you point me in the direction of the debugger symbols file, I can rerun with those symbols. I have included the logs from running OBS under gdb, as well as the backtrace of the crash. This appears to be new behavior within the last week or so - possibly a third party library updated?

```(gdb) run
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea000640 (LWP 46564)]
[New Thread 0x7fffe8c00640 (LWP 46565)]
[New Thread 0x7fffe3e00640 (LWP 46566)]
[New Thread 0x7fffe3400640 (LWP 46567)]
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/themes
debug: Attempted path: /usr/share/obs/obs-studio/themes
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
warning: [Safe Mode] Unclean shutdown detected!
warning: [Safe Mode] User elected to launch normally.
info: Using EGL/X11
info: CPU Name: AMD Ryzen 5 7640HS w/ Radeon 760M Graphics
info: CPU Speed: 2403.566MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 15168MB Total, 1668MB Free
info: Kernel Version: Linux 6.9.3-76060903-generic
info: Distribution: "Pop!_OS" "22.04"
info: Desktop Environment: pop:GNOME (pop)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffe1600640 (LWP 46572)]
[New Thread 0x7fffe0c00640 (LWP 46573)]
info: Qt Version: 6.2.4 (runtime), 6.2.4 (compiled)
info: Portable mode: false
info: OBS 30.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffd5e00640 (LWP 46574)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 550.67, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   2560x1440
	output resolution: 2560x1440
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffcd200640 (LWP 46576)]
info: NV12 texture support enabled
info: P010 texture support not available
[New Thread 0x7fffbbe00640 (LWP 46577)]
info: Audio monitoring device:
	name: 既定
	id: default
info: ---------------------------------
[Detaching after fork from child process 46579]
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
[Detaching after fork from child process 46580]
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
[Detaching after fork from child process 46581]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 46582]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 46583]
libDeckLinkAPI.so: 共有オブジェクトファイルを開けません: そのようなファイルやディレクトリはありません
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 46584]
[New Thread 0x7fffc6000640 (LWP 46585)]
[Detaching after fork from child process 46586]
[Detaching after fork from child process 46587]
[Detaching after fork from child process 46589]
[Detaching after fork from child process 46590]
[Detaching after fork from child process 46591]
[Detaching after fork from child process 46592]
[Detaching after fork from child process 46593]
[Detaching after fork from child process 46594]
[Detaching after fork from child process 46595]
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
[Detaching after fork from child process 46596]
[Detaching after fork from child process 46597]
[Detaching after vfork from child process 46599]
[Detaching after fork from child process 46601]
info: [obs-browser]: Version 2.23.4
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
[Detaching after fork from child process 46602]
info: NVENC supported
[New Thread 0x7fffadc00640 (LWP 46603)]
[New Thread 0x7fffad200640 (LWP 46604)]
[New Thread 0x7fff94c00640 (LWP 46605)]
[New Thread 0x7fff8fe00640 (LWP 46606)]
[New Thread 0x7fff8f400640 (LWP 46607)]
[New Thread 0x7fff8ea00640 (LWP 46608)]
[New Thread 0x7fff8e000640 (LWP 46609)]
[New Thread 0x7fff8d600640 (LWP 46610)]
[New Thread 0x7fff8cc00640 (LWP 46611)]
[New Thread 0x7fff83e00640 (LWP 46612)]
[New Thread 0x7fff83400640 (LWP 46613)]
info: VAAPI: API version 1.14
[Thread 0x7fff8e000640 (LWP 46609) exited]
[Thread 0x7fff83400640 (LWP 46613) exited]
[Thread 0x7fff83e00640 (LWP 46612) exited]
[Thread 0x7fff8cc00640 (LWP 46611) exited]
[Thread 0x7fff8d600640 (LWP 46610) exited]
[Thread 0x7fff8fe00640 (LWP 46606) exited]
[Thread 0x7fff94c00640 (LWP 46605) exited]
[Thread 0x7fff8f400640 (LWP 46607) exited]
[Thread 0x7fff8ea00640 (LWP 46608) exited]
[Thread 0x7fffad200640 (LWP 46604) exited]
[Thread 0x7fffadc00640 (LWP 46603) exited]
info: FFmpeg VAAPI H264 encoding supported
info: FFmpeg VAAPI AV1 encoding not supported
[New Thread 0x7fffadc00640 (LWP 46614)]
[New Thread 0x7fffad200640 (LWP 46615)]
[New Thread 0x7fff8ea00640 (LWP 46616)]
[New Thread 0x7fff8f400640 (LWP 46617)]
[New Thread 0x7fff94c00640 (LWP 46618)]
[New Thread 0x7fff8fe00640 (LWP 46619)]
[New Thread 0x7fff8e000640 (LWP 46620)]
[New Thread 0x7fff8d600640 (LWP 46621)]
[New Thread 0x7fff8cc00640 (LWP 46622)]
[New Thread 0x7fff83e00640 (LWP 46623)]
[New Thread 0x7fff83400640 (LWP 46624)]
[Thread 0x7fff8e000640 (LWP 46620) exited]
[Thread 0x7fff83400640 (LWP 46624) exited]
[Thread 0x7fff83e00640 (LWP 46623) exited]
[Thread 0x7fff8cc00640 (LWP 46622) exited]
[Thread 0x7fff8d600640 (LWP 46621) exited]
[Thread 0x7fff8ea00640 (LWP 46616) exited]
[Thread 0x7fff8f400640 (LWP 46617) exited]
[Thread 0x7fff94c00640 (LWP 46618) exited]
[Thread 0x7fff8fe00640 (LWP 46619) exited]
[Thread 0x7fffad200640 (LWP 46615) exited]
[Thread 0x7fffadc00640 (LWP 46614) exited]
info: FFmpeg VAAPI HEVC encoding supported
[Detaching after fork from child process 46625]
[Detaching after fork from child process 46626]
[Detaching after fork from child process 46627]
[Detaching after fork from child process 46628]
[New Thread 0x7fffadc00640 (LWP 46629)]
[New Thread 0x7fffad200640 (LWP 46630)]
[New Thread 0x7fff8fe00640 (LWP 46631)]
[New Thread 0x7fff94c00640 (LWP 46632)]
[New Thread 0x7fff8f400640 (LWP 46633)]
[New Thread 0x7fff8ea00640 (LWP 46634)]
[New Thread 0x7fff8e000640 (LWP 46635)]
[New Thread 0x7fff8d600640 (LWP 46636)]
[New Thread 0x7fff8cc00640 (LWP 46637)]
[New Thread 0x7fff83e00640 (LWP 46638)]
[Thread 0x7fff8e000640 (LWP 46635) exited]
[Thread 0x7fff83e00640 (LWP 46638) exited]
[Thread 0x7fff8cc00640 (LWP 46637) exited]
[Thread 0x7fff8d600640 (LWP 46636) exited]
[Thread 0x7fff8fe00640 (LWP 46631) exited]
[Thread 0x7fff94c00640 (LWP 46632) exited]
[Thread 0x7fff8f400640 (LWP 46633) exited]
[Thread 0x7fff8ea00640 (LWP 46634) exited]
[Thread 0x7fffad200640 (LWP 46630) exited]
[Thread 0x7fffadc00640 (LWP 46629) exited]
[Detaching after fork from child process 46639]
[Detaching after fork from child process 46640]
[Detaching after fork from child process 46641]
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.4.2 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.2.4 | Qt version (run-time): 6.2.4
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101801
info: [obs-websocket] [obs_module_load] Module loaded.
[Detaching after fork from child process 46642]
[Detaching after fork from child process 46643]
[New Thread 0x7fffadc00640 (LWP 46644)]
[New Thread 0x7fffad200640 (LWP 46645)]
[Detaching after fork from child process 46646]
[Detaching after fork from child process 46647]
info: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-qsv11.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
warning: QWidget::setTabOrder: 'first' and 'second' must be in the same window
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
[New Thread 0x7fff8ea00640 (LWP 46648)]
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.3) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_05_00.6.analog-stereo.monitor' (default)
info: [Loaded global audio device]: 'デスクトップ音声'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.3) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.usb-Generic_Blue_Microphones_LT_220514162012AD0200D4_111000-00.iec958-stereo' (default)
info: [Loaded global audio device]: 'マイク'
info: v4l2-input: Start capture from /dev/video2
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 1920x1080
info: v4l2-input: Pixelformat: YUYV
info: v4l2-input: Linesize: 3840 Bytes
info: v4l2-input: Framerate: 60.00 fps
[New Thread 0x7fff8f400640 (LWP 46649)]
info: v4l2-input: /dev/video2: select timeout set to 83333 (5x frame periods)
[New Thread 0x7fff94a00640 (LWP 46650)]
info: Switched to scene 'Main Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Main Scene':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: ------------------------------------------------
[New Thread 0x7fff8fe00640 (LWP 46652)]
[New Thread 0x7fff8e000640 (LWP 46653)]
[New Thread 0x7fff77e00640 (LWP 46654)]
[Detaching after fork from child process 46655]
[Detaching after fork from child process 46657]
[New Thread 0x7fff77200640 (LWP 46658)]
[New Thread 0x7fff76800640 (LWP 46659)]
[New Thread 0x7fff75e00640 (LWP 46660)]
[New Thread 0x7fff75400640 (LWP 46661)]
[New Thread 0x7fff74a00640 (LWP 46662)]
[New Thread 0x7fff6be00640 (LWP 46663)]
[New Thread 0x7fff6b400640 (LWP 46664)]
[Thread 0x7fffad200640 (LWP 46645) exited]
[New Thread 0x7fffad200640 (LWP 46666)]
[New Thread 0x7fff6a000640 (LWP 46668)]
[New Thread 0x7fff6aa00640 (LWP 46667)]
[New Thread 0x7fff69600640 (LWP 46669)]
[New Thread 0x7fff68c00640 (LWP 46670)]
[New Thread 0x7fff5fe00640 (LWP 46672)]
[New Thread 0x7fff5f400640 (LWP 46674)]
[Thread 0x7fff8e000640 (LWP 46653) exited]
error: YT: InitYTUserUrl() User is not signed
error: YT: InitYTUserUrl() User is not signed
[Detaching after fork from child process 46680]
error: v4l2-input: /dev/video2: select timed out
error: v4l2-input: /dev/video2: failed to log status
[New Thread 0x7fff8e000640 (LWP 46681)]
[New Thread 0x7fff5ea00640 (LWP 46691)]

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c01cd4 in QScreen::geometry() const () from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
(gdb) bt
#0  0x00007ffff4c01cd4 in QScreen::geometry() const ()
    at /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6
#1  0x00007ffff56e5bfa in  () at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#2  0x00007ffff56ef820 in  () at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#3  0x00007ffff56ef9d8 in  () at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#4  0x00007ffff572bdb5 in  () at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#5  0x00007ffff572c00c in  () at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#6  0x00007ffff571e5d9 in QMainWindow::restoreState(QByteArray const&, int) ()
    at /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6
#7  0x00005555556c0517 in  ()
#8  0x000055555561aec8 in main ()
```

**Comment by kkartaltepe** [comment] 2024-07-01 14:47
duplicate of #9907

**Closed by kkartaltepe** 2024-07-01 14:47 UTC
