### ISSUE TITLE
Window Capture shows most windows as the following format: [app_name](null)

### ISSUE THREAD

**Issue by bearcatjamboree** [obsproject/obs-studio#6036] opened 2022-02-26 01:12 UTC
### Operating System Info

Other

### Other OS

MacOS 12.2.1

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0-36-gda800ae24 (64 bit)

### OBS Studio Log URL

https://obsproject.com/logs/D26M2sfQILNq2moT

### Expected Behavior

When trying to add Window Capture for an application, the list of Windows should have names like:
 [java] Lunar Client (#####)

### Current Behavior

When trying to add Window Capture for an application, window names that have the format:
[app_name] (null)

### Steps to Reproduce

1. Open OBS Studio
2. Click add Window Capture
3. Select Window drop to display list of windows found by OBS Studio
...

### Anything else we should know?

I just decided to test the universal build because Window Capture is a little laggy with the Intel build running on Rosetta 2.  If I entered anything in the wrong format then please let me know...

**Comment by gxalpha** [comment] 2022-02-26 01:19
Does this happen with an official build as well?

**Comment by bearcatjamboree** [comment] 2022-02-26 02:32
I haven't encountered this on the official build.

**Comment by gxalpha** [comment] 2022-02-26 08:38
Could you send a screenshot of the available window names (with the dropdown open)?
However, keep in mind we don't support any unofficial builds (and additionally, I suspect this to be a support issue and not a bug)

**Comment by cboxgo69** [comment] 2022-03-01 18:24
Thanks for replying.  I only has a few days to test and has to switch back to the production version, so I no longer have the test release installed.  I can try again in the future but I’m not sure when that will be

**Comment by gxalpha** [comment] 2022-03-01 18:26
I suppose the issue can get closed then for now.

**Comment by Fenrirthviti** [comment] 2022-03-01 18:32
Closing per above.

**Closed by Fenrirthviti** 2022-03-01 18:32 UTC
Labels: macOS
