### ISSUE TITLE
OBS Studio crashes after trying to add a browser source on MAC

### ISSUE THREAD

**Issue by ImmortalRey** [obsproject/obs-studio#3918] opened 2020-12-17 11:53 UTC
## Platform

Operating system and version:
OBS Studio version:

## Expected Behavior
 OBS Studio crashes EVERYTIME I try and add a browser source

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment] 2020-12-17 11:54
Duplicate of #3095

**Closed by WizardCM** 2020-12-17 11:54 UTC
