### ISSUE TITLE
Virtual camera does not work with PotPlayer

### ISSUE THREAD

**Issue by xmcp** [obsproject/obs-studio#7461] opened 2022-09-25 09:22 UTC
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/NxA4fLyhzdLz2UaH

### Expected Behavior

Should be able to watch the OBS output in PotPlayer since it supports opening a WebCam video source

### Current Behavior

Output is not shown in PotPlayer (the video becomes transparent)

### Steps to Reproduce

1. Download and install PotPlayer at https://potplayer.daum.net/
2. Open OBS Studio, add a color source, and click on Start Virtual Camera
3. Open PotPlayer, right-click, and select "Open > Device settings..."
4. Select "OBS Virtual Camera" in the "Video capture device", and click on "Open device"

![image](https://user-images.githubusercontent.com/6646473/192136445-3c41d9d8-97cb-4dea-82e4-338472247a36.png)

![image](https://user-images.githubusercontent.com/6646473/192136474-9d7aea0d-c157-4f4b-90ba-880f7fa05aa7.png)

### Anything else we should know?

Since it is a compatibility issue, I am not sure whether the problem is in OBS or in PotPlayer.

Here are some findings:

- The OBS built-in virtual camera works well with other applications like Chrome
- PotPlayer works well with my real WebCam and the [OBS Virtualcam](https://obsproject.com/forum/resources/obs-virtualcam.949/) plugin in OBS 27
- The built-in virtual camera in OBS 27 does not work with PotPlayer (so it is not a regression)

I am willing to provide more diagnosis if needed.

**Comment by xmcp** [comment] 2022-09-25 11:31
Below is the OBS Virtualcam plugin on OBS 27, which works fine: (the "played/dropped frames" number keeps  growing)
![image](https://user-images.githubusercontent.com/6646473/192141054-21928089-a4b6-4c9e-b5d8-64b3e58eb005.png)

Below is the built-in virtual camera in OBS 27, with parameters set to the same as OBS Virtualcam (YUY2 720p60), which also doesn't work like in latest OBS 28.0.2: (the "played/dropped frames" always says 0)
![image](https://user-images.githubusercontent.com/6646473/192141069-050217cf-20d5-4a17-8057-a34617d30aec.png)

Note that sometimes only the first frame is correctly rendered but the video does not update for the built-in virtual camera.

**Comment by Fenrirthviti** [comment] 2022-09-25 17:58
Probably a dupe of #7442 manifesting in a different way.

**Comment by Fenrirthviti** [comment] 2022-09-25 17:59
Can test with PR https://github.com/obsproject/obs-studio/pull/7447 applied and see if it corrects this issue?

**Comment by xmcp** [comment] 2022-09-25 18:25
Sure. Do I need to compile the project by myself, or there is a pre-built version with this patch included?

**Comment by Fenrirthviti** [comment] 2022-09-26 01:33
You can grab a version with the patch applied here: https://obsbot.rodney.io/artifacts/375114136

**Comment by xmcp** [comment] 2022-09-26 10:49
The bug persists in the provided build.

You can [see the screencast](https://watch.screencastify.com/v/JXAEdxw1UPz0TMUpmavw), where PotPlayer only renders the first frame and does not update in most configurations, or crashes with a green video screen in some other configurations.

**Comment by RytoEX** [comment] 2023-02-08 20:16
Please re-test in OBS Studio 29.0.2 (or newer).

**Comment by xmcp** [comment] 2023-02-09 08:41
Tested on v29.0.2 and virtual camera is still not working in PotPlayer. The symptom is same.

**Comment by flaeri** [comment] 2023-02-10 18:02
The symptom is not the same for me. I'm using version 1.7.21873. I get the correct images, its just playing them back very slowly.
![image](https://user-images.githubusercontent.com/50419942/218162771-c2e04a9c-605c-4ff8-8f4a-e4ab3eae4628.png)

It correctly detects its nv12, 720p, 30fps. But it is not capable of playing it back for some reason. Its not dropping the frames, its just playing back at 1 fps.

This players seems to have been built on ffmpeg, and both ffmpeg and mpv play back the virtual camera without any issues, at the correct speed (30 fps in this instance).

I feel like its very likely that something PotPlayer is doing with this input is incorrect, and I don't think its OBS' fault.

**Comment by RytoEX** [comment] 2024-03-19 22:27
I've looked at this, and I agree with @flaeri 's assessment. Other applications can consume our virtual camera fine. Report this issue to PotPlayer. If they conclude that we're doing something wrong, our code is publicly available, and they can show us what we're doing wrong or submit a Pull Request that fixes the issue.

**Closed by RytoEX** 2024-03-19 22:27 UTC

**Comment by balibaliaya** [comment] 2024-03-25 22:12
VLC same problem , set audio device " non ", it's working.
But potplayer can‘t set audio device " non ".
