### ISSUE TITLE
OBS segfaults on launch

### ISSUE THREAD

**Issue by Gerodote** [obsproject/obs-studio#8481] opened 2023-03-17 07:34 UTC
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

29.0.2-1

### OBS Studio Log URL

sry, i can't do this

### Expected Behavior

normal run

### Current Behavior

crashes

### Steps to Reproduce

1.  ???
2. install from manjaro official repo
3.  get this

### Anything else we should know?

backtrace: 
```
    ~  gdb obs                                                                                                                                                                                       ✔  32s  
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
(No debugging symbols found in obs)
(gdb) run
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe31ff6c0 (LWP 4699)]
[New Thread 0x7fffe29fe6c0 (LWP 4700)]
[New Thread 0x7fffe21fd6c0 (LWP 4701)]
[New Thread 0x7fffe19fc6c0 (LWP 4702)]
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
info: CPU Speed: 3600.174MHz
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 32035MB Total, 24575MB Free
info: Kernel Version: Linux 6.1.19-1-MANJARO
info: Distribution: "Manjaro Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
[New Thread 0x7fffe0b086c0 (LWP 4703)]
[New Thread 0x7fffcbfff6c0 (LWP 4704)]
info: Qt Version: 6.4.2 (runtime), 6.4.2 (compiled)
info: Portable mode: false
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.2-1 (linux)
info: ---------------------------------
[New Thread 0x7fffcb7fe6c0 (LWP 4705)]
[New Thread 0x7fffcaffd6c0 (LWP 4706)]
[New Thread 0x7fffca7fc6c0 (LWP 4707)]
[New Thread 0x7fffc9ffb6c0 (LWP 4708)]
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
[New Thread 0x7fffc97fa6c0 (LWP 4709)]
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1050/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 525.89.02, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Lanczos
	fps:               24000/1001
	format:            NV12
	YUV mode:          Rec. 709/Partial
[New Thread 0x7fffb15ff6c0 (LWP 4710)]
info: NV12 texture support not available
info: P010 texture support not available
[New Thread 0x7fffa66456c0 (LWP 4711)]
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
[Detaching after fork from child process 4712]
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
[Detaching after fork from child process 4713]
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
[Detaching after fork from child process 4714]
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
[Detaching after fork from child process 4715]
[New Thread 0x7fffa5a296c0 (LWP 4716)]
[Detaching after fork from child process 4717]
[Detaching after fork from child process 4718]
[Detaching after fork from child process 4719]
[Detaching after fork from child process 4720]
[Detaching after fork from child process 4721]
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
[Detaching after fork from child process 4722]
[Detaching after fork from child process 4723]
[Detaching after vfork from child process 4724]
[Detaching after fork from child process 4726]
info: NVENC supported

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
XDisplayString (dpy=0x0) at /usr/src/debug/libx11/libX11-1.8.4/src/Macros.c:119
119	char *XDisplayString(Display *dpy) { return (DisplayString(dpy)); }
```

**Comment by tytan652** [comment] 2023-03-17 07:35
Duplicate of #8056

**Closed by tytan652** 2023-03-17 07:35 UTC
