### ISSUE TITLE
VAAPI encoding broken

### ISSUE THREAD

**Issue by ripper81** [obsproject/obs-studio#7956] opened 2022-12-22 11:13 UTC
### Operating System Info

Other

### Other OS

Kubuntu 22.10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/L0Ucu-FzcNtB0roT

### Expected Behavior

Working GPU encoding via VAAPI

### Current Behavior

FFMPEG VAAPI worked for me on both of my Kubuntu 22.10 installs. One uses an AMD Radeon RX 6700 XT with MESA the other system is a Notebook with an intel HD igpu using the intel mediadriver for VAAPI. Both systems are now unable to utillize GPU encoding. OBS throws an error and says that i need to check wether my drivers are up to date.  

### Steps to Reproduce

1. Install OBS via Flatpak
2. Try to use FFMPEG VAAPI for encoding
3.
...

**Comment by tytan652** [comment] 2022-12-22 11:47
> FFMPEG VAAPI worked for me on both of my Kubuntu 22.10 installs.
> …
> 1. Install OBS via Flatpak

How can you say it worked, if it doesn't work just after installing OBS ?

Other than that, if you installed Flatpak through the command line. Please update with `flatpak update` just in case to maybe fix the Intel issue.

RX 6000 is VAAPI is surely not available with mesa 21.
This one is normally fixed with OBS 29 but KDE still need to fix their runtime.

**Comment by ripper81** [comment] 2022-12-22 12:52
It worked beforehand. I don´ t use OBS that often. However i used the flatpak version for sometime now. I never had problems with using VAAPI. I am not shure when things started to fail. I just discovered this morning when i did some screenrecording. Since the encoder was set to VAAPI before i just started recording and it failed .And like i said it doesn´t just fail with my RX 6700XT with MESA, it also fails on the Intel iGPU with intels proprietary media driver. 

OBS is up to date i am running 28.1.2 on both devices.

**Comment by tytan652** [comment] 2022-12-22 13:20
Note that there is no such things as a "intels proprietary media driver", on Linux Intel driver are only open source.

For your issue, it looks like a support issue from the start, you should ask for help on our discord server or forums.

It could be a wrong device set in OBS or VAAPI driver not availlable or not working.

**Comment by ripper81** [comment] 2022-12-22 13:45
> Note that there is no such things as a "intels proprietary media driver", on Linux Intel driver are only open source.
> 
> For your issue, it looks like a support issue from the start, you should ask for help on our discord server or forums.
> 
> It could be a wrong device set in OBS or VAAPI driver not availlable or not working.

I have two packages available on Kubuntu, Intel-media-va-driver and Intel-media-driver-nonefree. Both are VAAPI drivers but they are different. Vainfo also reports different driverinformation for both drivers. 

There is also a noticeable difference in performance between both drivers when used for encoding with OBS.

**Comment by tytan652** [comment] 2022-12-22 14:04
Flatpak use Flatpak runtimes not system packages.

**Comment by ripper81** [comment] 2022-12-22 14:31
> 

Maybe there was a change in the MESA packages  for flatpak. I heard that some linuxdistributions recently have disabled support for h.264 and h.265 in MESA VAAPI.

**Comment by tytan652** [comment] 2022-12-22 14:39
Just tested and VAAPI indeed cease to work on Flatpak on 28.1.2

**Comment by ripper81** [comment] 2022-12-22 14:39
So i installed OBS via the Ubuntu ppa and it worked out of the box.  So i guess it is related to the flatpak version of OBS and not a general issue with obs.

**Comment by tytan652** [comment] 2022-12-22 14:40
> Maybe there was a change in the MESA packages for flatpak. I heard that some linuxdistributions recently have disabled support for h.264 and h.265 in MESA VAAPI.

Urelated, OBS 28 does not rely on 22.08 runtimes.

**Closed** 2022-12-22 15:35 UTC
Labels: Linux

**Comment by ripper81** [comment] 2022-12-22 15:45
I'll use the native build from the ppa for now. Personaly i'd prefer flatpaks over managing a lot of ppa's. I wonder if anyone else is affected by this.

**Comment by DomiStyle** [comment] 2022-12-23 20:44
> I wonder if anyone else is affected by this.

I'm having the same issue but on Fedora, VAAPI and gstreamer (via plugin) stopped working recently.

```
info: ---------------------------------
info: [FFMPEG VAAPI encoder: 'advanced_video_recording'] settings:
	device:       /dev/dri/by-path/pci-0000:0c:00.0-render
	rate_control: CBR
	profile:      578
	level:        40
	qp:           0
	bitrate:      2500
	maxrate:      2500
	keyint:       120
	width:        2560
	height:       1440
	b-frames:     0

[AVHWDeviceContext @ 0x555ab01979c0] libva: /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so has no function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x555ab01979c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

Or with gstreamer:
```
error: no element "vaapih264enc"
```

Any ideas where I should start to diagnose this?

All flatpaks are up to date. Kdenlive and ffmpeg in flatpaks have no issues with VAAPI.

**Comment by X-m7** [comment] 2022-12-25 13:49
This appears to be caused by a regression in the Flatpak Mesa drivers (an issue is filed upstream [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1528) already), in my case reverting the `org.freedesktop.Platform.GL.default//21.08` flatpak to commit `927c51d661eb70910a3a51e3e05e923cbaadd2c8be77f0bd7fedb18b9c079ce7` and the `org.freedesktop.Platform.VAAPI.Intel//21.08` flatpak to commit `22521e76f9717b19be38e431b8794224bf845d87430e3a3ec9009230f741242d` got VAAPI to work with the OBS flatpak again.

**Comment by DomiStyle** [comment] 2022-12-25 16:13
Thanks @X-m7, it worked for me:

```
sudo flatpak update --commit=927c51d661eb70910a3a51e3e05e923cbaadd2c8be77f0bd7fedb18b9c079ce7 runtime/org.freedesktop.Platform.GL.default/x86_64/21.08
```

Things are working just fine again.

**Comment by ripper81** [comment] 2022-12-25 16:44
> Thanks @X-m7, it worked for me:
> 
> ```
> sudo flatpak update --commit=927c51d661eb70910a3a51e3e05e923cbaadd2c8be77f0bd7fedb18b9c079ce7 runtime/org.freedesktop.Platform.GL.default/x86_64/21.08
> ```
> 
> Things are working just fine again.

Did not change anything on my end.

**Comment by DomiStyle** [comment] 2022-12-25 18:01
> Did not change anything on my end.

Did you test on AMD or Intel? On Intel you might try downgrading the second runtime @X-m7 linked as well.

I did it on my machine with an AMD 6900 XT and `org.freedesktop.Platform.GL.default` was sufficent.

**Comment by ripper81** [comment] 2022-12-25 18:30
I use an AMD Radeon RX 6700 XT on Kubuntu 21.10.

**Comment by ripper81** [comment] 2022-12-28 17:25
> > Did not change anything on my end.
> 
> Did you test on AMD or Intel? On Intel you might try downgrading the second runtime @X-m7 linked as well.
> 
> I did it on my machine with an AMD 6900 XT and `org.freedesktop.Platform.GL.default` was sufficent.

Since it does not work for me. Is there a way to revert anything back to as it was before installing the commit?

**Comment by X-m7** [comment] 2022-12-28 17:38
> > > Did not change anything on my end.
> > 
> > 
> > Did you test on AMD or Intel? On Intel you might try downgrading the second runtime @X-m7 linked as well.
> > I did it on my machine with an AMD 6900 XT and `org.freedesktop.Platform.GL.default` was sufficent.
> 
> Since it does not work for me. Is there a way to revert anything back to as it was before installing the commit?

It might be worth checking the logs after the revert and seeing if anything changes in there, to me it looks like you may have something else causing issues.

You could try choosing another commit to revert to (or try reverting the OBS flatpak itself, or the runtime it uses) by following the [Flatpak documentation](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading) on downgrading, and you could also try deleting the `~/.var/app/com.obsproject.Studio` folder (which is where the OBS flatpak stores its settings and such).

If you're just talking about undoing the revert you can just do `flatpak update` to get back to the latest versions of things.

**Comment by tytan652** [comment] 2022-12-28 17:48
This is maybe a potential issue with the Flatpak runtime, but I can't reproduce it.

This is a closed issue. And just in case I add that for 29 we bumped to 6.4 runtime (22.08).

**Comment by kkartaltepe** [comment] 2022-12-28 18:41
I am locking conversation as we prefer to avoid our bugs becoming a forum, we have [a forum](https://obsproject.com/forum/) for that.

Feel free to discuss the problem with the flatpak runtime on their bug tracker https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1528
