### ISSUE TITLE
OBS VirtualCam selects first v4l2-loopback virtual camera, even if already in use

### ISSUE THREAD

**Issue by rombert** [obsproject/obs-studio#4796] opened 2021-06-02 12:46 UTC
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/LInK3a0BCGJAmGQh

### Expected Behavior

I have an existing virtual camera set up using v4l2-loopback and I'd also like to use the OBS virtual cam. I've configured them as

```
options v4l2loopback devices=2 exclusive_caps=1 video_nr=8,9 card_label="Android Camera (Virtual)" ,"OBS Camera (Virtual)"
```

and I expect  /dev/video8 to be left alone and /dev/video9 to be used by OBS. Unfortunately OBS tries to use the first available camera, and attempts to write to /dev/video8. Since I already have /dev/video8 in my OBS screen i can see some weird corruption which I assume is due to two processes writing at the same time to that virtual input.

I would like OBS to either skip 'in use' virtual cameras or to allow me to configure the output, either by camera name or by device location.

### Current Behavior

OBS webcam uses the first loopback device, even if already in use.

### Steps to Reproduce

1. Set up v4l2-loopback with two virtual webcams
2. Hook up the first virtual webcam to another source
3. Display the first virtual webcam on screen
4. Start OBS virtual webcam

### Anything else we should know?

OBS rocks ;-) Hopefully you know that by now.

**Comment by WizardCM** [comment] 2021-06-02 12:48
Duplicate of #3929

**Closed by WizardCM** 2021-06-02 12:48 UTC

**Comment by rombert** [comment] 2021-06-02 12:49
Thanks @WizardCM, I missed that in my search.
