### ISSUE TITLE
Monitoring of audio stops working if using gstreamer plug-in but audio is still sent out in stream

### ISSUE THREAD

**Issue by biosmatrix123** [obsproject/obs-studio#6511] opened 2022-05-18 15:02 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/dt74bStDJ9huZSJ2

### Expected Behavior

Monitoring the audio to continue working after changing to the scene which Gstreamer is a source of

### Current Behavior

Audio through monitoring device can be heard for a few seconds then stops - but the audio is still sent out in the stream fine.

### Steps to Reproduce

1. Install the Gstreamer plug-in https://obsproject.com/forum/resources/obs-gstreamer.696/
2. Make sure to have an audio source you can physically hear set as the monitoring output in OBS settings
3. Create 2 scenes - one empty scene, the other scene with a Gstreamer source - the default pipeline value in Gstreamer which shows the 'test card' and plays a 'bleep' noise is fine for this!
4. Turn monitoring on for the Gstreamer Source in the scene with Gstreamer
5. Switch to the blank scene
6. Switch to the Gstreamer source scene - you will hear beeps but they stop - yet you can see audio is still happening by the audio meter + if you stream out, you will still hear the audio yet monitoring the audio has now stopped.

### Anything else we should know?

If the option to 'Use pipeline time stamps (video)' is selected in the properties of the Gstreamer source, the problem seems resolved.

Unsure if this is a Gstreamer plugin issue or OBS issue however as its only happening at the monitoring audio level, raising it to OBS.

**Comment by fzwoch** [comment] 2022-05-18 15:07
I think you should use timestamps always. That option exists for some specific use cases where you are know what you are doing. For historically reason this option is not set by default, maybe that should be changed.

**Comment by Fenrirthviti** [comment] 2022-05-18 19:08
Since the issue is resolved with an option in the gstreamer plugin, I would recommend reporting it to them. If there is something on our end that we need to look at, we can work with the gstreamer plugin dev on it and reopen this issue.

**Closed by Fenrirthviti** 2022-05-18 19:08 UTC

**Comment by biosmatrix123** [comment] 2022-05-18 19:29
> I think you should use timestamps always. That option exists for some specific use cases where you are know what you are doing. For historically reason this option is not set by default, maybe that should be changed.

Thanks for the info. Is there potential for this to effect not just the monitored audio? We have a separate issue whereby when watching a SRT stream using gstreamer plugin randomly results in choppy audio - selecting a different scene and then switching back resolves it. We don’t currently have the options ticked so will be enabling.
