### ISSUE TITLE
Intel QSV recording does not open with Avidemux

### ISSUE THREAD

**Issue by catscarlet** [obsproject/obs-studio#5163] opened 2021-08-20 08:48 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://gist.github.com/catscarlet/4b7d5d5adbfe348d23fc218ec684da18

### Expected Behavior

Output record file can be managed by Avidemux.

### Current Behavior

Output record file can not be managed by Avidemux.

### Steps to Reproduce

1. Start streaming but do not start recording (Make sure uncheck Setting->General->Output->Automatically record when streaming)
2. After starting streaming a while, click start recording.
3. After a while, stop streaming/recording.
4. Open the record video file with Avidemux. the time range is broken.

![screenshot_by_flameshot_at_20210820164247](https://user-images.githubusercontent.com/10594035/130206443-dc5b71f7-6dc9-4855-b45e-cf703621b241.png)

### Anything else we should know?

In the log file: I started to stream at 15:02:49 with "Automatically record when streaming, but I click stop recording at 15:02:51, then I start to record again at 15:39:05.

I think this was a bug before [26.1.0](https://github.com/obsproject/obs-studio/releases/tag/26.1.0).
There was a bugfix said "Fixed an issue where certain recordings could not be remuxed (typically from the QSV encoder) [R1CH]" but I didn't know which commit was it.

**Comment by RytoEX** [comment] 2022-02-13 04:52
I cannot reproduce this on an Intel HD Graphics 630 (i7-7700HQ, Kaby Lake) with driver 30.0.101.1069 in OBS Studio 27.0.1, 27.1.3, or 27.2.0 when opening the file with Avidemux nightly build [avidemux_r220207_win64Qt5_130.zip](http://www.avidemux.org/nightly/win64/avidemux_r220207_win64Qt5_130.zip). Can you please re-test and confirm if this is still an issue? If this is still an issue, please provide an updated OBS session log and let us know what version of Avidemux you are using.

**Comment by RytoEX** [comment] 2022-02-18 08:43
I am unable to observe your described issue with your settings (QSV, VBR, target 3000 Kbps, max 4500 Kbps; 1280x720@60) with OBS Studio 27.2.0 and Avidemux 2.7.6 on Windows 10.  Avidemux loads the video and plays audio just fine.  I can play and stop the video, and I can seek while the video is stopped.  Could you be more specific about what _exactly_ you're observing in Avidemux?

Are you able to reproduce this with files created with OBS Studio 27.2.0?

If the latest version of Avidemux doesn't show an issue, then I'm not sure what exactly the problem is here and if it makes sense to keep this open.

**Comment by catscarlet** [comment] 2022-02-18 12:48
` what exactly you're observing in Avidemux?`
I wasn't. After the video file is loaded by Avidemux 2.7.6, the seek-function is already broken as the screenshot shows.

------

It can be reproduced with OBS Studio 27.2.0 on Win10, with Avidemux 2.7.6 on Win10.

![b85m-win061-snap](https://user-images.githubusercontent.com/10594035/154682422-c3e42b96-71c9-48db-8495-8f15fbec8c06.png)

------

I find out something more about this. The Avidemux is basical a FFmpeg with GUI, so I tried to detach video and audio from the recording with *FFmpeg Latest Auto-Build (2022-02-17 12:31)*, and I got this.

<details>
  <summary>Click to show the FFmpeg log!</summary>
  
 ```

D:\GreenToolsX64\ffmpeg-master-latest-win64-gpl\bin>ffmpeg -i K:\obs_record\2022-02-18_20-02-14.mkv -vcodec copy -an K:\obs_record\noaudio.mkv
ffmpeg version N-105660-g2812508086-20220217 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220217
  libavutil      57. 21.100 / 57. 21.100
  libavcodec     59. 21.100 / 59. 21.100
  libavformat    59. 17.102 / 59. 17.102
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 27.100 /  8. 27.100
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
Input #0, matroska,webm, from 'K:\obs_record\2022-02-18_20-02-14.mkv':
  Metadata:
    ENCODER         : Lavf58.76.100
  Duration: 00:00:17.92, start: 0.000000, bitrate: 3711 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:00:17.917000000
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Track1
      DURATION        : 00:00:17.889000000
  Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track2
      DURATION        : 00:00:17.889000000
  Stream #0:3: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track3
      DURATION        : 00:00:17.889000000
  Stream #0:4: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track4
      DURATION        : 00:00:17.889000000
Output #0, matroska, to 'K:\obs_record\noaudio.mkv':
  Metadata:
    encoder         : Lavf59.17.102
  Stream #0:0: Video: h264 (High) (H264 / 0x34363248), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:00:17.917000000
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[matroska @ 00000258b733e6c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 00000258b733e6c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=    3 fps=0.0 q=-1.0 Lsize=      33kB time=00:00:00.00 bitrate=N/A speed=   0x
video:35kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

D:\GreenToolsX64\ffmpeg-master-latest-win64-gpl\bin>
```
</details>

![b85m-win062-snap](https://user-images.githubusercontent.com/10594035/154682328-d2c886e0-321b-45e4-93b1-0fcb9cf5cc04.png)

The audio detach works fine. Only video has this error.

`-vcodec copy -acodec copy` leads to same result.
 
I also tried param `-use_wallclock_as_timestamps 1` and `-fflags +genpts`
-  `-fflags +genpts` does nothing
- `-use_wallclock_as_timestamps 1` makes the output video goes crazy fast

Well now I doesn't know how did Avidemux fix this. The changelog of Avidemux didn't mention anything about this. I thought this was going to be a FFmpeg 4.2 issue because Avidemux update it to 4.4.1 but all FFmpeg 4.4.1 and 5.0 and git-master-builds report the same error.

------

More information I just found.

Even Avidemux 2.8 can open and play it, but when try to save the output with `copy`(basically it is FFmpeg -vcodec copy and -acodec copy), the output file is unplayable.

**Comment by catscarlet** [comment] 2022-02-18 12:58
Oh sorry forgot to mention I was using *(use stream encoder)*

Would that matter?

![b85m-win064-snap](https://user-images.githubusercontent.com/10594035/154687072-1216fd8d-0112-4b93-abc7-bc22f4753d8a.png)

![b85m-win063-snap](https://user-images.githubusercontent.com/10594035/154687012-5ec658d9-5d88-4aef-956b-50a295127ecc.png)

**Comment by flaeri** [comment] 2022-11-30 20:39
I believe there has been fixes (like timestamps) for QSV since. Recording with a modern version of OBS, I get the following results with avidemux.

2.7.6:
Can seek, play, and remux (copy video and audio), both to mp4 and mkv. Both play back fine after exporting.

2.8.0:
Can seek, play, and remux (copy video and audio), both to mp4 and mkv. Both play back fine after exporting.

**Comment by gxalpha** [comment] 2023-01-12 14:15
As mentioned above by Flaeri, we believe that this should be fixed. If you still see this issue occurring in OBS 29, please open a new issue, with a new log file and new Steps to Reproduce.

**Closed by gxalpha** 2023-01-12 14:15 UTC
