### ISSUE TITLE
Audio latency on monitor

### ISSUE THREAD

**Issue by cmavr8** [obsproject/obs-studio#3664] opened 2020-10-29 12:38 UTC
## Platform
Operating system and version: Mac OS 10.15.7
OBS Studio version: 26.0.2

## Expected Behavior
Audio output of OBS should be delivered with minimal lag/latency/delay to the audio monitor output

## Current Behavior
When I first start OBS, the audio is delivered to the monitor with minimal lag. After a few minutes (as low as 10), there is a noticeable delay added to the audio stream that is output to the monitor. Over time this increases, reaching more than 1 second lag after 90 minutes of having OBS running.
(Log attached in following comment, to keep this field short)

## Steps to Reproduce
1. Install OBS and either BlackHole (`brew install blackhole`) or VB-Cable
2. In obs, settings > audio > Mic/Aux audio: select a microphone
3. Monitoring device: BlackHole
4. In the audio mixer panel (lower center), click the cog of the mic source > Advanced audio properties > next to Mic/aux, under audio monitoring, select monitor & output
5. Hold Option and click on the audio icon at the top system bar, select BlackHole as the input device
6. Start Photo Booth
7. Record a video with the webcam showing your face. Say "test" and stop recording after a couple seconds. Watching the recorded video, observe your lips and note that there is no or minimal delay between audio and video. All good.
8. Wait 20-30' (Photo Booth doesn't need to be open)
9. Repeat steps 6 & 7. Observe that there is now a delay between lips and audio. 

## Additional information
I'm using a Trust USB microphone as a source. No other CPU/RAM/GPU intensive programs are running on the Mac. No video inputs or other audio sources configured in OBS. The default scene is the only one there, and is empty.

The following things do not solve the problem, once it manifests:
* playing with (muting/unmuting etc) various settings in OBS, MacOS's MIDI audio device panel and MacOS's Sound panel.
* using VB-Audio instead of BlackHole
* Removing filters on the Mic/Aux
* Using Mic/Aux 4 instead of 1
* Using different apps to record the test video

The only workaround is to restart OBS every 10 minutes. Obviously this is problematic.

**Comment by cmavr8** [comment] 2020-10-29 12:40
[90min obs results in mic lag.log](https://github.com/obsproject/obs-studio/files/5458362/90min.obs.results.in.mic.lag.log)

**Comment by kkartaltepe** [comment] 2020-10-29 15:48
It doesnt look like obs even supports increasing buffers on macosx monitors, so something other than obs in the audio chain is adding latency to monitors. OBS internally cannot add more than 1s of latency to any source before it, but its possible obs is still underrunning its buffers prompting something else to increase its latency. If any mac experts can add a way to detect this in OBS that would be nice, but otherwise you will need to investigate some other avenue to diagnose this.

**Comment by cmavr8** [comment] 2020-10-29 17:56
Thanks for the response. I'm wondering, assuming the hypothesis that something other than OBS adds the delay, why does a restart of OBS solve the issue? 

Sorry if this is a silly question, I'm not very familiar with how all this works together.

**Comment by Fenrirthviti** [comment] 2020-10-29 21:13
Restarting OBS will flush the buffers, which is not possible otherwise. When there is a device slowly drifting and sending back timestamps, the buffer (up to 1s) will fill and eventually cap out. Restarting OBS will "reset" this because the buffer is reinitialized, but it's pretty much always an external device misbehaving rather than something internal to OBS.

**Comment by cmavr8** [comment] 2020-10-30 08:07
I see, so, what other components may be responsible for this?
I'm thinking:
* the driver of the physical USB mic used as source
* coreaudio or whatever in macOS sits between the driver and OBS
* after OBS, the fake device's driver (BlackHole or VB-Audio)

Am I getting this right?

I understand that if this is not an OBS issue we should close this ticket. Given the number of people affected I'd appreciate if we can troubleshoot a bit more. Thanks.

**Comment by cmavr8** [comment] 2020-10-30 10:33
Could this be related?
![image](https://user-images.githubusercontent.com/843878/97694992-a24ed980-1aa3-11eb-80d2-dc607e92edd7.png)

**Comment by Fenrirthviti** [comment] 2020-10-30 19:41
Rendering lag is GPU overload, which shouldn't have any impact on audio. It does, however, point a finger at lack of system resources, so there could be a connection from that standpoint. If the system is being overloaded and can't send audio packets fast enough, that could absolutely cause the issues being described.

**Comment by cmavr8** [comment] 2020-10-31 09:51
Thanks once again for your help!

Let's see if this is considered overload:
While not recording, and just using my browser, obs is processing sound, obviously. The system load looks like this:
![idling](https://user-images.githubusercontent.com/843878/97776175-45682780-1b66-11eb-9e71-e52d1610b9cb.png)
Note that if I do this for 10' after starting OBS, and then start recording, I already experience the delay. So whatever the problem, it builds up during this "idling" stage.

When I'm actually recording (using the photobooth app), load looks like this:
![while recording](https://user-images.githubusercontent.com/843878/97776215-8bbd8680-1b66-11eb-8626-f3d24676e7cb.png)

If I restart OBS and restart recording, the lag is eliminated and the process monitor shows similar things to above. No change in load.

All in all, it seems to me that quite a bit of system resources are used, both in idle and recording, but within the limits of the system. What's your take?

**Comment by WizardCM** [comment] 2020-11-01 09:15
GPU = graphics card. htop only shows CPU usage.

**Comment by cmavr8** [comment] 2020-11-01 10:46
Actually I was focusing on the load of the rest of the system.
Here is the GPU load while recording:
![GPU load while recording](https://user-images.githubusercontent.com/843878/97800707-bcb9bc00-1c37-11eb-8058-ebf02002c86d.png)

The graph looks very similar when I'm experiencing the audio delay. No visible difference.

So, the system seems not overloaded, right?

**Comment by cmavr8** [comment] 2020-11-02 08:11
In [one of the forum threads I mentioned above](https://obsproject.com/forum/threads/elgato-hd60s-audio-becomes-delayed-after-running-for-around-1hr-please-help.132456/post-489176), someone made 2 observations:

* _I have left the original Elgato Game Capture App on for an hour and the Audio stays in sync there but not on OBS._ 
* _when I change the audio monitoring to Monitor Off, and recording for 1 hour, there does not seem to be any delay, but the problem then becomes I cannot hear it without Monitor Only (mute output)_

**Comment by cmavr8** [comment] 2020-11-03 15:58
Another data point:
* The internal mic of my laptop is also affected by this, but much less than the external USB mic
To make the problem easier to understand, I made a short video: https://youtu.be/y_P6GxZhIuU

**Comment by alextiekam** [comment] 2020-12-28 03:07
I have the same problem with audio delay on monitoring my elgato. Like it already mentioned, after approx 1 hour i've got this problem. 

I do only streaming, no recording. And the interesting thing is, that the stream works in sync. So I have 1 second delay, but my Viewer told me, that he doesn't have any delay between Audio and Video. So the issue is i think on the "monitoring"-Feature. 

To reset it i just hide the source through the "eye" (![image](https://user-images.githubusercontent.com/34971606/103186652-a8094580-48c1-11eb-85ce-2b1a539033b9.png)). 

And after few seconds I make it visible again. And then its fixed for approx. one hour.

**Comment by cmavr8** [comment] 2020-12-28 15:54
Hey @alextiekam, thanks for the tip about toggling the "eye". Unfortunately it doesn't help in my situation.

I think we need someone who understands the mac OS sound subsystem well to analyze this. I unfortunately don't have the time right now to do this :/

**Comment by negue** [comment] 2020-12-28 16:27
I get a lagging when ever I open the Filters on my Mic and to remove the Lag, I disable the monitoring and then activating it back.

Then the lag of (half / full second) is gone.

**Comment by alextiekam** [comment] 2020-12-28 19:30
Hi @cmavr8, i'm using obs in Windows. Sorry. Forgot to mention my OS. Therefore im thinking, its more within the Software.

**Comment by bruxy70** [comment] 2020-12-28 21:42
@cmavr8, OBS is currently unusable for anything else than recording or perhaps streaming to a few services. It is great that OBS introduced the virtual camera, but it is currently completely useless, as it does not feature virtual audio, and the ridiculous workaround through the audio monitor is unusable due to the latency issue.
So this makes OBS completely useless for any online services like Zoom, Webex or Teams, and I hate that I have to tell people to use crap like [splitcam](https://splitcamera.com/) instead of OBS, which used to be the de-facto standard for video production. I appreciate this is an open-source project and the community can decide to spend their time on things that are more fun to do. But please consider the consequences of these decisions. Thank you!

**Comment by cmavr8** [comment] 2020-12-29 09:41
> I get a lagging when ever I open the Filters on my Mic and to remove the Lag, I disable the monitoring and then activating it back.
> 
> Then the lag of (half / full second) is gone.

The fastest way I have found to fix the lag is by selecting the mic source in the sources panel, clicking on the drop-down "Device" that's in the above panel, selecting another source, clicking again, selecting my mic as source.



> Hi @cmavr8, i'm using obs in Windows. Sorry. Forgot to mention my OS. Therefore im thinking, something is wrong within the Software.

Interesting, so it may actually be a bug of OBS. Anyway, we need someone who understands the subsystems of one of these two OSes to analyze this 🤷 



> @cmavr8, OBS is currently unusable for anything else than recording or perhaps streaming to a few services. It is great that OBS introduced the virtual camera, but it is currently completely useless, as it does not feature virtual audio, and the ridiculous workaround through the audio monitor is unusable due to the latency issue.
> So this makes OBS completely useless for any online services like Zoom, Webex or Teams, and I hate that I have to tell people to use crap like [splitcam](https://splitcamera.com/) instead of OBS, which used to be the de-facto standard for video production. I appreciate this is an open-source project and the community can decide to spend their time on things that are more fun to do. But please consider the consequences of these decisions. Thank you!

Hey @bruxy70, I'm not sure what decision you're referring to, or why this is addressed to me personally. I have not made any decisions regarding the development of OBS. I'm just a user trying to figure out how to fix the audio lag issue.

**Comment by bruxy70** [comment] 2020-12-29 11:19
@cmavr8 , sorry, I thought you were the code owner for this. This issue does not have anyone assigned so I got confused. Sorry.

**Comment by cmavr8** [comment] 2020-12-29 15:09
No worries mate!

**Comment by AaronD-GH** [comment] 2021-03-28 13:53
I have the same problem on Ubuntu 20.04, updated weekly from the repositories.  Producing a live stream and backup recording for about 1.5 hours at a time, with multiple cameras feeding individually into OBS, and a finished audio feed from an external hardware mixer through a USB interface.  No audio processing at all in OBS...or at least not configured for it; that's the external mixer's job.

The stream and recording are always okay; only the monitor (my headphones) increases its latency as time goes on, which makes it difficult to produce the stream because what I hear in the 'phones no longer lines up with the cameras.  But even then, the stream and recording are still good, and OBS's audio meter is still in time with the room.  Only the monitor output itself (my 'phones) is wrong.

I also hear a "hiccup" every so often in the 'phones, so it would not surprise me if the latency is being added incrementally at those discrete moments.  Each one is not enough to notice a difference, but they add up.

Unlike the previous comments, I found a workaround that does NOT require restarting OBS.  I have two different audio output devices that can drive my 'phones equally well (one USB via PulseAudio and then Jack, and one built-in via PulseAudio alone), so I put a hardware switch between them.  When the latency gets to be intolerable, go to OBS's Audio settings, switch the Monitor output device, and flip the hardware switch to match.  The latency is now reset!  This can even be done during a live stream without interrupting it.  The details of the audio chain don't seem to matter; just switch to a different one, and it's all good...for a while.

So that removes the maximum length of an event if you care about the monitor, but it's still annoying.

**Comment by cmavr8** [comment] 2021-03-28 17:02
Hey @AaronD-GH, thanks for sharing 👍 
Maybe checkout this way too, from above:

> The fastest way I have found to fix the lag is by selecting the mic source in the sources panel, clicking on the drop-down "Device" that's in the above panel, selecting another source, clicking again, selecting my mic as source.

**Comment by AaronD-GH** [comment] 2021-03-28 22:27
> Hey @AaronD-GH, thanks for sharing +1
> Maybe checkout this way too, from above:
> 
> > The fastest way I have found to fix the lag is by selecting the mic source in the sources panel, clicking on the drop-down "Device" that's in the above panel, selecting another source, clicking again, selecting my mic as source.
> 
> I'm still suffering from this bug, so I use this workaround every day :)

I didn't get a chance to try that today.  We were already live by the time it did again, and I *really* don't want to mess with what's going out to the audience!

I also might be mistaken about the slow-and-steady part.  Twice today, I heard a full cut-out that lasted about half a second, and then the monitor was delayed by that much.  Just like a network glitch, except that this is all on the same machine.  Both times, the meter in OBS was still correct afterwards, only my headphones (the monitor output) had that delay.

So as not to disrupt the critical live output that was still okay, I used my trick again instead of yours, and just like always, that fixed it right up.  It would probably work to switch OBS twice and not use the hardware one (so if you only have one physical output but still have a virtual one or something else that doesn't go anywhere, that can work), but the second switch in OBS would take that much longer and I really want to get back to live production ASAP.  I can switch the software and the hardware at the same time, so it's slightly shorter to do it that way.

**Comment by MechanicallyDev** [comment] 2021-04-16 16:00
I've recently opened another issue with the same problem (https://github.com/obsproject/obs-studio/issues/4531).
The workaround I use is, for each microphone, to use 2 "Move Source" filters on the scene where I insert my audio inputs:
Move Source # 1: To disable the microphone source, wait an interval with it disabled (I got good results disabling for 100ms), and at the end enable the Move Souce # 2.
Move Source # 2: To enable the microphone source, wait an interval with it enabled (I got good results with 60000ms / 1 minute), and at the end enable the Move Source # 1.

**Comment by AaronD-GH** [comment] 2021-04-16 16:31
> Move Source # 1: To disable the microphone source, wait an interval with it disabled (I got good results disabling for 100ms), and at the end enable the Move Souce # 2.
> Move Source # 2: To enable the microphone source, wait an interval with it enabled (I got good results with 60000ms / 1 minute), and at the end enable the Move Source # 1.

So you're automatically "blinking the mic's mute button"?  (to slightly misappropriate some terminology from live audio)
(1/10-second cut-out every minute)

Doesn't that also cut out the stream/recording, which is still okay?  (or at least was before you added the artificial "mic blink")

**Comment by MechanicallyDev** [comment] 2021-04-16 17:22
> > Move Source # 1: To disable the microphone source, wait an interval with it disabled (I got good results disabling for 100ms), and at the end enable the Move Souce # 2.
> > Move Source # 2: To enable the microphone source, wait an interval with it enabled (I got good results with 60000ms / 1 minute), and at the end enable the Move Source # 1.
> 
> So you're automatically "blinking the mic's mute button"? (to slightly misappropriate some terminology from live audio)
> (1/10-second cut-out every minute)
> 
> Doesn't that also cut out the stream/recording, which is still okay? (or at least was before you added the artificial "mic blink")

Exactly, I use move source to blink the mic, refreshing the buffer automatically. 100ms is fast enough that it isn't noticeable even if it happens when you're speaking, but you can decrease the blink time (it stops refreshing the buffer if it's too fast), or increase the time between each blink to one that better fit your needs.

**Comment by maxdrfr** [comment] 2021-06-12 17:27
Theres already a ticket for this issue.
#3525

**Comment by VastleCania** [comment] 2022-09-15 18:19
It seems like I was able to fix this by switching the Sample Rate to 44.1 khz (down from 48 khz) in my particular setup. I'm using an EVGA XP1 on Windows 10. Maybe this well help someone else here!!

**Comment by VastleCania** [comment] 2022-09-15 20:49
Hmm, nevermind. It was _better_ but the delay does build up eventually in the monitor.

**Comment by Fenrirthviti** [comment] 2022-10-19 20:07
It's unclear what exactly the original issue was, and there has since been additional logging added for buffering.

If anyone in this thread is still having the issue, can you please reproduce and provide a log file?

**Comment by PatTheMav** [comment] 2022-10-20 16:27
Duplicate of https://github.com/obsproject/obs-studio/issues/4531

**Comment by PatTheMav** [comment] 2022-10-22 14:45
As explained in https://github.com/obsproject/obs-studio/issues/4531, monitoring is not supposed to stay in sync with the output of OBS, but with the input of the respective device.

Depending on available system resources, CPU time allotted to OBS' threads and other factors, audio buffering can and will increase during a session. OBS uses timestamps to ensure that audio and video stay in sync for recording or streaming outputs, but as monitoring is no output (hence the name "monitoring") no such syncing happens here.

In fact such syncing would actively _break_ the main purpose of monitoring, so the expected behaviour would only be met by a "master output" which OBS does not have and is a new feature.

**Closed by PatTheMav** 2022-10-22 14:45 UTC
Labels: macOS

**Comment by saurik** [comment] 2023-02-06 10:52
@PatTheMav I'm not sure I understand the argument... isn't the point of being able to monitor the input that it has low latency? It seems like you are saying that it should be tied to the input, but the problem is that it is gets later and later and later over time, which makes the monitor kind of broken as a monitor.

**Comment by MarcusBuer** [comment] 2023-02-06 17:01
@PatTheMav 
> OBS uses timestamps to ensure that audio and video stay in sync for recording or streaming outputs, but as monitoring is no output (hence the name "monitoring") no such syncing happens here.

Don't OBS has any watchdog that could be used to check the monitoring buffer size and if it is too long reset the buffer? It would give a "click" sound when cleaning the buffer to get the latest audio, but for monitoring this is less distracting than having a delay that increases over time.

The workaround I'm currently using is this script I made: https://github.com/MarcusBuer/OBS-Anti-Mic-Monitoring-Desync
It works by disabling and re-enabling the monitoring at a set interval to keep it updated.

**Comment by PatTheMav** [comment] 2023-02-06 18:52
As said before: The monitoring system is separate from the audio output system and for obvious reasons the latter has always taken priority (as that's what ends up in recordings and streams).

Main problem is that some users want monitoring to have almost no buffering at all (mimicking monitoring outputs on audio hardware, which would effectively mean a low + fixed buffer and probably realtime threads), while others abuse the monitoring output in combination with a preview projector to create a local "output" of their stream (and expect audio to be in sync with video).

Alas the current monitoring system is a good-effort implementation that gives _some_ form of monitoring and given that those directly contradict each other, I'm afraid that it might receive some superficial fixes to reduce issues, but might otherwise require a reimplementation.

**Comment by saurik** [comment] 2023-02-06 19:37
@PatTheMav But the current solution doesn't seem to be correct for either of those use cases. And, FWIW, I am often in that latter category and yet I am going to say that a low-latency actual-monitor would also work fine as what I am often doing to work around this issue is simply having the audio bypass OBS, and if I need a couple frames extra latency I am totally able to do that to the input before it even gets to OBS. To me, the more-easily-described issue here is that the monitor feature only sort of works as a monitor: due to increasing latency over time, eventually the monitor stops monitoring and you have to turn it off and turn it back on.

Like, I totally appreciate the argument "the current feature works for a while and making it lower latency would potentially be really hard" but you seem to be mixing up that argument with "you want the monitor tied to the output and that would make it a worse monitor"... I honestly don't actually think most of the people hoping for this to be improved are really needing that kind of a change even if it sounds like they want that and what they are actually running into is that the monitor isn't serving as a monitor: if OBS made it a perfect "monitor" (leaning into the former use case you describe), that would, as far as I know, satisfy these users.

**Comment by PatTheMav** [comment] 2023-02-06 19:53
Sorry if I wasn't clear enough:

I agree that the current system serves _neither_ purpose. And personally I'd expect a monitoring(!) system not to serve as an actual output and instead a bespoke post-fader output system to serve the needs of a "local master output".

Still, the system works _as implemented_ - not working as some users expect it to is not a "bug" (which would mean "software doesn't do what was implemented"). In some cases we chose to keep a GitHub issue even though it's not technically a bug (and instead a feature request) for transparency reasons and as motivation for possible contributors to implement a feature, in which case a single open issue is sufficient (we don't need to keep duplicates open).

So: Yes, it doesn't work as people expect it to, the expectations are valid, we need contributors to change/implement it that way, PRs welcome.
