### ISSUE TITLE
Browser Source ignores video autoplay unless interacted with

### ISSUE THREAD

**Issue by MadWolfDynamite** [obsproject/obs-studio#4444] opened 2021-04-03 09:36 UTC
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/LWWCcT-OjjcB0dmh

### Expected Behavior

When browser source is active any video tags with autoplay attribute will playback

### Current Behavior

Video appears paused until source is manually interacted with via the means of interact popup. Even then, mouse has to be constantly moved to properly show playback

### Steps to Reproduce

1. Create a html page with <Video> tag that includes "autoplay muted" attributes
2. Add browser source linking to html page to any scene
3. Select browser source and clink on "Interact"
4. Move cursor back and forth within the window that appears
4a. Open html file in any web browser compatible with <video> tag

### Anything else we should know?

This was only tested with a local file, but URLs may also be affected by this

**Comment by dodgepong** [comment] 2021-04-03 15:00
Out of curiosity, why are you playing a video with the browser source instead of a media source?

**Comment by MadWolfDynamite** [comment] 2021-04-03 16:42
> Out of curiosity, why are you playing a video with the browser source instead of a media source?

The media source only allows the playback for a single video file. Likewise as I do not have VLC installed I cannot use the playlist capabilities of the VLC video source so using a browser source was a workaround for this.

**Comment by RytoEX** [comment] 2021-04-03 16:48
This is a duplicate of https://github.com/obsproject/obs-browser/issues/182 and this belongs in the obs-browser repo.  I'm going to close this as a duplicate and move it there.

**Closed by RytoEX** 2021-04-03 16:48 UTC
