### ISSUE TITLE
OBS Studio drops frames with sane cache sizes in Linux while transferring files

### ISSUE THREAD

**Issue by RomuloPBenedetti** [obsproject/obs-studio#4403] opened 2021-03-28 22:59 UTC
### Operating System Info

Other

### Other OS

Fedora 33

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/6INKedhgl0sVyj4Z

### Expected Behavior

No frames drops or at last a sane amount of frames drop, at last, if saving to a dedicated device that is not being the origin or destiny of the file transference. 

### Current Behavior

While transferring a file of ~ 5 GB for example to home partition, OBS heavily drops frames if for some reason your system use sane cache sizes like for example:

    dirty_background_ratio = 128MB
    dirty_bytes = 256 MB

It happens even if I'm recording to a dedicated disk that is not receiving any IO apart from OBS.

### Steps to Reproduce

1. Set Kernel dirty settings:
    echo $((128*1024*1024)) > /proc/sys/vm/dirty_bytes && echo $((256*1024*1024)) > /proc/sys/vm/dirty_background_bytes
2. Start recording.
3. At some moment start to transfer a big file to /home/user
4. Use a browser, do some usage while file transfer.
5. Wait or interrupt the transfer.
4. interrupt record and go check.

### Anything else we should know?

Currently majority of distros use insane global cache sizes that can amount to 3GB+, this has its own sort of bad effects, like huge queues for slow devices like USB flash drives dominating the cache. Apart from OBS and Chrome I've not noticed any other app disturbance. Opened an issue in Chrome too:

https://bugs.chromium.org/p/chromium/issues/detail?id=1193262

Others app may be sensitive too? Maybe OBS use of `fsync` or `fflush` may be responsible?

**Comment by kkartaltepe** [comment] 2021-03-29 01:49
OBS does not issue any fsyncs during recording. The issue is most likely that you have set such "sane" buffering limits that your device is forced to sync excessively, while trying to flush buffers OBS (and other programs) will block on writes because you have limited the number of dirty bytes. Once OBS gets stalled long enough it will drop these frames because the device is not able to keep up.

If you find this works fine with your distributions "insane" buffering limits you can confirm that your device is able to achieve the required bandwidth given optimal enough IO scheduling allowed by increased buffer limits.

**Comment by kkartaltepe** [comment] 2021-03-29 05:35
Ill reopen this as right now OBS is pretty sensitive to any stalls greater than 1-2 frames in the muxing process and we can improve this as flushing can easily take longer than this.

**Comment by RomuloPBenedetti** [comment] 2021-03-29 21:50
It is not just me, Linus some time ago stated that the way Linux 64 bits decide the amount of dirty pages is insane, and it makes sense knowing how dumbly page-cache deals with it, even bigger dirty values will trigger it, it is just a matter to transferring a big enough file to a slow enough device until you deplete dirty page limits for all programs there.
 
Anyay I was just guessing, I don't know the internals of OBS, was trying to help figure any possible cause. For any chance OBS have a userspace cache? It can help as I guess even non blocking writes could help if something dominates page cache.

**Comment by kkartaltepe** [comment] 2021-03-29 22:36
user space caches make it harder for the linux page cache to make a good choice and increase queuing effects on backpressure which we do want if your device is not fast enough. Im not sure i've ever seen any cache sizing recommendations similar to yours for any workloads, but I dont often tune the vm subsystem.

But in this case we drop frames perhaps too agressively and cannot control the blocking behavior of the underlying muxers so a deeper cache is the only choice

**Comment by RomuloPBenedetti** [comment] 2021-03-30 03:56
Linus stated [this](https://lwn.net/Articles/572921/) in the kernel mailing list. The defaults today are not a problem in a system with homogeneous IO speed and reasonable IO pressure, but I agree with him, it gets a bit crazy on desktops with slow devices like a pendrives. 

My point with a user space cache was something small to allow not dropping maybe half a second or a second of record.

**Comment by RytoEX** [comment] 2022-11-09 21:46
We think this is fixed as of OBS Studio 28. Please retest in OBS Studio 28.1.2 (or newer) and confirm if this is resolved or if this is still an issue. If this is still an issue, please provide a new log file and new Steps To Reproduce.

**Comment by gxalpha** [comment] 2023-01-12 14:11
As mentioned, we think this is fixed. If it still happens in OBS 29, please open a new issue as described on the above comment.

**Closed by gxalpha** 2023-01-12 14:11 UTC
Labels: Linux, Confirmed
