### ISSUE TITLE
Audio is not send after recconection with server.

### ISSUE THREAD

**Issue by Sztacho** [obsproject/obs-studio#6813] opened 2022-07-25 21:20 UTC
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/qGkBxLNTDtIbTtpQ

### Expected Behavior

After reconnect with twitch I want to audio should be sending.

### Current Behavior

After reconnect with twitch the audio are not sending. 

### Steps to Reproduce

1. Lost connecting with twitch
2. Reconnect success
3. And now audio is not sended.

**Comment by RytoEX** [comment] 2022-07-25 21:21
Duplicate of #5572

**Closed by RytoEX** 2022-07-25 21:21 UTC
