### ISSUE TITLE
Distorted monitor capture bug

### ISSUE THREAD

**Issue by JordanPlayz158** [obsproject/obs-studio#6944] opened 2022-08-04 16:11 UTC
### Operating System Info

Other

### Other OS

Manjaro GNOME 42.3 Wayland 5.15.55-1

### OBS Studio Version

Other

### OBS Studio Version (Other)

I tested on both the pre-release (28.0.0-beta1) and stable (27.2.4) to see if it had been fixed and it has not

### OBS Studio Log URL

https://obsproject.com/logs/M8rdWLdLnwfmT1X2

### Expected Behavior

The monitor's image should not be distorted and should show the correct image.

### Current Behavior

There is a bug either in obs, maybe wayland or pipewire that distorts the image of the monitor, I don't believe this is an issue with wayland or pipewire as my screenshotting tool flameshot gets the screenshots sent to it through wayland and pipewire just fine and things like discord can live stream my screen without distortion.

### Steps to Reproduce

1. Open up OBS
2. Select the primary monitor you use for monitor capture
3. It should be distorted (don't know if this can be reproduced reliably though as I don't have multiple different monitors to test)

### Anything else we should know?

I have added one line to my grub config to add the 75Hz option for 1680x1050 to my monitor that is glitching with `video=DP-1:1680x1050@75` although I tested with 60Hz which is what it detects by default and it still glitches so I don't believe this is the root of the problem.

Video of issue: https://streamable.com/rjo4xv

This seems similar to #6408 but I am not using multiple GPUs

Neofetch:
```
██████████████████  ████████   jordan@Jordan-PC 
██████████████████  ████████   ---------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: MS-7A34 2.0 
████████            ████████   Kernel: 5.15.55-1-MANJARO 
████████  ████████  ████████   Uptime: 8 days, 15 hours, 30 mins 
████████  ████████  ████████   Packages: 1664 (pacman), 42 (flatpak) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 1680x1050 
████████  ████████  ████████   DE: GNOME 42.3.1 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita 
████████  ████████  ████████   Theme: Adwaita-dark [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
                               GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X 
                               Memory: 16558MiB / 32052MiB 
```

**Comment by kkartaltepe** [comment] 2022-08-04 16:16
Duplicate of #4961

**Closed by kkartaltepe** 2022-08-04 16:16 UTC

**Comment by JordanPlayz158** [comment] 2022-08-05 04:37
Oh, I see, sorry about that, the multiple GPU thing through me off (when checking the duplicate on the one I linked) and think my issue might've been different. Thanks for clearing this up.
