### ISSUE TITLE
Media Source renders portrait video in incorrect orientation

### ISSUE THREAD

**Issue by pmcgaley** [obsproject/obs-studio#5251] opened 2021-09-07 10:19 UTC
### Operating System Info

Windows 10

### Other OS

Also macOS 11.5.2 on M1

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/iMtIcCPaUcbCFDtI

### Expected Behavior

Portrait video from phone (mov/mp4 containing h.264/AVC and h.265/HEVC) should be rendered correctly in Media Source.

### Current Behavior

Media source appears to ignore `rotation` metadata and renders the video sideways.

### Steps to Reproduce

1. Add Media Source.
2. Select the attached video as source.
3. Observe incorrect orientation.

https://user-images.githubusercontent.com/18594548/132258725-4ef35599-fab2-44c3-8262-60d5914ea876.MOV

![image](https://user-images.githubusercontent.com/18594548/132258756-ea96e622-1874-4f98-878c-e4c8928975c3.png)

### Anything else we should know?

Metadata in the affected videos specifies `rotation` of `90` or `270`.

**Comment by WizardCM** [comment] 2021-09-07 10:28
Duplicate of #5250

**Closed by WizardCM** 2021-09-07 10:28 UTC

**Comment by pmcgaley** [comment] 2021-09-07 10:31
I had a quick look at the code and I don't think this is a duplicate, hence splitting it. Do you think it's the same underlying problem?

**Comment by pmcgaley** [comment] 2021-09-07 10:40
@WizardCM in particular, I'm guessing #5250 can be fixed with a change to VLC Video source by swapping the height and width when `rotation` is `90` or `270`, but that won't do anything for Media Source.
